### ISSUE TITLE
how to set server variable in sub vcl_recv()

### ISSUE THREAD

**Issue by dbsdsun** [varnishcache/varnish-cache#1]
I need to set $_SERVER['MAGE_RUN_CODE'] in varnish vcl_recv() for php code.
is it possible?
Thanks,
Wilson

**Comment by lkarsten** [comment]
Hi.

Please use the varnish-misc@ email list for support inquiries. Details on https://www.varnish-cache.org/ .

**Comment by bsdphk** [comment]
If you are looking for the very first bugreport against the varnish-cache, it was filed in Trac and
is archived here:  https://varnish-cache.org/trac/ticket/1
