### ISSUE TITLE
improve solaris least privileges & workdir permissions

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1676]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1676

**Comment by bsdphk** [comment]
It this ticket still relevant ?

**Comment by nigoroll** [comment]
we don't need a ticket, I know that I have to work on this anyway

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport. If this is fixed, @nigoroll can decide if he wants to backport it.
