### ISSUE TITLE
Fail more gracefully on -l >= 4GB

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1750]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1750

**Comment by nigoroll** [comment]
@mbgrydeland you owned this in trac, do you want to work on it?

**Comment by slimhazard** [comment]
This issue started a discussion recently about whether the size of an index into VSM can/should be larger than uint32, which of course would be a far-reaching undertaking.

That would take it much further afield than I intended in the original trac issue -- the point I wanted to emphasize was graceful failure. When -l > 4GB, there's no error message from the varnishd command, no panic message, nothing for diagnosis at all except for a syslog message saying that varnishd died, with no further explanation.

I know Varnish well enough that I could surmise what happened, but a less experienced user could have been completely mystified.

Whatever is ultimately decided about the size of VSM, it would go a long way (and would be quite simple) just to examine any -l argument after parsing argv, and fprintf a diagnostic to stderr if it exceeds the maximum.

**Comment by hermunn** [comment]
Backport review: The commit ec59b44 has been backported as 95100cd02cf54.

**Comment by Dridi** [comment]
This commit has been partially reverted, or reverted as part of another change!

**Comment by Dridi** [comment]
See 452ac52
