### ISSUE TITLE
Open ended range request results in truncated images

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1758]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1758

**Comment by lkarsten** [comment]
Backport review: related to the incorrect Range handling. Fixed in master pre-dating 4.1 release.

Big and most likely slightly breaking change for 4.0. I believe we already did it for VCP.

Not marking for 4.0 backport as upgrade to 4.1 is the better choice for anyone running into this.
