### ISSUE TITLE
VMOD abi check is always lenient

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1759]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1759

**Comment by lkarsten** [comment]
Discussed on bugwash today. 

Poul-Henning hasn't got the time and wants to go back to hard gitref checks at load time. This would make the life of everyone not running from source quite a bit harder.

The current check isn't perfect, but if the alternative is moving away from having a Varnish that can use packaged vmods, I'm all for keeping it.

Closing as wontfix.

**Comment by hermunn** [comment]
Backport review: Closed at wontfix.
