### ISSUE TITLE
External VDP filters can't change resp_len on cached objects

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1771]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1771

**Comment by bsdphk** [comment]
I'm moving this one to VIP14:

https://github.com/varnishcache/varnish-cache/wiki/VIP14%3A-%2A.body-access

**Comment by hermunn** [comment]
Backport review: Moved to VIP - nothing to backport.
