### ISSUE TITLE
Range requests problem

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1777]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1777

**Comment by lkarsten** [comment]
Backport review: Fixed in 4.1.0-beta1.

Needs 4.0 review.

**Comment by kanongil** [comment]
I'm investigating an issue regarding the fix for this in 121593312daabbef4e290a590b364a099980a8b7. The trac link is however broken, so I'm missing context. Is it possible to access somehow?

**Comment by kanongil** [comment]
Nvm, found it here: https://web.archive.org/web/20160809133121/https://varnish-cache.org/trac/ticket/1777
