### ISSUE TITLE
PRIV_TASK in a vmod object method leads to code that cannot be compiled/linked

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1800]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1800

**Comment by nigoroll** [comment]
pinging participants of the trac ticket: @slimhazard @aondio @fgsch @daghf : #2061 should fix this for master

**Comment by hermunn** [comment]
backport review: See #2061
