### ISSUE TITLE
Varnish crashes when a PRIV_TASK/PRIV_TOP function is invoked from vcl_init

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1811]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1811

**Comment by lkarsten** [comment]
Discussed this a bit with Martin.

In the original ticket Dag mentioned that we could teach the VCL compiler not to allow functions with PRIV_TASK arguments in init/fini.

Martin makes the point that we have other situations like this, and putting this magic into the VCL compiler may be not the best way. We could extend the vmod.vcc format so it details in which vcl functions each function can be called.

I don't have a clear view of what the best solution is, the 1851ae9 commit makes is more clear, but I'm sure there are situations not covered by it. Leaving this open until we come up with a bright idea or time it out.

**Comment by gquintard** [comment]
related to https://github.com/varnishcache/varnish-cache/wiki/VIP4:-Restrict-VMOD-function-call-sites

**Comment by fgsch** [comment]
IMO this should be done in the VCL compiler regardless of whether is PRIV_TASK/TOP or some artificil limitation (e.g. user restricting a particular function to a particular vcl subroutine) to keep things performant, whether the source is vmod.vcc or hardcoded.

For PRIV_TASK/TOP this won't change no matter what anyway.

**Comment by bsdphk** [comment]
Overtaken By Events

**Comment by nigoroll** [comment]
Ref: #2061

**Comment by hermunn** [comment]
Backport review: As @nigoroll points out, this is changed / solved in master now, and if this is backported, it will be tracked in other tickets.
