### ISSUE TITLE
Child died on pipe request

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1815]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1815

**Comment by Dridi** [comment]
I pushed a fix that does not send a 503 as decided during the bugwash. None of the pipe code fails with a synthetic 503 (probably related to #1890), the connection is simply closed.

In order to avoid a disruptive change on a maintenance branch I just pushed 62b5e3f that has been sitting in my workspace since February.

**Comment by Dridi** [comment]
Discussed with @fgsch, master closes the session with TX_ERROR in master, but I close them with OVERLOAD in my patch. My rationale is that this case can be triggered when a director runs out of healthy backends.

IRC logs:

> 16:37 < fgs> dridi: I think that commit to 4.0 should not use OVERLOAD
16:37 < fgs> but SC_TX_ERROR
16:38 < fgs> (as we do in master)
16:40 < dridi> fgs: looking up the meaning of TX_ERROR
16:43 < dridi> however I'm not sure about TX_ERROR, it looks like a catch-all reason
16:44 < dridi> OVERLOAD means that we ran out of some resource, which may happen for a director when all backends become sick
16:44 < dridi> so we effectively ran out of backend
16:45 < fgs> I'm not sure if backends are considered a resource
16:46 < fgs> And I'd prefer if we are inline with master (or master is inline with 4.[01])

I agree that being consistent across branches would be better, which one should we pick?

**Comment by mbgrydeland** [comment]
To me OVERLOAD sounds like an overload of Varnish' internal resources, not an external one like a backend is. So my vote goes to ERROR.

**Comment by lkarsten** [comment]
Backport review: this does not apply to 4.1. The passing r01730.vtc test case covers it.
