### ISSUE TITLE
random Panic's at recent master

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1831]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1831

**Comment by bsdphk** [comment]
I have not been able to figure this one out yet, but now I have added some more debugging to the panic output in case it happens again.

**Comment by nigoroll** [comment]
@bsdphk I think with the changes to ws management in the delivery pipeline we should consider closing this one.

**Comment by fgsch** [comment]
@nigoroll agreed. Probabaly OBE.

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
