### ISSUE TITLE
varnishlog assert in vslc_vtx_next

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1846]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1846

**Comment by nigoroll** [comment]
@mbgrydeland I suspect this is a vsm overrun which happens while we look at the vtx. If this is true, I think we should not try to address this, the vsm handling will always be optimistic as long as we dont want to block the writer (varnishd) and huge amounts written to a small segment will always remain problematic.

**Comment by nigoroll** [comment]
I have addressed an overrun issue in f91c6f9025bd2f8faf0e45542e21a4119f33c7c2, but I still think we should not attempt to fix this. Anyone with high vsm traffic should use a log of appropriate size.

**Comment by lkarsten** [comment]
Related: #1873

**Comment by lkarsten** [comment]
Backport review: Fix to #1873 pushed to 4.1head now, which should cover it.

Remains: Review for 4.0.
