### ISSUE TITLE
LostHeader setting req.url to an empty string

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1856]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1856

**Comment by nigoroll** [comment]
We got the same issue with `http_max_hdr` exceeded, so I created https://github.com/varnishcache/varnish-cache/wiki/VIP10-Differentiate-out-%22out-of-workspace%22-errors
@bsdphk @fgsch I could be a good idea to document there the plan you have agreed upon

**Comment by fgsch** [comment]
I don't quite see the point of creating a VIP for something that is already agreed on but OK.

**Comment by nigoroll** [comment]
@fgsch did you notice the fact that there is another aspect too it which we had missed so far? My understanding is that the VIPs are our preferred place for collecting design specs.

**Comment by fgsch** [comment]
As I said, if you want to have a VIP for it, sure. I don't think there is any spec to design though, just sit down and write the code.
