### ISSUE TITLE
Stale hit-for-pass objects generating 200 responses with missing content

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1858]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1858

**Comment by lkarsten** [comment]
backport review: this is in 4.1.2-beta2.

**Comment by slimhazard** [comment]
Sorry, shouldn't have reopened this, I thought that the fix had a mistake, but have decided that I was wrong about that.
