### ISSUE TITLE
[4.0] Request URL with whitespace is allowed

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1862]
Old ticket imported from Trac
See archived copy here: https://varnish-cache.org/trac/ticket/1862

**Comment by Dridi** [comment]
Ack'ed by @bsdphk.

**Comment by lkarsten** [comment]
Backport review: this is commited (but not released) in 4.0. Trusting Federico's comment that it does not apply to 4.1 or master.
