### ISSUE TITLE
Issue with enabling Inline C support

### ISSUE THREAD

**Issue by lijucorra** [varnishcache/varnish-cache#1867]
Hi,

I am setting up a Varnish server with version varnish-4.1.1.

[root@joma-stage-varnish ~]# rpm -qa | grep varnish
varnish-4.1.1-2.el6.x86_64
varnish-release-4.1-2.el6.noarch
varnish-libs-4.1.1-2.el6.x86_64
varnish-libs-devel-4.1.1-2.el6.x86_64

and enabled inline-C support.

But compiling VCL getting failed with following error message,

========================================
~]# varnishd -C -f /etc/varnish/default.vcl.turp
Error:
Message from VCC-compiler:
Inline-C not allowed
('/etc/varnish/default.vcl.turp' Line 2 Pos 1)
C{
##

Running VCC-compiler failed, exited with 2
VCL compilation failed
========================================

Complete file content and other details are in URL https://gist.github.com/lijucorra/8f83973f0d216d2e213c

Please help

**Comment by fgsch** [comment]
That would fail because the vcc_allow_inline_c is off.

What about `varnishd -pvcc_allow_inline_c=true -C -f /etc/varnish/default.vcl.turp`?

**Comment by lijucorra** [comment]
Output:

~]# varnishd -pvcc_allow_inline_c=true -C -f /etc/varnish/default.vcl.turp
Error:
Message from VCC-compiler:

directors are now in directors VMOD.
('/etc/varnish/default.vcl.turp' Line 27 Pos 1)
director default round-robin {
########----------------------

Running VCC-compiler failed, exited with 2
VCL compilation failed

**Comment by lijucorra** [comment]
The parameter vcc_allow_inline_c is already enabled on server,

~]# varnishadm param.show | grep vcc_allow_inline_c
vcc_allow_inline_c         on [bool]

**Comment by fgsch** [comment]
You are running a new varnishd instance.  The parameter is set for the varnishd that is already running, not the new one.

For the other error you need to update your VCL.

**Comment by lijucorra** [comment]
I do not fully understand your last reply.

Can you please elaborate on how I can fix this?

**Comment by lkarsten** [comment]
@lijucorra Please use the varnish-misc@ email list or the irc channels for further help on this.

There is nothing here that indicates (for me) that this is a Varnish bug or issue. Closing.
