### ISSUE TITLE
Apache format logs generated by 'varnishncsa' do not escape quotes

### ISSUE THREAD

**Issue by dannygonzalez** [varnishcache/varnish-cache#1868]
The Apache format logs that are generated by running the varnishncsa tool do not escape quotes.
Apache [specifies](http://httpd.apache.org/docs/2.2/mod/mod_log_config.html) that "Literal quotes and backslashes should be escaped with backslashes".

This causes issues when trying to parse these logs to extract the fields from the log line.

Take a look at the user agent field "echo crawl 2.0" in the following two examples.

Here is the varnishncsa output:
`127.0.0.1 - - [07/Mar/2016:10:59:36 +0000] "GET http://localhost:6081/hello HTTP/1.1" 503 417 "-" ""echocrawl 2.0""`

Here is the Apache output:
`- - [07/Mar/2016:13:20:15 +0000] "GET /hello HTTP/1.1" 404 203 "-" "\"echocrawl 2.0\""`

**Comment by scoof** [comment]
Which version?
4.1.1 seems to work just fine:
::1 - - [07/Mar/2016:21:40:04 +0100] "GET http://localhost:6081/\" HTTP/1.1" 404 281 "-" "\""

**Comment by dannygonzalez** [comment]
Looks like I may have been using an older version 3.0.5-2.
I installed it from Linux Mint 17.2 Software Manager.
I have installed the latest version and it does indeed seem to fix this issue.

Could you let me know what version this bug was fixed in?

Thanks

**Comment by fgsch** [comment]
This was already reported in #1378 and fixed in d68863d0d983685a286347824046f791bba58c55.
First appeared in 4.0.3.
