### ISSUE TITLE
std.cache_req_body() w/ return(pipe) is broken

### ISSUE THREAD

**Issue by daghf** [varnishcache/varnish-cache#1881]
## Expected Behavior
Varnish should pass the cached request body also in the event that the request was piped.

## Current Behavior
The request body is drained when we do std.cache_req_body(), and since the busyobj for a piped request does not have a bo->req pointer set, it will not be able to recover the cached body.

## Steps to Reproduce
The following test case fails after a timeout since the backend expects a request body that is never transmitted.

<pre>
varnishtest "cache_req_body + pipe does not play well"

server s1 {
	rxreq
	expect req.bodylen == 6
	expect req.http.foo == "true"
	txresp
} -start

varnish v1 -vcl+backend {
	import std;

	sub vcl_recv {
		set req.http.foo = std.cache_req_body(10KB);
		return (pipe);
	}
} -start

varnish v1 -cliok "param.set debug +syncvsl"

client c1 {
	txreq -body "foobar"
	rxresp
	expect resp.status == 200
} -run
</pre>

## Your Environment
* Version used: master

**Comment by fgsch** [comment]
This fixes it. Haven't looked at the implications of this change though.
```
diff --git a/bin/varnishd/cache/cache_req_fsm.c b/bin/varnishd/cache/cache_req_fsm.c
index a2d830c..2caa021 100644
--- a/bin/varnishd/cache/cache_req_fsm.c
+++ b/bin/varnishd/cache/cache_req_fsm.c
@@ -559,6 +559,11 @@ cnt_pipe(struct worker *wrk, struct req *req)
        VSLb(req->vsl, SLT_Link, "bereq %u pipe", VXID(bo->vsl->wid));
        THR_SetBusyobj(bo);
 
+       AZ(bo->req);
+       AZ(bo->wrk);
+       bo->req = req;
+       bo->wrk = wrk;
+
        HTTP_Setup(bo->bereq, bo->ws, bo->vsl, SLT_BereqMethod);
        http_FilterReq(bo->bereq, req->http, 0);        // XXX: 0 ?
        http_PrintfHeader(bo->bereq, "X-Varnish: %u", VXID(req->vsl->wid));
```
