### ISSUE TITLE
Broken parsing of $Method lines by vmodtool

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#1885]
The `vmodtool` expects method names to start with a dot and will generate a hybrid function signature if the dot is missing. It looks as if it were a `$Function` but it expects the `$Object`'s struct as the first parameter (after `ctx`).

Example:

```
$Object foo()
$Method VOID .bar(STRING)
$Method VOID baz(STRING)
```

## Expected Behavior

The `vmodtool` should err on `baz` or issue a warning and assume `.baz` instead. Ultimately, a correct `$Method` declaration should lead to the following interface:

```
/*
 * NB:  This file is machine generated, DO NOT EDIT!
 *
 * Edit vmod.vcc and run make instead
 */

struct vmod_priv;

/* Object foo */
struct vmod_broken_foo;
VCL_VOID vmod_foo__init(VRT_CTX, struct vmod_broken_foo **, const char *);
VCL_VOID vmod_foo__fini(struct vmod_broken_foo **);
VCL_VOID vmod_foo_bar(VRT_CTX, struct vmod_broken_foo *, VCL_STRING);
VCL_VOID vmod_foo_baz(VRT_CTX, struct vmod_broken_foo *, VCL_STRING);
```

## Current Behavior

The `vmodtool` creates the following signature for baz:

`VCL_VOID vmod_baz(VRT_CTX, struct vmod_broken_foo *, VCL_STRING);`

It does not belong to the `vmod_foo` namespace but takes a `foo` object, which I don't think has a proper type in VCL that can be passed around.

The following VCL snippet fails to compile:

```
sub vcl_init {
    new f = broken.foo();
    foo.baz("test");
}
```

I haven't tried this:

```
sub vcl_init {
    new f = broken.foo();
    broken.baz(foo, "test");
}
```

## Possible Solution

Make the parser strict?

## Steps to Reproduce (for bugs)

Write a VMOD, so it's probably easier to do it in `vmod_debug`.

## Context

I lost 5 minutes wondering why a change I was doing didn't work =)

It might be worth checking that a `$Function` whose name starts with a dot that is declared after an `$Object` doesn't end up in the object's namespace...

## Your Environment
* Version used: Varnish 4.1.2 (installed from source)
* Operating System and version: Fedora 23

**Comment by fgsch** [comment]
+1 error on baz.

**Comment by bsdphk** [comment]
It should issue an error.

**Comment by lkarsten** [comment]
Backported to 4.1 now. Not important enough to be applied to 4.0.
