### ISSUE TITLE
numerous "option 'subdir-objects' is disabled" warnings on exec of 'autogen.sh (automake)'

### ISSUE THREAD

**Issue by pgnd** [varnishcache/varnish-cache#1887]
Building varnish-git 4.1 branch on linux/64

    git clone https://github.com/varnishcache/varnish-cache.git
    cd varnish-cache
    git checkout 4.1
    git log | head
        commit 7d4febdbb540f7e83b077b2e42bd3a4f5eeed46c
        Author: Dridi Boukelmoune <dridi.boukelmoune@gmail.com>
        Date:   Fri Mar 18 11:57:58 2016 +0100

            Add a miniobj macro for taking over pointer

            There's a recurring pattern throughout the code base of taking over
            a reference (by nulling the original) essentially when resources are
            freed. Instead of repeating this anti dangling pointers measure, it
            can be wrapped in a documenting utility macro.

exec of autogen generates quite a few 'automake' wrnings, apparently non-fatal

    ./autogen.sh
        + libtoolize --copy --force
        libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
        libtoolize: copying file 'build-aux/ltmain.sh'
        libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
        libtoolize: copying file 'm4/libtool.m4'
        libtoolize: copying file 'm4/ltoptions.m4'
        libtoolize: copying file 'm4/ltsugar.m4'
        libtoolize: copying file 'm4/ltversion.m4'
        libtoolize: copying file 'm4/lt~obsolete.m4'
        + aclocal -I m4
        + autoheader
        + automake --add-missing --copy --foreign
        configure.ac:10: installing 'build-aux/compile'
        configure.ac:15: installing 'build-aux/config.guess'
        configure.ac:15: installing 'build-aux/config.sub'
        configure.ac:19: installing 'build-aux/install-sh'
        configure.ac:19: installing 'build-aux/missing'
        bin/varnishadm/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vas.c' is in a subdirectory,
        bin/varnishadm/Makefile.am:9: but option 'subdir-objects' is disabled
        automake: warning: possible forward-incompatibility.
        automake: At least a source file is in a subdirectory, but the 'subdir-objects'
        automake: automake option hasn't been enabled.  For now, the corresponding output
        automake: object file(s) will be placed in the top-level directory.  However,
        automake: this behaviour will change in future Automake versions: they will
        automake: unconditionally cause object files to be placed in the same subdirectory
        automake: of the corresponding sources.
        automake: You are advised to start using 'subdir-objects' option throughout your
        automake: project, to avoid future incompatibilities.
        bin/varnishadm/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vsa.c' is in a subdirectory,
        bin/varnishadm/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishadm/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vtcp.c' is in a subdirectory,
        bin/varnishadm/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishadm/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vss.c' is in a subdirectory,
        bin/varnishadm/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishadm/Makefile.am: installing 'build-aux/depcomp'
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_acceptor.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_backend.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_backend_cfg.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_backend_probe.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_backend_tcp.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_ban.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_ban_build.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_ban_lurker.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_busyobj.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_cli.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_deliver_proc.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_director.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_esi_deliver.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_esi_fetch.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_esi_parse.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_expire.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_fetch.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_fetch_proc.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_gzip.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_hash.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_http.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_lck.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_main.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_mempool.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_obj.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_panic.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_pool.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_req.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_req_body.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_req_fsm.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_rfc2616.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_range.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_session.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_shmlog.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_vary.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_vcl.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_vrt.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_vrt_priv.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_vrt_re.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_vrt_var.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_vrt_vmod.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_wrk.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'cache/cache_ws.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'common/common_vsm.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'common/common_vsc.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'hash/hash_classic.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'hash/hash_critbit.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'hash/mgt_hash.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'hash/hash_simple_list.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'http1/cache_http1_deliver.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'http1/cache_http1_fetch.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'http1/cache_http1_fsm.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'http1/cache_http1_line.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'http1/cache_http1_pipe.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'http1/cache_http1_proto.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'http1/cache_http1_vfp.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_acceptor.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_child.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_cli.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_jail.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_jail_unix.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_jail_solaris.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_main.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_param.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_param_tbl.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_param_bits.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_param_tcp.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_param_tweak.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_pool.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_shmem.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_vcc.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'mgt/mgt_vcl.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'proxy/cache_proxy_proto.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'storage/stevedore.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'storage/mgt_stevedore.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'storage/stevedore_utils.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'storage/storage_file.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'storage/storage_malloc.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'storage/storage_persistent.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'storage/mgt_storage_persistent.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'storage/storage_persistent_silo.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'storage/storage_persistent_subr.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'storage/storage_umem.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'waiter/mgt_waiter.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'waiter/cache_waiter.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'waiter/cache_waiter_epoll.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'waiter/cache_waiter_kqueue.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'waiter/cache_waiter_poll.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishd/Makefile.am:11: warning: source file 'waiter/cache_waiter_ports.c' is in a subdirectory,
        bin/varnishd/Makefile.am:11: but option 'subdir-objects' is disabled
        bin/varnishhist/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vas.c' is in a subdirectory,
        bin/varnishhist/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishhist/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/version.c' is in a subdirectory,
        bin/varnishhist/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishhist/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vpf.c' is in a subdirectory,
        bin/varnishhist/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishhist/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vtim.c' is in a subdirectory,
        bin/varnishhist/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishhist/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/flopen.c' is in a subdirectory,
        bin/varnishhist/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishhist/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnishtools/vut.c' is in a subdirectory,
        bin/varnishhist/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishhist/Makefile.am:26: warning: source file '$(top_srcdir)/lib/libvarnishtools/opt2rst.c' is in a subdirectory,
        bin/varnishhist/Makefile.am:26: but option 'subdir-objects' is disabled
        bin/varnishlog/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnishtools/vut.c' is in a subdirectory,
        bin/varnishlog/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishlog/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vas.c' is in a subdirectory,
        bin/varnishlog/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishlog/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/flopen.c' is in a subdirectory,
        bin/varnishlog/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishlog/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/version.c' is in a subdirectory,
        bin/varnishlog/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishlog/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vsb.c' is in a subdirectory,
        bin/varnishlog/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishlog/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vpf.c' is in a subdirectory,
        bin/varnishlog/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishlog/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vtim.c' is in a subdirectory,
        bin/varnishlog/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishlog/Makefile.am:27: warning: source file '$(top_srcdir)/lib/libvarnishtools/opt2rst.c' is in a subdirectory,
        bin/varnishlog/Makefile.am:27: but option 'subdir-objects' is disabled
        bin/varnishncsa/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnishtools/vut.c' is in a subdirectory,
        bin/varnishncsa/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishncsa/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vas.c' is in a subdirectory,
        bin/varnishncsa/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishncsa/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/flopen.c' is in a subdirectory,
        bin/varnishncsa/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishncsa/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/version.c' is in a subdirectory,
        bin/varnishncsa/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishncsa/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vpf.c' is in a subdirectory,
        bin/varnishncsa/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishncsa/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vtim.c' is in a subdirectory,
        bin/varnishncsa/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishncsa/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vsb.c' is in a subdirectory,
        bin/varnishncsa/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishncsa/Makefile.am:29: warning: source file '$(top_srcdir)/lib/libvarnishtools/opt2rst.c' is in a subdirectory,
        bin/varnishncsa/Makefile.am:29: but option 'subdir-objects' is disabled
        bin/varnishstat/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vas.c' is in a subdirectory,
        bin/varnishstat/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishstat/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/version.c' is in a subdirectory,
        bin/varnishstat/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishstat/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vtim.c' is in a subdirectory,
        bin/varnishstat/Makefile.am:9: but option 'subdir-objects' is disabled
        parallel-tests: installing 'build-aux/test-driver'
        bin/varnishtop/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnishtools/vut.c' is in a subdirectory,
        bin/varnishtop/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishtop/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vas.c' is in a subdirectory,
        bin/varnishtop/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishtop/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/flopen.c' is in a subdirectory,
        bin/varnishtop/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishtop/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/version.c' is in a subdirectory,
        bin/varnishtop/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishtop/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vpf.c' is in a subdirectory,
        bin/varnishtop/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishtop/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vtim.c' is in a subdirectory,
        bin/varnishtop/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishtop/Makefile.am:9: warning: source file '$(top_srcdir)/lib/libvarnish/vsb.c' is in a subdirectory,
        bin/varnishtop/Makefile.am:9: but option 'subdir-objects' is disabled
        bin/varnishtop/Makefile.am:27: warning: source file '$(top_srcdir)/lib/libvarnishtools/opt2rst.c' is in a subdirectory,
        bin/varnishtop/Makefile.am:27: but option 'subdir-objects' is disabled
        lib/libvarnishapi/Makefile.am:14: warning: source file '../libvarnish/vas.c' is in a subdirectory,
        lib/libvarnishapi/Makefile.am:14: but option 'subdir-objects' is disabled
        lib/libvarnishapi/Makefile.am:14: warning: source file '../libvarnish/vav.c' is in a subdirectory,
        lib/libvarnishapi/Makefile.am:14: but option 'subdir-objects' is disabled
        lib/libvarnishapi/Makefile.am:14: warning: source file '../libvarnish/version.c' is in a subdirectory,
        lib/libvarnishapi/Makefile.am:14: but option 'subdir-objects' is disabled
        lib/libvarnishapi/Makefile.am:14: warning: source file '../libvarnish/cli_common.c' is in a subdirectory,
        lib/libvarnishapi/Makefile.am:14: but option 'subdir-objects' is disabled
        lib/libvarnishapi/Makefile.am:14: warning: source file '../libvarnish/cli_auth.c' is in a subdirectory,
        lib/libvarnishapi/Makefile.am:14: but option 'subdir-objects' is disabled
        lib/libvarnishapi/Makefile.am:14: warning: source file '../libvarnish/vin.c' is in a subdirectory,
        lib/libvarnishapi/Makefile.am:14: but option 'subdir-objects' is disabled
        lib/libvarnishapi/Makefile.am:14: warning: source file '../libvarnish/vmb.c' is in a subdirectory,
        lib/libvarnishapi/Makefile.am:14: but option 'subdir-objects' is disabled
        lib/libvarnishapi/Makefile.am:14: warning: source file '../libvarnish/vre.c' is in a subdirectory,
        lib/libvarnishapi/Makefile.am:14: but option 'subdir-objects' is disabled
        lib/libvarnishapi/Makefile.am:14: warning: source file '../libvarnish/vsb.c' is in a subdirectory,
        lib/libvarnishapi/Makefile.am:14: but option 'subdir-objects' is disabled
        lib/libvarnishapi/Makefile.am:14: warning: source file '../libvarnish/vtim.c' is in a subdirectory,
        lib/libvarnishapi/Makefile.am:14: but option 'subdir-objects' is disabled
        lib/libvarnishapi/Makefile.am:14: warning: source file '../libvarnish/vnum.c' is in a subdirectory,
        lib/libvarnishapi/Makefile.am:14: but option 'subdir-objects' is disabled
        lib/libvarnishapi/Makefile.am:14: warning: source file '../libvarnish/vsha256.c' is in a subdirectory,
        lib/libvarnishapi/Makefile.am:14: but option 'subdir-objects' is disabled
        + autoconf

subsequent 'configure' & 'make' results in a functional build

    ./varnishd -V
        varnishd (varnish-4.1.2 revision 7d4febd)
        Copyright (c) 2006 Verdens Gang AS
        Copyright (c) 2006-2015 Varnish Software AS

Fyi, this is a build with

    libtoolize --version
        libtoolize (GNU libtool) 2.4.6
    aclocal --version
        aclocal (GNU automake) 1.15
    autoheader --version
        autoheader (GNU Autoconf) 2.69
    autoheader --version
        autoheader (GNU Autoconf) 2.69
    automake --version
        automake (GNU automake) 1.15
    autoconf --version
        autoconf (GNU Autoconf) 2.69

A useful summary of the 'quick fix' is at

    http://darmawan-salihun.blogspot.com/2015/09/makefileam-option-subdir-objects-is.html

**Comment by fgsch** [comment]
This is not specific to that commit and is an automake bug. 

Fixing the warning as the link suggests is not an option, it will break in other ways unless you have a recent automake version.

See https://debbugs.gnu.org/cgi/bugreport.cgi?bug=13928.

Unfortunately we have to live with these warnings for the time being.
