### ISSUE TITLE
What does -p flag for backend.list command means?

### ISSUE THREAD

**Issue by akuznecov** [varnishcache/varnish-cache#1889]
Hello,

Could someone explain me what this flag could be used for?
Just trying to understand but no documentation point given for it

```
[root@server ~]# varnishadm backend.list
Backend name                   Refs   Admin      Probe
apps01(172.16.32.100,,81)      4      probe      Healthy 5/5
apps02(172.16.32.101,,81)      2      probe      Healthy 5/5
[root@server ~]# varnishadm backend.list -p

[root@server ~]#
```

Thanks in advance

**Comment by fgsch** [comment]
The `-p` parameter has been added in 4.1 and is meant to replace `debug.health`.
It will display the probe details (states, response times, etc).

**Comment by akuznecov** [comment]
Ah.. I have checked documentation for trunk, but tried to apply to 4.0 instance :(

@fgsch thanks a lot for explanation!

**Comment by fgsch** [comment]
This should be documented however. I will address this shortly.
