### ISSUE TITLE
varnish version 4.0 and 4.1.2 can not able to stream smoothly.

### ISSUE THREAD

**Issue by shamimrezasohag** [varnishcache/varnish-cache#1901]
I have deployed Varnish 4.0 in CentOS 7 64 bit and Varnish 4.1.2 in Debian 8.4 64 bit machine. Configured the varnish cache for my HTTP Live Streaming. While i start testing the streaming it runs for 2/3 minutes and freezes for 60 second and its looping like this... Testing the streaming on VLC media player and also on Firefox browser.
## Expected Behavior

The streaming should not be freezes for a second and its should run smoothly along with the cache functionality.

## Current Behavior

The HLS streaming freezes for 60 second and automatically started running it with new segment and then after 2/3 minutes its again freezes for 60 second and it continues like this. 

It should be able to stream smoothly and not freezes for a second.
## Steps to Reproduce (for bugs)

1.Install Debian 8.4 64 bit OS with minimal Installation
2.install varnish 4.1.2 accordingly to Varnish official documentations
3. edit file like below: /etc/varnish/default.vcl
```
vcl 4.0;
import std; import directors; import querystring;
backend server1 {   .host = "192.168.4.1";   .probe = {
    .url = "/hls/newtv/index.m3u8";
    .interval  = 5s;
    .timeout   = 1s;
    .window    = 5;
    .threshold = 3;   } }
sub vcl_init {   new vdir = directors.round_robin();   vdir.add_backend(server1); }
sub vcl_recv {   set req.backend_hint = vdir.backend(); # send all traffic to the vdir director   set req.http.Host = regsub(req.http.Host, ":[0-9]+", "");   set req.url = std.querysort(req.url);
  if (req.url ~ "^[^?]*\.(m3u8)(\?.*)?$") {
    unset req.http.Cookie;
    return (hash);   }
  if (req.http.Authorization) {
    # Not cacheable by default
    return (pass);   }
  return (hash); } sub vcl_pipe {   if (req.http.upgrade) {
    set bereq.http.upgrade = req.http.upgrade;   }
  return (pipe); }
sub vcl_hash {
    if (req.method == "GET" || req.method == "HEAD") {
        hash_data(querystring.remove(req.url));
    }
    else {
        hash_data(req.url);
    }
    hash_data(req.http.host);
    return (lookup);
}
sub vcl_hit {
  if (obj.ttl >= 0s) {
    return (deliver);   }
  if (std.healthy(req.backend_hint)) {
    if (obj.ttl + 10s > 0s) {
      return (deliver);
    } else {
      return(fetch);
    }   } else {
      if (obj.ttl + obj.grace > 0s) {
      return (deliver);
    } else {
      return (fetch);
    }   } return (fetch); # Dead code, keep as a safeguard }
sub vcl_miss {   return (fetch); }
sub vcl_backend_response {   if (beresp.http.Surrogate-Control ~ "ESI/1.0") {
    unset beresp.http.Surrogate-Control;
    set beresp.do_esi = true;   }
  if (bereq.url ~ "^[^?]*\.(m3u8)(\?.*)?$") {
    unset beresp.http.set-cookie;   }
  if (bereq.url ~ "^[^?]*\.(m3u8)(\?.*)?$") {
    unset beresp.http.set-cookie;
    set beresp.do_stream = true;
    set beresp.do_gzip   = false;   }
  if (beresp.status == 301 || beresp.status == 302) {
    set beresp.http.Location = regsub(beresp.http.Location, ":[0-9]+", "");   }
  if (beresp.status == 500 || beresp.status == 502 || beresp.status == 503 || beresp.status == 504) {
    return (abandon);   }
  set beresp.grace = 6h;
  return (deliver); }
sub vcl_deliver {

  if (obj.hits > 0) { # Add debug header to see if it's a HIT/MISS and the number of hits, disable when not needed
    set resp.http.X-Cache = "HIT";   } else { set resp.http.X-Cache = "MISS";   }
  set resp.http.X-Cache-Hits = obj.hits;
  return (deliver); }

sub vcl_purge {   if (req.method != "PURGE") {
    # restart request
    set req.http.X-Purge = "Yes";
    return(restart);   } }

sub vcl_synth {   if (resp.status == 720) {
    set resp.http.Location = resp.reason;
    set resp.status = 301;
    return (deliver);   } elseif (resp.status == 721) {
    set resp.http.Location = resp.reason;
    set resp.status = 302;
    return (deliver);   }
 return (deliver); }
sub vcl_fini {
  return (ok); }
```

and /etc/default/varnish
START=yes
NFILES=131072
MEMLOCK=82000
DAEMON_OPTS="-a 192.168.2.1:80 \
             -T localhost:6082 \
             -f /etc/varnish/default.vcl \
             -S /etc/varnish/secret \
             -s malloc,256m"
4. And test the output with VLC media player or Firefox browser

## Context

I want to streaming some tv channels with HLS and also cache it accordingly.

## Your Environment

* Version used: 4.1.2
* Operating System and version: Debian 8.4 64 bit

**Comment by fgsch** [comment]
Can you include a varnishlog capture with such freezes?

**Comment by shamimrezasohag** [comment]
Here is the Varnish Log while streaming freezes;

`*   << Request  >> 57
-   Begin          req 56 rxreq
-   Timestamp      Start: 1460563841.759608 0.000000 0.000000
-   Timestamp      Req: 1460563841.759608 0.000000 0.000000
-   ReqStart       10.2.2.2 34501
-   ReqMethod      GET
-   ReqURL         /hls/newtv/01.m3u8
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: 192.168.2.1
-   ReqHeader      icy-metadata: 1
-   ReqHeader      Referer: http://192.168.2.1/hls/newtv/index.m3u8
-   ReqHeader      Cache-Control: max-age=0
-   ReqHeader      Accept-Encoding: gzip, deflate
-   ReqHeader      User-Agent: GStreamer souphttpsrc libsoup/2.48.0
-   ReqHeader      Connection: Keep-Alive
-   ReqHeader      X-Forwarded-For: 10.2.2.2
-   VCL_call       RECV
-   ReqUnset       Host: 192.168.2.1
-   ReqHeader      Host: 192.168.2.1
-   ReqURL         /hls/newtv/01.m3u8
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Surrogate-Capability: key=ESI/1.0
-   VCL_return     hash
-   ReqUnset       Accept-Encoding: gzip, deflate
-   ReqHeader      Accept-Encoding: gzip
-   VCL_call       HASH
-   VCL_return     lookup
-   Hit            30
-   VCL_call       HIT
-   VCL_return     deliver
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Content-Type: application/vnd.apple.mpegurl
-   RespHeader     Content-Length: 348
-   RespHeader     Last-Modified: Wed, 13 Apr 2016 16:07:57 GMT
-   RespHeader     Accept-Range: bytes
-   RespHeader     Server: Halo Origin Server
-   RespHeader     X-HLS-INFO: Playlist
-   RespHeader     Date: Wed, 13 Apr 2016 16:08:06 GMT
-   RespHeader     X-Varnish: 57 30
-   RespHeader     Age: 106
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Cache: HIT
-   RespHeader     X-Cache-Hits: 7
-   RespUnset      Server: Halo Origin Server
-   RespUnset      X-Varnish: 57 30
-   RespUnset      Via: 1.1 varnish-v4
-   VCL_return     deliver
-   Timestamp      Process: 1460563841.759681 0.000073 0.000073
-   RespHeader     Accept-Ranges: bytes
-   Debug          "RES_MODE 2"
-   RespHeader     Connection: keep-alive
-   Timestamp      Resp: 1460563841.759717 0.000109 0.000036
-   ReqAcct        261 0 261 298 348 646
-   End

*   << Session  >> 56
-   Begin          sess 0 HTTP/1
-   SessOpen       10.2.2.2 34501 192.168.2.1:80 192.168.2.1 80 1460563841.753734 18
-   Link           req 57 rxreq
-   SessClose      RX_TIMEOUT 5.010
-   End

*   << Request  >> 32822
-   Begin          req 32821 rxreq
-   Timestamp      Start: 1460563852.779719 0.000000 0.000000
-   Timestamp      Req: 1460563852.779719 0.000000 0.000000
-   ReqStart       10.2.2.2 34502
-   ReqMethod      GET
-   ReqURL         /hls/newtv/01.m3u8
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: 192.168.2.1
-   ReqHeader      icy-metadata: 1
-   ReqHeader      Referer: http://192.168.2.1/hls/newtv/index.m3u8
-   ReqHeader      Cache-Control: max-age=0
-   ReqHeader      Accept-Encoding: gzip, deflate
-   ReqHeader      User-Agent: GStreamer souphttpsrc libsoup/2.48.0
-   ReqHeader      Connection: Keep-Alive
-   ReqHeader      X-Forwarded-For: 10.2.2.2
-   VCL_call       RECV
-   ReqUnset       Host: 192.168.2.1
-   ReqHeader      Host: 192.168.2.1
-   ReqURL         /hls/newtv/01.m3u8
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Surrogate-Capability: key=ESI/1.0
-   VCL_return     hash
-   ReqUnset       Accept-Encoding: gzip, deflate
-   ReqHeader      Accept-Encoding: gzip
-   VCL_call       HASH
-   VCL_return     lookup
-   Hit            30
-   VCL_call       HIT
-   VCL_return     deliver
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Content-Type: application/vnd.apple.mpegurl
-   RespHeader     Content-Length: 348
-   RespHeader     Last-Modified: Wed, 13 Apr 2016 16:07:57 GMT
-   RespHeader     Accept-Range: bytes
-   RespHeader     Server: Halo Origin Server
-   RespHeader     X-HLS-INFO: Playlist
-   RespHeader     Date: Wed, 13 Apr 2016 16:08:06 GMT
-   RespHeader     X-Varnish: 32822 30
-   RespHeader     Age: 117
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Cache: HIT
-   RespHeader     X-Cache-Hits: 8
-   RespUnset      Server: Halo Origin Server
-   RespUnset      X-Varnish: 32822 30
-   RespUnset      Via: 1.1 varnish-v4
-   VCL_return     deliver
-   Timestamp      Process: 1460563852.779790 0.000071 0.000071
-   RespHeader     Accept-Ranges: bytes
-   Debug          "RES_MODE 2"
-   RespHeader     Connection: keep-alive
-   Timestamp      Resp: 1460563852.779825 0.000106 0.000035
-   ReqAcct        261 0 261 298 348 646
-   End

*   << Session  >> 32821
-   Begin          sess 0 HTTP/1
-   SessOpen       10.2.2.2 34502 192.168.2.1:80 192.168.2.1 80 1460563852.775618 18
-   Link           req 32822 rxreq
-   SessClose      RX_TIMEOUT 5.009
-   End

*   << Request  >> 59
-   Begin          req 58 rxreq
-   Timestamp      Start: 1460563863.793440 0.000000 0.000000
-   Timestamp      Req: 1460563863.793440 0.000000 0.000000
-   ReqStart       10.2.2.2 34503
-   ReqMethod      GET
-   ReqURL         /hls/newtv/01.m3u8
  ReqProtocol    HTTP/1.1
-   ReqHeader      Host: 192.168.2.1
-   ReqHeader      icy-metadata: 1
-   ReqHeader      Referer: http://192.168.2.1/hls/newtv/index.m3u8
-   ReqHeader      Cache-Control: max-age=0
-   ReqHeader      Accept-Encoding: gzip, deflate
-   ReqHeader      User-Agent: GStreamer souphttpsrc libsoup/2.48.0
-   ReqHeader      Connection: Keep-Alive
-   ReqHeader      X-Forwarded-For: 10.2.2.2
-   VCL_call       RECV
-   ReqUnset       Host: 192.168.2.1
-   ReqHeader      Host: 192.168.2.1
-   ReqURL         /hls/newtv/01.m3u8
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Surrogate-Capability: key=ESI/1.0
-   VCL_return     hash
-   ReqUnset       Accept-Encoding: gzip, deflate
-   ReqHeader      Accept-Encoding: gzip
-   VCL_call       HASH
-   VCL_return     lookup
-   Hit            30
-   VCL_call       HIT
-   VCL_return     deliver
-   Link           bereq 60 bgfetch
-   Timestamp      Fetch: 1460563863.793588 0.000148 0.000148
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Content-Type: application/vnd.apple.mpegurl
-   RespHeader     Content-Length: 348
-   RespHeader     Last-Modified: Wed, 13 Apr 2016 16:07:57 GMT
-   RespHeader     Accept-Range: bytes
-   RespHeader     Server: Halo Origin Server
-   RespHeader     X-HLS-INFO: Playlist
-   RespHeader     Date: Wed, 13 Apr 2016 16:08:06 GMT
-   RespHeader     X-Varnish: 59 30
-   RespHeader     Age: 128
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Cache: HIT
-   RespHeader     X-Cache-Hits: 9
-   RespUnset      Server: Halo Origin Server
-   RespUnset      X-Varnish: 59 30
-   RespUnset      Via: 1.1 varnish-v4
-   VCL_return     deliver
-   Timestamp      Process: 1460563863.793604 0.000164 0.000016
-   RespHeader     Accept-Ranges: bytes
-   Debug          "RES_MODE 2"
-   RespHeader     Connection: keep-alive
-   Timestamp      Resp: 1460563863.793632 0.000192 0.000028
-   ReqAcct        261 0 261 298 348 646
-   End

*   << BeReq    >> 60
-   Begin          bereq 59 bgfetch
-   Timestamp      Start: 1460563863.793529 0.000000 0.000000
-   BereqMethod    GET
-   BereqURL       /hls/newtv/01.m3u8
-   BereqProtocol  HTTP/1.1
-   BereqHeader    icy-metadata: 1
-   BereqHeader    Referer: http://192.168.2.1/hls/newtv/index.m3u8
-   BereqHeader    User-Agent: GStreamer souphttpsrc libsoup/2.48.0
-   BereqHeader    X-Forwarded-For: 10.2.2.2
-   BereqHeader    Host: 192.168.2.1
-   BereqHeader    Surrogate-Capability: key=ESI/1.0
-   BereqHeader    Accept-Encoding: gzip
-   BereqHeader    If-Modified-Since: Wed, 13 Apr 2016 16:07:57 GMT
-   BereqHeader    X-Varnish: 60
-   VCL_call       BACKEND_FETCH
-   VCL_return     fetch
-   BackendOpen    21 boot.server1 192.168.4.1 80 172.16.1.2 52529
-   Timestamp      Bereq: 1460563863.793859 0.000330 0.000330
-   Timestamp      Beresp: 1460563863.795371 0.001842 0.001512
-   BerespProtocol HTTP/1.1
-   BerespStatus   200
-   BerespReason   OK
-   BerespHeader   Content-Type: application/vnd.apple.mpegurl
-   BerespHeader   Content-Length: 348
-   BerespHeader   Last-Modified: Wed, 13 Apr 2016 16:10:06 GMT
-   BerespHeader   Accept-Range: bytes
-   BerespHeader   Server: Halo Origin Server
-   BerespHeader   X-HLS-INFO: Playlist
-   BerespHeader   Date: Wed, 13 Apr 2016 16:10:14 GMT
-   BerespHeader   Connection: keep-alive
-   TTL            RFC 120 10 -1 1460563864 1460563864 1460563814 0 0
-   VCL_call       BACKEND_RESPONSE
-   TTL            VCL 120 21600 0 1460563864
-   VCL_return     deliver
-   Storage        malloc s0
-   ObjProtocol    HTTP/1.1
-   ObjStatus      200
-   ObjReason      OK
-   ObjHeader      Content-Type: application/vnd.apple.mpegurl
-   ObjHeader      Content-Length: 348
-   ObjHeader      Last-Modified: Wed, 13 Apr 2016 16:10:06 GMT
-   ObjHeader      Accept-Range: bytes
-   ObjHeader      Server: Halo Origin Server
-   ObjHeader      X-HLS-INFO: Playlist
-   ObjHeader      Date: Wed, 13 Apr 2016 16:10:14 GMT
-   Fetch_Body     3 length stream
-   BackendReuse   21 boot.server1
-   Timestamp      BerespBody: 1460563863.795634 0.002105 0.000263
-   Length         348
-   BereqAcct      335 0 335 263 348 611
-   End

*   << Session  >> 58
-   Begin          sess 0 HTTP/1
-   SessOpen       10.2.2.2 34503 192.168.2.1:80 192.168.2.1 80 1460563863.789366 18
-   Link           req 59 rxreq
-   SessClose      RX_TIMEOUT 5.007
-   End
*   << Request  >> 32824
-   Begin          req 32823 rxreq
-   Timestamp      Start: 1460563874.813352 0.000000 0.000000
-   Timestamp      Req: 1460563874.813352 0.000000 0.000000
-   ReqStart       10.2.2.2 34504
-   ReqMethod      GET
-   ReqURL         /hls/newtv/01.m3u8
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: 192.168.2.1
-   ReqHeader      icy-metadata: 1
-   ReqHeader      Referer: http://192.168.2.1/hls/newtv/index.m3u8
-   ReqHeader      Cache-Control: max-age=0
-   ReqHeader      Accept-Encoding: gzip, deflate
-   ReqHeader      User-Agent: GStreamer souphttpsrc libsoup/2.48.0
-   ReqHeader      Connection: Keep-Alive
-   ReqHeader      X-Forwarded-For: 10.2.2.2
-   VCL_call       RECV
-   ReqUnset       Host: 192.168.2.1
-   ReqHeader      Host: 192.168.2.1
-   ReqURL         /hls/newtv/01.m3u8
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Surrogate-Capability: key=ESI/1.0
-   VCL_return     hash
-   ReqUnset       Accept-Encoding: gzip, deflate
-   ReqHeader      Accept-Encoding: gzip
-   VCL_call       HASH
-   VCL_return     lookup
-   Hit            60
-   VCL_call       HIT
-   VCL_return     deliver
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Content-Type: application/vnd.apple.mpegurl
-   RespHeader     Content-Length: 348
-   RespHeader     Last-Modified: Wed, 13 Apr 2016 16:10:06 GMT
-   RespHeader     Accept-Range: bytes
-   RespHeader     Server: Halo Origin Server
-   RespHeader     X-HLS-INFO: Playlist
-   RespHeader     Date: Wed, 13 Apr 2016 16:10:14 GMT
-   RespHeader     X-Varnish: 32824 60
-   RespHeader     Age: 11
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Cache: HIT
-   RespHeader     X-Cache-Hits: 1
-   RespUnset      Server: Halo Origin Server
-   RespUnset      X-Varnish: 32824 60
-   RespUnset      Via: 1.1 varnish-v4
-   VCL_return     deliver
-   Timestamp      Process: 1460563874.813423 0.000071 0.000071
-   RespHeader     Accept-Ranges: bytes
-   Debug          "RES_MODE 2"
-   RespHeader     Connection: keep-alive
-   Timestamp      Resp: 1460563874.813449 0.000098 0.000027
-   ReqAcct        261 0 261 297 348 645
-   End

*   << BeReq    >> 63
-   Begin          bereq 62 fetch
-   Timestamp      Start: 1460563874.831377 0.000000 0.000000
-   BereqMethod    GET
-   BereqURL       /hls/newtv/20160307T090852-01-2851896.ts
-   BereqProtocol  HTTP/1.1
-   BereqHeader    icy-metadata: 1
-   BereqHeader    Referer: http://192.168.2.1/hls/newtv/index.m3u8
-   BereqHeader    User-Agent: GStreamer souphttpsrc libsoup/2.48.0
-   BereqHeader    X-Forwarded-For: 10.2.2.2
-   BereqHeader    Host: 192.168.2.1
-   BereqHeader    Surrogate-Capability: key=ESI/1.0
-   BereqHeader    Accept-Encoding: gzip
-   BereqHeader    X-Varnish: 63
-   VCL_call       BACKEND_FETCH
-   VCL_return     fetch
-   BackendOpen    21 boot.server1 192.168.4.1 80 172.16.1.2 52529
-   Timestamp      Bereq: 1460563874.831411 0.000034 0.000034
-   Timestamp      Beresp: 1460563874.832998 0.001621 0.001586
-   BerespProtocol HTTP/1.1
-   BerespStatus   200
-   BerespReason   OK
-   BerespHeader   Content-Type: video/mp2t
-   BerespHeader   Content-Length: 1086076
-   BerespHeader   Last-Modified: Wed, 13 Apr 2016 16:09:18 GMT
-   BerespHeader   Accept-Range: bytes
-   BerespHeader   Server: Halo Origin Server
-   BerespHeader   X-HLS-INFO: Chunk
-   BerespHeader   Date: Wed, 13 Apr 2016 16:10:25 GMT
-   BerespHeader   Connection: keep-alive
-   TTL            RFC 120 10 -1 1460563875 1460563875 1460563825 0 0
-   VCL_call       BACKEND_RESPONSE
-   TTL            VCL 120 21600 0 1460563875
-   VCL_return     deliver
-   Storage        malloc s0
-   ObjProtocol    HTTP/1.1
-   ObjStatus      200
-   ObjReason      OK
-   ObjHeader      Content-Type: video/mp2t
-   ObjHeader      Content-Length: 1086076
-   ObjHeader      Last-Modified: Wed, 13 Apr 2016 16:09:18 GMT
-   ObjHeader      Accept-Range: bytes
-   ObjHeader      Server: Halo Origin Server
-   ObjHeader      X-HLS-INFO: Chunk
-   ObjHeader      Date: Wed, 13 Apr 2016 16:10:25 GMT
-   Fetch_Body     3 length stream
-   BackendReuse   21 boot.server1
-   Timestamp      BerespBody: 1460563874.845176 0.013799 0.012179
-   Length         1086076
-   BereqAcct      307 0 307 245 1086076 1086321
-   End

*   << Request  >> 62
-   Begin          req 61 rxreq
-   Timestamp      Start: 1460563874.831326 0.000000 0.000000
-   Timestamp      Req: 1460563874.831326 0.000000 0.000000
-   ReqStart       10.2.2.2 34505
-   ReqMethod      GET
-   ReqURL         /hls/newtv/20160307T090852-01-2851896.ts
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: 192.168.2.1
-   ReqHeader      icy-metadata: 1
-   ReqHeader      Referer: http://192.168.2.1/hls/newtv/index.m3u8
-   ReqHeader      User-Agent: GStreamer souphttpsrc libsoup/2.48.0
-   ReqHeader      Connection: Keep-Alive
-   ReqHeader      X-Forwarded-For: 10.2.2.2
-   VCL_call       RECV
-   ReqUnset       Host: 192.168.2.1
-   ReqHeader      Host: 192.168.2.1
-   ReqURL         /hls/newtv/20160307T090852-01-2851896.ts
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Surrogate-Capability: key=ESI/1.0
-   VCL_return     hash
-   VCL_call       HASH
-   VCL_return     lookup
-   VCL_call       MISS
-   VCL_return     fetch
-   Link           bereq 63 fetch
-   Timestamp      Fetch: 1460563874.833121 0.001795 0.001795
-   RespProtocol   HTTP/1.
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Content-Type: video/mp2t
-   RespHeader     Content-Length: 1086076
-   RespHeader     Last-Modified: Wed, 13 Apr 2016 16:09:18 GMT
-   RespHeader     Accept-Range: bytes
-   RespHeader     Server: Halo Origin Server
-   RespHeader     X-HLS-INFO: Chunk
-   RespHeader     Date: Wed, 13 Apr 2016 16:10:25 GMT
-   RespHeader     X-Varnish: 62
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Cache: MISS
-   RespHeader     X-Cache-Hits: 0
-   RespUnset      Server: Halo Origin Server
-   RespUnset      X-Varnish: 62
-   RespUnset      Via: 1.1 varnish-v4
-   VCL_return     deliver
-   Timestamp      Process: 1460563874.833133 0.001807 0.000012
-   RespHeader     Accept-Ranges: bytes
-   Debug          "RES_MODE 2"
-   RespHeader     Connection: keep-alive
-   Timestamp      Resp: 1460563875.691265 0.859939 0.858132
-   ReqAcct        225 0 225 279 1086076 1086355
-   End

                                                             `

**Comment by nigoroll** [comment]
There is no obvious varnish issue apparent in your varnishlog output. We suspect this could be related to your player not cleanly handling closure of the tcp session by varnish. Could you please try with the `timeout_idle` parameter set to a significantly higher value than the 5 seconds default?

**Comment by shamimrezasohag** [comment]
Thanks for your reply. I have tested the streaming on Ubuntu 14.04, Windows 10, And OSx along with VLC media player and Firefox browser, every where it freezes. But when i use the Varnish version 3 output then the streaming never freezes. And the new value of  "timeout_idle"  hasn't changed anything on the performance.

**Comment by nigoroll** [comment]
Just to be sure that we haven't overlooked anything, I've taken your vcl, made some trivial changes (like not removing cookies), configured varnish against an Akamai HDS Server (overriding DNS so hosts point to my local varnish) and tested with vlc -> zero issues. I get all cache hits and replay is flawless.
As mentioned before, unfortunately I cannot see any issues in the log you provided

**Comment by nigoroll** [comment]
I must say though that I have tested with master.

**Comment by shamimrezasohag** [comment]
Then this is really unfortunate for me of having this ridiculous problem without any error.
BTW thanks for your help.
