### ISSUE TITLE
Space is mandatory when using here document

### ISSUE THREAD

**Issue by fgsch** [varnishcache/varnish-cache#1907]
## Expected Behavior

Space is optional.

## Current Behavior

Space in mandatory. This is different to normal shell here document.

## Possible Solution

Drop the requirement.

## Steps to Reproduce (for bugs)

This fails to load in varnishadm:

```
vcl.inline foo <<EOF
106        
Message from VCC-compiler:
VCL version declaration missing
Update your VCL to Version 4 syntax, and add
        vcl 4.0;
on the first line the VCL files.
('<vcl.inline>' Line 1 Pos 1)
<<EOF
##---
```

## Your Environment
* Version used: master (dc360a4)

**Comment by bsdphk** [comment]
send patch

**Comment by fgsch** [comment]
I will raise a PR when the time comes.

**Comment by hermunn** [comment]
Backport review: Backporting will be handled in the pull request @fgsch raises.

**Comment by Dridi** [comment]
Until it's changed, please be aware of 4af8328 and 10ac7e1.

**Comment by hermunn** [comment]
@Dridi, if you want and have time to backport the documentation fixes, feel free to do so.

**Comment by Dridi** [comment]
Done in 055551d and f1bc4e8

**Comment by Dridi** [comment]
@hermunn, by the way my comment meant that if we change the parsing of heredocs, we should keep the recently-updated docs in sync too.

**Comment by hermunn** [comment]
@Dridi, good point. Thanks for the backport, by the way.
