### ISSUE TITLE
Missing errorhandling code in V1F_Setup_Fetch

### ISSUE THREAD

**Issue by mwethington** [varnishcache/varnish-cache#1908]
Varnish 4.1.2 Child Panic.

## Expected Behavior
Not sure, but should not panic.

varnish> panic.show
200        
Last panic at: Mon, 18 Apr 2016 05:33:56 GMT
"Missing errorhandling code in V1F_Setup_Fetch(), http1/cache_http1_vfp.c line 281:
  Condition((vfe) != 0) not true.thread = (cache-worker)
version = varnish-4.1.2 revision 0d7404e
ident = Linux,3.16.0-4-amd64,x86_64,-junix,-smalloc,-smalloc,-hcritbit,epoll
Backtrace:
  0x433db5: varnishd() [0x433db5]
  0x452d3e: varnishd(V1F_Setup_Fetch+0x1fe) [0x452d3e]
  0x435b30: varnishd(VRB_Iterate+0x270) [0x435b30]
  0x44eb6d: varnishd(V1F_SendReq+0x1ad) [0x44eb6d]
  0x41252b: varnishd() [0x41252b]
  0x41b45a: varnishd(VDI_GetHdr+0x5a) [0x41b45a]
  0x423df9: varnishd() [0x423df9]
  0x449c52: varnishd() [0x449c52]
  0x44a0cb: varnishd() [0x44a0cb]
  0x7ff421bff0a4: libpthread.so.0(+0x80a4) [0x7ff421bff0a4]
busyobj = 0x7ff40b326020 {
  ws = 0x7ff40b3260e0 {
    id = \"bo\",
    {s,f,r,e} = {0x7ff40b329390,+200,(nil),+396392},
  },
  refcnt = 2,
  retries = 0, failed = 0, state = 1,
  flags = {do_stream, do_pass, uncacheable},
  http_conn = 0x7ff40b3293a8 {
    fd = 67,
    doclose = NULL,
    ws = (nil),
    {rxbuf_b, rxbuf_e} = {(nil), (nil)},
    {pipeline_b, pipeline_e} = {(nil), (nil)},
    content_length = 0,
    body_status = none,
    first_byte_timeout = 60.000000,
    between_bytes_timeout = 60.000000,
  },
  director_req = 0x7ff3ebacecc0 {
    vcl_name = ucms,
    type = round-robin {
    },
  },
  director_resp = 0x7ff3eb9a4838 {
    vcl_name = ucms1,
    type = backend {
      display_name = e4f85ab1-9ac0-4080-b416-98b7da025d4b.ucms1,
      ipv4 = 10.250.65.170,
      port = 80,
      hosthdr = 10.250.65.170,
      health=healthy, admin_health=probe, changed=1460952663.9,
      n_conn = 1,
    },
  },
  http[bereq] = 0x7ff40b326d50 {
    ws[bo] = 0x7ff40b3260e0,
    hdrs {
      \"POST\",
      \"/health-stories/uploadImage-json.jsp?parentId=82fa77f5-6953-4d04-9219-efa496d1e06b\",
      \"HTTP/1.1\",
      \"host: www.healthgrades.com\",
      \"Accept: */*\",
      \"Accept-Encoding: gzip, deflate\",
      \"Accept-Language: en-us\",
      \"CloudFront-Forwarded-Proto: http\",
      \"CloudFront-Is-Desktop-Viewer: false\",
      \"CloudFront-Is-Mobile-Viewer: true\",
      \"CloudFront-Is-SmartTV-Viewer: false\",
      \"CloudFront-Is-Tablet-Viewer: true\",
      \"CloudFront-Viewer-Country: US\",
      \"Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryyyElrf9ZdaKaSF6d\",
      \"Cookie: JSESSIONID=EE286C1527FC51A15C462B3AC239AAF0; __gads=ID=7f0a2e737714de27:T=1445482226:S=ALNI_MZR1d2b8RcIZ60VCTzS5rW165XePA; __utma=236544792.83136032.1445482226.1445482226.1445482226.1; __utmz=236544792.1445482227.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _ga=GA1.2.83136032.1445482226; _gat=1; hg.locationRequest=wasAskedForCurrentLocation=true; hg.search=; s_pers=%20s_firstvisit%3D1445482218718%7C1603162218718%3B%20s_nr%3D1460957596489-New%7C1463549596489%3B%20s_lastvisit%3D1460957596506%7C1555565596506%3B%20s_lastvisit_s%3DMore%2520than%252030%2520days%7C1460959396506%3B%20s_firstvisit_s%3DMore%2520than%252030%2520days%7C1460959396549%3B; s_sess=%20s_cc%3Dtrue%3B%20s_sq%3D%3B%20s_ppv%3Dhealth-stories%25253A%252520submit%252C72%252C44%252C1480%3B; s_vi=[CS]v1|2B142775050132D1-4000011240015323[CE]\",
      \"DNT: 1\",
      \"Origin: http://www.healthgrades.com\",
      \"Referer: http://www.healthgrades.com/health-stories/submit\",
      \"User-Agent: Mozilla/5.0 (iPad; CPU OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4\",
      \"Via: 1.1 7e651d564f1f35b5c2ec0c92b0a2b37e.cloudfront.net (CloudFront)\",
      \"X-Amz-Cf-Id: y56Rtl_SLF-0-_S58n5f9sA8kEDSc-E2tYkU1GwDaan78LlXx9mjrw==\",
      \"X-Requested-With: XMLHttpRequest\",
      \"X-Forwarded-Port: 80\",
      \"X-Forwarded-Proto: http\",
      \"Content-Length: 57473\",
      \"X-Varnish: 60757679\",
    },
  },
  http[beresp] = 0x7ff40b327870 {
    ws[bo] = 0x7ff40b3260e0,
    hdrs {
    },
  },
  objcore[fetch] = 0x7ff3e1ca8100 {
    refcnt = 2,
    flags = 0x10a,
    exp_flags = 0x0,
    exp = { 0.000000, 0.000000, 0.000000, 0.000000 }
    objhead = 0x7ff420cc60e0,
    stevedore = (nil),
  },
  vcl = {
    temp = warm
    srcname = {
      \"/etc/varnish/default.vcl\",
      \"Builtin\",
      \"/etc/varnish/hgweb_backends.vcl\",
      \"/etc/varnish/hgnew3_backends.vcl\",
      \"/etc/varnish/m_backends.vcl\",
      \"/etc/varnish/ucms_backends.vcl\",
      \"/etc/varnish/mobile_detect.vcl\",
      \"/etc/varnish/mobile_be_detect.vcl\",
      \"/etc/varnish/uisvc_backends.vcl\",
      \"/etc/varnish/vcl_init.vcl\",
    },
  },
},

"

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
See panic info

## Your Environment

* Version used: 4.2.1
* Operating System and version: Linux

**Comment by fgsch** [comment]
Dup of #1871
