### ISSUE TITLE
objcore refcnt leak/race

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#1909]
On 'r' (FreeBSD/amd64/10.3) 2d51524ac36dd72efd9002381b711936dd5e305c

#4  0x000000000042d6b1 in exp_inbox (ep=0x802a21080, oc=0x809475600, flags=2)
    at cache/cache_expire.c:186
186                             assert(oc->timer_idx != BINHEAP_NOIDX);
(gdb) print *oc
$1 = {magic = 0, refcnt = 0, stobj = {{stevedore = 0x0, priv = 0x0, 
      priv2 = 0}}, objhead = 0x80947acf0, boc = 0x0, 
  timer_when = 1460924606.9766643, hits = 1, t_origin = 1460924476.9766643, 
  ttl = 120, grace = 10, keep = 0, flags = 128 '\200', exp_flags = 0 '\0', 
  oa_present = 87, timer_idx = 0, last_lru = nan(0x400000), hsh_list = {
    vtqe_next = 0x0, vtqe_prev = 0x802ab0700}, lru_list = {
    vtqe_next = 0x8094756a0, vtqe_prev = 0x802aaf130}, ban_list = {
    vtqe_next = 0x8094756a0, vtqe_prev = 0x80b909360}, exp_list = {
    vstqe_next = 0x802ab06a0}, ban = 0x0}
(gdb) print flags
$2 = 2

**Comment by bsdphk** [comment]
Ok, this crash has not happened again.

**Comment by lkarsten** [comment]
Backport review: I've had a few runs on seeing if this applies to 4.1 or not. Fairly complicated and involved, and not reported in any 4.1 context that I know of. I'm writing it off as a regression in master, and not adding the juicy parts of 33a49c4 this time.
