### ISSUE TITLE
Leak when running test e00008.vtc

### ISSUE THREAD

**Issue by hermunn** [varnishcache/varnish-cache#1912]
There seems to be a leak in cache_esi_parse.c when the test e00008.vtc is run.

Bug spotted by @mbgrydeland.

## Expected Behavior
Passing the test with a new assert enabled.

## Current Behavior

In very special circumstances, a well placed assert uncovers a memory leak.

## Possible Solution

Full review on the state machine when it comes to buffer allocations and deallocations in the different states.

## Steps to Reproduce (for bugs)

* Insert

> AZ(vep->attr_vsb);

before line 857,

> vep->attr_vsb = VSB_new_auto();

* Run the test e00008.vtc
* The assert will fire, failing the test.

## Your Environment

* Version used: Current master with PR1911 added

**Comment by lkarsten** [comment]
Applied in 4.1 in caf885323892dc42605f87683c5275511c018f15.
