### ISSUE TITLE
4.1.x fails to forward HTTP/1.1 response without content-length + missing Transfer-Encoding

### ISSUE THREAD

**Issue by adrian-bl** [varnishcache/varnish-cache#1918]
Varnish 4.1.2 fails to forward HTTP/1.**1** responses where 'Connection' is set to 'close' and the Content-Length & Transfer-Encoding headers are missing.

Example of such a backend reply:
```
HTTP/1.1 200 OK
Content-Type: text/plain
Connection: close

The quick brown fox
```

## Expected Behavior
AFAIK, such a reply does not violate RFC 7230 and should therefore be handled by Varnish
(But i fully agree that a Backend which sends such a reply isn't that smart.)

## Current Behavior
Varnish currently delivers a zero-sized body to the client:
```
[adrian@ebichu ~]$ curl -v 'http://127.0.0.1:80/'
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.48.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Date: Fri, 22 Apr 2016 06:52:48 GMT
< X-Varnish: 2
< Age: 0
< Via: 1.1 varnish-v4
< Accept-Ranges: bytes
< Content-Length: 0
< Connection: keep-alive
< 
```

This does not happen if a Content-Length is provided or if the HTTP Version in the backend-reply is changed to 1.0

## Possible Solution
Commit a6a6e97a4db6e94b14f81af55fea4d07aa06d0af seems to have introduced this issue.

This patch seems to resolve the problem while (hopefully?) not breaking anything else ;-)
```
--- a/bin/varnishd/http1/cache_http1_proto.c
+++ b/bin/varnishd/http1/cache_http1_proto.c
@@ -307,7 +307,7 @@ http1_body_status(const struct http *hp, struct http_conn *htc)
 		return (cl == 0 ? BS_NONE : BS_LENGTH);
 	}
 
-	if (hp->protover == 11)
+	if (hp->protover == 11 && !http_HdrIs(hp, H_Connection, "close"))
 		return (BS_NONE);
 
 	if (http_HdrIs(hp, H_Connection, "keep-alive")) {
```

## Steps to Reproduce (for bugs)
1. Build Varnish 4.1.2
2. nc -l -p 8080 -c < http_reply_posted_above.txt
3. configure varnish to forward 0:80 -> 127.0.0.1:8080
4. curl -v 'http://127.0.0.1:80/'

## Your Environment
* Version used: 4.1.2
* Operating System and version: CentOS 7

**Comment by fgsch** [comment]
RFC 7230, 3.3.3, p33:

```
   7.  Otherwise, this is a response message without a declared message
       body length, so the message body length is determined by the
       number of octets received prior to the server closing the
       connection.
    
   Since there is no way to distinguish a successfully completed,
   close-delimited message from a partially received message interrupted
   by network failure, a server SHOULD generate encoding or
   length-delimited messages whenever possible.  The close-delimiting
   feature exists primarily for backwards compatibility with HTTP/1.0.
```

Confirms this.

**Comment by hermunn** [comment]
Now also 7e90a2b has been back ported to 4.1
