### ISSUE TITLE
Varnish unable to start on reboot

### ISSUE THREAD

**Issue by stephen-kainos** [varnishcache/varnish-cache#1920]
## Expected Behavior
Varnish daemon should start at boot time

## Current Behavior
Varnish appears to start the master process, but then shortly afterwards all the child processes stop.
The syslog appears to be complaining about not being able to bind to the port varnish is running on, however there's nothing else running on this port. This is a dedicated varnish server. 

panic.show from varnishadm gives the following:

```
"Assert error in child_sigsegv_handler(), mgt/mgt_child.c line 282:
  Condition(Segmentation fault by instruction at 0x20bf68) not true.
thread = (cache-worker)
version = varnish-4.1.2 revision 0d7404e
ident = Linux,3.13.0-45-generic,x86_64,-junix,-smalloc,-smalloc,-hcritbit,epoll
Backtrace:
  0x433976: varnishd() [0x433976]
  0x452c43: varnishd() [0x452c43]
  0x7fdc2af61340: libpthread.so.0(+0x10340) [0x7fdc2af61340]
  0x43fba9: varnishd(VCL_DefaultDirector+0x19) [0x43fba9]
  0x436e05: varnishd(CNT_Request+0x9a5) [0x436e05]
  0x44e9d3: varnishd(HTTP1_Session+0xd3) [0x44e9d3]
  0x439d0d: varnishd(SES_Proto_Req+0x5d) [0x439d0d]
  0x4493d1: varnishd() [0x4493d1]
  0x44983b: varnishd() [0x44983b]
  0x7fdc2af59182: libpthread.so.0(+0x8182) [0x7fdc2af59182]
req = 0x7fdc2219a020 {
  vxid = 327766, step = R_STP_RECV,
  req_body = R_BODY_NONE,
  restarts = 0, esi_level = 0,
  sp = 0x7fdc2a1c0220 {
    fd = 22, vxid = 327765,
    client = 192.168.55.13 47216,
    step = S_STP_H1PROC,
  },
  worker = 0x7fdc2c2bac40 {
    stack = {0x7fdc2c2bb000 -> 0x7fdc2c2af000},
    ws = 0x7fdc2c2bae38 {
      id = \"wrk\",
      {s,f,r,e} = {0x7fdc2c2ba3e0,0x7fdc2c2ba3e0,(nil),+2040},
    },
    VCL::method = SYNTH,
    VCL::return = deliver,
    VCL::methods = {},
  },
  ws = 0x7fdc2219a200 {
    id = \"req\",
    {s,f,r,e} = {0x7fdc2219c000,+152,(nil),+57336},
  },
  http_conn = 0x7fdc2219a128 {
    fd = 22,
    doclose = NULL,
    ws = 0x7fdc2219a200,
    {rxbuf_b, rxbuf_e} = {0x7fdc2219c048, 0x7fdc2219c073},
    {pipeline_b, pipeline_e} = {(nil), (nil)},
    content_length = -1,
    body_status = none,
    first_byte_timeout = 0.000000,
    between_bytes_timeout = 0.000000,
  },
  http[req] = 0x7fdc2219a298 {
    ws[req] = 0x7fdc2219a200,
    hdrs {
      \"GET\",
      \"/ping\",
      \"HTTP/1.0\",
      \"Host: www.example.com\",
      \"X-Forwarded-For: 192.168.55.13\",
    },
  },
  vcl = {
    temp = warm
    srcname = {
"
```

Varnish runs fine when running interactively, also the VCL compiles fine. 

Same result can be seen on two different varnish servers. 

## Steps to Reproduce (for bugs)

1. Boot Ubuntu 14.04 with Varnish 4.1.2

## Context

Varnish is unable to recover from server restarts 

## Your Environment

* Version used: 4.1.2
* Operating System and version:  Ubuntu 14.04

**Comment by fgsch** [comment]
Can you provide your VCL?

**Comment by nigoroll** [comment]
And please let us know if you use the PROXY protocol. This looks similar to #1888

**Comment by Dridi** [comment]
Also, this panic happens during a transaction, at this point Varnish successfully bound the port.

What's the exact syslog'd panic you're seeing?

**Comment by stephen-kainos** [comment]
@fgsch VCLs attached. [varnish.zip](https://github.com/varnishcache/varnish-cache/files/234418/varnish.zip)


@nigoroll yes, I am using the PROXY protocol

@Dridi the syslog message only complains about being unable to bind to the listening port. However there's nothing else that listens on this port.

**Comment by bsdphk** [comment]
This issue is now tracked under #1933 only
