### ISSUE TITLE
systemd varnish.unit not using /etc/default/varnish

### ISSUE THREAD

**Issue by soleuu** [varnishcache/varnish-cache#1929]
## Expected Behavior
When using systemd, editing /etc/default/varnish and restarting varnish, changement must be applied.

## Current Behavior
When starting varnish only the default configuration present in /lib/systemd/system/varnish.service is used.

## Possible Solution
We could use the next code for the systemd unit.
Explanation : 
- whe define default value and 
- if value are present in /etc/default/varnish, they overide defaults values.
- ExecStartPre will check vcl syntax

```
[Unit]
Description=Varnish HTTP accelerator

[Service]
Type=forking
LimitNOFILE=131072
LimitMEMLOCK=82000
Environment="DAEMON_OPTS=-a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m"
EnvironmentFile=-/etc/default/varnish
ExecStartPre=/usr/sbin/varnishd -C -f /etc/varnish/default.vcl
ExecStart=/usr/sbin/varnishd $DAEMON_OPTS
ExecReload=/usr/share/varnish/reload-vcl

[Install]
WantedBy=multi-user.target
```

## Steps to Reproduce (for bugs)
1. edit /etc/default/varnish to listen on a new port
2. /etc/init.d/varnish restart (or systemd syntax)
3. netstat -lpne | grep varnish #varnish always listen on

## Environment
* Version used:varnish  4.1.2-2~jessie amd64
* Operating System and version: debian 8(jessie)
* systemd package present on the system (fresh install)

**Comment by fgsch** [comment]
Moved to https://github.com/varnishcache/pkg-varnish-cache/issues/25.
