### ISSUE TITLE
segfault varnish 4.1.2

### ISSUE THREAD

**Issue by jay78238** [varnishcache/varnish-cache#1940]
Assert error in SES_Delete(), cache/cache_session.c line 544:   Condition(now >= sp->t_open) not true. errno = 32 (Broken pipe) thread = (cache-worker) version = varnish-4.1.2 revision 0d7404e ident = Linux,4.1.19,x86_64,-jnone,-smalloc,-smalloc,-hcritbit,epoll Backtrace:   0x433762: pan_ic+0x152   0x43ad5f: varnishd() [0x43ad5f]   0x44e92e: HTTP1_Session+0x58e   0x4399ed: SES_Proto_Req+0x5d   0x448e7a: WRK_Thread+0x47a   0x4492db: pool_thread+0x2b   0x7fd55ab7e434: libpthread.so.0(+0x7434) [0x7fd55ab7e434]   0x7fd55a8bc0ad: libc.so.6(clone+0x6d) [0x7fd55a8bc0ad] req = 0x7fd5161201f0 {   vxid = 0, step = R_STP_RESTART,   req_body = R_BODY_INIT,   restarts = 0, esi_level = 0,   ws = 0x7fd5161203d0 {     OVERFLOWED id = \"\",     {s,f,r,e} = {(nil),(nil),(nil),(nil)},   },   http[req] = (nil) {

linux 4.1.19 x64

**Comment by nigoroll** [comment]
dup of #1874

**Comment by lkarsten** [comment]
Backport review: dup.
