### ISSUE TITLE
Assert error in hcb_delete()

### ISSUE THREAD

**Issue by R4Fi** [varnishcache/varnish-cache#1952]
Child process died few hours after started.
## Expected Behavior

Restarting child process is problemmatic for us, becouse we are loosing whole cache and having high load on the machines after that.

## Context

After few hours child process is died and starting again. 
We started varnish with enable debbuging mode and when child process died We got on console:

```
Error: Child (15333) not responding to CLI, killing it.
Error: Child (15333) died signal=6
Error: Child (15333) Last panic at: Tue, 17 May 2016 10:33:15 GMT
"Assert error in hcb_delete(), hash/hash_critbit.c line 294:
 Condition(y->ptr < DIGEST_LEN) not true.
thread = (cache-timeout)
version = varnish-4.1.2 revision 0d7404e
ident = Linux,3.14.32-xxxx-grs-ipv6-64,x86_64,-junix,-smalloc,-smalloc,-hcritbit,epoll
Backtrace:
 0x432d03: varnishd() [0x432d03]
 0x44c4f6: varnishd() [0x44c4f6]
 0x428103: varnishd(HSH_DerefObjHead+0xd3) [0x428103]
 0x428400: varnishd(HSH_DerefObjCore+0x160) [0x428400]
 0x4202e2: varnishd() [0x4202e2]
 0x448b47: varnishd() [0x448b47]
 0x73e3baaddaa1: libpthread.so.0(+0x7aa1) [0x73e3baaddaa1]
 0x73e3ba82a93d: libc.so.6(clone+0x6d) [0x73e3ba82a93d]

"
Debug: Child cleanup complete
```

We tried set `cli_timeout` to `90.000`, but still the same.

## Your Environment

* Version used: varnish-4.1.2 revision 0d7404e
* Operating System and version: CentOS release 6.7 (Final)

**Comment by nigoroll** [comment]
the info requested in #1950 could be helpful for this one too

**Comment by nigoroll** [comment]
timeout.please re-open with answers to my questions in #1950 if the issue still exists

**Comment by hermunn** [comment]
Removing backport-review tags since nothing has been commited. Please add these back if the issue is reopened and commits are added.
