### ISSUE TITLE
4.1.x fails to forward HTTP/1.1 close-delimited response missing CL, TE, and Conn:close headers

### ISSUE THREAD

**Issue by blblack** [varnishcache/varnish-cache#1954]
This is almost identical to #1918 .  The difference is that some backend servers (observed with multiple Apache versions with WSGI backend applications) will send HTTP/1.1 close-delimited responses which not only lack `Content-Length` and `Transfer-Encoding`, but also have no explicit `Connection: close` header.

RFC7230 is confusing on this whole issue when trying to dig into whether the server's behavior here is legal in HTTP/1.1, but I can't find any really clear prose that indicates this is actually illegal, and it apparently exists in real-world implementations that Varnish will end up revproxying for.

We've got a very short patch deployed that fixes this here in our environment, incoming shortly...

## Expected Behavior
Varnish should forward these requests with whatever content body it receives up through the backend server terminating the connection.

## Current Behavior
Currently, it treats these responses as `Content-Length: 0`

**Comment by fgsch** [comment]
Looks good to me. @bsdphk ?

**Comment by fgsch** [comment]
Fixed in 7e90a2b4d47c16209065a70c801a7dbf4844b60a.

**Comment by hermunn** [comment]
Backport to 4.1 added, removing tag.
