### ISSUE TITLE
The builtin.vcl hit-for-pass create logic does not take grace into account

### ISSUE THREAD

**Issue by mbgrydeland** [varnishcache/varnish-cache#1964]
The builtin.vcl for vcl_backend_response contains a test for whether the object we are inserting into the cache has a positive TTL or not. If it doesn't have a positive TTL, the TTL is changed to 120s and a hit-for-pass object is inserted. The purpose of this is to disable request coalescing and enable multiple clients to go to the backend at the same time for this cache point instead of the serialization which would happen otherwise.

Though the calculation does not take grace into account, meaning that a hit-for-pass object is created earlier than strictly necessary. While the object is in grace, we should be able to continue delivering stale cache results while the backend update is performed. Instead we immediately create a hit-for-pass object and request coalescing is deactivated for the next 2 minutes.
## Possible Solution

Change the builtin.vcl to take grace into account. See referenced pull-request.
## Steps to Reproduce (for bugs)

See test case in referenced pull-request.

**Comment by rezan** [comment]
Wouldn't this break VCLs where someone sets `beresp.ttl = 0s` and doesn't touch grace and expects the result to be hit-for-pass? I see this pattern in VCLs often. With this, the object will end up cached, which would be catastrophic.

In the VTC, the scenario seems to be when `Age > TTL`, you get a hit-for-pass. Im guessing this is not desired. Why would a backend specify the Age and no Cache-Control max-age? So now this scenario is `Age > TTL + grace` to get the undesired hit-for-pass (assuming no proper max-age). Is this the reason for the change? If so, we are just tweaking the Age range a bit while introducing a large pitfall.

Apologies if misunderstood something here.

**Comment by Dridi** [comment]
> Wouldn't this break VCLs where someone sets `beresp.ttl = 0s` and doesn't touch grace and expects the result to be hit-for-pass?

Yes, but I suppose breaking would be OK for a major release.

> Why would a backend specify the Age and no Cache-Control max-age? [...] So now this scenario is Age > TTL + grace to get the undesired hit-for-pass (assuming no proper max-age). Is this the reason for the change?

I think @mbgrydeland did it to keep the test simple, otherwise he could have set the TTL and grace via Cache-Control.

> (Edit: I realized Varnish does this... heh)

I was about to comment that varnish could be your backend, and then I saw your edit :)

**Comment by fgsch** [comment]
We could add to the builtin vcl `set beresp.grace = 0s;` in the uncacheable case to avoid breaking things.

**Comment by fgsch** [comment]
This is somewhat OBE due to 9f272127c6fba76e6758d7ab7ba6527d9aad98b0.

We will create a HfP earlier than strictly needed but if any subsequent request returns a cacheable object the HfP object will be replaced.

**Comment by nigoroll** [comment]
Some thoughts on this while revisiting:
should we maybe just remove the `beresp.ttl <= 0s` from the default hfp condition?
In general, I'd not be aware that backends would use `Age > max_age` as a "don't cache" indicator, so I suspect the existing code was more motivated to allow for the set `beresp.ttl = -1` shortcut?

**Comment by fgsch** [comment]
@nigoroll removing the condition will affect every person that:

1. Relying on this to get an uncacheable object (and subsequent HfP/HfM) and
2. Setting `beresp.ttl = 0s` thinking this is how you mark an object not cacheable.

Every person being a LOT of people in my experience.

**Comment by nigoroll** [comment]
@fgsch I fully agree with you. This would be a breaking change. Or rather: a breaking cleanup.

The VCL way to mark an object for hfm/hfp now is `set beresp.uncacheable` / `return (hit_for_pass())`, so I wonder if the builtin.vcl should continue to support this indirect way to trigger a hfp.
My understanding is that the buitin.vcl should DTRT for a well behaving backend (we've already fallen behind with this goal, btw), and for this purpose the `beresp.ttl` would only be zero or negative if the backend dilivered an object with `Age > max_age`.

**Comment by fgsch** [comment]
@nigoroll I think you are underestimating the amount of people this will affect negatively.
Just to be clear, if we remove this said users will experience request serialization.
If I have to estimate how many that is I'd say north of 60%.

Furthermore, a backend sending max-age or s-maxage of 0 will also be affected.

This check is a safety measure, as is the check for Cookie in vcl_recv{} or Set-Cookie in vcl_backend_response{}.

**Comment by nigoroll** [comment]
irc log - wanted to make sure that @fgsch and myself are in sync - and we are. So my suggestion is probably incompatible with existing "best (VS) practice".

> (22:00:09) slink: hi fgs can we talk about the builtin.vcl v_b_f for a sec?
> (22:00:16) slink: v_b_r sry
> (22:00:49) fgs: we can
> (22:00:53) fgs: hi
> (22:04:30) slink: So first of all I'd like to be sure that you get me right: I was _only_ suggesting to remote the _first_ condition of
> (22:04:30) slink:     } else if (beresp.ttl <= 0s ||
> (22:04:30) slink:       beresp.http.Set-Cookie ||
> (22:04:30) slink: ...
> (22:04:35) slink: did i get this across?
> (22:05:13) fgs: Is it anywhere else in that file to be confused? :-)
> (22:05:19) slink: ok
> (22:06:02) slink: so do I understand correctly that >60% of our users use set beresp.ttl = 0s or negative to trigger a hfp/hfm in the builtin.vcl?
> (22:06:35) slink: rather: trigger a hfp/hfm by falling through to the builtin.vcl v_b_r 
> (22:07:02) fgs: I'd say a big majority of that number is people setting beresp.ttl to 0 because they don't want to cache
> (22:07:11) fgs: but yes
> (22:07:30) slink: without any return(deliver) following before falling through to the builtin?
> (22:07:39) hugo [hugo@host107.g12.varnish-software.com] entered the room.
> (22:07:42) fgs: yes
> (22:08:27) fgs: At VS we used to suggest to fallback to the builtin logic because of this (among other things)
> (22:08:32) fgs: people setting beresp.ttl to 0
> (22:08:37) slink: ok
> (22:08:42) slink: that explains a lot
> (22:08:44) fgs: Not once, not twice, but most of the time
> (22:09:01) slink: case closed for me :)
>

**Comment by nigoroll** [comment]
@fgsch and myself agree and @rezan had also pointed out that the initial suggestion in this ticket would break the _set ttl to 0 to get hfm/hfp_ semantics, so it seems we should close this ticket and just keep it as is?

**Comment by bsdphk** [comment]
Timed out.
