### ISSUE TITLE
Panic assert in vca_close_session

### ISSUE THREAD

**Issue by matthewnourse** [varnishcache/varnish-cache#1973]
## Current Behavior
One of my customers is running Varnish on three servers.  The only purpose of the servers is to run Varnish.  This setup has been rock solid for at least 2 years now, dealing with ~2M hits a day with a load average that's almost always <1.  However on June 5 and 6 (Sydney AU time) all 3 servers hit a load average of 150 then the Varnish child crashed and was restarted.  This incident happened at different times for each server.  The servers are behind a load balancer and the hosting provider reported no traffic spikes, suggesting that it wasn't a big spike in real load.  The last incident was hours after the first.  One of the servers experienced the incident twice.

Sample log file fragment:
```
Jun  6 01:30:01 559274-varnish2 abrt[32520]: Saved core dump of pid 1869 (/usr/sbin/varnishd) to /var/spool/abrt/ccpp-2016-06-06-01:28:57-1869 (14599852032 bytes)
Jun  6 01:30:01 559274-varnish2 abrtd: Directory 'ccpp-2016-06-06-01:28:57-1869' creation detected
Jun  6 01:30:01 559274-varnish2 varnishd[1868]: Child (1869) died signal=6 (core dumped)
Jun  6 01:30:01 559274-varnish2 varnishd[1868]: Child (1869) Panic message: Assert error in vca_close_session(), cache_acceptor.c line 389:#012  Condition(i == 0 || errno != EBADF) not true.
errno = 9 (Bad file descriptor)
thread = (cache-worker)
ident = Linux,2.6.32-504.1.3.el6.x86_64,x86_64,-smalloc,-smalloc,-hcritbit,epoll
Backtrace:
  0x42ff68: /usr/sbin/varnishd() [0x42ff68]
  0x40c0bb: /usr/sbin/varnishd(vca_close_session+0x6b) [0x40c0bb]
  0x419a0f: /usr/sbin/varnishd(CNT_Session+0xdaf) [0x419a0f]
  0x431cb1: /usr/sbin/varnishd() [0x431cb1]
  0x7f8dfae42aa1: /lib64/libpthread.so.0(+0x7aa1) [0x7f8dfae42aa1]
  0x7f8dfab8f93d: /lib64/libc.so.6(clone+0x6d) [0x7f8dfab8f93d]
sp = 0x7f8becde6008 {
  fd = 2625, id = 2625, xid = 0,
  client = 52.63.65.231 63163,
  step = STP_WAIT,
  handling = deliver,
  restarts = 0, esi_level = 0
  flags = 
  bodystatus = 0
  ws = 0x7f8becde6080 { 
    id = "sess",
    {s,f,r,e} = {0x7f8becde6c78,+24,(nil),+65536},
  },
  http[req] = {
    ws = 0x7f8becde6080[sess]
      "",
      "/ah/script/prototype.js",
      "HTTP/1.1",
      "Host: [host]",
      "Connection: keep-alive",
      "Accept: */*",
      "User-Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2369.0 Safari/537.36",
      "Referer: http://[host]/ah/country/rent-residential?utm_source=excite&utm_medium=cpc&utm_content=DB-2_7_159_2152_4110845140&utm_term=rental%20property%20queanbeyan%20region&utm_campaign=c-all-rent-traffic",
      "Accept-Language: en-us,en;q=0.8",
      "X-Redirect: ",
      "X-Device: pc",
      "client-ip: 52.63.65.231",
      "Cookie: PROF-COOKIE-INSERT-V2=rd1o00000000000000000000ffffc0a81444o80",
      "X-Forwarded-For: 52.63.65.231",
      "Accept-Encoding: gzip",
      "X-Stats-Backend: ah_http",
      "X-Stats-HitMiss: hit",
      "X-Stats-Status: 200",
      "X-Stats-Key: ah_http.hit.200",
  },
  worke
```

## Steps to Reproduce (for bugs)
We haven't been able to reproduce this and it hasn't recurred.

## Context
This is not a big problem for the customer because Varnish restarted so promptly and has been very reliable overall.  I'm just reporting the incident in case it helps you.  Thanks for Varnish!

## Your Environment
* Version used: Varnish 3.0.7
* Operating System and version: CentOS 6.7
* Architecture: x86_64
* Kernel version: 2.6.32

**Comment by lkarsten** [comment]
Hi. Varnish 3.0 is end of life.

Please try 4.1 or master and let us know if you see similar issues there.

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to port.
