### ISSUE TITLE
session_max is a nop

### ISSUE THREAD

**Issue by fgsch** [varnishcache/varnish-cache#1974]
session_max was dropped in 4.0.

From an email exchange with phk in varnish-dev:

> >This looks like a relic from V3.
>
> Sort of, as I said in the previous email, we should be able to fail
> at creating more sessions (cant or wont) and this used to be the limit.
>
> If anything, we should move the other way and make it work again.

This was related to another email I sent to varnish-dev:

> >SES_New() will never return NULL. Replace noop with AN().
>
> That is actually in preparation/reminder that it should be allowed
> to fail, so I'd prefer to retain it.

Filling it here so it's not lost.

**Comment by fgsch** [comment]
@nigoroll did you forget to close this after 080ce03f238481e462622bcdb3f2dd30ecfae98f or you GC'd it before discussing this?

**Comment by nigoroll** [comment]
@fgsch wasn't aware of it, thanks.
So then we need to re-implement it...

**Comment by nigoroll** [comment]
@fgsch assinging to myself because I thought I should clean up after having fucked up. I do not want to take this from you, so if you want to do the patch, feel free.

**Comment by fgsch** [comment]
Consensus on bugwash: not missed ergo not needed.

**Comment by hermunn** [comment]
Backport review: Nothing commitet, nothing to backport.
