### ISSUE TITLE
Testsuite summary for Varnish trunk (Error)

### ISSUE THREAD

**Issue by Rod-Gomes** [varnishcache/varnish-cache#1977]
I'm following [this tutorial](https://www.varnish-cache.org/docs/trunk/installation/install.html#compiling-varnish-from-source) to compile Varnish from source.
Because I want to apply [this fix](https://github.com/varnishcache/varnish-cache/commit/a0c0481e4f0f9e578e6a062645c62c6ebffe118e), this error is causing many problems for our customers.

However, when using the command "make check" I'm getting a lot of failures.

[test-suite.log.txt](https://github.com/varnishcache/varnish-cache/files/310008/test-suite.log.txt)

## Steps to Reproduce (for bugs)

`make check`

## Your Environment

* Version used: master
* Operating System and version: CentOS 7 (VirtualBox)

**Comment by Dridi** [comment]
```
dlerror: /root/varnish-cache/lib/libvmod_directors/.libs/libvmod_directors.so: cannot open shared object file: Permission denied
```

Could it be a partition mounted with `noexec` for `/root`?

**Comment by Rod-Gomes** [comment]
@Dridi I don't know, how do I check if `/root` is `noexex`?

`root@server-server10 [~]# ls -ld /root
dr-xr-x---. 35 root root 4096 Jun 11 10:07 /root/`

`root@server-server10 [~]# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
devtmpfs on /dev type devtmpfs (rw,nosuid,size=10956864k,nr_inodes=2739216,mode=755)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct,cpu)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/mapper/centos_server--server10-root on / type xfs (rw,relatime,attr2,inode64,usrquota)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=300,minproto=5,maxproto=5,direct)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
sunrpc on /var/lib/nfs/rpc_pipefs type rpc_pipefs (rw,relatime)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)
/dev/sda1 on /boot type xfs (rw,relatime,attr2,inode64,noquota)
/dev/mapper/centos_server--server10-home on /home type xfs (rw,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /var/tmp type xfs (rw,relatime,attr2,inode64,usrquota)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
devtmpfs on /home/virtfs/user1/dev type devtmpfs (rw,nosuid,noexec,relatime,size=10956864k,nr_inodes=2739216,mode=755)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/opt type xfs (ro,nosuid,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/tmp type xfs (rw,nosuid,noexec,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/usr type xfs (ro,nosuid,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/var type xfs (ro,nosuid,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/var/log type xfs (rw,nosuid,noexec,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/var/tmp type xfs (rw,nosuid,noexec,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/etc/mail type xfs (rw,nosuid,noexec,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/usr/sbin type xfs (ro,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/var/spool type xfs (rw,nosuid,noexec,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/etc/pki/tls type xfs (ro,nosuid,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/etc/pki/ca-trust type xfs (ro,nosuid,relatime,attr2,inode64,usrquota)
sunrpc on /home/virtfs/user1/var/lib/nfs/rpc_pipefs type rpc_pipefs (ro,nosuid,relatime)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/var/cpanel/email_send_limits type xfs (rw,nosuid,noexec,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/usr/local/cpanel/3rdparty/mailman type xfs (ro,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/usr/local/cpanel/3rdparty/mailman/logs type xfs (rw,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/usr/local/cpanel/3rdparty/mailman/lists type xfs (rw,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/usr/local/cpanel/3rdparty/mailman/locks type xfs (rw,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user1/usr/local/cpanel/3rdparty/mailman/qfiles type xfs (rw,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-home on /home/virtfs/user1/home/user1 type xfs (rw,relatime,attr2,inode64,usrquota)
devtmpfs on /home/virtfs/user2/dev type devtmpfs (rw,nosuid,noexec,relatime,size=10956864k,nr_inodes=2739216,mode=755)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/opt type xfs (ro,nosuid,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/tmp type xfs (rw,nosuid,noexec,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/usr type xfs (ro,nosuid,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/var type xfs (ro,nosuid,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/var/log type xfs (rw,nosuid,noexec,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/var/tmp type xfs (rw,nosuid,noexec,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/etc/mail type xfs (rw,nosuid,noexec,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/usr/sbin type xfs (ro,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/var/spool type xfs (rw,nosuid,noexec,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/etc/pki/tls type xfs (ro,nosuid,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/etc/pki/ca-trust type xfs (ro,nosuid,relatime,attr2,inode64,usrquota)
sunrpc on /home/virtfs/user2/var/lib/nfs/rpc_pipefs type rpc_pipefs (ro,nosuid,relatime)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/var/cpanel/email_send_limits type xfs (rw,nosuid,noexec,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/usr/local/cpanel/3rdparty/mailman type xfs (ro,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/usr/local/cpanel/3rdparty/mailman/logs type xfs (rw,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/usr/local/cpanel/3rdparty/mailman/lists type xfs (rw,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/usr/local/cpanel/3rdparty/mailman/locks type xfs (rw,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-root on /home/virtfs/user2/usr/local/cpanel/3rdparty/mailman/qfiles type xfs (rw,relatime,attr2,inode64,usrquota)
/dev/mapper/centos_server--server10-home on /home/virtfs/user2/home/user2 type xfs (rw,relatime,attr2,inode64,usrquota)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=2194416k,mode=700)
gvfsd-fuse on /run/user/0/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
tmpfs on /run/user/1018 type tmpfs (rw,nosuid,nodev,relatime,size=2194416k,mode=700,uid=1018,gid=1017)
tmpfs on /run/user/1058 type tmpfs (rw,nosuid,nodev,relatime,size=2194416k,mode=700,uid=1058,gid=1057)
tmpfs on /run/user/1009 type tmpfs (rw,nosuid,nodev,relatime,size=2194416k,mode=700,uid=1009,gid=1008)
tmpfs on /run/user/1002 type tmpfs (rw,nosuid,nodev,relatime,size=2194416k,mode=700,uid=1002,gid=1000)
none on /home/virtfs/user2/proc type proc (rw,relatime)
`

**Comment by fgsch** [comment]
Can you supply the output of the following commands:

* getent passwd varnish
* getent passwd vcache
* getent group varnish
* find /root/varnish-cache -ls

**Comment by Rod-Gomes** [comment]
@fgsch http://pastebin.com/sC6XfKp0

I remade the whole process, but this time in a different directory.
And guess what? Works fine!

```
# TOTAL: 505
# PASS:  505
```

I can run `make install` in a different directory?

**Comment by fgsch** [comment]
You missed 2 commands:

* umask
* getenforce

Re your question, yes. The installation path and where you compile it are different things.

**Comment by Rod-Gomes** [comment]
@fgsch Thanks!

```
# umask
0022
# getenforce
Disabled
```

**Comment by Rod-Gomes** [comment]
I need to remove the release version (4.1.2) to install this?

**Comment by fgsch** [comment]
It depends but might be easier to do so. 

If you have any further questions please use any of the existing support channels as described at https://varnish-cache.org/support/index.html.

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
