### ISSUE TITLE
Varnish 4 purge

### ISSUE THREAD

**Issue by shorman88** [varnishcache/varnish-cache#1981]
Hi,

Using **varnish 4** i'm able to do the below with BAN but not with PURGE, is there away to do the same with PURGE?

`curl -v -k -H "host: www.ayman.com && req.url ~ /ar/about-us/" -X BAN http://varnishIP:port`

Thanks

**Comment by fgsch** [comment]
Please don't use the issue tracker for questions. See https://varnish-cache.org/support/index.html.

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
