### ISSUE TITLE
Varnish 4.1 purge all variants as defined by Vary

### ISSUE THREAD

**Issue by foot01** [varnishcache/varnish-cache#1982]
In the documentation it says.

    PURGE / HTTP/1.0
    Host: example.com

"And Varnish would then discard the front page. This will remove all variants as defined by Vary."
https://www.varnish-cache.org/docs/trunk/users-guide/purging.html#http-purging

I was expecting this to purge the home page and it's compressed versions
    curl -X PURGE http://exemple.com/

But it only purges the not compressed version.

Running this seems to do the job
    curl -X PURGE http://exemple.com/ -H "Accept-Encoding: gzip"
    curl -X PURGE http://exemple.com/ -H "Accept-Encoding: deflate"

Did I understand the documentation?
Is the encoding a variant of Vary?

Thanks for your help

Ubuntu 14.04.4 amd64
varnish_4.1.2-2~trusty
apt/source.list
deb https://repo.varnish-cache.org/ubuntu/ trusty varnish-4.1

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:

**Comment by gquintard** [comment]
Please keep the issue for bugs. We have a mailing-list (https://www.varnish-cache.org/lists/mailman/listinfo/varnish-misc) and an IRC channel (#varnish on the server irc.linpro.no), and more generally: https://www.varnish-cache.org/support/

**Comment by hermunn** [comment]
Backport review: Nothing to committed, nothing to backport
