### ISSUE TITLE
Request: Varnishtest proxy support or a way to set server.ip /port and client.ip / port

### ISSUE THREAD

**Issue by JvGinkel** [varnishcache/varnish-cache#1989]
For good testing it would be great if you can create varnishtests and specify the use of a server.ip and port and a client.ip port.

Let say you have a VCL like:
```
if ( server.ip == "1.2.3.4" && server.port = 81  && client.ip = "2.3.4.5") {

```
It would be cool if you can create a varnishtest where you can test against these ip's so you know your vcl is correct. At the moment I use a self written testing script that use the proxy protocol and I'm setting the server.ip server.port client.ip and client.port that way but I can't find a way to do it with varnishtest.

**Comment by fgsch** [comment]
Have you checked the oXXXX tests in the distro?

There are some examples using the proxy protocol.

**Comment by JvGinkel** [comment]
Aha, didn't see those tests. Thank you for pointing that out. 

Nevertheless it would be very cool I think if you can do it without (ab)use the proxy command.

**Comment by fgsch** [comment]
Perhaps something like this?

```
client c1 -proxy1 "1.2.3.4:1111 5.6.7.8:5678" {
    ...
}
```

I will look into it.

**Comment by lkarsten** [comment]
Backport review: Due to the suckaddr/sockaddr change it does not apply cleanly. The argument for backporting it is that future test cases will be simpler to backport, but I don't see us making a whole lot of backend PROXY tests.

No backport to 4.1 or 4.0.
