### ISSUE TITLE
Starting varnish on Linux with boot param ipv6.disable=1 fails

### ISSUE THREAD

**Issue by denisbr** [varnishcache/varnish-cache#1991]
On linux (tested on CentOS7 with linux 3.10.0-327.13.1.el7.x86_64) if IPv6 is disabled via kernel boot parameter `ipv6.disable=1` starting varnishd without specifying an IPv4 address to `-a` will fail with the error `Error: Cannot open socket: :6081: Address family not supported by protocol`.
## Expected Behavior

Expected behaviour when IPv6 is not available on any system, and no IPv6 address was specified as a listening address, would be that varnishd binds to the specified IPv4 port. 
## Current Behavior

varnishd tries to start, successfully binds to `0.0.0.0` IPv4, but then fails to perform calls on the IPv6 socket (see [stracelogs.zip](https://github.com/varnishcache/varnish-cache/files/327289/stracelogs.zip) attached) and stops with error `Error: Cannot open socket: :6081: Address family not supported by protocol`.
## Possible Solution

varnishd needs to handle the complete absence of IPv6 gracefully. The difference between disabling via systemctl and the boot parameter seems to be that `/proc/sys/net/ipv6` is completely absent. 
## Steps to Reproduce (for bugs)
1. Boot linux with `ipv6.disable=1` kernel option 
2. Verify that `/proc/sys/net/ipv6` is absent
3. Start varnishd with `-a :6081` 
4. Observe the error
## Context

Not sure where using the boot parameter is the normal thing to do, could be virtualization environments that inject this parameter. 
## Your Environment
- Version used: varnish-cache-plus 4.1.2, and also reproduced with varnish-cache master.
- Operating System and version: CentOS Linux release 7.2.1511 (Core)

**Comment by Dridi** [comment]
I'm suspecting a bug in glibc instead, Varnish merely uses `getaddrinfo(3)`.

What's the output of `ifconfig` for the loopback interface when you boot with `ipv6.disable=1`?

**Comment by denisbr** [comment]
@Dridi:

    [root@c7-vcp41-master vagrant]# ls -la /proc/sys/net/ipv6
    ls: cannot access /proc/sys/net/ipv6: No such file or directory

    [root@c7-vcp41-master vagrant]# ifconfig lo
    lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
            inet 127.0.0.1  netmask 255.0.0.0
            loop  txqueuelen 0  (Local Loopback)
            RX packets 22719  bytes 5925788 (5.6 MiB)
            RX errors 0  dropped 0  overruns 0  frame 0
            TX packets 22719  bytes 5925788 (5.6 MiB)
            TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by fgsch** [comment]
Bug or not we should not fail if the (ipv6) address is not specified.

**Comment by denisbr** [comment]
FWIW: reproduced this on Ubuntu 16.04 (Xenial) with varnish-cache master too.
Xenial has glibc ``2.23-0ubuntu2``.

**Comment by denisbr** [comment]
Suspect commits based on light digging (in order of guesstimated likelihood):
fde2d23125673f7ead9d74abc436b8ee9c907ed9
a4a7384e689835ca8c7b64f6f2bb13ce14828192
1ff5897b6d18954fc209b68270c637a510f30e79

**Comment by bsdphk** [comment]
What is the errno from the socket operation which fails in this case ?

Can we tell "definitively does not support IPv6" from "cannot use that IPv6" somehow ?

**Comment by denisbr** [comment]
The actual error is:

```
write(2, "Error: Cannot open socket: :6081"..., 75) = 75
```

Googling the kernel-parameter gave this:
https://www.kernel.org/doc/Documentation/networking/ipv6.txt

The ipv6-module is loaded, but:

```
No IPv6 addresses will be added to interfaces, and
it will not be possible to open an IPv6 socket.
```

**Comment by hermunn** [comment]
Backport review: This will not be backported to 4.1 unless demand increases (or @denisbr says so).
