### ISSUE TITLE
Lost req.url gives misleading error

### ISSUE THREAD

**Issue by viktorgunnarson** [varnishcache/varnish-cache#1998]
When writing a regex to normalize urls I managed to write a regex that in some cases completely removes the url and this lead to Varnish responding with 500 Internal Server Error. When inspecting the logs I could see that the whole VCL was executed but at the end there was the following line:

> Error           c workspace_client overflow

After some debuging I found that this error was not due to workspace exhaustion but simply becuase the req.url was lost. As the VCL execution is continued after the header is lost one is mislead to believe the execution is going ok.

## Expected Behavior
Fail fast when the error occurs and a error message that more clearly points towards the actual error.

## Current Behavior
There is a line in the log about the lost header, but as the rest of the VCL is executed that line is "drowned". At the end there is a error pointing to the workspace which at least made me believe that the client workspace was exhausted.

## Steps to Reproduce (for bugs)
```
varnishtest "Lost req.url gives misleading error"
server s1 {} -start

varnish v1 -vcl+backend {

    sub vcl_recv {

        set req.url = regsub(req.url, "/+", "");

        return (synth(200));
    }

} -start

client c1 {
    txreq -url "/"
    rxresp
    expect resp.status == 200
} -run
```

## Your Environment
* Version used: 4.1.2
* Operating System and version: RHEL 7

**Comment by fgsch** [comment]
Dup of #1856
