### ISSUE TITLE
Sending SIGHUP to varnishlog terminates the process

### ISSUE THREAD

**Issue by rlaban** [varnishcache/varnish-cache#2003]
When sending SIGHUP to varnishlog (using -w), it crashes the process instead of reopening log files.

## Expected Behavior
varnishlog should keep running and reopen its logfile.

## Current Behavior
varnishlog exits. stracoing the process shows:

nanosleep({0, 10000000}, NULL)          = 0
nanosleep({0, 10000000}, NULL)          = 0
nanosleep({0, 10000000}, NULL)          = 0
nanosleep({0, 10000000}, NULL)          = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
--- SIGHUP {si_signo=SIGHUP, si_code=SI_USER, si_pid=25471, si_uid=117} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
munmap(0x7f380cd4b000, 84934656)        = 0
close(4)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++

## Steps to Reproduce (for bugs)

1. Run varnishlog: /usr/bin/varnishlog -a -w /var/log/varnish/varnish.log
2. Send SIGHUP: killall -HUP varnishlog
3. varnishlog is no longer running.

## Context
I want to be able to rotate the logs written by varnishlog.

## Your Environment
* Version used: varnish-4.1.1 revision 66bb824
* Operating System and version: Ubuntu Server 16.04

**Comment by lkarsten** [comment]
Expected behaviour is the documented one. In the man page: (for 4.1.3-beta2)
```
SIGNALS
       · SIGHUP

         Rotate the log file (see -w option)
```

**Comment by lkarsten** [comment]
As @fgsch stated on IRC, when running in foreground mode the correct thing to do on sighup is to exit.

If this is the case when running in daemon mode (-d), it is a bug.

systemd service files should not attempt to run these without having them fork. We've had a few rounds on this with varnishncsa already.

**Comment by rlaban** [comment]
"Fixed" it by modifying the systemd unit file to use the "forking" type.
