### ISSUE TITLE
reloading with systemd fails if /etc/default/varnish is CRLF

### ISSUE THREAD

**Issue by cherouvim** [varnishcache/varnish-cache#2006]
Doing a `service varnish reload` on ubuntu 16 fails with `Management port disabled. $DAEMON_OPTS must contain '-T hostname:port'` if the `/etc/default/varnish` is CRLF (dos/windows newlines) instead of LF (*nix newlines).

That happens if `/etc/systemd/system/varnish.service` points to `ExecReload=/usr/share/varnish/reload-vcl`.

Doing a `vi /etc/default/varnish` and `:set ff=unix` to convert, solves the problem.

**Comment by fgsch** [comment]
Moved to https://github.com/varnishcache/pkg-varnish-cache/issues/35.

**Comment by hermunn** [comment]
Backport review: Moved, nothing to backport.
