### ISSUE TITLE
Update documentation part about CLI/management port authentication paramater

### ISSUE THREAD

**Issue by akuznecov** [varnishcache/varnish-cache#2007]
Hello,

Just faced with kind of confusion after upgrading one of Varnish installations from 3.x to 4.1

Short story:

1. almost of all main `varnishd` parameters has been kept as for 3.1
2. no authentication was used for CLI terminal and invalidation/ban commands
3. invalidation stopped to work after migration because of "Authentication required" error :)

Checked trunk and 4.1 documentation about that, it says:
>> -S file
>>>>Path to a file containing a secret used for authorizing access to the management port. If not provided a new secret will be drawn from the system PRNG.

then checked source code... random secret key generated when no `-S` argument specified
okay.jpg -  previously we just skipped -S option when no authentication was required
Now we need to specify empty `-S ''` parameter for that, but it is not mentioned anywhere (except code) :)

**Comment by fgsch** [comment]
I agree with this.

 On a related note, we might want to review using '' in favour of "none" or something sysv init friendly.

**Comment by lkarsten** [comment]
Backport review: I think we should add "none" as an empty value to 4.1, while keeping the original empty string as a possiblity.

**Comment by hermunn** [comment]
Patch adapted to allow both empty string and "none" as ways of disabling the secret. Commited as 564250aec470473.
