### ISSUE TITLE
Varnish Compilation Issue CentOS 7.2/Varnish 4.0.3 revision b8c4a34

### ISSUE THREAD

**Issue by mrgray** [varnishcache/varnish-cache#2009]
I don't seem to be able to initialize Varnish because of a compilation error,

```
usr/local$ systemctl status varnish.service
â— varnish.service - Varnish a high-perfomance HTTP accelerator
   Loaded: loaded (/usr/lib/systemd/system/varnish.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2016-07-07 02:48:03 CDT; 7min ago
  Process: 11534 ExecStartPre=/usr/sbin/varnishd -C -f $VARNISH_VCL_CONF (code=exited, status=1/FAILURE)

Jul 07 02:48:03 host.domain.co varnishd[11534]: .backend_response_func = VGC_function_vcl_backend_response,
Jul 07 02:48:03 host.domain.co varnishd[11534]: .backend_error_func = VGC_function_vcl_backend_error,
Jul 07 02:48:03 host.domain.co varnishd[11534]: .init_func = VGC_function_vcl_init,
Jul 07 02:48:03 host.domain.co varnishd[11534]: .fini_func = VGC_function_vcl_fini,
Jul 07 02:48:03 host.domain.co varnishd[11534]: };
Jul 07 02:48:03 host.domain.co varnishd[11534]: Message from C-compiler:
Jul 07 02:48:03 host.domain.co varnishd[11534]: collect2: fatal error: cannot find 'ld'
Jul 07 02:48:03 host.domain.co varnishd[11534]: compilation terminated.
Jul 07 02:48:03 host.domain.co varnishd[11534]: Running C-compiler failed, exited with 1
Jul 07 02:48:03 host.domain.co varnishd[11534]: VCL compilation failed
```

ld exists and seems to be working as expected,
```
/usr/local$ whereis ld
ld: /usr/bin/ld.bfd /usr/bin/ld.gold /usr/bin/ld /usr/share/man/man1/ld.1.gz
/usr/local$ ld
ld: no input files
```

Had an issue just before this with gcc and I set its permissions to 777 to resolve it.

I then reinstalled gcc and binutils and sadly, no dice.

I also ran varnishd -C -f /etc/varnish/default.vcl and get no errors. All the Googling in the world hasn't helped.. yet.

**Any** help would be **greatly** appreciated. I've been at this way too long and it's getting hazy.

## Expected Behavior
To be able to compile and initialize Varnish.

## Current Behavior
GCC compiler error?

## Your Environment

* Version used: Varnish 4.0.3 revision b8c4a34
* Operating System and version: CENTOS 7.2 x86_64

**Comment by fgsch** [comment]
This is a local problem. Your compiler / binutils installation is borked. 
You might need to reinstall it. Not much we can do I'm afraid.

**Comment by mrgray** [comment]
If anyone ever finds this, it was a permission issues with CentOS 7.2 and WHM's compiler permissions.

**Comment by brokeyourbike** [comment]
> If anyone ever finds this, it was a permission issues with CentOS 7.2 and WHM's compiler permissions.

So how do you manage to solve it?

**Comment by mrgray** [comment]
Ah, I wish I could remember, sorry, it's been too long.

Amit Goyal
(+91) 98928 36471

**Comment by didko6a** [comment]
to @brokeyourbike  - To solve the issue you need to enter in WHM-->Compiler Access --> Disable compilers --> Allow specific users to use the compilers. --> add varnish and varnishlog and enable compilers again. After that, you will be able to start varnish. I just resolved the issue to one of our servers a few minutes ago.

**Comment by brokeyourbike** [comment]
> to @didko6a - Thanks for your reply. My issue was that I have used nightly version of the WHM, and "Disable/Enable compilers" button simply doesn't work. Now it's resolved.

**Comment by maniramav** [comment]
> to @brokeyourbike - To solve the issue you need to enter in WHM-->Compiler Access --> Disable compilers --> Allow specific users to use the compilers. --> add varnish and varnishlog and enable compilers again. After that, you will be able to start varnish. I just resolved the issue to one of our servers a few minutes ago.

This worked, Thank you @didko6a
