### ISSUE TITLE
req.ttl: retire or document+vtc  (bugwash reminder)

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2014]
No matter how well you think you know varnish, there are always little secrets lurking still. My LKVFOTD ("lesser known varnish feature of the day") is `req.ttl`:
It puts an upper bound on the ttl returned by `EXP_Ttl()`, looks like this is a leftover from the days before hash_always_miss.
We should
- document it and add a vtc for the actual function (there are vcc-focussed vtcs)
- or retire it

**Comment by fgsch** [comment]
You can use req.ttl to trigger a bgfetch. With hash_always_miss grace is ignored.
Not sure that's enough to keep it. Personally I'm in favor of less code (and knobs).

Somewhat related, I wish we have a way to control the bgfetch inside vcl_hit{}.

**Comment by nigoroll** [comment]
@fgsch, yes, an explicit `return(refresh)` or the like from `vcl_hit{}` would be far less obscure.
Regarding `req.ttl` the question is if there any other use cases?

**Comment by fgsch** [comment]
AFAICT, no.  I don't know anyone using `req.ttl` either.

**Comment by nigoroll** [comment]
Actually retiring would requite a proper fix for #1799

**Comment by nigoroll** [comment]
decision after bugwash discussion:
> (13:40:30) phk: slink, you get to mark req.ttl deprecated, to be removed in 7.0 unless users riot.

**Comment by nigoroll** [comment]
FTR related e0b02b84a9cacd042203cac14fa903afa7ec0b9b

**Comment by hermunn** [comment]
Backport review: This is now deprecated and "scheduled for removal with varnish release 7". I see no need to bring back the deprecation to 4.1 with varnish 7 so far in the future.

**Comment by pumba-lt** [comment]
What about requests with `Cache-Control: max-age=`? Clients can also control TTL. How can that be implemented using VCL?

**Comment by gquintard** [comment]
@pumba-lt use vcl_hit. https://varnish-cache.org/docs/trunk/users-guide/vcl-grace.html

**Comment by pumba-lt** [comment]
Thanks. Any VCL examples where the TTL is actually derived from `req.http.Cache-Control`?

**Comment by nigoroll** [comment]
@pumba-lt @gquintard return miss from hit needs the workaround documented in #1799 while that is still open
@pumba-lt bugs are not for questions please, see http://varnish-cache.org/support/index.html
