### ISSUE TITLE
"%r" field is wrong

### ISSUE THREAD

**Issue by joshuaspence** [varnishcache/varnish-cache#2017]
It seems that the `%r` field for `varnishncsa` is either wrong or incorrectly documented. From `man varnishncsa`:

    %r     The first line of the request. Synthesized from other fields, so it may not be the request verbatim.

This doesn't seem consistent with my findings, however. For example, consider the following request:

    HEAD /ping HTTP/1.1
    User-Agent: curl/7.35.0
    Host: 127.0.0.1:6081
    Accept: */*

I would have expected the `%r` modifier to output `HEAD /ping HTTP/1.1` but instead it outputs `HEAD http://127.0.0.1:6081/ping HTTP/1.1`.

**Comment by nigoroll** [comment]
This looks correct in master as of d1fd1accbdd2c3ea0a12a36189476581c7fa8fe0
Which version of varnish are you using?

**Comment by joshuaspence** [comment]
> varnishd -V
    varnishd (varnish-4.1.3 revision 5e3b6d2)
    Copyright (c) 2006 Verdens Gang AS
    Copyright (c) 2006-2015 Varnish Software AS

**Comment by nigoroll** [comment]
I cannot see this in 4.1.3 either. Please provide exact information to reproduce

**Comment by lkarsten** [comment]
I have 4.1.3 running and in my test I'm not able to reproduce this.

```
1 lkarsten@IMMER ~> HEAD -Used -H http://hostname/ping/
```
```
lkarsten@lima:~$ varnishncsa -F "%r"
HEAD http://hostname/ping/ HTTP/1.1
```

My guess would be that you do somehow get bitten by the implicit method coercion in vcl_miss, where HEAD requests are rewritten to GET. varnishncsa has varying behaviour when it sees multiple lines logged with the same key, in this case http method. Your VCL or a varnishlog snippet of a request should tell what is happening.

**Comment by joshuaspence** [comment]
Oh sorry, I just realized that there is a typo in my original description. Let me fix and then hopeful this will make more sense.

**Comment by joshuaspence** [comment]
Does it make sense now? If not, what information would help here?

**Comment by lkarsten** [comment]
Please don't alter the history of the ticket. How would anyone reading this issue history in the future make sense of the first 4 comments here? The best way is to add an update explaining what was wrong initially.

Can you explain why you need your service probes logged verbatim? I don't understand why this is an issue in practice.

A workaround here is to change the varnishncsa format to use "%{VCL_Log:foo}x" and then use conditionals in VCL to `std.log("foo:" + req.http.Host)` or similar. That should get you the log line content you need.

The reason for this synthesis is that we don't keep the original request line. HTTP 1.1 has many ways of representing this data, so we parse it into our representation early to avoid having to handle the differences everywhere we look for the Host header or method in use. Quick example is `GET http://localhost/ping HTTP/1.1` vs `GET /ping HTTP/1.1\r\nHost: localhost\r\n"`.

I believe this works as documented. The man page section you pasted explains that the line is synthetic.

**Comment by joshuaspence** [comment]
No, I'm not interested in logging service probes. In this case, the HEAD request is initiated by me in order to reproduce this issue, but the URL or type of request isn't significant in any way.

The reason that I care about this issie is that it has lead to inconsistencies in our logging data, specifically it means that our Varnish and nginx logs are inconsistent (nginx shows the request as `/ping` whereas Varnish shows it as `http://127.0.0.1/ping`. I could of course deal with this inconsistency within Logstash, or just change our `varnishncsa` logging format to use `%U%q` instead, but it seems like a bug to me given that the "first line of the request" is not `HEAD http://127.0.0.1:6081/ping HTTP/1.1`.

**Comment by lkarsten** [comment]
HI. Thanks for the feedback.

I think we agree that it works as documented. It may be that it is sub-optimal, but I wouldn't really call it a bug.

If you want to propose a pull-request or patch that corrects this, we're happy to review it or even help you get started. We're around on irc or the varnish-dev@ email list.

I'll leave this open a bit longer in case someone else wants to comment.

**Comment by Dridi** [comment]
> Synthesized from other fields, so it may not be the request verbatim.

This didn't sound obvious to @joshuaspence (and probably others) so we could at least add an example of what this implies. A docfix is probably easier for a pull request than an actual change in behavior.

**Comment by fgsch** [comment]
I think we should change varnishncsa to match the %r behaviour from apache and what not, potentially adding a %R to keep the existing (and arguable) non standard behaviour.

I will raise a PR.

**Comment by fgsch** [comment]
After more thinking I've changed my mind and went for updating the documentation.
I hope this makes it more clear now, let us know otherwise.

**Comment by hermunn** [comment]
Backport review: Docfix (555c3a1) is ported to 4.1 as 555c3a1.
