### ISSUE TITLE
move RFC2616_Ttl() to vmod_std ? - Force Caching of a 403

### ISSUE THREAD

**Issue by davidbarratt** [varnishcache/varnish-cache#2018]
Is there a way to force caching of a 403?

It looks like from the code, that since a 403 is not a whitelisted status, the `Cache-Control` header is ignored:

```
switch (http_GetStatus(hp)) {
    default:
        expp->ttl = -1.;
                break;
```

https://github.com/varnishcache/varnish-cache/blob/4.0/bin/varnishd/cache/cache_rfc2616.c#L112-L114
## Expected Behavior

I'd expect a way to explicitly use the `Cache-Control` header on 403 responses.
## Current Behavior

This is the best I could come up with:

```
sub vcl_backend_response {
  if (beresp.status == 403) {
    set beresp.http.X-Status = beresp.status;
    set beresp.status = 200;
  }
}

sub vcl_deliver {
    if (resp.http.X-Status) {
      set resp.status = std.integer(resp.http.X-Status, 403);
      unset resp.http.X-Status;
    }
}
```

While this properly sets and unsets the status, every request is a cache `MISS`.
## Possible Solution

Provide a way to force cache-control to be used, or allow the status to be set and reset (like above) and properly store it in cache.
## Steps to Reproduce (for bugs)

See the VCL above.
## Context

No way to cache a 403 using the Cache-Control header. :(
## Your Environment
- Version used: 4.0
- Operating System and version: ubuntu 12.04

**Comment by nigoroll** [comment]
This is a user question, please use tickets for bugs only. http://varnish-cache.org/support/index.html
IMHO, not caching a 403 by default is correct, without additional configuration Varnish cannot know the server's reasons for sending a 403 and thus cannot know under which circumstances caching would be legitimate. For your custom case, setting the `resp.ttl` in `vcl_backend_response` should work.

**Comment by davidbarratt** [comment]
@nigoroll,

I'm not disagreeing with the default behavior, I'm saying there is no way to not completely ignore the `Cache-Control` header on a 403 unless you manually parse it yourself in the VCL. :(

This is a feature request, not a question. I just wanted to make sure I wasn't missing something obvious.

**Comment by fgsch** [comment]
I don't disagree with this but I wonder if we should expose the logic in RFC2616_Ttl() to the std module.

It's not the first time something like this has been requested.

**Comment by fgsch** [comment]
@davidbarratt if we were to expose the logic, would you expect to work the same as if it was a cacheable object, i.e. parse Cache Control and Expires headers?

**Comment by davidbarratt** [comment]
@fgsch,

Yes, I'd like a 403 to work the same way a 404 or 200 would work, or any of the whitelisted status here:
https://github.com/varnishcache/varnish-cache/blob/4.0/bin/varnishd/cache/cache_rfc2616.c#L115-L123

**Comment by nigoroll** [comment]
@fgsch actually I arrived at the same conclusion in a different context - yes exposing `RFC2616_Ttl()` via `std` would make a lot of sense for other cases as well. We should even check if we can move the call from C to VCL altogether.
@davidbarratt Apologies for not understanding your intention, but 
> No way to cache a 403 using the Cache-Control header.
was a bit misleading. Varnish has VCL and you can achieve caching and parsing of Cache-Control with  VCL. It's correct though that the latter could be made easier, see before.

**Comment by nigoroll** [comment]
@fgsch any myself want to look after this whenever we have time

**Comment by fgsch** [comment]
timed-out.
