### ISSUE TITLE
Idea: include saintmode VMOD plugin with varnish

### ISSUE THREAD

**Issue by mwethington** [varnishcache/varnish-cache#2020]
Currently, only std, and directors are included on Debian when I do a apt-get install varnish.

/usr/lib/varnish/vmods# ls
libvmod_directors.so  libvmod_std.so

Suggestion: Can we include saintmode VMOD? Cookie also would be very helpful.

But Saint was a standard feature in Varnish 3, and everyone should be using it. So why not? It seems arbitrary that std and directors are included and saintmode is not.

Optionally, how about a "apt-get install varnish-saintmode" and "apt-get install varnish-cookie"

**Comment by lkarsten** [comment]
Hi Bill.

Thanks for the suggestion. We've looked at this a few times, and found that the best way is to keep most of the vmods outside of core Varnish. There is the issue of maintenance, once vmods are taken into core they can pretty much never be taken out again, and so on. We may reconsider now that the vmod landscape has settled a bit, but there are currently no plans.

To make this easier for the users, we've recently combined most of the popular vmods into the varnish- modules package, see https://github.com/varnish/varnish-modules . This has both vmod-saintmode and vmod-cookie.

If you run Debian stretch or sid, you can even do `apt-get install varnish-modules` today. We still don't have the distribution we'd like for it (more distros, freebsd, others) but it is moving forward. Any help you can lend there is much appreciated. (filing wishlist bugs, nagging packagers and so on)

Hope this gave some insight. Leaving this open for a day or two in case you/someone wants to comment.

-Lasse (with release manager hat on)

**Comment by mwethington** [comment]
I tried:

apt-get install varnish-modules

What is the repo command to get the one for wheezy/Jessie?

Thanks.

**Comment by lkarsten** [comment]
Hi. Right now you'll have to run stretch to get it out of the box. On jessie you can use our official Varnish 4.1 packages and backport varnish-modules from stretch. 

We don't package varnish-modules ourselves, we ask the distributions to handle it. (They're far better at packaging than us.)

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport
