### ISSUE TITLE
varnishstat -1 -f field inclusion glob doesn't allow VBE backend fields

### ISSUE THREAD

**Issue by r0b0ticus** [varnishcache/varnish-cache#2022]
## Expected Behavior
When trying to view individual statistics about a backend I would expect to be able to run 
`sudo varnishstat -1 -f "VBE.boot.default.happy"` OR `sudo varnishstat -1 -f VBE\.boot\.default\.happy ` and get the correct results.

This works with similar commands:
`sudo varnishstat -1  -f LCK.wstat.locks
LCK.wstat.locks          55950         0.32 Lock Operations
`

## Current Behavior
When running these commands now I get the error `-f: Wrong number of elements`.

## Steps to Reproduce (for bugs)
Run varnish with multiple backends, attempt to query individual backend fields with varnishstat -f  command.

## Context
I am trying to configure zabbix autodiscovery and monitoring of individual backends. The ability to run this for each backend would make it easier.

## Your Environment

* Version used: `varnishstat (varnish-4.1.2 revision 0d7404e)` and `varnishstat (varnish-4.0.3 revision b8c4a34)`
* Operating System and version: Tested on both RHEL 7.1 and Archlinux

**Comment by Dridi** [comment]
Confirmed for master.

```
varnishtest ""

server s1 "" -start
varnish v1 -vcl+backend "" -start

shell {varnishstat -n ${v1_name} -1 | grep VBE.vcl1.s1.happy >/dev/null}

shell {varnishstat -n ${v1_name} -1 -f LCK.wstat.locks >/dev/null}
shell {varnishstat -n ${v1_name} -1 -f VBE.vcl1.s1.happy >/dev/null}
```

**Comment by fgsch** [comment]
field assumes type.name or type.ident.name.
In the case of backends, e.g. VBE.boot.default.happy, type is VBE, ident boot.default and name happy.
This breaks the assumption in vsc.c about having a max of 3 periods (.).
You can still do things like -f "VBE.*.happy" or -f "VBE.*"  but you cannot do -f "VBE.bo*" or the full string.

**Comment by Dridi** [comment]
Workaround: `varnishstat -1 -f "VBE?boot.default.happy"`

It you want the `happy` counter for all the backends in your boot VCL:
`varnishstat -1 -f "VBE?boot.*.happy"`

**Comment by Dridi** [comment]
> This breaks the assumption in vsc.c about having a max of 3 periods (.).

@r0b0ticus also reported this problem for 4.0.3 (haven't checked yet) where backends can also contain an IPv4 address. Does it mean that we can't filter backends based on an IP address with `-f`?

I haven't looked at the details in vsc.c yet, but it sounds like an assumption that shouldn't be made.

**Comment by fgsch** [comment]
Sorry, not 3 periods but 3 parts, which corresponds to type, name an indent.
I guess having a period within a particular field was not considered / originally supported.

**Comment by nigoroll** [comment]
bugwash: @Dridi  to look after this, change implementation to be just a glob match on the stats string, no special handling of dots

**Comment by hermunn** [comment]
Backport review: This will not be backported to 4.1, as the workarounds seem good enough to me.
