### ISSUE TITLE
panic vmod_rr_resolve() round_robin.c line 75 (be) != NULL

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2024]
panic after 6 minutes running on 1ce9cfc - no unusual activity

```
Panic at: Mon, 25 Jul 2016 20:22:06 GMT
"Assert error in vmod_rr_resolve(), round_robin.c line 75:
  Condition((be) != NULL) not true.
thread = (cache-worker)
version = varnish-trunk revision 1ce9cfc
ident = -jsolaris,-smalloc,-smalloc,-hcritbit,ports
Backtrace:
  454990: pan_backtrace+0x1d
  454d52: pan_ic+0x25e
  ffffbf7ff4a05ffa: libvmod_directors.so'vmod_rr_resolve+0x27b [0xffffbf7ff4a05ffa]
  434795: vdi_resolve+0x14b
  43493c: VDI_GetHdr+0xde
  43e386: vbf_stp_startfetch+0x299
  441242: vbf_fetch_thread+0x36f
  472692: Pool_Work_Thread+0x4d6
  471395: WRK_Thread+0x299
  4727c2: pool_thread+0x96
busyobj = f417030 {
  ws = f4170b0 {
    id = \"bo\",
    {s, f, r, e} = {f41ff68, +512, 0, +225440},
  },
  retries = 0, failed = 0, flags = {do_stream},
  director_req = 8af310 {
    vcl_name = php_rr,
    type = round-robin {
    },
  },
  http[bereq] = f417678 {
    ws[bo] = f4170b0,
    hdrs {
      \"GET\",
      \"/*redacted*\",
      \"HTTP/1.1\",
      \"Host: *redacted*\",
      \"*redacted*\",
      \"*redacted*\",
      \"Via: 1.1 *redacted*\",
      \"Accept-Encoding: gzip\",
      \"Surrogate-Capability: *redacted*=%22Surrogate/1.0 ESI/1.0%22\",
      \"X-Forwarded-For: *redacted*\",
      \"X-Varnish: 1376745\",
    },
  },
  http[beresp] = f417af0 {
    ws[bo] = f4170b0,
    hdrs {
    },
  },
  objcore[fetch] = f973250 {
    refcnt = 2,
    flags = {busy},
    exp_flags = {},
    boc = f95b670 {
      refcnt = 2,
      state = req_done,
      vary = 0,
      stevedore_priv = 0,
    },
    exp = {0.000000, 0.000000, 0.000000, 0.000000}
    objhead = f9c1ad0,
    stevedore = 0,
  },
  vcl = {
    busy = 70
    discard = 0,
    state = auto,
    temp = warm,
    conf = {
      srcname = {
        \"/etc/varnish/default.vcl\",
        \"Builtin\",
      },
    },
  },
},

"

```

**Comment by nigoroll** [comment]
Interesting. This looks exactly like #2005 and #1898 but the platform is different: The other issues were for linux and the one I had a detailed look at was KVM so I suspected this to be related - but this panic was on SmartOS, so there is no hypervisor to blame.

**Comment by nigoroll** [comment]
this got introduced with be69a0329c49e46a378599afa48dbd8c10f7bcb4

**Comment by fgsch** [comment]
I'm on my mobile so cannot check the code  but my first thought is whether
we should consider reverting this change.

Any reason not to?

**Comment by Dridi** [comment]
@fgsch I think this change was prep work for allowing add/delete operations after the init phase, enabling dynamic backends in the built-in directors.

**Comment by nigoroll** [comment]
I think we should keep the reader/writer lock to improve concurrency with the potentially higher amount of traffic for dynamic backends - plus many directors will actually only issue read access.
If anything I'd vote for rw access of the rr director.

**Comment by Dridi** [comment]
Summoning @slimhazard

**Comment by nigoroll** [comment]
@Dridi the original code aquired a mutex always, so that would also avoid the race. But @slimhazard (whom I pinged by email also) intended to improve concurrency. This was something we discussed at the Rotterdam VDD IIUC

**Comment by hermunn** [comment]
Backport review: Backported as 9edb2b653f531b

**Comment by rnsanchez** [comment]
@hermunn: any chances b8290db is going to be backported to 4.1?

**Comment by hermunn** [comment]
@rnsanchez I will work on backporting this week, and make sure this is considered.

**Comment by rnsanchez** [comment]
Great news!  4.1 is hitting this issue from time to time in production.

**Comment by hermunn** [comment]
The patch b8290db has been back ported as 1ec38efb6.
