### ISSUE TITLE
`varnishtop` appears to ignore `-p` (period) option when `-1` is used

### ISSUE THREAD

**Issue by b4hand** [varnishcache/varnish-cache#2025]
Here's a concrete example:

```
$ varnishtop -1 -i BerespStatus; varnishtop -p 5 -1 -i BerespStatus
  3478.00 BerespStatus 206
  3478.00 BerespStatus 206
```
Note the 206 status codes are the dominant responses I expect to get, so that's not the problem.

The issue is that the average rate for a 5 second interval, should almost certainly be less than the average rate for a 60 second interval, which is what the man page for `varnishtop` claims is the default value for the `-p` option.

I see the same results if I specify `-p 60` as well:

```
$ varnishtop -p 60 -1 -i BerespStatus; varnishtop -p 5 -1 -i BerespStatus
  3113.00 BerespStatus 206
  3113.00 BerespStatus 206
```

Here's another example using `-p 10`:

```
$ varnishtop -p 60 -1 -i BerespStatus; varnishtop -p 10 -1 -i BerespStatus
  3074.00 BerespStatus 206
  3074.00 BerespStatus 206
```

And in fact, it doesn't appear to matter at all what value that I pass to `-p`, I get the same results.

## Expected Behavior
The expected behavior is that `varnishtop` reports the average number of requests seen during the period given by the `-p` option as stated in the `varnishtop` man page:

> -p period
>             Specified the number of seconds to measure over, the default is 60 seconds.
> The first number in the list is the average number of requests seen over this time period.

## Current Behavior
I believe it is always counting over all of the logs available in the SHM rather than using the specified period from the command line option. Looking at the code of `varnishtop`, it appears the [`period`](https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishtop/varnishtop.c#L65) variable is never used within the [`accumulate`](https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishtop/varnishtop.c#L117-L181) function.

## Possible Solution
I think when the `-1` option is specified, it makes most sense to only consider the most recent time interval, so the solution would be to start at the top of the SHM, but only consider the logs within the time duration of the last 60 seconds or period seconds if specified.

The current behavior with `-1` is a little strange because the log is over an unknown quantity of requests based on the buffer size of the SHM, so its hard to pick out meaningful measurements using `varnishtop -1`. Alternatively, I could see an option that only takes the last N requests if you want a sample over a count of requests rather than a sample over a time interval.

## Steps to Reproduce (for bugs)

Already provided above.

## Context
I'm trying to report status code counts using `varnishtop` and `statsd` for monitoring purposes. 

## Your Environment
* Version used: varnishtop (varnish-4.1.2 revision 0d7404e)
* Operating System and version: Ubuntu 12.04.5

**Comment by gquintard** [comment]
The current behaviour makes sense since -1 implies -d, and you are just parsing the whole VSL.

The issue with the expected behaviour you propose is that log lines don't record their time of entry, so it's not possible.

However, you could use the -q parameter to only get the XVID finished in the last X seconds. That's a compromise, but it's pretty simple to do.

**Comment by b4hand** [comment]
At a minimum, it would seem you should update the documentation on the `-p` flag to say it has no effect in `-1` mode. Also, can you give an example of what the `-q` would look like for this work around?

**Comment by gquintard** [comment]
We would gladly consider a PR (or even the corrected version of the document) if you feel the man page is inadequate.

I will refer you to to the man pages vsl-query  (example section) and vsl (TimeStamp section), but as an example, you could use `-q "Timestamp:Resp[1] > 1472053199.0"`

**Comment by hermunn** [comment]
Backport review: Nothing commited - nothing to backport.
