### ISSUE TITLE
Racy backend selection

### ISSUE THREAD

**Issue by gquintard** [varnishcache/varnish-cache#2027]
We tripped on a WRONG():

-- panic.show -- 
Last panic at: Sun, 31 Jul 2016 01:43:54 GMT 
"Wrong turn at vdir.c:209:

thread = (cache-worker) 
version = varnish-4.1.3 revision 5e3b6d2 
ident = 
Linux,2.6.32-573.18.1.el6.x86_64,x86_64,-junix,-sfile,-sfile,-sfile,-smalloc,-hcritbit,epoll 

It looks like that while in vdir_pick_by_weight, somebody in vdir_pick_be changes vd->vbm under us.

## Expected Behavior
Not panicking would be nice

## Possible Solution
Switching vdir_pick_be lock acquisition to vdir_wrlock instead of vdir_rdlock.

## Your Environment
EL6, varnish 4.1.3

**Comment by slimhazard** [comment]
As discussed in IRC, I will look into this.

**Comment by hermunn** [comment]
Backport review: Fix backported as c3374b185e7db43db673
