### ISSUE TITLE
Should FetchError (Could not get storage) return a status of 200?

### ISSUE THREAD

**Issue by allanwind** [varnishcache/varnish-cache#2038]
I was surprised that Debian did not convert my config file in /etc/default/varnish when switching from initd to systemd, and a result I ended up with a different configuration (-s malloc,256m instead of file:/var/lib/varnish/pawan/varnish_storage.bin,32G) than I had setup.  This in turn caused large video files greater than the 256m size to be truncated, and yet varnish would return a 200 status to the client.  The browser would fail almost immediately as it would not get the promised content-length of data.

## Expected Behavior

I am not really sure what the correct behavior is here.  Should varnish drop the backend content on floor and return 500 or 507?

## Current Behavior

Here is an example request showing the problem:

[http://pastebin.com/Yqvfq074]

## Steps to Reproduce (for bugs)

1. configure varnish with -s malloc,_something_
2. restart varnish
3. request a file larger than _something_

## Context

I recently started serving a few large video files, and they would silently (at least to me as the admin) fail.

## Your Environment

* Version used: 4.1.3
* Operating System and version: Debian GNU/Linux 8.5 (jessie)

**Comment by fgsch** [comment]
Test case:

```
varnishtest ""                                                                                                                                     
 
server s1 {
        rxreq
        txresp -bodylen 1500000
} -start
 
varnish v1 -arg "-s malloc,1m" -vcl+backend {
 
} -start
 
client c1 {
        txreq
        rxresp
} -run
```

**Comment by fgsch** [comment]
FWIW, this is due to streaming being enabled.  Disabling streaming should work as expected.

**Comment by allanwind** [comment]
I had not configured streaming (my default.vcl just had vcl 4.0 and a single backend with a host and port), so it must be default behavior.  Irregardless, if varnish runs out of resources, and returns non-compliant content, it should not return a 200 should it?

**Comment by lkarsten** [comment]
Extracted varnishlog snippet from pastebin link for safe keeping:

```
*   << Request  >> 42121     
-   Begin          req 42120 rxreq
-   Timestamp      Start: 1470849892.110111 0.000000 0.000000
-   Timestamp      Req: 1470849892.110111 0.000000 0.000000
-   ReqStart       127.0.0.1 45197
-   ReqMethod      GET
-   ReqURL         /blob/<redacted>.mp4
-   ReqProtocol    HTTP/1.1
-   ReqHeader      User-Agent: curl/7.38.0
-   ReqHeader      Accept: */*
-   ReqHeader      Host:lifeintegrity.com
-   ReqHeader      X-Forwarded-For: 127.0.0.1
-   VCL_call       RECV
-   VCL_return     hash
-   VCL_call       HASH
-   VCL_return     lookup
-   VCL_call       MISS
-   VCL_return     fetch
-   Link           bereq 42122 fetch
-   Timestamp      Fetch: 1470849892.111039 0.000928 0.000928
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Date: Wed, 10 Aug 2016 17:24:52 GMT
-   RespHeader     Server: Apache/2.4.10
-   RespHeader     Last-Modified: Sat, 06 Aug 2016 17:29:25 GMT
-   RespHeader     ETag: "1eb022c7-5396a863cc740"
-   RespHeader     Content-Length: 514859719
-   RespHeader     Cache-Control: max-age=2592000
-   RespHeader     Expires: Fri, 09 Sep 2016 17:24:52 GMT
-   RespHeader     Content-Type: video/mp4
-   RespHeader     X-Varnish: 42121
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   VCL_return     deliver
-   Timestamp      Process: 1470849892.111058 0.000947 0.000019
-   RespHeader     Accept-Ranges: bytes
-   Debug          "RES_MODE 2"
-   RespHeader     Connection: keep-alive
-   Timestamp      Resp: 1470849892.644535 0.534424 0.533477
-   ReqAcct        121 0 121 374 268424525 268424899
-   End            
**  << BeReq    >> 42122     
--  Begin          bereq 42121 fetch
--  Timestamp      Start: 1470849892.110254 0.000000 0.000000
--  BereqMethod    GET
--  BereqURL       /blob/<redacted>.mp4
--  BereqProtocol  HTTP/1.1
--  BereqHeader    User-Agent: curl/7.38.0
--  BereqHeader    Accept: */*
--  BereqHeader    Host:lifeintegrity.com
--  BereqHeader    X-Forwarded-For: 127.0.0.1
--  BereqHeader    Accept-Encoding: gzip
--  BereqHeader    X-Varnish: 42122
--  VCL_call       BACKEND_FETCH
--  VCL_return     fetch
--  BackendOpen    23 boot.default 127.0.0.1 8080 127.0.0.1 50592
--  BackendStart   127.0.0.1 8080
--  Timestamp      Bereq: 1470849892.110508 0.000254 0.000254
--  Timestamp      Beresp: 1470849892.110969 0.000715 0.000460
--  BerespProtocol HTTP/1.1
--  BerespStatus   200
--  BerespReason   OK
--  BerespHeader   Date: Wed, 10 Aug 2016 17:24:52 GMT
--  BerespHeader   Server: Apache/2.4.10
--  BerespHeader   Last-Modified: Sat, 06 Aug 2016 17:29:25 GMT
--  BerespHeader   ETag: "1eb022c7-5396a863cc740"
--  BerespHeader   Accept-Ranges: bytes
--  BerespHeader   Content-Length: 514859719
--  BerespHeader   Cache-Control: max-age=2592000
--  BerespHeader   Expires: Fri, 09 Sep 2016 17:24:52 GMT
--  BerespHeader   Content-Type: video/mp4
--  TTL            RFC 2592000 10 -1 1470849892 1470849892 1470849892 1473441892 2592000
--  VCL_call       BACKEND_RESPONSE
--  VCL_return     deliver
--  Storage        malloc s0
--  ObjProtocol    HTTP/1.1
--  ObjStatus      200
--  ObjReason      OK
--  ObjHeader      Date: Wed, 10 Aug 2016 17:24:52 GMT
--  ObjHeader      Server: Apache/2.4.10
--  ObjHeader      Last-Modified: Sat, 06 Aug 2016 17:29:25 GMT
--  ObjHeader      ETag: "1eb022c7-5396a863cc740"
--  ObjHeader      Content-Length: 514859719
--  ObjHeader      Cache-Control: max-age=2592000
--  ObjHeader      Expires: Fri, 09 Sep 2016 17:24:52 GMT
--  ObjHeader      Content-Type: video/mp4
--  Fetch_Body     3 length stream
--  ExpKill        LRU_Cand p=0x7f923d7b4840 f=0x8 r=3
--  ExpKill        LRU_Fail
--  FetchError     Could not get storage
--  BackendClose   23 boot.default
--  BereqAcct      190 0 190 303 268424525 268424828
--  End
```

**Comment by bsdphk** [comment]
Basically we cannot do what you are asking about.

By the time we find out we cannot get storage, we already sent the 200 status code (because we're streaming) and there is now way to go back and change it.

**Comment by allanwind** [comment]
Thanks for the quick response.

Why is varnish allocating space for the entire backend response 
when streaming?  beresp.do_stream is documented as
"Deliver the object to the client directly without fetching the 
whole object into varnish. If this request is pass'ed it will not 
be stored in memory."  Is it to respond with the cached copy on 
the 2nd request?  If so, should varnish not gracefully degrade to 
streaming (but not caching) oppose to fail on all responses?

If something can go wrong, should varnish not defer sending the 
status till it's past that gate?  The benefit of streaming is
mainly the large body and not the header, right?

On 2016-08-15 04:20:41, Poul-Henning Kamp wrote:
> Basically we cannot do what you are asking about.
> 
> By the time we find out we cannot get storage, we already sent the 200 status code (because we're streaming) and there is now way to go back and change it.
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/varnishcache/varnish-cache/issues/2038#issuecomment-239780512

-- 
Allan Wind
Yaxto - Runs My Business
<https://yaxto.com>

**Comment by nigoroll** [comment]
To not leave your questions unanswered, despite the fact that issues are not a support forum:
* varnish is not actually allocating all of the space for objects at once - which would only be possible for the case that the backend sends `Content-Length` anyay
* For the case that the backend does send a `Content-Length` and you know that the object won't fit into your cache, you can decide to make it uncacheable in `vcl_backend_response`
  * we could do something similar in core code, but after all this is what vcl is for
* the `do_stream` documentation was not ideal, I have improved it just now. Thanks for the feedback.
* Falling back from streaming to something like a multi-client-pass for the case that we don't get enough storage as you suggest would be an option - but not that easy to implement. In particular, there is only one backend request, so if there are many clients streaming the same object and they read at different speeds, we would still need substantial amounts of memory even if we started to free behind the last reader. Alternatively, opening new backend connections may not even be possible because the object we're streaming may have ceased to exist or may have changed. This all gets really messy, we shouldn't do any of this for a special corner case fixing a wrongly sized cache size.
  * basic advise: just get enough cache for your application
* "Defer sending status" is just what `do_stream = false` does. But we can't stream the body without having sent the header first.

**Comment by nigoroll** [comment]
> (if) the object won't fit into your cache, you can decide to make it uncacheable in vcl_backend_response
Actually this may still use considerable amounts of memory, because varnish still tries to read the backend response at maximum speed.
If you need to minimize memory usage, use pipe mode (and keep the `Connection: close` header in `vcl_pipe` - see the `builtin.vcl`)

**Comment by iwikus** [comment]
I agree it is very strange to return HTTP 200 when there was an error. Found this old thread, when hit
**FetchError     Could not get storage**

**Comment by gquintard** [comment]
@iwikus, this is because of streaming, and mainly due to how HTTP works. You can disable streaming (`set beresp.do_stream = false`), but that will force you to wait until Varnish has itself downloaded the object before it can deliver it to you

**Comment by nigoroll** [comment]
@iwikus see [the explanation](https://github.com/varnishcache/varnish-cache/issues/2038#issuecomment-241664518). You can also use [a storage engine which never fails under normal circumstances](https://gitlab.com/uplex/varnish/slash).
