### ISSUE TITLE
Coverity uploads are broken

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#2043]
>     Your request for analysis of varnish  is failed.
>     Analysis status: Failure
>     Please fix the error and upload the build again.
> 
>     Error details:
>     Unknown Coverity Build tool version
> 

email received at: Thu, Aug 18, 2016 at 3:32 AM.

Currently the Coverity uploads happens from jenkins. The script run is fairly basic. We should change it to run on the new server (if there is a freebsd version of coverity), or have them pull&build directly from github if that is possible.

The current job is here: https://jenkins.varnish-software.com/job/varnish-master-coverity-upload/ , behind auth since there is an upload token there. Based on the fallout if someone runs off with our upload token, it doesn't seem necessary to keep the contents of this job secret in the future.

**Comment by Dridi** [comment]
As a suggestion, we can give that job to Travis.

In cashpack [1] I have a fairly large build matrix but I only trigger coverity builds for updates on the `coverity_scan` branch. I use the coverity add-on so that I don't have to maintain the integration.

That would mean having a dedicated branch in this repository.

Dridi

[1] https://github.com/Dridi/cashpack/blob/master/.travis.yml

**Comment by Dridi** [comment]
My workflow is fairly simple:

1. Wondering how things are doing
2. `git push origin master:coverity_scan`
3. Awaiting results

**Comment by fgsch** [comment]
Indeed. The token can be added securely via the travis UI too.

**Comment by lkarsten** [comment]
Documented the current setup a bit. https://github.com/varnishcache/varnish-cache/wiki/Coverity-scans

**Comment by lkarsten** [comment]
weekly job is now running again on:

```Coverity Build Capture (64-bit) version 8.5.0.2 on Linux 3.16.0-4-amd64 x86_64```

Closing.

**Comment by hermunn** [comment]
Backport review: Nothing commited - nothing to backport.
