### ISSUE TITLE
Official dockerfile for base image of varnish

### ISSUE THREAD

**Issue by shaunwarman** [varnishcache/varnish-cache#2045]
The [INSTALL](https://github.com/varnishcache/varnish-cache/blob/master/INSTALL) provides nice documentation and tools for easy install. It would also be great to have an official Dockerfile for base image to add configuration onto or to consume a default.vcl file.

I see a couple in the wild, but unsure if these are referenced by the official varnish team. Just a thought and suggestion! Thanks for the configure and make files!

**Comment by bsdphk** [comment]
Thanks for the suggestion, once somebody submits the necessary script/patch/code to do it, we'll look at it.
