### ISSUE TITLE
Retrieve info about child restarts

### ISSUE THREAD

**Issue by oesteve** [varnishcache/varnish-cache#2046]
Hello,

I have 2 instances of varnish running behind an haproxy on two different virtual machines with centos 7, with two different versions (varnish-4.1.3 revision 5e3b6d2 and varnish-4.1.2 revision 0d7404e ) from offical rpm repository. Sometimes, after 3 o 6 hours,
both instances crashed with a few seconds of difference, the child proccess died and then they was reset in 3 or 4 times.

	Aug 21 13:23:37 VARNISH01 varnishd[27752]: Child (9432) died signal=11
	Aug 21 13:23:37 VARNISH01 varnishd[27752]: Child (20424) said Child starts
	..
	Aug 21 13:23:45 VARNISH01 varnishd[27752]: Child (20424) died signal=11
	Aug 21 13:23:45 VARNISH01 varnishd[27752]: Child (21045) said Child starts
	..
	Aug 21 13:24:04 VARNISH01 varnishd[27752]: Child (21045) died signal=11
	Aug 21 13:24:04 VARNISH01 varnishd[27752]: Child (21686) said Child starts
	--
	Aug 21 13:25:52 VARNISH01 varnishd[27752]: Child (21686) died signal=11
	Aug 21 13:25:52 VARNISH01 varnishd[27752]: Child (22392) said Child starts

varnishadm don't capture any panic trace

	varnish> panic.show 
	300        
	Child has not panicked or panic has been cleared

Finally I don't found any core dump in the system

How can I get more info about those crashes?

Thank you for the help.

**Comment by nigoroll** [comment]
see https://www.varnish-cache.org/docs/trunk/users-guide/troubleshooting.html#varnish-is-crashing-segfaults

**Comment by hermunn** [comment]
Backport review: Nothing commited - nothing to backport.
