### ISSUE TITLE
varnish 4.1.3 fails to compile with Solaris Studio 12.5 because some exported functions are static

### ISSUE THREAD

**Issue by skrueger8** [varnishcache/varnish-cache#2047]
## Expected Behavior
varnish compiles fine

## Current Behavior
it fails with:

```
  CCLD     libvarnishapi.la
Undefined                       first referenced
 symbol                             in file
VSB_extend                          .libs/libvarnishapi.so.1.0.4.exp
VSB_newbuf                          .libs/libvarnishapi.so.1.0.4.exp
VSB_put_byte                        .libs/libvarnishapi.so.1.0.4.exp
VAS_Fail_default                    .libs/libvarnishapi.so.1.0.4.exp
VSB_extendsize                      .libs/libvarnishapi.so.1.0.4.exp
ld: warning: symbol referencing errors
```

## Possible Solution
remove "static":

1. lib/libvarnish/vsb.c

```
static int
VSB_extend(struct vsb *s, int addlen)
{
...

static struct vsb *
VSB_newbuf(struct vsb *s, char *buf, int length, int flags)
{
...

static void
VSB_put_byte(struct vsb *s, int c)
{
...

static int
VSB_extendsize(int size)
{
```

2. lib/libvarnish/vas.c

remove "static":

```
static void __attribute__((__noreturn__))
VAS_Fail_default(const char *func, const char *file, int line,
    const char *cond, enum vas_e kind)
{
```

## Steps to Reproduce (for bugs)
1. fix configure not detecting c99 capable Solaris Studio 12.5, comment out line 12830 and 12831
2. fix configure's default -Wall -Werror CFLAGS (Solaris Studio compiler can't handle them), delete them from lines 17250 and 17251
3. `CC=cc CFLAGS='-mt -O -g -m64' LDFLAGS='-m64' ./configure`
4. fix libtool, delete `| \$global_symbol_pipe`
```
global_symbol_pipe=""
...
export_symbols_cmds="\$NM \$libobjs \$convenience | \$global_symbol_pipe | \$SED 's/.* //' | sort | uniq > \$export_symbols"
```
5. gmake
6. fix static functions (see Possible Solution)

## Your Environment
* Version used: 4.1.3
* Operating System and version: Solaris 11.3 SRU 10.5, Solaris Studio 12.5

**Comment by nigoroll** [comment]
@skrueger8 just out of curiosity, why do you prefer Solaris Studio over gcc or llvm?

**Comment by nigoroll** [comment]
@skrueger8
I am not sure why you run into this issue. The functions triggering the error are declared static because they are not meant to get exported in the first place. I suspect this to be a symptom of the libtool hack.

But I addressed some of the other issues which you reported and got varnish binaries surviving a `make check` with Solaris Studio 12.4

I didn't actually test this with Solaris 11 and Solaris Studio 12.5 yet, because, in the varnish project, we got an illumos (actually SmartOS) build host. I can't use 12.5 on it due to `libc` being at `SUNW_1.22.6` :
`uplex@varnishdev-il ~/src/varnish-cache]$ /opt/OracleDeveloperStudio12.5-solaris-x86-bin/developerstudio12.5/lib/compilers/bin/iroptld.so.1: iropt: fatal: libc.so.1: version 'SUNW_1.22.7' not found (required by file /opt/OracleDeveloperStudio12.5-solaris-x86-bin/developerstudio12.5/lib/compilers/bin/iropt)
`

Solaris Studio 12.4 works after some tweaks to the build system, which are now in master.
So, could you please try current master and report here?
FYI, having installed some dependencies under `/opt/local`, I used the following `PATH` and `configure` call

```
PATH=/opt/SolarisStudio12.4-solaris-x86-bin/solarisstudio12.4/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
./configure CPPFLAGS="-I/opt/local/include" CFLAGS="-m64" LDFLAGS="-L/opt/local/lib -R/opt/local/lib"

```

**Comment by skrueger8** [comment]
> just out of curiosity, why do you prefer Solaris Studio over gcc or llvm?

it's just our default SPARC compiler here...

> I am not sure why you run into this issue. The functions triggering the error are declared static because they are not meant to get exported in the first place. I suspect this to be a symptom of the libtool hack.

I digged a bit deeper into this.

1. seems like everything is fine when you use Solaris Studio 12.4 *and* have `/usr/gnu/bin` in your `$PATH` first so that `/usr/gnu/bin/nm` is found, libtool is not broken anymore, no more undef. symbols when linking

So this works now (tested with master):

```
PATH=/usr/gnu/bin:/opt/solarisstudio12.4/bin:/usr/bin; export PATH
MAKE=gmake CC=cc CFLAGS='-O -g -m64' LDFLAGS='-m64' ./configure
gmake
```

2. Developer Studio 12.5 does support `-Wall` and `-Werror`, even though it's not mentioned in the manpage...

```
configure:17252: checking whether C compiler accepts -Wall
configure:17271: cc -c -O -g -m64 -D_POSIX_PTHREAD_SEMANTICS -mt  -Wall  conftest.c >&5
configure:17271: $? = 0
configure:17279: result: yes
configure:17293: checking whether C compiler accepts -Werror
configure:17312: cc -c -O -g -m64 -D_POSIX_PTHREAD_SEMANTICS -mt -Wall  -Werror  conftest.c >&5
configure:17312: $? = 0
configure:17320: result: yes
configure:17368: checking whether C compiler accepts -Werror=unused-result
configure:17387: cc -c -O -g -m64 -D_POSIX_PTHREAD_SEMANTICS -mt -Wall -Werror  -Werror=unused-result  conftest.c >&5
configure:17387: $? = 0
configure:17396: result: yes
```

But this makes the compiler very picky:

```
/tmp/varnish-cache-master/lib/libvarnishcompat $ gmake
  CC     libvarnishcompat_la-daemon.lo
"daemon.c", line 34: empty translation unit
cc: acomp failed for daemon.c
gmake: *** [libvarnishcompat_la-daemon.lo] Error 1


$ cat /tmp/empty.c
//#include <stdio.h>
#ifdef BLAH
#else
#endif
$ cc -c -Wall -Werror /tmp/empty.c
"/tmp/empty.c", line 1: empty translation unit
cc: acomp failed for /tmp/empty.c
```

I guess sticking with Studio 12.4 seems to be the best option right now.

**Comment by nigoroll** [comment]
> > just out of curiosity, why do you prefer Solaris Studio over gcc or llvm?
> it's just our default SPARC compiler here...
Interesting, so you are actually running varnish on SPARC? Please let me know if, by any chance, you'd contribute a zone as a build slave to the project.

> 1. seems like everything is fine when you use Solaris Studio 12.4 *and* have `/usr/gnu/bin` in your `$PATH` first so that `/usr/gnu/bin/nm` is found, libtool is not broken anymore, no more undef. symbols when linking

makes sense, thanks for clarifying. This also matches our SmartOS Zone, where gcc and Sun cc are under separate prefixes, but the first nm in PATH is gnu nm.


> But this makes the compiler very picky:
> 
> ```
> /tmp/varnish-cache-master/lib/libvarnishcompat $ gmake
>   CC     libvarnishcompat_la-daemon.lo
> "daemon.c", line 34: empty translation unit
> cc: acomp failed for daemon.c
> gmake: *** [libvarnishcompat_la-daemon.lo] Error 1

Yes, which is why I added `-errwarn=%all,no%E_EMPTY_TRANSLATION_UNIT,no%E_ATTRIBUTE_UNKNOWN,no%E_STATEMENT_NOT_REACHED,no%E_EMPTY_DECLARATION` yesterday.

Alternatively, we could plaster the code with [`#pragma error_messages`](https://docs.oracle.com/cd/E19205-01/819-5265/6n7c29cl9/index.html#indexterm-84) or try to avoid the warnings.

**Comment by hermunn** [comment]
Backport review: Since this fix is limited to Solaris Studio, it will not be backported to 4.1.
