### ISSUE TITLE
failing jenkins builds - issue with vcl labels?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2048]
did not have a look myself, this ticket is just a reminder for @bsdphk 
Jenkins builds https://jenkins.varnish-software.com/view/varnish-master/ seem to be failing on debian i386 and ppc with `v00048.vtc` failing since the vcl labels merge
e.g. https://jenkins.varnish-software.com/view/varnish-master/job/VC-master-jessie-ppc64/186/console
```
***  v1    4.6 debug| Debug: Stopping Child\n
***  v1    5.6 debug| Info: Child (930) ended\n
---- v1    5.6 CLI failed (stop) = 400 400 CLI communication error (hdr)
**** v1    5.6 CLI TX| status
---- v1    5.6 CLI write failed (status) = 32 Broken pipe
---- v1    5.6 CLI failed (status) = 400 400 CLI communication error (hdr)

#     top  TEST ./tests/v00048.vtc FAILED (5.623) signal=6 exit=0
```

**Comment by bsdphk** [comment]
I think this is fixed now.

**Comment by fgsch** [comment]
There is still a similar error in a different test (e00030.vtc) for both ppc64 and i386:

```
**** v1    0.4 CLI RX| VCL compiled.\n
**** v1    0.4 CLI TX| vcl.use vcl2
---- v1    0.4 CLI failed (vcl.use vcl2) = 400 400 CLI communication error (hdr)
---- s1    0.4 Assert error in varnish_vclbackend(), vtc_varnish.c line 788:  Condition(u == CLIS_OK) not true.
```

**Comment by bsdphk** [comment]
I just fixed this.  This was not related to labels.

**Comment by hermunn** [comment]
Backport review: VCL labels are not a part of 4.1, so this in not applicable.
