### ISSUE TITLE
Support for variables

### ISSUE THREAD

**Issue by joshuaspence** [varnishcache/varnish-cache#2049]
It would be great if the Varnish VCL had native support for variables. There is `vmod_var` in https://github.com/varnish/varnish-modules, but this functionality really feels like something that should exist in VCL itself. Specifically, in our use case we are trying to construct reusable Varnish subroutines and write associated unit tests for these subroutines.

Here is a sample of a subroutine that we are using:

```
  sub sanitize_cookies {
    if (req.http.Cookie) {
      set req.http.Cookie = regsuball(req.http.Cookie, "(?:^|; *)(<%= (@blacklisted_cookies + @tracking_cookies).join('|') %>)=[^;]*", "");
      set req.http.Cookie = regsuball(req.http.Cookie, "^; *", "");
    }
  }
```

Note that this snippet is a Puppet (ERB) template rather than pure VCL. The problem we are facing is that our unit tests (written with `varnishtest`) are very fragile because they are tied to the values of `@blacklisted_cookies` and `@tracking_cookies`. Instead, I was hoping that we could do something like this:

```
  const sanitize_cookies_regex = "(?:^|; *)(<%= (@blacklisted_cookies + @tracking_cookies).join('|') %>)=[^;]*";

  sub sanitize_cookies {
    if (req.http.Cookie) {
      set req.http.Cookie = regsuball(req.http.Cookie, sanitize_cookies_regex, "");
      set req.http.Cookie = regsuball(req.http.Cookie, "^; *", "");
    }
  }
```

This would take testing much easier because the `const` declaration could be moved to a separate file which isn't included by the VCL in our VTC files.

**Comment by nigoroll** [comment]
First of all, issues are not for feature requests, but anyway: The feature you are requesting has been on the list for a very long time and has been discussed back and forth. The main issue here is the question of scope, which is not that easy in vcl.

For your particular case, [vmod_re](https://code.uplex.de/uplex-varnish/libvmod-re) points in the right direction, but we don't have a `regsuball()` method yet: If you only wanted to do a fixed number of substitutions, vmod_re would be what you're asking for, but we can't loop in vcl.
Maybe @slimhazard would want to implement `regsub[all]` ?

**Comment by slimhazard** [comment]
@nigoroll, equivalents for regsub and regsuball in vmod_re can be done, I'll have to ask my boss if I should work on that.

There are equivalents for the those two functions in [vmod_re2](https://code.uplex.de/uplex-varnish/libvmod-re2) right now -- for that, you'd have to install the re2 library, and regexen would be subject to the restrictions that re2 imposes. I'm guessing that @joshuaspence's regexen just list cookie names, so it's probably not a problem. In fact, if they are just strings combined by `|` for 'or', @joshuaspence might be able to use re2 sets, which are likely to match faster than anything PCRE could do (PCRE is used for vmod_re as well as native VCL regexen).

**Comment by fgsch** [comment]
It's worth noting we have a VIP for this: 
https://github.com/varnishcache/varnish-cache/wiki/VIP9:-Expand-VCL-object-support

**Comment by hermunn** [comment]
Backport review: Nothing commited - nothing to backport.
