### ISSUE TITLE
provide package for Ubuntu 16.04 (xenial)

### ISSUE THREAD

**Issue by davidak** [varnishcache/varnish-cache#2055]
https://repo.varnish-cache.org/ubuntu/dists/

Ubuntu provides a package with Version 4.1.1-1

**Comment by fgsch** [comment]
Packaging related issue should be opened at https://github.com/varnishcache/pkg-varnish-cache.

**Comment by davidak** [comment]
Thanks. There is already an issue: https://github.com/varnishcache/pkg-varnish-cache/issues/36

**Comment by hermunn** [comment]
Backport review: Nothing commited - nothing to backport.
