### ISSUE TITLE
varnish 4.1.2 Segfault 

### ISSUE THREAD

**Issue by shorman88** [varnishcache/varnish-cache#2064]
Hello Team,

I have 4 varnish instances; each instance has 100GB file storage they were running fine since three weeks now every day i find one crashes and i lose the whole cache on that instance.

`varnishd[44532]: segfault at 28 ip 000000000043257f sp 00007f82675250f0 error 4 in varnishd[400000+93000]`

Here is the panic.show from the crashed instance.

`Last panic at: Tue, 30 Aug 2016 20:01:00 GMT
"Assert error in SES_Delete(), cache/cache_session.c line 544:
  Condition(now >= sp->t_open) not true.
thread = (cache-worker)
version = varnish-4.1.2 revision 0d7404e
ident = Linux,2.6.32-504.el6.x86_64,x86_64,-jnone,-sfile,-smalloc,-hcritbit,epoll
Backtrace:
  0x432d03: pan_ic+0x163
  0x439bdf: varnishd() [0x439bdf]
  0x434235: Req_Cleanup+0x1f5
  0x44e666: HTTP1_Session+0x506
  0x43a22d: SES_Proto_Req+0x5d
  0x44903d: WRK_Thread+0x4ad
  0x44946b: pool_thread+0x2b
  0x3d402079d1: libpthread.so.0() [0x3d402079d1]
  0x3d3fee88fd: libc.so.6(clone+0x6d) [0x3d3fee88fd]
req = 0x7f6940080960 {
  vxid = 0, step = R_STP_RESTART,
  req_body = R_BODY_INIT,
  restarts = 0, esi_level = 0,
  ws = 0x7f6940080b40 {
    OVERFLOWED id = \"\",
    {s,f,r,e} = {(nil),(nil),(nil),(nil)},
  },
  http[req] = (nil) {
"
`
I have increase the memlock to unlimited without luck

I appreciate your help.
Ayman

**Comment by nigoroll** [comment]
most likely a dup of #1874
The workaround is to use ntpd and avoid stepping the clock. See the other tickets for details

**Comment by nigoroll** [comment]
Also updating to 4.1.3 is highly recommended, though unrelated to this issue

**Comment by shorman88** [comment]
I use ntpd already, i will try the 4.1.3 and i will let you know.

Thanks

**Comment by nigoroll** [comment]
@shorman88 The workaround is to add the `-x` option to `ntpd`. Running `ntpd` alone does not avoid the issue.
For instance on debian, this is achieved by editing `/etc/default/ntp`, adding `-x` to `NTPD_OPTS` and restarting `ntpd`
