### ISSUE TITLE
H/2 crash if any frame padding is present

### ISSUE THREAD

**Issue by daghf** [varnishcache/varnish-cache#2066]
varnishd command line:

<pre>
  $ bin/varnishd/varnishd -a :9090 -b localhost:8080 -n /tmp/foo -d
</pre>

Request sent via nghttp with `-b 1`

<pre>
  $ nghttp http://localhost:9090/ -n -v --no-dep -b 1
</pre>

<pre>
Error: Child (10825) died signal=6
Error: Child (10825) Panic at: Wed, 31 Aug 2016 09:13:25 GMT
"Missing errorhandling code in h2_rx_headers(), http2/cache_http2_proto.c line 434:
  Condition((i) == 0) not true.thread = (cache-worker)
version = varnish-trunk revision e7b05d7
ident = Linux,4.6.0-1-amd64,x86_64,-jnone,-smalloc,-smalloc,-hcritbit,epoll
Backtrace:
  0x4521b0: pan_backtrace+0x20
  0x451fd3: pan_ic+0x363
  0x49960f: h2_rx_headers+0x41f
  0x49b0ab: h2_rxframe+0x3cb
  0x49a029: h2_new_session+0x489
  0x47fe95: Pool_Work_Thread+0x675
  0x47f6d4: WRK_Thread+0x324
  0x47f37d: pool_thread+0xdd
  0x7f6531660464: libpthread.so.0(+0x7464) [0x7f6531660464]
  0x7f653139f30d: libc.so.6(clone+0x6d) [0x7f653139f30d]
req = 0x7f6520096020 {
  vxid = 1, transport = H2
  step = 0x0,
  req_body = R_BODY_INIT,
  err_code = 1, err_reason = (null),
  restarts = 0, esi_level = 0,
  sp = 0x7f651fc0f420 {
    fd = 20, vxid = 1,
    t_open = 1472634805.115933,
    t_idle = 1472634805.116142,
    transport = H2 {
      streams {
        0x00000000 idle  
        0x00000001 idle  
      }
    }
client = ::1 54024,
  },
  ws = 0x7f65200961f8 {
    id = \"req\",
    {s, f, r, e} = {0x7f6520097ff8, +288, (nil), +57344},
  },
  http_conn = 0x7f6520096128 {
    fd = 20,
    doclose = NULL,
    ws = 0x7f65286e9e78,
    {rxbuf_b, rxbuf_e} = {0x7f65286e9470, 0x7f65286e949b},
    {pipeline_b, pipeline_e} = {(nil), (nil)},
    content_length = 0,
    body_status = none,
    first_byte_timeout = 0.000000,
    between_bytes_timeout = 0.000000,
  },
  http[req] = 0x7f6520096290 {
    ws[] = (nil),
    hdrs {
    },
  },
  flags = {
  },
},

"
</pre>

**Comment by bsdphk** [comment]
This is already fixed in 77cab3676155ac3f45db4176795f5621e12be8e6

**Comment by hermunn** [comment]
Backport review: H2, no backport needed.
