### ISSUE TITLE
Images can't be cached by client browsers via varnish 4.1.3?

### ISSUE THREAD

**Issue by ihaolin** [varnishcache/varnish-cache#2067]
## Expected Behavior
Client should cache the images from varnish, and don't request varnish
## Current Behavior

+ Client can't cache the images from varnish, therefore, every request will pass to varnish, and return **304 Not Modified**.

+ I add the **Cache-Control** http header when **vcl_deliver**, like:

    ![vcl_deliver](https://cloud.githubusercontent.com/assets/8662695/18126462/d29f588a-6fad-11e6-8b98-89a9b8f56f2b.png)

+ I found the broswer's debug console:

    ![chrome-debug](https://cloud.githubusercontent.com/assets/8662695/18127979/2735bb16-6fb6-11e6-9218-d0a9415ee4d6.png)

I think the response code should be **304**, not **304 Not Modified**，I hope the browser caches the image(**don't request the varnish**) but it doesn't work.

Could someone help me?

Thanks & Regards.

**Comment by gquintard** [comment]
Please submit your issue on varnish-misc@varnish-cache.org or on IRC, Github issues are for bugs only.

"Not Modified" is the reason, not part of the code

**Comment by hermunn** [comment]
Backport review: Nothing commited - nothing to backport.
