### ISSUE TITLE
Compilation error on OS X: vtc_http2.c

### ISSUE THREAD

**Issue by perbu** [varnishcache/varnish-cache#2070]
Trying to build f02d470 on OS X El Capitan 10.11.6
15.6.0 Darwin Kernel Version 15.6.0

> Making all in varnishtest
>   CC       varnishtest-vtc_http2.o
> vtc_http2.c:1087:28: error: format specifies type 'long' but the argument has type 'long long' [-Werror,-Wformat]
>                 snprintf(buf, 20, "%ld", s->id ? s->ws : s->hp->ws);
>                                    ~~~   ^~~~~~~~~~~~~~~~~~~~~~~~~
>                                    %lld
> /usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
>   __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
>                                                              ^~~~~~~~~~~
> vtc_http2.c:2738:55: error: format specifies type 'long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
>                 vtc_log(hp->vl, 4, "Upgrade: %s (%d): %ld", buf, i, v);
>                                                       ~~~           ^
>                                                       %llu
> 2 errors generated.

**Comment by Dridi** [comment]
Can you have a look at the current master? (c99382d)

**Comment by perbu** [comment]
It compiles nicely now. Thanks!

**Comment by hermunn** [comment]
Backport review: This was a master only problem. Nothing to backport.
