### ISSUE TITLE
How do we monitor 5xx for Saint Mode?

### ISSUE THREAD

**Issue by mwethington** [varnishcache/varnish-cache#2071]
How do we log and track 500s and if saint mode is helping?

Thanks.

**Comment by fgsch** [comment]
Running e.g. `varnishlog -g request -q 'RespStatus == 500'` should do the former.
That said, the issue tracker is for bugs. Please see https://varnish-cache.org/support/ for general support.

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
