### ISSUE TITLE
directors need refcounting - or maybe not?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2072]
discussed in the context of #2036 , but actually It's a separate, though related, question

> (15:30:52) slink: but other than that, at any rate, we need to agree on lifetime of struct directors:
> (15:30:52) slink: - refcount
> (15:30:52) slink: - never destruct before fini
> ...
> (15:32:56) dridi: regarding the two propositions, the answer is refcounting
> (15:33:35) dridi: it has already be discussed and phk said that we may have to bite bullet referring to backends/directors rc
> (15:33:44) slink: ok

**Comment by nigoroll** [comment]
irc dump for later, slightly edited for readability

> (15:25:56) slink: dridi, for lazy resolution directors to avoid the refcounting pandoras box, what if director objects had a flag marking them as transient? We could then require directors to never reference them for anything but a transient director.
> (15:27:08) dridi: I don't understand transient in this context
> (15:27:19) dridi: I'd say parametric or eager instead
...
> (15:28:14) slink: transient = lives on workspace, only valid for this req/bereq
> (15:29:49) dridi: I don't think we need either refcounting or ws allocation
> (15:30:36) dridi: the problem is that they can't be stacked because they need a parameter that lazy resolution doesn't provide
> (15:31:46) dridi: so instead, they could keep track of vcl_init allocations (being vmod objects) and use priv_task during transactions
> (15:30:50) slink: yes, but we could solve this
> (15:31:24) slink: dir1.add(dir2.lazy_resolve(pa=ra, me=ter))
> (15:32:10) slink: now dir2 would return a DIR_TRANSIENT object, so dir1 would do the same (*edit*)
> (15:32:43) slink: the object would, in the priv pointer, contain the info required to do the lookup when vdi_resolve_f is called
> (15:32:43) dridi: slink: I get the idea, I'm trying to formulate one that doesn't require anything new
> (15:33:01) slink: dridi that one _i_ don't understand
> (15:33:10) dridi: slink: I'm trying :)
> (15:33:28) slink: how would it look like in vcl?
> (15:33:53) dridi: so let's agree on dir1.add(dir2.lazy_resolve(...));
> (15:35:03) dridi: dir2.lazy_resolve can: allocate and keep track of the state in dir2 (being a vmod object, it can keep track of allocation with VCL lifetimes)
> (15:35:50) dridi: so dir2 allocates a backend, with a vdi_resolve_f that knows about the original backend and the desired parameters
> (15:36:05) slink: so far we agree
> (15:36:26) dridi: now let's imagine in the dynamic space that you want to do the same during a transaction
> (15:36:45) slink: but IIUC that could never get freed before vcl_fini
> (15:36:52) dridi: (kind of like you can control varnish with PURGE requests)
> (15:37:15) dridi: slink: definitely not
> (15:37:28) slink: so that's the point
> (15:37:43) slink: for shard every dir2.lazy_resolve(...) could be unique
> (15:37:58) slink: so we can't delay destruction until vcl_fini
> (15:39:01) dridi: could you explain me what shard resolution looks like
> (15:40:11) slink: basically its a uint32_t key
> (15:40:14) slink: (at the moment)
> (15:40:41) dridi: I think your problem is to allocate the same dir2.lazy_resolve(...) for a given param when the vcl reloads, is it?
> (15:40:47) slink: how we get to that key doesn't matter, basically we'd need a separate object for each, IIUC
> (15:41:09) slink: no the reload shouldn't be an issue
> (15:41:33) dridi: i know, it's reload-proof, that's why I'm asking
> (15:42:08) slink: let me re-phrase:
> (15:45:12) slink: I need to get that 32bit value across from vcl_recv{} or vcl_backend_request{} to whenver core calls my vdi_resolve_f. So at the moment I have to create a dynamic struct director with priv pointing to that value. So I either need to create that dynamic backend in vmod managed memory, then I got the gc problem. Or I put it on the ws, then I need to keep other directors from creating references which do not themselves live on the ws
> (15:46:44) slink: Because the first option does not appear valid, avoiding other code to create references seems like a good option.
> (15:47:18) slink: out of tree code here https://code.uplex.de/uplex-varnish/libvmod-vslp/tree/shard
> (15:47:46) slink: (I'm not considering to implement any of what I just said now, I just couldn't avoid re-thinking it)
> (15:53:34) dridi: slink: I will have a look, but this has been overtaken by support :(

**Comment by bsdphk** [comment]
I have been beating my head against this one again, and it invariably takes me places I don't want to go.

To illustrate the rabbit-hole, here is a VCL example:

    if (foo.bar(req.backend_hint == sna.pick_a_backend(some, args)) {
        return (pass);
    }

`sna.pick_a_backend` returns a ref'ed VCL_BACKEND, and it is up to VCC to release that ref, which  must happen in both the true and false cases.

In addition to this, variables of type VCL_BACKEND needs to ref/rel and so on.

All in all it becomes a LOT of complexity for very little gain.

I'm pondering doing it the other way instead:  We have talked about giving VMODs a callback at end of transactions.  That could be used to maintain a list of which threads have heard about a given VDI, so that the VMOD could know when no possible reference can exist "in the wild" any more.

There are two footnotes to that.

One is the req->bereq handoff of req.backend_hint, the VMOD needs to be told about that, a general purpose callback can do that.

The other is tricker:  If another VMOD (vmod_director) caches the VDI across threads, then it needs to acquire a ref too.

**Comment by nigoroll** [comment]
Re @bsdphk 

Please let me recap on my understanding of the overall context first, because it's been some time that we last discussed this and I want to be sure that we are all on the same page.

The use cases which I am aware of are:
* dynamic backends referenced in other directors
* dynamic directors created outside vcl_init referenced by other directors

In both cases, we create a VCL_BACKEND outside vcl_init. A simple solution would be to define the lifetime to be equal to that of the VCL, but as VCLs can exist for a very long time, we should gc unused backends earlier.

So obviously, we need an interface for vmods to (un)reference backends, for example adding a backend to a director would reference it, removing the backend would unreference it. But I think that's about it: bereq.backend has the same scope as a backend task, req.backend_hint has the same scope as the client + backend task and there is no other way in vcl (yet, see below) to hold a refrence than via a vmod. So why don't we just assume an implicit per-(be)req reference like so:

(be)reqs reference a death row. When the last reference to a backend is dropped (via a vmod), it is put onto the death row this (be)req references and a new death row is instantiated, so all new (be)reqs will reference that. The (be)req unref'ing a wildcard object last kills all backends on the death row.
The variables case would fit in like this:
* for local (function) or task scope, the reference would be implicit as above
* for global variables, a reference would be taken/released as from a vmod

Am I missing anything?

**Comment by nigoroll** [comment]
One side note: My primary use case for this is sort-of OBE: I had thought that the shard director could return a dynamic VCL_BACKEND with the right parameters for the resolve=LAZY case. But in the meantime I solved this by using the (backend) TASK scoped shard parameters and at the last VDD we've discussed generalizing these backend parameter objects to the client side also.

On the other hand, if we _had_ full support for dynamic VCL_BACKENDs, we might not need the backend parameters to begin with.

The other use case I got is vmod_dynamic.

**Comment by gquintard** [comment]
Hi,

So, here we do have dynamic backends, meaning you can do ``set
bereq.backend = goto.dns_backend("https://www.example.com")`` and that
works, but:
- you can't use it in request context
- we need to remember all the backends wrapping structures we return to
clean them once the TASK is over (because you can call ``.dns_backend()``
more than once during a TASK)

again, I would personally be in favor of killing ``req.backend_hint`` and
just do the routing in ``v_b_f``, but I know I'm a minority here.

-- 
Guillaume Quintard

**Comment by nigoroll** [comment]
Re @gquintard, I think what you are talking about in the first paragraph is what I called _director parameters_. Killing `req.backend_hint` is not an option, IMHO, unless we want to upset many users. But both options on the table would solve your case also, the two options being
* dynamic VCL_BACKEND with refcounting as proposed here
* director parameters passed from client to backend side as discussed at the last VDD

Re @bsdphk I fail to see the misfit. What is wrong with my proposal? The current setup forces us to just put dynamic backends on a cool list, having to assume that any use will have ceased when we kill them after a timeout.

**Comment by nigoroll** [comment]
@bsdphk and myself discussed this on IRC, and either I failed to get my suggestion across, or I fail to see the issue with it still. So we agreed that I shall prep a patch to have some concrete proposal to discuss.

**Comment by nigoroll** [comment]
As I have to switch tasks, I thought I'd share a more detailed plan in case anyone wants to review/comment:

```
/*--------------------------------------------------------------------
 * Director refcounting:
 *
 * - Each VCL task holds an implicit reference to all VCL_BACKENDs by
 *   referencing the current vdi_cool list, thus for any reference
 *   with a scope smaller or equal to a TASK, no explicit reference
 *   should be taken
 *
 * - VRT_VDI_Ref/Unref must be called whenever a reference to a VCL_BACKEND with
 *   longer scope is kept, for example when adding/removing a VCL_BACKEND
 *   to/from a director.
 *
 * To implement the implicit reference explicitly, we use a coollist:
 *
 * - each task references the current coollist
 *
 * - all VCL_BACKENDs with refcnt == 0 are put on the coollist ref'd by the
 *   current task. VCL_BACKENDs with refcnt > 0 are not on any coollist
 *
 * - when a VCL_BACKEND is put on a coollist and the coollist has reached the
 *   minimum age, we start a new coollist which is then referenced by all new
 *   tasks. This way, the old coollist with the VCL_BACKEND(s) to be killed will
 *   eventually get unref'd, at which point it is safe to kill the
 *   VCL_BACKEND(s) on it
 */
```

**Comment by nigoroll** [comment]
I have pushed to https://github.com/nigoroll/varnish-cache/tree/vdi_refcnt what I got at them moment. This is still WIP and needs integration with the existing VRT code (and actual use cases / testing), but I would certainly appreciate early reviews/comments.

**Comment by bsdphk** [comment]
I'm timing this ticket out.  This problem seems to have no workable solutions right now.
