### ISSUE TITLE
VCL comparison doesn't fold STRING_LIST

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2078]
set resp.http.foo = (req.http.bar == "X");

Gives "Operator == not possible on STRING_LIST".

It should fold to STRING and do the compare.

**Comment by fgsch** [comment]
I have a patch for this but it works regardless of the parenthesis due to the way VCC works.

@bsdphk should it be limited to parenthesis?

**Comment by nigoroll** [comment]
related to #2075

**Comment by bsdphk** [comment]
The (...) are just a relic of me trying to see if I could work around it.

It should work with/without (...)

**Comment by fgsch** [comment]
@bsdphk ok, I will fix it then. Any comment on #2075 wrt similar constructions but for regexp?

**Comment by bsdphk** [comment]
staring at #2075 is what made me discover this bug.  Not sure I have fully understood 2075 yet.

**Comment by hermunn** [comment]
Backport review: We are not bacporting features to VCL in 4.1, so this will not be backported.
