### ISSUE TITLE
unhandled SIGFPE for division by zero

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2083]
the following change to m7.vtc exposes it (actually the `resp.http.div` line would suffice)
```
diff --git a/bin/varnishtest/tests/m00007.vtc b/bin/varnishtest/tests/m00007.vtc
index b66fc0b..ddd7fad 100644
--- a/bin/varnishtest/tests/m00007.vtc
+++ b/bin/varnishtest/tests/m00007.vtc
@@ -13,7 +13,11 @@ varnish v1 -vcl+backend {
                set resp.http.ltzero = (std.integer(req.http.foo, 0) < 0);
                set resp.http.iszero = (std.integer(req.http.foo, 0) == 0);
                set resp.http.converted = std.integer(req.http.foo, 0);
-       }
+               set resp.http.add = 1 + std.integer(req.http.foo, 0);
+               set resp.http.sub = 1 - std.integer(req.http.foo, 0);
+               set resp.http.mul = 1 * std.integer(req.http.foo, 0);
+               set resp.http.div = 2 / std.integer(req.http.foo, 0);
+}
 } -start
 
 client c1 {
```

**Comment by bsdphk** [comment]
I'm not going anywhere near this one.

We actually want SIGFPE to happen if we have a divide by zero anywhere in the "real" varnishd code, and there is no sane way to quench it only while in VCL.

Futhermore, this is exactly why the conversion functions have a default argument, so that you are forced to think about what you want to happen with garbage input.

**Comment by nigoroll** [comment]
@bsdphk the best option I could think of so far is to only allow `/ <constant>` - iow forbid dynamic divisors. vcc could check for 0 already, but at least gcc barfs over it anyway.
I don't think we can ignore this if we want to keep vcl without inline-C safe.

**Comment by dhobsd** [comment]
There are other options:

 * Compile division into a VRT call that checks the divisor. The downside to this approach is that you really want a way to communicate the failure to the user; VCL doesn't really have this right now. There are cases today where this would be useful -- for example, a regex match or substitution hits a recursion limit.

 * Document. You can always check that a dynamic divisor is zero before you do a division, so:

```
set resp.http.div = 2 / std.integer(req.http.foo, 0);
```

could become

```
if (std.integer(req.http.foo, 0) != 0) {
  set resp.http.div = 2/std.integer(req.http.foo, 0);
} else {
  # only because numerator is non-zero, but arguably incorrect for integer division
  set resp.http.div = "Inf";
}
```

I don't necessarily like the idea of documenting this away. As VCL gains more power in performing numerical / arithmetic operations, it seems unfortunate to require this much boilerplate for something that could be easily done at runtime, if division was compiled into a VRT call.

**Comment by hermunn** [comment]
Backport review: Nothing committed, nothing to backport.
