### ISSUE TITLE
REAL <op> INT from vmod support incomplete

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2084]
* `set resp.http.add = 1.0 + std.integer(req.http.foo, 0);`

accepted by vcc, but result is a stringification

* `set resp.http.sub = 1.0 - std.integer(req.http.foo, 0);`

gives `REAL - INT not possible`

* `set resp.http.mul = 1.0 * std.integer(req.http.foo, 0);` and
* `set resp.http.mul = 1.0 / std.integer(req.http.foo, 0);`

give vcc assertion failure:
```
Assert error in vcc_expr_mul(), vcc_expr.c line 919:
  Condition(e2->fmt == f2) not true.
```

**Comment by hermunn** [comment]
Backport review: Type system changes is 5.0 only.
