### ISSUE TITLE
should we relax DURATION/REAL and DURATION/INT casting?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2089]
I have a performance ocd issue that instead of doing this

```
set beresp.ttl = std.random(beresp.ttl, * 0.9, beresp.ttl);
```

we need to do this

```
set beresp.ttl = std.duration(
    std.random(std.real(beresp.ttl, 10) * 0.9,
               std.real(beresp.ttl, 10)), 10s);
```
which
* stringifies twice just to convert from duration to real and then
* stringifies the result of std.random() just to get back to duration

I'd really be interested to hear if there are good reasons why not cast freely between DURATION and REAL/INT if the de-tour via a string is possible anyway (and will probably be what people would use)

**Comment by fgsch** [comment]
There are 2 points here:

1. Convert a real to duration.
2. Convert a duration to real.

The first one involves a unit. We'll need to relax that requirement (i.e. 10 and 10s should be the same). 
In that regard, your code above will always result in 10s since the first argument doesn't have the unit.

The second should be pretty straight forward.

**Comment by nigoroll** [comment]
Yes, I missed the unit in the second example, thank you. And I agree that _we should assume a lack of unit means seconds_ when parsing duration strings.

But I am not sure if I got the actual suggestion across: I meant to suggest that we should simply allow casting of `INT` and `REAL` to and from `DURATION` to avoid the de-tour via strings.

**Comment by nigoroll** [comment]
for completeness, the correct version of the second exemaple should be
```
 set beresp.ttl = std.duration(
    std.random(std.real(beresp.ttl, 10) * 0.9,
	       std.real(beresp.ttl, 10)) + "s", 10s);
```

**Comment by nigoroll** [comment]
Discussed during bugwash: dropped in favor of
https://github.com/varnishcache/varnish-cache/wiki/vmod-polymorphism-%28for-type-conversions%29

**Comment by hermunn** [comment]
Backport review: Dropped in favor of something else (see above).
