### ISSUE TITLE
Varnish 5.0 docs for installing from source on FreeBSD

### ISSUE THREAD

**Issue by eriknstr** [varnishcache/varnish-cache#2093]
The [FreeBSD section of the Varnish 5.0 install docs](https://varnish-cache.org/docs/5.0/installation/install.html#freebsd) says that in order to install from source, one should `cd /usr/ports/varnish && make install clean`.

This is missing the category, so should be something like `cd /usr/ports/www/varnish`. Secondly, `www/varnish` is still marked as "moved" to `www/varnish4`. Furthermore, currently, Varnish 5 is not yet available in the ports tree.

The mentioned docs should probably be updated to reflect this.

**Comment by bsdphk** [comment]
I've updated it to use the varnish4 port.  Will update when varnish5 makes it.

**Comment by hermunn** [comment]
Backport review: 5.0 only, nothing to backport.
