### ISSUE TITLE
need to handle bgfetch with uncached request body

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2105]
Noticed while working on #2104 

Problem is exposed by this vtc: The last client request will trigger a Garbage-400 because the request body of the second does not get read. With `std.cache_req_body(1KB);` added, the test succeeds.

```
varnishtest "Test POST->GET with bgfetch conversion"

server s1 {
	rxreq
	txresp \
		-body "012345\n"
	rxreq
	txresp \
		-hdr "Connection: close" \
		-hdr "Foo: 1" \
		-body "012345\n"
} -start

varnish v1 -vcl+backend {
	sub vcl_recv {
		if (req.method == "POST") {
			set req.method = "GET";
		}
	}
	sub vcl_backend_response {
		set beresp.ttl = 1s;
		set beresp.grace = 10s;
	}
} -start

client c1 {
	txreq -req POST -url "/" \
		-body "123456789\n"
	rxresp
	expect resp.status == 200
	expect resp.http.X-Varnish == "1001"

	delay 1

	txreq -req POST -url "/" \
		-body "123456789\n"
	rxresp
	expect resp.status == 200
	expect resp.http.X-Varnish == "1003 1002"

	txreq -req POST -url "/" \
		-body "123456789\n"
	rxresp
	expect resp.status == 200
	expect resp.http.Foo == "1"
	expect resp.http.X-Varnish == "1005 1004"
}

client c1 -run
```

The test also succeeds with the following change (I am _NOT_ suggesting this as a fix, this is only for illustration):

```
diff --git a/bin/varnishd/cache/cache_req_fsm.c b/bin/varnishd/cache/cache_req_fsm.c
index bab15ec..5890611 100644
--- a/bin/varnishd/cache/cache_req_fsm.c
+++ b/bin/varnishd/cache/cache_req_fsm.c
@@ -409,12 +409,15 @@ cnt_lookup(struct worker *wrk, struct req *req)
 
        switch (wrk->handling) {
        case VCL_RET_DELIVER:
+               // XXX: how would we bg-fetch a request with an uncached
+               // body?
+               (void)VRB_Ignore(req);
                if (busy != NULL) {
                        AZ(oc->flags & OC_F_PASS);
                        CHECK_OBJ_NOTNULL(busy->boc, BOC_MAGIC);
                        VBF_Fetch(wrk, req, busy, oc, VBF_BACKGROUND);
                } else {
-                       (void)VRB_Ignore(req);// XXX: handle err
+                       // XXX: handle err
                }
                wrk->stats->cache_hit++;
                req->is_hit = 1;
```

So how do we handle this case? The best option I can see at this point would be to never fall into the bgfetch when there is an uncached request body.

**Comment by fgsch** [comment]
The problem here is that the body is not consumed in the second request (bgfetch).
It has nothing to do with the body not being cached.

**Comment by nigoroll** [comment]
@fgsch how would a bgfetch be able to consume the body?

**Comment by fgsch** [comment]
This already works for bgfetch when we have a request.

What's happening here is that we're unsetting the request in vcl_backend_fetch{} but there is no VRB_Ignore() call in the bgfetch case to consume it.

I will fix it.

**Comment by nigoroll** [comment]
FTR: The design issue I suspected here does not exist. The client thread waits for the bgfetch thread to be done with the request before continuing, so we're fine. The relevant bit in the code is
`VBF_Fetch()`:
```
                if (mode == VBF_BACKGROUND) {
                        ObjWaitState(oc, BOS_REQ_DONE);
```
Nevertheless, the specific issue I reported was real. Thank you @fgsch for the fix.

**Comment by hermunn** [comment]
Backport review: This fix builds on a patch that will not be backported to 4.1, so this not be, either.
