### ISSUE TITLE
[CLI] vcl.inline failures

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2110]
Reported to me by @gquintard, I will have a look myself unless someone else wants to have a go. This is surprising, considering that `varnishtest` is a heavy user of `vcl.inline`.
## Expected Behavior

```
$ varnishadm help | grep vcl.inline
vcl.inline <configname> <quoted_VCLstring> [auto|cold|warm]
```
## Current Behavior

I actually ran into two different errors.
#### Too many parameters

```
$ varnishadm vcl.inline foo 'vcl 4.0; backend dummy { .host = "0" }'
Unknown request.
Type 'help' for more info.
Too many parameters

Command failed with error code 105
```
#### State must be one of auto, cold or warm.

If I end the line after the VCL marker I get this error.

```
$ varnishadm vcl.inline "toob"  'vcl 4.0;
backend dummy { .host = "0" }'
State must be one of auto, cold or warm.
Command failed with error code 106
```

Adding the optional parameter doesn't help.

```
$ varnishadm vcl.inline "toob"  'vcl 4.0;
backend dummy { .host = "0" }' auto
State must be one of auto, cold or warm.
Command failed with error code 106
```

Adding one or more parameters doesn't seem to trigger the too many parameters error.

```
$ varnishadm vcl.inline "toob"  'vcl 4.0;
backend dummy { .host = "0" }' auto warm cold warm-again winter is coming auto warm clod wram
State must be one of auto, cold or warm.
Command failed with error code 106
```
## Possible Solution

Me writing a patch.

**Comment by fgsch** [comment]
The quotes need to be double quotes ("). Also since you are calling varnishadm from the shell you also need to escape them. This works as expected:

`$ varnishadm vcl.inline foo "\"vcl 4.0; backend b { .host = \\\"0\\\"; }\""`
`$ varnishadm vcl.inline bar "\"vcl 4.0; backend b { .host = \\\"0\\\"; }\" cold"`

**Comment by Dridi** [comment]
Yes, I forgot that it was supposed to be a quoted string in the varnish-cli, which we lose with shell expansion. I will close this issue with a docfix instead to better explain it in the doc so that I don't get confused by bogus reports again :)

**Comment by hermunn** [comment]
Backport review: Backported by @Dridi as 055551d091 and f1bc4e8875.
