### ISSUE TITLE
debug.health in Varnish 5

### ISSUE THREAD

**Issue by guycalledseven** [varnishcache/varnish-cache#2112]
I was not aware that debug.health is gone form Varnish 5:

```
sudo varnishadm debug.health
Unknown request.
Type 'help' for more info.

Command failed with error code 101
```

What is the idea, to use backend.list instead?

Best

**Comment by fgsch** [comment]
It was replaced with `backend.list -p`.

In the future please use the existing support channels for questions. This is for bugs only.

**Comment by guycalledseven** [comment]
@fgsch tnx! what is the varnish 5 communication / feedback channel?

**Comment by fgsch** [comment]
See https://varnish-cache.org/support/index.html for details.

**Comment by hermunn** [comment]
Backport review: Not a bug, nothing to backport.
