### ISSUE TITLE
"varnishstat -f MAIN.sess_conn -1" produces empty output

### ISSUE THREAD

**Issue by gquintard** [varnishcache/varnish-cache#2118]
``varnishstat -f PATTERN -1`` produces empty output if PATTERN is a full counter name (such as "MAIN.sess_conn")

## Expected Behavior
varnishstat should return the information about the counter named PATTERN

## Your Environment
Happens on 5.0.

**Comment by hermunn** [comment]
Backport review: @gquintard's comment indicates that this is 5.0 only, so there is nothing to backport.

**Comment by zstyblik** [comment]
Hello,

I've applied patch from the commit, but situation hasn't changed. varnishstat still cannot reference eg. MAIN.cache_hit. :\

Thank you for any help.

**Comment by fgsch** [comment]
You are doing something wrong if it's not working but I'm afraid this is not the right place for support.
Check https://varnish-cache.org/support/ for the correct channels.

**Comment by zstyblik** [comment]
@fgsch, it was my bad indeed. patch is in libvarnishapi, therefore deploying varnish debpkg alone doesn't make sense. Thank you for the kick and sorry for the noise. Patch works.

**Comment by venkat-rafay** [comment]
This issue still persists with `varnish-5.0.0 revision 99d036f`. Could someone clarify whether this patch has been published in a later revision?

**Comment by Dridi** [comment]
If you look at the patch https://github.com/varnishcache/varnish-cache/commit/b21b0d7b326b18a808c26d4687fe87911a94f4fa with a git client or directly on github you can see that this patch was first released with Varnish 5.1.0.
