### ISSUE TITLE
Please sign RHEL7 EPEL RPMs

### ISSUE THREAD

**Issue by luyseyal** [varnishcache/varnish-cache#2119]
Varnish is awesome. It would work more nicely with RPM if the RPMs were signed. Please sign RHEL 7 EPEL RPMs.

## Expected Behavior

RPM signature (ideally, EPEL) available.

## Current Behavior

Workaround missing signatures:
`rpm --nosignature -i https://repo.varnish-cache.org/redhat/varnish-4.1.el7.rpm`

## Your Environment

* Version used: 4.1
* Operating System and version: RHEL 7

**Comment by nigoroll** [comment]
@fgsch would you move this to pkg please?

**Comment by luyseyal** [comment]
Sorry I put this in the wrong repo. Just copied to pkg-varnish-cache.

**Comment by hermunn** [comment]
Backport review: Wrong repo - nothing to commit.
