### ISSUE TITLE
Varnish with only named gives an error about backends not being there

### ISSUE THREAD

**Issue by mwethington** [varnishcache/varnish-cache#2121]
When using the plugin named, I get an error and varnish will not start.

When using named plugin, I get an error that tells me I need to define 1 backend.

Why?

This is what I added - but it is just wasting cycles.

# this is needed for a bug!
backend d1 {
    .host = "127.0.0.1";
    .port = "81";
    .probe = {
        .request =
                    "GET /build.txt HTTP/1.0"
                    "Connection: close";
        .timeout = 3500 ms;
        .interval = 2s;
        .window = 10;
        .threshold = 5;
    }
    .connect_timeout = 90s;
    .first_byte_timeout = 90s;
    .between_bytes_timeout = 90s;
}

**Comment by nigoroll** [comment]
libvmod-named is no longer public. If you're closed source from Varnish Software, please go through your support channel.
A public open source fork is being maintained here: https://github.com/nigoroll/libvmod-dynamic
Other than that, please read the documentation, See _Example_ in https://github.com/nigoroll/libvmod-dynamic/blob/master/src/vmod_dynamic.vcc

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
