### ISSUE TITLE
Illegal character in VCL name ('1')

### ISSUE THREAD

**Issue by opensubtitles** [varnishcache/varnish-cache#2125]
Hi,

upgraded to Varnish 5.0.0, got problems with loading VCL. Info:

```
# varnishadm vcl.load 1 /usr/local/etc/varnish/dummy.vcl 
Illegal character in VCL name ('1')
Command failed with error code 106
Exit 1

# varnishadm vcl.load 2 /usr/local/etc/varnish/dummy.vcl
Illegal character in VCL name ('2')
Command failed with error code 106
Exit 1

# less dummy.vcl
vcl 4.0;
backend dummy { 
        .host = "0";
}

# uname -a
FreeBSD xxx 10.3-STABLE FreeBSD 10.3-STABLE #8 r298620: Wed Apr 27 09:58:02 CEST 2016     xxx@xxxx:/usr/obj/usr/src/sys/SUPERMICRO  amd64

# varnishd -V
varnishd (varnish-5.0.0 revision 99d036f)
```

Tested on Varnish 4.x and it works. I found in https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishd/mgt/mgt_vcl.c#L114 there is some problem with names, but have no clue why it is throwing error.

**Comment by gquintard** [comment]
Looks pretty straightforward: 1 is an illegal character.

More precisely, vcl must have names that are valid in C, so they can't
start with a number.

**Comment by 2ge** [comment]
Right, got it. This has changed in v5, in v4 there was not a problem call
`varnishadm vcl.load 1 myconfig.vcl`

Ticket can be closed, thanks for help

**Comment by opensubtitles** [comment]
Right, got it. This has changed in v5, in v4 there was not a problem call
`varnishadm vcl.load 1 myconfig.vcl`

Ticket can be closed, thanks for help

**Comment by gquintard** [comment]
No problem. But please, next time, ask for help on the support channels first,  issues are for bugs only.

https://www.varnish-cache.org/support/index.html

**Comment by hermunn** [comment]
Backport review: Not an issue - nothing commited - nothing to backport

**Comment by zstyblik** [comment]
@gquintard, @hermunn, actually, it seems to me there is a bug in `/usr/share/varnish/reload-vcl` uses UUID for VCL label and it fails.

```
Illegal character in VCL name ('2')
Error: vcl.load 23db2fb6-a434-4b5a-883e-698a51652a1f /etc/varnish/default.vcl failed
```

Traced to this:

```
[...]
if [ -f /proc/sys/kernel/random/uuid ]
then
    uuid=$(cat /proc/sys/kernel/random/uuid)
    vcl_label="${LOGNAME}${LOGNAME:+_}${uuid}"
else
    vcl_label="$($date +${LOGNAME}${LOGNAME:+_}%s-%N)"
fi
[...]
if $varnishadm -T $mgmt_interface -S ${secret} vcl.load $vcl_label $vcl_file
[...]
```

Observed with Debian package `varnish_5.0.0-1`.

**Comment by gquintard** [comment]
Indeed, but then that's a packaging issue. The simple solution could be to prefix vcl_label with a safe char/string.

Can you open an issue with your findings on https://github.com/varnishcache/pkg-varnish-cache please?

**Comment by zstyblik** [comment]
@gquintard, I see and I didn't know(wasn't even aware there is pkg-varnish-cache repo). Actually, now I see the issue already is open https://github.com/varnishcache/pkg-varnish-cache/issues/51. Thank you for heads up.
