### ISSUE TITLE
Varnish stuck on VBT_Wait after reused connection (VBC_STATE_STOLEN) failed V1F_SendReq

### ISSUE THREAD

**Issue by jpastuszek** [varnishcache/varnish-cache#2126]
When POST request is canceled by the browser (connection is closed) before content length of data is received by Varnish and the backend connection was reused Varnish will get stuck for backend_idle_timeout .

## Expected Behavior
Varnish should close backend connection and send 400 error response and close client connection.

## Current Behavior
Varnish gets stuck for the backend_idle_timeout since the connection was put for reuse by previous request. When timeout runs out it closes backend connection and sends 503 to the client and closes client connection.

## Possible Solution
The bug is that when we have VBC_STATE_STOLEN connection and V1F_SendReq fails (due to "straight insufficient bytes") Varnish will still call VBT_Wait.
The VBT_Wait blocks until backend_idle_timeout runs out.

In case of fresh connection (VBC_STATE_USED) Varnish will not block and will respond with 503 (should be 400 in this case). The VBT_Wait (VBC_STATE_USED) and V1F_FetchRespHdr (i = -1) calls are skipped all together.

This looks similar to #1806 and probably relates to #1772.

As mentioned in other tickets Varnish should be able to abort backend connection when it is in the waiter or perhaps take it away somehow without the need to wait for full timeout.

## Steps to Reproduce
Make a request - this should put backend connection to reuse.
Make POST request but close the connection (write side is enough) before writing full Content-Length body bytes.
Varnish should get stuck until backend_idle_timeout triggers after it logged "straight insufficient bytes".

```
     98909 Debug          c "geoip2.lookup: No entry for this IP address (192.168.1.115)"
     98910 BackendOpen    b 29 boot.origin 10.1.1.72 80 10.1.1.248 33748
     98910 BackendStart   b 10.1.1.72 80
     98910 BackendReuse   b 29 boot.origin
     98909 Debug          c "RES_MODE 48"

    164271 Debug          c "geoip2.lookup: No entry for this IP address (192.168.1.115)"
    164272 BackendOpen    b 29 boot.origin 10.1.1.72 80 10.1.1.248 33748
    164271 FetchError     c straight insufficient bytes
    164272 BackendStart   b 10.1.1.72 80
    164272 FetchError     b req.body read error: 0 (Success)
    164272 FetchError     b backend write error: 0 (Success)
--- STUCK ---
    164272 BackendClose   b 29 boot.origin
    164272 BerespReason   b Backend fetch failed
    164272 VCL_Log        b Backend Error Code: 503
    164272 BerespReason   b Backend Unavailable
    164272 ObjReason      b Backend Unavailable
    164271 RespReason     c Backend Unavailable
    164271 Debug          c "RES_MODE 2"
```

## Context
Because we use session locks in our backend (IIS default behaviour) when Varnish keeps the backend request hanging for backend_idle_timeout all other requests for that given session are queued up on the session lock.
For the end user it looks like the page is very slow - it can be any page called after the above scenario happens.
We get "straight insufficient bytes" due to browser canceling POST request on multiple postbacks (or submit button clicks) - we don't know exactly why browser does that.

## Your Environment
* Version used: varnish-4.1.3-1.el6.x86_64
* Operating System and version: AmazonOS (RedHat/Centos 6)

**Comment by jpastuszek** [comment]
Also could be related to #1156

**Comment by daghf** [comment]
Hi @jpastuszek 

This looks a lot like #1806, and possibly also #1772. Both of those have since been fixed, so I wonder if this issue isn't overtaken by events at this point.

I'll close this now, but please feel free to reopen if you can still observe this behavior.
