### ISSUE TITLE
Disable Nagle's

### ISSUE THREAD

**Issue by mwethington** [varnishcache/varnish-cache#2134]
Can we consider disabling Nagle's

This flag (TCP_NODELAY) is an option that can be enabled on a per-socket basis and is applied when you create a TCP socket. This is done for a purpose: Nagle's algorithm is generally useful and helps handle network congestion. I doubt you want to disable it system-wide since your system will probably suffer from this deactivation.

To disable it for a given socket, you can apply the option TCP_NODELAY as explained here and here in C:

int flag = 1;
int result = setsockopt(sock,            /* socket affected */
                        IPPROTO_TCP,     /* set option at TCP level */
                        TCP_NODELAY,     /* name of option */
                        (char *) &flag,  /* the cast is historical cruft */
                        sizeof(int));    /* length of option value */
 if (result < 0)
    ... handle the error ...

**Comment by tfheen** [comment]
]] Bill Bell 

> Can we consider disabling Nagle's

This was done in 3.0.4 rc1 already, or are you seeing cases where it's
still on?

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

**Comment by mwethington** [comment]
Not seeing it on the server calls. I do see it on the accept

Bill Bell
Sent from mobile


On Nov 14, 2016, at 10:35 PM, Tollef Fog Heen <notifications@github.com<mailto:notifications@github.com>> wrote:

]] Bill Bell

> Can we consider disabling Nagle's

This was done in 3.0.4 rc1 already, or are you seeing cases where it's
still on?

--
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

-

**Comment by tfheen** [comment]
]] Bill Bell 

> Not seeing it on the server calls. I do see it on the accept

Right, we might not be setting it on outbound connections to backends.
That should probably be checked.  I thought we did, but I could be
wrong.

-- 
Tollef Fog Heen
UNIX is user friendly, it's just picky about who its friends are

**Comment by bsdphk** [comment]
This is such a fundamental change in networking behaviour that I want to see some emperical data why this is a good idea, and preferably also when it is not (distant backend ?)

I havn't had time to digest this, but it may be relevant: https://tools.ietf.org/html/draft-stenberg-httpbis-tcp-00

**Comment by fgsch** [comment]
The part specific to Nagle's algorithm:

```
4.3.  Nagle's Algorithm

   Nagle's Algorithm [RFC0896] is the mechanism that makes the TCP stack
   hold (small) outgoing packets for a short period of time so that it
   can potentially merge that packet with the next outgoing one.  It is
   optimized for throughput at the expense of latency.

   HTTP/2 in particular requires that the client can send a packet back
   fast even during transfers that are perceived as single direction
   transfers.  Even small delays in those sends can cause a significant
   performance loss.

   HTTP/1.1 is also affected, especially when sending off a full request
   in a single write() system call.

   In POSIX systems you switch it off like this:

   int one = 1;
   setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));
```

**Comment by bsdphk** [comment]
OK

**Comment by hermunn** [comment]
Backport review: The patch in master, 0205cdf, was just backported as 72435ed.
