### ISSUE TITLE
cache-worker child panic on FreeBSD

### ISSUE THREAD

**Issue by michbsd** [varnishcache/varnish-cache#2136]
After updating Varnish from 4.1.3 to 5.0.0 on FreeBSD 10.0-REL - I see the following child panics  at random in my syslog:

```
Nov 15 17:26:52 nsXXXXXX kernel: pid 87426 (varnishd), uid 429: exited on signal 6
Nov 15 17:26:53 nsXXXXXX varnishd[85454]: Child (87426) died signal=6
Nov 15 17:26:53 nsXXXXXX varnishd[85454]: Child (87426) Panic at: Tue, 15 Nov 2016 16:26:53 GMT "Assert error in child_sigsegv_handler(), mgt/mgt_child.c line 285:   Condition(Segmentation fault by instruction at 0x1) not true.
thread = (cache-worker)
version = varnish-5.0.0 revision 99d036f
ident = FreeBSD,10.0-RELEASE-p2,amd64,-junix,-smalloc,-smalloc,-hclassic,kqueue
Backtrace:
   0x4347c9: varnishd
   0x45dd74: varnishd
   0x8019bb3f6: libthr.so.3
   0x8019baff3: libthr.so.3
 req = 0x80c714020 {
   vxid = 491528,
 transport = HTTP/1 {
     state = HTTP1::Proc
   }
   step = R_STP_RECV,
   req_body = R_BODY_CACHED,
   restarts = 0,
 esi_level = 0,
   sp = 0x81142c220 {
     fd = 67,
 vxid = 720897,
     t_open = 1479227207.636993,
     t_idle = 1479227212.624129,
     transport = HTTP/1 {
       state = HTTP1::Proc
     }
 client = 172.31.255.248 9726,
   },
   worker = 0x7ffffe09cd08 {
     stack = {0x7ffffe09d000 -> 0x7ffffe091000},
     ws = 0x7ffffe09cec8 {
       id = \"wrk\",
       {s, f, r, e} = {0x7ffffe09c4e0, 0x7ffffe09c4e0, 0
Nov 15 17:26:53 ns327570 kernel: e09c4e0, 0
Nov 15 17:26:53 ns327570 kernel: e09c4e0, 0
```

@bsdphk urged me to open a new ticket.

I am using Varnish with the following vmods:
digest, throttle, VSF and GeoIP

Please let me know what else you require in order to debug.

Thanks,

**Comment by michbsd** [comment]
@daghf suggested increasing thread_pool_stack from 48k to 96k - which I have done, will let you know if the problem reoccurs.

**Comment by michbsd** [comment]
The panic occurred again (after increasing thread_pool_stack to 96k) : 

Nov 15 18:10:06 nsXXXXXX varnishd[85454]: Child (87457) died signal=6
Nov 15 18:10:06 nsXXXXXX varnishd[85454]: Child (87457) Panic at: Tue, 15 Nov 2016 17:10:06 GMT "Assert error in child_sigsegv_handler(), mgt/mgt_child.c line 285:   Condition(Segmentation fault by instruction at 0x1) not true. thread = (cache-worker) version = varnish-5.0.0 revision 99d036f ident = FreeBSD,10.0-RELEASE-p2,amd64,-junix,-smalloc,-smalloc,-hclassic,kqueue Backtrace:   0x4347c9: varnishd   0x45dd74: varnishd   0x8019bb3f6: libthr.so.3   0x8019baff3: libthr.so.3 req = 0x82c63c020 {   vxid = 5802044, transport = HTTP/1 {     state = HTTP1::Proc   }   step = R_STP_RECV,   req_body = R_BODY_CACHED,   restarts = 0, esi_level = 0,   sp = 0x80a839c20 {     fd = 25, vxid = 5638631,     t_open = 1479229788.016038,     t_idle = 1479229805.173664,     transport = HTTP/1 {       state = HTTP1::Proc     } client = 172.31.255.248 22242,   },   worker = 0x7ffffef06d08 {     stack = {0x7ffffef07000 -> 0x7ffffeefb000},     ws = 0x7ffffef06ec8 {       id = \"wrk\",       {s, f, r, e} = {0x7ffffef064e0, 0x7ffffef064e0
Nov 15 18:10:06 nsXXXXXX kernel: fffef064e0

**Comment by nigoroll** [comment]
related to #2129 - maybe we should really raise the default?

**Comment by bsdphk** [comment]
Mich, can you try to capture varnishlog when it happens ?

**Comment by bsdphk** [comment]
mich also:

try "varnishadm panic.show" that may give better output

**Comment by michbsd** [comment]
Here you go:

200
-----------------------------
Varnish Cache CLI 1.0
-----------------------------
FreeBSD,10.0-RELEASE-p2,amd64,-junix,-smalloc,-smalloc,-hclassic
varnish-5.0.0 revision 99d036f

Type 'help' for command list.
Type 'quit' to close CLI session.

varnish> panic.show
200
Panic at: Tue, 15 Nov 2016 17:10:06 GMT
"Assert error in child_sigsegv_handler(), mgt/mgt_child.c line 285:
  Condition(Segmentation fault by instruction at 0x1) not true.
thread = (cache-worker)
version = varnish-5.0.0 revision 99d036f
ident = FreeBSD,10.0-RELEASE-p2,amd64,-junix,-smalloc,-smalloc,-hclassic,kqueue
Backtrace:
  0x4347c9: varnishd
  0x45dd74: varnishd
  0x8019bb3f6: libthr.so.3
  0x8019baff3: libthr.so.3
req = 0x82c63c020 {
  vxid = 5802044, transport = HTTP/1 {
    state = HTTP1::Proc
  }
  step = R_STP_RECV,
  req_body = R_BODY_CACHED,
  restarts = 0, esi_level = 0,
  sp = 0x80a839c20 {
    fd = 25, vxid = 5638631,
    t_open = 1479229788.016038,
    t_idle = 1479229805.173664,
    transport = HTTP/1 {
      state = HTTP1::Proc
    }
client = 172.31.255.248 22242,
  },
  worker = 0x7ffffef06d08 {
    stack = {0x7ffffef07000 -> 0x7ffffeefb000},
    ws = 0x7ffffef06ec8 {
      id = \"wrk\",
      {s, f, r, e} = {0x7ffffef064e0, 0x7ffffef064e0, 0x0, +2040},
    },
    VCL::method = inside RECV,
    VCL::return = 0x0,
    VCL::methods = {RECV},
  },
  ws = 0x82c63c1f8 {
    id = \"req\",
    {s, f, r, e} = {0x82c63dff8, +2000, 0x0, +57344},
  },
  http_conn = 0x82c63c128 {
    fd = 25,
    doclose = NULL,
    ws = 0x82c63c1f8,
    {rxbuf_b, rxbuf_e} = {0x82c63dff8, 0x82c63e21e},
    {pipeline_b, pipeline_e} = {0x0, 0x0},
    content_length = 4096,
    body_status = length,
    first_byte_timeout = 0.000000,
    between_bytes_timeout = 0.000000,
  },
  http[req] = 0x82c63c290 {
    ws[req] = 0x82c63c1f8,
    hdrs {
      \"POST\",
      \"/Article/JA2810p030.xml3/\",
      \"HTTP/1.1\",
      \"x-forward: 123.123.123.123\",
      \"Host: www.myhost.com\",
      \"Connection: Keep-Alive\",
      \"Accept-Encoding: gzip\",
      \"CF-RAY: 302450882593540e-LAX\",
      \"Content-Length: 4096\",
      \"X-Forwarded-Proto: http\",
      \"CF-Visitor: {\"scheme\":\"http\"}\",
      \"Content-Type: application/x-www-form-urlencoded; Charset=UTF-8\",
      \"Accept: */*\",
      \"Accept-Language: zh-cn\",
      \"Referer: http://www.myhost.com/Article/JA2810p030.xml3/\",
      \"User-Agent: Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)\",
      \"CF-Connecting-IP: 111.222.222.222\",
      \"X-Forwarded-For: 111.222.222.222, 172.31.255.248\",
      \"grace: none\",
      \"X-VSF-Actual-IP: 111.222.222.222\",
      \"X-VSF-ClientIP: 172.31.255.248\",
      \"X-VSF-Method: POST\",
      \"X-VSF-Proto: HTTP/1.1\",
      \"X-VSF-UA: Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)\",
      \"X-VSF-URL: /Article/JA2810p030.xml3/\",
    },
  },
  vcl = {
    name = \"jaf_1\"
    busy = 59
    discard = 0,
    state = auto,
    temp = warm,
    conf = {
      srcname = {
        \"/usr/local/etc/varnish/jaf.vcl\",
        \"Builtin\",
        \"/usr/local/etc/varnish/security/vsf.vcl\",
        \"/usr/local/etc/varnish/security/build/variables.vcl\",
        \"/usr/local/etc/varnish/security/local.vcl\",
        \"/usr/local/etc/varnish/security/config.vcl\",
        \"/usr/local/etc/varnish/security/rules/protocol.vcl\",
        \"/usr/local/etc/varnish/security/rules/paths.vcl\",
        \"/usr/local/etc/varnish/security/rules/generic.vcl\",
        \"/usr/local/etc/varnish/security/rules/sql.vcl\",
        \"/usr/local/etc/varnish/security/rules/sql.encoded.vcl\",
        \"/usr/local/etc/varnish/security/rules/xss.vcl\",
        \"/usr/local/etc/varnish/security/rules/xss.encoded.vcl\",
        \"/usr/local/etc/varnish/security/rules/demo.vcl\",
        \"/usr/local/etc/varnish/security/rules/php.vcl\",
        \"/usr/local/etc/varnish/security/rules/cmd.vcl\",
        \"/usr/local/etc/varnish/security/rules/restricted-file-extensions.vcl\",
        \"/usr/local/etc/varnish/security/rules/content-encoding.vcl\",
        \"/usr/local/etc/varnish/security/rules/content-type.vcl\",
        \"/usr/local/etc/varnish/security/rules/localfiles.vcl\",
        \"/usr/local/etc/varnish/security/rules/user-agent.vcl\",
        \"/usr/local/etc/varnish/security/build/variables.vcl\",
        \"/usr/local/etc/varnish/security/handlers.vcl\",
      },
    },
  },
  objcore[BODY] = 0x838231f60 {
    refcnt = 1,
    flags = {busy, private},
    exp_flags = {},
    exp = {0.000000, 0.000000, 0.000000, 0.000000}
    objhead = 0x8028de160,
    stevedore = 0x8028a4300 (malloc Transient) {
      Simple = 0x82e0db100
      Obj 0x8382a9978 {priv=0x8382a9970, ptr=0x82e0db100, len=120, space=128}
      LEN = 0x0000000000001000
      VXID = 0x00000000
      FLAGS = 0x00
      GZIPBITS = 0x0...0
      LASTMODIFIED = 0x0...0
      VARY = {len=0, ptr=0x0}
      HEADERS = {len=0, ptr=0x0}
      Body 0x8382a99c8 {priv=0x8382a99c0, ptr=0x84a2ba000, len=4096, space=4096}
    },
  },
  flags = {
  },
},

"

**Comment by michbsd** [comment]
Writing varnishlog to a file until it happens again...

**Comment by michbsd** [comment]
Got it - anything is particular I should look for?

**Comment by bsdphk** [comment]
A more detailed backtrace ?

I would also help if you could run an unstripped binary so we get more detail in the backtrace

**Comment by bsdphk** [comment]
Basically, what we need to find out is where Varnishd is when it explodes, and the backtrace is not much help as it is above.  if varnishlog or any other information can give a clue that would help.
Bear in mind that due to the explosion the varnishlog may actually not have the offending transaction.

Doing a "varnishadm param.set debug +syncvsl" may help that

**Comment by michbsd** [comment]
yeah varnishlog stopped logging when it happened.. and resumed by itself. Will try with "varnishadm param.set debug +syncvsl" and log again.

**Comment by michbsd** [comment]
This happens every time there is panic:

 ❯ varnishlog -w varnishlog151116-185000.log                                [6:50:31 PM]
Log abandoned
Log reacquired
Log abandoned
Log reacquired
^C#

Guess it is normal... ?

**Comment by michbsd** [comment]
I finally figured out how to reproduce it!
Sending a special POST request to the URL "/Article/JA2810p030.xml3/\" would return an empty reply:

❯ curl -XPOST -A "Abekat/123" 'http://www.myhost.com/Article/JA2810p030.xml3/' -d "LORT"
curl: (52) Empty reply from server

@bsdphk asked me to check out vmods in vcl_recv() - and after commenting out the vsf include the problem is gone.

So it must be somewhere in the Varnish Security Firewall it fails.

I will open a ticket with VSF! 

Many thanks for quick feedback and assistance!

**Comment by hermunn** [comment]
Backport review: Nothing commited - nothing to backport. (The problem seems to be in Varnish Security Firewall.)
