### ISSUE TITLE
ip comparison fails

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2142]
`if (remote.ip != client.ip) { ... }`
fails with
`Expected CSTR got 'client.ip'`
I don't see any reason why this shouldn't work

**Comment by Dridi** [comment]
IP addresses should be compared without taking the port number into account. It should be documented once fixed too.

**Comment by Dridi** [comment]
Reopening because I did not bump the VRT ABI, for now. I'd like to avoid conflicting with #2145.

**Comment by fgsch** [comment]
Documented in vrt.h.

**Comment by hermunn** [comment]
Backport review: This is not for 4.1, as it seems that a VRT ABI update is necessary and the gain is small.
