### ISSUE TITLE
Storage.free_space - compilation fails

### ISSUE THREAD

**Issue by acachy** [varnishcache/varnish-cache#2146]
Update from the 4.1 to last version "varnish-trunk revision 76876e7"

With old VCL configtest finishes OK

But service start fails with:
Message from VCC-compiler:
Nov 26 16:02:24 vm101327.local varnishd[29689]: Symbol not found: 'storage.fast.free_space' (expected type BOOL):
Nov 26 16:02:24 vm101327.local varnishd[29689]: ('/etc/varnish/user.vcl' Line 17471 Pos 16)
Nov 26 16:02:24 vm101327.local varnishd[29689]: if(storage.fast.free_space > 2MB)

Without free_space check string - no problem

- Backend type is malloc
- Compiler - gcc

**Comment by fgsch** [comment]
WFM. Can you provide the varnishd command line you are using?

**Comment by acachy** [comment]
/usr/sbin/varnishd -a :81 -l 5m -T localhost:7090 -f /etc/varnish/user.vcl -S /etc/varnish/secret -p workspace_backend=128k -p cli_buffer=32k -p cli_limit=96k -p cli_timeout=150 -p max_retries=7 -p thread_pool_destroy_delay=0.01 -p thread_pool_timeout=600 -p thread_queue_limit=1000 -p nuke_limit=33072 -p lru_interval=60 -p send_timeout=700 -p idle_send_timeout=75 -p ban_lurker_sleep=0.5 -p ban_lurker_batch=25 -p ban_lurker_age=1 -p gzip_level=9 -p listen_depth=16383 -p fetch_chunksize=8k -p thread_pool_min=15 -p thread_pool_max=25 -p thread_pools=2 -s medium0=file,/m0/s.bin,10000m  -s fast=malloc,50m -s junk=malloc,3m

**Comment by fgsch** [comment]
Ok, still passing here. Can you share your VCL, OS, etc?
Also how are you starting varnishd?

**Comment by acachy** [comment]
1. Starts as systemd-service. 
Service file left same as it was for 4.1.
2. Debian 8
3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u2~bpo70+1 (2015-07-22) x86_64 GNU/Linux
4. Repeated with almost empty vcl
[user.vcl.txt](https://github.com/varnishcache/varnish-cache/files/617689/user.vcl.txt)
varnishd[31626]: Symbol not found: 'storage.fast.free_space' (expected type BOOL):
varnishd[31626]: ('/etc/varnish/user.vcl' Line 16 Pos 12)
varnishd[31626]: if(storage.fast.free_space > 2MB)
`

**Comment by fgsch** [comment]
Something is wrong in your setup. 
Are you perhaps using drop-in files with systemd or have multiple varnish installed?

The only time that error will show is if fast is not defined as you can see in the following varnishtest case:

```
varnishtest "storage.name.free_space works"
       
varnish v1 -arg "-s foo=malloc,10m" -vcl {
        backend default {
                .host = "127.0.0.1";
        }
        sub vcl_backend_response {
                if (storage.foo.free_space > 2MB) {
                }
        }
}      
       
varnish v1 -errvcl {Symbol not found: 'storage.bar.free_space' (expected type BOOL):} {
        backend default {
                .host = "127.0.0.1";
        }
        sub vcl_backend_response {
                if (storage.bar.free_space > 2MB) {
                }
        }
} 
```

**Comment by fgsch** [comment]
I'm not entirely sure why you are seeing this but I'm having a hard time believing this is a varnish problem so I'm closing this. If you cannot find the root case please reopen it.

**Comment by acachy** [comment]
Thank you extremely much.
You're right. 

It's connected with new version, but more with admin mistake.

No code changes needed, just maybe the story could be useful for someone.

In systemd I use "default" varnish.service file (got from "apt-get" way on Debian).

It contains string that was left unchanged 
"ExecStartPre=/usr/sbin/varnishd -C -f /etc/varnish/user.vcl"

So, it's reasonable if varnish don't know about specific storage names on that stage.

But this command with same VCL works with no problems on 4.1 version. 
Anything could be used as a storage-names and no error would appear. 
So, new version just better in checking mistakes on compilation stage.

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
