### ISSUE TITLE
Health probes do not honor a backend's PROXY protocol setting

### ISSUE THREAD

**Issue by fgtham** [varnishcache/varnish-cache#2151]
I'm using varnish-5.0.0 with PROXY protocol enabled on the backends thanks to the new `.proxy_header` attribute. This works great as long as the backends don't have health probes defined. When a backend has both a `.proxy_header` attribute and a probe defined, varnish fails to properly detect the backend health state and marks the backend as sick.

The problem seems to be that varnish does not use the PROXY protocol when sending health probes. If the backend correctly implements the PROXY protocol, it is required to drop the connection, as it cannot identify it as valid PROXY protocol v1 nor v2. Thus, from varnish's pov the backend is unreachable.

## Possible Solution
Health probes should honor the backend's `.proxy_header` attribute and send the correct PROXY header where appropriate.

**Comment by fgsch** [comment]
While I agree with the bug I'm not sure if we should assume that the probe should use the proxy protocol based on the backend definition. 

We don't for the timeouts and if we did for the probe we could not have a pure HTTP probe for a backend behind PROXY, although I'm not sure if this is a problem in RL.

**Comment by Dridi** [comment]
Don't we have different timeouts for the probe? The problem is that if the backend is expecting a PROXY preamble on the socket, we need to provide one. It's like on the accept side where Varnish can listen to either PROXY or not, but not both cases on the same socket.

**Comment by nigoroll** [comment]
A workaround is to use a proxyV1 `.request` probe like so
```
probe probe_varnish_pxy {
        .request =
                "PROXY TCP4 127.0.0.1 127.0.0.1 1 1"
                "GET /PROBE_URL HTTP/1.1"
                "Host: HOSTNAME"
                "Connection: close";
```
We should fix this nevertheless

**Comment by Dridi** [comment]
Further discussions after my previous comment:

> 14:20 < fgs> dridi: i have no idea what you meant with your comment on the issue
14:21 < fgs> dridi: re proxy header
14:21 < fgs> dridi: yes, we obviously need to send the proxy header if that's what expected
14:21 < fgs> dridi: and yes, that's a bug. My question, however, was something else.
14:25 < dridi> fgs: then I completly misunderstood your comment
14:25 < fgs> that's what I'm afraid of
14:31 < fgs> What I'm saying is that we should not derivate the need for the proxy header from the backend definition
14:31 < fgs> (we don't do these for the timeouts, for example)
14:32 < fgs> But rather have this as a separate parameter in the backend probe
14:32 < fgs> definition
14:33 < dridi> fgs: but then you can't safely share a probe between proxy-enabled and regular backends
14:40 < fgs> dridi: correct

**Comment by nigoroll** [comment]
NB the workaround assumes that the backend supports proxyv1. proxyv2 can still be used for the actual requests. I have this in production for varnish/varnish clustering

**Comment by fgtham** [comment]
@nigoroll I like your workaround, thank you!

**Comment by fgsch** [comment]
@fgtham we had a long discussion today, one of the longest one ever in fact, for any single issue.
A few things came to light, so we're going to check with Willy a few details.

In the meantime, mind to share what you are running on your backend that speaks the PROXY protocol?
Also, do you have some ACL or another way to control who is allowed to do the probes?

**Comment by fgtham** [comment]
@fgsch we use haproxy v1.7 as backends. A set of iptables rules makes sure that they can only be accessed from the varnish hosts.

**Comment by fgsch** [comment]
@fgtham right, but since you are using the proxy protocol, how you differentiate (or are you planning to) requests coming from varnish (backend probes) vs coming from client (requests)?

**Comment by fgtham** [comment]
@fgsch Basically this is our setup:

```
   inet
     |
     | :80
+----+----+               +---------+
|         |-------------->|         |
| haproxy |               | varnish |
|         |<--------------|         |
+----+----+ :90           +---------+
     |
     |
 +---+---+
 |   |   |
app app app ....
```

So, in addition to haproxy being varnish backends as mentioned in my previous comment, varnish is also an haproxy backend. The varnish servers query a monitor URI, /haproxy-backend-status, on the haproxy backend available on port :90 above, to get haproxy backend state.

The public-facing haproxy frontend does not accept requests for /haproxy-backend-status in the first place.  Additionally, varnish rejects all requests for /haproxy-backend-status in vcl_recv, just in case. Therefore I don't see the need to further differentiate the requests.

**Comment by fgsch** [comment]
Thanks for the info. There is some food for thought in there.

**Comment by nigoroll** [comment]
Follow up to the irc discussion: IIUC, concensus so far was that `LOCAL` PROXY requests are to be used for health checks and that varnish should handle them properly. For this case, we should have client.ip == remote.ip and server.ip == local.ip as for a non-PROXY connection. We should consider adding a local.proto being set to the protocol on the accepting socket (`HTTP/1` or `PROXY` atm).

**Comment by fgsch** [comment]
@nigoroll reading irc, the consensus was to check with Willy first, something @Dridi was going to do.

**Comment by nigoroll** [comment]
@fgsch yes, also

**Comment by Dridi** [comment]
As I said I would on IRC, I first checked how haproxy uses the proxy protocol on the backend side, and it indicates that `LOCAL` is the way to go. I looked at how proxy lines are constructed and drilled back up until I came across this comment:

```
/* The target server expects a PROXY line to be sent first.
 * If the send_proxy_ofs is negative, it corresponds to the
 * offset to start sending from then end of the proxy string
 * (which is recomputed every time since it's constant). If
 * it is positive, it means we have to send from the start.
 * We can only send a "normal" PROXY line when the connectio
 * is attached to a stream interface. Otherwise we can only
 * send a LOCAL line (eg: for use with health checks).
 */
```

It then raises another question that should be discussed before we'd implement it. How would that translate on the client side? For instance, when Varnish is the backend of another Varnish using proxy protocol and involving probes. For that matter, the spec says that handling `UNSPEC` is mandatory so I'm assuming we at least already parse it.

Also, there's no `LOCAL`/`UNSPEC` for the protocol v1, only `UNKNOWN`. So that's another case to ponder if we speak v1 to the backend.

**Comment by bsdphk** [comment]
So many details...

1. Our configuration (-a) should probably be able to say "mandatory PROXY" vs. "optional PROXY"

2. I'm not sure how we would/should/could deal with UNSPEC in either case.

3. By default we should send PROXY on health-checks if the backend is configured for PROXY, but it should probably also be possible to configure that in the probe itself.

**Comment by fgsch** [comment]
Outcome from irc:

1. PROXY is not optional.

2. UNSPEC = pretend PROXY didn't happen. 

3. Dridi to decide on this and document it.

**Comment by Dridi** [comment]
Outcome from my (most delayed) chat with Willy:

1. Confirmed.

2. UNKNOWN for v1, LOCAL for v2, more on "pretend" below.

The two points above are for the backend side, probe requests initiated by Varnish. If Varnish receives such proxy lines on the client side (because you may stack Varnish instances and have Varnish-to-Varnish health checks) local/remote IPs should match server/client IPs.

UNKNOWN/LOCAL traffic could still be detected in VCL without changing the language.

As a side note, an L4 proxy like Hitch receiving UNKNOWN/LOCAL should forward it as the actual client address (TCP/IPv[46]). Should you make Varnish-to-Varnish health checks over TLS for example.

**Comment by hermunn** [comment]
Backport review: If I am not mistaken, this is only relevant if #2244 makes it into 4.1. In other words, no backporting unless #2244 is backported.
