### ISSUE TITLE
Add the current VXID to the Begin log record

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2154]
There is currently no way that I know of to use a vxid in a VSL query, because no record exist in transaction with a field containing the transaction's id.

The closest one is `Begin`:

```
%s %d %s
|  |  |
|  |  +- Reason
|  +---- Parent vxid
+------- Type ("sess", "req" or "bereq")
```

In order not to break, I would suggest this change:

```
%s %d %s %d
|  |  |  |
|  |  |  +- Current vxid
|  |  +---- Reason
|  +------- Parent vxid
+---------- Type ("sess", "req" or "bereq")
```

It shouldn't break existing tools and allow lookups like `varnishlog -q "Begin[4] == $vxid"`.

**Comment by fgsch** [comment]
You can already do this using grouping (e.g. -g request).

**Comment by Dridi** [comment]
I don't know how you'd query a specific vxid.

**Comment by fgsch** [comment]
This will bring the whole request but should do it: `varnishlog -g request -q "Begin[2] == $vxid"`.

**Comment by Dridi** [comment]
`Begin[2]` would be the parent transaction, not the one I'm looking for.

**Comment by fgsch** [comment]
It will match on the child so you will get the parent. 
That said, to cover all cases you also need to check Link[2].

**Comment by Dridi** [comment]
Yes, I can either query a parent or a child vxid, not the *current* one. So depending on the grouping I need I may not get the results I expect.

What I'm proposing is to fix having to work around the main problem. I pick an `X-Varnish` header on an interesting transaction and want to query one of the vxids it's showing (eg. using `-r` or `-d`) but today I have to deal with relatives and proper grouping.

**Comment by bsdphk** [comment]
Dridi, the current VXID is present in all VSL records, but it is a binary field which is not part of the text and not normally rendered.

I'll leave it to Martin to find out if the query language should be extended or if rendering it in begin's text is smarter.

**Comment by Dridi** [comment]
I know, you get them with `varnishlog -v` but it doesn't solve the query limitation. Assigning to @mbgrydeland.

**Comment by mbgrydeland** [comment]
Moved to different TODO list. Closing ticket due to it not being a bug.

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
