### ISSUE TITLE
vmodtool removes text following $Event from RST docs

### ISSUE THREAD

**Issue by slimhazard** [varnishcache/varnish-cache#2155]
## Expected Behavior
I thought that I could add an ``$Event`` declaration anywhere to a VCC source, since it wouldn't matter where it's declared, and that the text in the VCC file following ``$Event`` would be rendered into the generated RST docs.

## Current Behavior
All text following ``$Event``, until either the next declaration or end of file, is removed from the RST.

vmodtool emits this warning:
```
WARNING: $Event description is not included in .rst:
```
... and then a Python array of strings containing the removed lines (may be just empty strings if ``$Event`` is the last non-empty line in the file). At least sometimes -- I only noticed that while setting up the toy example below, not while running make targets during VMOD development. When that happened, over 140 lines were removed, which should have been obvious, but I don't remember seeing the warning.

## Possible Solution
The intention is evidently either to "correct" VMOD authors who thought they could write public docs for the private event function; or to allow such documentation, but restrict it to the VCC file.

But does anybody do that? I personally doubt it, and would suggest that this "feature" be dropped altogether.

If we don't drop it, I would suggest that this behavior at least be documented, in the VMOD reference doc. Seeing so much text disappear from the RST was for me an extreme POLA violation, as was discovering that the contents of RST depend on the location of ``$Event``.

Another option: don't remove the text, and add a suggestion in the reference doc that VMOD authors who want to document an ``$Event`` use the [RST comment syntax](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#comments). That way, the RST contents remain unchanged, but the description for ``$Event`` is not rendered from RST into other outputs like man or html.

## Steps to Reproduce (for bugs)
Run vmodtool on this VCC:
```
$Module foo 3 vmod foo

$Event event

This is some documentation that ought to be rendered into the RST.

$Function VOID foo()
```
Then the line "This is some documentation ..." does not appear in the RST.

For this VCC:
```
$Module foo 3 vmod foo

This is some documentation that ought to be rendered into the RST.

$Function VOID foo()

$Event event
```
... the line does appear in RST.

## Context
VMOD development

## Your Environment
I doubt that it matters, but for the record I saw this with both trunk and Varnish 4.1.4.

**Comment by bsdphk** [comment]
This is on purpose, the .VCC file has structure ( "^$something") * and there is no way to tell where the text under $Event needs to go in the .RST if we don't also emit the $Event.

**Comment by bsdphk** [comment]
Long term plans are to ditch .VCC and pull the info we need out of user-written .RST instead.

**Comment by slimhazard** [comment]
Following discussion on IRC, I'll work up an idea to have RST as the source, presumably with directives for the VMOD declarations, so that the vmodtool generates ``vcc_if.*`` from the declarations. VCCs files will then be retired.

**Comment by Dridi** [comment]
Following further discussion on IRC, the current `vmodtool` doesn't need to be retired as soon as a new solution would land.

**Comment by hermunn** [comment]
Backport review: Since vmodtool has been rewritten, and this is just a warning, I do not imagine this being backported.
