### ISSUE TITLE
Varnish reload-vcl and varnishadm is caching failed .vcl data on reload and stops working

### ISSUE THREAD

**Issue by justnx** [varnishcache/varnish-cache#2160]
## Expected Behavior
reload current .vcl without the error previously made

## Current Behavior
if you made a mistake for example write an resp set header in vcl_recv method and execute a reload by using shellscript: reload-vcl following error won't disapear:

Command failed with error code 106
Message from VCC-compiler:
'resp.http.Access-Control-Allow-Origin': cannot be set in method 'vcl_recv'.
At: ('input' Line 52 Pos 21)
                set resp.http.Access-Control-Allow-Origin = "*";
--------------------#####################################-------
Running VCC-compiler failed, exited with 2
VCL compilation failed
Error: vcl.load root_f0d919eb-fcbb-4262-85ef-695ddd3841d3 /etc/varnish/custom.vcl failed

It looks like the error .vcl is cached somewhere. I removed the failing line fro my custom.vcl and start/stop varnish doing well, but when i try to reload varnish the error still persists. 

## Possible Solution
None yet

## Steps to Reproduce (for bugs)
1. Add wrong line somewhere in vcl_recv: set resp.http.Access-Control-Allow-Origin = "*";
2. systemctl reload varnish
3. see varnish failing
4. Remove failing line from .vcl. systemctl stop varnish; systemctl start varnish; systemctl reload varnish and see VCC-Compiler claiming same error again.
5. Try doing reload manually with varnishadm. Exactly same effect.

## Context
Varnish reload stops working and can't recover at this stage.

## Your Environment
* Version used: varnish 4.0.3-5~jessie
* Operating System and version: Debian Jessie 8.6

**Comment by justnx** [comment]
Nevermind this. It was an Cluster issue, since my varnishadm listens to failover ip and vcl on other node was faulty, it gave out this error :-D

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
