### ISSUE TITLE
varnish 4.1.4 and libvarnishapi-dev 4.1.3 libvarnishapi.so conflict

### ISSUE THREAD

**Issue by jasonpursian** [varnishcache/varnish-cache#2161]
Newest varnish 4.1.4 release for Debian tries to overwrite libvarnishapi.so from libvarnishapi-dev 4.1.3

## Expected Behavior
Installing varnish and libvarnishapi-dev via repo should not result in an error.

## Current Behavior
When installing varnish and libvarnishapi-dev at the same time (via apt from the repo), a dpkg error is generated and installation of varnish fails.

Error log:

```
root@jibakurei:/home/ubuntu# apt install varnish
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  varnish-dev
The following NEW packages will be installed:
  varnish
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/2,415 kB of archives.
After this operation, 5,997 kB of additional disk space will be used.
(Reading database ... 109777 files and directories currently installed.)
Preparing to unpack .../varnish_4.1.4-1~trusty_amd64.deb ...
Unpacking varnish (4.1.4-1~trusty) ...
Replacing files in old package libvarnishapi1 (4.1.3-1~trusty) ...
dpkg: error processing archive /var/cache/apt/archives/varnish_4.1.4-1~trusty_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/libvarnishapi.so', which is also in package libvarnishapi-dev 4.1.3-1~trusty
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for systemd (229-4ubuntu12) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 /var/cache/apt/archives/varnish_4.1.4-1~trusty_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

## Possible Solution
Did varnish package install libvarnishapi.so earlier? Specifying varnish 4.1.3 works.

## Steps to Reproduce (for bugs)
Install varnish and libvarnishapi-dev from via apt from the repo, without specifying a version.

## Context
I'm installing varnish and the api/dev packages (for vmods) at the same time using chef, which pulls down the latest version of each from the repo, and now the build fails.

## Your Environment
Ubuntu 16.04 LTS

**Comment by fgsch** [comment]
Moved to https://github.com/varnishcache/pkg-varnish-cache

**Comment by hermunn** [comment]
Backport review: Nothing to backport.
