### ISSUE TITLE
could do less calls to VEP_Parse()

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2166]
Noticed while working on #1988 

> (15:16:52) slink: phk also we should probably re-visit esi parsing because we enter VEP_Parse again and again for small increments of p
> (15:17:28) slink: most likely this is the reason why we hit this bug in production, because, as I suspected earlier, VEP_MATCHBUF is used unnecessarily

**Comment by nigoroll** [comment]
Most likely I have just observed the effects of `debug +esi_chop`

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
