### ISSUE TITLE
no config

### ISSUE THREAD

**Issue by Anolias** [varnishcache/varnish-cache#2169]
i have a problem with the varnish cache on solaris 11. i have no config file. i read about varnish.params but that file isnt on my system. i even have to start varnish from the command line with the daemon opts. is there any solution for that?

**Comment by Dridi** [comment]
I already replied to a very similar question in the misc mailing list an hour ago, we simply don't support them. Either you installed Varnish from source, and that's to be expected, or you installed Varnish from packages and you should ask your system's packager instead.

You can try to copy init services from the pkg-varnish-cache repo, but we only support Debian/Ubuntu and Red Hat derivatives so they may not work.

**Comment by Dridi** [comment]
For more information, you can have a look at the supported platforms:

http://varnish-cache.org/docs/trunk/phk/platforms.html

**Comment by nigoroll** [comment]
If you're using a distribution which does not ship varnish, you need to invest some time (or get commercial support - see http://varnish-cache.org/business/index.html#business

Having said that, varnish works fine with a simple SMF integration, see below for an example. You probably need to replace paths and at the very least `__ARGS__`.

```
<?xml version='1.0'?>
<!DOCTYPE service_bundle SYSTEM '/usr/share/lib/xml/dtd/service_bundle.dtd.1'>
<service_bundle type='manifest' name='export'>
  <service name='site/varnish' type='service' version='0'>
    <create_default_instance enabled='true'/>
    <single_instance/>
    <dependency name='network' grouping='require_all' restart_on='error' type='service'>
      <service_fmri value='svc:/milestone/network:default'/>
    </dependency>
    <dependency name='filesystem-local' grouping='require_all' restart_on='none' type='service'>
      <service_fmri value='svc:/system/filesystem/local:default'/>
    </dependency>
    <dependency name='config-file' grouping='require_all' restart_on='refresh' type='path'>
      <service_fmri value='file://localhost/etc/varnish/default.vcl'/>
    </dependency>
    <exec_method name='start' type='method' exec='/usr/local/sbin/varnishd __ARGS__' timeout_seconds='30'>
      <method_context>
        <method_credential user='varnish' group='varnish' privileges='basic,!proc_session,!proc_info,!file_link_any,net_privaddr' limit_privileges='basic,!proc_session,!proc_info,!file_link_any,net_privaddr'/>
        <method_environment>
          <envvar name='PATH' value='/usr/local/sbin:/usr/local/bin:/opt/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin'/>
        </method_environment>
      </method_context>
    </exec_method>
    <exec_method name='stop' type='method' exec=':kill' timeout_seconds='30'/>
    <property_group name='startd' type='framework'>
      <propval name='ignore_error' type='astring' value='core,signal'/>
    </property_group>
    <stability value='Evolving'/>
    <template>
      <common_name>
        <loctext xml:lang='C'>Varnish server</loctext>
      </common_name>
    </template>
  </service>
</service_bundle>
```

**Comment by Anolias** [comment]
thanks for your reply. i created a scripts which writes the service for me with a config file and it now works fine

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
