### ISSUE TITLE
Running VCC-compiler failed, exited with 2

### ISSUE THREAD

**Issue by AlexShapka** [varnishcache/varnish-cache#2171]
Following instructions on https://www.drupal.org/docs/7/caching-to-improve-performance/varnish-4x-configuration is giving the "Running VCC-compiler failed, exited with 2" as soon as I add either of vcl_recv or acl purge section and restart Varnish.

## Expected Behavior

Expected behaviour was for Varnish to come up with the recommended settings.

## Current Behavior

Varnish vcl file works fine with the "sub vcl_recv" example on https://www.drupal.org/docs/7/caching-to-improve-performance/varnish-4x-configuration added and restarted. However, if I add "acl purge" or "vcl_recv" section, then Varnish doesn't come up. Running the `journalctl -xe` command in CLI gives:

```
Dec 21 13:48:38 ns1.website.com varnishd[2737]: Message from VCC-compiler:
Dec 21 13:48:38 ns1.website.com varnishd[2737]: Expected one of
Dec 21 13:48:38 ns1.website.com varnishd[2737]: 'acl', 'sub', 'backend', 'director', 'probe', 'import',  or 'vcl'
Dec 21 13:48:38 ns1.website.com varnishd[2737]: Found: 'vcl_recv' at
Dec 21 13:48:38 ns1.website.com varnishd[2737]: ('input' Line 8 Pos 1)
Dec 21 13:48:38 ns1.website.com varnishd[2737]: vcl_recv {
Dec 21 13:48:38 ns1.website.com varnishd[2737]: ########--
Dec 21 13:48:38 ns1.website.com varnishd[2737]: Running VCC-compiler failed, exited with 2
Dec 21 13:48:38 ns1.website.com varnishd[2737]: VCL compilation failed
Dec 21 13:48:38 ns1.website.com systemd[1]: varnish.service: control process exited, code=exited status=2
Dec 21 13:48:38 ns1.website.com systemd[1]: Failed to start Varnish a high-perfomance HTTP accelerator.
```

## Your Environment
My Environment:

```
PHP 5.6.5 (cli) (built: Jun 29 2015 08:20:04) 
CentOS Linux release 7.3.1611 (Core) 
varnishd (varnish-4.0.3 revision b8c4a34)
```

**Comment by nigoroll** [comment]
your vcl has a syntax error before line 8 (forgotten braces? forgotten semicolon?)

**Comment by Dridi** [comment]
Missing `sub` keyword I think.

**Comment by nigoroll** [comment]
@Dridi someone who uses vcl since 2008 could have noticed ;)

**Comment by AlexShapka** [comment]
Guys, bear with me, but the https://www.drupal.org/docs/7/caching-to-improve-performance/varnish-4x-configuration has two different suggestions, one for:

`sub vcl_recv`

and another for

`vcl_recv`

Are instructions on https://www.drupal.org/docs/7/caching-to-improve-performance/varnish-4x-configuration outdated?

**Comment by nigoroll** [comment]
we dont write drupal documentation. Please refer to varnish documentation. This is not a help desk. Thank you

**Comment by gquintard** [comment]
...but you are welcome to ask on varnish-misc or on IRC.

https://www.varnish-cache.org/support/index.html

**Comment by fgsch** [comment]
@AlexShapka, What @nigoroll and @gquintard said is correct.

I read the link you mentioned, however, and I believe you're misunderstanding the documentation.
The first mention introduces `vcl_recv` and therefore the `sub` keyword is referred explicitly.

The second mention is to add code to the existing subroutine, so it just mentions its name.

In both cases is talking about the sub(routine) vcl_recv.

If it's not clear you should take this to the Drupal people.

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
