### ISSUE TITLE
varnish can not failover between multi different backends

### ISSUE THREAD

**Issue by lixp** [varnishcache/varnish-cache#2172]
backend app8080 {
  .host = "192.168.20.39";
  .port = "8080";
}
backend app9090 {
  .host = "192.168.20.49";
  .port = "9090";
}

while app8080 or app9090 is down, varnish  say 503 to client. how can i configure to failover between different backends automatically while a backend is down.best wishes. thanks.

**Comment by nigoroll** [comment]
* RTFM: http://varnish-cache.org/docs/trunk/users-guide/vcl-backends.html#directors
* See here for support options, this is not a help desk: http://varnish-cache.org/support/index.html
