### ISSUE TITLE
Parallel make VMOD builds fail against current master

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2173]
## Current Behavior

I get two different errors, one happens more often than the other.

The frequent one:

```
mv: cannot stat '.deps/vcc_querystring_if.Tpo': No such file or directory
```

The rare one:

```
Traceback (most recent call last):
  File "/opt/varnish-master/share/varnish/vmodtool.py", line 877, in <module>
    runmain(i_vcc, opts.rstdir, opts.output)
  File "/opt/varnish-master/share/varnish/vmodtool.py", line 841, in runmain
    v.cfile()
  File "/opt/varnish-master/share/varnish/vmodtool.py", line 823, in cfile
    os.remove(fn2)
OSError: [Errno 2] No such file or directory: 'vcc_querystring_if.c.tmp2'
```

## Possible Solution

Square things up :)

## Steps to Reproduce (for bugs)

1. cd path/to/vmod
1. export PKG_CONFIG_PATH=/path/to/varnish-master/lib/pkgconfig
1. export ACLOCAL_PATH=/path/to/varnish-master/share/aclocal
1. ./configure
1. make clean
1. make -j32 all

## Your Environment
* Version used: current master at 5db732c
* Operating System and version: Fedora 25

**Comment by bsdphk** [comment]
I've looked a little bit at this and started to sort out our dependencies more clearly.

I've also, against my doctors advise, looked at how autocrap handles parallism and I should have heeded his advice.

Getting rid of autocrap is the way to go, and our source tree is small enough to not need recursive make and list all the non-name-derivable dependencies explicitly, which will solve this once and for all.

I'm closing this ticket, we know what to do, and this ticket is no help.

**Comment by hermunn** [comment]
Backport review: A decision to get rid of autotools was indicated, but not carried out. Anyhow, this will not be backported, and a acceptable workaround for 4.1 is to build VMODs without parallelism.

**Comment by nigoroll** [comment]
@Dridi This smells like parallel execution of vmodtool, which should avoided by setting appropriate dependencies in the vmod, IMHO. I know that others had wanted to make vmodtool be agnostic regarding parallel execution, but I don't agree that this is the right way.
Refs:
* #1866
* https://github.com/varnish/libvmod-example/commit/82d2522712892b6edffdc4d805ce7400c52d1f34
