### ISSUE TITLE
Clarify interactions between restarts and labels

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2177]
According to this evening's discussions, all of the `expect` statements should fail, but the test case passes.

Today's behavior:

- it is possible to switch VCLs after a restart
- the label inherits the number of restarts so far

It is a priori not desirable to switch to a label after a restart from the top VCL.

However I can imagine cases where it could be useful to do a request from the top VCL, and possibly restart and switch to a label. Basically doing some sort of lookup from the top VCL and then deciding whether to let a label handle the original request or not. For example, to enable/disable proxy-ing of services dynamically, centralize authentication, centralize invalidation, implement circuit breakers [1] etc...

If we allow it, I think the label should start with `req.restarts == 0`.

```vcl
varnishtest "restart then switch to label"

server s1 {
	rxreq
	txresp
} -start

server s2 {
	rxreq
	txresp -status 404
} -start

varnish v1 -vcl {
	backend s1 { .host="${s1_addr}"; .port="${s1_port}"; }

	sub vcl_recv {
		set req.http.Label-Restarts = req.restarts;
	}

	sub vcl_deliver {
		set resp.http.Top-Restarts = req.http.Top-Restarts;
		set resp.http.Label-Restarts = req.http.Label-Restarts;
	}
}

varnish v1 -cli "vcl.label lbl vcl1"

varnish v1 -vcl {
	backend s2 { .host="${s2_addr}"; .port="${s2_port}"; }

	sub vcl_recv {
		set req.http.Top-Restarts = req.restarts;
		if (req.restarts > 0) {
			return (vcl(lbl));
		}
	}

	sub vcl_miss {
		return (restart);
	}
} -start

client c1 {
	txreq
	rxresp
	expect resp.status == 200
	expect resp.http.Top-Restarts == 1
	expect resp.http.Label-Restarts == 1
} -run
```

[1] That would different than saintmode per-backend circuit breakers

**Comment by bsdphk** [comment]
Actually, we may have to go in the other direction instead.

Fundamentally the problem is this:

Transaction starts in VCL1

VCL1 does req.http.foobar = vmod_illadvised.compiled_in_table_lookup()

VCL1 does return(vcl(VCL2))

Admin does vcl.use VCL3

Admin does vcl.discard VCL1, which was the only user of vmod_illadvised.

**Comment by hermunn** [comment]
Backport review: NA - labels are not part of 4.1.
