### ISSUE TITLE
March'17 release: 5.1 or 6.0 ?

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2183]
Input welcome

**Comment by nigoroll** [comment]
IIUC we have avoided breaking changes so far, so unless someone has a valid point, it should be 5.1 i think

**Comment by denisbr** [comment]
5.1 sounds good to me if there are no breaking changes.

**Comment by nigoroll** [comment]
I'd have a bunch of plans for breaking changes, but whether or not they will a) get implementation resources and b) actually get merged are completely different stories, so I'd prefer not to view the question from this angle. IF/WHEN we have breaking changes ready, we should make a decision, not before.

**Comment by fgsch** [comment]
I'd go for 5.1.

Besides breaking changes there are no major changes since 5.0.

My hopes were on the HTTP/2 front but it's been somewhat quiet on that area.

**Comment by Dridi** [comment]
I'd rather discuss whether September'17 should be 5.2 or 6.0, setting goals before the new cycle starts: should we avoid breakage in the next 6 month?

**Comment by nigoroll** [comment]
As far as we as a company (UPLEX - mostly @slimhazard and myself) are concerned, varnish development is way too much driven by customer demand and sponsoring agreements to make any commitment as to whether or not we'd work on breaking or non-breaking changes within the next cycle. As mentioned before, my personal vote would be for _do what needs to be done and set major/minor accordingly when the work is done_. If the project required a different scheme, we would try to adopt.

**Comment by Dridi** [comment]
@nigoroll I don't disagree with your view, but if we do that there's no real need to discuss the next version further than "how much did we break?" to pick "the logical one".

We tend to maintain forward-compatibility on the VCL side, although we technically broke `vcl 4.0;` if we include the VMODs we ship. VRT is broken more often, but I'm not sure it's a criteria for a `next.0` release. I'm not sure how we keep track of shmlog changes but I would assume `libvarnishapi` is a good candidate (but we break the ABI every time we sort records alphabetically). And regarding command line interfaces (`varnish*` programs and the varnish-cli) AFAICT there's no tracking in place. I'm not including `varnishtest`/VTC although it'd be nice to see some stability there (or have a means to know when breaking changes like `err_shell` occur).

I'd say 5.1 (that my previous message implied) but we could have a list of things to check before a release to help decide. We collect changes made regarding the check-list and use that as the basis for the discussion. Sometimes it's not just breakage, new significant features too.

My EUR 0.02

**Comment by bsdphk** [comment]
I'm firmly with Nils on "doing what needs to be done", and the question is posed to find out if what needs to be done in january and february forces the release to be 6.0 or not ?

With respect to dridis question, my definition of a trigger for dot-zero, is that users will need change their VCL, possibly reading documentation to do so, or that more than a few VMODs will need significant changes.

**Comment by bsdphk** [comment]
Discussed at bugwash.  Too early to tell, but so far 6.0 is not required.

**Comment by joshuaspence** [comment]
Are there any plans to release a 5.0.1 version? We are experiencing a number of issues with Varnish 5.0.0 which have been fixed at HEAD, specifically #2041, #2201 and #2207.
