### ISSUE TITLE
first_byte_error timeout error not appearing anymore

### ISSUE THREAD

**Issue by fgsch** [varnishcache/varnish-cache#2185]
In rev f9f6b2a4457dd96bcdb7983fc6377d540cc6281a, RxStuff() was changed to also receive the beresp headers. Unfortunately a side effect of this change is that the error message for first_byte_timeout timeout got lost. 

In VSL, you have now:

```
**** v1    1.6 vsl|       1002 FetchError      b HTC status 3
```

Whether before you got:

```
**** v1    2.3 vsl|       1002 FetchError      b http first read error: EOF
```

The `HTC status 3` error corresponds to `HTC_S_IDLE`.

Test case diff:

```
diff --git a/bin/varnishtest/tests/b00023.vtc b/bin/varnishtest/tests/b00023.vtc
index 7685f66..f279029 100644
--- a/bin/varnishtest/tests/b00023.vtc
+++ b/bin/varnishtest/tests/b00023.vtc
@@ -11,12 +11,17 @@ server s1 {
 varnish v1 -vcl+backend {} -start
 varnish v1 -cliok "param.set first_byte_timeout 1"
 
+logexpect l1 -v v1 {
+       expect * 1002   FetchError      "http first read error: EOF"
+} -start
+
 client c1 {
        txreq
        rxresp
        expect resp.status == 503
 } -run
 
+logexpect l1 -wait
 
 server s1 {
        rxreq
```

**Comment by bsdphk** [comment]
It's not obvious to me what you want us to do here ?

**Comment by fgsch** [comment]
At the very least ensure the error is clear and corresponds to the issue at hand.
Reporting on HTC_S_IDLE when the error is related to the first byte timeout is misleading.

**Comment by fgsch** [comment]
The error is now:

```
FetchError      b HTC idle (3)
```
