### ISSUE TITLE
vsm_free stat is never incremented

### ISSUE THREAD

**Issue by ehocdet** [varnishcache/varnish-cache#2187]
vsm_free stat is never incremented.
detected with varnish 4.1

$ varnishstat -n cache -1 -f "MAIN.vsm_*" 
MAIN.vsm_free     18446744071652838288          .   Free VSM space
MAIN.vsm_used        137578048          .   Used VSM space
MAIN.vsm_cooling             0          .   Cooling VSM space
MAIN.vsm_overflow            0          .   Overflow VSM space
MAIN.vsm_overflowed            0         0.00 Overflowed VSM space

**Comment by fgsch** [comment]
Fixed in b8dec3334e739a07a22dcbeb39aafcd45ed15fb8.

**Comment by hermunn** [comment]
Backport review: Backported (1978ebff506439) in the corresponding Pull Request.
