### ISSUE TITLE
varnishncsa: The %r formatter is NOT equivalent to "%m http://%{Host}i%U%q %H"

### ISSUE THREAD

**Issue by opa25000** [varnishcache/varnish-cache#2190]
## Expected Behavior
The %r formatter is equivalent to "%m http://%{Host}i%U%q %H"

## Current Behavior
The %r formatter is NOT equivalent to "%m http://%{Host}i%U%q %H" 
%{Host}i has the wrong value. pls. see steps to reproduce

## Steps to Reproduce (for bugs)
root@test-cc-01:~# varnishncsa -b -c -F '%r %{Host}i'
GET http://orlb03vip.t-online.de/telekom/wwtv_live_abr.isml/Manifest HTTP/1.0 orlb03vip.t-online.de
GET http://test-cc-01--svc41.main.tx.t-online.de/telekom/wwtv_live_abr.isml/Manifest HTTP/1.0 orlb03vip.t-online.de

## Your Environment
* Version used: 4.1.4
* Operating System and version: Ubunut 14.04 LTS

**Comment by fgsch** [comment]
Are you sure you are not changing the Host header in your VCL?

**Comment by opa25000** [comment]
I have todo this 

sub vcl_recv {
  if (req.http.Host ~ "svc41.*.t-online.de") {
    set req.http.host = "orlb03vip.t-online.de" ;
    set req.backend_hint = 35x;
    return (hash);
  }

to have the right host header for the backend request.

For my understanding changing req.http.host should not affect this behavior:  
Like the documentation: The %r formatter is equivalent to "%m http://%{Host}i%U%q %H"

**Comment by fgsch** [comment]
The %r and %{Host}i formatters works differently. 

For %r, the Host header is only expanded once. For %{Host}i the last one wins.
If you set the Host header inside VCL, %r will contain the original Host header while %{Host}i will contain the last occurrence.

I will amend the documentation. It's too late to change the code now without breaking existing installations.

**Comment by opa25000** [comment]
I am very disappointed, I have trusted the documentation and built on it that I can trust it.

**Comment by Dridi** [comment]
You don't need to be disappointed because the default configuration doesn't do what you want. You can still get the original host if you store it in a dedicated header, or log it, and then tweak your `varnishncsa` format to get the desired output.

**Comment by hermunn** [comment]
Backport review: Docfix 13db0ab backported as 5995222461.
