### ISSUE TITLE
systemd fails to parse LimitMEMLOCK value of "82000"

### ISSUE THREAD

**Issue by looppair** [varnishcache/varnish-cache#2193]
## Current Behavior

The following message appears in `journalctl` when systemd is reading the varnish service definition:

> systemd[1]: [/usr/lib/systemd/system/varnish.service:20] Failed to parse resource value, ignoring: 82000

The actual value:

```
# systemctl show varnish | grep LimitMEMLOCK
LimitMEMLOCK=65536
```

## Possible Solution

I thought the problem was the integer value and that it could be fixed by setting the value to `82M`. However, contrary to the [documentation](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#LimitCPU=) systemd is unable to parse *any* values other than `infinity` for this field. I even tried inserting the value `LimitMEMLOCK=65536` printed by the command above, and it still fails. So it's possible that this is actually a systemd issue, but I couldn't find any relevant bug reports.

## Steps to Reproduce (for bugs)

1. Install varnish: `yum install varnish`

Optionally run `systemctl daemon-reload` to see the message again.

## Context

The relevant configuration line: `LimitMEMLOCK=82000`

## Your Environment

* Version used: varnish-4.0.3 revision b8c4a34
* Operating System and version: CentOS 7.3.1611
* systemd version: 219

`ulimit -l 82000` works fine on the relevant machine.

**Comment by Dridi** [comment]
Hello, I'm closing this ticket but please reopen a new one in the pkg-varnish-cache repository where we deal with packaging.

**Comment by daghf** [comment]
Hi

Could you please file this issue in https://github.com/varnishcache/pkg-varnish-cache ?

**Comment by fgsch** [comment]
Moved to https://github.com/varnishcache/pkg-varnish-cache/issues/60

**Comment by hermunn** [comment]
Backport review: Moved, nothing to backport
