### ISSUE TITLE
unhandled SIGPIPE

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2203]
varnish dying seconds after enabling production traffic

```
Feb  2 09:45:09 localhost varnishd[52275]: [ID 702911 local0.info] Child (52347) said Child starts
Feb  2 09:56:03 localhost varnishd[52275]: [ID 702911 local0.error] Child (52347) died signal=13
Feb  2 09:56:03 localhost varnishd[52275]: [ID 702911 local0.info] Child (90479) said Security: Privilege proc_setid missing, will not change uid/gid
Feb  2 09:56:03 localhost varnishd[52275]: [ID 702911 local0.info] Child (90479) said Child starts
```

* varnishd (varnish-trunk revision 7347e93)
* SunOS 5.11 joyent_20160512T071413Z

**Comment by nigoroll** [comment]
Just saw exactly the same thing again when updating to 2c07886

**Comment by nigoroll** [comment]
completely different system (linux instead of smartos), much higher load, happened right after hitting varnish master with almost full traffic (1e3 r/s)
```
Error: Child (32) died signal=13
Debug: Child cleanup complete
Debug: Child (9664) Started
Info: Child (9664) said Child starts
```

**Comment by nigoroll** [comment]
hypothesis: with 71d30eeaede2b51618aff211b45e2bf47db705f8 we started to ignore `SIGPIPE` only in the master process, but IIUC our `writev` or whatever on a _socket(2)_ may trigger the signal. From linux _socket(2)_:
> A SIGPIPE signal is raised if a process sends or receives on a broken stream;  this causes  naive  processes,  which  do not handle the signal, to exit.

**Comment by nigoroll** [comment]
just to confirm: On the system where I could trigger this with a simple restart, the issue did not surface any more

**Comment by hermunn** [comment]
Backport review: This is in the new reworked startup code, so no backport will happen unless we see this in 4.1.
