### ISSUE TITLE
Varnish + MariaDB + Swap = 1GB in Disk Read!

### ISSUE THREAD

**Issue by ogulcanozugenc** [varnishcache/varnish-cache#2204]
## Expected Behavior

I looked at other requests but couldn't find a problem like mine.

## Current Behavior

When using Varnish, It uses %20 of 512MB of my RAM on its own. While using %20 of the RAM, it holds and not release %20 more by using the Buff/Cache. In total it uses %40 of my little 512MB RAM. So it is inevitable not to swap. I am not afraid of swap because my sistem is in SSD Cloud VPS. But with Varnish + MariaDB going to swap crashes the system by using 1GB of disk read per second. Thats why I stopped using Varnish and the system is now OK. It goes to swap sometimes and no disk read of 1GB anymore. So I couldn't find any solution. For a month I looked to optimize MariaDB, Apache, NGINX and no help. 
By the way Varnish Cache locates in SSD not RAM. I set it up at 512MB (I tried it on RAM also, no change).
## Possible Solution

Possible solution is to solve the problem of Varnish crashing when going into swap.

## Steps to Reproduce (for bugs)

1. This is server wide problem. Can't be observed outside.

## Context

This affected me in crash of my server. I stopped using Varnish and server is working flawlessly right now. I can give you root access after taking a snapshot if this helps you and your application to improve. Varnish is still installed but not activated. It will take only 5 minutes to go online with Varnish again.

## Your Environment

* Version used: 4
* Operating System and version: CentOS 7.3
Installed Applications: Vesta Control Panel, Transmission Torrent Client, NGINX, MariaDB, Apache, Exim, Dovecot, Roundcube, NetData Monitoring, OwnCloud and dependencies of these.

**Comment by fgsch** [comment]
Most likely you will need to configure Varnish to cap the size of the cache. 
See https://varnish-cache.org/docs/4.0/users-guide/storage-backends.html.

For help, use one of the existing channels for support. See https://varnish-cache.org/support/index.html.
Don't forget to provide the full version, parameters and configuration used and the error you are getting.

**Comment by hermunn** [comment]
Backport review: Nothing commited, nothing to backport.
