### ISSUE TITLE
Strange bug when I set client.ip with another string

### ISSUE THREAD

**Issue by Rod-Gomes** [varnishcache/varnish-cache#2205]
When I set `set req.http.someting` with `client.ip + ", " + server.ip` I receive this error: `Name or service not known`.

## Expected Behavior
Work without any errors.

## Current Behavior
Generates the following error:
```
Name or service not known
(Sorry if that error message is gibberish.)
('/etc/varnish/lib/ip.vcl' Line 77 Pos 68)
set req.http.X-Forwarded-For = client.ip + ", " + server.ip;
-------------------------------------------------------------------####-------------
Running VCC-compiler failed, exited with 2
```

## Possible Solution
`set req.http.X-Forwarded-For = "" + client.ip + ", " + server.ip;`

Solves the problem. lol

## Steps to Reproduce (for bugs)
`set req.http.X-Forwarded-For = client.ip + ", " + server.ip;`

## Context
I'm trying to set the header X-Forwarded-For correctly.

## Your Environment

* Version used: varnishd (varnish-4.1.4 revision 4529ff7)
* Operating System and version: CentOS Linux release 7.3.1611 (Core)

**Comment by hermunn** [comment]
Backport review: This code has changed a lot from 4.1, and there is a workaround in VCL. No backport will happen.
