### ISSUE TITLE
Backend fetch errors are not reflected in varnishstat

### ISSUE THREAD

**Issue by anchann** [varnishcache/varnish-cache#2212]
My backend intermittently drops requests, which result in varnish sending 503s to the client. In `varnishlog`, the request has `RespStatus 503` and `RespReason "Backend fetch failed"`, with the corresponding backend response having a `FetchError "HTC status -1"`. Yet in `varnishstat` these requests do not seem to be logged as failures of any sort: `fetch_eof` is 0, `fetch_failed` is 0, `backend_fail` is 0. 

## Expected Behavior
I expected to see the number of dropped backend requests in some metric in `varnishstat`. At the very least, I would have liked to see the number of 503s, or backend requests with `FetchError`.

## Current Behavior
It seems that currently there are fields in the `varnishstat` response that are meant to contain the data that I am looking for, but they all have value 0, while querying `varnishlog` shows that there are requests that should match these failure criteria.

## Context
I have a backend service running on spray (predecessor of akka-http), and it's dropping requests. The root cause has nothing to do with varnish, but `varnishstat` should be useful for monitoring the number of errors, and currently it is not.

## Your Environment
* Version used: varnish_5.0.0-1_amd64.deb
* Operating System and version: Ubuntu 14

**Comment by fgsch** [comment]
Fixed in master and 4.1.5 (commit e96889983d14abca14894b66729e8b6077206f89).

It will be part of the next release in the 5.x series, scheduled for March.
