### ISSUE TITLE
Discarded VCLs may be kept warm (via the busy state)

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2228]
I came across a detailed response on a support channel explaining why this may happen so I figured I could lazily edit-paste it here to ensure awareness and enable persistent discussion (I don't keep IRC logs, others may).

> Unfortunately this is nothing new. In varnish 4.0 and earlier you could get into a similar situation where you would discard a VCL but it wouldn't go away because it's reference counter wouldn't be zero.
>
> Starting with Varnish 4.1, if the VCL is referenced by workers, it cannot cool down and instead of appearing as warm it will be busy. It's basically on its way to cooling down but waiting for inbound references to be gone.
>
> The reason why references are still around is because workers will only release them at the beginning of a transaction. So when they get parked, they do with a reference to the VCL that was active for the last task they ran. And if a VCL switch happens around a big traffic spike, you can end up with workers holding on to VCLs for a long time when the traffic becomes quiet.
>
> For testing purposes, it is possible to force a rapid release:
>
> ```
> varnishadm param.set debug +vclrel
> ```
>
> As the name suggests it is not intended for production, and it is otherwise too late for workers that are already waiting while holding a reference. [Deferred VCL release] is an optimization to reduce contention on VCL reference counting.
>
> As I said, this is nothing new: it used to prevent a discarded VCL to be actually removed. However this defeats the goal of VCL temperature, since a busy VCL cannot reduce its footprint and there has been discussions but no plan yet on how to mitigate this situation.

I have already pondered this problem in the past, but I'm not sure how to solve this. One solution could be an expiry-like thread dedicated to releasing references in the background, or let thread pools do it somehow as part of there housekeeping. I haven't tried anything so far.

**Comment by bsdphk** [comment]
I thought I solved this long time ago:  Workers should release their VCL when they have been idle for 60 seconds.

See cache/cache_wrk.c around line 350:

```
                        pp->nidle++;
                        do {
                                i = Lck_CondWait(&wrk->cond, &pp->mtx,
                                    wrk->vcl == NULL ?  0 : wrk->lastused+60.);
                                if (i == ETIMEDOUT)
                                        VCL_Rel(&wrk->vcl);
                        } while (wrk->task.func == NULL);

```

**Comment by Dridi** [comment]
I had no idea, I've seen Varnish hang to discarded VCLs forever! Assigning to myself, I will have a look and try to figure what's keeping references around.

**Comment by Dridi** [comment]
After a quick look, I'm wondering whether we might be keeping references around because we don't check the result of the the cond wait.

I was thinking about doing this instead:

```diff
diff --git i/bin/varnishd/cache/cache_wrk.c w/bin/varnishd/cache/cache_wrk.c
index f3dfc3b..efefb51 100644
--- i/bin/varnishd/cache/cache_wrk.c
+++ w/bin/varnishd/cache/cache_wrk.c
@@ -352,7 +352,8 @@ Pool_Work_Thread(struct pool *pp, struct worker *wrk)
                        do {
                                i = Lck_CondWait(&wrk->cond, &pp->mtx,
                                    wrk->vcl == NULL ?  0 : wrk->lastused+60.);
-                               if (i == ETIMEDOUT)
+                               assert(i == 0 || i == ETIMEDOUT);
+                               if (wrk->vcl != NULL)
                                        VCL_Rel(&wrk->vcl);
                        } while (wrk->task.func == NULL);
                        tpx = wrk->task;
```

**Comment by Dridi** [comment]
It appears that most calls to `Lck_CondWait` aren't checked after a quick grep, so maybe leaving the assertion out would be preferable.

**Comment by Dridi** [comment]
OK, taking a step back, I think the reason for not releasing is when we break out of the loop for the `pool_kiss_of_death`. This is not a timeout, it looks like there's a task ahead of the worker but instead it terminates.

Proposed fix, take two:

```diff
diff --git i/bin/varnishd/cache/cache_wrk.c w/bin/varnishd/cache/cache_wrk.c
index f3dfc3b..d760416 100644
--- i/bin/varnishd/cache/cache_wrk.c
+++ w/bin/varnishd/cache/cache_wrk.c
@@ -378,6 +378,8 @@ Pool_Work_Thread(struct pool *pp, struct worker *wrk)
                wrk->seen_methods = 0;
        }
        wrk->pool = NULL;
+       if (wrk->vcl != NULL)
+               VCL_Rel(&wrk->vcl);
 }
 
 /*--------------------------------------------------------------------
```

**Comment by Dridi** [comment]
OOOOK, taking another step back, it should be cleaned up regardless after `Pool_Work_Thread` returns.

**Comment by bsdphk** [comment]
Make the VCL_Rel() conditional on task.func == NULL instead ?

**Comment by Dridi** [comment]
Not sure that would work, because this condition may be checked several times in the loop. You'd still need to check that `wrk->vcl != NULL` (or relax `VCL_Rel`). I was catching up with support activity while looking at this but so far I haven't found anything conclusive.

Currently I'm trying to assess (waiting for affected user feedback) whether VCLs can actually be stuck in the busy state (it doesn't apply to discarded VCLs only) and currently `vcl.list` doesn't tell anything useful, so maybe introducing a debug command would. Maybe Ref/Rel operations aren't always balanced, I will have a look there too (it applies to 4.1+).

**Comment by Dridi** [comment]
Timing this issue out until I hear about this on the other support channel.

**Comment by chap-dr** [comment]
Hi, Just wanted to also poke my head in here (as well as with my support case) and say that we're seeing this issue on our four production varnish instanses. 

We've had up to seven vcl's in a auto/busy state which does nothing great for our production. Only fix we know of as of yet is to pull each varnish out of LB and restart varnish entirely. 

If nothing else a "on the fly" command to drop the vcl's by hand would be great. 

Response on ticket was "yes, we are aware of the issue, with no eta on a fix"
