### ISSUE TITLE
[FreeBSD Accept Filters] Support "dataready" Accept Filter when listening for HTTP/2 or PROXY Protocol

### ISSUE THREAD

**Issue by josh4trunks** [varnishcache/varnish-cache#2231]
To the best of my knowledge the below statements are correct but I do not fully understand all the technologies mentioned. Please correct me if any of my statements/assumptions are wrong.
Thanks!

## Current Behavior
Currently, if you are on FreeBSD, and are listening for either HTTP/2 or PROXY Protocol connections, httpready will not be beneficial.

From searching the code for **httpready** and **dataready** I believe Varnish only works with 'httpready'. From looking at FreeBSD's **accf_http** code, it only supports standard HTTP/1.0 or HTTP/1.1.

## Possible Solutions
* Support FreeBSD's **dataready** accept filter when listening for HTTP/2 or PROXY Protocol connections
* Update FreeBSD's **httpready** accept filter to support HTTP/2
* Create a new FreeBSD accept filter to support Proxy Protocol

## Relevant Links
https://github.com/varnishcache/varnish-cache/blob/6db7d750d1340f7c28d1102d2d24ac1a3f290a38/lib/libvarnish/vtcp.c#L147-L160

https://www.freebsd.org/cgi/man.cgi?query=accf_http
https://github.com/freebsd/freebsd/blob/386ddae58459341ec567604707805814a2128a57/sys/netinet/accf_http.c

https://www.freebsd.org/cgi/man.cgi?query=accf_data
https://github.com/freebsd/freebsd/blob/386ddae58459341ec567604707805814a2128a57/sys/netinet/accf_data.c

**Comment by fgsch** [comment]
@bsdphk adding dataready should be fairly simple. comments?

**Comment by fgsch** [comment]
@bsdphk I'm happy to work on this but first, do you have any input?

**Comment by josh4trunks** [comment]
Any update on this? If you know how to simply add "dataready" i can try patching my source and testing if it works.

**Comment by fgsch** [comment]
@josh4trunks sorry for the delay. I think going for dataready is probably the best option atm.
If you have the time (and inclination) you can open a PR for review.

**Comment by fgsch** [comment]
Timed-out.
