### ISSUE TITLE
how to keep the data cahced in file reuseable after reloading?

### ISSUE THREAD

**Issue by GhostZCH** [varnishcache/varnish-cache#2236]
Hi.
       We want to use varnish handle our cache problems for it speed and stable. It works very well except need to re-cache data after reloading. As we have more then 200G data need to be cached in varnish, every re-cache process will be costly.

I find `persistent` option which saided not be well supported in varnish's docments. So i want to ask is there any other way to do so(samething like `persistent``)?

Thank you!

**Comment by gquintard** [comment]
Please use the proper help channels: **http://www.varnish-cache.org/support/#**

Github is reserved for bugs.

**Comment by hermunn** [comment]
Backport review: Not a bug, nothing to backport.
