### ISSUE TITLE
Varnishlog crash

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2237]
On v-c.org running "varnishlog":

    -   Debug          "HP {28, "content-length:", ""} <Content-Length: 4101>"
    -   Timestamp      Resp: 1488358376.022496 0.000389 0.000229
    -   ReqAcct        0 0 0 0 0 0
    -   End            
    
    Assert error in vslc_vtx_next(), vsl_dispatch.c line 285:
      Condition(c->offset <= c->vtx->len) not true.
    Abort (core dumped)

Have coredump:

    (gdb) where
    #0  0x00000008015fe55a in thr_kill () from /lib/libc.so.7
    #1  0x00000008015fe52b in raise () from /lib/libc.so.7
    #2  0x00000008015fe499 in abort () from /lib/libc.so.7
    #3  0x000000080082e45c in VAS_Fail_default (func=0x800857dca "vslc_vtx_next", file=0x800857ac2 "vsl_dispatch.c", line=285, 
        cond=0x800857e44 "c->offset <= c->vtx->len", kind=VAS_ASSERT) at ../libvarnish/vas.c:69
    #4  0x0000000800841fa1 in vslc_vtx_next (cursor=0x8020445a8) at vsl_dispatch.c:285
    #5  0x0000000800841250 in vtx_scan (vslq=0x802026000, vtx=0x802044400) at vsl_dispatch.c:855
    #6  0x0000000800840292 in vslq_next (vslq=0x802026000) at vsl_dispatch.c:1274
    #7  0x000000080083f945 in VSLQ_Dispatch (vslq=0x802026000, func=0x800850510 <vut_dispatch>, priv=0x0) at vsl_dispatch.c:1324
    #8  0x00000008008503f9 in VUT_Main () at vut.c:398
    #9  0x000000000040132d in main (argc=1, argv=0x7fffffffebf8) at varnishlog.c:172
    [...]
    (gdb) up
    #4  0x0000000800841fa1 in vslc_vtx_next (cursor=0x8020445a8) at vsl_dispatch.c:285
    285                             assert(c->offset <= c->vtx->len);
    (gdb) print *c
    $1 = {magic = 1959154239, cursor = {rec = {ptr = 0x80201d090, priv = 0}, priv_tbl = 0x800a61228, priv_data = 0x8020445a0}, 
      vtx = 0x802044400, synth = 0x0, chunk = 0x80203f000, chunkstart = 35, offset = 4170}
    (gdb)print *c->vtx
    $2 = {key = {vxid = 164124, entry = {rbe_left = 0x802034800, rbe_right = 0x0, rbe_parent = 0x802044600, rbe_color = 0}}, 
      magic = 2898402569, list_child = {vtqe_next = 0x802033e00, vtqe_prev = 0x802026068}, list_vtx = {vtqe_next = 0x802033e00, 
        vtqe_prev = 0x802044c40}, t_start = 6044658.8895928441, flags = 1, type = VSL_t_sess, reason = VSL_r_unknown, parent = 0x0, child = {
        vtqh_first = 0x0, vtqh_last = 0x802044470}, n_child = 0, n_childready = 0, n_descend = 0, synth = {vtqh_first = 0x80201d070, 
        vtqh_last = 0x80201d078}, shmchunks = 0x8020444a0, shmchunks_free = {vtqh_first = 0x0, vtqh_last = 0x802044578}, chunks = {
        vtqh_first = 0x802044530, vtqh_last = 0x80203f038}, len = 1087, c = {magic = 1959154239, cursor = {rec = {ptr = 0x80201d090, 
            priv = 0}, priv_tbl = 0x800a61228, priv_data = 0x8020445a0}, vtx = 0x802044400, synth = 0x0, chunk = 0x80203f000, chunkstart = 35, 
        offset = 4170}}
    (gdb)

**Comment by bsdphk** [comment]
Seems like "varnistop -i RxProto" just did the same thing:

    (gdb) where
    #0  0x000000080185e55a in thr_kill () from /lib/libc.so.7
    #1  0x000000080185e52b in raise () from /lib/libc.so.7
    #2  0x000000080185e499 in abort () from /lib/libc.so.7
    #3  0x000000080083245c in VAS_Fail_default (func=0x80085bdca "vslc_vtx_next",
        file=0x80085bac2 "vsl_dispatch.c", line=285,
        cond=0x80085be44 "c->offset <= c->vtx->len", kind=VAS_ASSERT)
        at ../libvarnish/vas.c:69
    #4  0x0000000800845fa1 in vslc_vtx_next (cursor=0x80226e5a8)
        at vsl_dispatch.c:285
    #5  0x0000000800845250 in vtx_scan (vslq=0x802226000, vtx=0x80226e400)
        at vsl_dispatch.c:855
    #6  0x0000000800844292 in vslq_next (vslq=0x802226000) at vsl_dispatch.c:1274
    #7  0x0000000800843945 in VSLQ_Dispatch (vslq=0x802226000,
        func=0x800854510 <vut_dispatch>, priv=0x0) at vsl_dispatch.c:1324
    #8  0x00000008008543f9 in VUT_Main () at vut.c:398
    #9  0x0000000000401ae0 in main (argc=3, argv=0x7fffffffebe0)
        at varnishtop.c:374
    (gdb) up
    #1  0x000000080185e52b in raise () from /lib/libc.so.7
    (gdb) up
    #2  0x000000080185e499 in abort () from /lib/libc.so.7
    (gdb) up
    #3  0x000000080083245c in VAS_Fail_default (func=0x80085bdca "vslc_vtx_next",
        file=0x80085bac2 "vsl_dispatch.c", line=285,
        cond=0x80085be44 "c->offset <= c->vtx->len", kind=VAS_ASSERT)
        at ../libvarnish/vas.c:69
    69              abort();
    Current language:  auto; currently minimal
    (gdb) up
    #4  0x0000000800845fa1 in vslc_vtx_next (cursor=0x80226e5a8)
        at vsl_dispatch.c:285
    285                             assert(c->offset <= c->vtx->len);
    (gdb) print *c
    $1 = {magic = 1959154239, cursor = {rec = {ptr = 0x80221d250, priv = 0},
        priv_tbl = 0x800a65228, priv_data = 0x80226e5a0}, vtx = 0x80226e400,
      synth = 0x0, chunk = 0x802240000, chunkstart = 35, offset = 4170}
    (gdb) print *c->vtx
    $2 = {key = {vxid = 164124, entry = {rbe_left = 0x80223e400, rbe_right = 0x0,
          rbe_parent = 0x80226e600, rbe_color = 0}}, magic = 2898402569,
      list_child = {vtqe_next = 0x80223e200, vtqe_prev = 0x802226068}, list_vtx = {
        vtqe_next = 0x80223e200, vtqe_prev = 0x80226ec40},
      t_start = 6044658.8896487374, flags = 1, type = VSL_t_sess,
      reason = VSL_r_unknown, parent = 0x0, child = {vtqh_first = 0x0,
        vtqh_last = 0x80226e470}, n_child = 0, n_childready = 0, n_descend = 0,
      synth = {vtqh_first = 0x80221d230, vtqh_last = 0x80221d238},
      shmchunks = 0x80226e4a0, shmchunks_free = {vtqh_first = 0x0,
        vtqh_last = 0x80226e578}, chunks = {vtqh_first = 0x80226e530,
        vtqh_last = 0x802240038}, len = 1087, c = {magic = 1959154239, cursor = {
          rec = {ptr = 0x80221d250, priv = 0}, priv_tbl = 0x800a65228,
          priv_data = 0x80226e5a0}, vtx = 0x80226e400, synth = 0x0,
        chunk = 0x802240000, chunkstart = 35, offset = 4170}}
    (gdb)

**Comment by bsdphk** [comment]
Hmm, this may actually be a bug on the varnishd site.  Taking Martin of until I figure this out.

**Comment by bsdphk** [comment]
I'm closing this, it seems to have been caused by VSL segment corruption on the varnishd side.

**Comment by sonicseaweed** [comment]
Is there a workaround for this or any solution on the way?
