### ISSUE TITLE
Set user agent to backend checks

### ISSUE THREAD

**Issue by janisz** [varnishcache/varnish-cache#2242]
It will be nice if Varnish health checks identify themselves with user agent set to _"Varnish Cache Health Check"_ just like [Consul health checks](https://github.com/hashicorp/consul/commit/ce93fdd76bcac6d0e154f5c6be189990f74d258b). It will make checks easier to distinguish in service access logs.

## Expected Behavior
```
User-Agent: Varnish Cache Health Check
```

## Current Behavior
No user agent header

## Context
I want to easily distinguish varnish health check from health check from other services and regular traffic.

**Comment by gquintard** [comment]
This issue tracker is not for feature requests, plus this is already possible: http://www.varnish-cache.org/docs/4.1/reference/vcl.html#probes

Please use the proper channels: http://www.varnish-cache.org/support/

**Comment by hermunn** [comment]
Backport review: Not a bug, nothing to backport
