### ISSUE TITLE
[trunk]Varnish doesn't start, if use vmod (vmod_cache dir was permission denied)

### ISSUE THREAD

**Issue by xcir** [varnishcache/varnish-cache#2245]
## Expected Behavior
Varnish start fine.

## Current Behavior
VCL
```
vcl 4.0;
import std;

backend default {.host = "127.0.0.1";.port = "81";}
sub vcl_recv{
  return(hash);
}
```

Error message
```
Debug: Platform: Linux,4.4.0-64-generic,x86_64,-junix,-smalloc,-smalloc,-hcritbit
Debug: Child (11454) Started
CLI result = 300
Error: Child (11454) Pushing vcls failed:
VCL "boot" Failed initialization
Message:
        Creating copy of vmod std: Permission denied

Debug: Stopping Child
Info: Child (11454) ended
Info: Child (11454) said Child starts
Info: Child (11454) said Child dies
Debug: Child cleanup complete
```

vmod_cache info
```
# ls -ltahd vmod_cache/
drwxr-xr-x 2 varnish varnish 4.0K Mar  4 17:12 vmod_cache/
```

## Possible Solution
vmod_cachedir owner is master process(varnish)., and permission is 755.
But, vmod backup copy function(vrt_vmod_backup_copy) is called by child process(vcache).
Child process is not have a write permission for vmod_cache.

It might be a good idea to set permissions to 775.

## Steps to Reproduce (for bugs)
See the Current Behavior above.

## Context
Can't use vmod.

## Your Environment
Version used: hitch1.4.4 + varnish-trunk revision 0ce6565
Operating System and version: Ubuntu 16.04.2 LTS (4.4.0-64-generic)

**Comment by hermunn** [comment]
Backport review: The backup mechanism is not in 4.1, there is nothing to backport.
