### ISSUE TITLE
"logexpect -wait" doesn't fail

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2249]
I just noticed that, see 3a27f6f.

Assigning to myself for later investigation unless someone's eager to fix it first :)

**Comment by Dridi** [comment]
OK, trivial fix, I will take care of it and other things I have found later today.

**Comment by hermunn** [comment]
About backporting: Since this is a `varnishtest` fix, I will leave it to @Dridi to decide if it is worth his time to bring this to 4.1. It is not affecting `varnishd`, so I will probably not take the time to form an opinion on this.

**Comment by Dridi** [comment]
Let's say that if a simple cherry-pick is not enough we don't need it in 4.1, I will give it a quick try today.

**Comment by Dridi** [comment]
Doesn't apply, not back-porting.
