### ISSUE TITLE
varnishapi.pc and varnishconfdir

### ISSUE THREAD

**Issue by rezan** [varnishcache/varnish-cache#2251]
This is more of a discussion right now, but I am proposing adding 2 new entries to `varnishapi.pc`:

```
sysconfdir=@sysconfdir@
varnishconfdir=@varnishconfdir@
```

Basically, im running into a situation where I need to know where the `vcl_dir` is (or `vcl_path`). The problem is that this path is prefixed when you install from source, but unprefixed when you install from package. In both cases, you are left guessing where is the actual location. Im thinking this info should be in the `varnishapi.pc`. Thoughts? Is there a better way to find the `varnishconfdir` after Varnish has been installed on a system?

**Comment by rezan** [comment]
Im now thinking to just query `varnishadm` directly and then fallback to `varnishconfdir` detection. However, this problem is 2 parts. We want to drop vcls into vcl_dir, simple enough. We also want to compile a VMOD which default loads configuration from vcl_dir. For the latter, we need some kind of auto config var.

**Comment by Dridi** [comment]
@rezan we've already had this discussion for 5.0 and as a result #2058 was submitted (but not merged as is). You already have a blessed directory for packaging where you can install VCL files and expect them to be readily available unless the user changes their `vcl_path`.

With pkg-config that would be `${pkgdatadir}/vcl/`.

It is documented in the changelog for 5.0 as "New system wide VCL directory: `/usr/share/varnish/vcl/`". There's maybe room for improvement in the documentation, but it's mentioned in varnishd(1) too:

http://varnish.org/docs/5.0/reference/varnishd.html#vcl-path

**Comment by rezan** [comment]
ok, that worked too. I did this, since it matched the [Makefile.am in varnishd](https://github.com/varnishcache/varnish-cache/blob/e5b99ec618d95cdd11160ccfbdc6aa408c5333f4/bin/varnishd/Makefile.am#L149):

```
${datarootdir}/varnish/vcl
```

Still have a need to put a VMOD config file into `varnishconfdir`. The idea here is all the VMOD conf file sits next to the Varnish conf files and VCL. So this path would need to be known at compile time for the VMOD. Any thoughts on this one?

**Comment by Dridi** [comment]
Sorry, I was too quick to close this. The reason why the Makefile doesn't use pkgdatadir is because it wasn't already there. I'd still recommend to take it from pkg-config (it's its purpose) and nothing prevents us from feeding automake a pkgdatadir variable in the varnish source tree.

Regarding a varnishconfdir, do you really need to drop your config there? Nothing prevents your own package to have its own directory in /etc. Otherwise I would call it pkgconfdir or pkgsysconfdir to be consistent.

**Comment by rezan** [comment]
Ya, right now, we are using plain `sysconfdir` with no `prefix`, aka `/etc`. The feedback we got was that this configuration file should be next to all the other bits in pieces in `/etc/varnish` or where ever this new `pkgconfdir` tells us. I think that is a valid design choice.

Given that this wont exist out in the wild anytime soon, assuming we do this, this isn't too important, but I think it would be useful in future scenarios.

Also, I have this tiny gut feeling that there is a bit of magic around because it will be unprefixed all the way thru the auto conf build, up until the end when it does the replacement in the conf files and then the prefix shows up. Hopefully I am wrong here, I just remember reading that and possibly seeing that in practice.

**Comment by rezan** [comment]
@Dridi Also, on your commit above (https://github.com/varnishcache/varnish-cache/commit/5c8b790fb18130dcdb532913d34bf2343d43ed1b), you are including `/vcl` inside of `pkgdatadir`. This will break with 4.x since there `pkgdatadir` does not have the `/vcl` suffix and nor does the pkgconfig.

**Comment by rezan** [comment]
Side question, if we define a custom variable in `varnishapi.pc` like `pkgdatadir`, how can that get used in autoconf?

**Comment by Dridi** [comment]
> Hopefully I am wrong here, I just remember reading that and possibly seeing that in practice.

See this short `autoconf` example:

```
$ cat configure.ac 
AC_INIT([foo])
AC_CONFIG_SRCDIR([configure.ac])
echo prefix: ${prefix}
echo sysconfdir: ${sysconfdir}
$ autoconf
$ ./configure
prefix: NONE
sysconfdir: ${prefix}/etc
$ ./configure --prefix=/opt
prefix: /opt
sysconfdir: ${prefix}/etc
$ ./configure --prefix=/usr
configure: loading site script /usr/share/config.site
prefix: /usr
sysconfdir: /etc
```

Also if you use the autoconf macros introduced in 5.0 your VMOD project will inherit Varnish's prefix by default (otherwise it will comply with `--prefix`). The default prefix in general is `/usr/local` with `autoconf` and the `/usr` case is handled correctly, so really there's no big deal about that.

>  This will break with 4.x

5c8b790 does not break 4.x, it was something introduced with 5.0 as I pointed out earlier.

This commit however breaks the assumption that `dirname ${pkgdatadir}` is `varnish`. So a downstream distribution of varnish under a different name won't break if it rebases itself on 5.1, wink wink ;)

**Comment by rezan** [comment]
> $ ./configure --prefix=/usr

Interesting, this might be what I was confused about. So autoconf treats that prefix special?

I guess my problem was that since we don't load `${sysconfdir}` or the actual `${pkgconfdir}` from the pkgconfig, I get this in a VMOD when I run plain `./configure`:

```
> cat test.in
prefix="@prefix@"
sysconfdir="@sysconfdir@"
```

```
> cat test
prefix="/usr"
sysconfdir="${prefix}/etc"
```

I get the same results when I do `./configure --prefix=/usr`. The difference here is that im using an autoconf `.in` file to capture these variables. It seems like the behavior is very different.

> This will break with 4.x

Well, the issue is that `${pkgdatadir}` in the varnish source will _now_ have the `/vcl` suffix. Ex:

```
/opt/varnish/share/varnish/vcl
```

If building a VMOD from pkgconfig, it does not have the `/vcl` at the end:

```
/opt/varnish/share/varnish
```

https://github.com/varnishcache/varnish-cache/blob/4.1/varnishapi.pc.in#L10

The definitions are no longer uniform. It seems that `${pkgdatadir}` has always existed starting with 4.0. So I guess the issue here is that you have repurposed `${pkgdatadir}` for VCLs. It should be something like this:

```
pkgdatadir = ${datarootdir}/${PACKAGE}
vcldatadir = ${pkgdatadir}/vcl
```

> This commit however breaks the assumption that `dirname ${pkgdatadir}` is `varnish`.

Correct, `Makefile.am` used `/varnish` and `varnishapi.pc` used the proper `${PACKAGE}`. So that was a bit foobar for some use cases in 4.x.

**Comment by Dridi** [comment]
In summary, we'd introduce new pkg-config variables:

- pkgsysconfdir (for VMODs and VUTs who want to co-locate their configuration)
- vcldir (akin to vmoddir rather than datadir)

If no one objects during the bugwash I will push those changes.
