### ISSUE TITLE
Assert error in WS_Reset(), cache/cache_ws.c line 140

### ISSUE THREAD

**Issue by lifaguiar** [varnishcache/varnish-cache#2261]
Varnish panic while processing request:

Assert error in WS_Reset(), cache/cache_ws.c line 140:
  Condition(ws->r == NULL) not true.
version = varnish-5.1.0 revision 6a9cc44, vrt api = 6.0
ident = Linux,3.10.0-514.6.2.el7.x86_64,x86_64,-jnone,-smalloc,-smalloc,-hcritbit,epoll
now = 1494369.639239 (mono), 1489694472.438293 (real)
Backtrace:
  0x438537: varnishd() [0x438537]
  0x452ef2: varnishd(WS_Reset+0xf2) [0x452ef2]
  0x43a94d: varnishd(Req_Cleanup+0x17d) [0x43a94d]
  0x459a32: varnishd() [0x459a32]
  0x45a239: varnishd() [0x45a239]
  0x451479: varnishd() [0x451479]
  0x4518db: varnishd() [0x4518db]
  0x7f3782472dc5: /lib64/libpthread.so.0(+0x7dc5) [0x7f3782472dc5]
  0x7f37821a173d: /lib64/libc.so.6(clone+0x6d) [0x7f37821a173d]
thread = (cache-worker)
thr.req = 0x7f37488e2610 {
  vxid = 0, transport = HTTP/1 {
    state = HTTP1::Busy
  }
  step = R_STP_LOOKUP,
  req_body = R_BODY_INIT,
  restarts = 0, esi_level = 0,
  sp = 0x7f3750040a10 {
    fd = -1, vxid = 329056,
    t_open = 1489694433.419691,
    t_idle = 1489694433.430611,
    transport = HTTP/1 {
      state = HTTP1::Busy
    }
    client = 10.255.0.3 60982,
  },
  ws = 0x7f37488e27f8 {
    id = \"req\",
    {s, f, r, e} = {0x7f37488e45f8, +1552, +57328, +57328},
  },
  http_conn = 0x7f37488e2720 {
    fd = -1 (@0x7f3750040a28),
    doclose = NULL,
    ws = 0x7f37488e27f8 {
      [Already dumped, see above]
    },
    {rxbuf_b, rxbuf_e} = {0x7f37488e4628, 0x7f37488e4b27},
    {pipeline_b, pipeline_e} = {(nil), (nil)},
    content_length = -1,
    body_status = none,
    first_byte_timeout = 0.000000,
    between_bytes_timeout = 0.000000,
  },
  http[req] = 0x7f37488e2890 {
    ws = 0x7f37488e27f8 {
      [Already dumped, see above]
    },
    hdrs {
      \"GET\",
      \"/sc/noticias/noticia/2017/03/ampliacao-do-terminal-de-passageiros-e-principal-desafio-da-zurich-no-aeroporto-hercilio-luz-9749738.html\",
      \"HTTP/1.1\",
      \"Cookie: EDITED\",
      \"Cache-Control: no-cache\",
      \"referer: http://m.facebook.com/\",
      \"x-fb-sim-hni: 72404\",
      \"Host: dc.clicrbs.com.br\",
      \"Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\",
      \"user-agent: Mozilla/5.0 (Linux; Android 6.0.1; SM-J500M Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/56.0.2924.87 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/113.0.0.16.70;]\",
      \"x-fb-net-hni: 72404\",
      \"X-Purpose: preview\",
      \"x-fb-http-engine: Liger\",
      \"X-FB-ABSURL-DEBUG: 0\",
      \"Connection: keep-alive\",
      \"X-Forwarded-For: 10.255.0.3\",
      \"ClientIP: 10.255.0.3\",
      \"X-UA-Device: mobile-android\",
      \"X-Paywall: none\",
      \"X-Vary-Cookie: none\",
      \"X-Group: IT\",
      \"X-Backend-Found: true\",
      \"Accept-Encoding: gzip\",
    },
  },
  vmods = {
    std = {Varnish 5.1.0 6a9cc44, 6.0},
    directors = {Varnish 5.1.0 6a9cc44, 6.0},
    saintmode = {Varnish 5.1.0 6a9cc44, 6.0},
    cookie = {Varnish 5.1.0 6a9cc44, 6.0},
  },
  flags = {
  },
},
thr.busyobj = (nil) {
},

* Version used: 5.1.0
* Operating System and version: CentOS Linux release 7.3.1611 (Core)

**Comment by simonvik** [comment]
Think that this is fixed in 5.1.1 released today, had the same issue before on 5.1, 
https://github.com/varnishcache/varnish-cache/commit/7b70617fdbf0f19585ca33b19c03e9ab54fbb4ee, https://github.com/varnishcache/varnish-cache/commit/fca21c77189ce058d4185c40e0372f04708297e7 fixed it

**Comment by bsdphk** [comment]
Correct, this is why 5.1.1 was needed.

**Comment by hermunn** [comment]
Backport review: This bug arrived with 5.1.0 and was fixed shortly after, in 5.1.1.
