### ISSUE TITLE
Build varnish-5.1.1 on el6: Why python >=2.7?

### ISSUE THREAD

**Issue by ingvarha** [varnishcache/varnish-cache#2264]
According to configure.in, varnish-5.1.1 needs python version 2.7 or higher to build. It seems to build fine on el6 with python-2.6.66, so why this requirement?

## Expected Behavior
Build fine on el6

## Current Behavior
configure bails out  because python-2.7 or higher is not available

## Possible Solution
Ugly workaround: Patch configure script

## Steps to Reproduce (for bugs)
Build from source on rhel6 or a clone

## Context
I'm building packages of all varnish versions on all supported variants of fedora and rhel clones

## Your Environment
* Version used: varnish-5.1.1
* Operating System and version: Centos 6 on x86_64, latest update

**Comment by nigoroll** [comment]
see bfab0a1ffa174b8c59ac5ed2f3f38a18ee7afe61:
a29fca70f7ccc75964bcfffb8c8ab1617fcf2bba requires `subprocess.check_output` which was added with Python 2.7
At the time, I checked with @bsdphk if we should change vmodtool back to avoid use of this function, but we agreed that depending upon 2.7 should not be demanding too much.

**Comment by ingvarha** [comment]
Well, either this is never reached in my 5.1.1 rpm build on el6, or that function is available in Red Hat's python-2.6.66. When is this called?

**Comment by nigoroll** [comment]
Actually I just followed the docs saying that it got added with 2.7 - might have been earlier/backported?
It's in vmodtool

**Comment by nigoroll** [comment]
Thanks to @dridi and @denisbr for taking this one

**Comment by Dridi** [comment]
Not that I doubted @ingvarha I tried to build it on el6 and can confirm it builds just fine. The version I see however is 2.6.6-66 (works with 2.6.6-64 too) so we could lower the requirement to 2.6.6 to be on the safe side.

We can reach consensus and fix that for 5.1.2 while we have a window :)

Anyone aware of another platform shipping python 2.6? pkgs.org has become downright unusable for me.

**Comment by nigoroll** [comment]
@Dridi shouldn't we check with which version the feature was introduced? Could this be a RH specific backport?

**Comment by Dridi** [comment]
I'm not much into Python, that's why I wanted to try another unrelated platform with Python 2.6 instead. If someone savvy wants to do a thorough check, I won't argue :)

**Comment by fgsch** [comment]
Python 2.6.9 (latest official version in the 2.6 series) does not have check_output.

We can roll our own check_output if it's not available but considering 2.6.9 was released in 2013 I'd prefer if this is fixed in the package since AFAICT this is not a vanilla 2.6 and it's long outdated.

**Comment by nigoroll** [comment]
@ingvarha I'm closing this under the assumption that the RH python has additional backports not available in an official release before 2.7

**Comment by hermunn** [comment]
Backport review: If packaging of 4.1 for EL6 has problems, it will be handled in a different issue or internally.
