### ISSUE TITLE
Build varnish-5.1.1 on el6: Warnings prohibits build with gcc- 4.4.7 and -Werror

### ISSUE THREAD

**Issue by ingvarha** [varnishcache/varnish-cache#2265]
varnish-5.1.1 is built with -Werror added to CFLAGS. This prohibits build on gcc-4.4.7, the standard cc on RHEL6 and clones. (A cast to void in the actual write calls seems not enough.)

## Expected Behavior
Build fine on el6

## Current Behavior
build fails like this: 

```
http1/cache_http1_deliver.c: In function ‘v1d_error’:
http1/cache_http1_deliver.c:74: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result
```

```
mgt/mgt_param.c: In function ‘MCF_DumpRstParam’:
mgt/mgt_param.c:627: warning: ignoring return value of ‘fwrite’, declared with attribute warn_unused_result
mgt/mgt_param.c:631: warning: ignoring return value of ‘fwrite’, declared with attribute warn_unused_result

```

```
proxy/cache_proxy_proto.c: In function ‘VPX_Send_Proxy’:
proxy/cache_proxy_proto.c:464: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result

```

## Possible Solution
Ugly workaround: Patch Makefile, remove -Werror

## Steps to Reproduce (for bugs)
Build from source on rhel6 or a clone

## Context
I'm building packages of all varnish versions on all supported variants of fedora and rhel clones

## Your Environment
* Version used: varnish-5.1.1
* Operating System and version: Centos 6 on x86_64, latest update

**Comment by bsdphk** [comment]
While undoubtedly well intentioned and in many cases even a good thing, I don't see us decorating the source to surpress this.

Can you please try the remedy at the bottom of this: http://www.linuxquestions.org/questions/programming-9/gcc-warn_unused_result-attribute-917158/

**Comment by denisbr** [comment]
I've discussed this issue with @ingvarha and for some reason I don't see this issue in our build jobs. We're also on CentOS6 x86_64 with gcc 4.4.7, and -Werror is definitely in use. 
Not sure what could cause these differences though.

**Comment by ingvarha** [comment]
The difference is that in Fedora and EPEL, there is a policy to set -D_FORTIFY_SOURCE=2. In the pkg-varnish builds, you use -D_FORTIFY_SOURCE=0.

I'll just patch bin/varnishd/Makefile for my builds for now. You may close this issue.
