### ISSUE TITLE
Release date for version 5.1.2

### ISSUE THREAD

**Issue by joshuaspence** [varnishcache/varnish-cache#2281]
I apologise if this isn't the correct place to ask this question, but I was wondering when you are expecting to release version 5.1.2? We are seeing quite a few panics on version 5.0.0 - 5.1.1 due to #2275. I have built from `master` and verified the fix, so now we are just awaiting a new package to be uploaded to PackageCloud.

**Comment by Dridi** [comment]
Definitely not the right place. 5.1.2 should land "soon" but there are other bugs to fix too.

For questions like this one, please head to the misc mailing list instead: http://varnish.org/support/

**Comment by hermunn** [comment]
Backport review: Invalid
