### ISSUE TITLE
memory leak? in HTTP/2

### ISSUE THREAD

**Issue by xcir** [varnishcache/varnish-cache#2284]
![foo](https://cloud.githubusercontent.com/assets/198198/24397944/b609a8ae-13e2-11e7-85c6-27ea3f58b429.png)
This graph is rev acd4c29.
Memory increase pace has increased, if enable H/2.
Enabled/Disable on hitch only.(alpn-protos)
I did not change/restart varnish.(keep feature=+http2)

![bar](https://cloud.githubusercontent.com/assets/198198/24397914/a2c3bb54-13e2-11e7-9849-0c0320afac2c.png)
Sorry, this graph rev is unknown. I forgot the note. (But, After5.1.1)

I got pmap -X. But, place of concern was [anon]. (7f23bbfc0000)
[1.pmap](https://gist.githubusercontent.com/xcir/8ba865dc78474f018b1889ff52032f5f/raw/e992981e3862289a68bdd66160267e2dc3143d16/1.pmap)
[2.pmap (A few hours after 1.pmap)](https://gist.githubusercontent.com/xcir/8ba865dc78474f018b1889ff52032f5f/raw/e992981e3862289a68bdd66160267e2dc3143d16/2.pmap)

## Your Environment
* Version used: hitch1.4.4 + varnish-5.1.1 (acd4c29)
* Operating System and version: Ubuntu 16.04.1 LTS (4.4.0-24-generic)

**Comment by bsdphk** [comment]
I certainly won't rule out a memory leak.

**Comment by xcir** [comment]
Sorry my run-parameter is bad.
Memory metrics trends were too different between H/1 and H/2, I thought leak.
Solved this issue, if tuning thread_pool_min.

**Comment by gaspo53** [comment]
> thread_pool_min

hey! How did you tune that param?

**Comment by gquintard** [comment]
@gaspo53 , check out `man varnishadm`, it should lead you to `varnishadm param.set thread_pool_min XXX`

**Comment by gaspo53** [comment]
> @gaspo53 , check out `man varnishadm`, it should lead you to `varnishadm param.set thread_pool_min XXX`

@gquintard thanks! I'm having memory spikes and varnish starts to return 500. Is there impact on memory by changing this param?

**Comment by gquintard** [comment]
let's step away from the bug tracker and only use it for confirmed bug. Can I ask you to send an email to varnish-misc@varnish-cache.org, including a pastebin link of the output of `varnishlog -g request -q 'RespStatus eq 500'`? (feel free to add any extra info you think could be relevant)

**Comment by gaspo53** [comment]
> let's step away from the bug tracker and only use it for confirmed bug. Can I ask you to send an email to [varnish-misc@varnish-cache.org](mailto:varnish-misc@varnish-cache.org), including a pastebin link of the output of `varnishlog -g request -q 'RespStatus eq 500'`? (feel free to add any extra info you think could be relevant)

@gquintard will do! Thanks a lot
