### ISSUE TITLE
Regression of #1767 in Varnish 5.0, 5.1

### ISSUE THREAD

**Issue by dmz-uk** [varnishcache/varnish-cache#2288]
configtest no longer works in 5.0 and 5.1 when the -a flag is set (could not bind to address); removing the -a flag allows configtest to work as normal. Appears to be a regression of https://github.com/varnishcache/varnish-cache/issues/1767

**Comment by nigoroll** [comment]
dup of #2217

**Comment by hermunn** [comment]
Backport review: Dup
