### ISSUE TITLE
Collect cookie-headers when running h2

### ISSUE THREAD

**Issue by simonvik** [varnishcache/varnish-cache#2291]
When running h2 its common that the client sends multiple cookie headers to increase compression.

According to https://tools.ietf.org/html/rfc7540#section-8.1.2.5 a h2 -> h1 proxy should concat multiple cookies into one delimited by "0x3B 0x20"

## Expected Behavior
That I only see one single req.http.cookie header delimited by "; "

## Current Behavior
Varnish sends multiple Cookie-headers to the backend.

## Possible Solution
1. Collect cookie-headers default when running h2.
2. Get std.collect( to take a delimiter option. 
     `std.collect(req.http.cookie, "; ");`

**Comment by Dridi** [comment]
For more information on the wonderful world of cookies, I also recommend RFC 6265.

https://tools.ietf.org/html/rfc6265

**Comment by hermunn** [comment]
Backport review: H2 is not in Varnish 4.1, so there is nothing to backport here.
