### ISSUE TITLE
Documentation for std.collect might be bad

### ISSUE THREAD

**Issue by simonvik** [varnishcache/varnish-cache#2292]
https://varnish-cache.org/docs/trunk/reference/vmod_std.generated.html#func-collect

Contains an example that says: 
```
Example
std.collect(req.http.cookie);
```

Multiple cookie headers should not be sent over HTTP/1.1 and if they were then they should be joined by "; " and not "," as the module does.

h2-clients might send multiple cookie headers and that's reported in : #2291

**Comment by hermunn** [comment]
Backport review: I do not think there is a need for this in 4.1, so we will keep it Varnish 5 only unless I hear strong protests.
