### ISSUE TITLE
Spinning loop in VBE_Poll causes master to kill child on CLI timeout

### ISSUE THREAD

**Issue by mbgrydeland** [varnishcache/varnish-cache#2295]
In VBE_Poll() there is a loop that deletes old dynamic backends after a cooling period. This loop bugs out and becomes a kind of long running spinlock when the backend to be cleaned has a non-zero n_conn (due to very slow backend fetch). This causes the CLI thread to spin in a tight loop, possibly for a very long time, causing the master process to kill the child on CLI timeout.

PR and test case will follow.

**Comment by mbgrydeland** [comment]
Ref #2296

**Comment by hermunn** [comment]
In the corresponding pull request I wrote:

Backport review: 667256f backported as 04b4e38.
