### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by thomas15v** [varnishcache/varnish-cache#2306]
While there are already some docker containers out their for varnish. I was wondering if you guys are planning to deliver official docker images?

**Comment by Dridi** [comment]
Github issues are not for questions, only bug reports. See other support channels [1] to discuss this. Regarding docker images, it has already been discussed and I believe it is nowhere on the agenda.

[1] http://varnish.org/support/

**Comment by egeland** [comment]
Not having an official Docker image, in today's world of containers, could qualify as a bug.. 😉
