### ISSUE TITLE
Content-Type JSON request gets HTML response on error 503

### ISSUE THREAD

**Issue by 1Hyena** [varnishcache/varnish-cache#2308]
## Expected Behavior

I should receive empty string or {}

## Current Behavior

I receive this as a response:
```
<!DOCTYPE html>
<html>
  <head>
    <title>503 Backend fetch failed</title>
  </head>
  <body>
    <h1>Error 503 Backend fetch failed</h1>
    <p>Backend fetch failed</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 32771</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

## Possible Solution

When the request's content-type is application/json as shown below
```
curl -H "Content-Type: application/json" -X POST --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getnettotals", "params": [] }' localhost:6000
```
and varnishd fails to fill that request then it should respond either an empty string or empty json object. empty string is preferred though. alternatively there should be a way to disable this default response from command line.

## Steps to Reproduce (for bugs)

1. `varnishd -n /home/xxx/Desktop/temp -W epoll -a 127.0.0.1:6000 -b 127.0.0.1:7000 -F`
2. `curl -H "Content-Type: application/json" -X POST --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getnettotals", "params": [] }' localhost:6000`
3. make sure nothing is listening on port 7000 to get the default error

## Context

I'm building a cache in front of Bitcoin's reference client's RPC interface. I only deal with JSON (requests and responses) so it is highly inappropriate to receive a HTML response generated by varnish sometimes.

## Your Environment

* Version used:
varnishd (varnish-4.1.1 revision 66bb824)

* Operating System and version:
Linux 4.8.0-45-generic #48~16.04.1-Ubuntu SMP Fri Mar 24 12:46:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Source of binary packages used (if any)
`sudo apt-get install varnish`

**Comment by gquintard** [comment]
This is not a bug, please use the appropriate support channels: http://varnish-cache.org/support/index.html

**Comment by 1Hyena** [comment]
@gquintard 
If the solution is to use config file then this is not acceptable solution

**Comment by 1Hyena** [comment]
@gquintard 
I updated the issue just before you commented and closed it. Please look at it again. I still think it is a bug.

**Comment by 1Hyena** [comment]
@gquintard 
If the application using varnish does not have anything to do with HTML then the default response of HTML is conceptually wrong. so this is a bug. prove me wrong

**Comment by gquintard** [comment]
Get on varnish-misc, or on IRC, and get us a the varnishlog corresponding to that backend transaction and we'll look at it.

To be clear: the server don't owe you a mime type, it can answer with whatever it wants, it merely has to advertise the MIME its replying with. If you don't like the  default html error message, you can change it.

**Comment by 1Hyena** [comment]
@gquintard thanks for the explanation. I can agree now that it is not necessarily a bug. however, the reason why I personally have chosen to use varnish instead of all the other alternatives is that varnish does not require me to use a configuration file for very simple use cases. I would very much like to solve this issue without using a configuration file. Or at least, make it possible to provide the configuration file over stdin.

**Comment by Dridi** [comment]
I think you lack enough understanding of the varnish architecture. Please move this discussion where we will prove you wrong [1] on any point you wish to discuss. I'm with @gquintard here and I insist this is not a bug, and the discussion is moving further away from a bug report.

[1] or as I would prefer to say, try to enlighten you :)
