### ISSUE TITLE
cannot link to varnishapi, symbols missing

### ISSUE THREAD

**Issue by dmatetelki** [varnishcache/varnish-cache#2313]
`libvarnishapi.map` contains:
```
VSM_iter0;
VSM_intern;
```
out of sync with `vapi/vsm.h`, which contains:
```
VSM__iter0;
VSM__itern;
```

Currently it's possible to compile against those symbols, as they are found in `vapi/vsm.h`, but cannot link to, as `libvarnishapi.map` does not expose them.

**Comment by Dridi** [comment]
This happened in f394f0adba53e7a60a516c85968a0f4c95095423, so quite a while ago. There may be other missing symbols from the API change, and the breakage appears to have happened between the inauguration of `libvarnishapi.map` and the first release shipping it.

Workaround: `#define` ?

**Comment by dmatetelki** [comment]
Two possible directions emerged:

1. These 2 symbols meant to be low level and not exposed, hence the double underscores in the names.

d

**Comment by Dridi** [comment]
We can also both have the foreach macro and promote (and possibly rename) those symbols. However, I wouldn't retroactively put them in 1.0 but rather inaugurate the next soname version. Older builds with the wrong names wouldn't expose the symbols anyway.

**Comment by dmatetelki** [comment]
@Dridi : do you mean in `libvarnishapi.map` 

```
LIBVARNISHAPI_1.7 {
  global:
	VSM__iter0;
	VSM__itern;
} LIBVARNISHAPI_1.0;
```

**Comment by Dridi** [comment]
Confirmed

**Comment by hermunn** [comment]
Backport review: As this is not very critical, I will leave it to @dmatetelki to decide if he wants it in 4.1. Send me an email with the port, and I can review it.
