### ISSUE TITLE
varnish 5 vcl name restrictions

### ISSUE THREAD

**Issue by mookie-** [varnishcache/varnish-cache#2317]
## Expected Behavior
`/usr/bin/varnishadm vcl.load reload_2017-04-20T12:28:54 /etc/varnish/varnish.vcl` returns 0 and loads vcl

## Current Behavior
With varnish 5 it fails:
```
/usr/bin/varnishadm vcl.load reload_2017-04-20T12:28:54 /etc/varnish/varnish.vcl
Illegal character in VCL name (':')
Command failed with error code 106
```
WIth varnish 4 it works:
```
/usr/bin/varnishadm vcl.load reload_2017-04-20T12:34:12 /etc/varnish/varnish.vcl
VCL compiled.
```

## Possible Solution
Make VCLs with `:` possible again or add the change to the upgrade/changes documentation of varnish 5.

## Steps to Reproduce (for bugs)
1. run `varnishadm vcl.load reload_2017-04-20T12:34:12 /etc/varnish/varnish.vcl` with varnish4 => works
2. run `varnishadm vcl.load reload_2017-04-20T12:34:12 /etc/varnish/varnish.vcl` with varnish5 => fails

## Context
The vcl name with `:` is used by the default Gentoo init script for varnish.

## Your Environment
* Version used: 5.1.2
* Operating System and version: Gentoo
* Source of binary packages used (if any): used source from http://repo.varnish-cache.org/source/varnish-5.1.2.tar.gz

**Comment by nigoroll** [comment]
https://www.varnish-cache.org/docs/5.0/whats-new/upgrading-5.0.html#changes-to-vcl

* VCL names are restricted to alphanumeric characters, dashes (-) and
  underscores (_).  In addition, the first character should be alphabetic.
  That is, the name should match "[A-Za-z][A-Za-z0-9\_-]*".

**Comment by mookie-** [comment]
@nigoroll sorry ![box-of-shame](https://media.giphy.com/media/d7fTn7iSd2ivS/giphy.gif)

**Comment by nigoroll** [comment]
no worries

**Comment by Dridi** [comment]
This is a packaging bug, it belonged in pkg-varnish-cache anyway. See varnishcache/pkg-varnish-cache#42.
