### ISSUE TITLE
Storage name collisions

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2321]
I just had an unexpected forced wait and took advantage of it to quickly look at how storage names are handled in order to do the same for listen addresses. During my review I found two ways of creating name collisions and I'm reporting it because I'm not sure how we want to handle it:

```
varnishtest "Storage name collisions"

# intentional collision
varnish v1 -arg "-s main=malloc -s main=malloc -b '${bad_backend}'" -start

shell {
        varnishadm -n ${v1_name} storage.list |
        grep 'storage.main = malloc' |
        wc -l |
        grep 2
}

# pseudo-accidental collision
varnish v2 -arg "-s malloc -s s0=malloc -b '${bad_backend}'" -start

shell {
        varnishadm -n ${v2_name} storage.list |
        grep 'storage.s0 = malloc' |
        wc -l |
        grep 2
}
```

This test is not fit for regression testing because it passes, proving that both approaches are broken.

Maybe we could add an "expect failure" feature in `varnishtest` since we don't use this feature in `automake`, split this test in two and expect `varnish v1` to simply fail. Otherwise I can write a test case that starts `varnishd` from a `shell` as we usually do.

Considering that we'd expect only a handful of listen addresses and storage backends, and since this is initialization code, I would go for a naive foreach loop to check name collisions at insert time. Regarding the accidental collision, I'm not sure how much helpful we would want to be in the error message. I'd say not too much since you really need to do it on purpose to collide with a fall-back name.

Until I know how this should be done I can't fix it, please enlighten me :)

**Comment by fgsch** [comment]
> Considering that we'd expect only a handful of listen addresses and storage backends, and since this is initialization code, I would go for a naive foreach loop to check name collisions at insert time. 

I think this should be enough. +1

**Comment by Dridi** [comment]
I will proceed as I intended unless someone objects based on @fgsch's feedback alone :)
