### ISSUE TITLE
checking backend health for more than 2 web servers in varnish 4

### ISSUE THREAD

**Issue by behinam** [varnishcache/varnish-cache#2324]
I have a varnish server with 3 backends. all backends are apache. everything is ok and the varnish server caches everything I need, and the connections are OK. I wnat to monitor the health of web servers. and in case of a failure, varnish does not send reuests to the failed web server. The problem is that when I enable the probe for all backedns I get the 503 error! If i enablle it on one or two backends, everything is OK, but when I enable it for 3 backends I get the 503 error.
here's varnish configuration for backends and health checking:

vcl 4.0;

import directors;

probe backend_healthcheck {
.url = "/";
.timeout = 34 ms;
.window = 5;
.threshold = 3;
.interval = 1s;

}

backend web1 {
.host = "192.168.1.16";
.port = "8080";
.probe = backend_healthcheck;
}

backend web2 {
.host = "192.168.1.18";
.port = "8080";
.probe = backend_healthcheck;
}

backend web3 {
.host = "192.168.1.20";
.port = "8080";
.probe = backend_healthcheck;
}

sub vcl_init {
new apache = directors.round_robin();
apache.add_backend(web1);
apache.add_backend(web2);
apache.add_backend(web3);
}

**Comment by behinam** [comment]
We resolved the problem with the command : `varnishlog -g raw -i Backend_health`: 

> Backend_health - web3 Still sick 4--X-R- 0 3 5 0.000803 0.000000 HTTP/1.1 403 Forbidden

 I added 

> expected_response = 403;

 to the probe section and the problem resolved.

**Comment by bsdphk** [comment]
Glad to see you found a solution, sorry about not answering before you did that :-)

In general it's probably not a good idea to probe on a 4xx response, because that doesn't really tell you if the apache is working (as opposed to hanging in disk/database access etc.), but it is certainly better than nothing.
