### ISSUE TITLE
Enforce proper symbol names for storage back-ends

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2325]
I was looking under the storage carpet and found two bugs. After I squashed the first one (#2321) the second turned into some kind of huge monster and suddenly I could no longer submit a fix.

Storage back-ends are exposed in VCL as `storage.<name>` symbols but the name can currently be anything:

```
varnishtest "nonsensical name"

varnish v1 -arg "-s ...=malloc" -cli storage.list
```

From the test report:

```
**** v1    0.1 CLI TX|storage.list
***  v1    0.2 CLI RX  200
**** v1    0.2 CLI RX|Storage devices:
**** v1    0.2 CLI RX|\tstorage.... = malloc           <= SEE HERE
**** v1    0.2 CLI RX|\tstorage.Transient = malloc
**   v1    0.2 CLI 200 <storage.list>
*    top   0.2 RESETTING after test.vtc
```

When I first reported this it turned into a discussion about unicode support in VCL symbols instead of allowing C-like symbol names. It was also suggested that `...` would be a proper symbol name, provided that we could use an escaped name that would be a proper symbol name. So on top of supporting characters outside of ascii, any character could become valid (extreme case IIUC).

I'm tracking this bug until we decide whether we kill or tame the unicode monster. Otherwise I can send a patch.

**Comment by bsdphk** [comment]
Now would be a good time to decide definitively what is a legal "name" in VCL.

Xcir's feedback seems to indicate that UNICODE is not a hot-ticket item, but I would prefer to not cut of that avenue yet.

I think my proposal would be `[a-zA-Z][a-zA-Z0-9_-]*`

The inclusion of '-' means that we need a canonical way to quote this into C-identifiers, but this is entirely confined to VCC and therefore not an API issue, neither now or going forward.

We already have code which does this one place:

        VSB_printf(vsb, "&VGC_%s_", vh->rname);
        for (p = b, u = 1; p < e; p++, u++)
                if (vct_isalpha(*p) || vct_isdigit(*p))
                        VSB_putc(vsb, *p);
                else
                        VSB_printf(vsb, "_%02x_", *p);
        AZ(VSB_finish(vsb));

And I think that works OK for me, and it is UTF-8 robust, should we need it.

The trailing '_' is not necessary for undoing the quoting, but I feel it improves readability.

We should add a canonical function (in VCT ?) to validate a VCL compliant name, so MGT can bail out early and intelligently.

**Comment by bsdphk** [comment]
I should add that it is probably also a good idea to settle once and for all on the

    ?( name "=" ) arg *( "," subarg )

form of arguments, and thus there may be a market for convenience functions for it in MGT.

**Comment by Dridi** [comment]
We also have the macro names in VTC, and if we want to expose named listen addresses [1] they also need to support whatever syntax we pick.

[1] https://github.com/varnishcache/varnish-cache/wiki/VIP-17:-Enable-Unix-domain-sockets-for-listen-and-backend-addresses#testing

**Comment by Dridi** [comment]
Bugwash consensus:

- all names to match `[a-zA-Z][a-zA-Z_-]*`
  - no "weak" symbols allowed
- header names to stay their own thing syntax-wise
- all symbol names to be unique (making r01569.vtc history)
- names "externally imported" (outside of VCL) to be namespace'd
  - `storage.Transient`, `socket.a0`, `vcl.my_label` etc

**Comment by fgsch** [comment]
Wot? No numbers?

**Comment by Dridi** [comment]
@fgsch, of course you can write numbers, spell them using letters. Just kidding, I forgot them, I will edit it now.

**Comment by Dridi** [comment]
Moved the remaining points to https://github.com/varnishcache/varnish-cache/issues/2318#issuecomment-336057770, closing.
