### ISSUE TITLE
/usr/bin/install: cannot stat '.libs/libvmod_std.so': No such file or directory

### ISSUE THREAD

**Issue by thuandh86** [varnishcache/varnish-cache#2328]
Hi,
I build varnish (from git):
1. Git clone ..
2. ./autogen.sh
3. ./configure
4. sudo ldconfig
5. make --> no show error
6. sudo make install

in step 6 show error:
make[3]: Entering directory `/varnish-5.1.2/lib/libvmod_std'
make[3]: Nothing to be done for `install-exec-am'.
 /bin/mkdir -p '/usr/local/lib/varnish/vmods'
 /bin/bash ../../libtool   --mode=install /usr/bin/install -c   libvmod_std.la '/usr/local/lib/varnish/vmods'
libtool: install: /usr/bin/install -c .libs/libvmod_std.so /usr/local/lib/varnish/vmods/libvmod_std.so
/usr/bin/install: cannot stat '.libs/libvmod_std.so': No such file or directory
make[3]: *** [install-vmodLTLIBRARIES] Error 1
make[3]: Leaving directory `/varnish-5.1.2/lib/libvmod_std'
make[2]: *** [install-am] Error 2
make[2]: Leaving directory `/varnish-5.1.2/lib/libvmod_std'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/varnish-5.1.2/lib'
make: *** [install-recursive] Error 1

please help me. I dont show build library share(*.so) in folder lib

**Comment by bsdphk** [comment]
What operating system is this on ?

**Comment by thuandh86** [comment]
I use Ubuntu 14.04:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

I run command line:
apt-get install automake autotools-dev libedit-dev libjemalloc-dev libncurses-dev libpcre3-dev libtool pkg-config python-docutils python-sphinx graphviz --> install all success

**Comment by fgsch** [comment]
Please use the existing support channels to receive help with this.
See https://www.varnish-cache.org/support/.
