### ISSUE TITLE
unix jail not used by default when running as varnish user

### ISSUE THREAD

**Issue by teohhanhui** [varnishcache/varnish-cache#2329]
According to http://www.varnish-cache.org/docs/5.1/reference/varnishd.html#jail

> _-j <unix[,user=\`user\`][,ccgroup=\`group\`][,workuser=\`user\`]>_
> Default on all other platforms when _varnishd_ is either started with an effective uid of 0 ("as root") or as user `varnish`.

But looking at the code at https://github.com/varnishcache/varnish-cache/blob/varnish-5.1.2/bin/varnishd/mgt/mgt_jail_unix.c#L124-L129

it seems to bail out if the `varnish` user exists.

## Expected Behavior
-junix

## Current Behavior
-jnone

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
1. Run varnishd as `varnish` user.

## Context
https://github.com/tripviss/docker-varnish

## Your Environment
* Version used: 5.1.2
* Operating System and version: Debian Jessie
* Source of binary packages used (if any): compiled from source

**Comment by Dridi** [comment]
Sorry about the confusion, only the root user can initiate a unix jail in Varnish. You need privileges to drop privileges...

**Comment by hermunn** [comment]
Backport review: The fix 4c9b8d8 was backported as 768a8536.
