### ISSUE TITLE
Varnish loses response when backend returns an error during a POST

### ISSUE THREAD

**Issue by dward** [varnishcache/varnish-cache#2332]
Varnish may lose the backend response when a backend immediately returns an error when varnish is still sending  a request body.

Example of this situation:

When a POST is received from varnish, and varnish sends the request to an apache backend with 
 a content-length that exceeds LimitRequestBody, apache will immediately return a 413 (Request Entity Too Large).

```
HTTP/1.1 413 Request Entity Too Large
Date: Tue, 23 May 2017 19:51:33 GMT
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>413 Request Entity Too Large</title>
</head><body>
<h1>Request Entity Too Large</h1>
The requested resource<br />/app/foo.php<br />
does not allow request data with POST requests, or the amount of data provided in
the request exceeds the capacity limit.
</body></html>
```

At this point, varnish appears to be in a loop reading/writing the request body from the client to the backend, unaware that the backend has sent an error.

Assuming the complete request body has not been sent, apache will wait until the client closes the connection or it hits the default linger timeout of 30 seconds, which at that point will forcefully close the socket.

The forceful shutting of the socket causes varnish to react with:
```
-        65584 Debug          b "Write error, retval = -1, len = 6, errno = Broken pipe"
-        65584 FetchError     b req.body read error: 32 (Broken pipe)
-        65584 FetchError     b backend write error: 32 (Broken pipe)
```

At this point, varnish returns a backend fetch fail error because of the write failure and never reads the response from the backend, and goes straight to vcl_backend_error.

This is particularly a problem with large POSTs from slow spoon feeding clients. The request body cannot be sent to the backend before the linger timeout (30 seconds).

## Expected Behavior
The error message would be read and returned to the client. Ideally, varnish would immediately detect the backend error preventing the long linger timeout to begin with.

## Current Behavior
Varnish attempts to read the request body until fully read, or an error/timeout occurs even if the backend immediately responds with an error.

## Steps to Reproduce (for bugs)
1. Configure an apache backend LimitRequestBody to a small limit, such as 10485760 
2. Create a 100MB file (dd if=/dev/zero of=largefile.txt bs=1M count=100)
3.  Slowly upload a file to varnish instance with apache backend with slow transfer rate: (curl -v --limit-rate 25K -F foo=@largefile.txt http://varnishendpoint/)

## Your Environment
* Version used: 4.1.6
* Operating System and version: CentOS 7

**Comment by Dridi** [comment]
One thing a client should do when POSTing a large body is to send a conditional request with an `Expect: 100-continue` header. When Varnish passes a POST to the backend, it could be nice to have a mechanism for that when the user knows the backend supports it.

Something like `set bereq.do_expect = true`, or simply by setting the header (or inheriting it from the client).

After a quick check in the test suite, Varnish appears to handle the 100-continue case at least on the client side.

**Comment by dward** [comment]
Sounds like that would work for an immediate error situation, such as content-length validation, which would be a great start and fix my particular example.

But, an error can also happen at any point during the request body transmission. Would it be beneficial to detect a socket shutdown of the backend (POLLRDHUP)? Looking at the code, it appears that it would not be a trivial change as it would need to change to non-blocking i/o.

**Comment by Dridi** [comment]
> Looking at the code, it appears that it would not be a trivial change as it would need to change to non-blocking i/o.

We have another possible change proposed for 6.0 that could require non-blocking i/o, so that could be a possibility.

**Comment by bsdphk** [comment]
When we get a write error sending body, we should do a read to see if a response is waiting for us.

Related to this, it would be nice to have the option of enabling 100-Continue to a backend:

    set bereq.100-continue = True;

**Comment by Dridi** [comment]
If I may interject, `100-continue` is not a valid symbol name. We can keep this bike shed for later ;(

**Comment by bsdphk** [comment]
I have parked this subject in a XXX comment in cache_http1_fetch.c.

The split between VBE and V1F is wrong, at least if we want to support H2, H3 and other kinds of protocol based backends, and this should be fixed as part of that API renovation.

**Comment by twbecker** [comment]
I'm confused about which versions of Varnish this is fixed in, if any. Can someone illuminate?

**Comment by Dridi** [comment]
There is currently no fix, it is tracked here:

https://github.com/varnishcache/varnish-cache/blob/ffc69d8170fef118f02b8dd158feb08ae7a24d87/bin/varnishd/http1/cache_http1_fetch.c#L120-L135

**Comment by fbotis** [comment]
Has anyone find any work-around for this? 

"This is particularly a problem with large POSTs from slow spoon feeding clients. The request body cannot be sent to the backend before the linger timeout (30 seconds)."

Where do I set the "linger timeout" ?

**Comment by gquintard** [comment]
> Where do I set the "linger timeout" ?

```
-p timeout_linger=XXXs
```

in the `varnishd` command line

**Comment by Dridi** [comment]
If anyone is still subscribed to this ticket, there's a new candidate to try: #3761.
