### ISSUE TITLE
fetch variable values in regexp varnish

### ISSUE THREAD

**Issue by NithishReddy** [varnishcache/varnish-cache#2334]
I have following regular expression in varnish configuration language

^/abc/([a-zA-Z0-9-\ ]*)-([0-9]+)

now i want fetch the value $2 part(i.e [0-9]+ ) of regular expression in varnish.

how can i get this value ?

**Comment by Dridi** [comment]
Hi, as indicated in the issue template you get when you open an issue, general questions don't belong on github. Please hit the misc mailing list instead or join the varnish channel on our IRC server.

http://varnish.org/support/

**Comment by nigoroll** [comment]
@Dridi is absolutely right, but I guess this pointer won't do any harm either: https://code.uplex.de/uplex-varnish/libvmod-re/
