### ISSUE TITLE
Connection: close handling on return(pipe) does not override present Connection headers

### ISSUE THREAD

**Issue by daghf** [varnishcache/varnish-cache#2337]
On a pipe Varnish will automagically set `Connection: close`. However, if there already is a `Connection` header present this will not be unset, with the result that we now have multiple possibly conflicting `Connection` headers,

<pre>
GET / HTTP/1.1
Connection: keep-alive
X-Forwarded-For: 127.0.0.1
X-Varnish: 1001
Connection: close
</pre>

## Steps to Reproduce (for bugs)

<pre>
varnishtest "Connection header and pipe"

server s1 {
	rxreq
	expect req.http.Connection == "close"
	txresp
} -start

varnish v1 -vcl+backend {
	sub vcl_recv {
		return (pipe);
	}
} -start

client c1 {
	txreq -hdr "Connection: keep-alive"
	rxresp
} -run
</pre>

## Workaround
<pre>
sub vcl_pipe {
	set bereq.http.Connection = "close";
}
</pre>

**Comment by carlosabalde** [comment]
We've been bitten by this bug recently. I guess the suggestion would be ensuring `Connection: close` is the only `Connection` header in the outgoing request (i.e. overwriting any incoming `Connection` header).

**Comment by gquintard** [comment]
shouldn't the C code do nothing at all and let the VCL take care of if? That's what builtin.vcl seems to indicate.

**Comment by fgsch** [comment]
@carlosabalde what if you want to retain it? That's my concern.

**Comment by fgsch** [comment]
> shouldn't the C code do nothing at all and let the VCL take care of if? That's what builtin.vcl seems to indicate.

I tend to agree with this but it's a non-backward compatible change.

**Comment by carlosabalde** [comment]
If retaining incoming `Connection` headers is a realistic use case then I guess going back to the original 3.x behaviour (i.e. execute `set bereq.http.Connection = "close";` during `vcl_recv` if needed) would be fine for everybody (except for the non-backwards compatible part).

**Comment by fgsch** [comment]
We could keep the connection by doing:

```
set bereq.http.connection = req.http.connection;
```

So I guess unsetting any existing Connection headers before setting it would make more sense.

**Comment by Dridi** [comment]
And we can revisit the `Connection: close` by default for 6.0 along with the other pipe changes. FWIW the VIPs 6 and 8 are still open, and IMO relevant until HTTP/2 support is no longer experimental.
