### ISSUE TITLE
Thread_pool_add_delay delays initialization of varnish on start.

### ISSUE THREAD

**Issue by zaterio** [varnishcache/varnish-cache#2343]
## Varnish Version

```
root@b5e01:/usr/src/varnish-cache-master# varnishd -V
varnishd (varnish-trunk revision NOGIT)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
```

(master.zip downloaded for github on 29/May/2017)

## Varnish Configuration

`/usr/local/varnish/sbin/varnishd  -a *:80 -T 127.0.0.1:6082  -f /etc/varnish/default.vcl -h classic,16383 -s malloc,8000M -p thread_pools=12 -p thread_pool_min=100 -p thread_pool_max=8000 -p thread_pool_add_delay=10 -p auto_restart=on -p ping_interval=3 -p send_timeout=60 -p workspace_session=128k -p cli_timeout=25 -p http_gzip_support=off -p tcp_keepalive_time=10 -p listen_depth=8192 -p cli_buffer=32k -p cli_limit=96k -p ban_dups=on`

## Current Behavior

When starting varnish, varnish is irresponsive to curl requests, backends are in sick state and varnishlog has no activitie for at least 10 minutes. After this time varnish begin to work normally.

If in the configuration line I delete "thread_pool_add_delay = 10" and then reinitialize varnish, varnish responds to curl immediately (also the backends are marked healthy from the start)

Since version 4 of varnish I used the configuration line described above, where this behavior did not occur.

**Comment by Dridi** [comment]
Since Varnish 4 all durations and times are in seconds, so 10 used to mean 10 milliseconds and now varnish is waiting 10 seconds per thread until each pool reaches 100 threads.

What you want is `thread_pool_add_delay=0.010` from now on.

**Comment by zaterio** [comment]
10-4
Thanks
