### ISSUE TITLE
varnish-4.1.6 test suite errors on 32bit i686 and armv7hl

### ISSUE THREAD

**Issue by ingvarha** [varnishcache/varnish-cache#2344]
Building varnish-4.1.6 on fedora 24, I get test suite errors on 32bit:

Failed tests i686:
c00071 (reproducable)
r00962 (on and off)
r02035 (on and off)
r02233 (reproducable)

https://kojipkgs.fedoraproject.org//work/tasks/8699/19988699/build.log
https://kojipkgs.fedoraproject.org//work/tasks/8955/19988955/build.log

Failed tests for armv7hl (32bit)
r02233

https://kojipkgs.fedoraproject.org//work/tasks/8696/19988696/build.log

**Comment by bsdphk** [comment]
This looks like workspace overflow not happening as expected in tests.

**Comment by fgsch** [comment]
r02233 in 4.1 needs updating from master.
Not sure about c00071 but the test is slightly different in master.

**Comment by ingvarha** [comment]
I'm a bit unsure of what r02233 is actually testing. I can "fix" it by just adding a few more lines of 

send "&a=1&a=1&a=1&a=1&a=1&a=1&a=1&a=1&a=1&a=1&a=1&a=1&a=1&a=1&a=1"

until varnish says 500. But that's perhaps not what you really like to test?

I also tried to use the test from master, but then varnishd segfaults, see attached files.

**Comment by ingvarha** [comment]
[r02233.vtc.txt](https://github.com/varnishcache/varnish-cache/files/1114863/r02233.vtc.txt)

**Comment by ingvarha** [comment]
[r02233.log.txt](https://github.com/varnishcache/varnish-cache/files/1114865/r02233.log.txt)

**Comment by ingvarha** [comment]
I forgot to mention the platform here. fedora 24 on i686 (mock chroot)

**Comment by ingvarha** [comment]
Tested varnish-4.1.7 on fedora 24 i686 (mock chroot). Tests c00071, r02233, and u00003 failed. Log attached. 
[build.log.txt](https://github.com/varnishcache/varnish-cache/files/1115364/build.log.txt)

**Comment by fgsch** [comment]
If you copy r02233 from master, does it make any difference?

**Comment by fgsch** [comment]
Ping @ingvarha

**Comment by ingvarha** [comment]
#     top  TEST ./tests/r02233.vtc FAILED (60.060) signal=9 exit=0

[r02233.log.txt](https://github.com/varnishcache/varnish-cache/files/1179478/r02233.log.txt)

**Comment by ingvarha** [comment]
ah, that was on 64bit. On 32bit it just dies with a segfault.

[r02233.log.txt](https://github.com/varnishcache/varnish-cache/files/1179633/r02233.log.txt)

**Comment by ingvarha** [comment]
Setting debug.workspace_allocate to -192 (like in master) seems to fix c00071.

**Comment by ingvarha** [comment]
There seems to be a real bug in varnishncsa in varnish-4.1.7, at least on 32bit, though.

64bit$ bin/varnishncsa/varnishncsa -F "%{VSL:Begin[999999999999]}x"Field specifier 999999999999 for the tag VSL:Begin[999999999999] is probably too high

32bit$ bin/varnishncsa/varnishncsa -F "%{VSL:Begin[999999999999]}x"
Can't open log - retrying for 5 seconds

**Comment by ingvarha** [comment]
I can use the master version for r02233 too. It works when backported to 4.1 style.

Then u00003 is the last bit missing (varnishncsa as noted above).

**Comment by hermunn** [comment]
Two possible patches:

Either:

```
$ git diff
diff --git a/bin/varnishncsa/varnishncsa.c b/bin/varnishncsa/varnishncsa.c
index 71ef79b8a..be73428bd 100644
--- a/bin/varnishncsa/varnishncsa.c
+++ b/bin/varnishncsa/varnishncsa.c
@@ -594,7 +594,7 @@ parse_x_format(char *buf)
 {
        char *e, *r, *s;
        int slt;
-       long i;
+       uintmax_t i;
 
        if (!strcmp(buf, "Varnish:time_firstbyte")) {
                addf_fragment(&CTX.frag[F_ttfb], "");
@@ -634,7 +634,7 @@ parse_x_format(char *buf)
                        if (r == buf || r[1] == ']')
                                VUT_Error(1, "Syntax error: VSL:%s", buf);
                        e[-1] = '\0';
-                       i = strtol(r + 1, &s, 10);
+                       i = strtoll(r + 1, &s, 10);
                        if (s != e - 1)
                                VUT_Error(1, "Syntax error: VSL:%s]", buf);
                        if (i <= 0)
```

Or:

```
$ git diff
diff --git a/bin/varnishncsa/varnishncsa.c b/bin/varnishncsa/varnishncsa.c
index 71ef79b8a..aafb64c2d 100644
--- a/bin/varnishncsa/varnishncsa.c
+++ b/bin/varnishncsa/varnishncsa.c
@@ -642,7 +642,7 @@ parse_x_format(char *buf)
                                    "Syntax error. Field specifier must be"
                                    " positive: %s]",
                                    buf);
-                       if (i > INT_MAX) {
+                       if (i > INT_MAX || errno == ERANGE) {
                                VUT_Error(1,
                                    "Field specifier %ld for the tag VSL:%s]"
                                    " is probably too high",
```

I think both would work, but I can't test them.

**Comment by hermunn** [comment]
The problem here is for architectures where `long` and `int` are the same. Now that I think about it, it is probably enough just to change `i > INT_MAX` to `i >= INT_MAX`.

**Comment by fgsch** [comment]
I will take care of this.

**Comment by ingvarha** [comment]
heh, 
i >= INT_MAX   works ... more or less. The test needs to be rewritten, though :-)

**** top   3.7 shell_out| Field specifier 2147483647 for the tag VSL:Begin[999999999999] is probably too high\n
---- top   3.7 shell_expect not found: ("Field specifier 999999999999 for the tag VSL:Begin[999999999999] is probably too high")

**Comment by Dridi** [comment]
Can't we agree on something sensible? Like for example field selection being limited to [0..255] and wait until someone complains that they have a valid use-case with more fields?

**Comment by fgsch** [comment]
@Dridi That's my plan. It makes no sense to allow any and all numbers up to INT_MAX.

**Comment by ingvarha** [comment]
Another 32bit test suite bug on 4.1.x: 

https://kojipkgs.fedoraproject.org//work/tasks/5469/20845469/build.log

Might be arm specific. Why does it fail. It seems to do everything it should, but then keeps hanging until killed.

Ingvar

**Comment by fgsch** [comment]
I believe we can close this one. @ingvarha?

**Comment by ingvarha** [comment]
Yes, this was fixed. Close.

Ingvar
