### ISSUE TITLE
resp.reason rewritten when setting resp.status in vcl_synth

### ISSUE THREAD

**Issue by ema** [varnishcache/varnish-cache#2345]
Hi,

a common pattern used to return synthetic responses from varnish such as HTTP redirects is to `return synth` using a fake HTTP status code, later checking for that value in `vcl_synth`: http://book.varnish-software.com/4.0/chapters/VCL_Subroutines.html#example-redirecting-requests-with-vcl-synth

When setting `resp.status` in `vcl_synth`, however, `resp.reason` gets rewritten with the default Reason-Phrase associated with the chosen Status-Code. Thus, VCL code like the one mentioned above does not work as expected. See https://phabricator.wikimedia.org/P5575

**Comment by nigoroll** [comment]
A custom reason phrase can be kept with this pattern:
```
            set resp.http.x-r-saved = resp.reason;
            set resp.status = ...;
            set resp.reason = resp.http.x-r-saved;
            unset resp.http.x-r-saved;
```
The reasoning behind `resp.status` overriding `resp.reason` is that core code has no knowledge as to whether or not the custom reason is intended or not.
Also please keep in mind that custom reasons do not exist for  H/2.
