### ISSUE TITLE
Does varnish confident with backend's timeout?

### ISSUE THREAD

**Issue by catap** [varnishcache/varnish-cache#2348]
Hey,

I've checked the varnish code, and I confused about backend's timeout.

At `vbe_dir_gethdrs` the code calls `V1F_SendReq` and after `V1F_FetchRespHdr`. 

`V1F_SendReq` calls `VTCP_blocking` and made the socket in blocking mode.

`V1F_FetchRespHdr` still is using blocking socket (or I miss where it switched to non-blocking?) and call `VTCP_read` over `HTC_RxStuff`.

`VTCP_read` uses `poll` to sleep for timeout or before some data arrived, but after this, it used `read` and try to read all data.

If I'm right and `VTCP_read` is working with blocking socket, and backend response larger than one TCP segment, `read` will block up to all response come.

Am I wrong?

**Comment by Dridi** [comment]
Hello,

Github issues are only for actual bug reports as described in the issue template when you open one. For general discussions please head to the mailing lists or the IRC channels.

http://varnish.org/support/
