### ISSUE TITLE
Assert error in h2h_decode_bytes

### ISSUE THREAD

**Issue by daghf** [varnishcache/varnish-cache#2349]
Spotted via http2fuzz, https://github.com/c0nrad/http2fuzz

Issue seems to occur if a request indicates padding without actually including the padding bytes.

Fix is probably to do proper input verification and error handling in h2_rx_headers.

    Assert error in h2h_decode_bytes(), http2/cache_http2_hpack.c line 254:
      Condition(in_u == in_l) not true.
    version = varnish-trunk revision b2623920d, vrt api = 6.1
    ident = Linux,4.9.0-3-amd64,x86_64,-jnone,-smalloc,-smalloc,-hcritbit,epoll
    now = 91966.016784 (mono), 1498044684.040222 (real)
    Backtrace:
      0x453ed0: bin/varnishd/varnishd() [0x453ed0]
      0x453ccb: bin/varnishd/varnishd() [0x453ccb]
      0x49b74d: bin/varnishd/varnishd(h2h_decode_bytes+0x5ed) [0x49b74d]
      0x49e3f4: bin/varnishd/varnishd() [0x49e3f4]
      0x49ff10: bin/varnishd/varnishd() [0x49ff10]
      0x49f687: bin/varnishd/varnishd(h2_rxframe+0x547) [0x49f687]
      0x4a12ef: bin/varnishd/varnishd() [0x4a12ef]
      0x4839cc: bin/varnishd/varnishd() [0x4839cc]
      0x483241: bin/varnishd/varnishd() [0x483241]
      0x482eca: bin/varnishd/varnishd() [0x482eca]
    thread = (cache-worker)
    thr.req = 0x7fcc32c46020 {
      vxid = 32831, transport = H2
      step = 0x0,
      req_body = R_BODY_INIT,
      err_code = 1, err_reason = (null),
      restarts = 0, esi_level = 0,
      sp = 0x7fcc3280ea20 {
        fd = 27, vxid = 32831,
        t_open = 1498044683.928865,
        t_idle = 1498044683.929133,
        transport = H2 {
          streams {
            0x00000000 idle  
            0x374cba31 open  
          }
        }
        client = ::1 36260,
        privs = 0x7fcc3280ea88 {
        },
      },
      ws = 0x7fcc32c46208 {
        id = \"req\",
        {s, f, r, e} = {0x7fcc32c48008, +384, (nil), +57328},
      },
      http_conn = 0x7fcc32c46130 {
        fd = 27 (@0x7fcc3280ea38),
        doclose = NULL,
        ws = 0x7fcc32c46208 {
          [Already dumped, see above]
        },
        {rxbuf_b, rxbuf_e} = {0x7fcc32c48168, 0x7fcc32c48188},
        {pipeline_b, pipeline_e} = {(nil), (nil)},
        content_length = 0,
        body_status = none,
        first_byte_timeout = 0.000000,
        between_bytes_timeout = 0.000000,
      },
      http[req] = 0x7fcc32c462a0 {
        ws = (nil) {
        },
        hdrs {
        },
      },
      vmods = {
      },
      flags = {
      },
    },
    thr.busyobj = (nil) {
    },

**Comment by mbgrydeland** [comment]
This seems to be due to unchecked padding decoding in cache_http2_proto.c:h2_rx_headers. The padding length can be larger than the frame size, causing integer underrun, giving an overly large frame size to the hpack decoding.
