### ISSUE TITLE
Assert error in h2_rx_continuation

### ISSUE THREAD

**Issue by daghf** [varnishcache/varnish-cache#2350]
This one also triggered via http2fuzz. No further details yet.

    Error: Child (17319) Panic at: Wed, 21 Jun 2017 11:35:51 GMT
    Assert error in h2_rx_continuation(), http2/cache_http2_proto.c line 620:
      Condition((r2) != 0) not true.
    version = varnish-trunk revision b2623920d, vrt api = 6.1
    ident = Linux,4.9.0-3-amd64,x86_64,-jnone,-smalloc,-smalloc,-hcritbit,epoll
    now = 92233.071132 (mono), 1498044951.094571 (real)
    Backtrace:
      0x453ed0: bin/varnishd/varnishd() [0x453ed0]
      0x453ccb: bin/varnishd/varnishd() [0x453ccb]
      0x49ef76: bin/varnishd/varnishd() [0x49ef76]
      0x49ff10: bin/varnishd/varnishd() [0x49ff10]
      0x49f687: bin/varnishd/varnishd(h2_rxframe+0x547) [0x49f687]
      0x4a12ef: bin/varnishd/varnishd() [0x4a12ef]
      0x4839cc: bin/varnishd/varnishd() [0x4839cc]
      0x483241: bin/varnishd/varnishd() [0x483241]
      0x482eca: bin/varnishd/varnishd() [0x482eca]
      0x7ff60047e494: /lib/x86_64-linux-gnu/libpthread.so.0(+0x7494) [0x7ff60047e494]
    thread = (cache-worker)
    thr.req = 0x7ff5ee8b6020 {
      vxid = 196637, transport = H2
      step = 0x0,
      req_body = R_BODY_INIT,
      err_code = 1, err_reason = (null),
      restarts = 0, esi_level = 0,
      sp = 0x7ff5ee40f020 {
        fd = 24, vxid = 196637,
        t_open = 1498044951.092275,
        t_idle = 1498044951.094419,
        transport = H2 {
          streams {
            0x00000000 idle  
            0x00000001 closed
            0x700598d1 idle  
          }
        }
        client = ::1 38900,
        privs = 0x7ff5ee40f088 {
        },
      },
      ws = 0x7ff5ee8b6208 {
        id = \"req\",
        {s, f, r, e} = {0x7ff5ee8b8008, +2280, (nil), +57328},
      },
      http_conn = 0x7ff5ee8b6130 {
        fd = 24 (@0x7ff5ee40f038),
        doclose = NULL,
        ws = 0x7ff5ee8b6208 {
          [Already dumped, see above]
        },
        {rxbuf_b, rxbuf_e} = {0x7ff5ee8b84e0, 0x7ff5ee8b88ef},
        {pipeline_b, pipeline_e} = {0x7ff5ee8b88e2, 0x7ff5ee8b88ef},
        content_length = 0,
        body_status = none,
        first_byte_timeout = 0.000000,
        between_bytes_timeout = 0.000000,
      },
      http[req] = 0x7ff5ee8b62a0 {
        ws = (nil) {
        },
        hdrs {
        },
      },
      vmods = {
      },
      flags = {
      },
    },
    thr.busyobj = (nil) {
    },

**Comment by Dridi** [comment]
I'd need to check with Martin or look at the code but I think that Varnish currently doesn't support continuations, although the HPACK code itself does. At least last time we discussed this that was the case.
