### ISSUE TITLE
Child process recurrently being restarted

### ISSUE THREAD

**Issue by stefanobaldo** [varnishcache/varnish-cache#2352]
Varnish child process is recurrently being restarted after 10~20h of use, with the following message:

Jun 21 10:58:09 d78ad9ffc67f varnishd[8983]: Child (8991) not responding to CLI, killed it.
Jun 21 10:58:09 d78ad9ffc67f varnishd[8983]: Unexpected reply from ping: 400 CLI communication error (hdr)
Jun 21 10:58:09 d78ad9ffc67f varnishd[8983]: Child (8991) died signal=9
Jun 21 10:58:09 d78ad9ffc67f varnishd[8983]: Child cleanup complete

The following is the `varnishstat -1` output just 1 minute before a restart: 

https://pastebin.com/1dBemmwq

Environment:

- varnish-5.1.2 revision 6ece695
- Debian 8.7 - Debian GNU/Linux 8 (3.16.0)
- Installed using pre-built package from official repo at packagecloud.io
- CPU 2x2.9 GHz
- Mem 3.69 GiB
- Running inside a Docker container
- NFILES=131072
- MEMLOCK=82000

Additional info:

- I need to cache a large number of objets and the cache should last for almost a week, so I have set up a 450G storage space, I don't know if this is a problem;
- I use ban a lot. There was about 10k bans in the system just before the last crash. I really don't know if this is too much or may have anything to do with it;
- No registered CPU spikes (almost always by 30%);
- No panic is reported, the only info I can retrieve is from syslog;
- During all the time, event moments before the crashes, everything is okay and requests are being responded very fast.

**Comment by gquintard** [comment]
Probably not a bug, please come discussed this on the varnish-misc mailing list.
