### ISSUE TITLE
Varnish 5.1.2 use PROXY cann't cache data

### ISSUE THREAD

**Issue by saga1015** [varnishcache/varnish-cache#2358]
I test the arch: hitch 1.4.6---->varnish 5.1.2----->nginx 1.13.2 and
hitch use apln='h2,http/1.1' and write-proxy-v2=on
varnish 5.1.2 use -a :8080,PROXY and default.vcl set backend param .proxy_header=1
nginx set 'listen 81 http2 proxy_protocol'

when I start all test servers ,I use firefox visit https://xxx.xxx.com and use firebug check http header ,I can see X-Firefox-Spdy:h2 ,but no any data be cached by varnish .

why ?please help me ,thank you very very much

**Comment by gquintard** [comment]
not a bug, please use the proper channels to get help: https://varnish-cache.org/support/index.html
