### ISSUE TITLE
Assert error in child_sigserv_handler() segfault on FreeBSD

### ISSUE THREAD

**Issue by michbsd** [varnishcache/varnish-cache#2361]
## Your Environment
* Version used: Varnish 5.1.2 
* Operating System and version: FreeBSD 10.3-REL-p16

## VMODs
* varnish-modules (except tcp) 
* geoip
* digest
* VSF (have already tried to disable this) 

Logging into the admin page on a WP system (/wp-admin) (POST req) will provoke the error.

Syslog:
Jul  5 09:57:36 nsXXXXXX varnishd[72618]: Child (72624) died signal=6
Jul  5 09:57:36 nsXXXXXX varnishd[72618]: Child (72624) Panic at: Wed, 05 Jul 2017 07:57:36 GMT Assert error in child_sigsegv_handler(), mgt/mgt_child.c line 271:   Condition(Segmentation fault by instruction at 0x656e77) not true. version = varnish-5.1.2 revision 6ece695, vrt api = 6.0 ident = FreeBSD,10.3-RELEASE-p16,amd64,-junix,-smalloc,-smalloc,-hcritbit,kqueue now = 14476274.945918 (mono), 1499241455.545207 (real) Backtrace:   0x437d77: <PAN_Init+0x227> at /usr/local/sbin/varnishd   0x464f93: <MCH_Init+0x293> at /usr/local/sbin/varnishd   0x8011c3b37: <pthread_sigmask+0x507> at /lib/libthr.so.3   0x8011c322c: <pthread_getspecific+0xe1c> at /lib/libthr.so.3 thread = (cache-worker) thr.req = 0x0 { }, thr.busyobj = 0x80b0b8020 {   ws = 0x80b0b80a0 {     id = \"bo\",     {s, f, r, e} = {0x80b0b9f60, +952, 0x0, +57496},   },   retries = 0, failed = 0, flags = {do_stream, do_pass, uncacheable},   http_conn = 0x80b0ba2b8 {     fd = 28 (@0x8080330f4),     doclose = NULL,     ws = 0x0 {     },     {rxbuf_b, rxbuf_e}
Jul  5 09:57:36 ns324674 kernel: , rxbuf_e}

```
panic.show:
-----------------------------
Varnish Cache CLI 1.0
-----------------------------
FreeBSD,10.3-RELEASE-p16,amd64,-junix,-smalloc,-smalloc,-hcritbit
varnish-5.1.2 revision 6ece695

Type 'help' for command list.
Type 'quit' to close CLI session.

varnish> panic.show
200
Panic at: Wed, 05 Jul 2017 07:57:36 GMT
Assert error in child_sigsegv_handler(), mgt/mgt_child.c line 271:
  Condition(Segmentation fault by instruction at 0x656e77) not true.
version = varnish-5.1.2 revision 6ece695, vrt api = 6.0
ident = FreeBSD,10.3-RELEASE-p16,amd64,-junix,-smalloc,-smalloc,-hcritbit,kqueue
now = 14476274.945918 (mono), 1499241455.545207 (real)
Backtrace:
  0x437d77: <PAN_Init+0x227> at /usr/local/sbin/varnishd
  0x464f93: <MCH_Init+0x293> at /usr/local/sbin/varnishd
  0x8011c3b37: <pthread_sigmask+0x507> at /lib/libthr.so.3
  0x8011c322c: <pthread_getspecific+0xe1c> at /lib/libthr.so.3
thread = (cache-worker)
thr.req = 0x0 {
},
thr.busyobj = 0x80b0b8020 {
  ws = 0x80b0b80a0 {
    id = \"bo\",
    {s, f, r, e} = {0x80b0b9f60, +952, 0x0, +57496},
  },
  retries = 0, failed = 0, flags = {do_stream, do_pass, uncacheable},
  http_conn = 0x80b0ba2b8 {
    fd = 28 (@0x8080330f4),
    doclose = NULL,
    ws = 0x0 {
    },
    {rxbuf_b, rxbuf_e} = {0x0, 0x0},
    {pipeline_b, pipeline_e} = {0x0, 0x0},
    content_length = 0,
    body_status = none,
    first_byte_timeout = 60.000000,
    between_bytes_timeout = 60.000000,
  },
  director_req = 0x8020d8978 {
    vcl_name = nsXXXX,
    type = backend {
      display_name = xxx_1.nsXXXX,
      ipv4 = 172.16.0.40,
      port = 80,
      hosthdr = 172.16.0.40,
      health = healthy,
      admin_health = probe, changed = 1499241407.120591,
      n_conn = 1,
    },
  },
  director_resp = director_req,
  http[bereq] = 0x80b0b8670 {
    ws = 0x80b0b80a0 {
      [Already dumped, see above]
    },
    hdrs {
      \"POST\",
      \"/_xx/my-account/\",
      \"HTTP/1.1\",
      \"Host: www.xxxxxxxxx.com\",
      \"Content-Length: 142\",
      \"Cache-Control: max-age=0\",
      \"Origin: http://www.xxxxxxxxx.com\",
      \"Upgrade-Insecure-Requests: 1\",
      \"User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36 OPR/46.0.2597.39\",
      \"Content-Type: application/x-www-form-urlencoded\",
      \"Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\",
      \"Referer: http://www.xxxxxxxxx.com/_xx/my-account/\",
      \"Accept-Encoding: gzip, deflate\",
      \"Accept-Language: en-GB,en;q=0.8,en-US;q=0.6,fr;q=0.4,da;q=0.2\",
      \"Cookie: __cfduid=d47345722747f972d37bd930a3b586ea51491570211; ja_cookieconsent_status=true; wp-settings-time-682=1493903055\",
      \"X-Forwarded-Proto: https\",
      \"grace: none\",
      \"X-Varnish: 393224\",
    },
  },
  http[beresp] = 0x80b0b8ae8 {
    ws = 0x80b0b80a0 {
      [Already dumped, see above]
    },
    hdrs {
    },
  },
  objcore[fetch] = 0x8110450c0 {
    refcnt = 2,
    flags = {busy, private},
    exp_flags = {},
    boc = 0x811047080 {
      refcnt = 2,
      state = invalid,
      vary = 0x0,
      stevedore_priv = 0x0,
    },
    exp = {0.000000, 0.000000, 0.000000, 0.000000},
    objhead = 0x8020f5080,
    stevedore = 0x0,
  },
  vcl = {
    name = \"xxx_1\",
    busy = 3,
    discard = 0,
    state = auto,
    temp = warm,
    conf = {
      srcname = {
        \"/usr/local/etc/varnish/xxx.vcl\",
        \"Builtin\",
        \"/usr/local/etc/varnish/security/vsf.vcl\",
        \"/usr/local/etc/varnish/security/build/variables.vcl\",
        \"/usr/local/etc/varnish/security/local.vcl\",
        \"/usr/local/etc/varnish/security/config.vcl\",
        \"/usr/local/etc/varnish/security/rules/protocol.vcl\",
        \"/usr/local/etc/varnish/security/rules/paths.vcl\",
        \"/usr/local/etc/varnish/security/rules/generic.vcl\",
        \"/usr/local/etc/varnish/security/rules/sql.vcl\",
        \"/usr/local/etc/varnish/security/rules/sql.encoded.vcl\",
        \"/usr/local/etc/varnish/security/rules/xss.vcl\",
        \"/usr/local/etc/varnish/security/rules/xss.encoded.vcl\",
        \"/usr/local/etc/varnish/security/rules/demo.vcl\",
        \"/usr/local/etc/varnish/security/rules/php.vcl\",
        \"/usr/local/etc/varnish/security/rules/cmd.vcl\",
        \"/usr/local/etc/varnish/security/rules/restricted-file-extensions.vcl\",
        \"/usr/local/etc/varnish/security/rules/content-encoding.vcl\",
        \"/usr/local/etc/varnish/security/rules/content-type.vcl\",
        \"/usr/local/etc/varnish/security/rules/localfiles.vcl\",
        \"/usr/local/etc/varnish/security/rules/user-agent.vcl\",
        \"/usr/local/etc/varnish/security/build/variables.vcl\",
        \"/usr/local/etc/varnish/security/handlers.vcl\",
      },
    },
  },
  vmods = {
    directors = {Varnish 5.1.2 6ece695, 6.0},
    std = {Varnish 5.1.2 6ece695, 6.0},
    digest = {Varnish 5.1.2 6ece695, 6.0},
    vsthrottle = {Varnish 5.1.2 6ece695, 6.0},
    geoip = {Varnish 5.1.2 6ece695, 6.0},
    vsf = {Varnish 5.1.2 6ece695, 6.0},
    cookie = {Varnish 5.1.2 6ece695, 6.0},
  },
},
```

I have changed IPs, VCL config names and URLs for obvious reasons. 

I can 100% reproduce this error on my staging environment, so let me know if you need anything else.

I will begin disabling VMODs one by one, and see which one might be the culprit. Will update the ticket with findings.

**Comment by michbsd** [comment]
Bug persists without any extra VMODs loaded:

  vmods = {
    directors = {Varnish 5.1.2 6ece695, 6.0},
    std = {Varnish 5.1.2 6ece695, 6.0},
  },

**Comment by michbsd** [comment]
Backtrace:

(gdb) bt
#0  0x000000080150b39a in thr_kill () from /lib/libc.so.7
#1  0x000000080150b386 in raise () from /lib/libc.so.7
#2  0x000000080150b309 in abort () from /lib/libc.so.7
#3  0x00000000004536c6 in pan_ic (func=0x5267ec "child_sigsegv_handler", file=0x5263f2 "mgt/mgt_child.c", line=271, cond=0x7fffdf172340 "Segmentation fault by instruction at 0x656e77", kind=VAS_ASSERT)
    at cache/cache_panic.c:665
#4  0x00000000004a4723 in child_sigsegv_handler (s=11, si=0x7fffdf172f30, c=0x7fffdf172bc0) at mgt/mgt_child.c:269
#5  0x0000000801234b37 in pthread_sigmask () from /lib/libthr.so.3
#6  0x000000080123422c in pthread_getspecific () from /lib/libthr.so.3
#7  <signal handler called>
#8  0x0000000000439c07 in VFP_Open (vc=0x80b848190) at cache/cache_fetch_proc.c:141
#9  0x0000000000458ba3 in vrb_pull (req=0x80b848020, maxsize=-1, func=0x48eec0 <vbf_iter_req_body>, priv=0x80b4b8020) at cache/cache_req_body.c:78
#10 0x0000000000458871 in VRB_Iterate (req=0x80b848020, func=0x48eec0 <vbf_iter_req_body>, priv=0x80b4b8020) at cache/cache_req_body.c:215
#11 0x000000000048ecbf in V1F_SendReq (wrk=0x7fffdf173d40, bo=0x80b4b8020, ctr=0x80b4b8150, onlycached=0) at http1/cache_http1_fetch.c:114
#12 0x00000000004177c4 in vbe_dir_gethdrs (d=0x8024d8838, wrk=0x7fffdf173d40, bo=0x80b4b8020) at cache/cache_backend.c:211
#13 0x0000000000427c65 in VDI_GetHdr (wrk=0x7fffdf173d40, bo=0x80b4b8020) at cache/cache_director.c:82
#14 0x00000000004354f3 in vbf_stp_startfetch (wrk=0x7fffdf173d40, bo=0x80b4b8020) at cache/cache_fetch.c:295
#15 0x0000000000434068 in vbf_fetch_thread (wrk=0x7fffdf173d40, priv=0x80b4b8020) at steps.h:53
#16 0x00000000004824a4 in Pool_Work_Thread (pp=0x807c0e100, wrk=0x7fffdf173d40) at cache/cache_wrk.c:370
#17 0x0000000000481d1c in WRK_Thread (qp=0x807c0e100, stacksize=49152, thread_workspace=2048) at cache/cache_wrk.c:121
#18 0x00000000004819d1 in pool_thread (priv=0x80800fb60) at cache/cache_wrk.c:400
#19 0x000000080122f855 in pthread_create () from /lib/libthr.so.3
#20 0x0000000000000000 in ?? ()

**Comment by michbsd** [comment]
Reverting 3e015a1a8e256c65d4536390b6db098740ca9a5e commit, fixes the issue.

**Comment by fgsch** [comment]
Thanks for confirming it. 

I was not very happy with how that commit moved things around. 
This seems like a good reason to fix #2266 in a different (IMO better) way.

**Comment by michbsd** [comment]
Just for good measure, just built "master" and I confirm that the problem is present there as well.

**Comment by Dridi** [comment]
ping @nigoroll

**Comment by michbsd** [comment]
I am using labels (like #2367) 
I cannot reproduce the error if I load the code directly (without labels)

**Comment by fgsch** [comment]
Closing in favour of #2367.
