### ISSUE TITLE
Upgrading from 4.1.6 to 4.1.7 breaks websocket connection

### ISSUE THREAD

**Issue by covidium** [varnishcache/varnish-cache#2366]
## Current Behavior
Websocket connection fails with: "WebSocket connection to 'wss://...' failed: Error during WebSocket handshake: Unexpected response code: 400"

## Possible Solution
Downgrading to 4.1.6 seems to fix that and I'm not sure if the bug fix from #2337 has something to do with this.
Switching to websocket protocol involves the req.http.connection to be Upgrade. 
https://tools.ietf.org/html/rfc6455#section-1.2

## Your Environment
* Version used: varnish-4.1.7-1.el7.x86_64
* Operating System and version: CentOS Linux release 7.3.1611 (Core)

Thanks.

**Comment by daghf** [comment]
Have a look at https://varnish-cache.org/docs/trunk/users-guide/vcl-example-websockets.html and please use the regular help channels for future follow-up.

http://varnish-cache.org/support/index.html

**Comment by covidium** [comment]
@daghf the varnish code for the websocket connection is the same as described in the document.
This is not a support request but rather a bug introduced in the latest version.

**Comment by daghf** [comment]
I was maybe a bit quick on the trigger there - sorry!

Could you provide `varnishlog` output for a full transaction where you observe this behavior?

**Comment by covidium** [comment]
No problem!

As you can see both requests hit the pipe vcl, that's why I've suggested the bug fix from #2337.

Request with Varnish 4.1.7. With the 4.1.6 can be found after this one.

*   << Request  >> 1016016
-   Begin          req 1016015 rxreq
-   Timestamp      Start: 1499694822.997220 0.000000 0.000000
-   Timestamp      Req: 1499694822.997220 0.000000 0.000000
-   ReqStart       2a02:2f0f:21:101:5a7:ba9c:96ed:2e0e 31816
-   ReqMethod      GET
-   ReqURL         /signalr/connect?transport=webSockets&clientProtocol=1.4&connectionToken=w66wKDqPLxnf5N6MHnISJ6GNQgqFUnhMjuaHxwCn4NkX5j7WWV8yz3TJm6RJyS%2FD%2FoqwnnF3r9lYMYUJBgjjXeeFS4ftH4Y7VheJDtq2IjZKasBuFwpik3pFpPSWSN46&connectionData=%5B%7B%22name%22%3A%22notificatio
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: notifications-staging.domain.tld
-   ReqHeader      Connection: Upgrade
-   ReqHeader      Pragma: no-cache
-   ReqHeader      Cache-Control: no-cache
-   ReqHeader      Upgrade: websocket
-   ReqHeader      Origin: https://staging.domain.tld
-   ReqHeader      Sec-WebSocket-Version: 13
-   ReqHeader      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
-   ReqHeader      Accept-Encoding: gzip, deflate, br
-   ReqHeader      Accept-Language: en-US,en;q=0.8
-   ReqHeader      Cookie: _svtri=4bc4f552-623b-4ca7-836c-39201ed5bfd0; 073abc8e-33a8-11e6-ac61-9e71128cae77=1484901923664; domain.subscription.popup=1; perf_cookie=5811e4f5-e4c4-5a82-e3df-29798f6f3b68; _gat=1; __zlcmid=YmfGc2q95tZrmH; lastPageViewTimestamp=1499694821654
-   ReqHeader      Sec-WebSocket-Key: 9nHWsgcIB5w9sjbruhx4Cg==
-   ReqHeader      Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
-   ReqHeader      X-Forwarded-For: 2a02:2f0f:21:101:5a7:ba9c:96ed:2e0e
-   VCL_call       RECV
-   VCL_return     pipe
-   VCL_call       HASH
-   VCL_return     lookup
-   Link           bereq 1016017 pipe
-   Timestamp      Pipe: 1499694822.997296 0.000077 0.000077
-   Timestamp      PipeSess: 1499694823.000258 0.003039 0.002962
-   PipeAcct       1660 1732 0 445
-   End


At this point the connection is stopped.


With Varnish 4.1.6 the varnishlog looks like this:


*   << Request  >> 131079
-   Begin          req 131078 rxreq
-   Timestamp      Start: 1499695108.437113 0.000000 0.000000
-   Timestamp      Req: 1499695108.437113 0.000000 0.000000
-   ReqStart       2a02:2f0f:21:101:5a7:ba9c:96ed:2e0e 32721
-   ReqMethod      GET
-   ReqURL         /signalr/connect?transport=webSockets&clientProtocol=1.4&connectionToken=9c%2FqyAljk%2BcZjMaqteIA7BiPXVJiRJbXassVCFGmuNgg15q7Qs%2BUGtzJCWz8%2Bqqcijf3JRH%2BNUuAet8IWTaevkBOcdLRUzhl0k0IHXFTkjc1%2BcW9xpS6p7HwbssE%2BcuN&connectionData=%5B%7B%22name%22%3A%22n
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: notifications-staging.domain.tld
-   ReqHeader      Connection: Upgrade
-   ReqHeader      Pragma: no-cache
-   ReqHeader      Cache-Control: no-cache
-   ReqHeader      Upgrade: websocket
-   ReqHeader      Origin: https://staging.domain.tld
-   ReqHeader      Sec-WebSocket-Version: 13
-   ReqHeader      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
-   ReqHeader      Accept-Encoding: gzip, deflate, br
-   ReqHeader      Accept-Language: en-US,en;q=0.8
-   ReqHeader      Cookie: _svtri=4bc4f552-623b-4ca7-836c-39201ed5bfd0; 073abc8e-33a8-11e6-ac61-9e71128cae77=1484901923664; domain.subscription.popup=1; perf_cookie=5811e4f5-e4c4-5a82-e3df-29798f6f3b68; __zlcmid=YmfGc2q95tZrmH; wt3_eid=%3B471144523687402%7C21453298575007
-   ReqHeader      Sec-WebSocket-Key: Sx090GTmXPHbVw+MhMC4Aw==
-   ReqHeader      Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
-   ReqHeader      X-Forwarded-For: 2a02:2f0f:21:101:5a7:ba9c:96ed:2e0e
-   VCL_call       RECV
-   VCL_return     pipe
-   VCL_call       HASH
-   VCL_return     lookup
-   Link           bereq 131080 pipe
-   Timestamp      Pipe: 1499695108.437170 0.000057 0.000057
-   Timestamp      PipeSess: 1499695277.002484 168.565372 168.565314
-   PipeAcct       1670 1762 87 875
-   End

**Comment by Dridi** [comment]
My assumption was that the `wss://` scheme wouldn't be accepted during the request dissection (only http and https AFAIK). So I'll leave a random thought here, built-in should maybe accept non-http schemes and `return (pipe)` if `req.proto !~ "https?"`?

**Comment by daghf** [comment]
@covidium could you try adding `set bereq.http.Connection = req.http.Connection;` in `vcl_pipe` to see if that fixes it as a workaround?

**Comment by covidium** [comment]
@daghf, no, that doesn't work

**Comment by fgsch** [comment]
@covidium could you post the varnishlog output for the entire transaction, not just the client side?

**Comment by benoitvidis** [comment]
Just had the same issue migrating from 4.1.4 to 4.1.7.

Dumping the headers received by the backend, I noticed the `connection` header was not kept in the `bereq` object, moving from `Upgrade` to `close`.

Setting it manually did the trick for me:

```
sub vcl_pipe {
    if (req.http.upgrade) {
        set bereq.http.upgrade = req.http.upgrade;
        set bereq.http.connection = req.http.connection;
    }
}
```

**Comment by fgsch** [comment]
I'm pretty confident this works but we'll wait a few days for @covidium to confirm.

**Comment by storm49152** [comment]
I didn't want to post this _here_ and I couldn't find a way to contact you directly, but since you're waiting for an answer: @covidium should be back this week. I'll give him a nudge about this issue.

**Comment by covidium** [comment]
@fgsch here's the output of varnishlog for frontend and backend:

Added also bereq.http.connection to the vcl_pipe as @benoitvidis suggested made the websocket connection work again.

```
*   << Request  >> 360453
-   Begin          req 360452 rxreq
-   Timestamp      Start: 1501760379.736524 0.000000 0.000000
-   Timestamp      Req: 1501760379.736524 0.000000 0.000000
-   ReqStart       2a02:2f0f:21:101:f85c:f6ec:e9d0:3653 35403
-   ReqMethod      GET
-   ReqURL         /signalr/connect?transport=webSockets&clientProtocol=1.4&connectionToken=aCVJCEdIgcpl7oQ2zhU2COVA9GIbnLnh3GpzlK%2Fmpg5q9yNvblw4%2B8%2FjepJsBSFo%2FCEZsJVR2O%2Fl%2FYaYJv71mEwX9RioRUB2I8qxI7Sev9OBpSjjpqN2JMcchckCiSu%2B&connectionData=%5B%7B%22name%22%3A%22n
-   ReqProtocol    HTTP/1.1
-   ReqHeader      Host: notifications-staging.domain.tld
-   ReqHeader      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0
-   ReqHeader      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
-   ReqHeader      Accept-Language: en-US,en;q=0.5
-   ReqHeader      Accept-Encoding: gzip, deflate, br
-   ReqHeader      Sec-WebSocket-Version: 13
-   ReqHeader      Origin: https://staging.domain.tld
-   ReqHeader      Sec-WebSocket-Extensions: permessage-deflate
-   ReqHeader      Sec-WebSocket-Key: 4F9AGT6aCtkal1wlOvtIWA==
-   ReqHeader      Cookie: _svs=%7B%22e%22%3A%7B%22112%22%3A%7B%22group%22%3A114%2C%22sent%22%3Atrue%7D%2C%22116%22%3A%7B%22group%22%3A118%2C%22sent%22%3Atrue%7D%7D%2C%22p%22%3A%7B%220%22%3A1501760228951%2C%227%22%3A1501760228969%7D%2C%22v%22%3A17%2C%22c%22%3A%7B%221%22%3A
-   ReqHeader      Connection: keep-alive, Upgrade
-   ReqHeader      Pragma: no-cache
-   ReqHeader      Cache-Control: no-cache
-   ReqHeader      Upgrade: websocket
-   ReqHeader      X-Forwarded-For: 2a02:2f0f:21:101:f85c:f6ec:e9d0:3653
-   VCL_call       RECV
-   VCL_return     pipe
-   VCL_call       HASH
-   VCL_return     lookup
-   Link           bereq 360454 pipe
-   Timestamp      Pipe: 1501760379.736597 0.000072 0.000072
-   Timestamp      PipeSess: 1501760379.739535 0.003011 0.002939
-   PipeAcct       1777 1837 0 445
-   End
```

```
*   << BeReq    >> 360454
-   Begin          bereq 360453 pipe
-   BereqMethod    GET
-   BereqURL       /signalr/connect?transport=webSockets&clientProtocol=1.4&connectionToken=aCVJCEdIgcpl7oQ2zhU2COVA9GIbnLnh3GpzlK%2Fmpg5q9yNvblw4%2B8%2FjepJsBSFo%2FCEZsJVR2O%2Fl%2FYaYJv71mEwX9RioRUB2I8qxI7Sev9OBpSjjpqN2JMcchckCiSu%2B&connectionData=%5B%7B%22name%22%3A%22n
-   BereqProtocol  HTTP/1.1
-   BereqHeader    Host: notifications-staging.domain.tld
-   BereqHeader    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0
-   BereqHeader    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
-   BereqHeader    Accept-Language: en-US,en;q=0.5
-   BereqHeader    Accept-Encoding: gzip, deflate, br
-   BereqHeader    Sec-WebSocket-Version: 13
-   BereqHeader    Origin: https://staging.domain.tld
-   BereqHeader    Sec-WebSocket-Extensions: permessage-deflate
-   BereqHeader    Sec-WebSocket-Key: 4F9AGT6aCtkal1wlOvtIWA==
-   BereqHeader    Cookie: _svs=%7B%22e%22%3A%7B%22112%22%3A%7B%22group%22%3A114%2C%22sent%22%3Atrue%7D%2C%22116%22%3A%7B%22group%22%3A118%2C%22sent%22%3Atrue%7D%7D%2C%22p%22%3A%7B%220%22%3A1501760228951%2C%227%22%3A1501760228969%7D%2C%22v%22%3A17%2C%22c%22%3A%7B%221%22%3A
-   BereqHeader    Connection: keep-alive, Upgrade
-   BereqHeader    Pragma: no-cache
-   BereqHeader    Cache-Control: no-cache
-   BereqHeader    X-Forwarded-For: 2a02:2f0f:21:101:f85c:f6ec:e9d0:3653
-   BereqHeader    X-Varnish: 360453
-   BereqUnset     Connection: keep-alive, Upgrade
-   BereqHeader    Connection: close
-   VCL_call       PIPE
-   BereqHeader    upgrade: websocket
-   VCL_return     pipe
-   BackendOpen    51 boot.default 127.0.0.1 8000 127.0.0.1 47104
-   BackendStart   127.0.0.1 8000
-   Timestamp      Bereq: 1501760379.736594 0.000000 0.000000
-   BackendClose   51 boot.default
-   BereqAcct      0 0 0 0 0 0
-   End
```

**Comment by fgsch** [comment]
@covidium thanks for confirming it. FWIW that's also what @daghf suggested 😄
