### ISSUE TITLE
varnishstat xml/json output not showing identity field

### ISSUE THREAD

**Issue by michbsd** [varnishcache/varnish-cache#2377]
## Your Environment

* Version used: varnishd (varnish-trunk revision 042774236)
* Operating System and version: FreeBSD-10.3-REL-p19

This was the behaviour on 5.0-REL:

        <stat>
                <type>MAIN</type>
                <name>uptime</name>
                <value>1968420</value>
                <flag>c</flag>
                <format>d</format>
                <description>Child process uptime</description>
        </stat>

on 5.1.2 : 

	<stat>
		<name>MAIN.uptime</name>
		<value>2208</value>
		<flag>c</flag>
		<format>d</format>
		<description>Child process uptime</description>
	</stat>

Looks like the "type" field has been moved into "ident" field in commit a93c4555ef664ce2835cb43d4cccddd188a27ecf

However it is not listed in xml|json output from varnishstat(1)

**Comment by fgsch** [comment]
@bsdphk has this been done on purpose and we should fix the docs or was an oversight and we should amend the code?

**Comment by michbsd** [comment]
As an example - the munin varnish plugin is no longer working after this change.

**Comment by fgsch** [comment]
Yeah, this breaks a number of things 😞 
Not sure if compatibility was a concern though.

**Comment by fgsch** [comment]
Today's bugwash outcome:

This was intended and I've just updated the docs.
The tools will need to be updated as well to cope with this.
