### ISSUE TITLE
 round_robin.c line 76:   Condition((be) != NULL) not true.

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2378]
commit is 3457dedc45a08a925fea05dc20850882c7049ab1 + a completely unrelated change

SmartOS zone joyent_20160512T071413Z

```
# varnishadm panic.show
Panic at: Fri, 28 Jul 2017 18:02:06 GMT
Assert error in vmod_rr_resolve(), round_robin.c line 76:
  Condition((be) != NULL) not true.
version = varnish-trunk revision bc9b8dd, vrt api = 6.1
ident = -jsolaris,-smalloc,-smalloc,-hcritbit,ports
now = 32949281.910102 (mono), 1501264865.147991 (real)
Backtrace:
  4630c2: /usr/local/sbin/varnishd'pan_backtrace+0x30 [0x4630c2]
  463535: /usr/local/sbin/varnishd'pan_ic+0x23a [0x463535]
  ffffbf7fca8881ac: /tmp/*redacted*-varnish-1/vmod_cache/_vmod_directors.@JPSCEUFIJNAWWTUFAYAXBPQXCNAJSRX'vmod_rr_resolve+0x27f [0xffffbf7fca8881ac]
  4425b9: /usr/local/sbin/varnishd'vdi_resolve+0x14b [0x4425b9]
  442760: /usr/local/sbin/varnishd'VDI_GetHdr+0xde [0x442760]
  44c353: /usr/local/sbin/varnishd'vbf_stp_startfetch+0x2ee [0x44c353]
  44f21a: /usr/local/sbin/varnishd'vbf_fetch_thread+0x366 [0x44f21a]
  482cbd: /usr/local/sbin/varnishd'Pool_Work_Thread+0x4e4 [0x482cbd]
  481d4c: /usr/local/sbin/varnishd'WRK_Thread+0x2bf [0x481d4c]
  482de4: /usr/local/sbin/varnishd'pool_thread+0x96 [0x482de4]
thread = (cache-worker)
thr.req = 0 {
},
thr.busyobj = 15b866030 {
  ws = 15b8660b0 {
    id = \"bo\",
    {s, f, r, e} = {15b86ef70, +512, 0, +225432},
  },
  retries = 0, failed = 0, flags = {do_stream},
  director_req = 940cd0 {
    vcl_name = php_rr,
    type = round-robin {
    },
  },
...
  http[beresp] = 15b866af8 {
    ws = 15b8660b0 {
      [Already dumped, see above]
    },
    hdrs {
    },
  },
  objcore[fetch] = 83984d90 {
    refcnt = 2,
    flags = {busy},
    exp_flags = {},
    boc = 54deb020 {
      refcnt = 2,
      state = req_done,
      vary = 0,
      stevedore_priv = 0,
    },
    exp = {0.000000, 0.000000, 0.000000, 0.000000},
    objhead = 4b5dce50,
    stevedore = 0,
  },
  vcl = {
    name = \"boot\",
    busy = 79,
    discard = 0,
    state = auto,
    temp = warm,
    conf = {
      srcname = {
        \"/etc/varnish/default.vcl\",
        \"Builtin\",
      },
    },
  },
  vmods = {
    std = {Varnish trunk bc9b8dd, 6.1},
    directors = {Varnish trunk bc9b8dd, 6.1},
  },
},

```

**Comment by nigoroll** [comment]
Ref #2024

**Comment by nigoroll** [comment]
OK, it's still the same race, but it's not that obvious. we haven't declared nxt as register, so the compiler is free to use a memory location:
_casually annotated `objdump -S`_
```
        for (u = 0; u < rr->vd->n_backend; u++) {
    8115:       c7 45 e8 00 00 00 00    movl   $0x0,-0x18(%rbp)
    811c:       e9 e8 00 00 00          jmpq   8209 <vmod_rr_resolve+0x2dc>
                nxt = rr->nxt %= rr->vd->n_backend;
    8121:       48 8b 45 f8             mov    -0x8(%rbp),%rax	rr
    8125:       8b 40 10                mov    0x10(%rax),%eax	%eax <- rr->nxt
    8128:       48 8b 55 f8             mov    -0x8(%rbp),%rdx	rr
    812c:       48 8b 52 08             mov    0x8(%rdx),%rdx	vd
    8130:       8b 4a 48                mov    0x48(%rdx),%ecx	%ecx <- n_backend
    8133:       ba 00 00 00 00          mov    $0x0,%edx	%edx <- $0
    8138:       f7 f1                   div    %ecx		nxt = %edx <- remainder
    813a:       48 8b 45 f8             mov    -0x8(%rbp),%rax	rr
    813e:       89 50 10                mov    %edx,0x10(%rax)	rr->nxt <- nxt
    8141:       48 8b 45 f8             mov    -0x8(%rbp),%rax	rr
    8145:       8b 40 10                mov    0x10(%rax),%eax	%eax <- rr->nxt	*BOOM*
    8148:       89 45 ec                mov    %eax,-0x14(%rbp)
                be = rr->vd->backend[nxt];
    814b:       48 8b 45 f8             mov    -0x8(%rbp),%rax	rr
    814f:       48 8b 40 08             mov    0x8(%rax),%rax	vd
    8153:       48 8b 40 50             mov    0x50(%rax),%rax	backend
    8157:       8b 55 ec                mov    -0x14(%rbp),%edx %edx <- nxt
```

**Comment by hermunn** [comment]
The patch b8290db has been back ported as 1ec38efb6.

I am not 100% comfortable with this patch. As it is now the code looks a bit strange, and it not made clear that there is a possible race with the `nxt` variable, and there is a danger that someone in the future might decide to shorten the code to something that is racy. I will ponder this a bit and consider issuing a pull request (where the word `volatile` will be featured).

**Comment by nigoroll** [comment]
@hermunn , delaring `rr->nxt` `volatile` would not change a thing regarding this bug.
`nxt` is a local variable, it cannot race.

**Comment by hermunn** [comment]
@nigoroll , I agree that the local variable `nxt` cannot race and that the patch is correct, but I am not 100% sure it is perfect. The patch is good because it removes the problematic `%=` and `++` on the `rr->nxt` variable (which are not atomic, but requires a read and a write). With this patch only a single write will happen.

What makes me uncomfortable is that a human (not you) might first change the order of `be = rr->vd->backend[nxt];` and `rr->nxt = nxt + 1;` statements, and then decide that the local variable `nxt` can be removed, and thus *should be*, removed. There is no clue for the human to see that the code should stay as it is, partly because the member variable `rr->nxt` is not declared as volatile. It might also be conceivable that a compiler can do the same "optimalization" if the compiler writers get overly eager.

I think making `rr->nxt` volatile and adding a comment (eg. *Careful: Someone else might change the rr->nxt variable, so keep a local copy and make sure it stays within bounds*) will make the code more "future proof" and clearer for the future maintainer. Actually, I think that `rr-nxt` should be declared as `volatile` simply because it *is* volatile, according to the definition.

**Comment by nigoroll** [comment]
@hermunn The history is that we replaced mutexes with rwlocks in the hope of making the director code more scalable. The compromise with this piece of code was that with a read-lock only around advancing `rr->nxt`, we trade a bit of correctness for some scalability: concurrent threads will, with low probability, select the same backend once in a while. If we wanted to avoid that, we should use a write lock or revert back to mutexen.
`volatile` would not have the same effect, it would only make it somehow less likely that two threads choose the same backend. The locking calls already act as memory barriers.
Please don't just declare any variable `volatile` because it "feels right". Your feeling will most likely be plain wrong, see for example https://software.intel.com/en-us/blogs/2007/11/30/volatile-almost-useless-for-multi-threaded-programming/ (IIUC there is a much better reference than this one, but I failed to find it again). So, unless you can explain exactly why `volatile` is correct, it will be most likely be wrong. And it's definitely not a biohazard sign to future code maintainers.

Regarding your worries about code maintenance: I guess we got much harder challenges in the varnish code base, but if you feel like it, add a comment.
Regarding your fears of bad compiler reordering: A compiler must preserve semantics of the code from the perspective of a single thread. The two lines
```
                rr->nxt = nxt + 1;
                be = rr->vd->backend[nxt];
```
however could be swapped, semantics would not change.

At any rate, please add a comment if that makes you happy.
