### ISSUE TITLE
docs error in v4-v5.1

### ISSUE THREAD

**Issue by dmackleffx** [varnishcache/varnish-cache#2380]
## Expected Behavior
i did not check for duplicate, sorry just too busy..

## Current Behavior
config docs example shown at
http://www.varnish-cache.org/docs/5.1/reference/vcl.html#regular-expressions
of
`if (req.http.host !~ "(?i)example.com$") {`
the unescaped period matches any character (except for line terminators)

## Possible Solution
`if (req.http.host !~ "(?i)example\.com$") {`

## Context
potential security risk if this model is followed naively?

## Your Environment
https://regex101.com

**Comment by fgsch** [comment]
Thanks.

Do you want to open a PR?

**Comment by hermunn** [comment]
Back ported 787133e to 4.1 as 610b309cbc6.
