### ISSUE TITLE
init script for restart seems to use status_of_proc incorrectly

### ISSUE THREAD

**Issue by rdonahoe-placed** [varnishcache/varnish-cache#2384]
## Expected Behavior
for restart (sudo service varnish restart),
status_of_proc should check if process exists. 

- If it **does**, stop process and then start the process (checking configtest during start init script)
- if it **doesn't**, check configtest and then start the process

## Current Behavior
- If process **does exist**, check configtest and then try to stop/start process
- If it **doesn't exit**, stop process and then start the process (checking configtest during start init script)

this causes a failure because the configtest will check if the varnish port is open and fail seeing that it is occupied (by current varnish process)

## Possible Solution
```
restart|force-reload)
   #this if statement evaluates as true when process is found
   if status_of_proc -p "${PIDFILE}" "${DAEMON}" "${SERVICE}" 1>/dev/null; then
      echo ${PIDFILE} ${DAEMON} ${SERVICE}
      if ! configtest; then
         log_failure_msg "Syntax check failed, not restarting"
         exit 1
      fi
   fi
```

but it should be like:
```
restart|force-reload)
   #this statement will now resolve correctly by negating the status_of_proc output
   if ! status_of_proc -p "${PIDFILE}" "${DAEMON}" "${SERVICE}" 1>/dev/null; then
      echo ${PIDFILE} ${DAEMON} ${SERVICE}
      if ! configtest; then
         log_failure_msg "Syntax check failed, not restarting"
         exit 1
      fi
   fi
```

## Steps to Reproduce (for bugs)
1. install varnish
2. sudo service varnish start
3. sudo service varnish restart

## Your Environment
ubuntu 14.04

**Comment by denisbr** [comment]
Thanks for reporting this.
Could you file this issue in https://github.com/varnishcache/pkg-varnish-cache instead?
That's the correct place for packaging related issues.

**Comment by fgsch** [comment]
Moved under varnishcache/pkg-varnish-cache
