### ISSUE TITLE
Memory Leaks in Varnish 4.1.8

### ISSUE THREAD

**Issue by sbason** [varnishcache/varnish-cache#2388]
We've been seeing unexplained memory usage increases in our instance of varnish running in production which is causing them to lock up. We decided to investigate the cause so ran Valgrind on varnish without any of our vmods switched on and saw memory leaks in varnish as follows:

```
==1110== LEAK SUMMARY:
==1110==    definitely lost: 462 bytes in 22 blocks
==1110==    indirectly lost: 30 bytes in 5 blocks
==1110==      possibly lost: 0 bytes in 0 blocks
==1110==    still reachable: 651,608 bytes in 2,259 blocks
==1110==         suppressed: 0 bytes in 0 blocks
```
An example of one of the leaks is:
```
==1113== 2 bytes in 1 blocks are still reachable in loss record 1 of 113
==1113==    at 0x4C28BE3: malloc (vg_replace_malloc.c:299)
==1113==    by 0x64DB889: strdup (in /usr/lib64/libc-2.17.so)
==1113==    by 0x45B6C6: tcp_probe (mgt_param_tcp.c:90)
==1113==    by 0x45B7B1: tcp_keep_probes (mgt_param_tcp.c:106)
==1113==    by 0x45B7B1: MCF_TcpParams (mgt_param_tcp.c:117)
==1113==    by 0x40EE96: init_params (mgt_main.c:438)
==1113==    by 0x40EE96: main (mgt_main.c:571)
```
[See full Valgrind output here](https://github.com/varnishcache/varnish-cache/files/1225030/4.1.8.-.No.Vmods.txt)

## Steps to Reproduce 
Run valgrind on Varnish using lkarsten's [varnish-valgrind](https://github.com/lkarsten/varnish-valgrind)

## Environment

* Version used: 4.1.8
* CentOS 7
* https://packagecloud.io/varnishcache/varnish41/el/7/x86_64

**Comment by bsdphk** [comment]
The logfile only seems to contain output from the management process, and the list of undeallocated memory does not seem to contain anything indicating problems.

(I'll admit that managers binheap looks a bit on the large side, but otherwise...)

If you suspect memory leaks is giving you trouble, it would almost certainly be in the worker process rather than the management process.
