### ISSUE TITLE
-a :6081,h2 is broken

### ISSUE THREAD

**Issue by daghf** [varnishcache/varnish-cache#2389]
Specifying `h2` for the listen endpoint picks the h2 transport directly, without the detour via `HTTP1_Session`. 

Opening this ticket as a reminder that we need to make this work at some point, currently we panic on the very first request.

```
Error: Child (23618) died signal=6
Error: Child (23618) Panic at: Thu, 17 Aug 2017 12:30:07 GMT
Assert error in h2_new_session(), http2/cache_http2_session.c line 289:
  Condition(req->err_code == H2_PU_MARKER || req->err_code == H2_OU_MARKER) not true.
version = varnish-trunk revision c21fae9a2, vrt api = 6.1
ident = Linux,4.9.0-3-amd64,x86_64,-jnone,-smalloc,-smalloc,-hcritbit,epoll
now = 19857.612957 (mono), 1502973007.221138 (real)
Backtrace:
  0x454420: bin/varnishd/varnishd() [0x454420]
  0x45421b: bin/varnishd/varnishd() [0x45421b]
  0x4a1840: bin/varnishd/varnishd() [0x4a1840]
  0x48418c: bin/varnishd/varnishd() [0x48418c]
  0x483a01: bin/varnishd/varnishd() [0x483a01]
  0x48368a: bin/varnishd/varnishd() [0x48368a]
  0x7f04714a7494: /lib/x86_64-linux-gnu/libpthread.so.0(+0x7494) [0x7f04714a7494]
  0x7f04711e9aff: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f04711e9aff]
thread = (cache-worker)
thr.req = (nil) {
},
thr.busyobj = (nil) {
},


Debug: Child cleanup complete
```

**Comment by bsdphk** [comment]
It's actually a good question how that should work...

We could do some magic to secretly set H1 and enable H2, but that would also allow H2 on the other socket if people did something like:

    -a :6080,h2 -a:6081,h1

I guess the ultimate fix would be to have a per-lsock H2 flag and enable H2 processing if that or the param is set.

**Comment by justnx** [comment]
I just trapped into that bug on a really huge high traffic site which i migrated to ssl with h2 support and failed.

A switch to seperate define which listener using which protocol would be very useful like its the case in nginx as described here on a Haproxy->Nginx Setup: 
https://ispire.me/http2-ssl-offloading-with-haproxy-and-nginx/

Especially at Setups were:
Varnish 5.1 http2 Varnish support enabled,
Hitch alpn-protos = h2,http1/1

IP:80 listens by Varnish directly and
IP:443 Gets Reverse Proxied via Hitch h2<>Varnish h2 
you will see site dieing in seconds due those session deadlocks.

**Comment by nigoroll** [comment]
@justnx I am not sure if this is the right issue for the problem you experienced. 
Also:
* Wouldn't you just want to use `IP:6086,PROXY`. ?
* I'd recommend to run more current code (master or some 5.2rc)

**Comment by justnx** [comment]
@nigoroll It looked similar but maybe the bug is related to this issue #2418 i watched before.

I didn't used the `-a IP:6086,h2` parameter on my failing setup but the effects reminds me about same issues (haproxy SSL offloading -> nginx, solution see: https://ispire.me/http2-ssl-offloading-with-haproxy-and-nginx/) i encountered when i was pointing/mixing traffic (h1 traffic to h2 or vice versa) to wrong endpoint protocols.

i ran it with this settings:

Hitch:
frontend = "[193.149.38.41]:443+/etc/hitch/certs/certfile.pem"
backend = "[127.0.0.1]:6086"
alpn-protos = "h2, http/1.1"
write-proxy-v2 = on             # Write PROXY header

Varnish 5.1:
-a PUBLIC IP:80 -a 10.1.40.5:8080 -a 127.0.0.1:6086,PROXY \
             -T 10.1.40.5:6082 \
             -f /etc/varnish/myvcl.vcl \
             -p feature=+http2 \
             -p thread_pool_add_delay=2 \
             -p thread_pools=2 \
             -p thread_pool_min=200 \
             -p thread_pool_max=4000 \
             -p syslog_cli_traffic=off \
             -t 120 \
             -S /etc/varnish/secret \
             -s malloc,3G"

**Comment by justnx** [comment]
@nigoroll Btw i just tested with 5.2.0-rc2 and the problem is the same.
