### ISSUE TITLE
std.file_exists does not honor vcl_dir or vcl_path

### ISSUE THREAD

**Issue by PaulKlumpp** [varnishcache/varnish-cache#2400]
## Expected Behavior
We expected std.file_exists to honor vcl_dir which is set, by command line, to /etc/varnish/
So, when we use ```if (std.file_exists("./common/htpasswd")) { .. }``` we think of a file in ```/etc/varnish/common/htpasswd```

## Why don't we just use absolute paths? Context

We don't want to use absolute paths because we are using varnishtest in deployment time. There, we use a temporary vcl_dir to test its next-to-be vcl-rules. But since std.file_exists does not understand relative paths (using absolute paths) we test the next-to-be vcl-rules against a productive file.

## Possible Solution
let std.file_exist honor vcl_dir/vcl_path
OR
have a $vcl_dir or $vcl_path variable that can be used inside VCL.

## Your Environment
* Version used: varnish-4.1.8 revision d266ac5c6
* Operating System and version: 3.10.0-514.26.2.el7.x86_64 #1 SMP Fri Jun 30 05:26:04 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux    RHEL 7.3

**Comment by Dridi** [comment]
`vcl_dir` is an alias for `vcl_path` and as the new name implies it may contain several directories (and since 5.0 the default path does). So using a variable wouldn't make sense. Which leaves us with the first suggested solution that needs to be discussed.

In the mean time, depending on the shape of your VCL, you may be able to isolate the code with absolute file names and provide alternative code in your VTC script.

**Comment by fgsch** [comment]
What about using std.getenv or set a macro and reference it in your vtc?

**Comment by PaulKlumpp** [comment]
Ah. Well... yes. With ```std.getenv``` it could work out.

**Comment by Dridi** [comment]
The environment would work, but they'd need to do the same for production, but it wouldn't change across VCL reloads (or they'd need to make it change somehow). With macros they'd stop using the production VCL in their test, which I think is the goal.

@PaulKlumpp, you could do something like that:

```
varnishtest "include hack"

server s1 { }

shell {
	touch some_file
	echo 'std.file_exists("${tmpdir}/some_file")' >some_file_exists.vcl
}

varnish v1 -cliok "param.set vcl_path ${tmpdir}:/path/to/production/vcl"
varnish v1 -vcl+backend {
	import std;
	sub vcl_recv {
		if (include "some_file_exists.vcl";) {
			return (synth(200));
		}
		return (synth(404));
	}
} -start

client c1 {
	txreq
	rxresp
	expect resp.status == 200
} -run
```

That would mean littering your production VCL with includes for `std.file_exists` calls. You'll probably need to split your VCL anyway for the backend definitions.

**Comment by PaulKlumpp** [comment]
I catch your drift. So, "include" honors vcl_path, and this is how I could work around it. But feels just wrong for me. ;)
The environment-variable is something that I can introduce for production and the testing process that happens before. This will work for me in the mean time. Thanks.

Still, the question/discussion remains: Shall std.file_exists honor vcl_path in the future, just like include does?

**Comment by fgsch** [comment]
You can always do:

```
        if (std.getenv("foo") == "bar") {
                # include staging
        } else if (std.getenv("baz") == "quz") {
                # include prod
        } else {
                # default include
        }
```

In any case, this is not a bug. Either a feature request or something to discuss in the future so might be worth taking it offline.

**Comment by PaulKlumpp** [comment]
I concur, it merely is a feature request now that I know it was not supposed to work like that by design. I will close this _issue_.

Your last suggestion won't fit my needs. In my case, I don't want to introduce more logic just for testing. The whole idea is that the actual production vcl-logic shall be (and is being) tested by the varnish test cases right before going into production.

So I will rather do it like that:
Testing: ```VCL_HOME=$tempdir varnishtest -f $tempdir/default.vcl```
Production will set VCL_HOME with a changed systemd unit environment file.
And in the vcl:
```
if (std.file_exists(std.getenv("VCL_HOME") + "/common/htpasswd")) { .. }
```
Should work. 👍

**Comment by fgsch** [comment]
Sorry, I was a bit hasty on my reply. 
I wrote that snipped and realised I missed your point when I gave it another thought.
