### ISSUE TITLE
(be)req.hash return type

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2402]
reminder issue, so we don't forget to finish with the discussion we had on IRC:
With cd44549432ec809c508b5966c80347e6ff47b582 and 7bfd13b4bf5f1d1307495705278e643b00410d7b, access to the hash value was implemented as a hex-serialized string.
IMHO, the correct data type would be BLOB. The conversion to whatever encoding should be left to a vmod like https://code.uplex.de/uplex-varnish/libvmod-blobcode

**Comment by fgsch** [comment]
Unless there is a specific usecase I don't see the point of returning a BLOB that will require a VMOD call (which we don't have in tree). This change was based on RL input and I consider it (to return a formatted string) to be the norm, not the exception.

**Comment by nigoroll** [comment]
To explain my POV also:
* the native data type of a sha256 hash is BLOB, which has been introduced to do away with (arbitrary) choices of string encodings in the first place.
* Different users will require different encodings, which is why we want to abstract from particular use cases
* for any users not requiring hex encoding, the current decision will imply unnecessary overhead
* The fact that certain functionality is not in tree should not keep us from making the right decision, but rather motivate us to pull stuff into tree

**Comment by fgsch** [comment]
All your points above assume that the hash either will be part of something else or needs to be represented in a different way (likely to be consumed by something else). 
This is not the input I got and the reason I wanted to expose the hash.

I'm all for changing this to a BLOB _if_ there is any need. I found that your proposal comes from the need to generalise rather than something concrete and will punish RL users that don't need this generalisation.

**Comment by nigoroll** [comment]
So what _is_ your use case then?
Other than that, good interface design does need to generalize.

**Comment by fgsch** [comment]
I believe most people expressed the desire to send the hash in a header without having to (re)compute it. As simple as that. I think @rezan might have some other use cases.

Feature creep, code rotting and security issues are also related to unneeded generalisation.

**Comment by rezan** [comment]
The use case I have for this is using the hash as a string and hex encoding works well. The only concern I had was automatically converting all blob types to hex encoding when referenced as a string. I think encoding should be done case by case, and sometimes not at all. However, this could become a non issue with the right code abstractions. Either way, I do not feel very strongly here and as long as we can get the hash as a string (ie header), im good.

**Comment by nigoroll** [comment]
@fgsch totally ok to have the hash in the header, my concerns are simply about the encoding
@rezan can you please explain "right code abstractios"?
Anyway, this seems to becoming too bikesheddish. @bsdphk I think the architect should have the final word.

**Comment by bsdphk** [comment]
I think I'm with Niels here, and this might be the trigger for deciding to import vmod_blob(code)

Related:

I think vmod_blob(code)'s errorhandling should be updated now that we have VRT_fail(), maybe by default call VRT_fail() on invalid input, but have an optional argument which changes that to return NULL ?

**Comment by slimhazard** [comment]
@bsdphk agreed on VRT_fail(). Quite a bit of VMOD error handling should be transitioned to use that, now that it's there, just a matter of doing the transition. (Same thing goes for some of VRT actually.)

@bsdphk by that do you mean taking up a VMOD for binary-to-text conversion in the Varnish distribution? Or that this would be the trigger for someone to import a 3rd-party VMOD for that purpose? (If the former, we better get started right away, if we're trying for September 15.)

**Comment by nigoroll** [comment]
as vmod blob will go in, the bugwash concensus has been to change this to BLOB
@fgsch will you look after this?
