### ISSUE TITLE
VCL_trace is not that helpful any more

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2403]
* does not contain info about the source file (not only vcl input, also `Builtin`)
* thus line numbers may be confusing when looking at the wrong vcl file
* really only makes sense when looking at `VRT_count()` statements in the c-code

**Comment by Dridi** [comment]
Related thread: https://varnish-cache.org/lists/pipermail/varnish-misc/2017-August/026100.html

**Comment by nigoroll** [comment]
summoning @xcir

**Comment by xcir** [comment]
Copy from misc-ML post.(little change)

I thought 2 pattern solution.

- Add vcl source index in vcl_trace.
https://github.com/xcir/varnish-cache/commit/2138ccf0fbfec22b8e7f8e6511984aa28136b84b

```
   32770 VCL_trace      c 1 2.3.3
   32770 VCL_trace      c 2 2.4.5
                          | | | |
                          | | | +---- VCL program line position
                          | | +------ VCL program line number
                          | +-------- VCL program source index
                          +---------- VCL trace point index
```

I think this is simple.
But, VSL format is changed.

- Add -t(trace) option in vcl.show
https://github.com/xcir/varnish-cache/commit/d22fa4d4e8da56405ee690904c2dfa27a629f082

```
   $ sudo varnishadm vcl.show -t boot
   index src  line  pos token
       1   2     3    3 "if"
       2   2     4    5 "std.log"
   ...
      36   1   189    5 "return"
      37   1   193    5 "return"
```


I can identify the line by using vcl.show -v output and either commit.

```
$ sudo varnishadm vcl.show -v boot|grep VCL.SHOW
// VCL.SHOW 0 1127 /etc/varnish/default.vcl
// VCL.SHOW 1 5294 Builtin
            |  |    |
            |  |    +------ VCL source name
            |  +----------- VCL length
            +-------------- VCL program source index  **use this
```

**Comment by bsdphk** [comment]
Now that we can switch vcls,  we probably also need to record which VCL we're talking about in the first place ?

**Comment by gquintard** [comment]
As said on -misc, I like the idea of adding the source index to the VSL. It's simple and only add a minimal overhead to an output that's deactivated by default.

Breaking the API isn't an issue in my opinion because since it's a little known/used one anyway, and we are switching to a major, now's the right time.

**Comment by Dridi** [comment]
Switching VCLs via `return(vcl(label))` doesn't make this problem new, switching VCL with `vcl.use` is already a problem regarding which code was traced when a log dump is analyzed at rest. If that is not already the case, we probably also need a unique id because the VCL names can be reused once discarded.

**Comment by xcir** [comment]
Ahh...Sorry, I forgot label...
I added configname to first field.

https://github.com/varnishcache/varnish-cache/compare/master...xcir:patch/modify_vcl_trace?expand=1
```
#use label
$ sudo /var/opt/varnish-patch/bin/varnishlog -ivcl_trace -graw
     32770 VCL_trace      c main 1 2.3.3
     32770 VCL_trace      c main 2 2.4.5
     32770 VCL_trace      c main 3 2.6.1
     32770 VCL_trace      c main 4 0.23.3
     32770 VCL_trace      c lt 1 0.9.3
     32770 VCL_trace      c lt 2 1.38.5
                             | | |  | |
                             | | |  | +- VCL program line position
                             | | |  +---- VCL program line number
                             | | +------- VCL program source index
                             | +---------- VCL trace point index
                             +------------- VCL configname

#vcl reload
# sudo /var/opt/varnish-patch/bin/varnishlog -ivcl_trace -graw                                                      3 VCL_trace      b boot 28 1.142.5
         3 VCL_trace      b boot 29 1.143.9
         3 VCL_trace      b boot 30 1.145.5
...
         2 VCL_trace      c boot 26 1.111.5
         0 VCL_trace      - vcl_root_5e6cf922-6b3e-472c-8f77-70e1a0eb8383 36 1.189.5  #reload
         5 VCL_trace      c vcl_root_5e6cf922-6b3e-472c-8f77-70e1a0eb8383 1 2.3.3
...
         5 VCL_trace      c vcl_root_5e6cf922-6b3e-472c-8f77-70e1a0eb8383 5 1.38.5

```

**Comment by bsdphk** [comment]
That works for me.

**Comment by nigoroll** [comment]
FTR: polished in ad82dbbce519eb496ec672bbb8bb7a08acf0cd42
