### ISSUE TITLE
keep req.backend_hint across restarts?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2405]
We clear req.backend_hint when restarting https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishd/cache/cache_req_fsm.c#L727
This complicates the #1799 workaround (the workaround vcl as given only works with `bereq.backend` being set on the backend side) and may have other drawbacks.
On the other hand, this would be a breaking change, so if we decide to make the change, we'd want it in a major release.

**Comment by nigoroll** [comment]
Sorry for the wrong reference in the commit message.

**Comment by nigoroll** [comment]
bugwash notes:

The proposal is that restart and retry should keep all of the `req`/`bereq` state except for `req.restarts` and `bereq.retries`.

Please review this proposal before next bugwash.

side issue `std.rollback()` (_not_ the scope of this ticket):
* documentation needs to be improved
* rollback does not play with vmods keeping references to objects on the workspace
* known, but not yet resolved - probably to be solved with the vcl variables/objects/scope rework

**Comment by Dridi** [comment]
I'd like to see a `VRT_Reset` with `VRT_Rollback`'s current behavior and have the latter only roll back `req`/`bereq`, leaving the workspace alone. Or even a new VRT symbol to avoid confusion, eg. `VRT_RollbackHttp`.

**Comment by nigoroll** [comment]
bugwash conclusion: Yes, implement restart and retry should keep all of the `req`/`bereq` state except for `req.restarts`, `bereq.retries` and `*.xid`.
More work on rollback/reset to follow later, maybe by @Dridi @slimhazard or myself

**Comment by nigoroll** [comment]
#2447 addresses `restart` only, not yet `retry`
