### ISSUE TITLE
Lift artificial name/ident limits

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2406]
Can I directly take care of these now that VSC names are no longer limited?

Retire `MAX_BACKEND_NAME`:

https://github.com/varnishcache/varnish-cache/blob/5d713b2d8a796c6d21c2066d8ef1e0beab690dd4/lib/libvcc/vcc_backend.c#L472-L480

Turn `stevedore->ident` into a pointer:

https://github.com/varnishcache/varnish-cache/blob/5d713b2d8a796c6d21c2066d8ef1e0beab690dd4/bin/varnishd/storage/storage.h#L122

https://github.com/varnishcache/varnish-cache/blob/5d713b2d8a796c6d21c2066d8ef1e0beab690dd4/bin/varnishd/storage/mgt_stevedore.c#L177-L185

I will look for other occurrences too, but those were the two I took note of while working on unrelated tickets.

**Comment by bsdphk** [comment]
Please do some extremesize testing to see that nothing else breaks.
