### ISSUE TITLE
return(miss) in vcl_hit acts like a Hit-For-Pass

### ISSUE THREAD

**Issue by rezan** [varnishcache/varnish-cache#2410]
I have run into a few scenarios where we are forcing a miss on a hit and sometimes that ends up as a pass. Normally this is done when the object is stale (grace) and that seems to work as expected. However, if you do this while the object is fresh (obj.ttl > 0s), then you get a pass. This is essentially a HFP as many clients will start hitting the backend and responses will not update the object.

## Expected Behavior
Normal miss behavior. A single backend request with possible cache update.

## Current Behavior
Pass

## Steps to Reproduce (for bugs)
VTC: https://gist.github.com/rezan/df7f30e994bbe5314220f42b38d6b651

## Context
VCL configuration where we want to escape from a hit in `vcl_hit`.

**Comment by carlosabalde** [comment]
Is it possible this behaviour is related with https://github.com/varnishcache/varnish-cache/issues/1799?

**Comment by rezan** [comment]
Looks like it.
