### ISSUE TITLE
rewrite pointer comparisons to uintptr_t ?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2415]
Biased summary of an IRC discussion triggered by a comment of @fgsch in #2132
* Reference for c11 is https://port70.net/~nsz/c/c11/n1570.html#6.5.8
* This suggests that by the c standard `WS_Inside()` and other functions / macros may show undefined behavior
* My understanding is that this is only relevant for exotic architectures and that varnish code asserts a modern architecture with a single, continuous address space anyway
* As suggested by @Dridi, we should consider casting to `uintptr_t` for comparisons, though -- Ref: https://docs.oracle.com/cd/E19120-01/open.solaris/816-5138/convert-10/index.html

**Comment by bsdphk** [comment]
I'm sorry, but I don't see it.

Anything which is inside a workspace, ended up there through the conversion of a `char *` pointer from `struct ws` to pointer to whatever type the object think it is.

Casting that object pointer through a `const void*` back to `const char*` will give the same pointer again and all architectures Varnish will ever care about.

I don't think I have ever heard about a computer where "char-memory" could not hold larger types, given suitable attention to alignment and padding, and all malloc(3) implementations I have ever seen would explode on such an architecture.
