### ISSUE TITLE
VAV_Parse storage, varnish segment object and maps leaked on vsm_delset()

### ISSUE THREAD

**Issue by fgsch** [varnishcache/varnish-cache#2416]
Seen on master rev 58057145d.

**Comment by bsdphk** [comment]
ehhh. what ?

**Comment by fgsch** [comment]
In `VSM_Destroy()` we call `vsm_delset()` to destroy the sets.
Within `vsm_delset()` we don't delete the segments, thus leaking the allocated vsm_seg object, the return from `VAV_Parse()` and the maps. 
This might be related to the **XXX: delete segments** comment in that function.
