### ISSUE TITLE
Assert error in VSMW_New() on varnishd 5.2.0-rc1 startup (EL7)

### ISSUE THREAD

**Issue by denisbr** [varnishcache/varnish-cache#2417]
While building packages for 5.2.0-rc1 I get an issue on RHEL7 / CentOS7 when starting varnishd, either using the same ``varnish.service`` systemd unit as in 5.1, or when starting with ``/usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m``.

The error message is:

```
Debug: Platform: Linux,3.10.0-514.21.2.el7.x86_64,x86_64,-junix,-smalloc,-smalloc,-hcritbit
Debug: Child (19827) Started
CLI result = 400
Error: Child (19827) Pushing vcls failed:
CLI communication error (hdr)
Debug: Stopping Child
Error: Child (19827) died signal=6
Info: Child (19827) said Assert error in VSMW_New(), vsmw.c line 291:
Info: Child (19827) said   Condition(fd >= 0) not true.
Info: Child (19827) said   errno = 13 (Permission denied)
Info: Child (19827) said Wrong turn in child_signal_handler(), mgt/mgt_child.c line 280: Signal 6 (Aborted) received at 0x3e200004d73 si_code -6
Info: Child (19827) said   errno = 13 (Permission denied)
Debug: Child cleanup complete
```

Note that when testing a package on Ubuntu 16.04, built off the same dist-tarball, I do not get the same error, and varnishd starts successfully, not sure why.
I've attached an strace log [strace.log.txt](https://github.com/varnishcache/varnish-cache/files/1277365/strace.log.txt)

## Expected Behavior

varnishd should start without the assert.

## Current Behavior

varnishd does not start due to the assert error. 

## Steps to Reproduce (for bugs)
1. Build 5.2.0-rc1 on RHEL7/CentOS7 (x86_64)
2. Start varnishd
3. Crash

## Your Environment
* Version used: 5.2.0-rc1
* Operating System and version: CentOS7
* Source of binary packages used (if any) staging repository

**Comment by bsdphk** [comment]
This looks like some kind of permissions problem but the strace attachment doesn't seem to contain the system calls made by the worker process, so it is a bit hard to guess what exactly goes wrong.

Can you rerun the strace so it captures child processes ?

**Comment by denisbr** [comment]
Here is an strace with -f.
I have the environment ready for any other tests / data if need be.
[strace_-f.log.txt](https://github.com/varnishcache/varnish-cache/files/1280372/strace_-f.log.txt)

**Comment by michbsd** [comment]
Just a "me too" - on FreeBSD 10.3-REL

# /usr/local/sbin/varnishd -f /usr/local/etc/varnish/default.vcl
Debug: Platform: FreeBSD,10.3-RELEASE-p16,amd64,-junix,-smalloc,-smalloc,-hcritbit
Debug: Child (84870) Started
CLI result = 400
Error: Child (84870) Pushing vcls failed:
CLI communication error (hdr)
Debug: Stopping Child
Error: Child (84870) died signal=6
Info: Child (84870) said Assert error in VSMW_New(), vsmw.c line 291:
Info: Child (84870) said   Condition(fd >= 0) not true.
Info: Child (84870) said   errno = 13 (Permission denied)
Info: Child (84870) said Wrong turn in child_signal_handler(), mgt/mgt_child.c line 280: Signal 6 (Abort trap) received at 0x0 si_code 65543
Info: Child (84870) said   errno = 13 (Permission denied)
Debug: Child cleanup complete

basic default.vcl:
cat /usr/local/etc/varnish/default.vcl
vcl 4.0;

/* We have to have a backend, even if we do not use it */
backend default { .host = "127.0.0.1"; }
