### ISSUE TITLE
Assert error with 5.2.0 (using labels) 

### ISSUE THREAD

**Issue by michbsd** [varnishcache/varnish-cache#2432]
## Your Environment

* Version used: Varnish 5.2.0
* Operating System and version: FreeBSD 10.3-REL-p19

## Syslog
Sep 18 11:17:27 nsXXXXXX varnishd[22424]: Child (26146) Panic at: Mon, 18 Sep 2017 09:17:27 GMT Assert error in vcl_get(), cache/cache_vcl.c line 274:   Condition(VCL_WARM(*vcc)) not true. version = varnish-5.2.0 revision NOGIT, vrt api = 6.1 ident = FreeBSD,10.3-RELEASE-p19,amd64,-junix,-smalloc,-smalloc,-hcritbit,kqueue now = 6040441.389303 (mono), 1505726246.716116 (real) Backtrace:   0x43737a: <pan_ic+0x17a> at /usr/local/sbin/varnishd   0x47c91c: <VAS_Fail+0x6c> at /usr/local/sbin/varnishd   0x442c55: <vcl_get+0x225> at /usr/local/sbin/varnishd   0x443abc: <VRT_vcl_select+0x3c> at /usr/local/sbin/varnishd   0x814b46525: <VGC_function_vcl_recv+0xd5> at vcl_main_1.1505723536.157132387/vgc.so   0x445147: <vcl_call_method+0x387> at /usr/local/sbin/varnishd   0x4462d6: <VCL_recv_method+0x66> at /usr/local/sbin/varnishd   0x43bf11: <CNT_Request+0x1581> at /usr/local/sbin/varnishd   0x457af1: <http1_req+0x361> at /usr/local/sbin/varnishd thread = (cache-worker) thr.req = 0x80b0b8020 {   vxid = 10, transport = HTTP/
Sep 18 11:17:27 nsXXXXXX kernel: rt = HTTP/
Sep 18 11:17:33 nsXXXXXX kernel: pid 26154 (varnishd), uid 429: exited on signal 6

## panic.show
varnish> panic.show
200
```
Panic at: Mon, 18 Sep 2017 09:00:45 GMT
Assert error in vcl_get(), cache/cache_vcl.c line 274:
  Condition(VCL_WARM(*vcc)) not true.
version = varnish-5.2.0 revision NOGIT, vrt api = 6.1
ident = FreeBSD,10.3-RELEASE-p19,amd64,-junix,-smalloc,-smalloc,-hcritbit,kqueue
now = 6039439.244144 (mono), 1505725244.570957 (real)
Backtrace:
  0x43737a: <pan_ic+0x17a> at /usr/local/sbin/varnishd
  0x47c91c: <VAS_Fail+0x6c> at /usr/local/sbin/varnishd
  0x442c55: <vcl_get+0x225> at /usr/local/sbin/varnishd
  0x443abc: <VRT_vcl_select+0x3c> at /usr/local/sbin/varnishd
  0x814d0b525: <VGC_function_vcl_recv+0xd5> at vcl_main_1.1505723536.157132387/vgc.so
  0x445147: <vcl_call_method+0x387> at /usr/local/sbin/varnishd
  0x4462d6: <VCL_recv_method+0x66> at /usr/local/sbin/varnishd
  0x43bf11: <CNT_Request+0x1581> at /usr/local/sbin/varnishd
  0x457af1: <http1_req+0x361> at /usr/local/sbin/varnishd
thread = (cache-worker)
thr.req = 0x80b8e8020 {
  vxid = 196857, transport = HTTP/1 {
    state = HTTP1::Proc
  }
  step = R_STP_RECV,
  req_body = R_BODY_NONE,
  restarts = 0, esi_level = 0,
  sp = 0x80bc30c20 {
    fd = 27, vxid = 196856,
    t_open = 1505725244.563564,
    t_idle = 1505725244.563564,
    transport = HTTP/1 {
      state = HTTP1::Proc
    }
    client = 90.87.241.123 61170,
    privs = 0x80bc30c88 {
    },
  },
  worker = 0x7fffde635e40 {
    stack = {0x7fffde636000 -> 0x7fffde62a000},
    ws = 0x7fffde635ec0 {
      id = \"wrk\",
      {s, f, r, e} = {0x7fffde635230, +0, 0x0, +2040},
    },
    VCL::method = inside RECV,
    VCL::return = 0x0,
    VCL::methods = {RECV},
  },
  ws = 0x80b8e8208 {
    id = \"req\",
    {s, f, r, e} = {0x80b8ea008, +872, 0x0, +57328},
  },
  http_conn = 0x80b8e8130 {
    fd = 27 (@0x80bc30c38),
    doclose = NULL,
    ws = 0x80b8e8208 {
      [Already dumped, see above]
    },
    {rxbuf_b, rxbuf_e} = {0x80b8ea008, 0x80b8ea316},
    {pipeline_b, pipeline_e} = {0x0, 0x0},
    content_length = -1,
    body_status = none,
    first_byte_timeout = 0.000000,
    between_bytes_timeout = 0.000000,
  },
  http[req] = 0x80b8e82a0 {
    ws = 0x80b8e8208 {
      [Already dumped, see above]
    },
    hdrs {
      \"GET\",
      \"/_pw/acc\",
      \"HTTP/1.1\",
      \"Connection: keep-alive\",
      \"User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36\",
      \"Upgrade-Insecure-Requests: 1\",
      \"Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8\",
      \"Accept-Encoding: gzip, deflate\",
      \"Accept-Language: en-GB,en;q=0.8,en-US;q=0.6,fr;q=0.4,da;q=0.2,de;q=0.2\",
      \"Cookie: _ga=GA1.2.913875026.1477557693; __cfduid=de0500152e34f528d9a8241a2359867e71504262634\",
      \"X-Forwarded-Proto: https\",
      \"X-Forwarded-For: 90.87.123.123\",
      \"host: www.myhost.com\",
    },
  },
  vcl = {
    name = \"jaf_1\",
    busy = 1,
    discard = 0,
    state = auto,
    temp = cold,
    conf = {
      srcname = {
        \"/usr/local/etc/varnish/jaf.vcl\",
        \"Builtin\",
        \"/usr/local/etc/varnish/security/vsf.vcl\",
        \"/usr/local/etc/varnish/security/build/variables.vcl\",
        \"/usr/local/etc/varnish/security/local.vcl\",
        \"/usr/local/etc/varnish/security/config.vcl\",
        \"/usr/local/etc/varnish/security/rules/protocol.vcl\",
        \"/usr/local/etc/varnish/security/rules/paths.vcl\",
        \"/usr/local/etc/varnish/security/rules/generic.vcl\",
        \"/usr/local/etc/varnish/security/rules/sql.vcl\",
        \"/usr/local/etc/varnish/security/rules/sql.encoded.vcl\",
        \"/usr/local/etc/varnish/security/rules/xss.vcl\",
        \"/usr/local/etc/varnish/security/rules/xss.encoded.vcl\",
        \"/usr/local/etc/varnish/security/rules/demo.vcl\",
        \"/usr/local/etc/varnish/security/rules/php.vcl\",
        \"/usr/local/etc/varnish/security/rules/cmd.vcl\",
        \"/usr/local/etc/varnish/security/rules/restricted-file-extensions.vcl\",
        \"/usr/local/etc/varnish/security/rules/content-encoding.vcl\",
        \"/usr/local/etc/varnish/security/rules/content-type.vcl\",
        \"/usr/local/etc/varnish/security/rules/localfiles.vcl\",
        \"/usr/local/etc/varnish/security/rules/user-agent.vcl\",
        \"/usr/local/etc/varnish/security/build/variables.vcl\",
        \"/usr/local/etc/varnish/security/handlers.vcl\",
      },
    },
  },
  vmods = {
    directors = {Varnish 5.2.0 NOGIT, 0.0},
    std = {Varnish 5.2.0 NOGIT, 0.0},
    digest = {Varnish 5.2.0 NOGIT, 0.0},
    vsthrottle = {Varnish 5.2.0 NOGIT, 0.0},
    geoip = {Varnish 5.2.0 NOGIT, 0.0},
    vsf = {Varnish 5.2.0 NOGIT, 0.0},
    cookie = {Varnish 5.2.0 NOGIT, 6.1},
  },
  flags = {
  },
},
thr.busyobj = 0x0 {
},
```

Please let me know if you require more information.

**Comment by michbsd** [comment]
I cannot reproduce the problem when I load the VCL directly (without using labels)

**Comment by Dridi** [comment]
Looking at the code I thought that this panic was caused by the lack of error handling in `mcf_vcl_label`:

```c
static void __match_proto__(cli_func_t)
mcf_vcl_label(struct cli *cli, const char * const *av, void *priv)
{
[...]
        (void)mgt_vcl_setstate(cli, vpt, VCL_STATE_WARM);
        if (!MCH_Running())
                return;

        i = mgt_cli_askchild(&status, &p, "vcl.label %s %s\n", av[2], av[3]);
        if (i) {
                VCLI_SetResult(cli, status);
                VCLI_Out(cli, "%s", p);
        }
        free(p);
}
```

A warmup may fail, and this needs to be handled, so I tried the following test case:

```
varnishtest "label a cold vcl"

server s1 { } -start

varnish v1 -vcl+backend {
	import debug; # can fail a VCL warmup

	sub vcl_recv {
		return (synth(200));
	}
} -start

# a dummy vcl to freely use vcl1
varnish v1 -vcl+backend { }

# the magic parameter that fails a VCL warmup
varnish v1 -cliok "param.set max_esi_depth 42"

varnish v1 -cliok "vcl.state vcl1 cold"
varnish v1 -clierr 300 "vcl.label label1 vcl1"

# stop failing VCL warmups
varnish v1 -cliok "param.set max_esi_depth 1"

varnish v1 -vcl+backend {
	sub vcl_recv {
		return (vcl(label1));
	}
}

client c1 {
	txreq
	rxresp
	expect resp.status == 200
} -run
```

Quite surprisingly it passes. The CLI error is caused by the aforementioned lack of error handling, so the `vcl.label` command inherits the internal warmup error but still proceeds with the labeling. This is why `label1` can then be used by `vcl3`. So I accidentally found a different bug when I was certain I was on the right trail...

I will investigate this further but here are some tasks to keep in mind:

- [ ] `AZ(...)` all VCL cooldowns as they aren't allowed to fail
- [ ] error handling for all VCL warmups as they may fail
- [ ] check how setting "auto" should behave (invariant or error handling)
- [ ] a proper test case that fails once the bug is fixed

**Comment by Dridi** [comment]
I looked one function below and had a wut moment: why are we unconditionally setting VCLs back to auto?

And I was able to reproduce @michbsd's panic:

```
varnishtest "label going cold"

server s1 { } -start

varnish v1 -cliok "param.set vcl_cooldown 1"

varnish v1 -vcl+backend {
	sub vcl_recv {
		return (synth(200));
	}
} -start

varnish v1 -cliok "vcl.label label1 vcl1"

varnish v1 -vcl+backend {
	sub vcl_recv {
		return (vcl(label1));
	}
}

# let the VCL poker trigger enough times to get
# an occasion to update vcl1's state
delay 3

client c1 {
	txreq
	rxresp
	expect resp.status == 200
} -run
```

**Comment by Dridi** [comment]
What happens is that given enough time (give or take 2-3 times `vcl_cooldown` seconds, depending on timing) the VCL poker may turn labels cold under our feet by indiscriminately setting them to `auto`. Before labels were introduced, it targeted all VCLs except the active one. I don't know yet why this regression appeared in 5.2, but 5.1 doesn't seem bothered by the VCL poker.

@bsdphk, what is the exact role of `mgt_vcl_poker`? Why do we periodically turn VCLs back to `auto` even when a user decides that a VCL should stay warm?

**Comment by bsdphk** [comment]
The poker doesn't set VCLs back to auto, it (is supposed to) turn AUTO to COLD after the timeout.

Passing AUTO as argument is a flag asking for this special behaviour (see mgt_vcl_setstate())

**Comment by Dridi** [comment]
I know what `vcl.state <vcl> auto` does, I'll make sure the poker does what it is supposed to do, and take care of the other things I highlighted.

Also, instead of doing changes in the manager and then in the child when it's running, I will make sure we first ask the running child to make state changes before we apply them to the manager.

**Comment by Dridi** [comment]
Contrary to my intuition after my first look, 606d48563464df01acb692a7a57188bf1eaa8d2c is actually the origin of the regression. I'd like to discuss the locking of `vcl_get` with @mbgrydeland separately from this issue.

I have taken care of all the bullet points in a patch series I'm about to push, except AZ'ing the cooldowns since I worked on the manager side for both this bug and #2433.
