### ISSUE TITLE
Cannot run multiple Instances of Varnish with 5.2.0 (did work until 5.1.3)

### ISSUE THREAD

**Issue by pjweder** [varnishcache/varnish-cache#2437]
## Expected Behavior
We are running multiple instances of Varnish on the same Host.

APP1 = 6081,6082
APP2 = 7081,7082
APP3 = 7091,7092
...

Until Varnish 5.1.3-1 this was no problem.

## Current Behavior
If any instance is started the other varnish instances can't start because varnish is already started.
Only one Varnish is possible to run on the Host, all other instances highlight the PID of the started
instance and fail to start.

These happens also when I use "-P" flag:

ExecStart=/usr/sbin/varnishd -j unix,user=vcache -P /var/run/varnish-app1.pid -F -a :6081 -T localhost:6082 -f /etc/varnish/app1.vcl -S /etc/varnish/secret -s malloc,4096m

$ cat /var/run/varnish-app1.pid 
902

ExecStart=/usr/sbin/varnishd -j unix,user=vcache -P /var/run/varnish-app2.pid -F -a :7081 -T localhost:7082 -f /etc/varnish/app2.vcl -S /etc/varnish/secret -s malloc,4096m

varnishd[2096]: Error: Varnishd is already running (pid=902)

## Current Solution
Downgrading to 5.1.3-1

**Comment by Dridi** [comment]
Since you are using systemd, can you share your three service files?

**Comment by pjweder** [comment]
[Unit]
Description=Varnish HTTP accelerator
Documentation=https://www.varnish-cache.org/docs/5.1/ man:varnishd
 
[Service]
Type=simple
LimitNOFILE=131072
LimitMEMLOCK=82000
ExecStart=/usr/sbin/varnishd -j unix,user=vcache -P /var/run/varnish-app1.pid -F -a :6081 -T localhost:6082 -f /etc/varnish/app1.vcl -S /etc/varnish/secret -s malloc,4096m
ExecReload=/usr/share/varnish/reload-vcl
ProtectSystem=full
ProtectHome=true
PrivateTmp=true
PrivateDevices=true
 
[Install]
WantedBy=multi-user.target


[Unit]
Description=Varnish HTTP accelerator
Documentation=https://www.varnish-cache.org/docs/5.1/ man:varnishd
 
[Service]
Type=simple
LimitNOFILE=131072
LimitMEMLOCK=82000
ExecStart=/usr/sbin/varnishd -j unix,user=vcache -P /var/run/varnish-app2.pid -F -a :7081 -T localhost:7082 -f /etc/varnish/app2.vcl -S /etc/varnish/secret -s malloc,4096m
ExecReload=/usr/share/varnish/reload-vcl
ProtectSystem=full
ProtectHome=true
PrivateTmp=true
PrivateDevices=true
 
[Install]
WantedBy=multi-user.target


[Unit]
Description=Varnish HTTP accelerator
Documentation=https://www.varnish-cache.org/docs/5.1/ man:varnishd
 
[Service]
Type=simple
LimitNOFILE=131072
LimitMEMLOCK=82000
ExecStart=/usr/sbin/varnishd -j unix,user=vcache -P /var/run/varnish-app3.pid -F -a :7091 -T localhost:7092 -f /etc/varnish/app3.vcl -S /etc/varnish/secret -s malloc,4096m
ExecReload=/usr/share/varnish/reload-vcl
ProtectSystem=full
ProtectHome=true
PrivateTmp=true
PrivateDevices=true
 
[Install]
WantedBy=multi-user.target

**Comment by bsdphk** [comment]
You need to pass the three instances different -n arguments

**Comment by pjweder** [comment]
Yes, this did work:

`[Unit]
Description=Varnish HTTP accelerator
Documentation=https://www.varnish-cache.org/docs/5.1/ man:varnishd

[Service]
Type=simple
LimitNOFILE=131072
LimitMEMLOCK=82000
ExecStart=/usr/sbin/varnishd -j unix,user=vcache -n varnish-app2 -F -a :7081 -T localhost:7082 -f /etc/varnish/app2.vcl -S /etc/varnish/secret -s malloc,4096m
ExecReload=/usr/share/varnish/reload-vcl
ProtectSystem=full
ProtectHome=true
PrivateTmp=true
PrivateDevices=true

[Install]
WantedBy=multi-user.target`

Thank you!

**Comment by fgsch** [comment]
Just to clarify, this was working on 5.1.3?

**Comment by pjweder** [comment]
Yes, this was working before. After Upgrading to 5.2.0 I had to add the -n <name> to the configuration files.
