### ISSUE TITLE
vbp_poke rlen handling

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2444]
in the read loop, we overwrite our buffer with every read after we filled it once. While I see a case for drain-reading probe responses, such a probe request will almost inevitably fail because the status line is long overwritten.
Also, we probably shouldn't have rlen += i because this will overflow rlen for i <0, just to be on the safe side (rlen is not used outside the loop, so we're safe at the moment, but we might want to avoid future confusion)

**Comment by daghf** [comment]
@nigoroll, which version are you looking at here?

From what I see we use a completely separate buffer for draining the rest of the response (`vt->resp_buf` vs `buf`) ?

Other than that, agree on testing `i <= 0` prior to the `rlen += i`.

**Comment by nigoroll** [comment]
@daghf right, thank you, my fault to open an issue in the middle of the night.
