### ISSUE TITLE
Varnish sets vcl auto state to cold while being labeled causing empty response

### ISSUE THREAD

**Issue by Marco208** [varnishcache/varnish-cache#2445]
## Expected Behavior
Varnish keeps labeled VCL warm because it's labeled.

## Current Behavior
Auto-state sets VCL to cold after a while.

## Possible Solution
Prevent auto-state VCL to go cold.
 -or-
Load VCL when needed making it warm for the next X time configurable through parameter with possibility to set unlimited.

## Steps to Reproduce (for bugs)
1. Add VCL-ONE
2. Add label to VCL-ONE
3. Add VCL-TWO with reference to label of VCL-ONE
4. Use VCL-TWO
5. Wait until VCL-ONE goes cold
6. Send request
-- manual fix --
7. vcl.state VCL-ONE warm
8. Send request

## Context
Issue is on testing server. Only occurs when labeling VCL's.

## Your Environment
CentOS 6.9 with Varnish 5.1.3 / 5.2.0 (tested both)

**Comment by Dridi** [comment]
This is probably a duplicate of #2432, can you check with the current master branch?

@michbsd, did you try the fix for #2432?

**Comment by michbsd** [comment]
Yes. I am unable to reproduce the crash since your fix. I am testing with the following version: 

FreeBSD,10.3-RELEASE-p19,amd64,-junix,-smalloc,-smalloc,-hcritbit
varnish-trunk revision 66db6c89a

Thanks!

**Comment by Marco208** [comment]
With the current master branch I can't reproduce it either, it stays warm now. I'll manually put it on warm for now until fix is released in next version.

**Comment by Dridi** [comment]
Thanks for confirming!
