### ISSUE TITLE
vsl clients report log overrun indefnitely

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2460]
Ticket ticket lacks more necessary detail and analysis:
Since the "vsm new world order" commits I've seen several incidents where vsl clients (varnishlog, varnishevent) would loop indefinitely with `Log overrun` being output.

**Comment by nigoroll** [comment]
the change in 17d7c4f387c5f7dc715d62bd87b770ee6b9319a4 seems to help. I've not seen this issue again since running with that hack included, but IMHO we still got an issue to look after. My understanding is that the vsl shm should not change, but apparently it does - or at least the vsl client detects a change.
{code}
Log abandoned
Log reacquired
Log abandoned
Log reacquired
Log abandoned
Log reacquired
...
{code}

**Comment by nigoroll** [comment]
Re-iterating over this issue and the fix for #2470, I think that 17d7c4f is correct and fixes this issue for real.

**Comment by hardik8585** [comment]
Hi,

we are using varnish 5.2.1 and getting "log overrun" for VSL clients like varnishlog.

varnish 5.2.1 does not has fix mentioned above, https://github.com/varnishcache/varnish-cache/commit/17d7c4f387c5f7dc715d62bd87b770ee6b9319a4.

Is this final fix means we can add this fix in varnish 5.2.1 ? 
Your comment will really helpful as we have urgent requirement. 

Thank you
Hardik

**Comment by nigoroll** [comment]
There are more changes required to fix vsm in 5.2.1, which are in master, which is also available as weekly binary packages. 17d7c4f fixes a particular issue of a log overrun, but it leaves other issues with vsm open
