### ISSUE TITLE
ESI truncated.

### ISSUE THREAD

**Issue by hjanuschka** [varnishcache/varnish-cache#2464]
i am having strange effects with ESI fragments.

main.html:

```html
<html>
   <head></head>
   <body>
      <div class='esi_fragment'>
         <esi:include src="/fragment.html">
      </div>
   </body>
</html>
```

fragment.html

```html
<div>Hello ESI</div>
```

i tested it with a simple VTC test. and it all works on unittests no matter how many trie's.

```
varnishtest "ESI retry"
server s1 {
        rxreq
        expect req.url == "/foo1"
        expect req.http.host == "www.krone.at"
        txresp -body {<h1>HELI <esi:include src="http://api.krone.at/baz1"/> END</h1>}

        accept
        rxreq
        expect req.url == "/baz1"
        expect req.http.host == "api.krone.at"
        txresp -status 200 -body "OK"


} -start



varnish v1 @@PARAMS@@ -vcl {
  @@BACKENDS@@
 include "${pwd}/deploy/DOCKER/config/test.vcl";
  
  } 

varnish v1 -start

client c1 {
        txreq -url "/foo1" -hdr "Accept-Encoding: gzip" -hdr "Host: www.krone.at"
        rxresp
        expect resp.body ~ "OK"

} -run


```

however in some cases - happens like 2-3 times a day (we have really high traffic) - the fragment gets cut of....

resulting in something like:

```html
<html>
   <head></head>
   <body>
      <div class='esi_fragment'>
      <div>Hello
   </body>
</html>
```

which in fact breaks our page, coz of broken html, in VCL we try to validate ESI and check for bad http error codes, so in case of backend-fail - we would like to see `<!-- ESI error-->`

vcl:

```
sub vcl_recv {
  if(req.esi_level > 0) {
    set req.http.IS-ESI = "1";
  }
}
sub vcl_deliver {
  if ( resp.status >= 300 && (req.esi_level > 0 || req.http.X-Esi ~ "\d") )  {
      return(synth(resp.status,resp.reason));
  }
}

sub vcl_backend_response {
  set beresp.do_esi = true;
}
sub vcl_synth {
  if ( req.esi_level > 0 || req.http.X-Esi ~ "\d" )  {
         synthetic("<!-- ESI error " + resp.status + " URL: 'http://" + req.http.host + "" + req.url + "'  xid: " + req.xid + " -->");
         return(deliver);
  }
}

```

i can verify the error response with a vtc test.

* all config, and sample files have been stripped down to the minimum required info*

i am struggeling with this problem since a couple of days, and i am lost and out of ideas, is there any known issue with ESI that results in something like this? - maybe http chunked response that got cut of? (but then the status code shouldnt be 200?)

any ideas on how to further debug this?

Varnish version installed via packagecloud.io (5.2)

the `@@@` stuf in my VTC gets pre-compiled by helper script

* the actual fragment response is larger it has like ~200KB

**Comment by bsdphk** [comment]
Is there any chance you can capture varnishlog output when this happens ?

**Comment by hjanuschka** [comment]
@bsdphk thx for taking your time, and many thx for all your time and effort you put into varnish ❤️ !!

i am suspecting that it is a similar problem to this: https://varnish-cache.org/lists/pipermail/varnish-misc/2016-April/024903.html


in fact it is hard to enable logging, we are dealing with ~5-10TB per day. and i am unsure what filter i could use on varnishlog, or how i can get close to the window when it happens.

what i did is, i took our "startpage" and curl them every 10 minutes. added `<!-- ESI start-->` at the top of my fragment and `<!--ESI END-->` at the end.

and after the curl, i check if the amount of start tags is equal to the end tags - and sending it to grafana.

looks like:

![image](https://user-images.githubusercontent.com/2891702/31927219-5c7522e0-b893-11e7-94a4-5c22dbfabb1a.png)


its a total strange behaviour, as our traffic peek is around 10:00-13:00, but most troubles are from 18:00-22:00.

i also ensured that the server/backend that servese the fragment is up-and-running  -and the served fragment is also a static html file.


we plan to use ESI more frequently on more sub pages. but we first of all have to find a solution for this one.


each varnish node has a malloc storage of 51GB


can you give me an advice?

**Comment by hjanuschka** [comment]
i also tried to parition the storage. by adding an explicit storage for ESI requests.

starting varnish with: `-s default=malloc,51G -s esi_storage=malloc,5G `

```
sub vcl_recv {
  if(req.esi_level > 0) {
    set req.http.IS-ESI = "1";
  }
}
sub vcl_backend_response {
if(bereq.http.IS-ESI) {
    set beresp.storage_hint = "esi_storage";
    set beresp.http.X-Varnish-Storage = "esi_storage";
    std.log("ESI own storage");
  } else {
    set beresp.storage_hint = "default";
    set beresp.http.X-Varnish-Storage = "default";
  }
}
```

**Comment by hjanuschka** [comment]
also changed all backend requests to `connection='close'` as i had high `sc_` errors.
looking good so far, atleast 2 hours without.

i started following varnishlog command on one of our varnish.

`varnishlog -b -i ESI_xmlerror -q 'ESI_xmlerror !~ "See feature esi_disable_xml_check"'`

maybe i get a bit more insight, as there is `MAIN.esi_error` like 10-15

**Comment by hjanuschka** [comment]
after some while this shows up:

```
-   ESI_xmlerror   ERR at 5702 VEP ended inside a tag
```

comes from: https://github.com/varnishcache/varnish-cache/blob/9d91bcca79a3125c852ee429e4d86342bfd2eb21/bin/varnishd/cache/cache_esi_parse.c#L1081



my esi_tags look like:

```
    <esi:include src="/partial/esi/fragment/inline__1/cache__120/123123" />
```

without any other `<esi:` element, how could this happen? can this be the root of the problem.

**Comment by hjanuschka** [comment]
@nigoroll in fact it was the backend, we had one "job" server writing a static html on disk (NFS).
and many "frontend" webservers (backends) serving this file, and indeed nfs is not the best thing for doing something like this 👎 

sorry to bother you with this issue, and thx for your time, disabling the static copy of the html fragment fixed it 👍
