### ISSUE TITLE
Dynamic CLI buffer follow up

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2467]
Upon closer inspection it looks like the dynamic allocation of the CLI buffer is only effective where the manager *sends* commands to the child. For commands *received*, the `cli_buffer` is still used (by both manager and child processes) but the buffer is already allocated on the heap with a fixed `cli_buffer` size.

The deprecation warning says the parameter is ignored, not entirely true.

Refs #2382

**Comment by bsdphk** [comment]
This is fixed with 6cb21b47a16be6b97b8197dd3cb79cef42999273.

**Comment by hermunn** [comment]
Backport review: The solution for 4.1 is to accept that `cli_buffer` is not removed. See 96534906297fb8440b for the revert of the documentation change.
