### ISSUE TITLE
Incompatible VMOD - hashes do not match

### ISSUE THREAD

**Issue by paulborile** [varnishcache/varnish-cache#2468]
Hi,
we release a varnish module in binary form and we do make them for almost all varnish versions in order to not have ABI mismatch problems. Our procedure builds the module .so by compiling it against the released versions that we download from git with git checkout <release_hash>. Release hashes are found at the releases link in github (https://github.com/varnishcache/varnish-cache/releases) and this as always worked fine (only one strange hash in 5.0 time ago) up to 5.2.0. We get this message while loading our binary module, built with 5.2.0 sources, commit 4c4875c , against 5.2.0 binary version we download from : https://packagecloud.io/varnishcache/varnish5/packages/ubuntu/xenial/varnish_5.2.0-1~xenial_amd64.deb/download.deb

```
Incompatible VMOD wurfl
	File name: /usr/lib64/varnish/vmods/libvmod_wurfl.so
	ABI mismatch, expected <Varnish 5.2.0 4c4875cbf>, got <Varnish 5.2.0 4c4875c>
```
Looks like the git hash short SHA is long 9 characters instead of 7 you used so far. Is this correct ?

**Comment by Dridi** [comment]
My comment from varnishcache/pkg-varnish-cache#91:

> It looks like it depends on your git version :(
>
> I noticed that short hashes were longer when I upgraded git to 2.13 but didn't pay attention to it.
>
> What you should do instead is to install the `varnish-dev` package from packagecloud to make sure to build against the same ABI anyway. Technically, this is "working" because you build against sources but run against packages, different targets... But of course we don't want to consider them different if it's the same commit.
>
> In `generate.py` we should probably replace `git show -s --pretty=format:%h` with `git rev-parse --short=7` to get a consistent short hash. And we should probably add a check to the release process from now on. To me, this is a problem in varnish-cache, not the packaging.

**Comment by Dridi** [comment]
We probably want this in 4.1 too, please advise :)

**Comment by hermunn** [comment]
Dridi, if you think this is not breaking people's setups, then I agree. I have not looked at this closely, so if you think it is safe to port to 4.1, please do.

**Comment by Dridi** [comment]
Added to 4.1 too.

**Comment by paulborile** [comment]
Are we sure that we will be able to build binary packages with the new generate.py that will ABI match with old releases of varnish ? If I understand correctly you are bringing the untruncated hashes to 4.1 : assuming only for versions > 4.1.8, correct ? Same applies to 5.1 ?

**Comment by Dridi** [comment]
> Are we sure that we will be able to build binary packages with the new generate.py that will ABI match with old releases of varnish ?

Short answer is that it doesn't matter, because the "strict" ABI (now known as "source" ABI) only matters for VMODs indicating so. Since 5.2, that's all VMODs unless their descriptor includes `$ABI vrt`.

Long answer is #2330, and the release notes:

https://varnish-cache.org/docs/5.2/whats-new/changes-5.2.html#news-for-authors-of-vmods-and-varnish-api-client-applications

> If I understand correctly you are bringing the untruncated hashes to 4.1 : assuming only for versions > 4.1.8, correct ?

That is correct but boils down to the #2330 problem statement, the VRT ABI will be used instead.

> Same applies to 5.1 ?

5.1 is superseded by 5.2 and will no longer have regular updates.

Please let me know if it needs more clarification, on the way towards 6.0 you might want to read this too:

https://varnish-cache.org/docs/trunk/phk/apispaces.html
