### ISSUE TITLE
varnish 5.2.0 fails to compile on OmniOS (Illumos)

### ISSUE THREAD

**Issue by jfqd** [varnishcache/varnish-cache#2472]
As an OmniOS userland-maintainer I tried to build the latest varnish 5.2.0.

It fails with `error: 'LOCK_NB' undeclared` as shown below:

```
vfl.c: In function 'VFL_Open':
vfl.c:71:14: error: 'LOCK_EX' undeclared (first use in this function)
  operation = LOCK_EX;
              ^
vfl.c:71:14: note: each undeclared identifier is reported only once for each function it appears in
vfl.c:73:16: error: 'LOCK_NB' undeclared (first	use in this function)
   operation |=	LOCK_NB;
                ^
vfl.c:82:3: error: implicit declaration	of function 'flock' [-Werror=implicit-function-declaration]
   if (flock(fd, operation) == -1) {
   ^
cc1: all warnings being	treated	as errors
  CC	   libvarnish_a-vsa.o
  CC	   libvarnish_a-vsb.o
gmake[3]: *** [libvarnish_a-vfl.o] Error 1
gmake[3]: *** Waiting for unfinished jobs....
gmake[3]: Leaving directory `/tmp/build_/varnish-5.2.0/lib/libvarnish'
gmake[2]: *** [all-recursive] Error 1
gmake[2]: Leaving directory `/tmp/build_/varnish-5.2.0/lib'
gmake[1]: *** [all-recursive] Error 1
gmake[1]: Leaving directory `/tmp/build_/varnish-5.2.0'
gmake: *** [all] Error 2
--- Make failed
```

## Steps to Reproduce (for bugs)

The build script can be found here: https://github.com/jfqd/omnios-userland/blob/151014/build/varnish5/build.sh

## Environment

* Version used: 5.2.0
* Operating System and version: OmniOS r151014
* gcc v4.8.1

## Possible Solution

OmniOS as an Illumos-Distribution does not have `flock()`. Jonathan Perkin wrote about it: [Solaris portability - flock()](https://www.perkin.org.uk/posts/solaris-portability-flock.html)

Might it be possible to include an additional `fcntl()` implementation for Illumos-Distributions like OmniOS or SmartOS?

**Comment by Dridi** [comment]
It looks like it has been added on April 14, 2016:

https://omnios.omniti.com/wiki.php/ReleaseNotes/r151018

> For improved portability from Linux: a full flock() implementation.

I'm not familiar with OmniOS, I only quick-searched this, and we already build fine on SmartOS.

**Comment by jfqd** [comment]
Thanks for sharing. I should have known it.

Will upgrade to OmniOSce r151022 LTS.
