### ISSUE TITLE
Please backport #2077 to 5.1.x

### ISSUE THREAD

**Issue by ema** [varnishcache/varnish-cache#2479]
The very useful feature contributed by @xcir in https://github.com/varnishcache/varnish-cache/pull/2077 is currently available in 4.1.8 and 5.2.0, but not in 5.1.3. Please consider backporting it to 5.1.x too.

Thanks!

**Comment by Dridi** [comment]
Hi @ema, what's preventing you from upgrading to 5.2?

**Comment by Dridi** [comment]
In general please keep discussions for the mailing lists, github issues are for actual bug reports. And since we already have #2077 maybe we could move the discussion there?

**Comment by ema** [comment]
> what's preventing you from upgrading to 5.2?

Breaking changes to the VSM API, lack of resources to go through major varnish upgrades every three months. :-)

**Comment by Dridi** [comment]
Hi @ema, I volunteered to be the bad guy and close this issue. As mentioned on the website [1] the 5.1 series is "retired" and superseded by 5.2 and we are not going to support 5.1 unless someone is willing to sponsor it. For example, 4.1 is maintained and released by Varnish Software and UPLEX also contributes back-ports.

[1] https://varnish-cache.org/releases/index.html
