### ISSUE TITLE
logexpect stalls

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2484]
just a quick note because we have neither understood nor documented this properly yet:
both @bsdphk and myself have seen logexpect stalls, see for instance this comment:
https://github.com/varnishcache/varnish-cache/commit/f1d60c1c7133f72c23bc7992212d8839acf93cf5#diff-38ea8f46b329bed7df58bd83a0ae7a5bR86
needs to be understood&fixed. @bsdphk suspected it to be related to my recent vsm fixes, but I consider this unlikely because I had seen it before touching vsm
Reason for failing r02339

**Comment by bsdphk** [comment]
Indeed, running  `varnishtest -n $bignum -i tests/r02339.vtc` produces a consistently high error rate.

To problems seems evident:

1. logexpect `l1` in varnishtest doesn't work as it should

2. varnishd coredumps in mgt_shm_atexit()->VSMW_Destroy()->unlinkat()

**Comment by bsdphk** [comment]
I have spent the morning beating up on r02339, and found that the high error rate were caused by the VSL order of worker threads not being deterministic (51a1d5a87f4f25d535b76fbd3a37c8d74ceb6a70).
