### ISSUE TITLE
PRIV_{TASK,TOP} leak on failure to reembark

### ISSUE THREAD

**Issue by daghf** [varnishcache/varnish-cache#2493]
Freeing of `PRIV_TASK` and `PRIV_TOP` is currently handled in `Req_Cleanup`. I've noticed we have a couple of cases where we might end up doing `Req_Release` without having done a prior `Req_Cleanup`.

Notably this is when we fail to reschedule after being waitlisted, in `http1_reembark` and `h2_reembark` (`h2_reembark` is also broken in other ways, but that's for another issue).

ESI delivery/`ved_include` also does not call `Req_Cleanup` but instead does the `VRTPRIV_dynamic_kill` call itself, so it should not be an issue there.

**Comment by nigoroll** [comment]
summoning @slimhazard and @Dridi : this is also related to our plans on `std.rollback`

**Comment by daghf** [comment]
Fixed in 5cc47eaa8a174d6f072c68d996ff17b38ccd16eb

For h/2, close this in favor of #2563
