### ISSUE TITLE
Possible OH leak in http1_reembark

### ISSUE THREAD

**Issue by daghf** [varnishcache/varnish-cache#2495]
The reqs coming off the waiting list hold a reference to an objhead via `req->hash_objhead`.

In the event that the `SES_Reschedule_Req` call in `http1_reembark` fails, we seem to lack a `HSH_DerefObjHead`, with the result that we're leaking objheads on reschedule failure.

**Comment by bsdphk** [comment]
Looking at that code path is seems particularly unexercised by our tests, so we should probably give it some serious attention.

**Comment by hermunn** [comment]
This was back ported to 4.1 as bf752eff529.
