### ISSUE TITLE
Use standard zlib instead of libvgz

### ISSUE THREAD

**Issue by ingvarha** [varnishcache/varnish-cache#2512]
varnish uses libvgz, a patched version of zlib. The patch is rather small, and according to* the main developer of zlib, Mark Adler, the adding of start and stop markers could be replaced by using Z_BLOCK.

*) Mark Adler wrote, in a reply to phk, on the zlib-devel mailing list:

Date: Mon, 02 Jan 2017 23:35:42 -0800
Subject: Re: [madler/zlib] access to start and stop markers in a stream of compressed files (#189)

I don't see anything here that can't be done with the Z_BLOCK flush option of deflate() and deflatePending().

**Comment by ingvarha** [comment]
The reason for me bugging about this: Fedora doesn't like bundled libraries: https://bugzilla.redhat.com/show_bug.cgi?id=1103578

**Comment by Dridi** [comment]
Not directly related but with GCC 7.2.1I get a plethora of `-Werror=implicit-fallthrough` kicking in the zlib code with our current developer warnings.

**Comment by bsdphk** [comment]
I have looked at this again and have decided to move it to VIP21.

https://github.com/varnishcache/varnish-cache/wiki/VIP21:-Avoid-modified-Zlib
