### ISSUE TITLE
New VSM/VSC doesn't scale for many backends

### ISSUE THREAD

**Issue by ehocdet** [varnishcache/varnish-cache#2518]
## Context
With varnish 5.2.1 on loaded server, Child is killed by master several minutes after a vcl.discard.
It is not systematic, but the more the server is loaded, the more the symptom appears.
This is an upgrade from Varnish 4.1.5+ with equivalent vcl code/vmod who work correctly.

. Varnish has 10k+ backends
. query varnishstats is done every 20 seconds (and take a lot of time, at least 4 times more than with 4.1 and one vcl in memory)
. vcl.load/vcl.discard is done very regularly

Could be similar to #2513, but with  died signal=3

## Your Environment

* Version used: Varnish 5.2.1 from git + fixes for #2460 #2470
* Operating System and version: Linux 3.14.79 / 4.9.0

* Log (typical)
```
Dec 12 15:33:04 webacc6-d varnishd[111821]: CLI telnet 10.5.1.82 44266 10.5.100.6 688 Rd vcl.discard cache_1_20171212T15h25m51s
Dec 12 15:33:04 webacc6-d varnishd[111821]: CLI telnet 10.5.1.82 44266 10.5.100.6 688 Wr 200 
Dec 12 15:33:04 webacc6-d varnishd[111821]: CLI telnet 10.5.1.82 44266 10.5.100.6 688 Rd quit
Dec 12 15:33:04 webacc6-d varnishd[111821]: CLI telnet 10.5.1.82 44266 10.5.100.6 688 Wr 500 Closing CLI connection
Dec 12 15:36:04 webacc6-d varnishd[111821]: Child (101757) not responding to CLI, killed it.
Dec 12 15:36:04 webacc6-d varnishd[111821]: Unexpected reply from ping: 400 CLI communication error (hdr)
Dec 12 15:36:05 webacc6-d varnishd[111821]: Child (101757) not responding to CLI, killed it.
Dec 12 15:36:05 webacc6-d varnishd[111821]: Unexpected reply from ping: 400 CLI communication error (hdr)
Dec 12 15:36:06 webacc6-d varnishd[111821]: Child (101757) died signal=3
Dec 12 15:36:06 webacc6-d varnishd[111821]: Child cleanup complete
Dec 12 15:36:06 webacc6-d varnishd[111821]: Child (103949) Started
Dec 12 15:36:21 webacc6-d varnishd[111821]: Child (103949) said Child starts
```

**Comment by Dridi** [comment]
> Could be similar to #2513, but with died signal=3

Indeed, in your case the child is "less" unresponsive because it handled the `SIGQUIT` message before Varnish would `SIGKILL` it.

I'm starting to wonder whether this could be related to the VSM change in 5.2, having trouble with the amount of backends involved. Especially pressure from constantly adding and removing them because of frequent `vcl.load` and `vcl.discard` operations.

**Comment by nigoroll** [comment]
@ehocdet @acachy could any one of you check if master has this issue

**Comment by ehocdet** [comment]
@nigoroll from which commit? With current master vmod like varnish-modules doesn't not build anymore.

**Comment by ehocdet** [comment]
@nigoroll I check with master (without unecessary dependancy) and issue is the same.

. varnish stops responding when vcl is really discarded
. 10k+ dynamic backends (only add in vcl_init) with same probe
. minimal traffic

This seems to happen when a backend is removed from the vcl.

**Comment by nigoroll** [comment]
thank you for your help @ehocdet . I do not have resources for this atm, but will get back to it in case no-one else takes care of it.
BTW, varnish modules for master are here: https://github.com/nigoroll/varnish-modules

**Comment by bsdphk** [comment]
Status update:

I clearly overlooked this scenario with the new VSM/VSC code.

I have picked a couple of low-hanging fruits which will help a little bit.

The real solution is to group musltiple VSM segments into files and I think I have an outline for that, but I need to pave a bit of road for it first.

**Comment by bsdphk** [comment]
Ok, after a lot of work, I have mitigated this as best I can.

We now cluster static backends into a single VSM segment and we use a flag to hide cold VCL's backend counters instead of destroying and recreating VSM segments.

There still is work to do for authors of VMODs which create a lot of dynamic backends, contact me if need be.
