### ISSUE TITLE
oc->last_lru as float gives too little precision

### ISSUE THREAD

**Issue by mbgrydeland** [varnishcache/varnish-cache#2527]
In commit f267941ff257d0b2400bf4ba16df2b19336b97ff the struct objcore member last_lru changes type from double to float (the reasoning behind is not given in the commit message). last_lru tracks real time as a floating point epoch value, and a float does not have the necessary bits to track the number of seconds since january 1st 1970.

The last_lru timestamp is an optimization in order to avoid having to take the LRU mutex too often. We do not really need high precision on this, and rounding errors should be mostly benign. It looks like the rounding error trying to squeeze today's epoch into a float is around 100 seconds, which is quite a lot higher than the default 5 second lru_interval, so the rounding alone is causing unexpected behaviour. But because the math in storage_lru.c is done using a double, the optimization of lru_interval is undone for ~50 second intervals, causing the LRU mutex have to be taken on every request, and this will affect performance.

The attached test case demonstrates this, and depending on what the clock is when the test is started give different results for n_lru_moved, up to 3 (one for every request performed), while it should have received only 1.

Possible approaches to fix this:

* Tweak the math in storage_lru.c to use floats and accept the huge rounding error (should probably document that in the description of lru_interval parameter)
* Change oc->last_lru back to being a double. This will inflate the size of struct objcore.
* Change oc->last_lru to track VTIM_mono() instead of VTIM_real(). Since VTIM_mono() tracks the system's uptime, the resolution of a float should be adequate (on the assumption that we don't have systems with a larger than 30 years uptime).

**Comment by mbgrydeland** [comment]
[lru-float.vtc.txt](https://github.com/varnishcache/varnish-cache/files/1600028/lru-float.vtc.txt)

**Comment by bsdphk** [comment]
I'm pretty sure the change from double to float was a matter of getting the size of oc to be 2^N again.

**Comment by hermunn** [comment]
Backport review: Commited the test case from 2261dcf as dceb4cf63.
