### ISSUE TITLE
Varnish shouldn't test gunzip for range responses

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2530]
This is a placeholder, I will close this issue once fixed in both master and 4.1 branches. Confirmed for any version since at least 4.0, and I have a patch for trunk. I will submit the first patch once I have a more comprehensive test case.

**Comment by Dridi** [comment]
I'm using this issue also as a placeholder for a collateral bug found while working on this, regarding ESI and partial responses.

The reasons why it took so long to send the patches despite having them ready at the time are 1) I was sick that week 2) I found the ESI bug and 3) it got OBE. Sorry about the latter.

**Comment by bsdphk** [comment]
Go see #2554 instead
