### ISSUE TITLE
Changing beresp.uncacheable is not logged.

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#2531]
Problem: When VCL sets beresp.uncacheable, this is not shown anywhere.

Expected: A log line in VSL mentioning that this object will not be inserted into cache.

Changes to TTL, grace or keep changes are logged to VSL. This overriding flag is not.

Scenario: a backend server sets `beresp.http.cache-control: no-cache`, and the administrator (me, 60 minutes ago) decides to override this temporarily in VCL. `set beresp.ttl = 120s;` in vcl_backend_response. Later, builtin.vcl will set ttl=120s as well, and in addition set beresp.uncacheable. Object appears to be inserted into cache, but later requests are not able to find it.

Experienced on VC 5.0.0.

**Comment by fgsch** [comment]
Should we extend the TTL tag instead of creating a new one?
I think this makes sense together.

**Comment by bsdphk** [comment]
Our policy, probably insufficiently documented, is to log all `set` and `unset` statements in VCL.

Adding `.uncacheable` to the TTL record as @fgsch proposes may make sense, but is orthogonal the the general policy.

We will probably need new VSL tags for this.

Somebody needs to write some code.

**Comment by fgsch** [comment]
@bsdphk while we decide the more holistic approach, can we agreed on adding the uncacheable field to the TTL tag and unblock this particular issue?

**Comment by lkarsten** [comment]
Not sure what fgs means, but usually nothing is as permanent as a temporary fix. Nobody is going to change this after it is implemented (if), since it will break log parsing vsl clients.

The TTL tag is variable length in the later versions. How would it be added to without breaking existing parsers?

A new tag increases per-request log length (noise), otherwise it is most likely trivial to add and maintain.

That being said, I just want it to be possible to understand what happens to the object from reading the log output. Either way is fine by me.

**Comment by gquintard** [comment]
@lkarsten: if I read the man correctly, given the first field, the number of fields is fixed, we can add a string at the end (or better at the beginning, for 6.0)

**Comment by gquintard** [comment]
Can we discuss this during bugwash?

**Comment by gquintard** [comment]
I've been looking at this, and it's pretty unsatisfaying: every time ttl, grace or keep is changed, we output a new line, changing only one field.

Wouldn't it make more sense to keep the full ``RFC`` line + cacheability and then output a line is only the modified field?

**Comment by Dridi** [comment]
This would break the format.

**Comment by gquintard** [comment]
What better time than a major release to break APIs?

**Comment by gquintard** [comment]
a PR (sort of) respecting the format: #2599

**Comment by gquintard** [comment]
fixed in 9e174d4c1d38b752e029d25c28127f9eeace39c9
