### ISSUE TITLE
Make '-g request' the default grouping for varnishlog

### ISSUE THREAD

**Issue by rezan** [varnishcache/varnish-cache#2538]
Discuss and implement making `request` grouping the default for `varnishlog`.

## Expected Behavior
Default request grouping. Ex: `varnishlog -g request`
## Current Behavior
vxid or no grouping. Ex: `varnishlog -g vxid`

## Possible Solution
`varnishlog` code change to make `request` the default.

## Context
I would say almost everytime I use `varnishlog`, I am doing `request` grouping. Extremely rarely do I ever need `vxid` grouping. I believe most users, new and experienced, expect to see request grouping when using varnishlog. Having to type `-g request` everytime is becoming tedious.

## Your Environment
`master` branch so this is available in the next release.

**Comment by nigoroll** [comment]
the current default is `vxid`

**Comment by slimhazard** [comment]
> I believe most users, new and experienced, expect to see request grouping when using varnishlog.

That strikes me as a bold statement, and "I believe" doesn't make for very compelling evidence that it's true.

I personally use `-g request` sometimes but rarely, and I think that I observe most people using the `vxid` default.

I may be wrong, and @rezan may be right that most users set `-g request`, in which case we probably should change it. But changing the default for the tool that might be the one most frequently used could stir up quite a bit of POLA, especially if the new default is not in fact what most people use and prefer. I think we should base that on something better than the subjective and conflicting impressions of a few of the devs.

Unfortunately I don't know how to get reliable empirical evidence of how most people use varnishlog. But ideally that's what we'd need to know to make a well-informed decision.

**Comment by Dridi** [comment]
`-g vxid` is the cheapest and unlike the varnish <= 3 days, sticks to transactions. Considering that I'm usually interested in grouping after figuring a `-q`uery, and that I often capture logs with `-w` then `-g vxid` feels like a more sensible default to me.

**Comment by bsdphk** [comment]
It is not obvious to me that the benefits, if any, of changing the default, will outweigh scripts which suddenly break all over the world ?
