### ISSUE TITLE
http post through  varnish- weblogic takes 30 sec for 302 redirect 

### ISSUE THREAD

**Issue by zatanm** [varnishcache/varnish-cache#2544]
I have a J2EE application running on varnish on RHEL 7. Backend is Apache 2.4 and application server is weblogic 12.2.1

In all such cases where user does a form submit (http post) and after performing some action (say database save) application server does 302 redirects  to a new page (success page). Weblogic adds a lag of approx 30 sec before redirecting to success page. This problem we have started facing recently when we did platforms upgrade. Pls note following

Old setup - radware LB + RHEL 6 + varnish 3.0.6 + Apache 2.2 + weblogic 12.1.2 (above mentioned use case works fine)

New setup F5 LB + (RHEL 7 + apache 2.4 + weblogic 12.2.1) with following versions of varnish

No varnish - works fine
Varnish 3.0.6 - adds 30 sec delay
Varnish 4/5 - works fine on firefox, adds 30 sec delay on IE 11

**Comment by nigoroll** [comment]
We do not use github issues for support questions. Please refer to http://varnish-cache.org/support/index.html
Hint: sounds like some component is not respecting Content-Length.
