### ISSUE TITLE
Not able to find vcl.h

### ISSUE THREAD

**Issue by h0ax-ki1l3r** [varnishcache/varnish-cache#2552]
Hi,

I am trying to find vcl.h, could anyone help me find this figure?
For example, `bin/varnishd/cache/cache_req_fsm.c` includes this file.

Thanks

**Comment by h0ax-ki1l3r** [comment]
Looks like it is generated at runtime.

Could anyone help point the folder/source code files that are responsible to generate vcl.h?

Thanks

**Comment by fgsch** [comment]
grep is your friend:
`lib/libvcc/generate.py:emit_file(fo, buildroot, "include/vcl.h")`

That said, this is for bugs only. For support and misc questions see https://varnish-cache.org/support/index.html.
