### ISSUE TITLE
Labeled VCLs going cold

### ISSUE THREAD

**Issue by radiant-velociraptor** [varnishcache/varnish-cache#2560]
I have just upgraded to Varnish 5.2.1-1.el6 from packagecloud.io, using the instructions provided on the Varnish site, in an effort to get away from a bug detailed here (both issues are closed, by the way): https://github.com/varnishcache/varnish-cache/issues/2432 and https://github.com/varnishcache/varnish-cache/issues/2445.

## Expected Behavior

Labeled VCLs either stay warm or become warm when a request is directed to them. 

## Current Behavior

After roughly 20 - 30 minutes, any labeled VCLs that are not active turn cold (the labels themselves remain warm) and, while they have the "available" status, they are not usable. It does not matter if there are multiple requests running through the labeled VCLs. The VCLs will still go cold. I will note that the VCLs seem to take longer to go cold in 5.1.3 and 5.2.1, if that info is helpful.

This happens for me in 5.1.3, 5.2.0, and 5.2.1.

## Possible Solution
I don't know enough about Varnish's internal workings to say.

## Steps to Reproduce (for bugs)

1. Create a default.vcl
2. Create a labeled.vcl
3. Wait 20 - 30 minutes, maybe a bit longer
4. Make a request that will branch off to the labeled VCL. The request will fail.

Run /path/to/varnishadm vcl.list and you will see something like

available   auto/cold          0 boot
available   auto/cold          0 labeled (1 label)
available  label/warm          0 labeled_label -> labeled (1 return(vcl))
active      auto/warm          0 default

panic.show should have something like

Panic at: Thu, 08 Feb 2018 02:37:06 GMT
Assert error in vcl_get(), cache/cache_vcl.c line 274:
  Condition(VCL_WARM(*vcc)) not true.
version = varnish-5.2.1 revision 67e562482, vrt api = 6.1

Backtrace:
  0x437670: /usr/sbin/varnishd() [0x437670]
  0x47f655: /usr/sbin/varnishd(VAS_Fail+0x55) [0x47f655]
  0x4471bb: /usr/sbin/varnishd() [0x4471bb]
  0x4472c4: /usr/sbin/varnishd(VRT_vcl_select+0x44) [0x4472c4]
  0x7fb04bdbf149: vcl_default.1518055435.605439186/vgc.so(VGC_function_vcl_recv+0x11d9) [0x7fb04bdbf149]
  0x445b95: /usr/sbin/varnishd() [0x445b95]
  0x445f6a: /usr/sbin/varnishd(VCL_recv_method+0x5a) [0x445f6a]
  0x43cb7e: /usr/sbin/varnishd(CNT_Request+0x6be) [0x43cb7e]
  0x45896f: /usr/sbin/varnishd() [0x45896f]
  0x45168d: /usr/sbin/varnishd() [0x45168d]

## Context

I make major use of Varnish's labeling capabilities since I have multiple different sites with slightly different behavior that I have to maintain. There's like seven labels and I'd like to upgrade to get away from the security bug that 5.0.0 is still vulnerable to...

This happens on any machine I install on. I've tried a prod machine (CentOS 6), a stage machine (CentOS 6), and my local machine (Mac).

## Your Environment
* Version used: 5.1.3, 5.2.0, 5.2.1
* Operating System and version: Centos6
* Source of binary packages used (if any)

**Comment by Dridi** [comment]
Duplicate of #2432, fixed in 32a7604c58175c7a5c358375bebc147c1815ef8c and other commits but not part of any release yet. The workaround from #2445 is to explicitly `vcl.state <the labeled VCL> warm`.

**Comment by radiant-velociraptor** [comment]
Good to know. Not sure it's something I can use because I think my manager will call it a hack and worry about the VCLs going cold. We get a lot of users, have a lot of revenue riding on them, and have a lot of business users who need the site up pretty much 24/7, so we prefer to be conservative in our approaches when possible. Not sure why this can't justify a patched release or something since it renders Varnish unusable for anyone using the labels feature.

Thanks. I will consult with my manager and we will either use the workaround or wait for the release with the fix in it.

**Comment by Dridi** [comment]
That's because 5.2 is not a supported branch, so no releases are to be expected, except for security advisories.

Since you prefer to be conservative, you probably won't be interested in our weekly packages, but I'll mention them anyway :)

https://packagecloud.io/varnishcache/varnish-weekly

There's also the possibility of community or commercial support: https://varnish-cache.org/support/
