### ISSUE TITLE
Retire req.esi ?

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2565]
req.esi

        Type: BOOL

        Readable from: client

        Writable from: client

        Set to `false` to disable ESI processing
        regardless of any value in beresp.do_esi. Defaults
        to `true`. This variable is subject to change in
        future versions, you should avoid using it.

As I recall, this was used to prevent ESI processing for front varnishes in deep stacks, and if we remove it I don't think we have tweak to do that.

Do we need resp.do_esi ? so the object can be esi_parsed and cached, but not esi-processed on delivery ?

**Comment by mbgrydeland** [comment]
On Fri, 16 Feb 2018 at 09:28 Poul-Henning Kamp <notifications@github.com>
wrote:

> req.esi
>
>     Type: BOOL
>
>     Readable from: client
>
>     Writable from: client
>
>     Set to `false` to disable ESI processing
>     regardless of any value in beresp.do_esi. Defaults
>     to `true`. This variable is subject to change in
>     future versions, you should avoid using it.
>
> As I recall, this was used to prevent ESI processing for front varnishes
> in deep stacks, and if we remove it I don't think we have tweak to do that.
>
Yes. If one sets up the Varnishes to get objects from eachother (rather
than going to the backend), this flag is needed to get the real object
rather than the ESI-processed one.

> Do we need resp.do_esi ? so the object can be esi_parsed and cached, but
> not esi-processed on delivery ?
>
Isn't that exactly the same?

Martin

>

**Comment by gquintard** [comment]
Indeed, we need to be able to get the verbatim object (except for grip since the transformation can be reverted).

I would prefer to have it as a resp attribute, it makes more sense, but it's just a personal preference.

**Comment by bsdphk** [comment]
vcl4.1 removes req.esi.

vcl4.0 and vcl4.1 adds resp.do_esi which can disable ESI-expansion.
