### ISSUE TITLE
Retire {req|bereq|beresp|resp|obj|.proto ?

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2566]
I think we should remove these variables in vcl4.1, generally nothing good comes out of people mucking about with them, and the C-code already stomps on them a lot.

Input ?

**Comment by Dridi** [comment]
I don't see the point of `obj.proto` because at this point it belongs to Varnish, but the other ones could be kept read-only instead.

I see no reason to have them writable.

**Comment by simonvik** [comment]
We're dependent of being able to read them, its not uncommon that DDoS attacks only use http/1.0 and its nice to be able to block it in that case.

**Comment by bsdphk** [comment]
bugwash consensus:  Make them readonly.
