### ISSUE TITLE
varnish 4.1 vcc accepts $thing.http.$thing.http.$Header

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2573]
This test does not trigger an error as it should (ie the -errvcl does not succeed)

```
diff --git a/bin/varnishtest/tests/v00019.vtc b/bin/varnishtest/tests/v00019.vtc
index c4bd725..dd08480 100644
--- a/bin/varnishtest/tests/v00019.vtc
+++ b/bin/varnishtest/tests/v00019.vtc
@@ -63,3 +63,10 @@ varnish v1 -errvcl {Comparison of different types: STRING '==' INT} {
                }
        }
 }
+
+varnish v1 -errvcl {foo} {
+       backend b { .host = "127.0.0.1"; }
+       sub vcl_recv {
+               set req.http.req.http.foo = "bar";
+       }
+}

```

**Comment by nigoroll** [comment]
FTR: 4.1 has no prio for me, so I'd be happy if someone else looked after the fix if it is at all required

**Comment by gquintard** [comment]
Indeed, and I know of at least one client that will get burned when upgrading to 6.

**Comment by Dridi** [comment]
Regarding `resp.http.Cache-Control[max-age]` I like the idea but we need clear semantics since we can't really express the difference between `field=value` or just `field`.

This for example would feel like magic to me:

```
set resp.http.Cache-Control[public] = BOOL; # or just set/unset without a value?
```

And if we take that from the client side instead, the one we don't trust, how do we deal with duplicates? For example multiple entries with the same name/value in an `Accept*` header.

I would rather write this by the way:

```
set resp.http[Cache-Control].max-age = 30s;
```

Using double quotes would be consistent with VSL where the prefix may contain spaces:

```
Timestamp:"my custom timestamp"
```

Again, not a big fan of double quotes for header names.

**Comment by fgsch** [comment]
We could use `:`, e.g.:

`set resp.http.Cache-Control:public`

ftr, this is how Fastly does it.

**Comment by nigoroll** [comment]
does fastly handle the additional characters?

**Comment by Dridi** [comment]
I don't like the syntax, but I'd rather use `:` and bridge the gap. That's not incompatible with square brackets or double quotes if we want to support the full range of header names.

**Comment by fgsch** [comment]
@nigoroll, please elaborate on additional characters.

`if (req.http.foo:bar) { ... }` will be true if field is present, regardless of its value (or lack of).

**Comment by slimhazard** [comment]
- Data types such as BOOL or DURATION for the header sub-fields strikes me as opening an enormous can of worms, and I'm not sure of the added value. How about just STRING no matter what?

- We're all familiar with the max-age case -- if I have a header with a value for max-age, and I want to set max-age to another value, then it replaces the max-age setting in the header. In other words, there's never more than one max-age. But is there something in the RFCs that says that this will _always_ be true of _every_ possible header subfield? I for one honestly don't know; but if there's no rule establishing that in so many words, it seems to me that it would be daring assumption, and probably asking for trouble.

The latter question has a lot to say about how this might work. Obviously we expect this:
```
set beresp.http.Cache-Control:max-age = "30";
# ...

# The second assignment overwrites the first one,
# so then we only have max-age=60 in Cache-Control
set beresp.http.Cache-Control:max-age = "60";
```

But suppose that someone expects to be able to do something like this:
```
set resp.http.Hdr:foo = "bar";
# ...

# After this, we expect to have *both* foo=bar *and* foo=baz in Hdr.
set resp.http.Hdr:foo = "baz";
```
Then we'll need some way to distinguish the "overwrite" and "append" cases.

If the standards already say that header subfields must be unique, then there's no problem here; in that case sorry for the noise.

**Comment by fgsch** [comment]
@slimhazard I don't think this is specific to the subfields and we should behave the same as with `set resp.http.Set-Cookie = ...;`.

Whether we want/need an `append`/`add` keyword (Fastly has the latter) it's up to discussion.

**Comment by fgsch** [comment]
Related to this, I've a diff to enforce two invalid header cases:

1. A header without a name, e.g. `: foo`
2. A header name that includes a separator, e.g. `;: foo`

We should return 400 for those malformed requests.

**Comment by bsdphk** [comment]
Either hack VCC parser (req.http."!$@#$") or vmod_header import ?

I'll make up my mind this week.

**Comment by bsdphk** [comment]
OK, long overdue decision:  The solution to this problem is vmod_header, (in or out of the tree).

**Comment by nigoroll** [comment]
see also https://github.com/varnish/varnish-modules/pull/148
