### ISSUE TITLE
Fate of -sdeprecated_persistent in 6.0

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2575]
We need to decide if this major release is when we remove `-sdeprecated_persistent`

My only argument against is that we have a few API's that will not be exercised without it, and I worry about keeping them both honest and working.

One solution is to write something minimal which tests those APIs without actually being a stevedore.

Not sure there are any other solutions ?

**Comment by nigoroll** [comment]
If it was removed, we'd probably need to resurrect it in a vmod

**Comment by mbgrydeland** [comment]
13:27:49 < phk> Ok, I call it for make it a build option not enabled by default but enabled in autogen.des

**Comment by bsdphk** [comment]
Pretty rough consensus result:  Keep it as default-disabled build option.  enable by default in autogen.des for developer coverage.

**Comment by Dridi** [comment]
Done in 0f7baca494d06c07f9fc34e9594b36e8748f15b2.

**Comment by domgraziano** [comment]
it might be helpful having a mention to this and how to enable it in the official docs.
https://varnish-cache.org/docs/6.3/reference/varnishd.html#storage-backend

It's a deprecated feature, disabled by default, but documented but without mentioning how to turn it on as I'm having `Error: Unknown storage method "persistent"` by default

**Comment by nigoroll** [comment]
@domgraziano you need to compile with `--with-persistent-storage`

**Comment by domgraziano** [comment]
Thanks @nigoroll do you know how I would I do it in the context of using the official dockerimage https://hub.docker.com/_/varnish ?

**Comment by nigoroll** [comment]
@domgraziano Not. You need to build binaries yourself
