### ISSUE TITLE
varnishlog holding onto old vsms ?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2578]
symptom observed with 062234c19e62fac492bf6559ca2a296d4cc1020a, should be investigated:
file system runnning full, re-start a long runnning varnishlog and space is freed.

**Comment by bsdphk** [comment]
Since there is only one VSL segment, I have a hard time understanding how this would work, and I see no signs of it in trivial tests here.

Isn't it more likely to be old/rotated output files which are still open ?

**Comment by nigoroll** [comment]
closing: I cannot see any issues related to reloading vcls and/or VSMs.

In this case, varnishlog is started via a systemd service, which seems to cause stderr/stdout to be redirected to a hidden file on /tmp. When this issue was observed, the single root partition was running full, so one very likely explanation would be that varnishlog errors were being written to the hidden file.
```
# lsof -p $(pgrep varnishlog)
...
varnishlo 254129 root    1w   REG  254,0         0 1180810 /tmp/fileO2nWsv.varnish (deleted)
varnishlo 254129 root    2w   REG  254,0         0 1180810 /tmp/fileO2nWsv.varnish (deleted)
```

Now changed to: `varnishlog >/dev/null 2>/dev/null`
