### ISSUE TITLE
Assert error in delpt() while running "varnishstat -f MAIN.client_req" command for few minutes in varnish 5.2.1

### ISSUE THREAD

**Issue by hardik8585** [varnishcache/varnish-cache#2580]
if we run "varnishstat -f MAIN.client_req" for some time than below error message is appearing.

Assert error in delpt(), varnishstat_curses.c line 967:
                                                         Condition(((pt)) != 0) not true.
                                                                                         Aborted

I have gone though code but did not get exact problem.

Sharing code flow below.
 
varnishstat_curses.c
961 static void __match_proto__(VSC_destroy_f)
962 delpt(void *priv, const struct VSC_point *const vpt)
963 {
964     struct pt *pt;
965
966     AZ(priv);
967     CAST_OBJ_NOTNULL(pt, vpt->priv, PT_MAGIC);
968     VTAILQ_REMOVE(&ptlist, pt, list);
 
bin/varnishd/cache/cache_panic.c
621     case VAS_ASSERT:
622         VSB_printf(pan_vsb,
623             "Assert error in %s(), %s line %d:\n"
624             "  Condition(%s) not true.\n",
625             func, file, line, cond);
626         break;
627     }   

what can be the problem of this abort ? we are getting this when ever we run above command.

**Comment by hardik8585** [comment]
Error values are changing..! But in most cases there are no error no "errno" as above.

Assert error in delpt(), varnishstat_curses.c line 967:
Condition(((pt)) != 0) not true.
errno = 78 (Remote address changed)
Aborted

Assert error in delpt(), varnishstat_curses.c line 967:
Condition(((pt)) != 0) not true.
errno = 1 (Operation not permitted)
Aborted

**Comment by gquintard** [comment]
Or weekly packages at least? https://packagecloud.io/varnishcache/varnish-weekly

**Comment by nigoroll** [comment]
closing for now. Please re-open if you can reproduce this on post-5.2.1

**Comment by gquintard** [comment]
Hi,

Wha version was this, and could you try to reproduce with 6.0 please?

-- 
Guillaume Quintard

**Comment by nigoroll** [comment]
I think we are seeing this for overruns

**Comment by nigoroll** [comment]
sorry, my previous comment was useless, have deleted it (as I will delete this one)
