### ISSUE TITLE
106 Permission denied issue when try  vcl.load

### ISSUE THREAD

**Issue by bumblebeey** [varnishcache/varnish-cache#2581]
hi i am try on  varnishadm
 vcl.load enabled /var/www/vhosts/example.com/httpdocs/var/conf/varnish/enabled.vcl

i am getting this error 

`106
Message from VCC-compiler:
Cannot read file '/var/www/vhosts/example.com/httpdocs/var/conf/varnish/enabled.vcl' (Permission denied)
Running VCC-compiler failed, exited with 2
VCL compilation failed`

how can i fix this ?

**Comment by Dridi** [comment]
For general questions, reach out to the misc@ mailing list as requested in the issue template. This is only for bug reports.

https://varnish-cache.org/support/

In this case either make sure that the process' user (`varnish` by default) has enough permissions to read that file, or change the process user to something with enough privileges. See jails in `man varnishd`.
