### ISSUE TITLE
suspected objhead leak

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2601]
[See graph](https://raw.githubusercontent.com/nigoroll/scratch/master/objhead.png):

These graphed varnish statistics (summed up over 6 servers) suggest that there might exist an issue leaking objheads. This is the first instance of this symptom to be ever recorded on this installation.

versions used:
* issue seen with: 2babc68abe967715b51aa526f14417f1c081cc05 (had been deployed since January 19th)
* last previous version, where the issue was not seen: 7674f657e385a396ea4504fb1879b25fa0658178

**Comment by daghf** [comment]
Could it be #2495, which was fixed very recently? (5cc47eaa8a174d6f072c68d996ff17b38ccd16eb)

**Comment by nigoroll** [comment]
That is indeed a very likely hypothesis. Thank you so much, @daghf , and sorry for the duplicate!
