### ISSUE TITLE
VCL support for INT64_MAX

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2603]
this vcl
```
       sub vcl_recv { 
               set req.http.int64_max = 9223372036854775807;
       }
```
gets VCC compiled into
```VRT_INT_string(ctx, -9223372036854775808)```
which righty throws a c compiler warning:
```integer constant is so large that it is unsigned [-Werror]```

Even if this is exotic, we should be consistent with integers
(had already been discussed very briefly on IRC, may be caused by the VCC detour over double)

**Comment by bsdphk** [comment]
I looked at this today on the way to visit family and yeah, it's problematic.

The trouble is that we take a detour over `double`, which only has 53 bits mantissa.

There is no fix that I'm comfortable with sticking so few days before the release.

We should relnote this.
