### ISSUE TITLE
Help arguments ("usage listing") gone in varnishd 5.2

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#2608]
Having just upgraded from 5.0.0 to 5.2.1, I'm having issues with finding the command line argument reference.

```
root@host:~# varnishd -V
varnishd (varnish-5.2.1 revision 67e562482)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
root@host:~# varnishd -h
varnishd: option requires an argument -- 'h'
root@host:~# varnishd --help
varnishd: invalid option -- '-'
```
On Linux systems, using `-h` and/or `--help` to get usage is the standard way of getting usage().

Expected:  List of what arguments are available to stdout/stderr.

In 5.0.0 and earlier, this worked as I expected (perhaps by accident) because usage was output on invalid arguments:

```
root@lima:~# varnishd -V
varnishd (varnish-5.0.0 revision 99d036f)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
root@lima:~# varnishd -h
varnishd: option requires an argument -- 'h'
usage: varnishd [options]
    -a address[:port][,proto]    # HTTP listen address and port (default: *:80)
                                 #   address: defaults to loopback
[..]
```

Suggestion: add `--help` as an alias for `-?`. 

Suggestion 2: See if it makes sense to extend the error messages seen when doing `-h` to include a mention of `-?` (or `--help`).

**Comment by fgsch** [comment]
Should we bring back usage on invalid arguments and/or implement --help?

**Comment by bsdphk** [comment]
Somebody write a patch and commit it. this is bikeshed territory.
