### ISSUE TITLE
varnishlog -c -m VCL_Log:company_id:abc  is not working

### ISSUE THREAD

**Issue by hardik8585** [varnishcache/varnish-cache#2620]
This is very hand for us to debug in production. Currently this is not supported in varnish 5.2.1.
There is -I option but its giving only matching line and not "transaction record" for particular match. or is there similar option included like -m?

**Comment by Dridi** [comment]
The issue tracker is for bugs only. For questions or feature request use the support channels as explained in the issue template.

https://varnish-cache.org/support/

**Comment by hardik8585** [comment]
Sure. I will take case next time.Thank you.
