### ISSUE TITLE
Thread leak?

### ISSUE THREAD

**Issue by xcir** [varnishcache/varnish-cache#2623]
![image](https://user-images.githubusercontent.com/198198/37662970-94f81a24-2c9b-11e8-87f2-779f492f6a8c.png)
ESI: enabled HTTP/2: enabled
I disabled http/2 after noticing threads increase.(only hitch restart)
But, It seems gradual increase.

![image](https://user-images.githubusercontent.com/198198/37663158-f8716394-2c9b-11e8-8718-696ac00358a2.png)
This is another instance(ESI: enabled + HTTP/2: enabled)

![image](https://user-images.githubusercontent.com/198198/37663286-3fca1218-2c9c-11e8-86df-a8aa299c81b6.png)
ESI: disabled HTTP/2: enabled
This instance is not using ESI.
Thread was not increase.

## Your Environment
* Version used: Varnish 6.0.0 + Hitch 1.4.6
* Ubuntu 16.04 (4.13.0-19-generic)

**Comment by xcir** [comment]
I'm testing other conditions.(ESI + HTTP/1 + varnish restart)
But, take few days to result comes out.

**Comment by xcir** [comment]
ESI + h1 + varnish restart
->Not increase.

not using ESI + h2
-> After posting thread increased in few instance. 
![image](https://user-images.githubusercontent.com/198198/37818669-517c9106-2ebe-11e8-846c-38c8d7bd815d.png)
This graph(non-ESI+h2) is running for 5 days. 

I think this issue seems at http2.

**Comment by xcir** [comment]
Hitch stopped.
Only healthcheck request.(HTTP)
Instance removed from the cluster at 20:30(JST)

![image](https://user-images.githubusercontent.com/198198/37905191-065b35ba-3139-11e8-89f5-e9c6567e29ae.png)
ESI: Enabled  h2: Enabled thread_pools: 2 thread_pool_min: 200 MAIN.threads: 527

![image](https://user-images.githubusercontent.com/198198/37905181-fb7d4750-3138-11e8-997f-89dd72be61de.png)
ESI: Disabled h2: Enabled thread_pools: 2 thread_pool_min: 150 MAIN.threads: 344

**Comment by xcir** [comment]
All TZ is UTC+0900(JST)

![image](https://user-images.githubusercontent.com/198198/37955874-bf172c16-31e4-11e8-994e-ef9aa8268216.png)
I added some counters for check.
https://github.com/varnishcache/varnish-cache/compare/master...1c804ea
nidle_delta = nidle_incr - nidle_decr (idle threads count)
nidle_active = MAIN.threads - nidle_delta (active threads count)
h2_refcnt_delta = h2_refcnt_incr - h2_refcnt_decr (active h2 streams count)

h2_refcnt_delta and nidle_active increased simultaneously at 10:40-11:00.
This instance removed (and Hitch restart) from cluster at 17:00-17:30.
But, h2_refcnt_delta is not  so much reduced.

I think this problem is related to h2.

**Comment by xcir** [comment]
I'm looking for a cause commit...

3f3213d (Leaked)
12:00(JST)~ removed instance , set thread_pool_timeout=10 and thread_pool_min=50.
![image](https://user-images.githubusercontent.com/198198/38402711-24c37536-3999-11e8-930c-54b1b79de185.png)
https://github.com/xcir/varnish-cache/tree/tmp/snap/0122-3f3213d

d19ce7d(Not leaked? I look a little more.)
![image](https://user-images.githubusercontent.com/198198/38402780-bf1b301a-3999-11e8-859c-10f6c98c8e69.png)
https://github.com/xcir/varnish-cache/tree/tmp/snap/1101-d19ce7d

**Comment by xcir** [comment]
I think thread leak began after 0d3044d

**Comment by Francois-v3** [comment]
I have also a thread leak under unbuntu 16.04 (4.4.0-98-generic) with varnish 6.0.0 and HAProxy 1.8 with h2 enable. The same config with very few h2 trafic show no leak.
![image](https://user-images.githubusercontent.com/12576924/39725559-8155f3a2-524c-11e8-9d3c-ea9f18b801c7.png)
Threads goes down when child restart ...

**Comment by Francois-v3** [comment]
In addition, i can observe that by changing communication between HAProxy and varnish from TCP to UDS, threak leak become at least very small:
![image](https://user-images.githubusercontent.com/12576924/39868266-23aca48a-5459-11e8-9b26-a6edd67ac5ae.png)

**Comment by Francois-v3** [comment]
Finaly i still have thread leak, but only above 2500/3000 requests per second.
![image](https://user-images.githubusercontent.com/12576924/40165840-4febef9c-59bd-11e8-9425-441af0810d8b.png)

**Comment by ehocdet** [comment]
We have also thread leak since h2 is activated.
With frequently vcl load/discard  we can see a lot of vcl stalled in  "discarded   cold/busy" state.

n_vcl grows with h2 enable, and stop to grow without. n_vcl metric on 4 servers:
![image](https://user-images.githubusercontent.com/15999974/40495038-866b77ea-5f76-11e8-828b-edc37316af35.png)

**Comment by daghf** [comment]
Hey

I've now pushed fixes for two separate potential thread leak situations (a56469c3f and 4b73c5f75).

The first one relates to failing POST bodies, and the second one is relating to our handling of PRIORITY frames.

Could I ask you to please give master a spin to see if you still have a thread leak?

**Comment by xcir** [comment]
I'm testing at varnish 6.0.0 + bin/varnishd/http2/* changes.
Please tell me, if you need other commit.
https://github.com/varnishcache/varnish-cache/compare/master...xcir:tmp/snap/v600-apply-h2commit

**Comment by xcir** [comment]
![image](https://user-images.githubusercontent.com/198198/40770797-b18dc876-64f6-11e8-8677-e409f87a7907.png)
https://github.com/xcir/varnish-cache/tree/tmp/snap/v600-apply-h2commit
16:45(JST) ~ removed instance , set thread_pool_timeout=10 and thread_pool_min=10.

Leaked...

**Comment by ehocdet** [comment]
Testing with varnish 6.0.0 and all h2 changes from master: same issue.
Leaks view with stalled vcl (n_vcl):
![image](https://user-images.githubusercontent.com/15999974/40834187-700d0c28-6590-11e8-8780-691ed46f432c.png)

**Comment by daghf** [comment]
Thanks for the updates - looks like we still have a thread leak situation happening somewhere. I'll keep looking.

**Comment by xcir** [comment]
![image](https://user-images.githubusercontent.com/198198/41529056-d6b11822-7326-11e8-8d0e-295f4b82a5b1.png)

https://github.com/varnishcache/varnish-cache/compare/master...xcir:ed50971841d6774b4f92cade3e0520d168616891 (b591b02+add metrics)
18:20(JST) ~ removed instance , set thread_pool_timeout=10 and thread_pool_min=10.

Leaked...

**Comment by xcir** [comment]
https://gist.github.com/xcir/53d33161d1361038a0af677a8eeaa4d3
https://github.com/xcir/varnish-cache/tree/tmp/snap/0618-trunk

**Comment by daghf** [comment]
Thanks a lot @xcir, that was hugely helpful.

I'm pretty confident I've gotten to the bottom of this now. Will push a fix asap.

**Comment by daghf** [comment]
I'm pretty sure this is fixed now, but please reopen if you still see problems.

**Comment by xcir** [comment]
leaked again...
![image](https://user-images.githubusercontent.com/198198/41613715-538affb0-7431-11e8-82c6-d7a2d4063028.png)

https://gist.github.com/xcir/6d0dc200a11ba987f53a770a1f80ff3f

**Comment by xcir** [comment]
backtrace(full)
https://gist.github.com/xcir/902991fbdd32efc6cff7bf89c31b5d3e

backtrace(0x7fd05bd4dfc0) with H2RxHdr,H2TxHdr,H2RxBody
https://gist.github.com/xcir/233dfcaa528c64b75dc2ff260c8e158c

**Comment by xcir** [comment]
backtrace
https://gist.github.com/xcir/05c2e1e534c649c1d00fa9dd2168b725#file-backtrace-all

VSL (h2:0x7fa6c1189fc0)
https://gist.github.com/xcir/05c2e1e534c649c1d00fa9dd2168b725#file-h2sess-h2-0x7fa6c1189fc0-wrk-0x7fa6c118ade0-arg-0x7fa1ae9a0020

VSL (h2:0x7fa1bb4b8fc0)
https://gist.github.com/xcir/05c2e1e534c649c1d00fa9dd2168b725#file-h2sess-h2-0x7fa1bb4b8fc0-wrk-0x7fa1bb4b9de0-arg-0x7fa1a5346020

VSL (h2:0x7fa6c4813fc0)
https://gist.github.com/xcir/05c2e1e534c649c1d00fa9dd2168b725#file-h2-0x7fa6c4813fc0-wrk-0x7fa6c4814de0-arg-0x7fa1ac505020

**Comment by xcir** [comment]
![image](https://user-images.githubusercontent.com/198198/41804774-2820b588-76d7-11e8-9888-a78344222844.png)

again..
I think bit different than before.

backtrace + VSL
https://gist.github.com/xcir/336098bb0d2a93552d232ff4516f90a1

working varnish(tmp/snap/0618-trunk)
https://github.com/xcir/varnish-cache/commit/d2378c9a56669c2314e4ddf09d88c3d1d0dce2a1

**Comment by xcir** [comment]
I'm running 812b136135eac0592d8d8f43d4e5511725d9579b commit for 4days. Not leak!
I think this issue was fixed.
