### ISSUE TITLE
more fixes for http_gzip_support=false

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2626]
#2610 was not complete, more work needs to be done regarding esi. 

> More interesting question: Does esi really work with these changes, even if the
> backend responds with CE: gzip? Or do we maybe want to disable gzip if esi and
> ! cache_param->http_gzip_support?

Also @Dridi mentioned some concerns on -commit:

> My understanding was that http_gzip_support enabled means that Varnish
> will sanitize the client Accept-Encoding header and ask backends to
> compress (which they may not) and handle clients that support gzip or
> not depending on what's present in storage.
> 
> Do we really want to neuter do_g[un]zip set _manually_ in VCL when
> _automatic_ gzip support is disabled?

**Comment by fgsch** [comment]
Esi should work fine with gzip support disabled:

```
        if (bo->do_esi && (bo->do_gzip || (bo->is_gzip && !bo->do_gunzip)))
                return (VFP_Push(bo->vfc, &VFP_esi_gzip) == NULL ? -1 : 0);
```

**Comment by fgsch** [comment]
I don't understand @Dridi concerns. Can you elaborate?

**Comment by nigoroll** [comment]
@fgsch the problem is https://github.com/varnishcache/varnish-cache/blob/5e2b0d8abda18e807b73ed2f6c0746688001e85b/bin/varnishd/cache/cache_fetch.c#L534 in combination with https://github.com/varnishcache/varnish-cache/blob/5e2b0d8abda18e807b73ed2f6c0746688001e85b/bin/varnishd/cache/cache_fetch.c#L565

this ticket was more a reminder, it's probably easier to just review & do the work than discuss it here

**Comment by fgsch** [comment]
@nigoroll if gzip support is disabled, do_gunzip will be 0.
If is_gzip is 1 and do_esi is 1, we will still push the VDP.

**Comment by nigoroll** [comment]
@fgsch good point, might just be fine. I'd like to double check and add vtcs at least.

**Comment by Dridi** [comment]
@fgsch my comment in the original context: https://varnish-cache.org/lists/pipermail/varnish-commit/2018-March/019461.html

With that patch, `do_g[un]zip` becomes a no-op, so either the docs should reflect that, or disabling automatic gzip support should still allow you to manually set it up.

**Comment by fgsch** [comment]
Valid point though we have always behaved like that (gzip support disabled neutered do_gzip / do_gunzip).

**Comment by Dridi** [comment]
Then it's only a matter of documenting it in the varnishd manual :)
