### ISSUE TITLE
Enforce Host requirement for HTTP/1.1 requests

### ISSUE THREAD

**Issue by fgsch** [varnishcache/varnish-cache#2631]
We currently allow HTTP/1.1 requests without the Host header, however this is mandatory.

As per RFC 7230:

```
   A client MUST send a Host header field in all HTTP/1.1 request messages.
```

Also:

```
   A client MUST send a Host header field in an HTTP/1.1 request even if
   the request-target is in the absolute-form, since this allows the
   Host information to be forwarded through ancient HTTP/1.0 proxies
   that might not have implemented Host.
```

And finally:

```
   A server MUST respond with a 400 (Bad Request) status code to any
   HTTP/1.1 request message that lacks a Host header field and to any
   request message that contains more than one Host header field or a
   Host header field with an invalid field-value.
```

Adding this ticket to discuss it during bugwash.

**Comment by fgsch** [comment]
The diff is trivial but the implications are big:

```--- a/bin/varnishd/http1/cache_http1_proto.c
+++ b/bin/varnishd/http1/cache_http1_proto.c
@@ -352,6 +352,7 @@ HTTP1_DissectRequest(struct http_conn *htc, struct http *hp)
        uint16_t retval;
        const char *p;
        const char *b = NULL, *e;
+       unsigned n;

        CHECK_OBJ_NOTNULL(htc, HTTP_CONN_MAGIC);
        CHECK_OBJ_NOTNULL(hp, HTTP_MAGIC);
@@ -364,7 +365,8 @@ HTTP1_DissectRequest(struct http_conn *htc, struct http *hp)
        if (hp->protover < 10 || hp->protover > 11)
                return (400);

-       if (http_CountHdr(hp, H_Host) > 1)
+       n = http_CountHdr(hp, H_Host);
+       if (n > 1 || (hp->protover == 11 && n == 0))
                return (400);

        if (http_CountHdr(hp, H_Content_Length) > 1)
```

**Comment by Dridi** [comment]
Should we also fail a backend transaction if `bereq.http.host` is unset in VCL and the selected backend doesn't have a fallback `.host_header` ?

**Comment by fgsch** [comment]
We will always send the Host header to the backend AFAICT.

**Comment by slimhazard** [comment]
If there's no `.host_header`, then `bereq.http.Host` is set to the value of `.host` in the backend declaration for IP backends, or `0.0.0.0` for UDS backends. This comes up in the [Upgrading docs](https://varnish-cache.org/docs/6.0/whats-new/upgrading-6.0.html#uds-backends-and-the-host-header) for 6.0 (since the UDS part is new).

**Comment by Dridi** [comment]
Then let's ensure coverage as part of this effort.

**Comment by bsdphk** [comment]
Decision: We will do this in builtin.vcl and document prominently for next release.

We can reconsider at 7.0 time if we want to enforce in C code.

**Comment by fgsch** [comment]
I will rework the PR.

**Comment by fgsch** [comment]
Updated. I will update the doc once I have an OK on the change itself
