### ISSUE TITLE
2018-09 Release TODO/Wishlist/Coord

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2641]
At present time, I *expect* this to be a 6.1.0 release, but the final decision will not be made until late summer.

Approximate Schedule:

* 2018-08-15 Code cool-down until
* 2018-09-01 Hard Code freeze
* 2018-09-15 Release

TODO
-----
* VCL-configurable VFP/VDP stacks

Evacuate issues from #2438 to here before we close it.

Wishlist
--------

Coordination
------------

**Comment by slimhazard** [comment]
Wishlist: improve FetchError messages

**Comment by nigoroll** [comment]
* show-stoppers (absolutely need to be fixed before release, IMHO)
  * #2708 handle out-of-workspace for priv_task / priv_top 
* personal show-stoppers which would relevantly impair use of the next release for me/us
  * #2680 VRT_DirectorResolve()
* wishlist
  * #2725 director refcounting
  * #2462 additional ban attributes

**Comment by bsdphk** [comment]
release date will be 17 september, 15th is a saturday.

**Comment by nigoroll** [comment]
@slimhazard 991e101bbc3e41681b0bbe462f8daa6662735007 is in at least

**Comment by bsdphk** [comment]
Release is out, next one in march 19
