### ISSUE TITLE
assert failure stopping a VUT app via vtc process -stop

### ISSUE THREAD

**Issue by slimhazard** [varnishcache/varnish-cache#2649]
This came up while I was trying to construct a test case for #2646.

When a VUT app is started with `process -start` (I found this with varnishncsa), and then stopped with `process -stop`, this assertion failure is invoked:
```
Assert error in vut_sighandler(), varnishncsa.c line 1127:
  Condition((vut) != NULL) not true.
```
It's happening because `VUT_Fini()` starts with `TAKE_OBJ_NOTNULL`, which NULLs the `vut` object, and the signal handler gets the object after that.

Apparently the only way we run varnishncsa in the current tests is with the `shell` command, and then it can be stopped with `shell "kill"`, apparently without any problems:
```
varnishtest "assert error stopping varnishncsa via vtc process -stop"

varnish v1 -vcl { backend b { .host="${bad_ip}"; } } -start

# No problem starting varnishncsa -D via the shell command, but then
# we can't use the process command to check the error status, stderr
# output, etc.
shell {
	varnishncsa -n ${v1_name} -D -P ${tmpdir}/ncsa.pid -w ${tmpdir}/ncsa.log
}

delay 1

# Killing the process with the shell command doesn't seem to cause any
# errors.
shell "kill -TERM `cat ${tmpdir}/ncsa.pid`"

# Now we use process -start, to use some of its checks in a test.
process p1 {
	varnishncsa -n ${v1_name} -P ${tmpdir}/ncsa.pid -w ${tmpdir}/ncsa.log
} -start

delay 1

# This results in assertion failure and coredump:
# Assert error in vut_sighandler(), varnishncsa.c line 1127:
#   Condition((vut) != NULL) not true.
#   errno = 4 (Interrupted system call)
process p1 -stop
```
But for the bugfix I need to use `process` for the checks it provides, which can't be done when it's started as a demon with `shell`.

I'll have a PR to fix this shortly, and another PR based on the first one as a fix for #2646.

**Comment by Dridi** [comment]
Fixed in d0a2ec9e75f4e09d9d40c057d34f66c548766c81.
