### ISSUE TITLE
VSL query on ReqHeader:host doesn't match exact hostname (either with regexp or «ne»)

### ISSUE THREAD

**Issue by dugwood** [varnishcache/varnish-cache#2652]
I'm trying to ignore one domain name in the `varnishncsa` log.

Using `!~` is working, but for speed I think I should use `ne`:
`-q "ReqHeader:host ne \"ignore.domain.com\""`

## Expected Behavior
VSL query should filter requests with host `ignore.domain.com`

## Current Behavior
VSL query doesn't filter out requests

## Possible Solution
Perhaps the host isn't properly cleaned, even if there's some whitespace cleaning here:
https://github.com/varnishcache/varnish-cache/blob/master/lib/libvarnishapi/vsl_query.c#L141

## Steps to Reproduce (for bugs)
If varnishncsa is filtered with:
`-q "ReqHeader:host !~ \"ignore.domain.com\""` => works (bad regexp with dots not escaped)
`-q "ReqHeader:host !~ \"ignore\.domain\.com\""` => works
`-q "ReqHeader:host !~ \"ignore\.domain\.com$\""` => works
`-q "ReqHeader:host !~ \"^ignore\.domain\.com$\""` => doesn't work
`-q "ReqHeader:host !~ \"\s+ignore\.domain\.com$\""` => doesn't work
`-q "ReqHeader:host !~ \" ignore\.domain\.com$\""` => doesn't work
`-q "ReqHeader:host !~ \"^.+ignore\.domain\.com$\""` => doesn't work
`-q "ReqHeader:host !~ \"^.*ignore\.domain\.com$\""` => works
`-q "ReqHeader:host ne \"ignore.domain.com\""` => doesn't work

The fact that `^.+ignore\.domain\.com$` doesn't work should imply that there's no character in front of the host header. But `^ignore\.domain\.com$` doesn't work either! Am I missing something obvious?

I thought there could be `Host: ` in front of the header value, but the test `\s+` for whitespaces or with a space is negative...

So what is the real string passed to this test?

## Context
Multiple varnishncsa that logs to different files for multiple domains. In my case it's just to split one huge domain from the crowd, and I need a different logging format too. So two instances of varnishncsa and it will be great!

## Your Environment
* Version used: 5.2.1 from packagecloud
* Operating System and version: Debian 9 (stable)

**Comment by fgsch** [comment]
IOW, these should work:

```
-q "ReqHeader:host !~ \"ignore.domain.com\"" (OK)
-q "ReqHeader:host !~ \"ignore\.domain\.com\"" (OK)
-q "ReqHeader:host !~ \"ignore\.domain\.com$\"" (OK)
-q "ReqHeader:host !~ \"^ignore\.domain\.com$\"" (FAILS)
-q "ReqHeader:host !~ \"^.*ignore\.domain\.com$\"" (OK)
-q "ReqHeader:host ne \"ignore.domain.com\"" (FAILS)
```

And these should not:

```
-q "ReqHeader:host !~ \"\s+ignore\.domain\.com$\"" (FAILS as expected)
-q "ReqHeader:host !~ \" ignore\.domain\.com$\"" (FAILS as expected)
-q "ReqHeader:host !~ \"^.+ignore\.domain\.com$\"" (FAILS as expected)
```

**Comment by fgsch** [comment]
I've tried to reproduce it but seems to be working fine for me:

```
varnishtest ""

server s1 {
        rxreq
        txresp
} -start

varnish v1 -vcl+backend {

} -start

client c1 {
        txreq -hdr "Host: example.com"
        rxresp
} -run

shell {
        set -e
        test -n "$(varnishncsa -n ${v1_name} -d -q "ReqHeader:Host ~ \"^example.com$\"")"
        test -z "$(varnishncsa -n ${v1_name} -d -q "ReqHeader:Host !~ \"^example.com$\"")"
        test -n "$(varnishncsa -n ${v1_name} -d -q "ReqHeader:Host eq \"example.com\"")"
        test -z "$(varnishncsa -n ${v1_name} -d -q "ReqHeader:Host ne \"example.com\"")"
}
```

**Comment by Dridi** [comment]
I think I can reproduce this with a 19GB VSL dump. For practical reasons (and mostly confidentiality) I will share it internally.

I thought that using `ReqHeader:Host[1]` could help ensure that whitespaces don't accidentally pollute the match, but apparently not. In my case, transaction with a given host are properly ignored, but other hosts too.

If I use a dummy host that appears nowhere in the VSL then `... ne "dummy"` matches everything. So it looks like some flag is not reset between transaction groups.

**Comment by dugwood** [comment]
Your test is right, but something seems wrong to me. In my test, I was running on a development server, so I prefix domains with `dev.`, so `example.com` becomes `dev.example.com`. In the `vcl_recv`, I remove the prefix, so that my backend (lighttpd) only see the production domain, and act the same way as it was in production.

Hence:
`varnishncsa -q "ReqHeader:Host eq \"dev.example.com\""`
and
`varnishncsa -q "ReqHeader:Host eq \"example.com\""`
=> both are matching requests from `dev.example.com` (which is rewritten as `example.com` in the `vcl_recv`)

If I log `%{Host}i`, I get `example.com`, so I expect that the VSL query only match `example.com` and not `dev.example.com`.

OK, I think that I understand my issue: I don't `unset` the Host header... so it must appear twice! Once with `dev.example.com`, then with `example.com` which is reported by the varnishncsa. But the test is done on both. So conditions are always true, because `eq` will match one or the other, and `ne` will not match because of the first one.

Retrying with unset... but in fact I can't unset it (unless I use another variable). In the `varnishlog`:
```
-   ReqHeader      Host: dev.example.com
-   VCL_call       RECV
-   ReqUnset       Host: dev.example.com
-   ReqHeader      host: example.com
```
So I should not have any `dev.example.com` that should match. Do you agree that `eq` means equals and not include?

**Comment by dugwood** [comment]
@Dridi, I tested `Host[1]` too, with no luck. But the issue seems to be related to the Host rewritten, as you  have a "dummy" in your case, and I have a "dev.*".

Here's my code:
```
	if (req.http.host ~ "^dev\.")
	{
		set req.http.host = regsub(req.http.host, "^dev\.", "");
		set req.http.X-Special-Header-With-Another-Name = "dev";
	}
```

**Comment by gquintard** [comment]
Sorry, looking at it from afar, but isn't it just that when you rewrite the
host, the log contains two records with the host header?

the VSL query will match the first record, validating the transaction, and
varnish will just use the second record to print it's line.

-- 
Guillaume Quintard

**Comment by dugwood** [comment]
@gquintard yes I think it's the issue, but as the varnishlog says the host header is unset, it should not appear in varnishncsa. I should have the first one or the new one, but not both, don't you think?

**Comment by Dridi** [comment]
@dugwood I'm not sure how to interpret my observations, but maybe I hit a bug unrelated to your problem. You are in tricky territory when it comes to VSL queries because you modify the host header in VCL. But that doesn't explain why the same check with an equivalent regex doesn't give the same results.

**Comment by dugwood** [comment]
@Dridi not sure either... if it's not a bug, then how can I go around? Not a real issue to me because in production I won't have this rewritten host, but it's good to know why it's working like this (ie: requesting on both headers)

**Comment by Dridi** [comment]
Tricky VSL queries will be tricky... If you want to filter out your "dev" requests, then you can try this:

```
-q 'ReqUnset:host ne "dev.example.com"'
```

I don't understand why the regex variant does what you expected though, instead of also matching the second `ReqHeader:Host` entry.

**Comment by dugwood** [comment]
In fact I just wanted to filter in and out the example.com domain. So that I have one log for all domains but example.com, and one specific log for example.com.

But my VCL may have got in the way, at least on my development server.

I'll try it in production (with the same queries) and let you know. Thanks for all the hints.

**Comment by dugwood** [comment]
Just tried in development without the Host rewrite, and it's working fine. So I'm closing this. I can replace `-q "ReqHeader:host !~ \"example\.com$\""` with `-q "ReqHeader:host ne \"example.com\""`.

I'll add a comment in my code where I do the filtering so that it won't work as expected when Host is rewritten.

Thanks you all for your help, and such a great piece of software :1st_place_medal:

**Comment by fgsch** [comment]
To expand a bit on this, from varnishncsa(1):

`%{X}i  The contents of request header X. If the header appears multiple times in a single transaction, the last occurrence is used.`

Whether e.g. `"%r"` will use the first occurrence.

You are effectively matching both records with the VSL query, but the last one is being logged.

You could use`"%{VSL:ReqHeader:Host}x"` to match on the original Host header, use a different header from VCL to filter, or a combination of both.

**Comment by dugwood** [comment]
Thanks for the clarification, although I've read it and didn't think it would be different than the one used in VSL query.
Sorry I forgot to close the issue (green button is too tempting!)

**Comment by fgsch** [comment]
No worries.  👍
