### ISSUE TITLE
Varnish cache packaging in Ubuntu 18.04

### ISSUE THREAD

**Issue by craigcarnell** [varnishcache/varnish-cache#2655]
Hi,

Could Varnish cache be upgraded to the 6.x release line in ubuntu's 18.04 packaging to be included in the next release please?

**Comment by nigoroll** [comment]
It sure could, but that's up to the Ubuntu maintainers.
This project is looking after our own packaging, see http://varnish-cache.org/releases/index.html

**Comment by fgsch** [comment]
I think the OP is asking exactly about that (packages provided by us).

**Comment by fgsch** [comment]
Continued in https://github.com/varnishcache/pkg-varnish-cache/issues/100.

**Comment by nigoroll** [comment]
Ah, now I get it.
@craigcarnell sorry for my failure to understand what you are asking for
@fgsch thank you for taking care.
