### ISSUE TITLE
varnishncsa -t waiting period is unbreakable

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#2657]
Issue: When running varnishncsa (or another tool like varnishhist) as a user that does not have access to the shared memory file, the period where it is retrying the process is not possible to stop with Ctrl+c.

Expected: the process should abort the wait and exit back to the shell.

```
$ date; time varnishncsa -t 10; date
Mon Apr 23 16:46:56 CEST 2018
^C^C.^C.........
VSM: Could not get hold of varnishd, is it running?

real	0m10.246s
user	0m0.002s
sys	0m0.001s
Mon Apr 23 16:47:06 CEST 2018
```

Workaround: bringing out the big hammer and send sigquit with Ctrl+4 does work.

Running Varnish Cache 5.2.1 from packagecloud on ubuntu bionic. (xenial packages)

**Comment by nigoroll** [comment]
I had seen this as well in the past.

**Comment by lkarsten** [comment]
Did the same thing now on and older rig, and with varnishtest from 5.0.0 on ubuntu artful this is not an issue. The waiting period is possible to break with Ctrl+c.
