### ISSUE TITLE
[BUG] Newest build fails to run, default.vcl does not exist

### ISSUE THREAD

**Issue by ASmith-** [varnishcache/varnish-cache#2659]
[BUG] Newest build fails to run, error report states default.vcl does not exist

$ sudo service varnish
 * Usage: /etc/init.d/varnish {start|stop|restart|reload|force-reload|configtest}
$ sudo service varnish start
$ sudo /etc/init.d/varnish start
[ ok ] Starting varnish (via systemctl): varnish.service.
$ sudo /etc/init.d/varnish configtest
Error: Cannot read -f file (/etc/varnish/default.vcl): No such file or directory

The only file in /etc/varnish is 'secret'. Varnish immediately shuts-down/crashes upon not finding any default.vcl file.

**Comment by rezan** [comment]
How did you install varnish?

**Comment by ASmith-** [comment]
If a vitally needed file is found 'missing' and confirmed missing from the newest Varnish build and install, one wonders what else is missing. It's unimaginable a package would be presented for mass use with a vitally needed file missing to begin with which immediately crashes the Varnish application from even running.

**Comment by ASmith-** [comment]
The Varnish newest package was built from source, ./configure   then make  then sudo make install. It all appeared to progress without errors or issues.

**Comment by rezan** [comment]
> If a vitally needed file is found 'missing' and confirmed missing from the newest Varnish build and install

ok, so im trying to confirm this is actually an issue. Again, how did you install Varnish?

**Comment by gquintard** [comment]
But...make install doesn't install service files, does it?

Where did /etc/init.d/varnish come from?

**Comment by rezan** [comment]
> The Varnish newest package was built from source

When you build from source, there is no systemv (or systemd) integration. You need to manually start Varnish from the command line.

Whatever systemv service file you are using above came from a previous install.

If you want systemv and systemd integration, you need to install Varnish from an actual package and not from source.

**Comment by ASmith-** [comment]
You closed this BUG post because I can't find a vitally needed FILE??? I've never seen such ever. ALL of the information indicates the missing file must be there in that folder which I have explcitedly pointed out in the parent thread. ALL of the documentation on this application requires a user to edit that exact file aligning the port to the Apache server. That file is missing, the configtest fails, when the Varnish app is started it immediately shuts down upon not finding that file and you closed this???

**Comment by gquintard** [comment]
Please calm down.

The file is not vital, you can very well use the -b switch instead of -f.

Also, you are mixing source-installed and package files.

This is not a bug, hence this bug has been closed, however you are welcome to join us on IRC or on varnish-misc to discuss that issue (https://varnish-cache.org/support/index.html)

**Comment by rezan** [comment]
The file you are missing is *your* VCL. You need to create a VCL by defining at least one backend, then save that VCL to a file, then start `varnishd` using that file as the `-f` parameter.

If you install from package, Varnish will ship with a minimal VCL file. It can be located [here](https://github.com/varnishcache/varnish-cache/blob/master/etc/example.vcl).

**Comment by ASmith-** [comment]
I'll go back to Varnish 4.1.1 from the Ubuntu repo. Calling my attempt to locate and correct the problem 'silly' and then closing the issue out almost instantly. I'm shocked by the response here to my bug report which takes away whatever the benefit would bring a user with the newest release. I'll glean whatever benefit that comes from the older repo build and I'll leave this matter there.

**Comment by gquintard** [comment]
As you prefer, just know that there are Packagecloud repos available to installed newer versions (https://varnish-cache.org/releases/install_debian.html#install-debian).

As to our interaction, please re-read the two issues you opened:
- You didn't follow the bug report template.
- We explained multiple times this was not a bug and you didn't believe us.
- I offered multiple times to switch to a more proper channel and was never heard.
- The tone of your reply to Reza answer was less than amiable.
- You duplicated the issue, adding no additional information and were called out on that.

So, I'm sorry my handling of those tickets shocked you, and again, I'm more than ready to assist you with your issue, but this isn't the place to handle this particular problem.

And now I'm also ceasing communication on this ticket too.

Best regards
