### ISSUE TITLE
[BUG] Error: Cannot read -f file (/etc/varnish/default.vcl): No such file or directory

### ISSUE THREAD

**Issue by ASmith-** [varnishcache/varnish-cache#2660]
Error: Cannot read -f file (/etc/varnish/default.vcl): No such file or directory
$ sudo service varnish start
Varnish immediately shuts-down reporting
Error: Cannot read -f file (/etc/varnish/default.vcl): No such file or directory

Built from a direct clone from https://github.com/varnishcache/varnish-cache
Newest Varnish build, Linux Ubunu Xenial LTS/Mint 18.3 amd64 distro.

**Comment by gquintard** [comment]
You are now playing silly.

The source doesn't install service files, I'm pretty sure you are doing something wrong. Now, this bug tracker isn't the place to discuss this and this ticket is going to be closed. If you want to get to the bottom of this, send a mail to the varnish-misc mailing list and we'll figure it out.

But opening a duplicate issue minutes after the first one was closed won't help.

**Comment by ASmith-** [comment]
Oh you feel I'm 'starting' Varnish wrong and provide no effort whatsoever in the syntax to use? Simply to confirm this is buggy, the file is missing, confirmed missing and you are telling me I'm starting Varnish incorrectly? The vitally needed, should be included file /etc/varnish/default.vcl is missing.

**Comment by gquintard** [comment]
1. Again, not vitally needed.
2. Your service file wasn't provided by the source and is trying to use a non-existing file. In other words: you are using a non-secure file that decided to run varnishd with a file it can't find. That is unfortunate, but this is not the source's doing.

default.vcl is, as the name states, a default configuration, and is provided by the package managers, not by the source.

I'm going to stop responding here, if you want to discuss it further, please post on the varnish-misc mailing list.
