### ISSUE TITLE
varnishtest: corrupted double-linked list

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2666]
As of d0a2ec9e7 I consistently get this error:

```
$ bin/varnishtest/varnishtest -i bin/varnishtest/tests/r02649.vtc -n32 -j32
#    top  TEST bin/varnishtest/tests/r02649.vtc passed (3.722)
#    top  TEST bin/varnishtest/tests/r02649.vtc passed (3.724)
#    top  TEST bin/varnishtest/tests/r02649.vtc passed (3.824)
#    top  TEST bin/varnishtest/tests/r02649.vtc passed (3.825)
#    top  TEST bin/varnishtest/tests/r02649.vtc passed (3.831)
#    top  TEST bin/varnishtest/tests/r02649.vtc passed (3.834)
#    top  TEST bin/varnishtest/tests/r02649.vtc passed (3.966)
corrupted double-linked list
Aborted (core dumped)
```

I was testing the robustness of the test case before checking it in. I'm haven't looked into it yet.

**Comment by Dridi** [comment]
When I add the `-k` option I get this error instead: `double free or corruption (!prev)`.

At this point I should probably mention that I upgraded my OS to Fedora 28, and a couple things seems to have gone haywire because of that. More on that later.

**Comment by Dridi** [comment]
Unlike #2667, downgrading jemalloc is not enough to make this go away.

**Comment by fgsch** [comment]
44d2893 should correct this while I investigate.
