### ISSUE TITLE
vcc does not handle attempt to use object() as an expression

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2671]
```
diff --git a/bin/varnishtest/tests/m00000.vtc b/bin/varnishtest/tests/m00000.vtc
index 7bdaa02b1..17d70e130 100644
--- a/bin/varnishtest/tests/m00000.vtc
+++ b/bin/varnishtest/tests/m00000.vtc
@@ -30,6 +30,9 @@ varnish v1 -vcl+backend {
                set resp.http.not = vtc.typesize("*");
                debug.test_priv_call();
                debug.test_priv_vcl();
+               if(objx()) {
+                       return(synth(200));
+               }
                objx.test_priv_call();
                objx.test_priv_vcl();
                std.log("VCL" + " initiated " + "log");
```

triggers:

```
**** v1    0.1 CLI RX|Message from VCC-compiler:
**** v1    0.1 CLI RX|Incomplete code in vcc_expr_cmp(), vcc_expr.c line 1130:
**** v1    0.1 CLI RX|Running VCC-compiler failed, signal 6
**** v1    0.1 CLI RX|VCL compilation failed
```

**Comment by nigoroll** [comment]
discussed during bugwash:
* use of `objx()` should throw a vcc error
* `objx` should work as a test for initialization

**Comment by bsdphk** [comment]
This was fixed somewhere along the way:

    **** v1    0.2 CLI RX|Message from VCC-compiler:
    **** v1    0.2 CLI RX|Expression has type INSTANCE, expected BOOL
    **** v1    0.2 CLI RX|('<vcl.inline>' Line 46 Pos 21) -- (Pos 24)
    **** v1    0.2 CLI RX|                if (objx()) {
    **** v1    0.2 CLI RX|--------------------####-----
    **** v1    0.2 CLI RX|
    **** v1    0.2 CLI RX|Running VCC-compiler failed, exited with 2
    **** v1    0.2 CLI RX|VCL compilation failed
