### ISSUE TITLE
Why is MAIN.summs on top in varnishstat, and what is it?

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#2672]
Issue: the new (?) MAIN.summs counter updates frequently and occupies the space where client_req used to be. It has no documentation, is it important?

Expected: the counters I need to know about in the top of the list.

I don't think I need it, why is it at the very top? This is on 5.2.1.

Suggestion: sort the varnishstat counters so what you need is on top. I can make an ordered list if that is required.

**Comment by nigoroll** [comment]
I believe this is a dup of #2587

**Comment by lkarsten** [comment]
In part. 

I can confirm that on 6.0.0 I do not see this MAIN.summs by default in varnishstat.

The remaining issue here is that the ordering in varnishstat is strange. Was it at some point in alphabetical order?

**Comment by Dridi** [comment]
But this is a debug flag, it shouldn't appear unless you increase verbosity in interactive mode.

**Comment by nigoroll** [comment]
@Dridi that was the bug which #2587 fixed

**Comment by Dridi** [comment]
I think it's safe to close this one as a duplicate, especially now that the counter is documented.

**Comment by nigoroll** [comment]
@lkarsten the ordering is just that from the respective vsc file, which appears to me to be a mixture between "by relevance" and "alphabetically". Sure it could be changed, but the only reason you saw the summs statistic was that the filtering was broken

**Comment by lkarsten** [comment]
No, I'm not happy about closing this without further discussion. Please don't mark 40% overlapping bugs as duplicate.

**Comment by lkarsten** [comment]
As discussed on bugwash last week, I'll prepare a suggested ordering.

**Comment by nigoroll** [comment]
sorry

**Comment by bsdphk** [comment]
Closing, nothing actionable left.
