### ISSUE TITLE
ASAN complains about vrnd.c

### ISSUE THREAD

**Issue by rezan** [varnishcache/varnish-cache#2674]
I have been running into this for a year or so but havent had time to dig into it or report it, so I guess now is the time. I have some testing VCL which use `std.random()` to drive random paths in Varnish and it looks like ASAN complains about it. I looked at the code and couldnt really figure out why ASAN does not like it, so feel free to dismiss this if you think the fault is in ASAN and not `std.random()`.

Summary:

```
nfo: Child (21099) said ==21099== ERROR: AddressSanitizer: global-buffer-overflow on address 0x55cae95930e0 at pc 0x55cae9403398 bp 0x7fb673111550 sp 0x7fb673111540
Info: Child (21099) said READ of size 4 at 0x55cae95930e0 thread T161 (cache-worker)
...
Info: Child (21099) said 0x55cae95930e0 is located 0 bytes to the right of global variable 'randtbl (vrnd.c)' (0x55cae9593060) of size 128
Info: Child (21099) said 0x55cae95930e0 is located 32 bytes to the left of global variable 'rptr (vrnd.c)' (0x55cae9593100) of size 8
```

Full ASAN dump: https://gist.github.com/rezan/f6204e8d8ff7640d9edf98659faa95d9

**Comment by bsdphk** [comment]
I think this is fixed now.  We had overlooked that VRND-testable and random(3) is not thread-safe.
