### ISSUE TITLE
Varnish Cache 6.0.0 randomly crashing?

### ISSUE THREAD

**Issue by craigcarnell** [varnishcache/varnish-cache#2676]
## Current Behavior
Varnish 6.0.0 crashes after several hours, it appears to be running but I can't even telnet to it on port 80

## Your Environment
Ubuntu 16.04.4
Varnish Cache using pre-built packages

**Comment by craigcarnell** [comment]
@nigoroll How do I produce more information for yourselves?

**Comment by fgsch** [comment]
Also see  9171f0ca77f094fa483f2e0e50803b2d9270b8e7

**Comment by nigoroll** [comment]
What @fgsch is trying to say here: This issue and #2647 could potentially have the same cause, so it would be good to know if this issue still surfaces with 9171f0ca77f094fa483f2e0e50803b2d9270b8e7 or later

**Comment by craigcarnell** [comment]
Not having this issue at the moment, so going to close.
