### ISSUE TITLE
varnishncsa wishlist: truncate IP when logging

### ISSUE THREAD

**Issue by woodpeck** [varnishcache/varnish-cache#2677]
I would like `varnishncsa` to log only the first three bytes of an IP number (plus a ".0"), in order to not log "personal data" which new EU legislation is putting some brakes on.

I didn't see a way to configure this, nor was there an obvious place in the code; I noticed that `varnishncsa` tries to avoid allocating memory when combining a log line from fragments, so it wasn't a straightforward change. I ended up hard-coding my change by cloning the frag_fields method and modifying it so that it blindly counts how many dots it has written, and returns after the third:
```
+        while (q < e && !isspace(*q))
+        {
+            if ((*q == '.') && (dots++==2)) break;
+            q++;
+        }
```

Then I changed

```
@@ -949,12 +997,12 @@ dispatch_f(struct VSL_data *vsl, struct
                                    0, NULL);
                                break;
                        case (SLT_BackendStart + BACKEND_MARKER):
-                               frag_fields(1, b, e,
+                               frag_fields_copythreedots(1, b, e,
                                    1, &CTX.frag[F_h],
                                    0, NULL);
                                break;
                        case SLT_ReqStart:
-                               frag_fields(0, b, e,
+                               frag_fields_copythreedots(0, b, e,
                                    1, &CTX.frag[F_h],
                                    0, NULL);
                                break;
```
For the full treatment, I also have to use the format specification "%h.0" on the command line so that the extra 0 is added as the fourth byte.

It works for me but it feels a bit dirty. If anybody with more Varnish experience than me would like to suggest a proper way to implement this and to make it configurable (special format letter? command line switch for `varnishncsa`?) then I'm happy to try and make a proper pull request.

**Comment by Francois-v3** [comment]
Be carreful of IPv6.

**Comment by gquintard** [comment]
What you are asking for is understandable, but not generic at all. What if
people want to blank a larger part of the address for example?

Why not pipe the output into awk/see?

-- 
Guillaume Quintard

**Comment by simonvik** [comment]
Wouldnt it be easier to to this in VCL or in a vmod and instead log #{VCL_Log:GDPRIP}x from std.log or something?

**Comment by gquintard** [comment]
@simonvik : that's also an excellent idea.

No need for a vmod though, a regex should do the trick.

By the way, I didn't notice it was a GH ticket. I'm going to close this. To continue the discussion, please write to varnish-misc.
