### ISSUE TITLE
corrupted POST body with FireFox and H2

### ISSUE THREAD

**Issue by ehocdet** [varnishcache/varnish-cache#2679]
## Current Behavior
With FireFox (any version), POST an image with H2 negotiated. File is seen as corrupt on webserver.
This behavior has been tested with all versions of FireFox, and not triggered with other browsers nor with FireFox and http/1.1.

It looks like a FireFox bug, but it's strange that it was not seen earlier with varnish nor another H2 frontend.
The specificity VCL that could have an impact is the use of std.cache_req_body.

## Steps to Reproduce (for bugs)

. Varnish 6.0 with h2 and VCL:
```
sub vcl_recv {
        if (req.method ~ "^(POST|PUT|PROPFIND|PATCH)$") {
                        set req.storage = storage.wub;
                        std.cache_req_body(262144000B);
        }
}
```
. Firefox and POST an image

. the unexpected things seen with varnishlog
```
-   Timestamp      ReqBody: 1526388840.124451 0.145437 0.145437
-   ReqUnset       content-length: 470919
-   ReqHeader      Content-Length: 340346
-   ReqUnset       content-length: 470919
-   ReqHeader      Content-Length: 340346

```

**Comment by daghf** [comment]
Hi @ehocdet 

Would it be possible for you to grab tcpdump for one of these POSTs? It would be interesting to see the DATA frames being transmitted, to help us decide if this is triggers a bug in Varnish or if Firefox is at fault here.

I can also try to reproduce this myself.

The duplication you see in Varnishlog is actually expected. The reason for this is that we keep a pristine copy of the original header set for use for `rollback`. For request body caching in particular, we need to update the Content-Length in both this copy and in the current request header set, thus the duplicate header set/unset.

**Comment by ehocdet** [comment]
. The Content-Length update is different with FireFox  (compared with Safari or Chrome)

. Another symptom is failed POST request, 'varnishlog -g request' only output:

```
*   << Request  >> 33147     
-   Begin          req 33146 rxreq
-   Timestamp      Start: 1526465331.480890 0.000000 0.000000
-   ReqProtocol    HTTP/2.0
-   Timestamp      Req: 1526465331.480899 0.000009 0.000009
-   ReqStart       x.y.z.1 63532 a0
-   ReqMethod      POST
-   ReqURL         /up.php
-   ReqProtocol    HTTP/2.0
-   ReqHeader      host: XXXX.net
-   ReqHeader      scheme: https
-   ReqHeader      user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:59.0) Gecko/20100101 Firefox/59.0
-   ReqHeader      accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
-   ReqHeader      accept-language: en-US,en;q=0.5
-   ReqHeader      accept-encoding: gzip, deflate, br
-   ReqHeader      referer: https://XXXX.net/up.php
-   ReqHeader      content-type: multipart/form-data; boundary=---------------------------19366169351458672613237292539
-   ReqHeader      content-length: 20020
-   ReqHeader      upgrade-insecure-requests: 1
-   ReqHeader      X-Forwarded-For: x.y.z.1
-   VCL_call       RECV
-   ReqUnset       X-Forwarded-For: x.y.z.1
-   ReqHeader      X-Forwarded-For: 
-   Storage        malloc Transient
-   Timestamp      ReqBody: 1526465381.494730 50.013840 50.013831
-   VCL_return     pass
-   ReqAcct        278 16384 16662 0 0 0
-   End            
```

. It's ok without  std.cache_req_body

**Comment by daghf** [comment]
Hey

That second part of your problem should now be taken care of via a56469c3f

Thanks for reporting.
