### ISSUE TITLE
Bad documentation for "http_resp_size"

### ISSUE THREAD

**Issue by ernestojpg** [varnishcache/varnish-cache#2684]
Hello!

I just realised that the documentation at https://varnish-cache.org/docs/trunk/reference/varnishd.html regarding the **http_resp_size** parameter does not look correct:

### http_resp_size
> "Maximum number of bytes of HTTP backend response we will deal with. This is a limit on all bytes up to the double blank line which ends the HTTP `request`. The memory for the `request` is allocated from the backend workspace (param: workspace_backend) and this parameter limits how much of that the `request` is allowed to take up."

I guess that all those `request` words that I marked should say `response` instead, right?

By the way, if I understood correctly, the parameters **http_req_size** and **http_resp_size** are referring to the total size of the headers only, without including the body, correct? Could you please make it clear in the documentation?

Thanks in advance and congratulations for this amazing project!

**Comment by hermunn** [comment]
Back ported as 24f57e048c6466 to 4.1
