### ISSUE TITLE
need to communicate the reason if vcl_init fails in vcl passed at start time

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2694]
When `vcl_init` fails loading the initial vcl (`-f` parameter), all we say is

```
Child (70751) Pushing vcls failed:
VCL "boot" Failed initialization
```

We should output basic information on the underlying problem, maybe the tail of the log?

**Comment by bsdphk** [comment]
There's a vsb available in VRT_CTX during vcl_init which is emitted as CLI result, that should be output for -f also if at all possible.

**Comment by nigoroll** [comment]
to confirm: this is looking good indeed.

test with {{new regex = re.regex("(");}}:

```
VCL "boot" Failed initialization
Message:
	vmod re: error compiling regex "(" in regex constructor: missing ) (at offset 1)
```
