### ISSUE TITLE
VCL usability: missing import gives standard error.

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#2696]
Issue: When writing VCL that is using a vmod, and the vmod isn't imported, the error message is vague.

Expected: A clear error message. This generic parse error looks the same as when you have non-breaking space, missing a closing bracket, and probably other syntax issues in your VCL. Not user friendly.

Suggested: "Are you missing an import?" or "You may need `import cookie;`"

```
$ ~/work/Varnish-Cache/bin/varnishd/varnishd -C -f `pwd`/foo.com.vcl
Message from VCC-compiler:
Expected an action, 'if', '{' or '}'
('/[[CUT]]/var/foo.com.vcl' Line 24 Pos 9)
        cookie.parse(req.http.cookie);
--------############------------------

Running VCC-compiler fail
```
git master.

**Comment by Dridi** [comment]
You may also get this generic error message for objects, for example if you comment out a `new xxx = vmod.constructor()` and forget to comment out an `xxx.call()` somewhere.

**Comment by nigoroll** [comment]
I'd just add {{(e.g. function, method call)}} after "action"

**Comment by fgsch** [comment]
What about unknown identifier `cookie`?
