### ISSUE TITLE
Probes ignore a manually specified request's port

### ISSUE THREAD

**Issue by svenstaro** [varnishcache/varnish-cache#2703]
I'm using a config like this:

```
backend mybackend {
  .host = "192.168.99.1";
  .port = "10080";
  .probe = {
    .request =
      "GET /something HTTP/1.1"
      "Host: localhost:5555"
      "Connection: close"
      "User-Agent: Varnish Health Probe";
    .timeout = 1s;
    .interval = 5s;
    .window = 1;
    .threshold = 1;
  }
}
```

## Expected Behavior

I would expect varnish to query `localhost:5555/something`

## Current Behavior

It insteads queries `localhost:10080/something`. Effectively. it ignores the port provided in the `Host` part of the manually written HTTP request.

## Possible Solution

In case the `Host` part has a port, always use that. It's definitely the intended behavior in all cases if the user proivdes their port for the probe host manually.

## Your Environment
* Version used: 6.0
* Operating System and version: CentOS 7

**Comment by fgsch** [comment]
The Host header is just that, a header; the probe port comes from the port.

**Comment by nigoroll** [comment]
the disucssion has already happened and the outcome is that the vmod is the appropriate solution.
