### ISSUE TITLE
libvarnishapi needs soname bump

### ISSUE THREAD

**Issue by bzed** [varnishcache/varnish-cache#2710]
## Current Behavior

Programs linking /usr/lib/libvarnishapi.so.1 expect LIBVARNISHAPI_1.0, but since 6.0 libvarnisharpi.so ships 
```
root@host:~# objdump -x /usr/lib/libvarnishapi.so.1 | grep API
2 0x00 0x000d1570 LIBVARNISHAPI_2.0
0000000000000000 g     O *ABS*	0000000000000000              LIBVARNISHAPI_2.0
```
## Possible Solution

Bump the soname of libvarnishapi to avoid linking issues.

## Steps to Reproduce (for bugs)
Install varnish 5, run objdump as shown above. Install varnish 6, do the same and compare the results.

## Context
Programs like collectd link libvarnishapi and fail badly due to missing symbols.

## Your Environment
Debian stretch with varnish from the official varnish repository.

**Comment by bsdphk** [comment]
Merge this with #2718
