### ISSUE TITLE
vcl.list is zero on excessive VCL count. (6.0.0)

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#2713]
Issue: On 6.0.0 on bionic, I'm seeing an empty `vcl.list` with a 200 response, when there are a high (200+) number of VCLs loaded.

```
# varnishadm
200
-----------------------------
Varnish Cache CLI 1.0
-----------------------------
Linux,4.15.0-20-generic,x86_64,-junix,-smalloc,-sdefault,-hcritbit
varnish-6.0.0 revision a068361dff0d25a0d85cf82a6e5fdaf315e06a7d

Type 'help' for command list.
Type 'quit' to close CLI session.

varnish> vcl.list
200

varnish>

# time varnishadm vcl.list; echo $?


real	0m2.013s
user	0m1.946s
sys	0m0.064s
0
```

The VCL count is due to a broken vcl.discard script, which will be fixed in time.

Sifting through syslog, I'm able to find the VCL names currently loaded and it is possible to run discard on it. It runs very slowly:
```
# time varnishadm vcl.discard vcl_e04b7d6d-e261-4894-a502-cb5d8e7b86aa


real	0m33.145s
user	0m1.881s
sys	0m0.053s
```

Last operation as seen in syslog:
```
Jun 18 14:13:14 HOST varnishd[32436]: CLI telnet 127.0.0.1 47548 127.0.0.1 6082 Rd vcl.discard vcl_e04b7d6d-e261-4894-a502-cb5d8e7b86aa
Jun 18 14:13:45 HOST varnishd[32436]: CLI telnet 127.0.0.1 47548 127.0.0.1 6082 Wr 200
```

**Comment by lkarsten** [comment]
After collecting all the pieces, and realising that removing all the VCLs one by one would take 4-6 hours, I restarted varnishd which removed the slowdown for now:

```
# time varnishadm vcl.list
active      auto/warm         22 boot


real	0m0.002s
user	0m0.000s
sys	0m0.002s

```

**Comment by bsdphk** [comment]
Do we want to have a "too many VCL's to list them all" limit ?

**Comment by lkarsten** [comment]
Yes, that would improve on the current behaviour.

Perhaps attacking this from the other direction is better? Deny adding a 500th VCL without removing an old one first? (make a new parameter for the count)

**Comment by Dridi** [comment]
I'd rather have a `vcl.count` command that would always complete in pseudo

**Comment by lkarsten** [comment]
Note that having an excessive count of VCLs also influence startup time of VSL tools like varnishstat. 
Unless that bug is handled separately, that angle won't be covered by vcl.count.

**Comment by slimhazard** [comment]
Some ideas from bugwash for auto-discarding VCLs:
* -p param to limit the number of loaded VCLs, discard the oldest first when n > max, default unlimited
* CLI ``vcl.autodiscard DURATION``: on ``vcl.load``, auto-discard VCLs older than DURATION, 0s means unlimited, default 0s
* or ``vcl.autodiscard INT``: auto-discard when the number of VCLs > n, oldest first, 0 == unlimited, default 0

Mainly it's a common admin problem that's easily overlooked -- nothing prevents you now from exercising some ``vcl.discard`` discipline, but many of us don't think of it (I've certainly done that), and you don't notice the problem until it is a problem, and then it may be hard to recover. So an addition like one of the above would help to automate.

**Comment by nigoroll** [comment]
Do we still want the auto-discard?
