### ISSUE TITLE
final clear screen makes curses varnishtop -d useless

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2721]
since d1b78e8d13a993931d19f2c11acd19959e258ce9 we should keep the screen content intact, otherwise curses `varnishtop -d` is pretty useless

**Comment by nigoroll** [comment]
Ref #2686

**Comment by Dridi** [comment]
Let's ask a show of hands during bugwash:

1. once `varnishtop -d` is done building up the output, print it and exit
2. revert the patch, let the user quit `varnishtop -d`, fix the docs instead

**Comment by nigoroll** [comment]
bugwash decision: (2) with 2 + 1 virtual votes, 0 for (1)
