### ISSUE TITLE
HTTP 416 on multipart range requests

### ISSUE THREAD

**Issue by idl0r** [varnishcache/varnish-cache#2739]
Hi,

we have issues that we could reproduce with at least 4.1.8 and 4.1.10. As soon as you do a multipart range request, you'll get a HTTP 416 which is apparently hitting "RANGE_FAIL Trailing stuff" - https://github.com/varnishcache/varnish-cache/blob/varnish-4.1.10/bin/varnishd/cache/cache_range.c#L123
A test request to reproduce the issue:
curl -vs http://127.0.0.1:1337 -o /dev/null -H 'range: bytes=0-50, 50-100'
Do the same request with just one range and you'll get a 206 as expected.

```
 > GET /path/to/somepdf HTTP/1.1
> Host: example.com
> User-Agent: curl/7.61.0
> Accept: */*
> range: bytes=0-50, 50-100
> 
{ [5 bytes data]
< HTTP/1.1 416 Requested Range Not Satisfiable
< Date: Wed, 01 Aug 2018 12:25:40 GMT
< Server: Apache
< ETag: someetag
< Content-Type: application/pdf;charset=UTF-8
< Content-Language: en-US
< Cache-Control: public, max-age=86400
< Last-Modified: Wed, 01 Aug 2018 12:25:40 GMT
< X-Varnish: 230769
< Age: 0
< Via: 1.1 varnish-v4
< Accept-Ranges: bytes
< Content-Range: bytes */12947862
< Content-Length: 0
< Strict-Transport-Security: max-age=300
```

The actual content size was 12947862 but it doesn't seem to matter. I tried that with just a simple plaintext file as well

We're using the varnish-cache Debian repo/versions
https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
https://tools.ietf.org/html/rfc7233#section-2.1

**Comment by fgsch** [comment]
We don't support multiple ranges.

**Comment by idl0r** [comment]
@fgsch: What's the proper way to deal with such requests? Just unsetting the range header for the request?

**Comment by nigoroll** [comment]
@idl0r any properly behaving client should be able to handle a 200 response resulting from the Range header removed.
Can you maybe share a real life request from the plugin?

**Comment by idl0r** [comment]
@nigoroll:
```
*   << Request  >> 6561581
-   Begin          req 656157 rxreq
-   Timestamp      Start: sometime 0.000000 0.000000
-   Timestamp      Req: sometime 0.000000 0.000000
-   ReqStart       someip someport
-   ReqMethod      GET
-   ReqURL         /path/to/some/pdf
-   ReqProtocol    HTTP/1.1
-   ReqHeader      accept: */*
-   ReqHeader      range: bytes=2634752-2637823, 2637824-2639359
-   ReqHeader      ua-cpu: AMD64
-   ReqHeader      Accept-Encoding: gzip, deflate
-   ReqHeader      user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; Trident/7.0; rv:11.0) like Gecko
-   ReqHeader      dnt: 1
-   ReqHeader      Host: example.com
-   ReqHeader      X-EC-Uuid: someid
-   ReqHeader      X-EC-Session-ID: someid
-   ReqHeader      X-Forwarded-For: someip
-   ReqHeader      X-Host: example.com
-   ReqHeader      X-Forwarded-Proto: https
-   ReqHeader      Via: HTTPS/1.1 ECAcc (somestring)
-   ReqHeader      Connection: close
-   VCL_call       RECV
-   VCL_acl        NO_MATCH acl_local
-   VCL_return     hash
-   ReqUnset       Accept-Encoding: gzip, deflate
-   ReqHeader      Accept-Encoding: gzip
-   VCL_call       HASH
-   VCL_return     lookup
-   Hit            853349
-   VCL_call       HIT
-   VCL_Log        DEBUG: vcl_hit(): obj.ttl=86399.133
-   VCL_return     deliver
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Date: Wed, 01 Aug 2018 11:29:33 GMT
-   RespHeader     Server: Apache
-   RespHeader     ETag: someetag
-   RespHeader     Content-Type: application/pdf;charset=UTF-8
-   RespHeader     Content-Language: de-DE
-   RespHeader     Content-Length: 2639449
-   RespHeader     Vary: https
-   RespHeader     Cache-Control: public, max-age=86400
-   RespHeader     Last-Modified: Wed, 01 Aug 2018 11:29:33 GMT
-   RespHeader     X-Varnish: 656158 853349
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Cache: HIT
-   VCL_acl        NO_MATCH acl_debug
-   RespUnset      X-Cache: HIT
-   VCL_return     deliver
-   Timestamp      Process: sometime 0.000050 0.000050
-   RespHeader     Accept-Ranges: bytes
-   Debug          "RANGE_FAIL Trailing stuff"
-   RespHeader     Content-Range: bytes */2639449
-   RespProtocol   HTTP/1.1
-   RespStatus     416
-   RespReason     Requested Range Not Satisfiable
-   RespReason     Requested Range Not Satisfiable
-   RespUnset      Content-Length: 2639449
-   RespHeader     Content-Length: 0
-   Debug          "RES_MODE 2"
-   RespHeader     Connection: close
-   Timestamp      Resp: sometime 0.000079 0.000029
-   ReqAcct        596 0 596 455 0 455
-   End
```
This was done using a IE 11 + Adobe plugin. Does it help or do you need anything else?

**Comment by nigoroll** [comment]
@idl0r thank you. I'll mark this for bugwash discussion. We should reconsider implementing multi range responses, I guess

**Comment by bsdphk** [comment]
Because of the streaming nature of our delivery pipeline (VDP), there are a legal ranges which would be very hard to deliver, out of order subranges, overlapping subranges etc.

So there will be ranges we will not satisfy, and the question becomes what we return 416 or 200.

I prefer and originally chose 416 because it implies "We do ranges, but not this one", whereas 200 implies "We probably don't do ranges at all" and risks delivery massive amounts of data needlessly.

It would certainly be preferable if our range implementations supported more possible range requests, non-overlapping, in order subranges should be relatively trivial to do, and patches for it are welcome.

**Comment by nigoroll** [comment]
@idl0r jsut FYI, reason for closure is that we do not track feature requests in gh issues
