### ISSUE TITLE
obj.hits is always 0 in vcl_hit

### ISSUE THREAD

**Issue by gquintard** [varnishcache/varnish-cache#2746]
This test doesn't pass on master (nor 4.1):

```
varnishtest "obj.hits doesn't increase in vcl_hit"

server s1 {
	rxreq
	txresp
} -start

varnish v1 -vcl+backend {
	sub vcl_hit {
		if (obj.hits == 0) {
			return(synth(503));
		}
	}
} -start

client c1 {
	txreq
	rxresp

	txreq
	rxresp
	expect resp.status == 200
} -run
```

I would expect ``obj.hits`` to be at least one.

**Comment by gquintard** [comment]
this question is what prevented from proposing a patch. Internally, when finding the object, we are increasing the ``cache_hits`` counter, and the vcl manual says "A value of 0 indicates a cache miss."

I reckon we should set ``is_hit`` to 1 in ``vcl_hit`` but null it if vcl returns ``miss``, ``restart`` and possibly ``synth`` even though it shouldn't matter.

**Comment by bsdphk** [comment]
Originally obj.hits was intended for doing strange things to obj.ttl for (un)popular objects, I don't think that really ever worked in practice ?

Strictly speaking, it doesn't become a hit until vcl_hit{} returns (deliver), so it is consistent that obj.hits is zero first time we come in vcl_hit{}, giving it the semantics "obj.hits == number of *previous* hits".

However, if the semantics "obj.hits == number of times in vcl_hit{}" makes more sense, then by all means change it ... along with the docs.

**Comment by fgsch** [comment]
Isn't a tad late in the game to change this?

**Comment by gquintard** [comment]
Currently, in ``vcl_hit``, obj.hits always equals 0, not just the first time we hit it, and that feels wrong any way you look at it.

**Comment by fgsch** [comment]
@gquintard ok, that feels wrong indeed. I'd expect to be the number of hits excluding this one.

**Comment by gquintard** [comment]
it might prove difficult as the ``cache_hits`` is incremented during lookup
