### ISSUE TITLE
Doesn't work varnishlog, varnightop and all the others utilities...

### ISSUE THREAD

**Issue by kselax** [varnishcache/varnish-cache#2747]
I installed varnish 6 on ubuntu 16.04 by using the tutorial https://packagecloud.io/varnishcache/varnish60/install#manual-deb

Then do these commands and got the result
```
neo@neo:~$ varnishlog
.....
VSM: Could not get hold of varnishd, is it running?
neo@neo:~$ varnishtop
.....
VSM: Could not get hold of varnishd, is it running?
neo@neo:~$ sudo systemctl status varnish.service 
[sudo] password for neo: 
● varnish.service - Varnish Cache, a high-performance HTTP accelerator
   Loaded: loaded (/lib/systemd/system/varnish.service; enabled; vendor preset: 
   Active: active (running) since Mon 2018-08-20 18:13:27 EEST; 1h 45min ago
 Main PID: 7577 (varnishd)
   CGroup: /system.slice/varnish.service
           ├─7577 /usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/
           └─7589 /usr/sbin/varnishd -a :6081 -T localhost:6082 -f /etc/varnish/

Aug 20 18:13:27 neo.ru systemd[1]: Starting Varnish Cache, a high-performance HT
Aug 20 18:13:27 neo.ru varnishd[7576]: Debug: Platform: Linux,4.15.0-32-generic,
Aug 20 18:13:27 neo.ru varnishd[7577]: Platform: Linux,4.15.0-32-generic,x86_64,
Aug 20 18:13:27 neo.ru varnishd[7576]: Debug: Child (7589) Started
Aug 20 18:13:27 neo.ru varnishd[7577]: Child (7589) Started
Aug 20 18:13:27 neo.ru varnishd[7577]: Child (7589) said Child starts
Aug 20 18:13:27 neo.ru systemd[1]: Started Varnish Cache, a high-performance HTT
lines 1-15/15 (END)

```
Varnish is running.

I tried it on VM and got the same result. Before on both was installed varnish 4.4 that is default in an Ubuntu repository. 
I used for removing **sudo apt-get purge vanish*** and then **sudo reboot** os and install varnish 6 by using an instruction from an official site. 
It's looks like a bag.

**Comment by nigoroll** [comment]
most likely, the user you are trying to use the the utilities with lacks permissions to access the varnish shared memory files. Most likely the solution for you is to put your user in the `varnish` group and re-login.
Other than that, we do not use github issues for user questions. Please consult http://varnish-cache.org/support/index.html
