### ISSUE TITLE
child not responding to CLI

### ISSUE THREAD

**Issue by hardik8585** [varnishcache/varnish-cache#2750]
we are using varnish 5.2.1 branch. Getting below error frequently and also child restarts frequently due to this. Looking forward for reply..!  There is no panic and core. Even getting without load/traffic.

Aug 28 09:05:47 vtr9 varnishd[10498]: Child (10586) not responding to CLI, killed it.
Aug 28 09:05:47 vtr9 varnishd[10498]: Unexpected reply from ping: 400 CLI communication error (hdr)
Aug 28 09:05:49 vtr9 abrt-hook-ccpp: Process 10586 (varnishd) of user 994 killed by signal 3 - ignoring (unsupported signal)
Aug 28 09:05:56 vtr9 varnishd[10498]: Child (10586) not responding to CLI, killed it.
Aug 28 09:05:56 vtr9 varnishd[10498]: Unexpected reply from ping: 400 CLI communication error (hdr)
Aug 28 09:05:56 vtr9 varnishd[10498]: Child (10586) not responding to CLI, killed it.
Aug 28 09:05:56 vtr9 varnishd[10498]: Unexpected reply from ping: 400 CLI communication error
Aug 28 09:05:57 vtr9 varnishd[10498]: Child (10586) died signal=3 (core dumped)
Aug 28 09:06:57 vtr9 varnishd[10498]: Child (27271) Pushing vcls failed:#012CLI communication error (hdr)
Aug 28 09:07:57 vtr9 abrt-hook-ccpp: Process 27271 (varnishd) of user 994 killed by signal 3 - ignoring (unsupported signal)
Aug 28 09:07:57 vtr9 varnishd[10498]: Child (0) not dying, killingChild (27271) died signal=3 (core dumped)
Aug 28 09:07:57 vtr9 varnishd[10498]: Child (27271) said Child starts

we have already gone through https://github.com/varnishcache/varnish-cache/issues/2518#event-1425825376  and https://github.com/varnishcache/varnish-cache/commit/a417bf6fcb78b418865fec874cc8211ac63828cc. These changes are already available in src code which we are using currently in production.

**Comment by nigoroll** [comment]
I guess the best advise we can give you is to move to current code (master from src or weekly build).
If that's not possible, please try to get a stacktrace from the code dump.
Increasing the `cli_timeout` could help, but without any more details we cannot know.

**Comment by hardik8585** [comment]
we have gone through #2518 (comment) and a417bf6. Here also no one mentioned statcktrace. And same thing for us, we are not getting any panic or core dump for this otherwise I could have shared. If you can point out any fixes related to CLI issue other then above two in varnish 5.2.1.

**Comment by Dridi** [comment]
I think we should close this issue and move the discussion to the misc mailing list. We can reopen it once it becomes actionable but that's looks like a `cli_timeout` simply needs to be increased.

**Comment by nigoroll** [comment]
@hardik8585 please refer to http://varnish-cache.org/support/index.html

Your report does not have sufficient information to make it actionable. If you got a core dump, you should be able to extract a stack trace from it. Also it sounds like you are running patched code, in which case we'd need to be able to see the code you are running. Finally, the most practical advise has already been given: Move to latest code.
For all other options, see the above.

**Comment by hardik8585** [comment]
Thanks @nigoroll 
we moved from varnish 3.x version to 5.2.1. which has many issues and this is running in production. with your advise if we move to latest code ( i understood is varnish 6.0) will it be stable ? or please suggest latest stable version we should use. your inputs are really important for us. Thanks.

**Comment by nigoroll** [comment]
https://packagecloud.io/varnishcache/varnish-weekly if you intend to use binary builds or
build from current master branch

**Comment by nigoroll** [comment]
And yes, I think the current code is very stable, we're running close-to-cutting-edge code in many large-isch production environments
