### ISSUE TITLE
strange behavior with varnish 

### ISSUE THREAD

**Issue by hardik8585** [varnishcache/varnish-cache#2757]
I have noticed ( both on varnish 5.2.1 and 6.0) the strange behavior with the cache-worker thread of the cache-main process Each time it has happened with a request for abc.com. While the same process is working fine for xyz.com. It seems like the thread is getting stuck in writev() syscalls which take more than a minute for writing very small data. This causes the thread to be stuck for few minutes.

I am marking in bold the relevant syscalls
1) Connection request
2) read GET request
3) write data back to client (this took about 40 seconds)
4) write data back to client (this took more than a minute and ultimately returned EAGAIN). When writes to socket will be blocked, writev() should return immediately in non-blocking mode with errno set to EAGAIN. The fact that it took so long to return EAGAIN is very strange. But the code doesn't restart the system call and goes to accept another client request.

Please help to understand, this is problem with kernel or "varnish code + kernel" ? we are using centos 7.4 ( kernel version -Linux 3.10.0-693.11.6.el7.x86_64 ). we were using varnish 3 on same kernel before and could not see this issue any time.

I have changed ip address with x.x.x.x and port number with y.

accept(5, {sa_family=AF_INET, sin_port=htons(42818), sin_addr=inet_addr("x.x.x.x")}, [16]) = 172
ioctl(172, FIONBIO, [0])                = 0
getsockname(172, {sa_family=AF_INET, sin_port=htons(y), sin_addr=inet_addr("x.x.x.x")}, [16]) = 0
setsockopt(172, SOL_SOCKET, SO_LINGER, {onoff=0, linger=0}, 8) = 0
setsockopt(172, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(172, SOL_TCP, TCP_NODELAY, [1], 4) = 0
ioctl(172, FIONBIO, [0])                = 0
poll([{fd=172, events=POLLIN}], 1, 49)  = 1 ([{fd=172, revents=POLLIN}])

 read(172, "GET /abc/xyz/image-t.jpg HTTP/1.1\r\nHost: www.abc.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\r\nAccept: image/webp,image/apng,image/*,*/*;q=0.8\r\nAccept-Language: en-GB,en-US;q=0.9,en;q=0.8\r\n\r\n\r\n", 32768) = 806
futex(0x7fc23a94da44, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7fc23a94da40, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7fbd2c0631a4, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x7fbd2c021738, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fbd2c0631a4, FUTEX_WAIT_PRIVATE, 3, NULL) = 0
futex(0x7fbd2c021738, FUTEX_WAKE_PRIVATE, 1) = 0

writev(172, [{"HTTP/1.1", 8}, {" ", 1}, {"200", 3}, {" ", 1}, {"OK", 2}, {"\r\n", 2}, {"Date: Fri, 31 Aug 2018 06:30:51 GMT", 35}, {"\r\n", 2}, {"Content-Type: image/jpeg", 24}, {"\r\n", 2}, {"Content-Length: 3052544", 23}, {"\r\n", 2}, {"Last-Modified: Mon, 27 Aug 2018 05:41:22 GMT", 44}, {"\r\n", 2}, {"ETag: \"5b838f02-2e9400\"", 23}, {"\r\n", 2}, {"Age: 1", 6}, {"\r\n", 2}, {"Server:abc", 39}, {"\r\n", 2}, {"Accept-Ranges: bytes", 20}, {"\r\n", 2}, {"Connection: keep-alive", 22}, {"\r\n", 2}, {"\r\n", 2}, {"\20\6\226\307\312(\247U\264\200\204\371*\255\0\243S\223\35\0024\347\337\335\345\363\360\314u\302\252\36\270\354XT\341\356)\212mtM\16\207\2648\324 \23\220\36OG\223\270&\265\31\204U\f\320i\37C\216\271\374\347\353z\376\360\366\303\367b\201< \376\226<\353\343t}\3\255x`'\4\230-\270\3622 _\314\1?@\367\30DPYP\342\24\321i\313\20\324\361?}\314\373\3\247\r\352)\274\v\224\321\327\361\264\4Z\264\31$\256\273\4\0073^v\231\364\220\364\26\253\271\16\214\nCxK\226:\2n\371\31`\365\340\317WZR\24\226D\304\247\241\355\324\273\376\20\230\246u5S\177MX?Vx\"\204\35\374\322\377KB\3140\313\347\n\274N\335\236g\345\241\377\31\323]\270HtF\374\362;{\246\177\220\274IbM\10I\361q`\361\260\10\357x\372\315\202\345\277XX\316\346|\310\211L\252\225\f\263\375~\325\260q\227\23\206\30\fy\366(\324\213H\346\272\275&/'\356\17F\10\373\16\330\7O\302\256~J\10\v\237\366\223\334BKp\262p\260\250\221\233y\272O-\326\316]f\270\202\3147\253k\343\2621fiLkp\277\0202\4&w\342\323\351r\350T\204~\207\26'\361\250\231\203-\33}\215\333D\323\212\222I/\360\210\177:\307\325JSG)x\305x\316^k \2141/)\273jfQ\6\2214\377\223\221l\21)\266{\343!,W\330Y@\272\26\347\244:l\253\273=N3t\232\352\20C\252\316\37\211f\357^\375\r7\217\371FT\332\37xN|f\1\321\375D\305H\272\26\205\201'\270\5>\247\"\367\222\236\300\r-\371\347\0=1\24\256\3101\230\242a\27\3\215\320}\231\21s\3640\247>\364H\377\35\335\243c\347\303N\1\247\35\267>\370\367\224F\233\330\0004\271\244\6o\203\222\240\273\247]^&G\316`\303\352\22F(=\262\246(\364\317\217SYQmG\366)3y\360%\24P\223)\0276\260LE\35\257Uv\331\0\345\323\257\305=@\2P\221\376K\263\271\366\255\t\2424\4\251'|\304d\245gfZ\360\374\324\231tB-.\337_\214\17,\2618\335\366\35W\347 \262L\325Q\352kC{\242\0\t[\253\351\230\26s\300\371\230\321\206U8\271\211`7F<t\362F\230\22\300\233N\26\302\342\6\321\301\320\334\275c\17\332\177\252\347\7:,\n\375 i\177\212\33\352nf\254\343\254\317\356#(\247\234[\37\341\220\360\f\2772\247\205>\226\215\317L\351\3238\347O\nt\326\201\30\332-\217\355@\263d\177\303i3A\300fZ\266\262\306\7\211\316\304\327F\223\227\243\5f\27o\"ez\0254\275\326Z\224}K7(@\347\361\334\313\nP\221\202\241ps\25SE6\276\226\31\345\243b6`\261Phv\246\332\360=@\233O\307X\316\302\t\363\4\205w\263s\230\231~\207\36\32\316\224\332\321\220\350\351,\364\34\353\247\323\247j\324\251\214\212\235^?\10\307t\35\255r\327\263w\245k\324\2m\273~\211=\362yA*\316\322\231\301}w\351G\302\373\333E\216\234S\341'&\201\356\272\251\37\203\313\35\363\360\333\237\340\233*E\24?j\346\321\367\245\27\2354\336Y/?\351\2343?[\340\274\233/{w\247zr\276\321\306T\201\231\314\357d&\205\7\231\251\326\372\340\274\216I\2708\365Y\326$&.\312\327\246\213\245B\23\314k\253+9\216\313\311\6\235\347\177\212[U\355\204\232G\233\227\316>\376\31\362\261=\220\331\253\r2\260\373\215\340\226|\207C/g\367}j\315\367N'\215=N\"\372c\25L\314#\31\351\t\5#\325J+\25m\367b"..., 352130}], 26) = 86880

writev(172, [{"^\267\305b\265\177\207\325\201\254\266<Sl\23h|,\245e\266\300\250}\314\n^\2\221A\226S<7`\272\263\254P\224)_\230uvNz$\277\3526\203\303%R\377\4\273  \rJ\333v\367\240x\232\270\335e\222\362+\367&n\202wH\266^\33\256F\37\351\213\277~Rt\362\265Y\210I\314-\271}3\330hi\252}\224\242B\264}S\17\272\7\241\324\217\36\f\260\2306\263b\177XK\311\35\210\244\317v\320&\331O\372\317\6\207\214\2452^\5\323$\333Vp\360\20e\367\266H\245J\362\30\212[O\31\376\226\23}>l\273K`K\250\354\353fO\212\224\35\237l\273b&\321h`\346\316$5M\351\224\342M-\255\266\227\361x\303t%\247\341\375\23\344\377@\266\273S\321\215\335\364_\22X\316\234\25`q\2\242S\rBR\244\213\250\27\341PHCq\370?C\335\262B\366\304IR\335u\265\375\3653\211\0328\222\261\211sB\20i\207]\371M\354+T\272x\177\261Y\205\253\346(\335\252X\337G\223\37*\244\236j8\240\353 B\275\375\362\306WW\375\352\270\224?\"'P\350\245\214\226]\262\373vt\201\37Q\276\303}\177\20\24\216\243J\3341<\351~\317\347\241\340\221\370YH\237s \335T?\234:Sv\250\\e\221<\321\6C\271`\376\301HQ\241\221\\\221\351\243\210\267\t\306\216\347\363_\10 9\34\3041\200\307\f9\326P\230\362f\371\6\310`B\375L\244\177\5\210u\336{q\205\302l\316\335\17\231,\17\276Mu\361gL\226\223\236O\207\315\225\345\253%d\312\2114\337\3428/\201f\352l\232\26\36{\341\300{\30\320\356]Xc\272\335?\336\24\6Q\210\30\26n\37X\243\rT$r#X\220\264\247,\27\n\321\363;q|<v&r\201#\31\1\32\313U\351h\353n\306\237\310\245\214\325\254}+\24\305q\337\246[K\215\331uMc8\177}\3317\250s\317Cgq\374\225\214a\324dv\4\30\347\366\304\23\4\f6\37i\202z\307\237\226]h3u\340C\314\305\336{M\326\342T:)\377\263\24\247\230 df(:-\264\364\240\346}4\ng\307\220\243\345\25\250\313\252}#)\356\325\7\277\272DHx\333DHM\237R\373u\31\262\227\226a\247\262cX\267\221\334]vZ\256\27\274\244-O+\255\340\226xl\220V\305\26h>\316RP4}\357>n\346\277\224\27\222l\301\260\224\253\310\r\215*\300]`2B\21d\332%2D\263]1\232\266\217\342?b\21\236\371E:\5\370L\344@\226*L\322@\353\363V\3379R\335\274\223q\205\344-\242\275B\325#\201\0028\"\262\34\vi\3221\315\216z~LS\2424\222\224\t\355\10\204\322^=E\316\264G\20i\25#\244\343*\366\264|S\2303oJ1\350\320\321O\236\202\33\307\302\3\306W\206\254\315d>$\23*\222\26\10gI\317\266\347\20\215^\321\235[\244\257\267\5\260\4T\4I\322\35\211F$\247A+\304\210g\227(\253w\346]\35\366\354\3217\200\236\324<\342\17_\2323\340\266C\201\36\300\364\252\213>I\2713a\203\335%\270\225\270\227q\32)c\342\200\315\251\335\357\20P\315^g\235\7\5@\\\314F\v\276$\256\247p\377W\33h\270\365\252d\f\16\336\333P\335\263\266\347\300\224\246a\345\373\321\341\345\206\345\220\256\376@^`X\356$p\234\215\3\\\375N\3\276\0357|\205#\365\254\344!\2659\23\361a&\324\255\266\2L-\263\274\276Hg\24F\267\16/\202\344\200\234\17\303\216\311&\367\5\227)G\16\211\204\223\371e\335\t\317\17\232\\\367sY3\334\37:s"..., 265523}], 1) = -1 EAGAIN (Resource temporarily unavailable)
close(172)                              = 0
futex(0x713da0, FUTEX_WAIT_PRIVATE, 2, NULL) = 0
futex(0x713da0, FUTEX_WAKE_PRIVATE, 1)  = 1
accept(5, {sa_family=AF_INET, sin_port=htons(9245), sin_addr=inet_addr("x.x.x.x")}, [16]) = 3264
ioctl(3264, FIONBIO, [0])               = 0
getsockname(3264, {sa_family=AF_INET, sin_port=htons(y), sin_addr=inet_addr("x.x.x.x")}, [16]) = 0
futex(0x713da0, FUTEX_WAIT_PRIVATE, 2, NULL) = 0
futex(0x713da0, FUTEX_WAKE_PRIVATE, 1)  = 1
setsockopt(3264, SOL_SOCKET, SO_LINGER, {onoff=0, linger=0}, 8) = 0
setsockopt(3264, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(3264, SOL_TCP, TCP_NODELAY, [1], 4) = 0
ioctl(3264, FIONBIO, [0])               = 0
poll([{fd=3264, events=POLLIN}], 1, 1)  = 1 ([{fd=3264, revents=POLLIN}])
read(3264, "GET /abc/xyz/image-t.jpg HTTP/1.1\r\nHost: www.abc.com\r\nUser-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36\r\nAccept: image/webp,image/apng,image/*,*/*;q=0.8\r\nAccept-Encoding: gzip\r\nAccept-Language: en-US,en;q=0.9\r\nCookie: _ga=GA1.2.562923030.1472453460; __gads=ID=5daeb41a8a133402:T=1530516884:S=ALNI_MaU7Inl4IDrXMwxXX8j_nv_Cl1p0g; _gid=GA1.2.934063802.1531104231; _gat=1\r\nX-IMForwards: 20\r\nVia: 1.1 pqr.com:80 \r\n\r\n", 32768) = 884
futex(0x7fc239309a44, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7fc239309a40, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7fbd2c0631a4, FUTEX_WAIT_PRIVATE, 1, NULL) = 0
futex(0x7fbd2c021738, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fbd2c0631a4, FUTEX_WAIT_PRIVATE, 3, NULL) = 0
futex(0x7fbd2c021738, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x713da0, FUTEX_WAIT_PRIVATE, 2, NULL) = 0
futex(0x713da0, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0x7fbd2c0631a4, FUTEX_WAIT_PRIVATE, 5, NULLc^Cstrace: Process 35154 detached
 <detached ...>

**Comment by Dridi** [comment]
If you don't have steps to reproduce, this is hardly actionable for us. We keep github issues for actual bug reports, otherwise we have options for support like mailing lists.

https://varnish-cache.org/support/

Please reopen this issue once you find a way to reproduce it. I also encourage you to avoid the 5.2 series, the current maintained branch is 6.0 and we recently released 6.0.1 with many fixes and improvements.
