### ISSUE TITLE
Review release docs for Varnish 6.1 (2018-09 release)

### ISSUE THREAD

**Issue by slimhazard** [varnishcache/varnish-cache#2774]
The 'Upgrading to 6.1' document currently has a first draft of release notes for the new release scheduled for Sep 17th. This includes everything I saw in the commit logs from 6.0.0 to now that in my own judgment is worth mentioning to end users.

All contributors are welcome and encouraged to proofread, revise, fix, add and subtract as they see fit. Go right ahead and push changes. For all I know I could have written up any detail incorrectly, or I may have completely missed a new feature that you think is important.

Some issues that I'm aware of:
* ~Not sure which CLI commands support ``-j`` for a JSON response (there's currently an **XXX** in the text).~
* Also not sure if the output of ``backend.list -v`` is described correctly.
* ~The section on ``req.ttl``, ``req.grace`` and keep links to the new docs about grace, but it touches on the the new features from #1799. Any changes in the capabilities of VCL from #1799 should be mentioned in the 'Changes to VCL' section, for example transitions from ``vcl_hit`` to ``vcl_miss`` or the other way around~ (a good subject for @hermunn).
* ~A review about the new diagnostics for fetch and accept failures (stats and logs) would be a good idea~ (thx @nigoroll).
* A review of the part about ``beresp.filters`` and VMOD-pluggable VFPs would be in order.
* ~The part in 'Changes for developers' about allocations of PRIV_TASK and PRIV_TOP objects may have errors.~ (thx @nigoroll)
* ~For the list of bugfixes I would just link to ``changes.rst``, but we should make sure that's up to date.~

But review efforts don't have to be limited to this list, since I don't know what I don't know, and you probably know better. %^)

**Comment by slimhazard** [comment]
'Upgrading' says that you may see ``stream`` in ``beresp.filters`` if ``beresp.do_stream`` has been set to true, but I'm not sure if that's correct. I do know that you may see any of ``gzip``, ``gunzip`` or ``esi``.

**Comment by nigoroll** [comment]
@slimhazard I don't think ``stream`` can surface as a filter, checked with ``git grep -A 1 "struct vfp .*="``

**Comment by slimhazard** [comment]
@nigoroll agreed, done

**Comment by hermunn** [comment]
I have created the pull request #2776, but the documentation on #1799 is accurate and good enough as it is. In other words, the third bullet point can be striked out, but the pull request can be considered.

**Comment by slimhazard** [comment]
@bsdphk says he's satisfied with the remaining items
