### ISSUE TITLE
No counter on v1d_error() ?

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2789]
There doesn't seem to be a VSC for late delivery errors (WS overflow) which triggers v1d_error()'s 500 response ?

**Comment by daghf** [comment]
Bikeshed time - 

Should this be the same counter for h/1.1 and h/2? (I think yes)

What's a good name? Some ideas: `resp_ws_overflow`, `sess_ws_overflow`, `deliver_ws_overflow` ?

**Comment by bsdphk** [comment]
We want a "500-counter" for delivery like client_req_400

We want per-ws-type (client/be/wrk) overflow counters

**Comment by daghf** [comment]
Fixed via #2798
