### ISSUE TITLE
varnish-6.0.1: Lots of segfaults when running test suite on el6/i686

### ISSUE THREAD

**Issue by ingvarha** [varnishcache/varnish-cache#2793]
This is when running the fedora rpm build for varnish-6.0.1 (still unreleased for fedora) on el6/i686 (mock chroot)

[test-suite.log](https://github.com/varnishcache/varnish-cache/files/2456271/test-suite.log)

I'll try some more debugging in an el6/i686 KVM tomorrow.

Ingvar

**Comment by Dridi** [comment]
FYI I'm still using a custom jemalloc-4.5.0 to not have segfaults on my x86_64 Fedora 28.

This looks different.

**Comment by ingvarha** [comment]
Note that I have only been able to reproduce this on el6, on i686. While still unsure what is causing this, I can get around it by removing either -fPIC or -fexceptions from CFLAGS.

**Comment by ingvarha** [comment]
epel6 uses the redhat %optflags macro, and I add -fPIC to that, so the effective CFLAGS on el6 are

-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -fPIC

**Comment by ingvarha** [comment]
I went with

%optflags -fno-exceptions -fPIC -ffloat-store

https://copr.fedorainfracloud.org/coprs/ingvar/varnish60/
