### ISSUE TITLE
Segregate VCC-only "VRT" symbols (related to VIP 20)

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2800]
Summary:

* Identify VRT symbols needed by VCC only (not for VMODs/Inline C)
* Bikeshed a new namespace for them (for example VCCRT)
* For 6.0 decide whether we can "break" such VRT symbols (see 20ab2abc36781b03605785c0a9ae463460cdffef)

Discussed this morning:

> 09:30 < dridi> phk: around?
09:31 < phk> yes
09:32 < dridi> hi
09:32 < phk> wassup ?
09:32 < dridi> i was working on backports on friday
09:32 < dridi> and i ran into another vip20 wall
09:33 < dridi> we have VRT_* (and a couple other) symbols for VMOD/inline C authors
09:33 < dridi> but some of the VRT symbols don't look like something we want to offer vmod authors
09:34 < phk> Strictly speaking VRT is for both VCC, VMOD and inline-C
09:34 < dridi> for example, trying to backport 20ab2abc36781b03605785c0a9ae463460cdffef (Only dlclose() Vmods after all "fini" processing.)
09:34 < dridi> we have a VRT change
09:35 < dridi> but something that looks like should only be used by VCC-generated code
09:35 < dridi> namely VRT_Vmod_Unload (formerly known as VRT_Vmod_Fini)
09:36 < dridi> so in our endeavour to nail down the VRT ABI (looping back to vip 20)
09:36 < dridi> would it make sense to have VCCRT_* symbols to differentiate them from VRT_*
09:36 < dridi> ?
09:37 < phk> I've thought about finer splitting of the API/ABI's, but if somebody calls those functions from a VMOD or inline-C I really don't care...
09:37 < dridi> so you think it might be ok for a vmod to manually load another vmod?
09:37 < phk> I mean, yeah, ideally it would all be segregated and clearly labeled, but in practice...
09:37 < phk> no I think it would explode on them
09:37 < phk> which is also a way of saying "do not call this function"
09:38 < dridi> yes
09:38 < dridi> a different namespace would help imho
09:38 < phk> well, if we want to do that, it will be a 7.0 thing I guess...
09:38 < dridi> i'd like to bring this up during bugwash if you don't care
09:39 < phk> sure
09:39 < dridi> i don't think that requires a .0 release, we (almost?) always a major VRT bump for our bi-annual releases
09:40 < phk> true, and people shouldn't be calling these anyway

**Comment by nigoroll** [comment]
bugwash concensus:
* ok to _break VRT_Vmod_(Fini|Unload) in 6.0 and proceed with backports towards 6.0.2_
* @Dridi to come back with a list of functions

**Comment by Dridi** [comment]
I haven't started enumerating all VRT symbols so I'll keep track of those I accidentally found:

- VRT_Vmod_Init
- VRT_Vmod_Unload
- VRT_BundleStrands

**Comment by Dridi** [comment]
I reviewed `vrt.h` but not `vrt_obj.h` because of its very nature (eventually I did for completeness).

Here goes my list of things that should be exposed only to VCC-generated code:

- struct vrt_type
- struct vmod_data
- struct vrt_ref
- VRT_count
- VRT_Vmod_Init
- VRT_Vmod_Unload
- VRT_BundleStrands

If you get a chance, please review before next bugwash.

I would paint my bikeshed with a `VCCRT_` namespace located in `vrt_vcc.h` and not install that header.

**Comment by Dridi** [comment]
@nigoroll makes a good case to keep VRT_BundleStrands around as a convenience for vmod authors. I have no strong feeling about that one :)

**Comment by nigoroll** [comment]
after my discussion with @Dridi 1:1 I think we should just keep those functions to VCCRT which we do not want vmod authors to touch. So +1 for all but `VRT_BundleStrands`.

**Comment by Dridi** [comment]
Upon further inspection, I have a new candidate: `VRT_VSA_GetPtr`.

**Comment by nigoroll** [comment]
-1 on blacklisting `VRT_VSA_GetPtr`: vmods could hold a suckaddr for other good reasons and it does not match the _just isolate those functions to VCCRT which we do not want vmod authors to touch_ paradigm

**Comment by bsdphk** [comment]
I have started this process now.  Prototypes go in include/vcc_interface.h and the namespace is VPI_

**Comment by Dridi** [comment]
Bugwash consensus: I sweep the tree and either close this ticket or challenge other definitions.

**Comment by Dridi** [comment]
@bsdphk, any reason why `struct vrt_type` wasn't moved to VPI considering that today only VCC code uses it?

Could this be related to type/symbol ongoing work?

If not, should we have vmod-debug or vmod-vtc coverage to show how a VMOD author may use it?

**Comment by Dridi** [comment]
I will revisit this once the dust settles in libvcc, for now we can't make a decision.

**Comment by bsdphk** [comment]
Note:  if we decide 2020-03½ is 7.0, this needs a line-by-line review of cache.h and vrt.h

**Comment by Dridi** [comment]
We keep `struct vrt_type` visible to allow runtime argument introspection in the future if the need arises, even though today only `libvcc` uses it.

**Comment by Dridi** [comment]
I found new candidates for VPI: the `VRT_re_{init,fini}()` functions. They are clearly here to support libvcc and only serve as thin wrappers around VRE functions.

Plus, this comment:

> ```
> /* This was already check-compiled by the VCL compiler */
> ```

**Comment by Dridi** [comment]
#3489 takes care of `VRT_re_init()` and `VRT_re_fini()`.

**Comment by bsdphk** [comment]
I am going to close this ticket now.  I think we have caught the worst "pollution", and from here it will be an ongoing activity of API-design.
