### ISSUE TITLE
varnish starts a bg_fetch even the object TTL has not expired !

### ISSUE THREAD

**Issue by Malkocoglu** [varnishcache/varnish-cache#2805]
I recently upgraded some members of a varnish farm to varnish-5.0.0 (debian-9.2). All the metrics were good except the backend_req value. Although varnish instance has a >95% hit rate, backend_req value is around 65% of client_req value, which is too high for our type (image files) of load. The backend_req/client_req for varnish 2.1.5 (which gets the same traffic) server is around 5%.

The TTL values in the VCL code are all 10d as we are serving static (image) files from this domain. I also adjusted the default_ttl parameter to 864000 (10d) so that objects' lifetime is at least 10 days as there is no memory pressure. But the backend_req value never declined.

Then I cross-checked docs to code. According to docs, varnish should not start a bgfetch for objects whose TTL has not expired. But (version 5.0.0) in file bin/varnishd/cache/cache_req_fsm.c around line 410 right after VCL_hit_method is called, when the wrk->handling value is VCL_RET_DELIVER and busy != NULL, VBF_Fetch(wrk, req, busy, oc, VBF_BACKGROUND) is issued without checking the TTL of that object (or any other lifetime related check).

## Expected Behavior

varnish should check the TTL of the object before issuing a background fetch.

## Current Behavior

varnish does not check the TTL of the object before issuing a background fetch.

## Possible Solution

?

## Steps to Reproduce (for bugs)

```
sub vcl_hit { // this is from stackoverflow.com and makes sense for our config
    if (obj.ttl >= 0s) {
        return (deliver);
    }

    if (std.healthy(req.backend_hint))
    {
        if((obj.ttl + 30s) >= 0s){
            return (deliver);
        }else{
            return (pass);
        }
    }
    else
    {
        if((obj.ttl + obj.grace) >= 0s){
            return (deliver);
        }else{
            return (pass);
        }
    }
    // if we did not handle it, let the default do its job...
}

sub vcl_backend_response {
    if ((bereq.backend == active.backend() || bereq.backend == passive.backend() || bereq.backend == activeFB.backend()) &&
        (beresp.status == 404 || beresp.status == 500 || beresp.status == 503)) {
        // here we retry when we get 404, because backends have different set of images 
        return(retry);
    }

    set beresp.http.X-Backend = bereq.backend;

    if (beresp.status == 404) {
        set beresp.ttl   = 60s;
        set beresp.grace =  1h;
    } else {
        set beresp.ttl   = 10d;
        set beresp.grace =  1h;
    }
}

```
1. set default_ttl = 864000
2. use functionally identical VCL in old/new varnish instances
3. after some heavy traffic, compare backend_req value(s) from new (5.0.0) and old (2.1.5) versions of varnish

## Context

varnish should cache and serve all the NOT-expired objects without requesting them from the backend. Otherwise backend servers have a hard time handling all these varnish requests. Varnish becomes a tunnel instead of a cache.

## Your Environment

* Version used: varnish-5.0.0 revision 99d036f
* Operating System and version: debian 9.2
* Source of binary packages used (if any): official stable debian 9.2 repository

**Comment by nigoroll** [comment]
this should have long been fixed and 5.0.0 is `Retired` for ages - see http://varnish-cache.org/releases/index.html
Please reopen should you see such behavior with a fresh/supported release.

**Comment by nigoroll** [comment]
Apologies, I think my explanation was wrong due to my bad memory, actually I now think we never had this bug and I was confusing it with something else.
But looking at your VCL, I'd guess you should double check the `return(pass)` statements in your vcl_hit, it would appear to me that expired objects in grace would never be fetched and that your load does not stem from bgfetches but rather the passes.

At any rate, github issues are for real bugs with supported code. For anything else please refer to other options: http://varnish-cache.org/support/index.html

**Comment by Malkocoglu** [comment]
varnishstat reports cache_hitpass something around 0. I will re-test without my custom vcl_hit. I will then observe the behavior with only the default vcl_hit...

**Comment by Dridi** [comment]
I wouldn't expect hitpass when we reach `vcl_backend_response` with `bereq.uncacheable` already true. Maybe this was undefined behavior "fixed" by the recent work on #1799.

FWIW we reintroduced `req.grace` so the desired behavior can be achieved in `vcl_recv` instead of `vcl_hit` without the need for spurious passes. Available in 6.0.1+:

https://varnish-cache.org/docs/6.0/reference/vcl.html?highlight=req.grace

**Comment by Malkocoglu** [comment]
The problem was related to the built-in VCL code injected into the vcl_recv subroutine. vcl_hit and vcl_backend_response were the red herrings. As I changed those subroutines during the update and also read about the bgfetch feature addition, I had wrongfully focused on those.

Sorry for taking your time, best of luck...

**Comment by Dridi** [comment]
We'd rather know if we break VCL, we version it to normally ensure an upgrade path. So thanks for letting us know this was a false positive, better that than the other way around ;-)
