### ISSUE TITLE
Can't overtake 4898 threads

### ISSUE THREAD

**Issue by Francois-v3** [varnishcache/varnish-cache#2822]
Hello,

i have a new issue with varnish 6.1.0/6.1.1 which was not in 6.0.1: I can't overtake 5000 threads.

More, when i reach the limit, threads.failed get stuck at 10 by second (for ever).

Requests are still served (perhaps with some lag). Reducing to very few traffic does not fix it. Traffic is mainly H2/UDS.

Neither VCL reload. Trying to reload shows that fork is not possible:

# varnishadm vcl.load toto /etc/varnish/default.vcl
Starting VCC-compiler: fork() failed: Resource temporarily unavailableVCL compilation failed
Command failed with error code 106

If I set thread_pool_max to 2400. Things are ok: going to 4800 threads (max) and reducing thread from 4800 to 3000 as traffic is reducing. And I can do it several times, obtaining a MAIN.threads_created greater than 6000.

varnishstat

MAIN.pools 2          0.00           .            2.00          2.00 2.00
MAIN.threads 4898          0.00           .         4898.00       4898.00 4898.00
MAIN.threads_limited 3          0.00          0.00          0.00          0.00 0.00
MAIN.threads_created 5050          0.00          0.07          0.00 0.00          0.00
MAIN.threads_destroyed 152          0.00          0.00          0.00 0.00          0.00
**MAIN.threads_failed 1380          9.98          0.02          9.62 9.83          9.83**
MAIN.thread_queue_len 0          0.00           .            6.26         10.05 10.05
MAIN.busy_sleep 1160          0.00          0.02          0.02 0.04          0.04
MAIN.busy_wakeup 1160          0.00          0.02          0.02 0.04          0.04

# varnishadm param.show | grep thread
cc_command                    exec gcc -g -O2 -fdebug-prefix-map=/build/varnish-ICggro/varnish-6.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -Werror -Wno-error=unused-result -pthread -fpic -shared -Wl,-x -o %o %s (default)
thread_pool_add_delay         0.000 [seconds] (default)
thread_pool_destroy_delay     1.000 [seconds] (default)
thread_pool_fail_delay        0.200 [seconds] (default)
thread_pool_max               5000 [threads] (default)
thread_pool_min               1500 [threads]
thread_pool_reserve           0 [threads] (default)
thread_pool_stack             48k [bytes] (default)
thread_pool_timeout           300.000 [seconds] (default)
thread_pool_watchdog          10.000 [seconds] (default)
thread_pools                  2 [pools] (default)
thread_queue_limit            20 (default)
thread_stats_rate             10 [requests] (default)
workspace_thread              2k [bytes] (default)

vcache    4154 28.9  9.9 11243260 9831220 ?    SLl  Nov01 357:21 /usr/sbin/varnishd -a :80 -a 127.0.0.1:6080,PROXY -a [::1]:6080,PROXY -a /var/lib/haproxy/varnish.sock,PROXY,mode=666 -T localhost:6082 -f /etc/varnish/default.vcl -s malloc,50g -t 0 -p thread_pool_min=1500 -p thread_pool_max=5000 -p feature=+http2

# cat /proc/4154/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited unlimited            seconds
Max file size             unlimited unlimited            bytes
Max data size             unlimited unlimited            bytes
Max stack size            8388608 unlimited            bytes
Max core file size        unlimited unlimited            bytes
Max resident set          unlimited unlimited            bytes
Max processes             386121 386121               processes
Max open files            262144 262144               files
Max locked memory         82000 82000                bytes
Max address space         unlimited unlimited            bytes
Max file locks            unlimited unlimited            locks
Max pending signals       386121 386121               signals
Max msgqueue size         819200 819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited unlimited            us

# uname -a
Linux cdn2.xxxxx.fr 4.15.0-38-generic #41-Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 18.

-- 
François Veux

**Comment by nigoroll** [comment]
This is highly unlikely to be a varnish issue. Because we have reserved github issues for real bugs, please refer to support options: http://varnish-cache.org/support/index.html
Most likely you have run out of memory. The fork failure is pretty clear.
Other hints:
* check `/proc/meminfo` 
* check why worker thread creation is failing: `varnishlog -g raw -I Debug:thread`

**Comment by razvanphp** [comment]
We have the exact same problem with Varnish 6.0.1 and Debian Stretch, we can't even reload when the max number of threads is reached (usually after a load test or many slow requests to backend).

In our case, the server has enough memory free left, 50% actually:
```
# varnishlog -g raw -I Debug:thread
         0 Debug          - "Create worker thread failed 11 Resource temporarily unavailable%00"
         0 Debug          - "Create worker thread failed 11 Resource temporarily unavailable%00"
         0 Debug          - "Create worker thread failed 11 Resource temporarily unavailable%00"
$ cat /proc/1442/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             245554               245554               processes
Max open files            1048576              1048576              files
Max locked memory         unlimited            unlimited            bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       245554               245554               signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
$ sudo cat /proc/meminfo
MemTotal:       62884004 kB
MemFree:        21346604 kB
MemAvailable:   35106344 kB
Buffers:          127068 kB
Cached:         13929128 kB
SwapCached:            0 kB
Active:         26647824 kB
Inactive:       13696792 kB
Active(anon):   26375008 kB
Inactive(anon):    78444 kB
Active(file):     272816 kB
Inactive(file): 13618348 kB
Unevictable:      107404 kB
Mlocked:          107404 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               332 kB
Writeback:             0 kB
AnonPages:      26395812 kB
Mapped:           229984 kB
Shmem:             79296 kB
Slab:             621656 kB
SReclaimable:     576280 kB
SUnreclaim:        45376 kB
KernelStack:       82608 kB
PageTables:        60044 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    31442000 kB
Committed_AS:   29140648 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       81920 kB
DirectMap2M:     8306688 kB
DirectMap1G:    57671680 kB
```

Can you please provide us maybe one more hint? Maybe others will get into this... we don't remember having it on 4.1.

Thank you!

**Comment by razvanphp** [comment]
one of the latest AFAIK:
```$ uname -a
Linux varnish-server 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```
in systemd unit file we also have:
```
LimitNOFILE=infinity
LimitMEMLOCK=infinity

**Comment by nilsmeyer** [comment]
Can you check the kernel log buffer? `dmesg -T`
A shot in the dark: Perhaps you have exhausted the available process ids

```
sudo sysctl kernel.pid_max # get current value, default is 32768
sudo sysctl -w kernel.pid_max=2097152 # increase limit, persist in /etc/sysctl.d
```

**Comment by razvanphp** [comment]
dmesg:
```
[Wed Nov 21 20:06:43 2018] ena: Feature 27 isn't supported
[Wed Nov 21 20:16:43 2018] ena: Feature 27 isn't supported
[Wed Nov 21 20:22:30 2018] cgroup: fork rejected by pids controller in /system.slice/varnish.service
[Wed Nov 21 20:26:43 2018] ena: Feature 27 isn't supported
[Wed Nov 21 20:36:43 2018] ena: Feature 27 isn't supported
[Wed Nov 21 20:46:43 2018] ena: Feature 27 isn't supported
```
I increased the max pid number but the error persists:
```
# sudo sysctl kernel.pid_max
kernel.pid_max = 32768
# sudo sysctl -w kernel.pid_max=2097152
kernel.pid_max = 2097152

**Comment by nilsmeyer** [comment]
I believe the limit you're looking for is pids.max in the cgroup, you can set this in your systemd unit: `TasksMax`

**Comment by Francois-v3** [comment]
Did you set
TasksMax=infinity
in the varnish service Unit ?

**Comment by nigoroll** [comment]
Not sure if this is relevant because of the systemd suspicion, but Re
https://github.com/varnishcache/varnish-cache/issues/2822#issuecomment-440796879

> In our case, the server has enough memory free left, 50% actually:

MemFree is not relevant, it is Committed_AS vs. CommitLimit, quoting from above:

```CommitLimit:    31442000 kB
Committed_AS:   29140648 kB
```

Ref: https://github.com/torvalds/linux/blob/master/Documentation/filesystems/proc.txt#L941

The (stupid, IMHO) linux concept of overcommitting makes this figure only relevant for `vm.overcommit_memory = 2`, so we need to know that value also. Ref: https://github.com/torvalds/linux/blob/master/Documentation/vm/overcommit-accounting.rst

So can you please:
* also paste your `sysctl -a -r '^vm\.'`
* check if increasing `vm.overcommit_ratio` helps, to maybe 90 (% that is)?

Also just to double check: You did restart varnish after changing the sysctls?

**Comment by Francois-v3** [comment]
On my side, I can confirm that the problem came from systemd. With TasksMax=infinity in the varnish service Unit, there's no more problem.
Ubuntu 18 use a new realease of systemd which implements pid manager.

**Comment by razvanphp** [comment]
Yes, this solved it for us too, thank you!

Maybe varnish packages should tune the default 4915 value.

**Comment by Dridi** [comment]
Moved to https://github.com/varnishcache/pkg-varnish-cache/issues/118, thanks everyone.
