### ISSUE TITLE
VIP decision points

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2830]
This issue is to request discussion regarding the following vips:

* decide on VIP1 https://github.com/varnishcache/varnish-cache/wiki/VIP1:-PRIV_*-visibility-and-lifetime-control

IMHO should be closed and `VRT_priv_top()` / `VRT_priv_task()` should be gold-plated as the official interface.

* close VIP17 (if @slimhazard is not already doing this in the meantime) https://github.com/varnishcache/varnish-cache/wiki/VIP-17:-Enable-Unix-domain-sockets-for-listen-and-backend-addresses

* close VIP11 https://github.com/varnishcache/varnish-cache/wiki/VIP11:-Shared-Memory-revamp

IMHO, that's implemented

* do VIP16 https://github.com/varnishcache/varnish-cache/wiki/VIP16:-Retire-parameters-aliases

I think it's really about time to retire these now

* review VIP9 https://github.com/varnishcache/varnish-cache/wiki/VIP9:-Expand-VCL-object-support

This might be considered OBE with https://code.uplex.de/uplex-varnish/varnish-objvar

**Comment by nigoroll** [comment]
bugwash conclusion:

* Keep VIP1 by request of @bsdphk 
* Close VIP11: Dynamic VSCs are done, dynamic SLTs are non-trivial and using a fixed tag with a string prefix achieves the same (e.g. `VCL_Log` / `std.log()`) at low overhead
* Close VIP17: Ask @slimhazard if any details need to be saved from it, but it's done by and large
* Close VIP16
* VS folk will ping @rezan about VIP9

**Comment by nigoroll** [comment]
all ticked off except for VIP9 -> @rezan

**Comment by rezan** [comment]
Im not sure what the ask is here?

> This might be considered OBE with https://code.uplex.de/uplex-varnish/varnish-objvar

Is there a write up on what objvar is doing? Its not clear what is being introduced...? What does OBE mean?

**Comment by nigoroll** [comment]
@rezan OBE is "overtanken by events". The question is if you would consider the objvar vmod-bundle a replacement for your proposal in VIP9. The overview is given in https://code.uplex.de/uplex-varnish/varnish-objvar/blob/master/README.rst

**Comment by rezan** [comment]
So my proposal introduced request scoped objects which could be used anywhere in VCL. Your proposal just implements this using traditional global objects? I would say I like my proposal better because it matches how variables are used in other languages, basically define and use them locally to your logic.

Other than that, the only feedback would be that constants should be implemented as C `#define` macros at the VCC level and compiled in as a constant or literal. They do not need to involve runtime code.

**Comment by nigoroll** [comment]
> So my proposal introduced request scoped objects which could be used anywhere in VCL. Your proposal just implements this using traditional global objects?

Yes and no. In the technical sense, the objects are global, but the scope as seen by the VCL developer is per task or topreq.

> constants should be implemented as C #define macros at the VCC level and compiled in as a constant or literal.

Agree for a VCC change. As we did not get native VCC variables for the past years, I think the vmod_constant solution is second best: It requires function calls at VCL run time, but it does not require VCC changes.

**Comment by rezan** [comment]
> but the scope as seen by the VCL developer is per task or topreq

So in this example:

```vcl
vcl_init {
     new xtask_int = taskvar.int(5);
}
```

Isn't `xtask_int` in a global scope now? How does that `5` move to a task? So these objects are mixed scope?

**Comment by rezan** [comment]
So for my proposal, objects have 1 scope and that is transparent to the object.

Looking back, scope matters for safety. VCL (global) scope means the object needs to be thread safe. Request (task) scope means the object can assume a single thread. Apart from that, scope is of no concern.

**Comment by nigoroll** [comment]
@rezan I had mentioned the documentation in the hope that you would maybe read it, alternatively feel free to read the source. The relevant bit for the topreq/task variables is to get a VRT_priv_task / VRT_priv_top with the id of the global object, e.g. here https://code.uplex.de/uplex-varnish/varnish-objvar/blob/master/src/vmod_taskvar.c#L77 which is called from the template code, e.g. here https://code.uplex.de/uplex-varnish/varnish-objvar/blob/master/src/tasktop.h#L93

In the `new xtask_int = taskvar.int(5);` example, 5 is a default, which gets stored in a vcl object. Whenever used, the varniable's scope is the task though because its value is stored via a VRT_priv_tsak as explained above.

> VCL (global) scope means the object needs to be thread safe. Request (task) scope means the object can assume a single thread.

yes, that's the implementation.

**Comment by nigoroll** [comment]
Maybe I should also have pointed to the more detailed documentation which, for example here https://code.uplex.de/uplex-varnish/varnish-objvar/blob/master/src/vmod_taskvar.rst#description

**Comment by rezan** [comment]
Right, this is similar to how the original object patch was implemented:

https://github.com/rezan/varnish-cache/commit/b547bd9ad2fca9db1ef17ee73b8e9b7df9950c34

(see `VRT_priv_task_object` and the thread discussing why that had to be done)

I still think the VIP9 patch accomplishes 2 things here:

* gives VCL writers variables which can be defined and used anywhere. This makes VCL better and easier to use.
* gives VMOD writers a simple object model. The reason I was asking about the mixed scopes is because that requires the VMOD author to jump thru several mental model hoops. I think we can do something much better than that. I think its important to keep the VMOD dev experience in mind here.

**Comment by nigoroll** [comment]
I do fully agree: Native VCC-supported variables (which could also hold objects) would be the optimal solution, which we also had discussed during VDDs. Also your remark on the mental model hoops is true.

I brought this question back on the table because
* from the VCL perspective, it appeared to me that the only difference is the declaration
* The VIP9 route has some more obstacles for which, IIUC, we have not yet found good solutions. (your discussion with @mbgrydeland in https://varnish-cache.org/lists/pipermail/varnish-dev/2016-November/009037.html ) In particular, we have not even solved the null object issue for the vcl scope (the `if(false) { new ...` in vcl_init case)

So, to wrap this up, I am fine with keeping VIP9, I just wanted to ask if we should consider it still relevant because there are other viable ways to achieve the same semantics.
