### ISSUE TITLE
Unable To install php72 ext on Centos7 - current dependencies available are obsolete 

### ISSUE THREAD

**Issue by haxcop** [varnishcache/varnish-cache#2847]
Currently tryin' to install lastest Varnish with PhP72 is impossible, I can't find a solution anywhere, hopefully you guys can help me out.
### Downloaded the package manually 
`root@localhost ]# rpm -ivh /home/user/php72-php-pecl-varnish-1.2.4-1.el7.remi.x86_64.rpmerror: ` `Failed dependencies:
        libvarnishapi.so.1()(64bit) is needed by php72-php-pecl-varnish-1.2.4-1.el7.remi.x86_64
        libvarnishapi.so.1(LIBVARNISHAPI_1.0)(64bit) is needed by php72-php-pecl-varnish-1.2.4-1.el7.remi.x86_64`
        `libvarnishapi.so.1(LIBVARNISHAPI_1.2)(64bit) is needed by php72-php-pecl-varnish-1.2.4-1.el7.remi.x86_64`

### via Pecl

`checking for pkg-config... /usr/bin/pkg-config
checking for varnish files in default path... not found
configure: error: Please reinstall the varnish distribution
ERROR: `/tmp/pear/temp/varnish/configure --with-php-config=/usr/local/apps/php72/bin/php-config' failed
[root@localhost ]#`

I have installed Varnish via yum and also manually in several ocasions but the same result, also looking for the dependencies required seems to be obsoletes for the current version 6.1.1

**Comment by Dridi** [comment]
That is because starting with 6.1 we had an soname bump so `libvarnishapi.so.1()(64bit)` is now `libvarnishapi.so.2()(64bit)` (see #2710).

I recommend Varnish 6.0 LTS if you don't need specific features from the 6.1 release.

**Comment by haxcop** [comment]
@Dridi Thanks for your prompt reply, but I'm still unable to connect Varnish with php72 seem that the extension is not been found anywhere. 
My output is the following. 
I appreciate your help in this matter

`checking for pkg-config... /usr/bin/pkg-config`
`checking for varnish files in default path... not found`
`configure: error: Please reinstall the varnish distribution`
`ERROR:'/tmp/pear/temp/varnish/configure --with-php-config=/usr/local/apps/php72/bin/php-config' `failed`


[root@centos7 ~]# yum search varnish
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.heanet.ie
 * epel: www.mirrorservice.org
 * extras: ftp.heanet.ie
 * remi-safe: remi.mirror.wearetriple.com
 * updates: ftp.heanet.ie
========================================= N/S matched: varnish ==========================================collectd-varnish.x86_64 : Varnish plugin for collectd
php-pecl-varnish.x86_64 : Varnish Cache bindings
php54-php-pecl-varnish.x86_64 : Varnish Cache bindings
php55-php-pecl-varnish.x86_64 : Varnish Cache bindings
php56-php-pecl-varnish.x86_64 : Varnish Cache bindings
php70-php-pecl-varnish.x86_64 : Varnish Cache bindings
php71-php-pecl-varnish.x86_64 : Varnish Cache bindings
php72-php-pecl-varnish.x86_64 : Varnish Cache bindings
php73-php-pecl-varnish.x86_64 : Varnish Cache bindings
varnish-devel.x86_64 : Development files for varnish
varnish-docs.x86_64 : Documentation files for varnish
varnish-libs.x86_64 : Libraries for varnish
varnish-libs-devel.x86_64 : Development files for varnish-libs
varnish.x86_64 : High-performance HTTP accelerator

  Name and summary matches only, use "search all" for everything.
[root@centos7 ~]# yum install php72-php-pecl-varnish.x86_64
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.heanet.ie
 * epel: www.mirrorservice.org
 * extras: ftp.heanet.ie
 * remi-safe: remi.mirror.wearetriple.com
 * updates: ftp.heanet.ie
varnishcache_varnish60lts/x86_64/signature                                        |  836 B  00:00:00
varnishcache_varnish60lts/x86_64/signature                                        | 1.0 kB  00:00:00 !!!
varnishcache_varnish60lts-source/signature                                        |  836 B  00:00:00
varnishcache_varnish60lts-source/signature                                        | 1.0 kB  00:00:00 !!!
Resolving Dependencies
--> Running transaction check
---> Package php72-php-pecl-varnish.x86_64 0:1.2.4-1.el7.remi will be installed
--> Processing Dependency: libvarnishapi.so.1(LIBVARNISHAPI_1.0)(64bit) for package: php72-php-pecl-varnish-1.2.4-1.el7.remi.x86_64
Package varnish-libs-4.0.5-1.el7.x86_64 is obsoleted by varnish-6.0.2-1.el7.x86_64 which is already installed
--> Processing Dependency: libvarnishapi.so.1(LIBVARNISHAPI_1.2)(64bit) for package: php72-php-pecl-varnish-1.2.4-1.el7.remi.x86_64
Package varnish-libs-4.0.5-1.el7.x86_64 is obsoleted by varnish-6.0.2-1.el7.x86_64 which is already installed

**Comment by Dridi** [comment]
I think you should bring this to @remicollet instead, because it ap-pear-s (pun intended) that a configure script running from his packaging is failing to locate your varnish setup. It might be that you are simply missing the `varnish-devel` package.

I'm not reopening this issue but if it turns out to be a packaging bug on our end, please open a new one in the varnishcache/pkg-varnish-cache project instead of here.

**Comment by haxcop** [comment]
> I think you should bring this to @remicollet instead, because it ap-pear-s (pun intended) that a configure script running from his packaging is failing to locate your varnish setup. It might be that you are simply missing the `varnish-devel` package.
> 
> I'm not reopening this issue but if it turns out to be a packaging bug on our end, please open a new one in the varnishcache/pkg-varnish-cache project instead of here.

@Dridi Thanks, was missing `varnish-devel` which is not stated on any documentation related to the installation.
