### ISSUE TITLE
ESI vs return(vcl(label))

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2849]
I was reviewing code while working on 6.0 back-ports and found something fishy, but I failed to exhibit side effects in a test case so I'm dropping my notes here instead to pick them up later (or give the opportunity to someone else).

ESI is one of those areas where I know almost nothing about the implementation details so take my observations with a gain of salt. I think that ESI sub-requests borrow the VCL reference of their parent request so that effectively only one worker in an ESI sequence holds the ref. And since it's sequential, moving the ref between requests shouldn't be a problem.

We can see the sub-request borrow the VCL here:

https://github.com/varnishcache/varnish-cache/blob/cca34010d11950b04cae41ccdd2cd94ed4ae86a6/bin/varnishd/cache/cache_esi_deliver.c#L168-L170

And later in the same function it's given back to the parent request:

https://github.com/varnishcache/varnish-cache/blob/cca34010d11950b04cae41ccdd2cd94ed4ae86a6/bin/varnishd/cache/cache_esi_deliver.c#L204-L206

Seeing this piece of code I asked myself how this would cope with VCL switching:

```vcl
sub vcl_recv {
    if (req.esi_level > 0) {
        return (vcl(label));
    }
}
```

I can't find a way to make things going haywire, the best I could do is a crude patch to show that the reference can indeed change during the transaction:

```diff
diff --git i/bin/varnishd/cache/cache_esi_deliver.c w/bin/varnishd/cache/cache_esi_deliver.c
index 9d1fd4782..f6df8ca95 100644
--- i/bin/varnishd/cache/cache_esi_deliver.c
+++ w/bin/varnishd/cache/cache_esi_deliver.c
@@ -167,6 +167,7 @@ ved_include(struct req *preq, const char *src, const char *host,
 
        AZ(req->vcl);
        req->vcl = preq->vcl;
+       VSLb(preq->vsl, SLT_Debug, "preq->vcl=%p", preq->vcl);
        preq->vcl = NULL;
 
        req->req_step = R_STP_RECV;
@@ -203,6 +204,7 @@ ved_include(struct req *preq, const char *src, const char *host,
 
        AZ(preq->vcl);
        preq->vcl = req->vcl;
+       VSLb(preq->vsl, SLT_Debug, "preq->vcl=%p", preq->vcl);
        req->vcl = NULL;
 
        req->wrk = NULL;
```

With this patch and a simple VTC I can witness `preq->vcl` change after the ESI req completes:

```
**** v1    1.1 vsl|       1001 Debug           c preq->vcl=0x7f33010d7700
**** v1    1.1 vsl|       1001 Debug           c preq->vcl=0x7f33010d72a0
```

Whatever I do in my test case, `req_top` never seems to be bothered by its VCL changing under its feet. I will resume my investigation next week.

**Comment by nigoroll** [comment]
I don't understand why we should allow to switch to a label from ESI. It would appear sensible  to me to keep all the ESI processing within one label to reduce the risk of running into fierce edge cases.

**Comment by gquintard** [comment]
One label use case I have is using them to isolate backend-specific backend ("you go there, and you only see the conf for it"). That's useful for teams that want to have control over their VCL, but IT don't want their code bleeding all over. But that doesn't mean the ESI is going to be strictly local to their backend, and they may want to incorporate fragment from all over.

**Comment by rezan** [comment]
Agree with @gquintard 

If you have a label per host, I see no reason why includes can span multiple hosts. I do remember seeing Host in the ESI code. I know this is a big use case for Edgestash.

**Comment by rezan** [comment]
@dridi I would check the VCL refcounts. The label switch could be causing the patent to deref the wrong VCL.

**Comment by Dridi** [comment]
@nigoroll I'm not saying we should allow that, or not allow that. But as of today VCL allows you to switch to a label from ESI and I found something possibly worthy of a review, or a red herring. I'll look again on Monday, and we can discuss what should be allowed or not during the bugwash :)

**Comment by Dridi** [comment]
@rezan I tried some VCL discarding and listing in my VTC attempts, to no avail.

**Comment by slimhazard** [comment]
I know of at least one project for which switching the label in an ESI could be the altogether intuitive thing to do (@nigoroll you might be able to guess which project I'm thinking of). They don't in fact do it that way, but it's been under consideration, with just the sort of scenario @gquintard has described -- ESIs are used extensively to direct part of request processing to an app that one dev team is responsible for, and that can be reflected in VCL by use of labels.

If this is too difficult in Varnish's implementation, or if the edge cases are too much trouble, we could reasonably decide to restrict it. But I would definitely +1 the view that, from the perspective of authoring VCL, it can be an intuitive choice.

**Comment by bsdphk** [comment]
My conclusion so far is that the switched VCL does not contaminate anything.

We do however have a refcounting problem.

**Comment by bsdphk** [comment]
Bugwash concensus-ish:

1. ESI child requests should start out in the same VCL as the top request did.  (NB: Not the same as active_vcl!)

2. A feature-flag (default=off) can enable ESI child requests to start in parents VCL.

3. ref-counting must be fixed.
