### ISSUE TITLE
hitpass turning into hitmiss after ttl

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2864]
It looks like hitpass objects last for the whole TTL + grace + keep period, and when they are hit beyond their TTL they turn into a hitmiss instead:

```vcl
varnishtest "hfp without ttl"

server s1 -repeat 2 {
        rxreq
        txresp
} -start

varnish v1 -vcl+backend {
        sub vcl_backend_response {
                #set beresp.ttl = 0.1s;
                #set beresp.grace = 0s or 10s;
                #set beresp.keep = 100s;
                return (pass);
        }
} -start

client c1 {
        txreq
        rxresp

        delay 0.5

        txreq
        rxresp
} -run

varnish v1 -vsc *cache_hit*
varnish v1 -expect cache_hitpass == 1
```

If you add the lines commented out to make the hit happen during either grace or keep this test will fail because `cache_hitmiss` is incremented instead.

**Comment by bsdphk** [comment]
@Dridi moves this to a VIP until we have an actionable concensus.

**Comment by bsdphk** [comment]
VIP24: https://github.com/varnishcache/varnish-cache/wiki/VIP-24%3A-Hitpass-turning-into-hitmiss-after-ttl

**Comment by Dridi** [comment]
I understand that #2865 was turned into a VIP, but this is a bug. I would like to reopen this issue and investigate it myself.
