### ISSUE TITLE
STRANDS regression

### ISSUE THREAD

**Issue by steven-j-wojcik** [varnishcache/varnish-cache#2873]
## Expected Behavior

A function taking in a  `STRANDS` parameter from a function returning a `STRANDS` object results in an assert error. Given the additional debug function below, I would expect the provided VTC below that to pass. This affects master and 6.0.

```diff
diff --git a/lib/libvmod_debug/vmod.vcc b/lib/libvmod_debug/vmod.vcc
index e3fb3cf..5faa718 100644
--- a/lib/libvmod_debug/vmod.vcc
+++ b/lib/libvmod_debug/vmod.vcc
@@ -227,3 +227,5 @@ $Method STRING .meth_opt(PRIV_CALL, PRIV_VCL, PRIV_TASK,
                         [STRING s], [BOOL b])
 
 Test object method with all the fancy stuff.
+
+$Function STRANDS return_strands(STRANDS strand)
diff --git a/lib/libvmod_debug/vmod_debug.c b/lib/libvmod_debug/vmod_debug.c
index 474bc06..8bcbe60 100644
--- a/lib/libvmod_debug/vmod_debug.c
+++ b/lib/libvmod_debug/vmod_debug.c
@@ -599,3 +599,11 @@ xyzzy_priv_perf(VRT_CTX, VCL_INT size, VCL_INT rounds)
 
        return (d);
 }
+
+
+VCL_STRANDS
+xyzzy_return_strands(VRT_CTX, VCL_STRANDS strand)
+{
+       CHECK_OBJ_NOTNULL(ctx, VRT_CTX_MAGIC);
+       return (strand);
+}
```

```vcl
varnishtest "Test strands"
server s1 {} -start

varnish v1 -vcl+backend {
	import debug;
	sub vcl_deliver {
		set req.http.s = "est";
		set resp.http.ret = debug.collect(debug.return_strands("t" + req.http.s));
	}
} -start

client c1 {
	txreq
	rxresp
	expect resp.http.ret == "test"
} -run
```

## Current Behavior

The above VTC fails as such:

```
***  v1    1.7 CLI RX  106
**** v1    1.7 CLI RX|Message from VCC-compiler:
**** v1    1.7 CLI RX|Assert error in vcc_expr0(), vcc_expr.c line 1303:
**** v1    1.7 CLI RX|  Condition(!(*e)->fmt->stringform) not true.
**** v1    1.7 CLI RX|Running VCC-compiler failed, signal 6, core dumped
**** v1    1.7 CLI RX|VCL compilation failed
---- v1    1.7 FAIL VCL does not compile
*    top   1.7 RESETTING after file.vtc
**   s1    1.7 Waiting for server (4/-1)
**   v1    1.7 Wait
**** v1    1.7 CLI TX|panic.clear
***  v1    1.7 CLI RX  300
**** v1    1.7 CLI RX|No panic to clear
***  v1    1.7 debug|Info: manager stopping child
***  v1    1.7 debug|Info: manager dies
**** v1    1.7 STDOUT poll 0x10
***  v1    1.8 vsl|No VSL chunk found (child not started ?)
**   v1    1.8 WAIT4 pid=5559 status=0x0000 (user 0.761275 sys 0.772649)
*    top   1.8 TEST file.vtc FAILED
#    top  TEST file.vtc FAILED (2.231) exit=2
```

Where as when letting the VCL compile the `STRAND`, the following test passes:

```vcl
varnishtest "Test strands"
server s1 {} -start

varnish v1 -vcl+backend {
	import debug;
	sub vcl_deliver {
		set req.http.s = "est";
		set resp.http.ret = debug.collect("t" + req.http.s);
	}
} -start

client c1 {
	txreq
	rxresp
	expect resp.http.ret == "test"
} -run
```

## Possible Solution
Let functions accept a `STRANDS` from a function returning a `STRANDS`.

## Steps to Reproduce (for bugs)
1. Add function to VMOD Debug
2. Run VTC from Expected

## Context
I was trying to pass a new `STRANDS` to a function accepting `STRANDS`.
This appears to be related to issue #2745 and commit [2ba2cc341f06d732abed554fc23aa6934e3b9950](https://github.com/varnishcache/varnish-cache/commit/2ba2cc341f06d732abed554fc23aa6934e3b9950).

## Your Environment
* Version used: master [head](https://github.com/varnishcache/varnish-cache/commit/f088152194f57a26e8e173e60e4f8cb6a460aae3)
* Operating System and version: Ubuntu 16.04

**Comment by Dridi** [comment]
Works for me in current master:

```diff
diff --git c/lib/libvcc/vcc_expr.c i/lib/libvcc/vcc_expr.c
index 780befa0c..3775eb0db 100644
--- c/lib/libvcc/vcc_expr.c
+++ i/lib/libvcc/vcc_expr.c
@@ -1300,6 +1300,13 @@ vcc_expr0(struct vcc *tl, struct expr **e, vcc_type_t fmt)
        else
                vcc_expr_cor(tl, e, fmt);
        ERRCHK(tl);
+
+       if (fmt == STRANDS && (*e)->fmt == STRANDS) {
+               (void)vcc_expr_edit(tl, STRANDS, "\v+\n\v1\v-", *e, NULL);
+               ERRCHK(tl);
+               return;
+       }
+
        assert(!(*e)->fmt->stringform);
 
        if ((*e)->fmt != STRINGS && fmt->stringform)
```

**Comment by Dridi** [comment]
The patch above is not enough on 6.0 (after bringing the missing bits and bobs to run the test case):

> Message from VCC-compiler:
Assert error in vcc_do_arg(), vcc_expr.c line 496:
  Condition(e2->fmt == fa->type) not true.
Running VCC-compiler failed, signal 6, core dumped
VCL compilation failed

**Comment by Dridi** [comment]
On current master, if I change the function to add a parameter with a \_default\_ value before the STRANDS my patch confuses the compiler:

```diff
-$Function STRANDS return_strands(STRANDS strand)
+$Function STRANDS return_strands(INT before = 0, STRANDS strands)
```

Result:

> ```
> Message from VCC-compiler:
> Expression has type STRING, expected INT
> ('<vcl.inline>' Line 8 Pos 72) -- (Pos 87)
>                 set resp.http.ret = debug.collect(debug.return_strands("t" + req.http.s));
> -----------------------------------------------------------------------################---
> ```

Adding a parameter after doesn't seem to be a problem.

Also, I made a mistake when I pasted this patch which has been edited. The good news is that I get the same behavior for both master and 6.0 with my first attempt at a patch.

**Comment by Dridi** [comment]
Edited the patch again to remove the needless `ERRCHK`.

**Comment by Dridi** [comment]
Gaining more confidence in my patch, the compile error I ran into is a separate issue (#2874).

**Comment by bsdphk** [comment]
VCC is not yet ready to deal with functions returning STRANDS where STRING_LIST is needed.

Imagine a `func_taking_string_list(func_returning_strands())`

(which is what happens when you do a `set resp.http.x = func_returning_strands();`)

Since we wont know how many elements the STRANDS contains until runtime, there is no way we can convert it into a compile-time varargs STRING_LIST.

I am not prepared to build varargs stackframes by hand, the only way to fix this is to retire STRING_LIST, which we should absolutely do, but it will take some time to get vmods to follow suit.

**Comment by steven-j-wojcik** [comment]
After re-running my VTC the VCC gives the below error about converting from STRANDS to STRANDS.

```
**** v1    1.5 CLI RX|Message from VCC-compiler:
**** v1    1.5 CLI RX|Cannot convert type STRING(STRANDS) to STRING(STRANDS)
**** v1    1.5 CLI RX|('<vcl.inline>' Line 8 Pos 51) -- (Pos 88)
**** v1    1.5 CLI RX|                set resp.http.ret = debug.collect(debug.return_strands("t" + req.http.s));
**** v1    1.5 CLI RX|--------------------------------------------------######################################--
**** v1    1.5 CLI RX|
**** v1    1.5 CLI RX|Expected argument: STRANDS (unnamed argument)
**** v1    1.5 CLI RX|
**** v1    1.5 CLI RX|While compiling function call:
**** v1    1.5 CLI RX|
**** v1    1.5 CLI RX|('<vcl.inline>' Line 8 Pos 37) -- (Pos 88)
**** v1    1.5 CLI RX|                set resp.http.ret = debug.collect(debug.return_strands("t" + req.http.s));
**** v1    1.5 CLI RX|------------------------------------####################################################--
**** v1    1.5 CLI RX|
**** v1    1.5 CLI RX|Running VCC-compiler failed, exited with 2
```

The issue I am getting is from having a function that receives a STRANDS from a function that returns a STRANDS. This issue is independent of STRING_LIST.

**Comment by bsdphk** [comment]
That should be fixed now.
