### ISSUE TITLE
Inconsistencies in libvarnish and libvcc unit handling

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2882]
In `libvarnish` we have unit support in:

- `VNUM_duration`
- `VNUM_2bytes`

Already in libvarnish we have an inconsistency between the two: `VNUM_duration` accepts spaces (plural) between the value and the unit whereas `VNUM_2bytes` accepts up to one space (singular). One of them accepts spaces after the unit, the other doesn't.

In `libvcc` we work with self-contained tokens so spaces before, after or inside the value are never considered. However `libvcc` is case sensitive and requires the `B` part of the unit whereas `VNUM_2bytes` isn't and doesn't. Finally, `libvcc` stops at `TB` and `libvarnish` goes up to `PB`.

This makes `libvarnish` functions less useful because they are too permissive, and also confusing. In a VMOD context they also don't fit with the VCL syntax.

See also #2863.

**Comment by bsdphk** [comment]
Yeah, that's a mess.

I think a cleanup is in order where as much common code as possible is moved into vnum.c

**Comment by Dridi** [comment]
I think `VNUM` should not accept spaces anywhere. This way it can work with tokens and be used directly by `libvcc`. That doesn't remove the need to sync them to ensure that error messages correctly list the supported units.

In particular, `VNUM_duration` uses `isspace(3)` so this is currently running fine:

```c
assert(VNUM_duration(" 1  \n \r \t h \n  ") == 3600.)
```
