### ISSUE TITLE
vxp_lexer backslash confusion

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2891]
I think the backslash processing in vxp_lexer.c is wrong.

vxp_decstr() does backslash processing and is called two places from vxl_Lexer().

At line 159 vxp_decstr() is called after assembling a full "word" but backslash is not a valid char in a word, so vxp_decstr() cannot possibly reach the backslash processing in line 85.

In line 147, at the end of lexing a quoted string, vxp_decstr() is called, but in this case the backslash processing in line 133 has already handled backslashes ?

Specifically, I see no way the error processing in line 93-97 can ever be reached ?

**Comment by Dridi** [comment]
For reference:

> At line 159 vxp_decstr() is called after assembling a full "word" but backslash is not a valid char in a word,

https://github.com/varnishcache/varnish-cache/blob/2cba061d8d47934af1226b2c87701324d6b84cee/lib/libvarnishapi/vxp_lexer.c#L153-L163

> so vxp_decstr() cannot possibly reach the backslash processing in line 85.

https://github.com/varnishcache/varnish-cache/blob/2cba061d8d47934af1226b2c87701324d6b84cee/lib/libvarnishapi/vxp_lexer.c#L84-L91

> In line 147, at the end of lexing a quoted string, vxp_decstr() is called, but in this case the backslash processing in line 133 has already handled backslashes ?

https://github.com/varnishcache/varnish-cache/blob/2cba061d8d47934af1226b2c87701324d6b84cee/lib/libvarnishapi/vxp_lexer.c#L129-L151
