### ISSUE TITLE
Surrogate-Control handling in built-in vcl_backend_response

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2893]
Taking this as a separate issue from #2865.

Below is the current built-in VCL:

```vcl
sub vcl_backend_response {
    if (bereq.uncacheable) {
        return (deliver);
    } else if (beresp.ttl <= 0s ||
      beresp.http.Set-Cookie ||
      beresp.http.Surrogate-control ~ "no-store" ||
      (!beresp.http.Surrogate-Control &&
        beresp.http.Cache-Control ~ "no-cache|no-store|private") ||
      beresp.http.Vary == "*") {
        # Mark as "Hit-For-Miss" for the next 2 minutes
        set beresp.ttl = 120s;
        set beresp.uncacheable = true;
    }
    return (deliver);
}
```

Suggested change:

```vcl
sub vcl_backend_response {
    if (bereq.uncacheable) {
        return (deliver);
    } else if (beresp.ttl <= 0s ||
      beresp.http.Set-Cookie ||
      beresp.http.Surrogate-control ~ "no-store" ||
      beresp.http.Cache-Control ~ "no-cache|no-store|private" ||
      beresp.http.Vary == "*") {
        # Mark as "Hit-For-Miss" for the next 2 minutes
        set beresp.ttl = 120s;
        set beresp.uncacheable = true;
    }
    return (deliver);
}
```
```diff
       beresp.http.Surrogate-control ~ "no-store" ||
-      (!beresp.http.Surrogate-Control &&
-        beresp.http.Cache-Control ~ "no-cache|no-store|private") ||
+      beresp.http.Cache-Control ~ "no-cache|no-store|private" ||
```

I changed the `Surrogate-Control` logic because even if we aren't told as an edge server not to store, we should still look at the Cache-Control to figure whether the response is cacheable. Backends may use `Surrogate-Control` for the sole purpose of advertising ESI support, so this shouldn't neuter `Cache-Control`.

I think it should also be safe to back-port to 6.0 for the low risk it brings.

**Comment by bsdphk** [comment]
No clear bugwash consensus.

Please discuss this offline and we will revisit in two weeks (feb25 bugwash)

**Comment by nigoroll** [comment]
IMHO
```
Surrogate-Control: max-age=60
Cache-Control: no-cache
```

would make perfect sense

**Comment by Dridi** [comment]
IMHO

```
Surrogate-Control: max-age=60
Cache-Control: private
```

would make absolutely no sense

**Comment by Dridi** [comment]
And we already know users may use `Surrogate-Control` "only" for ESI: https://github.com/varnishcache/varnish-cache/issues/2865#issuecomment-449025982

It should be treated like cookies in `vcl_recv`, better safe than sorry, and let power users who know better neuter `vcl_backend_response`'s built-in code and bake their own uncacheable handling.

**Comment by slimhazard** [comment]
``Surrogate-Control`` supports content like ``foo=bar``, targeted at named downstream proxies and entirely unrelated to caching. There are examples related to advertising ESI capability. This example is from section 2.3 of the ["TR"](https://www.w3.org/TR/edge-arch/):

```
Surrogate-Control: content="ESI/1.0";abc, content="ESI-Inline/1.0";def
```

The relevant point here is that the mere presence of ``Surrogate-Control`` should altogether erase what ``Cache-Control`` says:

```
Surrogate-Control: content="ESI/1.0";abc, content="ESI-Inline/1.0";def
Cache-Control: no-store
```

If I'm not mistaken, current ``builtin.vcl`` would ignore ``Cache-Control`` in that case, and could very well end up caching the response with default TTL.

**Comment by nigoroll** [comment]
> IMHO
> 
> ```
> Surrogate-Control: max-age=60
> Cache-Control: private
> ```
> 
> would make absolutely no sense

It would make sense to me: The surrogate we control understands how to ensure privacy, but other caches downstream will not.

**Comment by bsdphk** [comment]
Having looked more at Surrogate Control, It seems to be a very CDN-ish thing, and as such does not belong in our builtin.vcl, but it would probably be a good idea to either have a include'able VCL library or a VMOD implementing it.

See also:

https://cache-tests.fyi/

https://www.w3.org/TR/edge-arch/

**Comment by karptonite** [comment]
@bsdphk If you think Surrogate Control doesn’t belong in the builtin, shouldn’t the proposed changes be accepted? @Dridi seems is proposing to _remove_ special handling for Surrogate Control headers from builtin.vcl.

**Comment by nigoroll** [comment]
IMHO, varnish coverage of the standards could be improved to simplify deployments by requiring less custom vcl. My understanding is that Varnish is a Surrogate by the definition in https://www.w3.org/TR/edge-arch/

> intermediaries that act on behalf of and with authority of an origin server

**Comment by Dridi** [comment]
Which is why I'm not too happy that bug #2864 and proposal #2865 were turned into a VIP. Especially the bug report.

**Comment by andrerom** [comment]
For us (link above), like original vg.no case, Varnish is a Surrogate. It acts like a well integrated cache delivery layer.
As opposed to ISP Proxies or browsers cache which are both controlled by Cache-Control.

So to me the suggested on VCL change for `Surrogate-Control` change here was anyway wrong. If there is a `Surrogate-control`, that should be used as source of cache control rules to follow.

_Example: Using Varnish as your application cache layer, and you vary cache by user rights so it's done also for logged in users. But as current response contains sensitive data you need to block the cache being cached on ISP proxy / browsers cache._
