### ISSUE TITLE
VIP12bis (extend std.conversions)

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2899]
Should we extend functionality of std.conversions:

    TIME std.time([STRING input], [TIME fallback], [REAL real_input], [INT int_input])

See discussion in: https://github.com/varnishcache/varnish-cache/wiki/VIP12:-vmod-polymorphism-(for-type-conversions)

**Comment by nigoroll** [comment]
I would prefer if we kept the argument names short, but otherwise sgtm
```
TIME std.time([STRING string], [TIME fallback], [REAL real], [INT int])
```

**Comment by bsdphk** [comment]
Bugwash consensus: Yes we should.

**Comment by bsdphk** [comment]
VIP12 updated, now we just need somebody to do it.

**Comment by nigoroll** [comment]
I've started working on it
