### ISSUE TITLE
503 back

### ISSUE THREAD

**Issue by itssivashankar** [varnishcache/varnish-cache#2900]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Source of binary packages used (if any)

**Comment by Dridi** [comment]
Closing, please reopen once you have a proper description of the problem.

**Comment by itssivashankar** [comment]
Ubuntu 16.04 is my system.
while running (sudo apt-get update) command.
their is an error 503 back end fetch failed error. kindly give me a proper solution for the above issue.

**Comment by Dridi** [comment]
We only use github issues for actionable bugs. Please use the varnish-misc mailing list as stated in the issue template for general questions.

https://varnish-cache.org/support/
