### ISSUE TITLE
 Backend fetch failed

### ISSUE THREAD

**Issue by itssivashankar** [varnishcache/varnish-cache#2901]
Hi
I am using varnish 4.0 version in Ubuntu 16.04 machine 
while Running **sudo apt-get update** command in terminal i am getting the below error 

example
Err:67 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages
**503 Backend fetch failed**
Ign:88 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main amd64 Packages
Ign:89 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu xenial/main i386 Packages
Get:119 http://in.archive.ubuntu.com/ubuntu xenial-updates/restricted Sources [2,528 B]
Get:120 http://in.archive.ubuntu.com/ubuntu xenial-updates/universe Sources [245 kB]

**Comment by nigoroll** [comment]
duplicate of #2900 
hint: Check your repository settings and supported releases http://varnish-cache.org/releases/index.html
