### ISSUE TITLE
kill backend.list -v ?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2906]
for all cases in varnish-cache, `backend.list -v` is synonymous to `-p` and `-v` is not documented. Retire?

putting this onto our list for bugwash after an email to -commit by @Dridi :

> I think we should kill it before the March release, good catch!

Ref:

https://github.com/varnishcache/varnish-cache/blob/965857f2b0605bbc791c794879109c778c81b69a/bin/varnishd/cache/cache_director.c#L375

**Comment by Dridi** [comment]
Took me some time to work my way through all master commits but I finally caught up :)
