### ISSUE TITLE
Rename the OF_CHGGZIP flag to OF_CHGCE for "changed Content-Encoding"

### ISSUE THREAD

**Issue by slimhazard** [varnishcache/varnish-cache#2910]
This came up during development of a VFP for compression ([brotli](https://code.uplex.de/uplex-varnish/libvfp-brotli)).

It turned out that when the VFP sets OF_CHGGZIP, then the following features work correctly, as for Varnish's built-in gzip support, and as to be expected for compression filters:

* If a 304 backend response (to an IMS request from Varnish) includes a Content-Encoding response header, then don't pass that header along to the client -- use Content-Encoding in the cached and validated response, if any.

* Any ETag header from the backend should be weakened in client responses.

These features are verified for Varnish in g0004.vtc.

The corresponding test for the VFP is [here](https://code.uplex.de/uplex-varnish/libvfp-brotli/blob/master/src/tests/etag.vtc). [This version](https://gist.github.com/slimhazard/126374cbec68a71709777c3090749fd4) of the test was not working before making the change to set ``OF_CHGGZIP``. The change is shown in [this commit](https://code.uplex.de/uplex-varnish/libvfp-brotli/commit/f8b50ca9e6ab34e99dd415b47f9beaee004e1dee).

I suspect that the naming of ``OF_CHGGZIP``, as well as some of the other flags, is due to legacy -- they were originally conceived to add gzip support specifically. But the way that the flag is actually used in the code has to do with the fact that Content-Encoding as received from the backend has changed, and another VFP that manipulates Content-Encoding can legitimately use it as well.

By changing the flag name:

* we make it apparent in the code that flag is about changed Content-Encoding, and non-gzip filters can use it appropriately.

* we don't discourage VFP authors from making use of the flag (I originally thought I mustn't touch the ``OF_*GZIP*`` flags, because the VFP isn't about gzip).

**Comment by bsdphk** [comment]
So we need to decide what happens in this scenario:

    vcl.use vcl_gzip
    fetch, vfp_gzip, cache
    vcl.use vcl_brotli
    ims-fetch, 304, ???

**Comment by slimhazard** [comment]
> ``fetch, vfp_gzip, cache``

... assuming that this means that the VFP compresses the beresp, sets Content-Encoding to "gzip" in the cache, and sets the CHG flag (the gzip VFP does in fact do all of that).

(BTW I believe that all of this reasoning also applies if it goes the other way -- the beresp has "Content-Encoding: gzip", and the gunzip VFP is applied to decompress it. In that case, Content-Encoding is removed from the cached object, and the CHG flag is also set.)

> ``vcl.use vcl_brotli``
> ``ims-fetch, 304, ???``

The critical case here, which is tested in the last request in g00006.vtc, is when the IMS response from the backend has the Content-Encoding header. Ordinarily the rule applies that headers from a 304 response "overwrite" headers saved from the previous response, but we don't want that to happen for Content-Encoding when a VFP has encoded the cached response.

Since the CHG flag is set, Varnish will do the right thing in this situation -- any Content-Encoding header from the IMS response is ignored. It actually doesn't matter that the brotli VFP is in use at this point, since VFPs are bypassed for 304 responses anyway. It also doesn't matter what value is set for Content-Encoding in the IMS response. Content-Encoding in the cached object retains the value "gzip", so the object is handed off to delivery as gzip-encoded.

If it goes the other way, the right thing also happens. If the cached object had been originally decompressed, so that the cached object has no Content-Encoding header and the CHG flag is set, then CHG ensures that a Content-Encoding header in the IMS response does not "override" the cached object.

(I think it's kinda screwy for a backend to set Content-Encoding in a 304 response -- how does the backend know the encoding of a response body that it's not sending? But stupid backends might do that, so it's a good thing that we can handle it.)

This is just me thinking it through, but we can verify what happens with a VTC test. I'll see if I can add one for the brotli VFP.

**Comment by slimhazard** [comment]
I added a VTC test to the VFP to verify what happens, see [this test](https://code.uplex.de/uplex-varnish/libvfp-brotli/blob/master/src/tests/etag.vtc#L93) starting at line 93.

Varnish does indeed do the right thing as expected. So I am convinced now that setting ``OF_CHGGZIP`` to say "a VFP set Content-Encoding, so don't let an IMS response change it" is the thing to do.

**Comment by bsdphk** [comment]
I wonder if the flag for C-E should instead be a bitmap which says "these headers from the stored object overwrites whatever a 304 comes in with ?

**Comment by nigoroll** [comment]
My understanding is that a backend should not respond with 304 if C-E has changed, so I consider OF_CHGGZIP/OF_CHGCE a safety measure only and do not think that we need to generalize without at last one other good example (which I am unaware of)

**Comment by slimhazard** [comment]
Yeah, I might agree with this idea if we have some examples from real-world use cases.

Someone could write a whack VFP that translates German responses to Danish, and sets the Content-Language header. Then we wouldn't want an IMS response to change Content-Language. But unless I'm mistaken, this sort of thing only really comes up for C-E.

@nigoroll a backend can't know if it's behind a proxy that went and changed the content encoding on its own, it can only validate on the basis of I-M-S and I-N-M. I just suspect that a backend is broken if it sends a C-E (or no C-E) for the 200 response, then some other value for C-E in the 304 response.

**Comment by Dridi** [comment]
Isn't that what a weakened ETag is for? Maybe the backend didn't do gzip by default during the first fetch, and then got configured to do so when the conditional request kicked in.

**Comment by bsdphk** [comment]
Bugwash consensus:  We rename the flag.  Futher generalizations await informative examples.
