### ISSUE TITLE
Source/tarball checksums?

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#2911]
Looking at https://varnish-cache.org/releases/index.html to download the latest 6.1 source release, I'm wondering how I can check that the downloaded tarball is correct.

Is there a list of sha checksums available somewhere for me to verify against?

Maybe the table with the download link can include a checksum?

**Comment by bsdphk** [comment]
I guess that has fallen of our release-enginering checklist, it's supposed to live on the release pages on the homepage like this:  http://varnish-cache.org/releases/rel5.1.2.html

**Comment by Dridi** [comment]
I added SHA256 checksums for all releases, and evidence when I found a reliable independent source.

On the https://varnish-cache.org/releases/index.html page, I don't think we need to add checksums again: if you click on the link in the release column you land on the release page where the checksum (and in your case evidence) is visible.

**Comment by lkarsten** [comment]
Thanks!
