### ISSUE TITLE
vmodtool --boilerplate does not take -o argument into account.

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#2914]
Issue: vmodtool --boilerplate does not take -o argument into account.

Expected: vmodtool writing automake_boilerplate.am referencing the overridden "vcc_if.c" name it will write.
```
$ ../../lib/libvcc/vmodtool.py -o vcc_cookie_if -b

NOTICE: Please put $Module description in quotes.

$ cp automake_boilerplate.am with-o
$ ../../lib/libvcc/vmodtool.py  -b

NOTICE: Please put $Module description in quotes.

$ diff automake_boilerplate.am with-o    # diff is empty
$ grep vcc_if with-o
nodist_libvmod_cookie_la_SOURCES = vcc_if.c vcc_if.h
$(libvmod_cookie_la_OBJECTS): vcc_if.h
vcc_if.h vmod_cookie.rst vmod_cookie.man.rst: vcc_if.c
vcc_if.c: $(vmodtool) $(srcdir)/vmod.vcc
CLEANFILES = $(builddir)/vcc_if.c $(builddir)/vcc_if.h \
```

**Comment by Dridi** [comment]
I already asked for changes to make this generally usable out of tree (we don't use `-o` in tree) but this wasn't too well received and then OBE.

**Comment by bsdphk** [comment]
Uhm... that doesn't ring a bell with me ?   What changes were that @dridi ?

**Comment by Dridi** [comment]
I don't remember the specifics, maybe @nigoroll will. But there are some in-tree assumptions made by the generated `*.am` files.

**Comment by bsdphk** [comment]
That wouldn't have been "my department", so that's why I don't remember I guess :-)

**Comment by nigoroll** [comment]
no bell rung here either.

**Comment by lkarsten** [comment]
I worked around this by just using multiple directories, each with a `vmod.vcc` file. A bit of duplication, but with the short-short `Makefile.am` that isn't much of a burden.

My guess is that this is used by varnish-modules, and not much else. I wouldn't mind if the functionality disappeared from vmodtool, if that makes things easier.
