### ISSUE TITLE
Feature request: Skip access log

### ISSUE THREAD

**Issue by ernestojpg** [varnishcache/varnish-cache#2919]
Hello all!

I was wondering if there is any way of skipping or disabling a specific request in varnishncsa. For example, in Nginx we can specify "access_log off;" for a specific request so it is not printed in the logs.

This would be very useful for removing from the logs the typical health checks, etc.

Maybe we could have a new function in vmod_std for indicating varnishncsa to not print the log for that request ....

What do you think?

**Comment by carlosabalde** [comment]
It looks like you are looking for varnishncsa `-q` option. You can use it to filter out VSL transactions.

**Comment by bsdphk** [comment]
If need be, you can set a "magic" HTTP header, that will end up in the VSL log, then remove it before delivering to the client (so they dont see it).

Then you can use the `-q` option of varnishncsa to filter those requests out.

**Comment by ernestojpg** [comment]
Ahhh, good one! Thanks for the trick! ;)

**Comment by danielmotaleite** [comment]
Just to help others using google:

      -q ' ReqHeader:host ne "healthcheck" '

https://varnish-cache.org/docs/trunk/reference/vsl-query.html

**Comment by nigoroll** [comment]
FWIW, using `std.log()` to emit a `Log` header to filter for with 
```
-q 'Log !~ "^marker"'
```
would be slightly more efficient.
