### ISSUE TITLE
VCL_INT, VCL_BYTES and the 64-bit range

### ISSUE THREAD

**Issue by slimhazard** [varnishcache/varnish-cache#2926]
Raising this issue due to 0f7f757c478351e7a30c9820f7542b868743b7b8 and the discussion there. IMO this looks like a regression.

["Upgrading" for 6.0](https://varnish-cache.org/docs/6.0/whats-new/upgrading-6.0.html#other-changes) had this to say:

> The VCL_INT and VCL_BYTES types are now defined to be strictly 64 bit (rather than leave it to whatever your platform defines as long). But you may not get that full precision, for reasons discussed in the change log.

... linking to [changes.rst,](https://github.com/varnishcache/varnish-cache/blob/master/doc/changes.rst) which had this at the time:

> Integers in VCL are now 64 bits wide across all platforms (implemented as int64_t C type), but due to implementation specifics of the VCL compiler (VCC), integer literals' precision is limited to that of a VCL real (double C type, roughly 53 bits).

> In effect, larger integers are not represented accurately (they get rounded) and may even have their sign changed or trigger a C compiler warning / error.

My understanding at the time was that this was regarded as a bug. And I'm sure I remember understanding the work leading to 6.1 as having fixed the bug, in particular b637c111d6db652f7849c0d68fa19491f0f9c598, 5d1dd90aa55918d0d37fa87fd7a0374fa5aabe19 and da727285da6d62e70dd2038dcf6c79d91bba7564.

["Upgrading" for 6.1](https://varnish-cache.org/docs/6.1/whats-new/upgrading-6.1.html#other-changes) then said:

> We have fixed a bug that had limited the precision available for the INT data type, so you now get the full 64 bits.

That statement seems clear enough.

But 0f7f757c478351e7a30c9820f7542b868743b7b8 now defines the macros ``VCL_INT_MAX`` and ``VCL_BYTES_MAX`` in ``vrt.h`` to limit them to 53 bits, and the "to-integer" conversion functions return the fallback if they are out of that range.

The previous changes make it possible to use the full range of 64-bit literals in VCL, but not the conversion. IMO users will not find it especially plausible if we say that INT and BYTES have 64-bit range, but not if you're converting a string.

The main question IMO (which @nigoroll has also raised) is why do have to use ``VNUMpfx()`` to convert an integer to a double and back. (I suspect some possible reasons for that -- ``strtoll()`` will probably work on most platforms, but the C standard does not guarantee any relationship between long long and int64_t. The "official" way would be to use ``sscanf()`` with the ``SCNd64`` formatter, which is ugly.)

Also: the names ``VCL_INT_MAX`` and ``VCL_BYTES_MAX`` in the API include header will strongly suggest to devs programming against VRT that these are maxima for the data type, not just for conversions.

And to be really pedantic: the 53-bit range holds when C doubles have the IEEE 754 binary64 format. In practice, "every" C compiler does it that way, but in fact the C standard doesn't strictly require it. So it's possible for Varnish to be built with a standards-conforming compiler for which the maxima in ``vrt.h`` do not hold.

Overall, I think it best if we convert integers with a function that doesn't turn them into doubles along the way.

**Comment by slimhazard** [comment]
Although come to think of it, the maximum could be defined without assumptions about the double format like this:
```
#include <float.h>
#define VCL_INT_MAX ((INT64_C(1)<<DBL_MANT_DIG )-1)
```
So my "pedantic" objection can be addressed with better pendantry.

**Comment by nigoroll** [comment]
note on the bug label: I _am_ aware that this is kind-of on the edge, but I still think it's a bug

**Comment by bsdphk** [comment]
This one needs action if 2020-03½ becomes 7.0

**Comment by bsdphk** [comment]
(It's lingering, awaiting ID structured-headers to settle the same question)

**Comment by slimhazard** [comment]
OBE due to the restricted numeric ranges currently being introduced in the master branch. @nigoroll's PR has already been closed.

To add the obvious, please remember to document the range restrictions in the new version. But you knew that. %^) I opened the issue originally because I had interpreted the previous docs quoted above as saying that, for example, VCL_INT would have the full 64-bit range.
