### ISSUE TITLE
improve timeout_idle documentation wrt H2

### ISSUE THREAD

**Issue by Francois-v3** [varnishcache/varnish-cache#2927]
In varnishadm 6.1, documentation of timeout_idle says:

> # varnishadm param.show timeout_idle                                                          timeout_idle
>         Value is: 10.000 [seconds]
>         Default is: 5.000
>         Minimum is: 0.000
> 
>         Idle timeout for client connections.
> 
>         A connection is considered idle until we have received the full
>         request headers.
> 
>         This parameter is particularly relevant for HTTP1 keepalive
>         connections which are closed unless the next request is
>         received before this timeout is reached.

It appears that it's "particularly relevant" for HTTP/2 too ! I would says even more, as there's no more connection header in HTTP/2 ...

```
# varnishd -V
varnishd (varnish-6.1.1 revision efc2f6c1536cf2272e471f5cff5f145239b19460)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
```

**Comment by nigoroll** [comment]
FTR the meaning of `timeout_idle` is not particularly well defined at the moment. work in this broad area is currently happening in #2980

**Comment by daghf** [comment]
With #2980 done, we now take timeout_idle into account also for h/2.

I'll close this ticket now.

**Comment by daghf** [comment]
Sorry - I noticed #2980 did not update the doc. I'll reopen for now

**Comment by Dridi** [comment]
Are you sure? I don't remember the specifics but I worked on different timeouts: idle_send_timeout and send_timeout, not timeout_idle. I think we are back to @nigoroll's comment.

**Comment by Dridi** [comment]
I'm not sure how @nigoroll feels about it but I think we shouldn't discuss this question today. As requested in https://github.com/varnishcache/varnish-cache/pull/2983#issuecomment-489557939 we worked on bringing consistency to timeouts, and while we did not specifically address h2 we have a VIP draft that we may submit to the wiki to be discussed next bugwash.

A side effect of this draft is that it should help us define what `timeout_idle` would mean for streams-based transports like h2.

**Comment by nigoroll** [comment]
I agree with @Dridi 
We have already spent some relevant amount of time on a comprehensive proposal and I would think bugwash time was invested more wisely if spent on that proposal (later).

**Comment by nigoroll** [comment]
@Dridi and myself still need to finish the timeout-proposal we have already spent quite some time on, but which we did not finish yet. This ticket seems to serve no real purpose, other than reminding me once again that we need to.

**Comment by bsdphk** [comment]
Timed out.
