### ISSUE TITLE
varnishtest leaks varnishtest tasks

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2952]
See below, when the main `varnishtest` process receives a `SIGINT` or `SIGTERM` it goes away but the tasks it started are not interrupted:

```
$ cat >leak.vtc <<EOF
varnishtest "varnishtest leak"

# should be plenty of time to kill varnishtest
delay 50
EOF
$ bin/varnishtest/varnishtest -i leak.vtc &
[1] 30936
$ pgrep varnishtest
30936
30959
$ kill 30936
[1]+  Terminated              bin/varnishtest/varnishtest -i leak.vtc
$ pgrep varnishtest
30959
```

**Comment by bsdphk** [comment]
This is not a bug as such, the tester process dies eventually when the VTIM_sleep() call in cmd_delay() returns.

I guess one could rewrite the VTIM_sleep() call to be a loop of shorter sleeps which checks the vtc_error and vtc_stop flags.

Patch welcome.
