### ISSUE TITLE
6.2.0: Test c00003.vtc fails on Arch Linux

### ISSUE THREAD

**Issue by WRMSRwasTaken** [varnishcache/varnish-cache#2958]
Hello, 

building Varnish on Arch Linux fails on the test `c00003.vtc`. However, it passes this test successfully on a fresh installation with Arch Linux. I've attached the `test-suite.log` and package list (with versions) of the passing & failing node:

[test-suite.log](https://github.com/varnishcache/varnish-cache/files/3000634/test-suite.log)
[packagelist-on-failing-node.txt](https://github.com/varnishcache/varnish-cache/files/3000635/packagelist-on-failing-node.txt)
[packagelist-on-working-node.txt](https://github.com/varnishcache/varnish-cache/files/3000636/packagelist-on-working-node.txt)

The configure flags are: `./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var/lib --sbindir=/usr/bin`

The kernel version on the failing node is `4.20.16.a-1-hardened` and on the passing node it's version `4.20.17.a-1-hardened` (it also works with `5.0.3`).

It's going to take a while for figuring out which package is causing the build error.

€: I also attached both `config.log` files of each node:
[config-failing.log](https://github.com/varnishcache/varnish-cache/files/3000696/config-failing.log)
[config-passing.log](https://github.com/varnishcache/varnish-cache/files/3000697/config-passing.log)

What's directly noticeable is the error about missing `jemalloc` on the node that passes all tests:

```
/usr/bin/ld: cannot find -ljemalloc
collect2: error: ld returned 1 exit status
```

**Comment by WRMSRwasTaken** [comment]
Installing `1:5.1.0` did NOT reproduce it, it still passed this test w/o that block in `config.log` anymore.

**Comment by nigoroll** [comment]
From the log it seems apparent that the issue is that binding to `192.0.2.255:0` succeeds while it should not:

```
**   top   0.4 === shell -err -expect "Error: Could not get socket" {
**** top   0.4 shell_cmd|exec 2>&1 ; 
**** top   0.4 shell_cmd|\tvarnishd -F -a "192.0.2.255:0" -b '***' -n /tmp/vtc.8371.40a9ca57
**** top   0.4 shell_out|Error:
**** top   0.4 shell_out|Message from VCC-compiler:
**** top   0.4 shell_out|Backend host '"***"' could not be resolved to an IP address:
**** top   0.4 shell_out|\tName or service not known
**** top   0.4 shell_out|(Sorry if that error message is gibberish.)
**** top   0.4 shell_out|('<-b argument>' Line 3 Pos 13)
**** top   0.4 shell_out|    .host = "***";
**** top   0.4 shell_out|------------#####-
**** top   0.4 shell_out|
**** top   0.4 shell_out|
**** top   0.4 shell_out|In backend specification starting at:
**** top   0.4 shell_out|('<-b argument>' Line 2 Pos 1)
**** top   0.4 shell_out|backend default {
**** top   0.4 shell_out|#######----------
**** top   0.4 shell_out|
**** top   0.4 shell_out|Running VCC-compiler failed, exited with 2
**** top   0.4 shell_out|VCL compilation failed
**** top   0.4 shell_status = 0x0002
---- top   0.4 shell_expect not found: ("Error: Could not get socket")
```

**Comment by WRMSRwasTaken** [comment]
Thanks for the catch! I am running `keepalived` thus having set `net.ipv4.ip_nonlocal_bind = 1` which makes this test fail.

Disabling it temporarily while building Varnish makes that test pass, so I guess I am going to close this issue.

Thanks.
