### ISSUE TITLE
varnish Health probes fail but  backend server HTTP response is  http/1.1 200 ok

### ISSUE THREAD

**Issue by gavenpeng** [varnishcache/varnish-cache#2960]
i use the command : varnishlog -g raw -i Backend_health, the result is follow

```
0 Backend_health - discovery_activity_mobile_1 Still healthy 4--X-RH 3 3 3 0.000763 0.000797 HTTP/1.1 200 OK
0 Backend_health - business_marketing_esi_1 Still sick 4--X--- 0 3 3 0.000000 0.000000 HTTP/1.1 200 OK
```
the discovery_activity_mobile_1 response is http/1.1 200 OK ,heathcheck is success,but the business_marketing_esi_1  response is alse http/1.1 200 OK,but healthcheck is failed

discovery_activity_mobile_1  is tomcat server,business_marketing_esi_1  is apigateway development by my self

--------------------------------------------------
My gateway server is support healthcheck,the curl result is follow:
```
[dev@uat-sh-bs-3-b2-app-0-56 southgate]$ curl -i http://xxxxx:3743/healthcheck
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=UTF-8
Content-Length: 53
Connection: close
Date: Sun, 31 Mar 2019 03:27:25 GMT
```

* xdcs.default.healthCheck: OK
  healthCheck success

return 200 OK,but varnish think is failed

do the command : varnishadm -S /etc/varnish/secret -T localhost:6082 debug.health the result is follow:

```
Backend business_marketing_esi_1 is Sick
Current states  good:  0 threshold:  3 window:  3
Average responsetime of good probes: 0.000000
Oldest                                                    Newest
================================================================
--------------------------------------------------------44444444 Good IPv4
--------------------------------------------------------XXXXXXXX Good Xmit
----------------------------------------------HH---------------- Happy
```

varnish no RRRRRRRRRRRRRRRRRR item,but tcpdump analyse the varnish host is receive
the backend server gateway is response ,the result is follow:

the tcpdump  reslut
![image](https://user-images.githubusercontent.com/2044082/55284552-f23b5b00-53ab-11e9-89e9-0309f7278e77.png)

```
GET /0331/healthcheck HTTP/1.1
Host: 172.29.0.46
Connection: close

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: application/json;charset=UTF-8
Content-Length: 53
Connection: keep-alive
Date: Sun, 31 Mar 2019 03:49:52 GMT
```

* xdcs.default.healthCheck: OK
  healthCheck success

please help me,thanks!!

**Comment by nigoroll** [comment]
I think the issue might be related to the backend keeping the connection open despite varnish sending `Connection: close`. Other than that please note
* we do not use github issues for support, please refer to http://varnish-cache.org/support/index.html
* If you think you are hitting a geniune varnish issues, please respect the issue template, follow its guidelines and provide the information requested therein

**Comment by gavenpeng** [comment]
> I think the issue might be related to the backend keeping the connection open despite varnish sending `Connection: close`. Other than that please note
> 
> * we do not use github issues for support, please refer to http://varnish-cache.org/support/index.html
> * If you think you are hitting a geniune varnish issues, please respect the issue template, follow its guidelines and provide the information requested therein

I start also think is the connection problem,so i change to connection is close

![image](https://user-images.githubusercontent.com/2044082/55296809-52380d00-5451-11e9-857d-4b13f0857142.png)

the reft is gateway healthcheck response,the right is tomcat healthcheck response,the two response is the same,but varnish think tomcat is ok,gateway is sick
thanks!!!
