### ISSUE TITLE
Remove the repetition in user release docs ("What's New / Upgrading")

### ISSUE THREAD

**Issue by slimhazard** [varnishcache/varnish-cache#2961]
What's New / Upgrading in every version since 5.1 includes release notes for each previous version going back to 4.0:

* WN/U for trunk and 6.2 have release notes each version from 4.0 to 6.2.
* WN/U for 6.1 has release notes from 4.0 to 6.1.
* WN/U for 6.0 has release notes from 4.0 to 6.0.
* ... and so on ...

So our docs repeat the release notes for versions since 4.0 up to about five times.

Suggestion:

Starting with the next version (current trunk), "What's New / Upgrading" only documents release notes for that version. If you want to know how to upgrade to version X.Y, you look in the docs for X.Y. We no longer repeat the release notes for X.(Y-1) and X.(Y-2) and (X-1).Z and so on.

**Comment by Dridi** [comment]
4.1 is officially EOL. I will read the rest later, I only noticed this with a quick glance.

**Comment by slimhazard** [comment]
@Dridi, as @nigoroll pointed out, that was really the homepage repo, so I've moved that part to an issue over there: https://github.com/varnishcache/homepage/issues/72

**Comment by bsdphk** [comment]
OBE
