### ISSUE TITLE
Mark's cache tests

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2962]
We should decide what to do about Mark's HTTP Cache tests:

https://cache-tests.fyi/

**Comment by nigoroll** [comment]
FYI https://github.com/http-tests/cache-tests

**Comment by bsdphk** [comment]
Would be nice to run Marks test maybe once a week to know if things change better/worse.

**Comment by nigoroll** [comment]
bugwash: I'll try to work on this as a side project

**Comment by Dridi** [comment]
I reported the first false-negative I found: https://github.com/http-tests/cache-tests/issues/50

**Comment by bsdphk** [comment]
See also:

https://github.com/httpwg/wiki/wiki/HTTP-Testing-Resources

**Comment by bsdphk** [comment]
Consensus is that we should be more std's compliant.

Issue closed, links moved to wiki.
