### ISSUE TITLE
vcl_deliver restart does not abort backend fetch

### ISSUE THREAD

**Issue by HLeithner** [varnishcache/varnish-cache#2963]
## Expected Behavior
Restart the connection and pipe the data.

## Current Behavior
Restart and piping seams to work, but it seams as the old connection is still running.

## Possible Solution
Closing the connection as soon as deliver returns restart?

## Steps to Reproduce (for bugs)
1. create a big file (ex. 5gb) on the backend server
2. use a varnish with limited memory 2gb
3. use the following vcl

```
sub vcl_recv {
  if(req.http.x-pipe && req.restarts > 0) {
    unset req.http.x-pipe;
    return (pipe);
  }
}
sub vcl_backend_response {
  // don't cache files larger than 20MB
  if (std.integer(beresp.http.Content-Length, 0) > 20242880) {
    set beresp.http.x-pipe = "1";
    set beresp.uncacheable = true;
    set beresp.do_gzip     = false;
    set beresp.do_gunzip   = false;
    set beresp.ttl         = 120s;
    return (deliver);
  }
}
sub vcl_deliver {
  if (resp.http.x-pipe && req.restarts == 0) {
    set req.http.x-pipe = "1";
  return (restart);
  }
}

```

4. varnish will run oom
5. directly pipe in vcl_recv without restart works

## Context
I'm trying to get around caching big files, in varnish < 4.0 I found code snipes for restarting and piping. But this doesn't work any longer in varnish >= 4.0. As alternative I tried 2 things.

Adding a x-pipe header in vcl_backend_response and restart in vcl_deliver and pipe the restarted connection in vcl_recv.

if you not disable gzip you will see that the process use 100% for compression even if the transfer is canceled.

## Your Environment

* Version used: 6.2
* Operating System and version: Debian Stretch
* Source of binary packages used: official packages
* haproxy with UDS

**Comment by nigoroll** [comment]
I have not reproduced it, but this seems plausible to me: After (possibly aborted) delivery of the body on the client side, we `HSH_Abandon()` a private body in `cnt_deliver`:
https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishd/cache/cache_req_fsm.c#L407
So I guess we should do the same in `cnt_deliver` for `return(restart)` and `return(synth)`
