### ISSUE TITLE
SLT_BackendOpen and UDS

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#2970]
for UDS backends, `BackendOpen` is not particularly useful as it outputs

```
vcl_name 0.0.0.0 0 0.0.0.0 0
```
I wonder if we should have instead two tags, `BackendOpenTCP` and `BackendOpenUDS`, with the latter containing the path. Or `BackendOpen` with just the name and an additional proto-specific tag.

**Comment by slimhazard** [comment]
That was a deliberate decision. The first version of UDS code changed log entries like this, but @bsdphk specifically did not want to change the log record formats, so as not to break existing parsers.

Documented in https://varnish-cache.org/docs/6.0/whats-new/upgrading-6.0.html#other-changes as:

> 0.0.0.0 and port 0 appear in the logs where an IP and port otherwise appear, when the connection in question was addressed as a Unix domain socket. This affects ReqStart, SessOpen, BackendStart and BackendOpen.

A UDS backend has to be identified by the VCL name.

**Comment by nigoroll** [comment]
@slimhazard thank you for the recap, I just wonder if it is time to change this?

**Comment by bsdphk** [comment]
I think it makes sense to revisit this in relation to the VSLng idea.

Whatever we do should make room also for SSL,H2, H3 and more weird backends.

Presumably we could make this a job for the transports themselves.

Come back with a concrete proposal?
