### ISSUE TITLE
Using backend.probe in separated VCL file

### ISSUE THREAD

**Issue by tsu1980** [varnishcache/varnish-cache#2973]
## Expected Behavior

`varnishadm backend.list` should lists the backends that declared in separated VCL.

## Current Behavior

If I run `varnishadm backend.list`. there are no backends that declared in separated VCL.

```
> sudo varnishadm backend.list
Backend name                   Admin      Probe                Last updated
main.fake                      probe      Healthy (no probe)   Tue, 09 Apr 2019 21:43:33 GMT
```

## Possible Solution

I dunno. Is it limitation?
If it's limitation, it should be documented to clarify in [here](https://varnish-cache.org/docs/trunk/users-guide/vcl-separate.html).

## Steps to Reproduce (for bugs)

1. Create VCL files

/etc/varnish/main.vcl:
```
vcl 4.1;

backend fake {
  .host = "0:0";
}

sub vcl_recv {
  if (req.http.host == "example.com") {
    return (vcl(l_vhost_1));
  }

  return (synth(404));
}
```

/etc/varnish/vhost_1.vcl:
```
vcl 4.1;

backend be_spapp_gke {
  .host = "1.2.3.4";
  .port = "80";
  .probe = {
    .url = "/health";
    .timeout = 2s;
    .interval = 5s;
    .window = 8;
    .threshold = 3;
  }
}
```

2. Load and activate VCL files
```
sudo varnishadm vcl.load vhost_1 /etc/varnish/vhost_1.vcl
sudo varnishadm vcl.label l_vhost_1 vhost_1
sudo varnishadm vcl.load main /etc/varnish/main.vcl
sudo varnishadm vcl.use main
```
3. Run `varnishadm backend.list`
```
sudo varnishadm backend.list
```

## Context

I'm trying to do that serve stale cache when backend down. I'm refered below URLs and tried, but in the first place, it seems not working backend probe.

https://varnish-cache.org/docs/trunk/users-guide/vcl-grace.html#the-effect-of-grace-and-keep
https://github.com/mattiasgeniar/varnish-6.0-configuration-templates/blob/master/default.vcl

So I'd like to use backend.probe in separated VCL files. Is it possible? If not, Is there a workaround?

## Your Environment

* Version used: varnishd (varnish-6.0.3 revision 7d1ded3aa033a018317dbafc61587026ea2ef8a3)
* Operating System and version: Ubuntu 18.04
* Source of binary packages used: official packages

**Comment by Dridi** [comment]
Not a bug, `backend.list` takes a pattern and in its absence it only lists backends from the active VCL. Labels, even if they are referenced by the active VCL don't count as active although that is debatable, but the issue tracker is for actionable bugs and not feature requests.

See `varnishadm help backend.list` and `man varnish-cli`.
