### ISSUE TITLE
Waitinglist rushing of hit-for-pass is delayed

### ISSUE THREAD

**Issue by mbgrydeland** [varnishcache/varnish-cache#2978]
When a hit-for-pass object is inserted, the rushing of the waitinglist propagates too slowly. After the first level of rushing, the next level happens only after the client delivery has finished.

**Comment by nigoroll** [comment]
@mbgrydeland fearing that my message on IRC might have got unnoticed: http://varnish-cache.org/vtest/ still shows errors for c97-c99

**Comment by mbgrydeland** [comment]
Failing test cases fixed by #2986
