### ISSUE TITLE
Address SO_{RCV,SND}BUF limitations in the test suite

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#2987]
Initially submitted via #2980, we can now reduce the socket buffers to test some timeouts that would otherwise be hard to check in a test case.

This enabled testing in #2983 for example.

The problem is that the current implementation only works on Linux and while this is better than nothing I would rather have it work on the main systems we care about. But not at the expense of polluting core code like VTCP to support testing (we'll need to figure where to draw the line).

**Comment by nigoroll** [comment]
we could add a callback and a priv pointer to VTCP_connect to be called inbetween `socket()` and `connect()`and pass it through VTCP_open - would this be considered pollution?
Another simple solution would be to separate varnishtest's vtcp.c

**Comment by bsdphk** [comment]
It is admittedly monday morning and all that, but I have *no* idea what you guys are talking about here, and I see nothing in either of the cited tickets which clues me in either.

Can I buy a couple of clues ?

**Comment by Dridi** [comment]
Commits pushed so far around this topic:

- d49025519
- bfbd2963f
- 09785c4ee
- cc90aab3a
- 211f72da3

**Comment by nigoroll** [comment]
bugwash: @bsdphk decision is finer-grained VTCP primtives, not callbacks

**Comment by bsdphk** [comment]
Bugwash conclusion:  Finer grained VTCP primitives, not callbacks.

**Comment by Dridi** [comment]
Currently the s10 test case works on Linux and FreeBSD, but SunOS is a bit more restrictive regarding when we can tweak socket buffers. Because this is specific to SunOS it is assigned to @nigoroll who is expected to come up with finer-grained VTCP primitives.

In varnishd we currently use vmod_debug to tweak `SNDBUF` on the client side, but could leverage `struct tcp_opt` to apply it once to the listen socket, and hope it will be inherited by accepted sockets.

There are currently no plans for the backend side and we may revisit this if a `fetch_timeout` of sorts akin to `send_timeout` appears on the backend side.

**Comment by bsdphk** [comment]
I'm closing this ticket, feel free to reopen if new events warrant that.
