### ISSUE TITLE
Test s00010 and send timeouts

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#2988]
I'm a little bit unhappy about what goes on here.

But first, I don't understand how this the first part of this test is supposed to work.

The test sets send_timeout to one second, but leave idle_send_timeout at the default.

As I read the code, that does not work, because the send_timeout relevant code only gets called on short writes and those only happen when idle_send_timeout triggers.

Action 1:  Should we always lower idle_send_timeout to half of send_timeout ?

If the client c1 part of s10 works on linux,  something else is broken.

Something else can either be setting of idle_send_timeout or socket being in non-blocking mode.

Action 2: Find out which it is ?

**Comment by bsdphk** [comment]
Action2: linux returns short write on Client TCP::RST.

Action1: Dridi+Slink to come up with coherent plan (at least for H1)

**Comment by bsdphk** [comment]
The failure mode on ARM64 FreeBSD VTEST'er is:

        ***  l1    2.5 expecting| expect * * Debug Hit total send timeout

Which doesn't happen, probably because of this:

        **** v1    4.7 vsl|       1001 Debug           c Write error, retval = -1, len = 100183, errno = Broken pipe

**Comment by Dridi** [comment]
For later analysis: http://phk.freebsd.dk/misc/2dridi.txt

**Comment by nigoroll** [comment]
On Action1, I continued here https://github.com/varnishcache/varnish-cache/pull/2983#issuecomment-489561298

**Comment by Dridi** [comment]
OBE, I worked on fixing s10 and besides FreeBSD on arm64 where it still happens a bit (it used to float above 50%) it is now fixed.
