### ISSUE TITLE
Varnish intercepts URLs containing sprit keywords

### ISSUE THREAD

**Issue by robotxman** [varnishcache/varnish-cache#2989]
![image](https://user-images.githubusercontent.com/49476524/56951222-cefdfa00-6b69-11e9-8c75-c0271b9a562e.png)

![image](https://user-images.githubusercontent.com/49476524/56951238-dae9bc00-6b69-11e9-9066-6cabbf2a0d21.png)

**Comment by nigoroll** [comment]
it is not clear what you are trying to say. But you probably would want to check your VCL.
For all additional requests for assistance, please refer to http://varnish-cache.org/support/index.html
We use github issues for bugs only.
