### ISSUE TITLE
Probes don't work well with Envoy proxy, likely RFC violation by Varnish

### ISSUE THREAD

**Issue by MarcinFalkowski** [varnishcache/varnish-cache#2994]
We encountered a problem running Varnish with Envoy proxy (https://www.envoyproxy.io) as a backend.
Varnish probes don't work well with Envoy because Envoy [delays connection closing](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto.html?highlight=delayed_close_timeout)  and the probe expects connection to be closed by the backend within the timeout to mark backend as healthy.

We discussed this already on Envoy github: https://github.com/envoyproxy/envoy/issues/6616 and current conclusion is this should be fixed on Varnish side. More below.

## Expected Behavior
* Varnish probe should succeed when it receives expected response. Connection closing shouldn't be necessary to pass the check.
* Varnish probe should close the connection by itself when it receives a response. This is required by rfc7230 section 6.6:
   > A client that sends a "close" connection option (...) MUST close the connection after reading the final response message corresponding to this request.

## Current Behavior
* Varnish probe, after receiving expected http response, doesn't mark the backend as healthy. It waits for connection closing by the backend. If the backend won't close the connection within the timeout, Varnish close the connection and mark backend as unhealthy. This is even stated in docs (https://varnish-cache.org/docs/6.2/reference/vcl.html#probes):
> Note that probes require the backend to complete sending the response and close the connection within the specified timeout

Here is a dump of Varnish <-> Envoy communication to illustrate current behaviour: https://github.com/MarcinFalkowski/envoy-varnish-testing-env/blob/master/captures/tcpdump-2019-04-22_23-00.pcap?raw=true  (192.168.0.3 is Varnish and 192.168.0.2 is Envoy). We can see that Varnish receives expected response after 1ms but still nobody closes the connection. Only after probe timeout (100ms) Varnish closes the connection and marks backend as unhealthy. You cannot see it but you can test it by yourself using this docker-compose environment: https://github.com/MarcinFalkowski/envoy-varnish-testing-env 

## Possible Solution
* Modify Varnish Probes logic to not require connection closing within the specified timeout to pass the health check.
* Close the connection immediately after receiving response from backend (as required by RFC7230)

## Other

Envoy delays connection closing to mitigate some possible race conditions with badly designed clients. More in the linked issue on Envoy github.

Some thoughts/questions:
* Is this behaviour of Varnish probes (requiring connection closing by the backend) needed for something? Is it necessary? Or does it work that way simply accidentally?
* Of course there is a workaround for this problem: increase the probe timeout by 1s (the default Envoy delayed close timeout). But in our case, we have hundreds of varnish servers with thousands of probes. And everyone can create new ones (500+ developers). They all have to be instructed to add +1s to probe timeout if their backend is an Envoy. This doesn't sound as a good solution.

**Comment by nigoroll** [comment]
FTR https://tools.ietf.org/html/rfc7230#section-6.6 also reads:

> A server that receives a "close" connection option MUST initiate a close of the connection (see below) after it sends the final response to the request that contained "close". [...]
> First, the server performs a half-close by closing only the write side of the read/write connection.

Would we have this issue if this was implemented as suggested by the RFC?

Other than that, the probe client is pretty simplistic, which has its merits, but yes, one of the drawbacks is that we currently rely on the server side to close. This is equally an issue with `.request = ...` not containing `Connection: close`.

Also we've seen this before (for instance in #2960), so I wonder if we should do something...

**Comment by bsdphk** [comment]
Bugwash needs to decide disposition of this ticket.

**Comment by bsdphk** [comment]
Bugwash consensus:  Close.  @nigoroll to create VIP on more VCL control over probes.
