### ISSUE TITLE
last command in start.cli is silently discarded if lacking a newline

### ISSUE THREAD

**Issue by gquintard** [varnishcache/varnish-cache#2995]
## Expected Behavior

When run with `-I` for this file:

```
action1
action2
```

Both action1 and action2 should be run.

## Current Behavior

action2 isn't run if it isn't followed by a newline. As the last command is often `vcl.use` or `param.set`, the breakage isn't immediately obvious

## Possible Solution

Maybe add a flag to `mgt_cli_setup` to flush the last line on EOF?

## Steps to Reproduce (for bugs)

```
varnishtest "No newline at the end of the start.cli file"

shell {
	echo 'vcl.inline vcl404 "vcl 4.0; backend b {.host=\"0.0\";} sub vcl_recv { return(synth(404)); }"' >> ${tmpdir}/start.cli
	echo 'vcl.inline vcl200 "vcl 4.0; backend b {.host=\"0.0\";} sub vcl_recv { return(synth(200)); }"' >> ${tmpdir}/start.cli
	echo -n 'vcl.use vcl200' >> ${tmpdir}/start.cli
}

varnish v1 -arg {-f ""} -arg "-I ${tmpdir}/start.cli" -start

client c1 {
	txreq
	rxresp
	expect resp.status == 200
} -run
```

## Context

Multiple users followed https://info.varnish-software.com/blog/one-vcl-per-domain and got bit by this.

## Your Environment

This is present on master, and I assume on all active branched

**Comment by bsdphk** [comment]
This is intentional.

In CLI context the newline is the execute signal.

Think about it from a tty point of view:  Would we ever execute a command without a NL ?

**Comment by Dridi** [comment]
No docfix needed, it's already in the manual. Sorry for the noise.
