### ISSUE TITLE
resp.filters missing esi

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3002]
It seems that `resp.filters` as seen from VCL never contains `esi`.
From a quick look at the code it seems to me that this may be related to `req->resp_len` getting set in `cnt_transmit()`, so the `resp_Get_Filter_List()` call in `cnt_transmit()` sees it, but not calls from `sub vcl_deliver{}`

**Comment by nigoroll** [comment]
On a related topic, I think it would help if `resp.do_esi` in `sub vcl_deliver{}` was only true if ESI processing actually happened, not just because it was enabled.

**Comment by rezan** [comment]
> I think it would help if resp.do_esi in sub vcl_deliver{} was only true if ESI processing actually happened, not just because it was enabled.

Might be better to have `resp.is_esi`. This is a pattern I have run into a lot and its useful to know if certain attributes exist, like ESI codes. Not sure if open source is at this level of sophistication, but I think you should at least avoid overloading the `do_*`.

**Comment by slimhazard** [comment]
@rezan I agree. ``resp.do_esi`` is about whether or not ESI is enabled, especially since it's mainly useful for disabling ESI by setting it to false. Whether or not ESI will happen is another question, and if anything warrants another variable.

(BTW at the risk of being very pedantic, in ``vcl_deliver`` we can say if ESI will happen, future tense, by checking the objcore bits. We can't say that it happened, past tense, in any VCL subroutine.)

**Comment by nigoroll** [comment]
to work around this deficit: https://code.uplex.de/uplex-varnish/libvmod-objesi

**Comment by bsdphk** [comment]
Strictly speaking, isn't the correct one to add "resp.can_esi" ?  As in "The response is an object which has been ESI parsed and therefore have the necessary ESI metadata" ?

**Comment by slimhazard** [comment]
@bsdphk or ``.has_esi``. Or of course ``.bikeshed_esi``. As long as ``.do_esi`` retains the meaning of "this is how you selectively turn ESI on and off".

**Comment by nigoroll** [comment]
my implementation idea is
* first read access to `resp.filters` creates the default filter list based on the switches like `.do_esi`
* after that point, the switches have not effect any more

**Comment by bsdphk** [comment]
Consensus seems to be `resp.can_esi` with reference to `req.can_gzip`

**Comment by nigoroll** [comment]
discussed between @bsdphk @Dridi @nigoroll :
* before it having been written to, `resp.filters` reads should reflect the decision from the `do_*` switches
* the first _write_ should fix `resp.filters`
  * after that point setting the `do_*` switches should fail the VCL
* the dynamic strings should be rendered on the workspace as now, but could also be pre-rendered at init time if that is easy enough

* If an object is asi-able (has been esi-parsed) should be reflected in `obj.can_esi`
