### ISSUE TITLE
std.rollback() without restart/retry unsafe

### ISSUE THREAD

**Issue by rezan** [varnishcache/varnish-cache#3009]
If you `std.rollback()` without a restart/retry, workspace gets reset, however, the req and bo still references these locations. This leads to a panic when that workspace gets reused.

VTC:

``` vcl
varnishtest "Rollback without restart/retry is unsafe"

server s1 {
	rxreq
	txresp
} -start

varnish v1 -vcl+backend {
	import std;

	sub vcl_recv {
		set req.http.test = "1";
	}

	sub vcl_backend_fetch {
		unset bereq.http.test;
	}

	sub vcl_backend_response {
		std.rollback(bereq);
		set beresp.http.test = bereq.http.test;
		set beresp.http.workspace = "start overwriting active workspace";
		set beresp.http.workspace = "0123456789012345678901234567890123456789";
		# panic...
	}
} -start

client c1 {
	txreq
	rxresp
	expect resp.status == 200
	expect resp.http.test == "1"
} -run
```

I looked into this, the only safe way to address this is to not reset the workspace on a rollback. Or just docfix this and state you must restart/retry?

**Comment by rezan** [comment]
Or delay the reset until the restart/retry via a flag...?

**Comment by Dridi** [comment]
We discussed it with @nigoroll and @slimhazard when this last came up. The rollback today requires a restart/retry and we were hoping to make it configurable depending on one's needs.

Unfortunately that discussion happened offline.

Until something is done to allow narrowing down what we wish to rollback it should be docfixed.
