### ISSUE TITLE
VRT_ACL_MAGIC removed from VRT

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3012]
since c878d750fa31310e71df7b1590e60e9148545ee0 `VRT_ACL_MAGIC` has been removed from VRT, so vmods can not use `CHECK_OBJ_*` on ACLs any more.

Is this intentional or should there be a way for vmods to check ACL pointers?

**Comment by bsdphk** [comment]
They should fall back to AN()
