### ISSUE TITLE
Built-in VCL not case folding host header

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#3023]
A short summary of today's bugwash discussion:

- authorities or host names are case insensitive
- the `hash_data()` VCL function works on opaque strings
- we may want specialize hashing functions:
  - `hash_url()` that could deal with percent encoding
  - `hash_host()` that would be case insensitive
  - `hash_string()` for opaque strings
  - `hash_blob()` for opaque data
- we'd rather avoid new pure VCL symbols
  - we could move them to `vmod_std`
    - except maybe `hash_blob()` to `vmod_blob`
  - always implicitly import `vmod_std` even when omitted
    - extra `import std;` statements become no-op
  - make the built-in VCL use the functions from `vmod_std`

Originally suggested differently on IRC and posted to the dev list:

https://varnish-cache.org/lists/pipermail/varnish-dev/2019-June/009425.html

**Comment by Dridi** [comment]
Another solution emerged that wouldn't involve VMODs: add `.lower()` and `.upper()` methods to the STRING type in VCL.

The built-in `vcl_hash` could look like this:

```vcl
sub vcl_hash {
    hash_data(req.url);
    if (req.http.host) {
        hash_data(req.http.host.lower());
    } else {
        hash_data(server.ip);
    }
    return (lookup);
}
```

**Comment by bsdphk** [comment]
Implementing STRING.upper & .lower, I'm not entirely sure if think these kinds of methods should be calls or properties (ie:  STRING.uppper() vs. STRING.upper).

The advantage to making them calls, is that they can be given arguments later.

**Comment by bsdphk** [comment]
Ehhh... I just remembered that the stevedore methods have no (), so _always_ adding () would break syntax.

Will ponder

**Comment by nigoroll** [comment]
@Dridi can you explain why this would be better than forcing the host/authority to lowercase in the built-in `vcl_recv {}`?
I do see that one might want to have the option to access original value for obscure use cases, but simply converting to lowercase by default would be the right thing also for matches on `req.http.host` etc.

**Comment by bsdphk** [comment]
I've solve-ished the () issue.

@nigoroll has a point, in that there are other headers we "normalize" before running, notably we Collect X-F-F and Cache-Control.

Given all the work the HTTPwg has done on trying to clear things up, normalizing Host: by forcing it to lower-case sounds reasonable, and if so, could be done in-place in C-code.

**Comment by bsdphk** [comment]
Bugwash:  We'll lower req.http.host in vcl 4.2.   If need to override plausible, in builtin-vcl

**Comment by bsdphk** [comment]
We decided at todays bugwash to test this out in the upcoming 6.3 release.

I've implemented the folding in builtin.vcl with 06ffea8738b07b24de8e so people easily can override it.
