### ISSUE TITLE
vcl_backend_error unexpectedly caching synthetic responses

### ISSUE THREAD

**Issue by carlosabalde** [varnishcache/varnish-cache#3024]
## Expected Behavior

`vcl_backend_error` not caching synthetic responses unless explicitly instructed to do so.

## Current Behavior

`vcl_backend_error` caches responses when requests are coalesced. For  some reason the following  variables are set when entering in the subrroutine:  `ttl = 1s`, `grace = 5s`, `keep = 5s`.

## Possible Solution

Explicitly set `beresp.ttl`, `beresp.grace` and `beresp.keep` to `0s` during `vcl_backend_error`.

## Steps to Reproduce (for bugs)

```
varnishtest "vcl_backend_error caching issue"

barrier b1 cond 2

server s1 {
    rxreq
    barrier b1 sync
    txresp -status 500

    rxreq
    txresp -status 500
} -start

varnish v1 -vcl {
    backend s1 {
        .host = "${s1_addr}";
        .port = "${s1_port}";
    }

    backend s2 {
        .host = "${bad_backend}";
    }

    sub vcl_hit {
        set req.http.X-Cache = "HIT";
    }

    sub vcl_miss {
        set req.http.X-Cache = "MISS";
    }

    sub vcl_deliver {
        set resp.http.X-Cache = req.http.X-Cache;
    }

    sub vcl_backend_fetch {
        if (bereq.retries == 0) {
            set bereq.backend = s1;
        } else {
            set bereq.backend = s2;
        }
    }

    sub vcl_backend_response {
        if (beresp.status == 500) {
            return (retry);
        }
    }

    sub vcl_backend_error {
        set beresp.http.X-TTL = beresp.ttl;
        set beresp.http.X-Grace = beresp.grace;
        set beresp.http.X-Keep = beresp.keep;
        return (deliver);
    }
} -start

client c1 {
    txreq
    rxresp
    expect resp.status == 503
    expect resp.http.X-Cache == "MISS"
    expect resp.http.X-TTL == "0.000"
    expect resp.http.X-Grace == "0.000"
    expect resp.http.X-Keep == "0.000"
} -start

delay .1

client c2 {
    barrier b1 sync
    txreq
    rxresp
    expect resp.status == 503
    expect resp.http.X-Cache == "MISS"
    expect resp.http.X-TTL == "0.000"
    expect resp.http.X-Grace == "0.000"
    expect resp.http.X-Keep == "0.000"
} -run
```

## Context

When a backend request reaches `vcl_backend_error` we restart the client request in order to  expand the grace window and deliver staled content. Due  to this issue, in same cases the staled content was overwritten by the synthetic response generated by `vcl_backend_error`.

## Your Environment
* Version used: tested in  trunk and 4.1.11.
* Operating System and version: Ubuntu Xenial.

**Comment by gquintard** [comment]
this is done on purpose (https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishd/cache/cache_fetch.c#L683), but it may be time to look at it again

**Comment by carlosabalde** [comment]
I makes sense to avoid serialization. Perhaps it's just a matter of explaining that behavior in the docs.
