### ISSUE TITLE
return (abandon) with response code

### ISSUE THREAD

**Issue by rezan** [varnishcache/varnish-cache#3027]
Just want to put the idea out here before working on this. It would be very helpful to be able to have a response code and reason when we `return (abandon)` on a backend operation. This response code and reason will be used when you enter `vcl_synth`.

For example, if we get a bad response in `vcl_backend_response` and we do not want to update the existing cached object, we would abandon. But it would be helpful to pass along that information to the requesting client:

``` vcl
sub vcl_backend_response
{
    # Do not update cache, return the error to the client
    if (beresp.status >= 400) {
        return (abandon(beresp.status, beresp.reason));
    }
}
```

This would also allow us to better communicate error information between backend and client contexts without using a cached object.

This would function very similar to the recently added `return (error)` in that the new parameters are completely optional.

**Comment by gquintard** [comment]
https://github.com/varnishcache/varnish-cache/pull/3014 ?

**Comment by rezan** [comment]
I thought #3014 was unrelated, but it looks like `vcl_backend_error` does not insert into cache. For some reason I thought it would. Closing...

**Comment by gquintard** [comment]
`vcl_backend_error` can, and sometime will, insert to cache. You have access to `beresp.{ttl,grace,keep}` in it.

**Comment by rezan** [comment]
Yup, and according to the code, those values are overwritten. Anyway, I need to test this a bit more on Monday, I'm not getting consistent results at the momemt.
