### ISSUE TITLE
Debian package erase systemd configuration

### ISSUE THREAD

**Issue by dugwood** [varnishcache/varnish-cache#3053]
##  Expected Behavior
Keep current configuration for systemd if it already exists: `/lib/systemd/system/varnish.service` and `/lib/systemd/system/varnishncsa.service`

## Current Behavior
Files are erased by apt/aptitude. I know some packages ask for changes in `/etc/` before erasing the file (hence keeping the current configuration).

## Possible Solution
As most of the Varnish configuration is now in `varnish.service`, the file must be kept as is if it has been modified.

## Steps to Reproduce (for bugs)
1. Install Debian package 6.2.0
2. Change `/lib/systemd/system/varnish.service` (for example add `-a ":6086,PROXY"` for a successful Hitch backend)
3. Update to Debian package 6.2.1
4. All configuration is erased

## Context
Smooth transition (it was a minor upgrade here). Everything is down because Hitch doesn't have a functional backend after Varnish restart.

## Your Environment
* Version used: 6.2.0 / 6.2.1
* Operating System and version: Debian 9 (Stretch)
* Source of binary packages used (if any): PackageCloud

**Comment by gquintard** [comment]
Hi,

This is an issue for https://github.com/varnishcache/pkg-varnish-cache if you use packagecloud.io, or for your Debian maintainer if you use their packages.

However, it is very likely the issue will be marked as invalid as you are not supposed to change the unit file provided by the packages. Instead install an override/drop-in in `/etc`. Some information here: https://docs.varnish-software.com/tutorials/configuring-systemd-services/

The quick-and-dirty command: `systemctl edit --full varnish`

**Comment by dugwood** [comment]
Thanks Guillaume for this valuable information. I also didn't see the other repository, my bad.
