### ISSUE TITLE
vmod_purge example in reference guide not working in version 6.0.3?

### ISSUE THREAD

**Issue by fredvd** [varnishcache/varnish-cache#3054]
I'm debugging a problem with a varnish.vcl where vmod_purge has been put in use to do soft/hard purges. 

First documentation oddity: vmod_puge is documented in the 5.2 documentation at:
https://varnish-cache.org/docs/5.2/reference/vmod_purge.generated.html?highlight=vmod_purge
, it is present in 6.1 at https://varnish-cache.org/docs/6.1/reference/vmod_purge.generated.html?highlight=vmod_purge

but the vmod_purge is not documented in 6.0. However the code example at the vmod_purge documentation using import purge and calling purge.hard() works fine in vcl loaded in varnish 6.0.4 .

The problem I see with the example usage of vmod_puge is the following:

```sub my_purge {
    set req.http.purged = purge.hard();
    if (req.http.purged == "0") {
        return (synth(404));
    }
    else {
        return (synth(200));
    }
}
```

When an item is not in the cache and I send a purge request, I get the synthetic response with the 404.  But If the item is present in the cache through a previous client request and I perform the purge request,  the answer to the purge request is a full 200 deliver of the content item.  I'd expec to receive a synthetic small response with a 200 status.

Also when I monitor all subroutine calls with varnishlog, the purge request doesn't cause any backend request to renew the item. Also reg.http.purged which is set in the request is empty in the return http headers. 

Is vmod_purge still working in 6.X > ?

**Comment by gquintard** [comment]
`vmod_purge` is tested in https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishtest/tests/m00031.vtc, so I'm pretty sure it works.

To be really sure, I wrote this VTC (you can run it using `varnishtest foo.vtc`):

```
varnishtest "purge"

server s1 {
	rxreq
	expect req.url == "/foo"
	txresp

	rxreq
	expect req.url == "/bar"
	txresp

	rxreq
	expect req.url == "/foo"
	txresp
} -start

varnish v1 -vcl+backend {
	import purge;
	sub vcl_recv {
		if (req.method == "PURGE") {
			#if (client.ip !~ purge_acl) {
			#	return (synth(405));
			#}
			return (hash);
		}
	}

	sub my_purge {
		set req.http.purged = purge.hard();
		if (req.http.purged == "0") {
			return (synth(404));
		}
		else {
			return (synth(200));
		}
	}

	sub vcl_hit {
		if (req.method == "PURGE") {
			call my_purge;
		}
	}

	sub vcl_miss {
		if (req.method == "PURGE") {
			call my_purge;
		}
	}

	sub vcl_synth {
		if (req.method == "PURGE") {
			if (req.http.purged) {
				set resp.http.purged = req.http.purged;
			}
			return (deliver);
		}
	}
} -start

client c1 {
	txreq -url "/foo"
	rxresp

	txreq -url "/foo"
	rxresp

	txreq -url "/bar"
	rxresp

	txreq -url "/bar"
	rxresp

	txreq -req PURGE -url "/foo"
	rxresp
	expect resp.status == 200

	txreq -req PURGE -url "/foo"
	rxresp
	expect resp.status == 404

	txreq -url "/foo"
	txreq -url "/foo"
	rxresp

	txreq -url "/bar"
	rxresp
} -run
```
It reuses the example code pretty much verbatim (I commented out the acl check).

I'll close this as it doesn't appear to be a bug but rather a misconfiguration issue, but please get in touch via the help channels (https://varnish-cache.org/support/) so we can get to the bottom of this.
