### ISSUE TITLE
Varnish 5.x series  EOL terms

### ISSUE THREAD

**Issue by icsu** [varnishcache/varnish-cache#3060]
Hello,

     I'm trying to find the EOL terms for Varnish Cache 5.x series, but I can't find anything in the official websites and documentation.

     What are the future plans in terms of EOL dates for Varnish 5.x series? (especially for the last stable version v5.2.1)

Thanks,
Adrian

**Comment by gquintard** [comment]
Hi,

5.x series have always only been "fresh" releases, meaning they would only
survive for 6 months (until the new version is released).

I guess the answer you are seeking is: they are all EOL already.

Cheers,

-- 
Guillaume Quintard

**Comment by icsu** [comment]
Thank you for your answer @gquintard , but there's no official announcement for 5.x like they announced 4.1 EOL?

**Comment by bsdphk** [comment]
We should communicate this better, I'll try to make it more clear on our website.
