### ISSUE TITLE
Test v00058.vtc fail on 32bit Linux

### ISSUE THREAD

**Issue by ingvarha** [varnishcache/varnish-cache#3061]
Test v00058.vtc fail on 32bit Linux. I can reproduce this on Fedora 29/i386, Fedora 29/armv7hl, and Centos6/i386.

## Steps to Reproduce (for bugs)
Build varnish-6.0.4 on 32bit Linux. Run make check. Builds fails on v00058.vtc at
`**   s1    0.8 === expect req.http.Result == <undef>`
`---- s1    0.8 EXPECT req.http.Result () == "<undef>" failed`

Full build log here
https://paste.fedoraproject.org/paste/XCs6F1nj8UmN7Ny1FjhwUg
and here
https://koji.fedoraproject.org/koji/taskinfo?taskID=37496168

To run the fedora 29 build on centos6 without mock:

`git clone https://src.fedoraproject.org/rpms/varnish.git`
`cd varnish`
`git checkout f29`
`sudo yum-builddep varnish.spec`
`wget http://varnish-cache.org/_downloads/varnish-6.0.4.tgz`
`wget -O pkg-varnish-cache-0ad2f22.tar.gz https://github.com/varnishcache/pkg-varnish-cache/archive/0ad2f22629c4a368959c423a19e352c9c6c79682.tar.gz`
`bd="$(pwd)"`
`rpmbuild \`
`  --define "_sourcedir $bd" \`
`  --define "_specdir $bd" \`
`  --define "_builddir $bd" \`
`  -bb varnish.spec`

## Your Environment
* Version used: varnish-6.0.4
* Operating System and version: fedora-29-i386 (local mock chroot and fedora build system), fedora-29-armv7hl (fedora build system), epel-6-i386 (local mock chroot)
*

**Comment by bsdphk** [comment]
Getting the workspace overflow tests right for all archs/widths may be tricky.

Idea from bugwash:  Add "INT sizeof(STRING)" to vmod_vtc to make it easier.

**Comment by Dridi** [comment]
We already have `vtc.typesize("p")` for that matter, unless I misunderstand the intent.

**Comment by ingvarha** [comment]
For debugging purposes, changing the "magic number" from -12 to -11, makes the test go through.

vtc.workspace_alloc(client, -11);
