### ISSUE TITLE
Should in-tree vmods be listed on the homepage/vmods ?

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#3075]
Right now vmod_std is listed in homepage/vmods, but with outdated branch information and other in-tree vmods are not mentioned.

Should the in-tree vmods even be in this table ?

Or would it be better with a separate table for them at the top, just listing their first version ?

**Comment by Dridi** [comment]
My preference goes to a clean separation between built-in and third-party modules.

**Comment by nigoroll** [comment]
I think we should have the in-tree vmods on the same page, but as a different section.
Maybe we should also have the vmods per varnish version, as both their location and supported versions change.

**Comment by nigoroll** [comment]
I'll have a go at this

**Comment by bsdphk** [comment]
Bugwash consensus:  Could be better, not clear how.

**Comment by nigoroll** [comment]
moved to my long time TODO list outside github.
