### ISSUE TITLE
review settings ?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3076]
after we are done with https://github.com/varnishcache/homepage/pull/80, do we want to automate the review process by
* setting PRs to require reviews by CONTRIBUTORS
* defining the CONTRIBUTORS file?

Ref: https://help.github.com/en/articles/enabling-required-reviews-for-pull-requests

**Comment by bsdphk** [comment]
I prefer to trust people, rather than add more infrastructure to maintain.

**Comment by nigoroll** [comment]
I do fully agree. The suggestion is just to automate part of the process, not to forbid manual overrides.

**Comment by nigoroll** [comment]
bugwash: not seen as being worth it.
