### ISSUE TITLE
+= operator

### ISSUE THREAD

**Issue by lkarsten** [varnishcache/varnish-cache#3079]
When building long strings in VCL, for example lengthy GET args for vmod-curl or a body for a callout, I'm constantly missing the += operator from Python.

```
set req.http.foo = req.http.foo + "&bar="
set req.http.foo = req.http.foo + "&baz="
```
vs  (future, wanted):
```
set req.http.foo += "&bar="
set req.http.foo += "&baz="
```

In the case of a redirect in vcl_synth, setting `resp.http.Location = resp.http.Location + "&foo"` has low SNR in 80 character wide files.

**Comment by Dridi** [comment]
Should this be limited to strings on the left hand side? Or should we have a new dedicated keyword?

```
cat req.http.foo "&bar=";
cat req.http.foo "&baz=";
```

Do we have prior-art syntax at Fastly's?

**Comment by nigoroll** [comment]
@fgsch can you help here?

**Comment by fgsch** [comment]
Once upon a time, you had to use the `+=` to append to the hash.

Fastly has `+=` and `-=` only for addition and subtraction (https://docs.fastly.com/vcl/operators/).

**Comment by bsdphk** [comment]
I think the syntax is much clearer.

Originally I did not include it, because I felt it could give the wrong impression about workspace usage.

I have not investigated what it would take to optimize the WS usage of the trivial case of

    req.http.foo += this;
    req.http.foo += that;
    req.http.foo += also;

But I guess it might be possible.

**Comment by nigoroll** [comment]
+1 for adding `+=`.

speaking of which, it would be great if vmod objects could become lvalues such that

`mytaskvar += 5`

became possible. I think, a practical way to get there was to designate `$Method` as getters or setters.

But my add-on proposal should not keep this back, just mentioning it.

Re @bsdphk : While some optimizations could be added to VCC, I also think that not having them would sill be ok, we would not make VCL worse.

**Comment by bsdphk** [comment]
Bugwash consensus:  Implement first, optimize later. Caveat WS consequence in docs.
