### ISSUE TITLE
panic: VRT_DelDirector from VCL Event would deadlock / director locking wrong?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3094]
seen during a vcl reload with https://github.com/nigoroll/libvmod-dynamic

calling `VRT_DelDirector()` from a `VCL_COLD` event handler leads to a panic because the `temp_rwl` lock is already held when the director event handler is to be called here:

https://github.com/varnishcache/varnish-cache/blob/1f226e6d8c1c5443d9df127797c62b1e1228bfd1/bin/varnishd/cache/cache_vrt_vcl.c#L222

While this could be avoided by additional delayed destruction in the director vmod, I wonder if holding the `temp_rwl` for `VDI_Event()` is actually the right thing to do, and then if we actually need the `temp_rwl` in the first place.:

* for the actual director insertion/removal, we use the `vcl_mtx`
* we write-lock `temp_rwl` when we change the temperature in `vcl_set_state()`
* we read-lock `temp_rwl` when adding and removing directors (plus for assertions on the temperature)

We post `VDI_Event()` for adding/removing directors and from `vcl_BackendEvent()`, which is called from `vcl_set_state()`

So the purpose is to ensure that the warm/cold events from construction/destruction do not interfere with VCL temperature events.

But `vcl_BackendEvent()` only posts events for directors on the `director_list`, so it seems to me that if we get the list members right, we should not need the additional lock.

`vcl_BackendEvent()`, on the other hand, currently walks the `director_list` not holding `vcl_mtx`, so aren't we already failing to properly handle director addition/deletion concurrent to VCL events?

At this point, the following would appear sensible to me:
* hold `vcl_mtx` whenever we handle the `director_list`, IIUC the missing cases are `vcl_BackendEvent() and vcl_KillBackends()`
* by ensuring that only backends on the `director_list` receive events, we can then kill `temp_rwl`: As events happen in the cli thread (`ASSERT_CLI()`), we do not need another layer of serialization

Feedback welcome

```
Panic at: Thu, 10 Oct 2019 11:02:07 GMT
Assert error in VRT_DelDirector(), cache/cache_vrt_vcl.c line 222:
  Condition(((*__errno_location ())=pthread_rwlock_rdlock(&vcl->temp_rwl)) == 0) not true.
version = varnish-trunk revision 3fcfd4b8feb289836762902b14750d345e75ab78, vrt api = 9.0
ident = Linux,3.10.0-862.14.4.el7.x86_64,x86_64,-jnone,-smalloc,-sdefault,-hcritbit,epoll
now = 27968678.416989 (mono), 1570705183.817889 (real)
Backtrace:
  0x445790: /opt/varnish/sbin/varnishd() [0x445790]
  0x445db1: /opt/varnish/sbin/varnishd() [0x445db1]
  0x4cd44b: /opt/varnish/sbin/varnishd(VAS_Fail+0x4d) [0x4cd44b]
  0x46ac40: /opt/varnish/sbin/varnishd(VRT_DelDirector+0x207) [0x46ac40]
  0x7fc0029c4747: ./vmod_cache/_vmod_dynamic.ac90823754667b39adf868c2db7f41ad3d09769cddb736a57629336ce699ce98(+0x4747) [0x7fc0029c4747]
  0x7fc0029c6e8f: ./vmod_cache/_vmod_dynamic.ac90823754667b39adf868c2db7f41ad3d09769cddb736a57629336ce699ce98(vmod_event+0x37f) [0x7fc0029c6e8f]
  0x7fbf0f7fa565: vcl_reload-varnish_20191009135156_248082.1570629116.539489/vgc.so(+0x41565) [0x7fbf0f7fa565]
  0x4573c4: /opt/varnish/sbin/varnishd() [0x4573c4]
  0x458af1: /opt/varnish/sbin/varnishd() [0x458af1]
  0x459cf4: /opt/varnish/sbin/varnishd() [0x459cf4]
errno = 35 (Resource deadlock avoided)
thread = (cache-main)
pthread.attr = {
  guard = 0,
  stack_bottom = 0x7ffe0aef7000,
  stack_top = 0x7ffe0b6f6000,
  stack_size = 8384512,
}
thr.req = (nil) {
},
thr.busyobj = (nil) {
},
vmods = {
  std = {0x7fc0204c60f0, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  header = {0x7fc0204c61d0, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 9.0},
  cookie = {0x7fc0204c6240, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 9.0},
  re = {0x7fc0204c62b0, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 9.0},
  re2 = {0x7fc0204c6320, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 9.0},
  dispatch = {0x7fc0204c6390, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  blob = {0x7fc0204c6400, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  blobdigest = {0x7fc0204c6470, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  blobsynth = {0x7fc0204c64e0, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  *one private vmod removed*,
  dns = {0x7fc0204c65c0, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 9.0},
  directors = {0x7fc0204c6630, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  all_healthy = {0x7fc0204c66a0, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  cluster = {0x7fc0204c6710, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  constant = {0x7fc0204c6780, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  taskvar = {0x7fc0204c67f0, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  querystring = {0x7fc0204c6860, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  vsthrottle = {0x7fc0204c68d0, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 9.0},
  geoip2 = {0x7fc0204c6a20, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  dynamic = {0x7fc0204c7900, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  hoailona = {0x7fc0206044e0, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  frozen = {0x7fbfbc5ca320, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
  crypto = {0x7fbfbc7f70b0, Varnish trunk 3fcfd4b8feb289836762902b14750d345e75ab78, 0.0},
},
```

**Comment by bsdphk** [comment]
Wasn't there something about CLI wandering the backends getting in the way of traffic when creation of dynamic backends got stuck behind CLI's holding the mutex ?

**Comment by nigoroll** [comment]
> Wasn't there something about CLI wandering the backends getting in the way of traffic when creation of dynamic backends got stuck behind CLI's holding the mutex ?

please continue in #3119
