### ISSUE TITLE
circleci tests failing

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3095]
for example:

 https://circleci.com/gh/varnishcache/varnish-cache/163?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

as these issues are unrelated to our code, I would appreciate if the cci runs could either be fixed or disabled until fixed.
The fact that all checks are flagged bad basically makes the github CI integration useless for the project.

**Comment by gquintard** [comment]
I commented out the `centos:7` `distcheck` and opened this: https://github.com/varnishcache/varnish-cache/issues/3097

Should I do the same for the `alpine` `distcheck`? That one is due to a vtc failure

**Comment by bsdphk** [comment]
Is this still relevant ?

**Comment by nigoroll** [comment]
looking good again
