### ISSUE TITLE
can't distcheck master on centos:7

### ISSUE THREAD

**Issue by gquintard** [varnishcache/varnish-cache#3097]
I believe @Dridi is on it, but if there are people who want to give it a stab, here's the log: https://pastebin.com/u6cemS4r

**Comment by bsdphk** [comment]
The linux box I have in VTEST runs Centos7, I just updated it so we can see if that fails too.

**Comment by bsdphk** [comment]
I updated my centos box, and after I actually installed python3 on it, vtest seems happy...

    [root@l107 etc]# cat centos-release*
    CentOS Linux release 7.7.1908 (Core) 
    Derived from Red Hat Enterprise Linux 7.7 (Source)
    [root@l107 etc]# uname -a
    Linux l107.freebsd.dk 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gquintard** [comment]
this is vexing. Would you mind sharing the output of `rpm -qa | grep -e sphinx -e docutils` please?

**Comment by gquintard** [comment]
nevermind...

you need `python` and `python-sphinx`, the second you thrown `python3-sphinx` in the mix, you are doomed.
