### ISSUE TITLE
param.reset fails for thread_pool_max

### ISSUE THREAD

**Issue by Lallassu** [varnishcache/varnish-cache#3098]
param.reset for thread_pool_max fails, it tries to set a default value less than minimum. There is no information about that this is caused by thread_pool_min being set to higher value than default.

## Expected Behavior
Reset to default value that seems to be 15k?

## Current Behavior
Tries to reset param to a value not allowed.

## Possible Solution
param.set thread_pool_max 15000

## Steps to Reproduce (for bugs)

varnish> param.reset thread_pool_max
106
Must be at least 15000

(attempting to set param 'thread_pool_max' to '5000')
varnish> param.show thread_pool_max
200
thread_pool_max
        Value is: 16000 [threads]
        Default is: 5000
        Minimum is: 15000

## Context

Tried to reset parameters.

## Your Environment

Linux,4.9.184-linuxkit,x86_64,-junix,-smalloc,-sdefault,-hcritbit
varnish-plus-6.0.4r3 revision b12564b520cd5ff7e381c0e6f98b591583ff7556
(running docker)

**Comment by Dridi** [comment]
I have patch ready, I will submit it once I have a test case.
