### ISSUE TITLE
Varnish fails to deliver objects larger than the configured memory limit

### ISSUE THREAD

**Issue by siilike** [varnishcache/varnish-cache#3104]
Varnish does not deliver objects that are larger than the memory limit: it just closes the connection which makes the client retry with a range request, but that also fails, because Varnish tries to load the entire file from the backend and closes the connection again.

It does work with piped requests and when setting `beresp.uncacheable = true`. `beresp.do_stream = true` has no effect.

A workaround is to set `beresp.uncacheable = true` based on `Content-Length` in vcl, but that is rather cumbersome.

How to reproduce:
  - start Varnish with minimal memory, e.g. `-s default,64m`;
  - create a file larger than the configured limit;
  - download the file with wget, the output should say something like `Connection closed at byte 67101856. Retrying.`

varnishd (varnish-6.3.0 revision 0c9a93f1b2c6de49b8c6ec8cefd9d2be50041d79)
Linux 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linux

**Comment by nigoroll** [comment]
This is a known issue, pipe mode is the only current workaround.
Dup #2964
