### ISSUE TITLE
storage size documentation is wrong

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3108]
Ref: https://varnish-cache.org/lists/pipermail/varnish-commit/2019-October/022232.html

> hi, i use varnish6.2.0 to cache image, my machine memory is 16g, varnish malloc do not set size and use the default。
> i see the documentation from varnish-cache.org, the default size is unlimited. my test images size about 6g,when i send http request to
> varnish,only a little images can cache from varnish, about 200m size. most of them is miss.
> my some varnish settings as follows:
> /usr/local/varnish/sbin/varnishd -a 0.0.0.0:80,HTTP -f /usr/local/varnish/etc/default.vcl
> when i set malloc size(8g),varnish is working ok, malloc must be seted specify size？how i can do if use unlimited ？

The OP is right. http://varnish-cache.org/docs/trunk/users-guide/storage-backends.html says the default was unlimited, but it actually is 100m

**Comment by liniannian** [comment]
thank you!

**Comment by Dridi** [comment]
FYI:

> 09:18 < dridi> slink: i don't consider this a bug
09:19 < dridi> the unlimited malloc (and possibly umem) is for an explicit -s
09:19 < dridi> -s unlimited=malloc
09:19 < dridi> your storage "unlimited" will be unbounded
09:19 < slink> OH
09:20 < dridi> if you don't specify Transient, core code will specify -s Transient=default
09:20 < slink> too bad I only read your reply after I posted to -misc
09:20 < dridi> if you don't specify storage at all, you get unbounded transient and 100m s0
09:20 < slink> yes
09:20 < dridi> possibly worth a docfix
09:21 < slink> I will fix

**Comment by nigoroll** [comment]
thank you @Dridi
