### ISSUE TITLE
Unable to unset bereq.http.x in vcl_miss/vcl_pass

### ISSUE THREAD

**Issue by anthosz** [varnishcache/varnish-cache#3120]
Hello,

Following the post on https://stackoverflow.com/questions/58732587/unset-x-varnish-header-to-the-backend-server-but-keep-it-in-the-response-to-clie , it seems that there is a typo in the documentation or in the code (works in 3.0.x but I cannot find the equivalent for 6.0.x): https://book.varnish-software.com/4.0/chapters/VCL_Subroutines.html

Indeed, we can see that for vcl_miss, unset bereq.http.x can work (like in 3.0 but for vcl 4+) but in real, it doesn't works, so we cannot use these parameters to remove the header when the request is sent to backend & keep it for condition in vcl_backend_response.

Best regards,

**Comment by Dridi** [comment]
Github issues are only for bug reports, you should probably ask on the misc mailing list instead.

https://varnish-cache.org/support/

**Comment by anthosz** [comment]
Hi @Dridi,

It seems that it is a bug. Indeed, in the documentation, we can see that we can use unset bereq in vlc_miss/vcl_pass but didn't works when we try it (Varnish 6.3.1)

Best regards,

**Comment by Dridi** [comment]
Let's discuss this on the misc mailing list and reopen the github issue if it turns out to be a bug, which I'm convinced is not. None of the links point to varnish-cache.org so they should not reflect a documentation bug.
