### ISSUE TITLE
Implement 412 response for non-GET/HEAD Cond fetch

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3121]
https://github.com/varnishcache/varnish-cache/blob/dfc71c66582852f2b53c58da55d935c0abb07f4e/bin/varnishd/cache/cache_rfc2616.c#L267

Reviewing for #3118 and #3111 I realized that our conditional request handling is incomplete, see in particular https://tools.ietf.org/html/rfc7232#section-6
Some aspects:
* We do not handle `If-Match` and `If-Unmodified-Since`. The RFC defines that caches can ignore those, yet some use cases of varnish-cache or not that of a typical cache. I am not sure how to best handle such cases, some ideas:
  * move the conditional checks to a vmod which can then be used for custom applications and document that we never check these conditionals
  * run the checks in `vcl_hit {}` to fulfil the requirement to _ensure that the _state changing request_ has not yet succeeded when we run the check
* For those conditionals which we do already handle, we should respond with 304 only for `GET/HEAD` and with 412 for all other methods

There are likely more aspects which we also miss to implement correctly.

**Comment by bsdphk** [comment]
We left out If-Match and If-Unmodified-Since because nobody had ever seen either used.

**Comment by nigoroll** [comment]
@bsdphk I agree, and their primary use case would probably be for uncached "state changing" requests primarily handled by backends.
I am OK with not implementing them also until we actually see a use case.
But the second thing, 412 for non-get/head, is something we should fix, IMHO.

**Comment by nigoroll** [comment]
bugwash:
* fix the 412 cases (I want to keep this ticket open for the respective fix)
* Add `If-Match` & `If-Unmodified-Since` when a use case comes up

**Comment by Dridi** [comment]
We shouldn't need to worry about `If-Match` & `If-Unmodified-Since` because they are building blocks for compare&swap:

- GET /some/resource
- modify locally
- PUT /some/resource `If-Match|If-Unmodified-Since`

Typically backend business.

**Comment by nigoroll** [comment]
@Dridi I totally agree. But besides "typically", one could actually handle them in varnish.

**Comment by Dridi** [comment]
Let's wait for a use case then, because currently I'm highly skeptical.

**Comment by nigoroll** [comment]
Yes, we had already reached that conclusion, see https://github.com/varnishcache/varnish-cache/issues/3121#issuecomment-552458676

**Comment by bsdphk** [comment]
I have tried to figure out what is up or down in this, relative to the current HTTPwg "restatement" drafts, and I cannot find anything we should change.

When building the `bereq` we only strip `If-*` headers when we fetch with intent to cache, we dont touch them for `pass`, so I fail to see any case where any desired policy cannot be implemented in VCL, and since our `builtin.vcl` only caches on "safe" methods, all should be good.

Re-open with specific concrete real-world, example, if/when one such exist.
