### ISSUE TITLE
Setting vcl_cooldown=0 makes main process unresponsive (100% cpu)

### ISSUE THREAD

**Issue by stromnet** [varnishcache/varnish-cache#3135]
Setting vcl_cooldown to zero causes unresponsive adm cli (but worker process still seems to be working)

## Expected Behavior
To not allow setting 0, or handle 0 in some expected way.

## Current Behavior
varnishadm stops responding.

## Steps to Reproduce (for bugs)
1. Launch varnishd, preferably with `-p vcl_cooldown 2` to avoid waiting for <270s for next "refresh"
2. `varnishadm vcl.list` to show that varnish responds
3. `varnishadm param.set vcl_cooldown 0`
4. `varnishadm vcl.list` to show that it now does not respond

Example:
```
# docker run --rm -it --name varnish-test varnish:latest varnishd -F -f /etc/varnish/default.vcl -p vcl_cooldown=1
Debug: Version: varnish-6.3.1 revision 6e96ff048692235e64565211a38c41432a26c055
Debug: Platform: Linux,4.15.0-47-generic,x86_64,-junix,-sdefault,-sdefault,-hcritbit
Debug: Child (17) Started
Info: Child (17) said Child starts
```

```
# docker exec -it varnish-test sh
# varnishadm vcl.list
active   auto    warm         0    boot

# varnishadm param.set vcl_cooldown 0

# varnishadm backend.list
Rejected 400
CLI communication error (hdr)
#
```

## Context
Found this while exploring VCL cooldown behaviour n scope of https://github.com/jonnenauha/prometheus_varnish_exporter/issues/57

## Your Environment
See docker-based example above

**Comment by nigoroll** [comment]
the infinite loop happens here:

```
#0  vev_bh_update (priv=0x7f4cd0814040, a=0x7f4cd0835140, u=0) at vev.c:96
#1  0x000055a10833eb69 in binheap_delete (bh=0x7f4cd0814100, idx=1) at binary_heap.c:408
#2  0x000055a108342aca in vev_sched_timeout (evb=0x7f4cd0814040, e=0x7f4cd0835140, t=5123.2201666649999)
    at vev.c:366
#3  0x000055a108342ee8 in VEV_Loop (evb=0x7f4cd0814040) at vev.c:347
#4  0x000055a1082a9e33 in main (argc=<optimized out>, argv=<optimized out>) at mgt/mgt_main.c:917
```
