### ISSUE TITLE
Fix typo in user guide

### ISSUE THREAD

**Issue by djmgit** [varnishcache/varnish-cache#3136]
Following typos needs to be fixed:

missing **allow** in /doc/sphinx/users-guide/run_security.rst
```Allow inline C in VCL, which would any C code from VCL to be executed by Varnish. ```

double **it** in /doc/sphinx/tutorial/peculiarities.rst
``` Varnish Cache has an admin console. You can connect it it through the ```

**Comment by Dridi** [comment]
You don't have to create an issue for something like that, the pull request was enough.

Thanks!
