### ISSUE TITLE
Limiting memory for varnish process

### ISSUE THREAD

**Issue by kaaaq** [varnishcache/varnish-cache#3138]
Hi
On Varnishv4.1 when i use ram as backend for Caching,when Reqests comes to it
after a while the amount of server's ram  begans to full little by little and after it completely fills, the server crashes
and again it starts caching in the ram

I assign following variables in systemd service file for varnish.service
but still it does its Previous behavior and it crushs again:
LimitMEMLOCK=14336
MemoryLimit=13G
MemoryHigh=13G
MemoryMax=13G

How can i limit and specify the special amonut of memory that it cant exceed from that?

* Version used:
Varnishv4.1
* Operating System and version:
Ubuntu16.04
* Source of binary packages used (if any)
Installed from official ubuntu packages

**Comment by Dridi** [comment]
Hi, as explained in the issue template we use github issues only for actionable bug reports, otherwise please ask general questions to the misc mailing list:

https://varnish-cache.org/support/

And by the way the 4.1 series is no longer supported, you should upgrade to 6.0 LTS instead.
