### ISSUE TITLE
Watchdog panic caused by h2 traffic

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#3142]
The test below is a variant of the r2418 VTC that involves 2 clients instead of 3:

```
varnishtest "h2 watchdog panic"

barrier b1 cond 2

varnish v1 -cliok "param.set thread_pools 1"
varnish v1 -cliok "param.set thread_pool_min 3"
varnish v1 -cliok "param.set thread_pool_max 3"
varnish v1 -cliok "param.set thread_pool_reserve 1"
varnish v1 -cliok "param.set thread_pool_watchdog 1"
varnish v1 -cliok "param.set feature +http2"
varnish v1 -cliok "param.set feature +no_coredump"

varnish v1 -vcl {
	backend be none;
	sub vcl_recv {
		return (synth(200));
	}
} -start

client c1 {
	txpri
	stream 0 rxsettings -run

	barrier b1 sync

	stream 1 {
		txreq
		rxresp
	} -run
} -start

client c2 {
	barrier b1 sync
	txpri
	delay 2
} -start

client c1 -wait
client c2 -wait
```

Another variant of this test exists in https://github.com/varnishcache/varnish-cache/pull/2796#issuecomment-547536988 as #2796 sets new expectations (I'm just saying, in case it is merged before this issue is closed).

**Comment by daghf** [comment]
With 3 threads total and 1 reserve we effectively only have 2 threads available for h2 sessions and streams.

Client `c1` takes up one thread, `c2` takes up the second thread.

For `c1:stream1` we're all out of threads, so it gets queued. The delay in `c2` ensures that it will not get dequeued before the watchdog kicks in.

Isn't this just the watchdog working as advertised?

**Comment by Dridi** [comment]
Maybe, at the very least we have something to work on once #2796 is merged.

**Comment by nigoroll** [comment]
I agree with @daghf and think this could just get closed.

**Comment by bsdphk** [comment]
Agreed, this is not relevant.
