### ISSUE TITLE
BUG in varnish 

### ISSUE THREAD

**Issue by kaaaq** [varnishcache/varnish-cache#3144]
Im using varnish v 4.1.1, in our system after a while varnish suddenly crush and iowait raise a lot and we should restart varnish for fixing it.
this is journalctl resault after crushing varnish:

-- Logs begin at Tue ********************************** --

Nov 19 17:29:58 varnish-06 systemd[1]: Started Varnish HTTP accelerator.
Nov 19 17:29:59 varnish-06 varnishd[9205]: Debug: Platform: Linux,4.4.0-154-generic,x86_64,-junix,-smalloc,-smalloc,-hcritbit
Nov 19 17:29:59 varnish-06 varnishd[9205]: Platform: Linux,4.4.0-154-generic,x86_64,-junix,-smalloc,-smalloc,-hcritbit
Nov 19 17:29:59 varnish-06 varnishd[9205]: Debug: Child (9342) Started
Nov 19 17:29:59 varnish-06 varnishd[9205]: Child (9342) Started
Nov 19 17:29:59 varnish-06 varnishd[9205]: Info: Child (9342) said Child starts
Nov 19 17:29:59 varnish-06 varnishd[9205]: Child (9342) said Child starts
Nov 19 17:30:10 varnish-06 varnishd[9205]: Error: Manager got SIGINT
Nov 19 17:30:10 varnish-06 varnishd[9205]: Debug: Stopping Child
Nov 19 17:30:10 varnish-06 systemd[1]: Stopping Varnish HTTP accelerator...
Nov 19 17:30:10 varnish-06 varnishd[9205]: Manager got SIGINT
Nov 19 17:30:10 varnish-06 varnishd[9205]: Stopping Child
Nov 19 17:30:11 varnish-06 varnishd[9205]: Error: Child (9342) died signal=15
Nov 19 17:30:11 varnish-06 varnishd[9205]: Debug: Child cleanup complete
Nov 19 17:30:11 varnish-06 systemd[1]: Stopped Varnish HTTP accelerator.
Nov 19 17:30:11 varnish-06 systemd[1]: Started Varnish HTTP accelerator.
Nov 19 17:30:11 varnish-06 varnishd[10479]: Debug: Platform: Linux,4.4.0-154-generic,x86_64,-junix,-smalloc,-smalloc,-hcritbit
Nov 19 17:30:11 varnish-06 varnishd/varnish[10479]: Platform: Linux,4.4.0-154-generic,x86_64,-junix,-smalloc,-smalloc,-hcritbit
Nov 19 17:30:11 varnish-06 varnishd[10479]: Debug: Child (10513) Started
Nov 19 17:30:11 varnish-06 varnishd/varnish[10479]: Child (10513) Started
Nov 19 17:30:11 varnish-06 varnishd[10479]: Info: Child (10513) said Child starts
Nov 19 17:30:11 varnish-06 varnishd/varnish[10479]: Child (10513) said Child starts
Nov 20 17:22:11 varnish-06 systemd[1]: Stopping Varnish HTTP accelerator...
Nov 20 17:22:18 varnish-06 varnishd[10479]: Error: Child (10513) not responding to CLI, killing it.
Nov 20 17:22:18 varnish-06 varnishd/varnish[10479]: Child (10513) not responding to CLI, killing it.
Nov 20 17:22:18 varnish-06 varnishd[10479]: Error: Child (10513) not responding to CLI, killing it.
Nov 20 17:22:18 varnish-06 varnishd[10479]: Error: Manager got SIGINT
Nov 20 17:22:18 varnish-06 varnishd/varnish[10479]: Child (10513) not responding to CLI, killing it.
Nov 20 17:22:18 varnish-06 varnishd[10479]: Debug: Stopping Child
Nov 20 17:22:18 varnish-06 varnishd/varnish[10479]: Manager got SIGINT
Nov 20 17:22:18 varnish-06 varnishd/varnish[10479]: Stopping Child
Nov 20 17:22:18 varnish-06 varnishd[10479]: Error: Child (10513) died signal=15
Nov 20 17:22:18 varnish-06 varnishd/varnish[10479]: Child (10513) died signal=15
Nov 20 17:22:18 varnish-06 varnishd[10479]: Debug: Child cleanup complete

**Comment by nigoroll** [comment]
After #3139 and #3138 please DO NOT open any more bug reports before you have got informed about the ways we provide support: https://varnish-cache.org/support/

**Comment by hermunn** [comment]
Varnish Cache 4.1 has been end of life for some time now, see https://varnish-cache.org/lists/pipermail/varnish-announce/2018-December/000732.html

Furthermore, the latest version of 4.1 is 4.1.11, and it was released in January this year. You can find installation instructions for newer versions through the link above, but this is a more direct source: https://varnish-cache.org/docs/trunk/installation/index.html

I am closing this issue since the version you are reporting is very old, 4.1.1 was released January 2016.

**Comment by kaaaq** [comment]
Please answer my question without saying go another place...
I decided to installing new version of varnish,
Which version is the best? 
varnish_6.3.1-1~xenial_amd64.deb OR
varnish_6.0.5-1~xenial_amd64.deb
Thanks for Ur answer

**Comment by kaaaq** [comment]
Please answer my question without saying go another place...
I decided to installing new version of varnish,
Which version is the best?
varnish_6.3.1-1xenial_amd64.deb OR
varnish_6.0.5-1xenial_amd64.deb
Thanks for Ur answe

**Comment by nigoroll** [comment]
Please respect the response developers give you.
If you want commercial support, go buy it.
