### ISSUE TITLE
Truncated CLI responses don't always appear as such

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#3148]
When a CLI exceeds the `cli_limit` it is truncated and uses the status 201 instead of 200. This is not a hard error but the documentation states that the last line should mention that the \[response was truncated\] in addition to having a different status.

This is currently not the case for:

- VTE-based commands
- syslog'd CLI responses

There is also the question of JSON responses that shouldn't be mindlessly truncated, but for starters we should add some coverage and make sure that all relevant commands properly indicate when they overflow.

Currently this is only checked for one command:

https://github.com/varnishcache/varnish-cache/blob/806b697a4c72db45a9e186b9c4b3ce64bfbdde11/bin/varnishtest/tests/u00000.vtc#L116-L117

This isn't per-se a test targeted at the CLI itself, but rather `varnishadm`.

**Comment by nigoroll** [comment]
FTR this is a follow up on #3092

**Comment by bsdphk** [comment]
The syslog'ed responses should not be truncated by `cli_limit` IMO.

**Comment by bsdphk** [comment]
Bugwash questions:

Syslog copies of cli commands truncated: Yes/No ?

Is the '[response was truncated]' helpful ?

Should it be created by varnishadm, in response to 201 rather than varnishd ?

**Comment by bsdphk** [comment]
Bugwash consensus:

Truncate syslog (think ban.list)

varnishadm and other CLI talkers responsible for adding truncation warning.

JSON responses should not be truncated.

**Comment by nigoroll** [comment]
> JSON responses should not be truncated.
I do not think this will work because of `ban.list -j`
we might want to have other means of truncation, but we need something as an upper bound to long iterations like that.

**Comment by bsdphk** [comment]
Please comment on the JSON question:

Does truncating a JSON response make any sense ?

If truncation happens in JSON mode, should we substitute a valid JSON response communicating the truncation ?

**Comment by nigoroll** [comment]
> If truncation happens in JSON mode, should we substitute a valid JSON response communicating the truncation ?

This sounds like the best option to me for now.

Long term, would we might want to replace the cli_limit in bytes with something more general like "number of thingies"?

**Comment by andrewwiik** [comment]
@nigoroll it might be difficult to quantify for certain log messages what a "thingy" is

**Comment by nigoroll** [comment]
@andrewwiik it could be lines or KB as a fallback

**Comment by bsdphk** [comment]
Timed out.

We can revisit of truncation of JSON responses ever become an actual problem.
