### ISSUE TITLE
Caching a resource after specific number of requests

### ISSUE THREAD

**Issue by smart-developerr** [varnishcache/varnish-cache#3150]
Hello there!
Is there any functionality like [proxy_cache_min_uses](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_min_uses) in the Varnish cache that caches a resource after specific number of requests to that resource?

**Comment by nigoroll** [comment]
Yes and no. There are ways to do it, but not built in in the form of a simple switch.
Because we do not use github issues for support, please refer to the channels given in http://varnish-cache.org/support/index.html

**Comment by rezan** [comment]
Might make sense to discuss this a bit. In terms of caching, this is the most important optimization that can be done.

Would it be possible to add a counter on the objcore to track this? So if its a clean miss, the counter is 0. If its a HFM or multiple clients are waiting on the object, then the value is non zero. The VCL becomes:

```
sub vcl_backend_fetch {
    # This is a clean miss, dont cache
    if (!bereq.hits) {
        set beresp.uncacheable = true;
        return (deliver);
    }
}
```

Thoughts?

**Comment by gquintard** [comment]
you can't set `beresp.*` in `vcl_backend_fetch`, so you would need to use `bereq.uncacheable`, and it's probably best to pop a request from the waitinglist as soon as it get set to avoid waiting for `v_b_r` to return. But I like the idea.

**Comment by rezan** [comment]
That was a typo. Re-review :)

**Comment by smart-developerr** [comment]
Thanks! But I'm newbie to varnish, could you help with more descriptive code?

**Comment by slimhazard** [comment]
```
import vsthrottle;

sub vcl_recv {
    if (req.url ~ "^/min/use/me" && vsthrottle.is_denied(req.url, 50, 2h, 1h) {
        # If the URL was requested more than 50 times during the last two hours,
        # then go to cache lookup for the next hour.
        return (hash);
    }
    else {
        # Otherwise bypass the cache
        return (pass);
    }
}
```
``is_denied()`` is not an intuitive name for the "min uses" use case, but I think this would do the job. And it seems to me that the threshold duration makes more sense for min uses than an absolute threshold.
