### ISSUE TITLE
CORS issue with Varnish 6.2 on Firefox

### ISSUE THREAD

**Issue by ethniccode** [varnishcache/varnish-cache#3151]
Is this an issue with Varnish or Firefox? I have Magento 2.3.3 deployed with Varnish 6.2, nginx and assets being served via cloudfront. CORS is working fine in all browsers except FireFox. Firefox behavior is inconsistent. First time the fonts delivered without any issue. Upon clearing the firefox cache the second time browsing of site does not deliver fonts. I am not seeing CORS enabled headers while CURL and headers inspected on other browsers show CORS enabled headers. Below are the entries in nginx and VCL file. Also below are the screenshot of headers in firefox and chrome. Mostly importantly this issue doesn’t exist when varnish is disabled.

```
add_header 'Access-Control-Allow-Origin' '*' 'always';
if ($request_method = 'OPTIONS') {
    add_header 'Access-Control-Allow-Origin' '*' 'always';
    add_header 'Access-Control-Allow-Headers' 'x-requested-with' 'always';
    add_header 'Access-Control-Max-Age' 86400 'always';
    add_header 'Content-Length' 0 'always';
    return 204;
}

```
   ```
set resp.http.Access-Control-Allow-Origin = "*";
   if (req.method == "OPTIONS") {
       set resp.http.Access-Control-Allow-Origin = "*";
       set resp.http.Access-Control-Max-Age = "86400";
       set resp.http.Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS";
       set resp.http.Access-Control-Allow-Headers = "Origin, Accept, Content-Type, X-Requested-With, X-CSRF-Token";
       set resp.http.Content-Length = "0";
       set resp.status = 204;
     }

```

![Screenshot 2019-12-09 at 11 35 53 AM](https://user-images.githubusercontent.com/16968205/70412033-bea3eb00-1a79-11ea-93d3-46424a89bd8a.jpg)
![Screenshot 2019-12-09 at 11 36 32 AM copy](https://user-images.githubusercontent.com/16968205/70412042-c4013580-1a79-11ea-98c6-dfd8dadf07ac.jpg)

**Comment by Dridi** [comment]
When you open an issue you should get an issue template. The template clearly states that Github issues are for actionable bugs, for general questions you have support options like the misc@varnish-cache.org mailing list.

https://varnish-cache.org/support/
