### ISSUE TITLE
Using the release tarball to build custom debian packages states include/generate.py is missing

### ISSUE THREAD

**Issue by BlackIkeEagle** [varnishcache/varnish-cache#3165]
## Expected Behavior

* download release tarball
* git init
* add debian folder
* configure and build

## Current Behavior

* download release tarball
* git init
* add debian folder
* configure
* make -> fail

```
make[3]: Entering directory '/build/cmb-varnish6/include'
/usr/bin/python3.7: can't open file './generate.py': [Errno 2] No such file or directory
make[3]: *** [Makefile:1142: vcs_version.h] Error 2
```

## Possible Solution

https://github.com/varnishcache/varnish-cache/blob/master/include/Makefile.am#L135 checks if the toplevel source dir has a `.git` folder, which is the case for us. So when using the unpacked release tarball and init git in that folder you will get the error the generate.py file is missing

the possible solution can be found in the following patch:
https://github.com/BlackIkeEagle/varnish-deb/blob/stop-check-for-git-folder/debian/patches/0001-dont-generate-version-for-release-tarball.patch

## Steps to Reproduce (for bugs)

1. https://github.com/BlackIkeEagle/varnish-deb
2. mk-build-deps -irBt 'apt-get --no-install-recommends -y' debian/control
3. dpkg-buildpackage -us -uc -b

## Your Environment

* Version used: 6.3.1
* Operating System and version: debian buster (10)
* Source of binary packages used (if any)

**Comment by nigoroll** [comment]
The reason for the current behavior is that we want the generator scripts to always run for developers.

I wonder why you do not chose one of the following options:
* clone our repository and check out a release
* unpack the source tarball in a sub-directory of a repository

**Comment by BlackIkeEagle** [comment]
I understand why its there, but in theory it should not be there in a release tarball. Since the Makefile.in has a potential depenency on this generator.py being present - which isn't.

Maybe the generator.py can be added to the release tarball with fixed output so it would generate just the same content as what is shipped in vcs_version.h

Why like this:
We have over 100 custom packages - for various reasons - who have all the same structure, the source is the release code checked in in git + added debian folder. This makes it very easy for someone to start on something because everything has the same structure.

**Comment by BlackIkeEagle** [comment]
It's not like I really need this change, but I'm wondering if there is not a better solution that fits more flows

**Comment by BlackIkeEagle** [comment]
thanks
