### ISSUE TITLE
RFC: vmod read-access to parameters

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3172]
A very long time ago, we already discussed if parameters should be part of the API for vmods to use. The answer at the time was *no* and I _think_ it was 9699424ccd9f7fc51a8d1c651889433fdd200ce5 which put the final nail on the coffin to discourage vmod access to `struct param`, unless you were willing to leave `$ABI vrt` and compile requiring access to varnish internal headers.

The example at the time was access to the `pcre_match_limit` and `pcre_match_limit_recursion` which would be useful as defaults for [vmod_re](https://code.uplex.de/uplex-varnish/libvmod-re/blob/master/README.rst).

Since then, varnish has grown additional parameters and we would now have a use case where for a new [vmod_file](https://code.uplex.de/uplex-varnish/libvmod-file/blob/master/README.rst), access to `vcl_path` would be the sensible thing to set the default *path*.

So the topic is back on the table with the question: Should we make _some_ of the varnish parameters part of VRT? IMHO, at least the following could/would be useful and safe for vmods to access:

* ``*_timeout``, ``timeout_*``
* ``*_support``
* ``pcre_match_limit``
* ``pcre_match_limit_recursion``
* ``thread_pool_stack``
* ``vcl_path``

**Comment by slimhazard** [comment]
As I recall, the issue was that VMODs should not be able to modify the params, and I would agree. We have the CLI with `param.set` as the public interface for that, it should be enough.

If that's the issue, then why not just have read-only VRT access to all of the params? Rather than try to decide which of them to provide.

I would add that the API feels a bit inconsistent in some places, because it exposes some capabilities without a way to know about the params that might affect them. A good example is VRE -- `VRE_exec()` has an argument for the `pcre_*` params, and users may have changed those values for a reason. But a VMOD using VRE has a take a guess, or ask users to set the params a second time. The natural choice for `VRE_exec()` would be to default to whatever the current `pcre_*` settings are, but a VMOD can't do that and stay within VRT.

**Comment by nigoroll** [comment]
bugwash:
* `VRT_param_${type}(VCL_STRING name)`
* all parameters exposed
* return `const * const` for pointer types
* vmods have to behave and we are aware that vmods which intend not to, can do so anyways

**Comment by bsdphk** [comment]
The issue with changing parameters from anywhere in the worker process, is that the master-copy in the mgt process would not have them, so they would be lost in a restart.

**Comment by bsdphk** [comment]
Do consider for the special case of `vcl_path` if it would make more sense to have a `OpenThisFileNameTakingVclPathIntoConsideration()`

**Comment by bsdphk** [comment]
Uhmm... Hang on...  VclPath ?

The worker process is likely jailed, so it cannot be expected to have access to the directories in `vcl_path`

**Comment by Dridi** [comment]
> The issue with changing parameters from anywhere in the worker process, is that the master-copy in the mgt process would not have them, so they would be lost in a restart.

This is about read-only access, so that aspect should be safe. The only thing we can't prevent is a rogue VMOD ignoring the `const` qualifier of pointer-type parameters (I guess it's only strings?) and we agreed with @nigoroll that trying to work around that would be needless overhead. If a VMOD wants to wreck havoc today there are plenty symbols to pick from outside of VRT even without this suggestion.

> The worker process is likely jailed, so it cannot be expected to have access to the directories in `vcl_path`

Yes, not all parameters would make sense in VMOD space, but do we want to apply some kind of arbitrary filter to decide what's relevant or not?

**Comment by nigoroll** [comment]
re @Dridi I agree (and imply you suggest a "no" to your last question)

re @bsdphk 

> The worker process is likely jailed, so it cannot be expected to have access to the directories in `vcl_path`

Yes. But that is policy, right?

> `OpenThisFileNameTakingVclPathIntoConsideration()`

That would solve the issue, as well as `Get_Pcre_Match_Limit()`, but generic access to parameters appears to be much simpler and more generally useful.

**Comment by nigoroll** [comment]
note on bugwash: @bsdphk found out that `vcl_path` and other `tweak_string` parameters cannot be safely access from the worker process because pointers resulting from changes are valid only for the master.

**Comment by bsdphk** [comment]
The way string paramters (vcl_path, vmod_path and cc_command) are implemented, they are *never* safe to us in the client.

The master process simply calls REPLACE() on a pointer in struct param, and memcpy's that into VSM, but the corresponding malloc never happens in the worker process.

**Comment by bsdphk** [comment]
I guess somebody™ foresaw this years ago, those three pointers are not in the VSM'ed struct param.

**Comment by bsdphk** [comment]
Ok, with string value paramters out of the picture, back to numerical parameters.

It makes sense that vmods can inspect parameters, but there is a lot of dirty laundry hidden in mgt_param.c and we'd like to keep it there.

Proposed solution:

mgt_param.c exposes an iterator, which calls a callback function with prototype::

    int parlist_callback(void *priv, const char **name, const struct par_type *, const void *val, size_t len);

A nonzero returnvalue terminates the iteration immediately, and passes that value back to the caller of the iterator function.

Strictly speaking, the iterator function will live in the "common" name space, as it can be used form both mgt and child.

Contents of struct par_type to be thought about.

A VRT-wrapper will use the iterator to implement something like::

    int VRT_GetParam(const char **name, void *buf, size_t len);

**Comment by slimhazard** [comment]
What would the purpose of struct par_type be? I don't see anything in the proposal that requires it.

Other than that question, I'm +1 for the iterator and `VRT_GetParam()`. The linear search won't be efficient, but reading param values is probably not on anyone's critical path. My guess is that most or all of the UPLEX VMODs that might use it will only need it at init time (in `vcl_init`).

Also +1 for `OpenThisFileNameTakingVclPathIntoConsideration()`, except perhaps with a shorter name ...?

**Comment by nigoroll** [comment]
`OpenThisFileNameTakingVclPathIntoConsideration()` is dead because `vcl_path` is not available in the worker process as we learned today. Still pondering alternatives, will summarize later.

**Comment by slimhazard** [comment]
Oh I thought that was the idea for a safe alternative. If there is a safe alternative, presumably it will be encapsulated in `VRT_OpenOnVclPath()` in any case. (That's still a long name.)

I don't see why a VMOD would need to access vmod_path or cc_command, but vcl_path does seem reasonable. Our VMOD file would definitely use it, and `std.fileread()` would also benefit from it. The main use case is for large HTML custom error pages, which are cumbersome to embed into `vcl_synth`. It's very intuitive for VCL authors to put those in the same place they put their VCL sources. (VMOD file is mainly about letting you update the file at runtime, which `std.fileread()` doesn't allow.)

**Comment by nigoroll** [comment]
This ticket has served its purpose, we have a consensus regarding a viable implementation design, so the next step would be a PR.
Regarding the motivation to use `vcl_path`, I have opened #3181
