### ISSUE TITLE
`SES_*_client_ip` and `SES_*_client_port` is broken

### ISSUE THREAD

**Issue by catap** [varnishcache/varnish-cache#3173]
@bsdphk, hey!

I just would like to pointed that `SES_Get_client_ip` and `SES_Get_client_port` is broken since https://github.com/varnishcache/varnish-cache/commit/36477c6f6f2e68f1a76938cd03229e514ef01cb7.

For this two attributes a new conditions is `assert(0 > 0)` and varnish crashes on `SES_*_client_ip` and SES_*_client_port` with log:

```
Warnings:
VCL compiled.

Debug: Version: varnish-trunk revision 6a483b19f143ad472a4e82d2a76919f167f92b20
Debug: Platform: Darwin,19.2.0,x86_64,-jnone,-sdefault,-sdefault,-hcritbit
Debug: Child (89080) Started
Info: Child (89080) said Child starts
Error: Child (89080) died signal=6
Error: Child (89080) Panic at: Fri, 20 Dec 2019 22:57:29 GMT
Assert error in SES_Get_client_ip(), ../../include/tbl/sess_attr.h line 41:
  Condition(0 > 0) not true.
version = varnish-trunk revision 6a483b19f143ad472a4e82d2a76919f167f92b20, vrt api = 10.0
```

Right now it is possibly to overstep over `SES_Set_String_Attr` and `SES_Get_String_Attr`.

**Comment by nigoroll** [comment]
@catap use `SES_Get_String_Attr()` to access the string attributes and see 7c4cdd48563095fb70ff5db642288ae13a06f2ce for a demo and some background.

**Comment by catap** [comment]
@nigoroll I agree, but generate a function call of that crashed the process is bad idea.

Particularly if it works fine for years before.

**Comment by nigoroll** [comment]
@catap If you think you need the other function, please provide some code example.
With regards to existing interfaces, in the varnish-cache project, we have a long history of deliberate breaking interfaces to make progress, any at any rate SES_* was never part of VRT
