### ISSUE TITLE
Varnish 6.3 - clusters sick once we remove a backend & reload the conf (vcl.load / vcl.use)

### ISSUE THREAD

**Issue by anthosz** [varnishcache/varnish-cache#3183]
Hello,

I just discover an issue with Varnish 6.3.1.

Once the instance is started, if we change the composition of a cluster (by example comment 2 backends of a cluster (4 backends instead 6 online)) & we reload the configuration, the cluster status is sick (and each backends of this cluster).

## Expected Behavior
The removed backends need to be removed from the cluster without incidence on the other backends.

## Steps to Reproduce (for bugs)
1. VCL
```
backend a {
  .host = "1.1.1.1";
  .port = "80";
  .max_connections = 640;
  .first_byte_timeout = 300s;
  .between_bytes_timeout = 120s;
  .probe = test_probe;
}
backend b {
  .host = "2.2.2.2";
  .port = "80";
  .max_connections = 640;
  .first_byte_timeout = 300s;
  .between_bytes_timeout = 120s;
  .probe = test_probe;
}
backend c {
  .host = "3.3.3.3";
  .port = "80";
  .max_connections = 640;
  .first_byte_timeout = 300s;
  .between_bytes_timeout = 120s;
  .probe = test_probe;
}
backend d {
  .host = "4.4.4.4";
  .port = "80";
  .max_connections = 640;
  .first_byte_timeout = 300s;
  .between_bytes_timeout = 120s;
  .probe = test_probe;
}
...
  new clusterA = directors.round_robin();
  clusterA.add_backend(a);
  clusterA.add_backend(b);
  clusterA.add_backend(c);
  clusterA.add_backend(d);

  new clusterB = directors.round_robin();
  clusterB.add_backend(c);
  clusterB.add_backend(d);
...
set req.backend_hint = clusterA.backend();
...
set req.backend_hint = clusterB.backend();
```
2. Start the instance: all healthy / OK
3. Edit the previous conf
```
backend a {
  .host = "1.1.1.1";
  .port = "80";
  .max_connections = 640;
  .first_byte_timeout = 300s;
  .between_bytes_timeout = 120s;
  .probe = test_probe;
}
backend b {
  .host = "2.2.2.2";
  .port = "80";
  .max_connections = 640;
  .first_byte_timeout = 300s;
  .between_bytes_timeout = 120s;
  .probe = test_probe;
}
backend c {
  .host = "3.3.3.3";
  .port = "80";
  .max_connections = 640;
  .first_byte_timeout = 300s;
  .between_bytes_timeout = 120s;
  .probe = test_probe;
}
backend d {
  .host = "4.4.4.4";
  .port = "80";
  .max_connections = 640;
  .first_byte_timeout = 300s;
  .between_bytes_timeout = 120s;
  .probe = test_probe;
}
...
  new clusterA = directors.round_robin();
  cluster.add_backend(a);
  cluster.add_backend(b);

  new clusterB = directors.round_robin();
  clusterB.add_backend(c);
  clusterB.add_backend(d);
...
```
4. Reload the configuration via vcl.load / vcl.use
5. Cluster A & Cluster B (+ other round_robin directors) are sick instead to remove only the 2 machines of Cluster A only

## Your Environment
* Version used: 6.3.1
* Operating System and version: RHEL 7

**Comment by anthosz** [comment]
Update: I can reproduce it only with directors.round_robin() (all cluster are down when a backend is removed from one of the cluster)

directors.hash() not impacted by the change I cannot reproduce it on this type of director if I remove a backend from it.

**Comment by nigoroll** [comment]
This report does not look legit to me, just to be sure, I have tried to reproduce the issue:

base VCL:

```
vcl 4.1;

import directors;

probe p {
	.url = "/";
}

backend a {
	.host = "127.0.0.1";
	.port = "8080";
	.probe = p;
}
backend b {
	.host = "127.0.0.1";
	.port = "8080";
	.probe = p;
}
backend c {
	.host = "127.0.0.1";
	.port = "8080";
	.probe = p;
}
backend d {
	.host = "127.0.0.1";
	.port = "8080";
	.probe = p;
}

sub vcl_init {
	new rr_1 = directors.round_robin();
	rr_1.add_backend(a);
	rr_1.add_backend(b);
	rr_1.add_backend(c);
	rr_1.add_backend(d);

	new rr_2 = directors.round_robin();
	rr_2.add_backend(a);
	rr_2.add_backend(b);
}

sub vcl_recv {
	return (synth(200));
}
```

diff to changed vcl:

```
--- /tmp/t.vcl	2020-01-08 15:30:55.905747485 +0100
+++ /tmp/t1.vcl	2020-01-08 15:32:02.137750310 +0100
@@ -31,12 +31,10 @@
 	new rr_1 = directors.round_robin();
 	rr_1.add_backend(a);
 	rr_1.add_backend(b);
-	rr_1.add_backend(c);
-	rr_1.add_backend(d);
 
 	new rr_2 = directors.round_robin();
-	rr_2.add_backend(a);
-	rr_2.add_backend(b);
+	rr_2.add_backend(c);
+	rr_2.add_backend(d);
 }
 
 sub vcl_recv {
```

demo/test:

```
$ /tmp/sbin/varnishd -a 127.0.0.1:8080 -f /tmp/t.vcl 
Warnings:
VCL compiled.

Debug: Version: varnish-trunk revision c46b48506f19e0d4e9bb14662c455621887dae66
Debug: Platform: Linux,4.9.0-11-amd64,x86_64,-jnone,-sdefault,-sdefault,-hcritbit
Debug: Child (20309) Started
$ /tmp/bin/varnishadm backend.list
Backend name   Admin    Probe    Health     Last change
boot.a         probe    3/8      healthy    Wed, 08 Jan 2020 14:31:10 GMT
boot.b         probe    3/8      healthy    Wed, 08 Jan 2020 14:31:10 GMT
boot.c         probe    3/8      healthy    Wed, 08 Jan 2020 14:31:10 GMT
boot.d         probe    3/8      healthy    Wed, 08 Jan 2020 14:31:10 GMT
boot.rr_1      probe    4/4      healthy    Wed, 08 Jan 2020 14:31:10 GMT
boot.rr_2      probe    2/2      healthy    Wed, 08 Jan 2020 14:31:10 GMT

$ /tmp/bin/varnishadm vcl.load t1 /tmp/t1.vcl
VCL compiled.

$ /tmp/bin/varnishadm vcl.use t1
VCL 't1' now active
$ /tmp/bin/varnishadm backend.list
Backend name   Admin    Probe    Health     Last change
t1.a           probe    4/8      healthy    Wed, 08 Jan 2020 14:32:05 GMT
t1.b           probe    4/8      healthy    Wed, 08 Jan 2020 14:32:05 GMT
t1.c           probe    4/8      healthy    Wed, 08 Jan 2020 14:32:05 GMT
t1.d           probe    4/8      healthy    Wed, 08 Jan 2020 14:32:05 GMT
t1.rr_1        probe    2/2      healthy    Wed, 08 Jan 2020 14:32:05 GMT
t1.rr_2        probe    2/2      healthy    Wed, 08 Jan 2020 14:32:05 GMT

```

**Comment by anthosz** [comment]
@nigoroll 
It's not like my example (in my case, there are 2 same backends that are used in 2 clusters):

Could you try:
VCL
```
sub vcl_init {
	new rr_1 = directors.round_robin();
	rr_1.add_backend(a);
	rr_1.add_backend(b);
	rr_1.add_backend(c);
	rr_1.add_backend(d);

	new rr_2 = directors.round_robin();
	rr_2.add_backend(c);
	rr_2.add_backend(d);
}
```
NEW VCL
```
sub vcl_init {
	new rr_1 = directors.round_robin();
	rr_1.add_backend(a);
	rr_1.add_backend(b);

	new rr_2 = directors.round_robin();
	rr_2.add_backend(c);
	rr_2.add_backend(d);
}
```

**Comment by nigoroll** [comment]
@anthosz apologies for having missed that detail, but the result is the same.

```
--- /tmp/t.vcl	2020-01-08 15:50:00.245796302 +0100
+++ /tmp/t1.vcl	2020-01-08 15:32:02.137750310 +0100
@@ -31,8 +31,6 @@
 	new rr_1 = directors.round_robin();
 	rr_1.add_backend(a);
 	rr_1.add_backend(b);
-	rr_1.add_backend(c);
-	rr_1.add_backend(d);
 
 	new rr_2 = directors.round_robin();
 	rr_2.add_backend(c);

```

**Comment by anthosz** [comment]
@nigoroll 
On my side: I use Debug: Version: varnish-6.3.1 revision 6e96ff048692235e64565211a38c41432a26c055

Can be related?

**Comment by nigoroll** [comment]
are you aware that based on your `.initial` / `.window` / `.threshold` probe settings you might need some probes to succeed before backend become healthy on a newly loaded vcl?
See http://varnish-cache.org/docs/trunk/reference/vcl.html#probes

**Comment by nigoroll** [comment]
I have also built the 6.3.1 release to be even more confident that the root cause of the issue you are seeing is not related to varnish-cache core:

```
$ /tmp/sbin/varnishd -a 127.0.0.1:8080 -f /tmp/t.vcl 
Debug: Version: varnish-6.3.1 revision 6e96ff048692235e64565211a38c41432a26c055
Debug: Platform: Linux,4.9.0-11-amd64,x86_64,-jnone,-sdefault,-sdefault,-hcritbit
Debug: Child (16094) Started
$ /tmp/bin/varnishadm backend.list
Backend name   Admin    Probe    Health     Last change
boot.a         probe    4/8      healthy    Wed, 08 Jan 2020 14:59:39 GMT
boot.b         probe    4/8      healthy    Wed, 08 Jan 2020 14:59:39 GMT
boot.c         probe    4/8      healthy    Wed, 08 Jan 2020 14:59:39 GMT
boot.d         probe    4/8      healthy    Wed, 08 Jan 2020 14:59:39 GMT
boot.rr_1      probe    4/4      healthy    Wed, 08 Jan 2020 14:59:39 GMT
boot.rr_2      probe    2/2      healthy    Wed, 08 Jan 2020 14:59:39 GMT

$ /tmp/bin/varnishadm vcl.load t1 /tmp/t1.vcl 
VCL compiled.

$ /tmp/bin/varnishadm vcl.use t1
VCL 't1' now active
slink@haggis:~/Devel/varnish-git/varnish-cache ((varnish-6.3.1))$ /tmp/bin/varnishadm backend.list
Backend name   Admin    Probe    Health     Last change
t1.a           probe    4/8      healthy    Wed, 08 Jan 2020 15:00:04 GMT
t1.b           probe    4/8      healthy    Wed, 08 Jan 2020 15:00:04 GMT
t1.c           probe    4/8      healthy    Wed, 08 Jan 2020 15:00:04 GMT
t1.d           probe    4/8      healthy    Wed, 08 Jan 2020 15:00:04 GMT
t1.rr_1        probe    2/2      healthy    Wed, 08 Jan 2020 15:00:04 GMT
t1.rr_2        probe    2/2      healthy    Wed, 08 Jan 2020 15:00:04 GMT

```

**Comment by anthosz** [comment]
> 
> 
> I have also built the 6.3.1 release to be even more confident that the root cause of the issue you are seeing is not related to varnish-cache core:
> 
> ```
> $ /tmp/sbin/varnishd -a 127.0.0.1:8080 -f /tmp/t.vcl 
> Debug: Version: varnish-6.3.1 revision 6e96ff048692235e64565211a38c41432a26c055
> Debug: Platform: Linux,4.9.0-11-amd64,x86_64,-jnone,-sdefault,-sdefault,-hcritbit
> Debug: Child (16094) Started
> $ /tmp/bin/varnishadm backend.list
> Backend name   Admin    Probe    Health     Last change
> boot.a         probe    4/8      healthy    Wed, 08 Jan 2020 14:59:39 GMT
> boot.b         probe    4/8      healthy    Wed, 08 Jan 2020 14:59:39 GMT
> boot.c         probe    4/8      healthy    Wed, 08 Jan 2020 14:59:39 GMT
> boot.d         probe    4/8      healthy    Wed, 08 Jan 2020 14:59:39 GMT
> boot.rr_1      probe    4/4      healthy    Wed, 08 Jan 2020 14:59:39 GMT
> boot.rr_2      probe    2/2      healthy    Wed, 08 Jan 2020 14:59:39 GMT
> 
> $ /tmp/bin/varnishadm vcl.load t1 /tmp/t1.vcl 
> VCL compiled.
> 
> $ /tmp/bin/varnishadm vcl.use t1
> VCL 't1' now active
> slink@haggis:~/Devel/varnish-git/varnish-cache ((varnish-6.3.1))$ /tmp/bin/varnishadm backend.list
> Backend name   Admin    Probe    Health     Last change
> t1.a           probe    4/8      healthy    Wed, 08 Jan 2020 15:00:04 GMT
> t1.b           probe    4/8      healthy    Wed, 08 Jan 2020 15:00:04 GMT
> t1.c           probe    4/8      healthy    Wed, 08 Jan 2020 15:00:04 GMT
> t1.d           probe    4/8      healthy    Wed, 08 Jan 2020 15:00:04 GMT
> t1.rr_1        probe    2/2      healthy    Wed, 08 Jan 2020 15:00:04 GMT
> t1.rr_2        probe    2/2      healthy    Wed, 08 Jan 2020 15:00:04 GMT
> ```

Indeed, I just try with your config & it works.. I don't understand how is it possible :o My only changes is to remove 2 backens and reload.. I will investigate. Thx!

Concerning probes, I confirm that all is in health state on my side and switch to sick in parallel of the reload (30 min after, alway in sick state)...

**Comment by Dridi** [comment]
That's probably because by default the initial value of a probe is its threshold minus one, so it starts sick until the first probe requests succeeds, assuming healthy backends.

In `varnishreload` we have the possibility to add a delay for that between `vcl.load` and `vcl.use`:

https://github.com/varnishcache/pkg-varnish-cache/blob/ec7ad9e6c6dd7c9b4f4ba60c5b223376908c3ca6/systemd/varnishreload#L46-L74

See the `-w` option.

I don't think this is a bug, at best an unfortunate side effect of having per-VCL backends that start their probes from scratch at `vcl.load` time even if a previous identical backend existed and was healthy (a trade-off for dynamic backends).
