### ISSUE TITLE
http/2 send_timeout triggered but not in http/1

### ISSUE THREAD

**Issue by Cactusbone** [varnishcache/varnish-cache#3189]
Using http/1 and `beresp.do_stream = true`, we can take as long as we want to send data,
but after switching to http/2, the send_timeout is triggered and connection closes.

## Expected Behavior
Either connection should close using http/1 to honor send_timeout configuration, or it should not close in http/2.

## Current Behavior
Connection is closed after send_timeout using http/2, but not http/1, both with `beresp.do_stream = true`, `beresp.do_gzip = false` and `beresp.ttl = 0s;`

## Possible Solution
Improve docs to explain http/2 behaviour
Ability to configure send_timeout in VCL will solve problem (#2983)

## Steps to Reproduce
1. have a backend which send data regularly, taking a high time, for exemple, we sent a dot every second for 700seconds (to reach the default 600s timeout)
2. use http/2 to call the backend. we used haproxy in tcp mode for ssl termination
3. wait until the timeout, connection get closed.
4. using http/1, connection is not closed

## Context
We're sending a file to client, generating it on the fly.  Right now we increased timeout to 4 hours so it's working, but we might be keeping idle connections for naught.
I must stress out that connection is not closed using http/1, so we're sending enough data to keep connection alive

## Your Environment
* Version used: 6.3.1
* Operating System and version: docker image
* Source of binary packages used (if any) "official" docker image 6.3.1
Running behind a haproxy 7.5 in proxy mode

**Comment by nigoroll** [comment]
@Cactusbone your report comes as a surprise because we got test cases for HTTP/1 `send_timeout` 
Can you please double check if this issue has been diagnosed correctly and provide varnishlog evidence to us? A reproducible test case would be ideal.

**Comment by Cactusbone** [comment]
I'll look at test cases to see if I can reproduce

**Comment by Cactusbone** [comment]
Using a default varnish installation on ubuntu 18.04, with a nodejs server, connection is not closed in http/1

```sh
apt-get install varnish nodejs
```

Nodejs server simply sends a dot every second for 700s, then ends https request properly.

server.js in node.js : 
```js 
const http = require('http');
const delay = time => new Promise(res => setTimeout(res, time));

const requestListener = async function (req, res) {
    res.writeHead(200);
    for (let time = 0; time < 700; time++) {
        res.write(".");
        await delay(1000);
    }
    res.end();
}

const server = http.createServer(requestListener);
server.listen(8080);
```

`node server.js &`

`curl localhost:6081` => no timeout after 600s

I've also tried using `-p send_timeout=30` and it was not closed after 30s either.

**Comment by Cactusbone** [comment]
I've edited the previous post with varnish logs and configuration files to reproduce

**Comment by nigoroll** [comment]
@Cactusbone thank you very much for the detailed information. We should be able to work with that.
I suspect that lowering `idle_send_timeout` could help you, but I have not got around to looking into the details.

**Comment by Cactusbone** [comment]
@nigoroll idle timeout is set to 30sec by default, but we're sending data every second, so I believe it's not triggered at all. For now we increased send_timeout to 4h, which seems enough for our use case.

**Comment by nigoroll** [comment]
I got a simple VTC reproducing the issue now. Expect a fix soon.
