### ISSUE TITLE
Missing copyright notices/licensing information

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#3200]
I've had a phone-call from a rather grumpy person, who pointed out that a LOT of the files in our distribution lacks copyright/license information.

He didn't actually point out anything which were an obstacle to using Varnish Cache in the application his company was contemplating, but he was grumpy about the amount of time he had spent making sure that was indeed the case.

**Comment by nigoroll** [comment]
bugwash conclusion IMHO:

> (15:22:28) phk: if any of you want to help improve the situation as far as your own works, please do.
> (15:22:36) phk: coord with me if it is other peoples works.

**Comment by bsdphk** [comment]
I'll deal with this.  Please forward names of contributors to .rst and .vtc if you know of any.

**Comment by bsdphk** [comment]
I have done what I reasonably can now.

I have not found anything which imperils our "BSD-licensed" status, nor anything which should trouble a competent and pragmatic laywer.
