### ISSUE TITLE
RFC: workspace sizes on 32 bit

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3203]
I am a bit lost regarding `v00004.vtc` failures on 32bit, exposed (_not_ caused!) by 598b13d7fb96e65346e25ab5fdbe1810a3dd93d7:
Our default 32bit client workspace (24k) has long been too small to accommodate this test, which is intended as a sanity check on our defaults in the first place.
I think that this kind of header fiddling (setting a 16k response header) _is_ a realistic test case, so the only consequence would be to use out 64bit workspace sizes also for 32bit.
On the other hand, this could lead to 32bit installations exposing more failures by default.

This issue is to ask for opinions. Some questions I would have:
* Is 32bit support relevant in practice or is it more a means to assure code quality?
* Are larger default workspace sizes helpful or do they cause harm?

**Comment by bsdphk** [comment]
We are probably degrading 32bit archs to "best effort" starting at Varnish 7.0, so this is not worth wasting too much time on.

Make these test "feature 64bit" and move on.
