### ISSUE TITLE
RFC: struct hdr_name instead of "\007string:"

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#3214]
As I was working on #3211 I noticed that our header constants aren't really constant and we need an `HTTP_Init()` step to fix their length. It also reminded me that despite understanding the optimization behind header name strings with their sizes encoded in the first octet, I'm really not happy with magic `+1` offsets whenever we need it (it also leaks in the `VCL_HEADER` type).

I'm asking for permission to go through the code base and introduce a new type instead, with the following construct:

```c
#include <stdint.h>
#include <stdio.h>

struct hdr_name {
	uint8_t		len;
	const char	str[];
};

#define HDR_NAME(name)	((const struct hdr_name*)			\
	    &(const struct { uint8_t _l; char _s[sizeof(name ":")]; })	\
	    { sizeof(name), name ":" })

/* convenience macro */
const struct hdr_name *const H_Host = HDR_NAME("Host");
const struct hdr_name *const H_Cache_Control = HDR_NAME("Cache-Control");

/* hard-coded layout */
const struct hdr_name *const H_Same_Layout = (struct hdr_name *)("\014Same-Layout:");

int
main(void)
{

	printf("%2u %s\n", H_Host->len, H_Host->str);
	printf("%2u %s\n", H_Cache_Control->len, H_Cache_Control->str);
	printf("%2u %s\n", H_Same_Layout->len, H_Same_Layout->str);
	return (0);
}
```

This only changes how we manipulate header names, not their layout, and it should result in more readable code:

```diff
--- i/bin/varnishd/cache/cache_http.c
+++ w/bin/varnishd/cache/cache_http.c
@@ -292,17 +292,14 @@ http_PutField(struct http *to, int field, const char *string)
 /*--------------------------------------------------------------------*/
 
 static int
-http_IsHdr(const txt *hh, const char *hdr)
+http_IsHdr(const txt *hh, const struct hdr_name *hn)
 {
-       unsigned l;
 
        Tcheck(*hh);
-       AN(hdr);
-       l = hdr[0];
-       assert(l == strlen(hdr + 1));
-       assert(hdr[l] == ':');
-       hdr++;
-       return (!strncasecmp(hdr, hh->b, l));
+       AN(hn);
+       assert(hn->len == strlen(hn->str));
+       assert(hn->str[hn->len - 1] == ':');
+       return (!strncasecmp(hn->str, hh->b, l));
 }
 
 /*--------------------------------------------------------------------*/
```

To my knowledge, this is all legal C99 code, and both GCC and Clang seem to approve:

```
$ gcc hdr_name.c -std=c99 -pedantic -Wall -Wextra -Werror && ./a.out 
 5 Host:
14 Cache-Control:
12 Same-Layout:
$ gcc hdr_name.c -std=c90 -pedantic -Wall -Wextra -Werror && ./a.out 
hdr_name.c:6:13: warning: ISO C90 does not support flexible array members [-Wpedantic]
    6 |  const char str[];
      |             ^~~
hdr_name.c:11:6: warning: ISO C90 forbids compound literals [-Wpedantic]
   11 |      { sizeof(name), name ":" })
      |      ^
hdr_name.c:14:39: note: in expansion of macro ‘HDR_NAME’
   14 | const struct hdr_name *const H_Host = HDR_NAME("Host");
      |                                       ^~~~~~~~
hdr_name.c:11:6: warning: ISO C90 forbids compound literals [-Wpedantic]
   11 |      { sizeof(name), name ":" })
      |      ^
hdr_name.c:15:48: note: in expansion of macro ‘HDR_NAME’
   15 | const struct hdr_name *const H_Cache_Control = HDR_NAME("Cache-Control");
      |                                                ^~~~~~~~
cc1: all warnings being treated as errors
```

Permission to proceed?

**Comment by nigoroll** [comment]
lgtm

**Comment by bsdphk** [comment]
This has merit, but not one month before a release ?

**Comment by nigoroll** [comment]
FTR for the @Dridi s who could not attend bugwash:

> (15:04:02) slink: 3214 so dridi is primarily asking for an ok, which I guess he got
> (15:04:20) phk: I'm not sold on this (yet), but I'm firmly against something this intrusive and totally untested a month before release
> (15:04:22) slink: waiting until after the release is probably the safe option
> (15:04:43) slink: what is your reservation?
> (15:04:55) phk: also, doesn't this screw any vmod with a built in header name ?
> (15:05:12) phk: My reservation is precisely what I said: Intrusive and untested
> (15:05:21) slink: ok
> (15:05:55) slink: the vmod interface is `typedef const struct gethdr_s *                   VCL_HEADER`
> (15:05:57) phk: and as I started out saying: it has merit, but it is by no means a trivial change.
> (15:06:13) slink: I do not think we have an issue there, but yes, we will see such things when there is code

**Comment by Dridi** [comment]
I kinda forgot that we have a major release soon, so let's shelve this for after the release. I agree that I shouldn't proceed directly so instead I will open a pull request with this change and maybe Someone(tm) will pick it up and confront it to production.

**Comment by Dridi** [comment]
Continued in #3215, we can revisit this after the next release.
