### ISSUE TITLE
Different handling of Age when pass and miss

### ISSUE THREAD

**Issue by espebra** [varnishcache/varnish-cache#3221]
## Expected Behavior

If we get a ``beresp.http.age``, it is expected that Varnish takes the value into account when calculating ``beresp.ttl`` and also passing the value over into ``resp.http.age`` to let the client know how old the object really is.

Related section in the RFC: https://tools.ietf.org/html/rfc7234#section-4.2.3

## Current Behavior

This is done as expected on cache misses (and cache inserts). However, on pass ``resp.http.age`` is always set to 0, independent on whether we got a ``beresp.http.age`` or not. It is unexpected that the handling differs between miss and pass, and also that ``beresp.http.age`` is not considered for pass.

## Possible Solution
A VCL workaround is to copy ``beresp.http.age`` into ``resp.http.age`` on pass, but default behavior for pass should perhaps be to let the client know the value of ``beresp.http.age``.

## Steps to Reproduce (for bugs)
[Test case (c2 currently fails)](https://github.com/varnishcache/varnish-cache/files/4203647/pass.vtc.txt)

## Context
Proper handling of Age makes Varnish easier to use in stacks with multiple HTTP caches in the delivery path.

**Comment by bsdphk** [comment]
I'm not sure what you mean when you write "considered for pass" ?

I would expect pass to just send it straight through ?

**Comment by Dridi** [comment]
That's the problem, currently the test case fails because Varnish replies with an unconditional `Age: 0` if I understood @espebra's problem correctly.

I'm also inlining the test case here to make things simpler:

```
varnishtest "Handling of Age and TTL when return(pass)"

server s1 {
	rxreq
	txresp -hdr "cache-control: max-age=2" -hdr "age: 1"

	rxreq
	txresp -hdr "cache-control: max-age=2" -hdr "age: 1"
} -start

varnish v1 -vcl+backend {
	sub vcl_recv {
		if (req.url == "/pass") {
			return(pass);
		}
	}
	sub vcl_backend_response {
		set beresp.http.ttl = beresp.ttl;
	}
} -start

client c1 {
	txreq
	rxresp
	expect resp.http.age == 1
	expect resp.http.ttl == 1.000
} -run

client c2 {
	txreq -url "/pass"
	rxresp
	expect resp.http.age == 1        # THIS EXPECTATION FAILS
	expect resp.http.ttl == 1.000
} -run
```

**Comment by nigoroll** [comment]
bugwash tendency: fixing `t_origin` considered the better option, unless it introduces rounding issues

**Comment by mbgrydeland** [comment]
This regression was introduced in Varnish 5.0

**Comment by mbgrydeland** [comment]
@nigoroll I have updated and force pushed this PR with the changes we discussed during bugwash.
