### ISSUE TITLE
Default session_workspace causes sessions closed with OVERLOAD

### ISSUE THREAD

**Issue by kn-cpt** [varnishcache/varnish-cache#3225]
Sessions are closed with OVERLOAD due to insufficient session workspace.

## Expected Behavior
Proper session handling with the default value of `session_workspace`.

## Current Behavior
Sessions to particular mobile clients (iOS, Android) are closed with `OVERLOAD`.
Desktop, cURL, etc. work fine.
This also only happens with one particular backend (read: product) that is being cached
and is not a general problem.

## Possible Solution
Bumping the default value of 0.5K to 0.505K (0.005K = 5 bytes increase) fixes a great deal of those sessions, bumping it to 0.51K fixes all of them and `MAIN.sc_overload` constantly stays at zero.

## Steps to Reproduce (for bugs)
As this is both client and backend specific, I cannot provide a generic reproducer.
It does happen reproducibly in our setup, so I can provide specific debug information, performance counters or log snippets if need be.

## Context
Increasing the workspace by 10 bytes seems suspiciously low,
https://varnish-cache.org/docs/6.3/reference/varnishd.html#workspace-session indicates that this memory area is used for varnish internal structures and client/server IP addresses be the only environment specific data in it.

## Your Environment
PROXY2 frontend
IPv4 only

* Version used: varnish-6.3.2-1.el7.x86_64 , hitch-1.5.2-1.el7.x86_64
* Operating System and version:  CentOS Linux release 7.7.1908 (Core)
* Source of binary packages used (if any): EPEL

**Comment by nigoroll** [comment]
This is already addressed in 0f3bb35480acadbb910c6f7277d815f40ce5a7f7 which will be part of the next release
