### ISSUE TITLE
RFC: optimize vcl_init compile time during `vcl.load`

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3230]
I have seen cases where `vcl_init` has thousands of lines, for example for initialization of [vmod_re2](https://code.uplex.de/uplex-varnish/libvmod-re2).

With default flags, gcc invoked for VCL loading might spend considerable amounts of time compiling such code, with most of the time spent in the optimization phase as shown in this example from a gcc call with `-ftime-report`:

```
Execution times (seconds)
 phase setup             :   0.00 ( 0%) usr   0.00 ( 0%) sys   0.00 ( 0%) wall   1104 kB ( 1%) ggc
 phase parsing           :   0.28 ( 1%) usr   0.45 (52%) sys   0.72 ( 4%) wall  16266 kB (10%) ggc
 phase opt and generate  :  19.19 (99%) usr   0.40 (47%) sys  19.60 (96%) wall 151549 kB (89%) ggc
 phase last asm          :   0.01 ( 0%) usr   0.00 ( 0%) sys   0.01 ( 0%) wall    261 kB ( 0%) ggc
 phase finalize          :   0.00 ( 0%) usr   0.01 ( 1%) sys   0.00 ( 0%) wall      0 kB ( 0%) ggc
 dump files              :   0.00 ( 0%) usr   0.00 ( 0%) sys   0.01 ( 0%) wall      0 kB ( 0%) ggc
 callgraph construction  :   0.02 ( 0%) usr   0.00 ( 0%) sys   0.01 ( 0%) wall   7505 kB ( 4%) ggc
 ipa cp                  :   0.04 ( 0%) usr   0.00 ( 0%) sys   0.02 ( 0%) wall   2690 kB ( 2%) ggc
 ...
```

I checked some options on how best to optimize this case (not sacrificing performance elsewhere) and the best option I came up with so far is to add an `optimize` attribute for `vcl_init` as inline-C to the VCL:

```
C{
void __attribute__((optimize("O"))) VGC_function_vcl_init(VRT_CTX);
}C
```

in my case, this speeds up vcl compilation from ~90 to ~20 seconds (x4.5 speedup)

The reasoning here is that `vcl_init` is run exactly once per `vcl.load`, so any effort put into optimization is wasted effort.

Question: Do we want something like this by default? We could have a macro similar to the following

```
#if __GNUC_PREREQ__(4,4) // added 2008-07-23
#  define v_cold __attribute__((optimize("O"))) // or optimize(0)
#else
#  define v_cold
#endif
```

and then use `v_cold` to decorate the code generated for `vcl_init` and `vcl_fini`

What do you think?

**Comment by Dridi** [comment]
I think it's a great idea, similar to #3020.

**Comment by bsdphk** [comment]
Can I get you do an experiment ?

Split your vcl_init into three equali sized subs and call those from vcl_init, then time the compilation ?

Some compiler optimizations go O(n²) or worse on the line count in functions.

**Comment by nigoroll** [comment]
@bsdphk good point.

Splitting the functions helps in addition to the optimizer setting:

original vcl:
```
# time varnishadm vcl.load ori /tmp/ori/default.vcl 
VCL compiled.


real	1m51.389s
user	0m0.000s
sys	0m0.000s
```

with `void __attribute__((optimize("O"))) VGC_function_vcl_init(VRT_CTX);`:

```
# time varnishadm vcl.load attr_opti default.vcl 
VCL compiled.


real	0m21.303s
user	0m0.000s
sys	0m0.000s
```

one part of `vcl_init` split in 5 subs (that was more natural than 3):

```
# time varnishadm vcl.load split_5 /tmp/split_5/default.vcl 
VCL compiled.


real	0m44.659s
user	0m0.000s
sys	0m0.000s
```

split and `void __attribute__((optimize("O")))` on the split subs:

```
# time varnishadm vcl.load attr_opti_split_5 /tmp/attr_opti_split_5/default.vcl 
VCL compiled.


real	0m9.825s
user	0m0.000s
sys	0m0.000s
```

**Comment by bsdphk** [comment]
How many lines were the longest part of vcl_init in that test ?

**Comment by bsdphk** [comment]
(Context: There has been similar issues with huge ACLs in the past)

**Comment by nigoroll** [comment]
The longest sub has ~4.7k lines, second longest ~3.1k

**Comment by nigoroll** [comment]
bugwash: `v_dont_optimize` define
