### ISSUE TITLE
autodetect varnish config

### ISSUE THREAD

**Issue by timur1988** [varnishcache/varnish-cache#3233]
Good afternoon!We want to learn more about your product . There is a website warnish want to use as a front well, or for nginx . But we have a problem with a lot of mobile devices . Do you have a description of auto-detect devices? Can a barbarian do this?And maybe there is an example of a config we will look at and read.

**Comment by Dridi** [comment]
The github issue templates makes it clear that our issue tracker is for actionable bugs only, use the misc mailing list for general questions.

https://varnish-cache.org/support/
