### ISSUE TITLE
g00005.vtc fails on Linux/powerpc 

### ISSUE THREAD

**Issue by ingvarha** [varnishcache/varnish-cache#3235]
g00005.vtc fails on Linux/powerpc 

Environment: Ubuntu 16.04 (Xenial), 32-bit powerpc

Logs attached

Ingvar

**Comment by ingvarha** [comment]
[varnish-cache-issue-3235.txt](https://github.com/varnishcache/varnish-cache/files/4271015/varnish-cache-issue-3235.txt)

**Comment by Dridi** [comment]
Can you try f82b5f150f2a9aa92ac38665d90082cc51aeb2d8?

**Comment by ingvarha** [comment]
Yes, that change makes the test work on xenial/ppc.

**Comment by nigoroll** [comment]
dup #3237

**Comment by Dridi** [comment]
This is certainly not a duplicate, the suggested patch (thanks @ingvarha for confirming) closes a race unrelated to the DNS canary issue.

**Comment by nigoroll** [comment]
sorry

**Comment by Dridi** [comment]
No worries, back-ported as 03e5bae.
