### ISSUE TITLE
r02964.vtc fails on Linux/powerpc 

### ISSUE THREAD

**Issue by ingvarha** [varnishcache/varnish-cache#3236]
r02964.vtc fails on Linux/powerpc

Environment: Ubuntu 16.04 (Xenial), 32-bit powerpc

Logs attached

Ingvar

**Comment by ingvarha** [comment]
[varnish-cache-issue-3236.txt](https://github.com/varnishcache/varnish-cache/files/4271038/varnish-cache-issue-3236.txt)

**Comment by Dridi** [comment]
Can you try 79ae2fd8442152a83536d6901b58025eb4512ee4?

**Comment by ingvarha** [comment]
Yes, this makes the test work on xenial/ppc

**Comment by nigoroll** [comment]
dup #3237

**Comment by Dridi** [comment]
This is not a duplicate, the suggested patch (thanks @ingvarha for confirming) will be pushed to the 6.3 branch just in case we have another 6.3 release in the future.

**Comment by nigoroll** [comment]
sorry.

**Comment by Dridi** [comment]
No worries, back-ported as 8646119.
