### ISSUE TITLE
should we clean out the working directory?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3243]
It was noticed that for a varnish update, the `vmod_cache` directory in the working directory still contains old vmod versions.

I wonder: should we maybe clean out our working directory or at least the vmod cache?

Ref:

https://github.com/varnishcache/varnish-cache/blob/0e13b705eafdc2bfa1cc29a660dd75227e179212/bin/varnishd/mgt/mgt_main.c#L761

https://github.com/varnishcache/varnish-cache/blob/0e13b705eafdc2bfa1cc29a660dd75227e179212/bin/varnishd/mgt/mgt_jail.c#L152

**Comment by Dridi** [comment]
We already prune the contents of the working directory during startup. And something I find weird is that we remove sub-directories in the working directory so this was probably just an oversight:

https://github.com/varnishcache/varnish-cache/blob/0e13b705eafdc2bfa1cc29a660dd75227e179212/bin/varnishd/mgt/mgt_shmem.c#L71-L85

**Comment by bsdphk** [comment]
yes, looks like an oversight.

**Comment by bsdphk** [comment]
Nobody objects to cleaning, but maybe we need a way to keep the child state around for debugging
