### ISSUE TITLE
need logexpect negative matches // logexpect doesn't fail when timeout is specified

### ISSUE THREAD

**Issue by dbevacqua** [varnishcache/varnish-cache#3249]
It's possible that I have misinterpreted the purpose of the `-T` argument to `logexpect`, but it seems that specifying any value for it causes it not to fail.
 
## Expected Behavior

When `-T` is specified for a `logexpect` thread, test should fail if timeout is reached

## Current Behavior

When `-T` is specified for a `logexpect` thread, test does not fail if timeout is reached

## Steps to Reproduce (for bugs)

The following test fails with a timeout error:

```
varnishtest

server s1 {
} -start

varnish v1 -vcl+backend {
} -start

logexpect l1 -v v1 -g raw {
	expect * *	ExpKill		anything
} -start

logexpect l1 -wait
```

whereas this one succeeds:

```
varnishtest

server s1 {
} -start

varnish v1 -vcl+backend {
} -start

logexpect l1 -v v1 -g raw -T5 {
	expect * *	ExpKill		anything
} -start

logexpect l1 -wait
```

## Context

While writing a test to assert that correct log entries are written, I wanted to convince myself that the test was valid by adding assertions that would never be true. However, the test either timed out after 60s (with no `-T`) or passed (with `-T`).

## Your Environment
* Version used: 6.0.6
* Operating System and version: Ubuntu 18.04
* Source of binary packages used: packagecloud.io

**Comment by bsdphk** [comment]
The docs describe -T as:

   -T <seconds>
           Transaction end timeout

And r01762.vtc uses -T this way.

That's not to say that being able to set a non-match timeout for logexpect wouldn't be nice, rather than having to rely on the total-vtc timeout.

**Comment by Dridi** [comment]
I think we'd need something like this for a negative match:

```
logexpect l1 ... -err {
    expect ...
} -start
```

You wouldn't `-wait` for `l1` and instead it would trigger a failure upon completing its spec.

**Comment by nigoroll** [comment]
briefly discussed with @Dridi : I think I could have implemented https://github.com/varnishcache/varnish-cache/issues/3249#issuecomment-735702210 straight away, but he seems to have better ideas now.

**Comment by Dridi** [comment]
Now that we have a '?' skip marker and considering the way @nigoroll refactored the `logexpect` code to introduce it, I think we can reuse this syntax and logic for negative matches:

```
logexpect l1 -err ... {
    expect ? <vxid> <tag> <regex>
    ...
} -start
```

In `-err` mode only the '?' marker makes sense: the current "undefined match order" of normal mode would translate to "any match".

I would also use `l1 -wait` to explicitly break out of `l1`'s dispatch loop in `-err` mode.

Thoughts?

**Comment by nigoroll** [comment]
This makes perfect sense and is exactly what I would have thought except for the good idea to have `-wait` _stop_ the `-err` logexept

**Comment by nigoroll** [comment]
@Dridi pondering this has kept mind busy whenever it had no higher priority task scheduled. (if @mbgrydeland has time, I would also value his feedback)

I see an issue with the idea we followed above: You might need to start a negative logexpect only after some point and you might also need to stop it at another. Thus, negating all of the logexpect seems to not be advisable and I would rather go for negation of individual expects, again reusing the _skip_ column.

I think this could look similar to this:

```
logexpect l1 ... {
    expect - <vxid> <tag> <regex must not match>
    expect - <vxid> <tag> <regex must not match>
    expect 5 <vxid> <tag> <regex must match within 5 lines> # as before
    expect * <vxid> <tag> <regex must match eventually, negative matches stil in place>
    expect ! # clear negative matches
    expect - <vxid> <tag> <new regex which must not match>
    expect * <vxid> <tag> <regex must match eventually>
    ...
} -start
```

To explain the idea in words:
When we encounter an `expect -`, we put it onto a separate list of negative matches, which we evaluate for every VSL line. This does not affect how the existing positive matches work, so _skip_ and `?` keep their semantics, the next expect still has to be seen within the given max number of lines.
When we encounter an `expect !`, we clear the list of negative matches.

One thing which I would actually like to drop is the idea of negative matches at the tail of a logexpect with `-wait` ending it despite the end of the VSL query not having been reached. For one, this would complicate the implementation I have in mind and I think it would also not make that much sense: In my mind, there should always exist some condition determining when we can stop looking for negative matches, either some explicit tag, or the end of transaction.

That said, what I think _should_ work is

```
logexpect l1 -v v1 -g vxid -q "vxid == 1001" {
   expect - * Error "out of workspace"
   expect - * VCL_Error "Workspace overflow"
} -start
logexpect l1 -wait
```

The logexpect would finish successfully when the VSL transaction ends and none of the negative expects has been seen.
Implementation wise, we would not stop matching after the last expect if we still have negative matches active.

What do you think?

**Comment by nigoroll** [comment]
Oh and @dbevacqua I did not mean to exclude you from the discussion. I think this suggestion would also satisfy your requirement, but your feedback sure is welcome too.

**Comment by Dridi** [comment]
I think at this point we might as well have different commands than `expect` in the logexpect spec.

- `expect - ...` => `fail -add ...`
- `expect !` => `fail -clear`

That kind of paint, no obvious color on my end.

**Comment by nigoroll** [comment]
yeah I think I'll try
```
fail add <vxid> <tag> <regex>
fail clear
```
