### ISSUE TITLE
RFC: log implicitly filtered headers

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3260]
working on #3102 I noticed some issues with our built-in header filtering (PRs coming up).
Pondering these, I noticed that we do not log when we do not copy a header from one context to another due to
* explicit filtering based upon the specs in https://github.com/varnishcache/varnish-cache/blob/master/include/tbl/http_headers.h or
* it being marked hop-by-hop in the `Connection` header.

I think we definitely need to log implicitly filtered headers for POLArity.

My question is:
* Do we want a separate VSL tag, e.g. `(Req|Bereq|Resp|Beresp)Filter` or
* do we simply use `(Req|Bereq|Resp|Beresp)Unset` ?

I had a quick look into the first option and, for my first trivial approach at least, it would move most VSL tags and thus cause VSL binary compatibility broken. But if the vote was for `Unset` anyway, we could avoid even having to worry about this issue.

**Comment by Dridi** [comment]
For me it's `*Unset` or, in the spirit of `LostHeader` a separate `FilteredHeader` (but not a new one per type of HTTP message).

**Comment by nigoroll** [comment]
bugwash: logging not considered required.
