### ISSUE TITLE
reminder: change vcc_acl_pedantic default to on

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3269]
from #3157 : switch to on after June 1st

**Comment by bsdphk** [comment]
I tried setting this `true` by default and that revealed a number of VTC's which require it set `false` to work.

I'm still a bit worried about us making the pattern `thishost.example.com/24` fail, I have seen it in many VCL's over the years.

I agree that the `$ipv6/24` is a nasty surprise, so I was wondering if it would be better to augment the ACL syntax instead, for instance by using a double // to indicate that non-zero hostpart is intended:

    thishost.example.com/24    -> fails with VCC error

    thishost.example.com//24   -> works.

Also, this is the fourth stand-alone boolean `vcc_something` flag, maybe we should collect them under a `feature_vcc` (`feature_vcl`) flag ?

**Comment by bsdphk** [comment]
The tests which fail with default true are c00005, m00023 and r01312

**Comment by nigoroll** [comment]
While I like the idea to allow non-zero host-parts explicitly per ACL entry, I do not see any demand for something like this in my world.
+1 on `feature_vcc` !

**Comment by Dridi** [comment]
>  +1 on `feature_vcc` !

I'm also in favor, but I would simply go for `vcl` or `vcc` for the parameter name.

**Comment by Dridi** [comment]
I know this is off topic regarding the pedantic acl flag but another boolean switch that has come up more than once would be to enable experimental VCL features. Something we can ship without locking ourselves.

**Comment by bsdphk** [comment]
Bugwash consensus:

// syntax could be OK, but might be overkill.

vcc_feature param is go.

**Comment by bsdphk** [comment]
Looked at the // syntax, and it is a no go, because we allow the / both inside and outside the string, and outside the string // is a comment.

**Comment by Dridi** [comment]
Off topic, but somewhat related, so I'll register the question here:

Should we also fold `http_gzip_support` and `http_range_support` into the `feature` parameter?
