### ISSUE TITLE
varnishtest/process/kill(SIGKILL)

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#3272]
The issue troubling test r02990 currently.

**Comment by benatto** [comment]
Hello,

I sent pull request #3291 which at least locally solved the issue with r02990 under stress testing.

**Comment by nigoroll** [comment]
#3291 looked innocent enough to give it a try. Let's see if that changes vtest

**Comment by benatto** [comment]
@nigoroll I have discussed this with @Dridi this afternoon. I think it's just a matter of pX -expect-text being offscale regarding time units with vX -expect. I run a few tests locally, got one fail using -n 2000 -j 50 which I could not reproduce anymore.

**Comment by nigoroll** [comment]
@benatto I understand what you are saying and the change makes sense. Yet still we need to see if http://varnish-cache.org/vtest/ _actually_ shows less r02990 errors

**Comment by benatto** [comment]
@nigoroll sure. I'll check the results later.

**Comment by nigoroll** [comment]
vtest is looking good.
@bsdphk it is not clear to me if you had anything else in mind for this issue. Can we close it or do you have anything left to do?

**Comment by bsdphk** [comment]
Nothing to add.
