### ISSUE TITLE
VUT `-b` and `-c` flags should only affect output, not input to vslq

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3293]
@uplexPaul noticed that the `-b` and `-c` flags of VUTs (here: `varnishlog`) may be un-pola: He would expect them to be applied on the query result, yet we use them as part of the query.
The case at hand was with `-g request` and a query selecting the transaction by client criteria. With `-b` applied, they would never match, and the expectation was that `-b` would show the backend side of the selected transactions.

Should we change this?

**Comment by Dridi** [comment]
I personally never felt the unpolaness in this area (and I had to transition from v3 to v4 logs) and it seems to me that the documentation makes it clear that it's an output tweak:

> Only display transactions and log records coming from (client|backend) communication.

If that's ambiguous, I would rather improve the manuals. We already have similar non obvious interactions between querying, grouping and displaying (like `varnishlog -i`).

That doesn't mean that I'm against extending the VSL query language:

https://varnish-cache.org/lists/pipermail/varnish-dev/2018-May/009251.html
https://varnish-cache.org/lists/pipermail/varnish-dev/2019-September/009464.html
https://github.com/varnishcache/varnish-cache/pull/2199
https://github.com/varnishcache/varnish-cache/pull/2872

What you are suggesting could materialize as `-q '@client <expr>'` following my email from 2018.

**Comment by nigoroll** [comment]
bugwash: We agree that behavior should be as expected by @uplexPaul : `-b` / `-c` should have effect at print time and not limit which records are fed to the query.
I will look into it and fix or PR.

**Comment by nigoroll** [comment]
I guess it makes sense to repurpose this ticket for what we now agreed is a bug.

**Comment by nigoroll** [comment]
My apologies. This turned out to be a non-issue and a layer 8 error.
Thank you to everyone involved, if anything we clarified how things should be.
