### ISSUE TITLE
Aarch64 Compatible varnish APK

### ISSUE THREAD

**Issue by odidev** [varnishcache/varnish-cache#3295]
Hi Team,

I am not able to find apk for aarch64 in its release. Is there any plan to release aarch64 compatible varnish apk.

**Comment by martin-g** [comment]
Hi,

See https://github.com/varnishcache/varnish-cache/pull/3263.
This PR adds aarch64 packages for CentOS 7/8, Ubuntu 16.04/18.04, Debian 8/9/10 and Alpine 3.
Feedback is very welcome!

**Comment by nigoroll** [comment]
FTR: We do not use github issues for support. Please see here: https://varnish-cache.org/support/index.html
