### ISSUE TITLE
Connection to admin-healthy backend with sick probe fails

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3299]
found by @uplexPaul: 
Forcing a backend with a failing probe to be healthy using `varnishadm backend.set_health ... healthy` does not work as expected, trying to connect to it still fails with `FetchError      b backend ...: unhealthy`
Logging issue for completeness, fix is on the way.

**Comment by nigoroll** [comment]
FTR I checked if this is a regression from b16a9d9a8d000a0c9fcac2245ec0e6e0bd5cbecb, but it is not, the vtc to be committed already fails for the commit before, 6ab26126194fc81017c1847925b7ea4fc2b10969

**Comment by rezan** [comment]
Just want to comment that this does **not** affect 6.0.

**Comment by nigoroll** [comment]
you are right @rezan , sorry for the wrong label.
Actually from a quick look it seems this was originally introduced with 401d1dd92aec97e9a41733549442737100375266
