### ISSUE TITLE
vcl_.CflagTest directories are not deleted after varnishd -C

### ISSUE THREAD

**Issue by mouchar** [varnishcache/varnish-cache#3307]
When I run `varnishd -C -f some.vcl` as root user, temporary directory created to compile vgc library is not removed. It looks like a regression of very old bug #1869

## Expected Behavior
Temporary files and directories are removed when  `varnishd -C -f some.vcl` terminates.

## Current Behavior
Running strace on the process, it shows EPERM error caused by improper UID/GID juggling.
See the following snippet (note that my varnish user has uid=986 and gid-989):
```
// varnishd -C -f default.vcl
geteuid()                               = 0
getgid()                                = 0
setresgid(-1, 986, -1)                  = 0
setresuid(-1, 989, -1)                  = 0
setresuid(-1, 0, -1)                    = 0
mkdir("/var/lib/varnish/myinstance/", 0755) = -1 EEXIST (File exists)
setresuid(-1, 989, -1)                  = 0
setresuid(-1, 0, -1)                    = 0
setresgid(-1, 0, -1)                    = 0
unlink("_.testfile")                    = 0
setresgid(-1, 986, -1)                  = 0
setresuid(-1, 989, -1)                  = 0
setresuid(-1, 0, -1)                    = 0
mkdir("vmod_cache", 0755)               = -1 EEXIST (File exists)
setresuid(-1, 989, -1)                  = 0
setresuid(-1, 0, -1)                    = 0
setresgid(-1, 0, -1)                    = 0
setresgid(-1, 986, -1)                  = 0
setresuid(-1, 989, -1)                  = 0
setresuid(-1, 0, -1)                    = 0
mkdir("vcl_.CflagTest.13585.1588609245.292533", 0755) = 0
setresuid(-1, 989, -1)                  = 0
geteuid()                               = 989
geteuid()                               = 989
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=13586, si_uid=989, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=13587, si_uid=989, si_status=0, si_utime=0, si_stime=0} ---
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=13592, si_uid=989, si_status=0, si_utime=0, si_stime=0} ---
unlink("vcl_.CflagTest.13585.1588609245.292533/vgc.c") = 0
unlink("vcl_.CflagTest.13585.1588609245.292533/vgc.sym") = 0
unlink("vcl_.CflagTest.13585.1588609245.292533/vgc.so") = 0
rmdir("vcl_.CflagTest.13585.1588609245.292533") = -1 EACCES (Permission denied)
+++ exited with 0 +++
```
EPERM is caused by rmdir attempt to modify directory `/var/lib/varnish/myinstance`:
```
drwxr-xr-x. 11 root varnish 4096 May  3 23:05 /var/lib/varnish/myinstance
```
Temporary directory is created with euid=0, but removed with euid=989.
 
## Possible Solution
Set uid to 0 right before cleanup, or create `/var/lib/varnish/myinstance/` directory with `0775` permissions (not recommended).

## Steps to Reproduce (for bugs)
Steps used to run strace:
```
$ sudo strace -s1000 -o /tmp/output.strace  \
  -e setresuid,setresgid,mkdir,rmdir,unlink,geteuid,getuid,getegid,getgid \
  /usr/sbin/varnishd -C -f default.vcl 2> /dev/null
$ ls -al /var/lib/varnish/myinstance/
total 16
drwxr-xr-x. 4 root    varnish 4096 May  4 18:20 .
drwxr-xr-x. 4 root    root    4096 May  4 17:52 ..
-rw-r--r--. 1 root    root       0 May  4 18:20 _.pid
drwxr-xr-x. 2 varnish varnish 4096 May  4 18:20 vcl_.CflagTest.13585.1588609245.292533
drwxr-xr-x. 2 varnish varnish 4096 May  4 18:12 vmod_cache
```
Check the `/tmp/output.strace` file contents.

## Context
I used this command on an older VC version to verify VCL validity before trying to load it to running instance. With new versions, it's not possible anyway because I cannot run `varnishd -C` when the varnishd instance is already running (by the way, is it desired behavior?).

## Your Environment
```
varnishd (varnish-6.4.0 revision 13f137934ec1cf14af66baf7896311115ee35598)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2020 Varnish Software AS
```
OS: CentOS 7.7 x64
Custom built RPM using your SPEC file.

**Comment by nigoroll** [comment]
possibly related to #3243

**Comment by bsdphk** [comment]
I think -C should not leave behind anything.

**Comment by Dridi** [comment]
> I think -C should not leave behind anything.

We have the `vcl_keep` debug flag if people want to leave `-C` droppings behind.

**Comment by bsdphk** [comment]
Bugwash consensus:  -C leaves nothing nehind unless told to with vcl_keep.

Now somebody needs to find and fix the bug.
