### ISSUE TITLE
building html/man broken for out-of-tree build

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3309]
I tried to get back to clean out-of-tree builds and noticed that they got broken since I last had a go.

To illustrate:
```
cd $SRCDIR
make maintainer-clean || true
./autogen.sh

cd $TMPDIR
$SRCDIR/configure
make
make html
```

* `make` fails while building man pages (`$SRCDIR` substituted)

```
make[2]: *** No rule to make target '$SRCDIR/doc/sphinx/include/cli.rst', needed by 'varnish-cli.7'.  Stop.
```

* `make html`:

```
sphinx-build -W -q -N -b html -d ./build/doctrees -D latex_elements.papersize=a4  $SRCDIR/doc/sphinx ./build/html
Error: Config directory doesn't contain a conf.py file.
Makefile:579: recipe for target 'html' failed
make[2]: *** [html] Error 1
```

The root cause is that we build some of the documentation source files while we provide others as manually written sources and the tools we use do not (as far as I know) offer an _include path_.

I had originally addressed this issue by copying the source files to the build dir, such that the doc tools can run only on the build dir. Some of the more relevant commits are 5822d0ce45b99e03ee2e611c5ef0d74bfc6a585d and 531ecb40733d3df41007784d7039f0fe9adb0150

This method did work with the disadvantage of not picking up changes to the hand written source files immediately.

subsequent commits, for example 883fddfea4e185ff417762fb64207b81d4cea971, broke this method, so now out-of-tree builds do not work any more.

Questions:
* Does anyone but me care about out-of-tree builds?
* If yes, are there any good ideas how to solve this?

I would suggest do either go back to the method from 5822d0ce45b99e03ee2e611c5ef0d74bfc6a585d (copy rst files from `$(srcdir)` to `$(builddir)`) or use the same idea but with symlinks, which should also make incremental rebuilds work for source file changes.

Thoughts?

**Comment by bsdphk** [comment]
Have you looked in the sphinx documentation to see if there is any help there ?

**Comment by nigoroll** [comment]
I have checked the `sphinx-build` and `rst2man` man pages and went over the search results for [include](https://www.sphinx-doc.org/en/stable/search.html?q=include) and [path](https://www.sphinx-doc.org/en/stable/search.html?q=path), but did not spot anything which looked like it could help.

**Comment by Dridi** [comment]
Definitive answer: https://github.com/sphinx-doc/sphinx/issues/5491

We need to copy all the sources somewhere in `$(builddir)`.

**Comment by nigoroll** [comment]
Thank you, @Dridi . I have taken this as a valid reason to merge the symlink-fix, but will be happy to discuss if copies would be better.

**Comment by Dridi** [comment]
Unfortunately that wasn't an endorsement of your PR ;-)

Reopening and assigning to myself, I'd like to contain the entropy that accumulated in our documentation generation.

**Comment by nigoroll** [comment]
notes from bugwash: `cpio` would need to be added to the build requirements, but @Dridi prefers to change the implementation instead, so we want to keep the ticket to track.

**Comment by Dridi** [comment]
I'm leaving this as-is, feel free to updates the docs accordingly.
