### ISSUE TITLE
VBE.*.conn not working as expected

### ISSUE THREAD

**Issue by ernestojpg** [varnishcache/varnish-cache#3312]
## Expected Behavior

If I understood correctly the documentation, **VBE.*.conn** is a gauge that represents the number of concurrent or stablished connections to a specific backend at that moment.

If that is true, the value in that counter should be the same as the number of stablished connections in the system to that specific backend when doing something like: `netstat -nat | grep <IP_Backend> | grep ESTABLISHED`

## Current Behavior

Currently the value represented in that counter is always much less than the number of real stablished connections to that backend server. For example, the counter was showing 0 when I had 12 stablished connections to that backend server.

Maybe I'm not understanding the meaning of the counter?

## Steps to Reproduce

Just compare the value of the counter with the value returned by `netstat -nat | grep <IP_Backend> | grep ESTABLISHED | wc -l`

## Your Environment

- varnish-6.4.0
- CentOS Linux release 7.7.1908

**Comment by nigoroll** [comment]
@ernestojpg thank you for pointing out that connection pooling was not documented. I have not written a first take on explaining it and would appreciate your feedback if your questions are being answered. If not, please let me know and I will try to further improve the documentation.

**Comment by ernestojpg** [comment]
Hi @nigoroll , thank you for updating the documentation. Now the meaning of the counter is clear to me.

Don't you think that Varnish should provide some kind of counter/gauge to expose the current number of stablished connections to a specific backend? It is a quite basic and useful information to expose in a reverse-proxy. Without that information we cannot monitor is for example we are hitting the max limit of connections for that backend.

What do you think?

**Comment by nigoroll** [comment]
response in #3314

**Comment by ernestojpg** [comment]
Thanks @nigoroll
