### ISSUE TITLE
RFC: VSCs for connection pools? backend_busy per backend?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3314]
@ernestojpg writes in #3312 

> Don't you think that Varnish should provide some kind of counter/gauge to expose the current number of stablished connections to a specific backend? It is a quite basic and useful information to expose in a reverse-proxy. Without that information we cannot monitor if, for example, we are hitting the max limit of connections for that backend.

Yes, I think we should have something like that and actually when I implemented the code to address #2622, IIUC, I actually did initially propose to add counters at the pool level. But at the time, it was decided to have them at the backend level for simplicity.

So, if we actually wanted to keep track of the pool size, it would make more sense to move the error counters back from backends to the pool.

Regarding the `max_connections` limit, that actually _is_ per backend and checked against the `conn` counter per backend. I guess one could argue against this decision, but the killer argument for having the check per backend is that this allows to change it with a VCL reload, while, as long as we want pools to be shared across VCLs, changing pool limits would require an abstraction which we do not have.

Right now, you can at least monitor the global counter `backend_busy` to check if you hit `max_connections` anywhere and extract `FetchError` `backend %s: busy` (with `%s` being the backend name) from the log. I agree that having a counter per backend would make sense.

**Comment by bsdphk** [comment]
Bugwash conclusion:  Not actionable, but improvement certainly desired.

Move to VIP.

**Comment by nigoroll** [comment]
Added a [bare minimum VIP](https://github.com/varnishcache/varnish-cache/wiki/VIP33:-Connection-Pool-Statistics)
