### ISSUE TITLE
haproxy to varnish 6.4 acl always returns false on client.ip

### ISSUE THREAD

**Issue by bfis108137** [varnishcache/varnish-cache#3334]
## Expected Behavior
I would expect that it would return true if the ip is in the acl

## Current Behavior
If the request comes from haproxy, it should be true if client.ip is in the acl.  When the ip comes from a direct request (without haproxy) it is fine.  If we take the ip as a string and do std.ip("some ip", client.ip, false), then that works.  If we save client.ip to a header and then do std.ip, that also works.

## Steps to Reproduce (for bugs)
1. Setup haproxy to forward to varnish 6.4
2. Create an acl (call it some_acl) with your ip 
3. do if(client.ip !~ some_acl){std.syslog(0,"ip not in acl")}
4. You will see "ip not in acl in syslog"

## Context
We are not able to restrict based on ip.  It has caused a lot of internal requests to be blocked.  Note that our setup is according to https://info.varnish-software.com/blog/failure-to-purge-a-story-about-client.ip-and-proxies and it worked before we upgraded from 6.1 to 6.4.

## Your Environment
Varnish 6.4 from http://packagecloud.io/
Debian 10
Proxy Protocol v2

**Comment by nigoroll** [comment]
I do not think this is a bug. Please refer to [some other support channel](https://varnish-cache.org/support/index.html). If you disagree and still think you have found a bug, please add full information on how to reproduce it: Your haproxy config, your VCL and the exact steps how to reproduce. The "Steps to Reproduce" you have filled out are, unfortunately, not sufficient.

Hint: [RTFM](https://varnish-cache.org/docs/trunk/reference/vcl.html#local-server-remote-and-client) and `send-proxy` or `send-proxy-v2` in haproxy

**Comment by bfis108137** [comment]
Our haproxy is configured like you said in the next line

server localhost 127.0.0.1:94 send-proxy-v2  maxconn 99999

our vcl has internal information and is comprised of ~ 10 files but I will make some close copies of what's going on.  

If you run this code and your ip is 98.76.54.32, you will see "ip not good normal way" in the log but not "ip  not good by hack with str and std.ip".  

Again, the ip does appear in varnish but there is some issue when comparing it.

sub vcl_recv {
```
acl goodIps {
 "10.0.0.0"/24;
 "98.76.54.32";
}

if(client.ip !~ goodIps){
   std.syslog(0,"ip not good normal way");
}

set req.http.ip_str = client.ip;
if(std.ip(req.http.ip_str, client.ip, false) !~ goodIps){
   std.syslog(0,"ip  not good by hack with str and std.ip");
}

}
```

**Comment by nigoroll** [comment]
ok, I get you now. That would indeed be a bug.

**Comment by nigoroll** [comment]
I have pushed tests cases for this specific scenario and cannot reproduce the issue.
@bfis108137 please send the output of `varnishlog` for a client request showing your case.

**Comment by nigoroll** [comment]
FTR, I have also re-run the tests with 6.4.0 release 13f137934ec1cf14af66baf7896311115ee35598 and b3ec626b975152b607d85d58d1790d3c064436ae cherry-picked on top

**Comment by nigoroll** [comment]
@bfis108137 and please make sure that your log excerpt contains the information from the session, `SessOpen` and `Proxy` in particular.

**Comment by nigoroll** [comment]
@bfis108137 do you still think this is a bug?

**Comment by bfis108137** [comment]
I honestly don't know now. I need to try and reproduce it locally. The information I have provided is from the manager of the system. We sort of piggyback on it. Anyways my setup for development doesn't have haproxy so I need to set this up. You can close it if you want and if I am able to reproduce the bug then I will reopen it.

**Comment by nigoroll** [comment]
@bfis108137 yes please, thank you.
