### ISSUE TITLE
RFC: add bereq.filters

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3336]
See https://github.com/varnishcache/varnish-cache/wiki/VIP-30:-bereq.body_filters

This ticket is to ask for feedback on this proposal

**Comment by bsdphk** [comment]
I think this makes a lot of sense.

Not sure I any reason for the name needs to be different from the other `*.filters` ?

**Comment by Dridi** [comment]
It would be nice to see more VCL control over `bereq` filters, something like `bereq.do_g[un]zip`.

**Comment by nigoroll** [comment]
Re @bsdphk if the argument that this could avoid confusion is not convincing, I agree that the name could just be `bereq.filters`
Re @Dridi yes we can have switches to control the default `bereq.filters`, but that is the second step.

**Comment by bsdphk** [comment]
bugwash: `bereq.filters` it is.
