### ISSUE TITLE
std.rollback(bereq) and HttpGarbage

### ISSUE THREAD

**Issue by rezan** [varnishcache/varnish-cache#3353]
I have backported the various rollback() fixes and I am running into an HttpGarbage situation. The weird thing is that I cannot reproduce in a VTC. The root of the problem is we are not setting `bo->htc->doclose`, the connection is recycled, and then we re-read the body as the next requests headers.

I will try and explain what I am seeing in the logs:

```
--  BackendOpen    31 boot.default 127.0.0.1 8008 127.0.0.1 33944

--  VCL_call       BACKEND_RESPONSE

--  BackendReuse   31 boot.default

--  FetchError     No backend connection (rollback?)

--  VCL_call       BACKEND_ERROR
--  VCL_return     retry

--- BackendOpen    31 boot.default 127.0.0.1 8008 127.0.0.1 33944
--- HttpGarbage    "%0d7%c4%eb%e3%b7%d5%eb%c6%f7%e8%8d%14z%fc%f0%e3bv%ccS%d7%c9%db%02h%f1%1a6%98%db`e%d4%0a+h%89%0eD%09a%e1z7%f4V%d5%0f8Le%b81%ac%af%07%04S%ae%eb%1a%b7%0e%d5C%83g%b4%06%d8%d2%88%b8%f2%f7Q%0f%e3lQ%08%f3&0Q%0c%b5`%f1;%cf%90U9/"%c7%e9%87%b8%82%b8n^%c6%89b%88X%ef%ac%10%10%1c%f2%0b3%0aOZ%16%1a%f7F%89%87%15%9a%f4%a7^%9a%f4%ee%84o[%e9?)%c5%ee%f3%95%e3u%c5%80%de%99%d1%ef%90%e0%e5%fd%9fFX%0a%a0%88%91%00"
```

Open a connect to the backend (`33944`), call `std.rollback(bereq)`, note that we get a `BackendReuse` log line. The fetch fails because we have no htc anymore, jump to `vcl_backend_error`, return `retry`, then we get the same connection (`33944`), then `HttpGarbage`.

The fix is straight forward, just set `htc->doclose` to `SC_RX_BODY` if we have started reading the response in the rollback(). However, not being able to replicate this in a vtc has me scratching my head.

**Comment by rezan** [comment]
I did get a reproducer vtc, you need a slight delay after sending the headers to make sure the body is read into the next request:

``` vcl
varnishtest "Test rollback and retry"

server s1 {
	rxreq
	txresp -nolen -hdr "Content-Length: 3"
	delay 0.1
	send "xxx"

	rxreq
	txresp -body xxx
} -start

varnish v1 -vcl+backend {
	import std;

	sub vcl_backend_response {
		if (bereq.retries == 0) {
			std.rollback(bereq);
		}
	}

	sub vcl_backend_error {
		if (bereq.retries == 0) {
			return (retry);
		}
	}
} -start

client c1 {
	txreq
	rxresp
	expect resp.status == 200
} -run
```

You get:

```
**** v1   vsl|       1002 BackendReuse    b 25 s1
**** v1   vsl|       1002 VCL_return      b deliver
**** v1   vsl|       1002 FetchError      b No backend connection (rollback?)
...
**** v1   vsl|       1003 HttpGarbage     b xxxHTTP/1.1
**** v1   vsl|       1003 BerespStatus    b 503
**** v1   vsl|       1003 BerespReason    b Service Unavailable
**** v1   vsl|       1003 FetchError      b http format error
```

I was able to replicate this on `master` too.

**Comment by nigoroll** [comment]
7d25b83b855e650dde9aa5af59d52a4f0be302e2 has some background about the complication. I am looking at your suggested fix

**Comment by nigoroll** [comment]
I guess this fix is close to what you envisioned, but I went for `SC_RESP_CLOSE` because the close comes from VCL, not from an actual error.

**Comment by rezan** [comment]
Looks good, will continue testing and get back to you.
