### ISSUE TITLE
no Backend Counters beresp_bodybytes in varnishstat if option set beresp.do_gzip = true;

### ISSUE THREAD

**Issue by ajoffre** [varnishcache/varnish-cache#3354]
## Current Behavior

if i use the option "set beresp.do_gzip = true;" in "vcl_backend_response", I no longer have the value of Backend Counters beresp_bodybytes in varnishstat.
```
# with option: varnishstat -1|grep VBE.boot.front_fd.be 
VBE.boot.front_fd.bereq_hdrbytes                         71549599706     51664.65 Request header bytes
VBE.boot.front_fd.bereq_bodybytes                         2573041705      1857.95 Request body bytes
VBE.boot.front_fd.beresp_hdrbytes                        22571311577     16298.33 Response header bytes
VBE.boot.front_fd.beresp_bodybytes                                 0         0.00 Response body bytes
```

## Steps to Reproduce (for bugs)

1.add set beresp.do_gzip = true; in vcl_backend_response
2.request on varnish
3.varnishstat -1|grep VBE.boot.front_fd.be 
4.VBE.boot.front_fd.beresp_bodybytes                                 0         0.00 Response body bytes

## Context

we lost our volume production indicator by data by backend

## Your Environment

* Version used: varnish-6.3.1 revision 6e96ff048692235e64565211a38c41432a26c055
* Operating System and version:ubuntu xenial
* Source of binary packages used (if any)

**Comment by Dridi** [comment]
I can't reproduce this on the master branch:

```
varnishtest "beresp.do_gzip and beresp_bodybytes"

server s1 {
        rxreq
        txresp -bodylen 1000
} -start

varnish v1 -vcl+backend {
        sub vcl_backend_response {
                set beresp.do_gzip = true;
        }
} -start

client c1 {
        txreq
        rxresp
        expect resp.bodylen == 1000
} -run

varnish v1 -expect VBE.vcl1.s1.beresp_bodybytes == 1000
```

However, I get a different failure:

```
---- v1   Not true: VBE.vcl1.s1.beresp_bodybytes (145) == 1000 (1000)
```

It looks like we register the number of body bytes in storage instead of the number of body bytes fetched.

I get the same result with varnish-6.3.1 so we probably need further details to explain how that counter fails to increase at all.

**Comment by ajoffre** [comment]
Thank you for responses,
I reproduce the problem with the following test (add of set beresp.do_esi = true;)
```
varnishtest "beresp.do_gzip and beresp_bodybytes"

server s1 {
        rxreq
        txresp -bodylen 1000
} -start

varnish v1 -vcl+backend {
        sub vcl_backend_response {

                set beresp.do_gzip = true;
                set beresp.do_esi = true;

        }
} -start

client c1 {
        txreq
        rxresp
        expect resp.bodylen == 1000
} -run

varnish v1 -expect VBE.vcl1.s1.beresp_bodybytes == 1000
``` 

result
``` 
----** v1   Not true: VBE.vcl1.s1.beresp_bodybytes (0) == 1000 (1000)
```
