### ISSUE TITLE
What is $ABI vrt, exactly?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3356]
From a VMOD developer perspective, there should be clear and concise documentation about exactly what is allowed for `$ABI vrt`, namely which includes can be used. I guess the main question is really about `cache.h`, is it part of VRT or not? If it is was not, we would have changed the VRT version quite often in the past for no good reason (but we already know that and the decision was made as a safety measure). Also, there will be almost no VMOD which does not make use of the workspace API, so `$ABI vrt` would probably be quite useless for all practical purposes.

Right now, our documentation is either vague or contradictory. Some findings:

* https://github.com/varnishcache/varnish-cache/blob/master/doc/sphinx/reference/vmod.rst

> If it complies to the VRT and only needs to be rebuilt when breaking changes are introduced to the VRT API, use `vrt`.

Yes, but which files constitute that API?

* https://github.com/varnishcache/varnish-cache/blob/master/doc/sphinx/phk/apispaces.rst#vmod-apiabi-levels

good level of detail (namely, includes the actual file names), but out of sync with reality

* https://github.com/varnishcache/varnish-cache/blob/master/include/vrt.h#L122

Might suggest that `cache.h` was part of the ABI

**Comment by Dridi** [comment]
#3355 dupe

**Comment by nigoroll** [comment]
yeah, github had issues, I submitted twice after a 500.
