### ISSUE TITLE
Is there an option to cache external resources in varnish

### ISSUE THREAD

**Issue by erangil** [varnishcache/varnish-cache#3359]
Hi,

I have a varnish server and nginx server each residing on different EC2 instance.
on the nginx server I have a simple html file with a video player and the video source is a full url.

The browser downloads the video directly from the url and doesn't go thru the varnish server.
If I place the movie to be local to the nginx and change the url to be relative then the browser goes thru varnish.

Is there a solution for that or this is the only way that it works?

**Comment by Dridi** [comment]
As stated in the issue template you see when you open a new issue we only allow actionable bug reports. For general questions please seek a different support channel like the misc mailing list.

https://varnish-cache.org/support/
