### ISSUE TITLE
VSM: Could not get hold of varnishd, is it running?

### ISSUE THREAD

**Issue by iammeken** [varnishcache/varnish-cache#3365]
I am running Ubuntu 20.04.

Recently upgrade of bash (apt update && apt upgrade) causes varnishlog/varnishtop/varnishtop not working:
http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 bash amd64 5.0-6ubuntu1.1 

varnishstat
.....
VSM: Could not get hold of varnishd, is it running?

Change to" sudo varnishstat" no use

(but varnish is running)

Tested on Varnish 6.2.1 also 6.4 master.

So it is a bug of Ubuntu or Varnish?

The only fix is to roll back to cancel the upgrade.

Any idea?  Thanks!

**Comment by gquintard** [comment]
from the bug template:

```
<!--- Things to check before you report a bug

    - Is the issue you are seeing clearly an issue in varnish core or
      could it be a support question? We do not use github issues for
      support questions, please refer to
      http://varnish-cache.org/support/index.html when in doubt.
...
```

please send an email to the varnish-misc mailing, with the output of `ps aux | grep varnish`, and we can have a look at this
