### ISSUE TITLE
single byte read in VRND_RandomCrypto()

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3366]
https://github.com/varnishcache/varnish-cache/blob/e0ca9dcca1ddb86f4bae57a2403b5c2b4f65ed2d/lib/libvarnish/vrnd.c#L179

@bsdphk does the single byte read serve any particular purpose?

**Comment by bsdphk** [comment]
It used to:  It allowed other processes a chance to grab entroy so we wouldn't get sequential bytes from a (sub-par) random source.

People I trust on this, say this is no longer necessary on Linux and FreeBSD, but I don't know from which precise versions that hold or what the status is on other kernels.

We use `VRND_RandomCrypto()` very little, so I have seen no reason to optimize this.

I'm open to counter arguments.

**Comment by nigoroll** [comment]
my counter argument is use in a vmod

(and wasn't this a workaround for basically a broken `/dev/urandom` implementation then?)

**Comment by nigoroll** [comment]
bugwash: should be optimized
