### ISSUE TITLE
autocrap-issue: doc/sphinx/include is mode 755

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#3374]
If I `git clone` trunk and run `autogen.des` the `doc/sphinx/include` directory gets created with mode 755 which means I cannot write files into it:

    critter phk> ls -la doc/sphinx/include/ | head
    total 2
    drwxr-xr-x   2 phk  phk   2 Jul 29 21:55 .
    drwxrwxr-x  11 phk  phk  19 Jul 29 21:55 ..

Therefore `make distcheck` fails.

**Comment by bsdphk** [comment]
Finally found out how to reproduce this:

    mkdir /somewhere/empty
    cd /somewhere/empty
    git clone \
        https://github.com/varnishcache/varnish-cache.git \
        varnish-cache

    sed '
    /^submit/a\
            return
    ' varnish-cache/tools/vtest.sh > vtest.sh

    diff -u varnish-cache/tools/vtest.sh vtest.sh || true

    env MAXRUNS=1 sh -x vtest.sh

**Comment by Dridi** [comment]
Unfortunately the reproducer didn't fail on my machine.

**Comment by Dridi** [comment]
It should be fixed by #3443, please reopen if it still happens.
