### ISSUE TITLE
ctx in vcl_pipe mixes req and bo priv pointers

### ISSUE THREAD

**Issue by rezan** [varnishcache/varnish-cache#3385]
So I was hunting a very odd bug when backporting some of the recent shard patches around `vcl_pipe`. This bug seems to effect anything using a dynamic priv pointer in `vcl_pipe`, so I believe its different than (#3329 and #3330).

Basically, when we construct the `ctx` for for `vcl_pipe`, we favor `bo`:

https://github.com/varnishcache/varnish-cache/blob/83ab25a259374194bda0ae222a5484cb1f2091c4/bin/varnishd/cache/cache_vrt_vcl.c#L430-L443

And `ctx->ws` is a `bo` workspace.

Here, when we pull a dynamic priv, we favor `req`:

https://github.com/varnishcache/varnish-cache/blob/83ab25a259374194bda0ae222a5484cb1f2091c4/bin/varnishd/cache/cache_vrt_priv.c#L147-L162

And this line mixes `req` and `bo`:

https://github.com/varnishcache/varnish-cache/blob/83ab25a259374194bda0ae222a5484cb1f2091c4/bin/varnishd/cache/cache_vrt_priv.c#L150-L151

This means that we are going to always put bo workspaced privs on the req priv list.

This has slipped under the radar for a few reasons. The main one being that we dont have enough checks in place when freeing the priv list. We also zero out the workspace when done, which basically masks the problem when we iterate the priv list, as that skips the free and terminates the loop.

Anyway, a few different ways to fix this. I would like to discuss this before making the PR to fix this, so please do not jump out ahead with a fix, thank you :)

**Comment by rezan** [comment]
Problem also exists here in the director resolve function:

https://github.com/varnishcache/varnish-cache/blob/83ab25a259374194bda0ae222a5484cb1f2091c4/bin/varnishd/cache/cache_director.c#L209-L210

**Comment by rezan** [comment]
The fix I had in mind was reversing `bo` and `req` in the ctx init. This would make `ctx->ws` point to `req` and solve a lot of problems, possibly even #3329 and #3330. This works because `req` will never be freed before `bo` when piping.

**Comment by nigoroll** [comment]
IMHO, we need to decide on the [question summarized here](https://github.com/varnishcache/varnish-cache/pull/3330#issuecomment-654346165):

> But still, conceptually, moving pipe mode to the backend side (yet running it in the existing client thread) would seem to make more sense to me.

rezas suggestion points in the opposite direction, to move `ctx->ws` for `vcl_pipe` back to the client side.

**Comment by rezan** [comment]
The candidate 6.0 patch is here: https://github.com/varnishcache/varnish-cache/pull/3386

**Comment by bsdphk** [comment]
Ehh... Where is the trunk parent/analog/version of this and if it has been committed, when was that discussed ?

**Comment by rezan** [comment]
Funny, I was just about to make a master PR for this. This has not been discussed, but I would recommend this gets merged before 6.5.

**Comment by rezan** [comment]
https://github.com/varnishcache/varnish-cache/pull/3408

**Comment by nigoroll** [comment]
master now has #3470 , is this ticket still needed for 6.0?

**Comment by rezan** [comment]
6.0 has been patched, this can close now.
