### ISSUE TITLE
Add proper h2 session close reason

### ISSUE THREAD

**Issue by pbowyer** [varnishcache/varnish-cache#3393]
Currently `SC_RX_JUNK` is used when HTTP/2 sessions are closed, which on `varnishstat` translates to a high value for `MAIN.sess_closed_err`. I discovered this via https://github.com/varnish/hitch/issues/314, while looking to see why I had so many session error closes.

In the [Varnish source code](https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishd/http2/cache_http2_session.c#L433) there's a TODO which says:
```
/* TODO: proper sess close reason */
h2_del_sess(wrk, h2, SC_RX_JUNK);
```
so I guess this is something that is meant to be changed.

**Comment by arnobecksdv** [comment]
Hello,

We encounter an issue on trafic increase event, which seems very similer to this problem.

Here is the timeline:

- We have normally ~1000 req/s, a event cause the traffic to increase to ~1400 req/s with spike at ~2300.
- Varnish is creating new threads to the limit
- threads_limited counter strongly increase
- Varnish don't response to all requests, req/s decrease slowly to 0 (see attachment)
- A restart of Varnish solved the problem, varnish accept all requests.

You can find a param.show here : [varnishadm_param_show_20201029.txt](https://github.com/varnishcache/varnish-cache/files/5459871/varnishadm_20201029.txt)

And a varnishstat when it had problems here : [varnishstat_20201022.txt](https://github.com/varnishcache/varnish-cache/files/5459933/varnishstat_20201022_.txt)

It seems there is a high number of `MAIN.sess_closed_err`.

$ varnishd -V
varnishd (varnish-6.4.0 revision 13f137934ec1cf14af66baf7896311115ee35598)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2020 Varnish Software AS

We use hitch for TLS support:

$ hitch -V
hitch 1.5.2

Is it related ? Is there any solution ?

Best Regards,

**Comment by Dridi** [comment]
FYI the previous message is discussed on the misc mailing list and unrelated to this issue.

**Comment by arnobeck** [comment]
I know @Dridi, it's a colleague of mine on the misc mailing list.
But I thought it could be related.
Thanks (merci)
