### ISSUE TITLE
varnishstat with both -f and curses is weird

### ISSUE THREAD

**Issue by gquintard** [varnishcache/varnish-cache#3394]
This applies to all versions since at least `6.0`. It might just be me being dense, and it might only require a doc fix, but trying to filter out lines from the `curses` output just didn't work.

For example, I wanted to snip the backend counters and went with:

```
varnihstat -1 -f '^VBE.*'
```

And I was greeted by a screen with only four counters, the ones allowlisted here:

```
// bin/varnishstatvarnishstat.c +337
	if (curses) {
		if (has_f) {
			AN(VSC_Arg(vsc, 'f', "MGT.uptime"));
			AN(VSC_Arg(vsc, 'f', "MAIN.uptime"));
			AN(VSC_Arg(vsc, 'f', "MAIN.cache_hit"));
			AN(VSC_Arg(vsc, 'f', "MAIN.cache_miss"));
		}
		do_curses(vd, vsc);
	}
```

so they just filtered everything else when i only wanted to block the `VBE` ones.

In my case, commenting out the four `VSC_Arg` lines produced the right output, but I assume they were placed here for a reason, like always including them by default in case of a positive glob.

**Comment by Dridi** [comment]
Very bad assumption that filtering is necessarily removing counters, good catch!

**Comment by Dridi** [comment]
After a brief look I think we can solve this without too much hassle:

- add a force list in addition to existing include and exclude lists
- teach `VSC_Arg()` to force fields with a `'F'` argument
- do not expose a `-F` option in `varnishstat`

The force list has include-only semantic and obviously takes precedence over the others.

This is back-port friendly, not breaking binary compatibility despite the increased size of `struct vsc`, it's opaque.
