### ISSUE TITLE
client.ip writable?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3406]
In cluster setups, a common basic requirement is to make available the `client.ip` of the "front" server (facing the client) to the "back" server (receiving a request from the "front" server).
This will be set correctly with `PROXY` support enabled on the intra-varnish connection, but `PROXY` backend connections come at a high price: One connection per request. This not only increases the overhead, but also can lead to failing connections because of ephemeral ports being exhausted.
Thus, in real world setups, I thus do not use `PROXY` for  intra-varnish connection and rather use a header to transport `client.ip` to the "back" server, where a [taskvar.ip()](https://code.uplex.de/uplex-varnish/varnish-objvar/blob/master/src/vmod_taskvar.rst) object gets initialized from that header.
This works well, but requires adjustments to VCL, replacing `client.ip` with `client_ip.get()`.
Re-iterating over this question makes me wonder: Should we maybe just make `client.ip` writable?

**Comment by bsdphk** [comment]
I dont see any obvious downsides...

**Comment by nigoroll** [comment]
FTR: This was discussed recently
* _Changing_ the client-ip in place (the session attribute) would be simple and compatible with all existing code using the client ip, but it would change the ip also for other requests on the same session
* @Dridi suggested to override `client.ip` for the client/backend task which is, IMHO, the right approach.
* For the simple cases, implementing this approach is rather trivial (see WIP https://github.com/nigoroll/varnish-cache/commit/1267e929aaf74612ebd3758f2e7a2a05f3883f68). Trouble is that we are using the client ip in many different places via the stringified session attribute. (run a `git grep SA_CLIENT_).
* If we just replaced all of these cases with access to the `client.ip` suckaddr, we would need to stringify multiple times (calling `VTCP_name()`)
* I hope we can avoid this by adding another abstraction on top of `VSA` which caches the `VTCP_name()` result.

**Comment by nigoroll** [comment]
ticket has served its purpose, needs to be implemented.
