### ISSUE TITLE
Varnish 6.5 packages missing

### ISSUE THREAD

**Issue by johanneswuerbach** [varnishcache/varnish-cache#3418]
The new varnish release 6.5 doesn't seem to have any packages available, but it is still the recommended installation method on https://varnish-cache.org/releases/rel6.5.0.html

Compare 
- No packages in 6.5: https://packagecloud.io/varnishcache/varnish65
- Previous 6.4 release: https://packagecloud.io/varnishcache/varnish64

Did the recommended installation change or are package builds just delayed? Sorry if this is already tracked somewhere else, but I couldn't find a related issue here or in https://github.com/varnishcache/pkg-varnish-cache.

**Comment by gquintard** [comment]
they are on their way, just a little patience and they'll be in the repos

**Comment by johanneswuerbach** [comment]
Thanks, now there are packages.
