### ISSUE TITLE
Accounting protocol overhead (#3354 fallout)

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#3425]
Our accounting records are defined according to this pattern:

    SLTM(XXXAcct, 0, "XXX accounting",
            "Contains byte counters from XXX processing.\n\n"
            "The format is::\n\n"
            "\t%d %d %d %d %d %d\n"
            "\t|  |  |  |  |  |\n"
            "\t|  |  |  |  |  +- Total bytes received\n"
            "\t|  |  |  |  +---- Body bytes received\n"
            "\t|  |  |  +------- Header bytes received\n"
            "\t|  |  +---------- Total bytes transmitted\n"
            "\t|  +------------- Body bytes transmitted\n"
            "\t+---------------- Header bytes transmitted\n"
            "\n"
    )

Before the #3354 fix, body bytes included the overhead of chunked encoding.

After the #3354 fix, this is the body-size at the lowest VDP/VFP.

Total bytes is the sum of header+body.

@Dridi raise the question if we should start to account the "overhead".

In H1 overhead is chunked headers, in H2 it is an economy-sized can of worms.

I'm all for striving for perfection, but in this case I think it would be pointless perfection.

Keeping track of the overhead requires a VSC counter to hold it.

Opinions ?

Total = header + body

or 

Total = header + body + overhead

**Comment by Dridi** [comment]
I would count any kind of text framing as protocol overhead in h1, so not just chunked but also CRLF and SP separators before the body payload.

My 2 pedantic cents

**Comment by bsdphk** [comment]
Discussed on IRC with @nigoroll:  It would be hard and expensive to correctly and precisely account for and allocate H2 and H3 overheads, and the net utility to users if we did seems very questionable.
