### ISSUE TITLE
Very high VUT clients fstat overhead after USR1/HUP is received

### ISSUE THREAD

**Issue by ema** [varnishcache/varnish-cache#3436]
VUT clients such as varnishncsa perform poorly after receiving signals like USR1/HUP when Varnish is under load due to very frequent `fstatat` calls. This is the same issue as #2788, with the twist that it shows up only after the VUT client receives a signal.

## Expected Behavior

Sending signals such as USR1 and HUP to VUT clients should not negatively affect performance.

## Possible Solution
The mitigation for #2788 involved the following do-while loop:
```
do
    i = VSLQ_Dispatch(vut->vslq, vut_dispatch, vut);
while (i == vsl_more && !vut->sighup && !vut->sigusr1);
```

After commit 55995ab the code now looks like this:

```
do
    i = VSLQ_Dispatch(vut->vslq, vut_dispatch, vut);
while (i == vsl_more && !VSIG_hup && !VSIG_usr1);
```

To the best of my understanding, `VSIG_hup` and `VSIG_usr1` are global counters that are incremented in `VUT_Signaled` and are never set back to 0. Once the first HUP or USR1 signal is received, the do-while loop gets executed only once for each iteration of the outer while loop, making the mitigation ineffective. A possible solution would be setting VSIG_hup/VSIG_usr1 back to 0 in the signal handler.

## Steps to Reproduce (for bugs)

Have a varnish daemon listening on port 80:

```
sudo varnishd -F -b localhost:8080
```
Generate some load with a HTTP benchmarking tool such as [hey](https://github.com/rakyll/hey) and count the number of `fstat` calls executed by `varnishncsa` in 10 seconds:

```
hey -n 1000000 http://localhost > /dev/null &
sudo timeout 10 strace varnishncsa 2>&1 | grep -c fstat
149
```

This time, also send USR1 to varnishncsa:

```
hey -n 1000000 http://localhost > /dev/null &
sudo timeout 10 strace varnishncsa 2>&1 | grep -c fstat & sleep 1 ; sudo kill -USR1 `pidof varnishncsa`
17334
```

## Context

See https://phabricator.wikimedia.org/T264074. Our production environment uses Varnish 6.0.6 LTS, and the issue is subtly different there. This github issue affects 6.5.1 and master.

## Your Environment

* Version used: Varnish 6.5.1
* Operating System and version: Debian buster
* Source of binary packages used (if any) 6.5.1~buster-1 from packagecloud.io

**Comment by nigoroll** [comment]
thank you for this very good bug report.
I can reproduce the issue, `strace -c` shows for the `USR1` signal case:
```
strace: Process 18447 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 42.32    0.001014           0    120435           newfstatat
 33.18    0.000795           0     90342           fstat
 12.98    0.000311           0     60230           read
 11.52    0.000276           0     60220           lseek
```
I will suggest a patch for master
