### ISSUE TITLE
6.0.6 LTS: high VUT fstat overhead if sighup_f is not defined

### ISSUE THREAD

**Issue by ema** [varnishcache/varnish-cache#3437]
This is very similar to #3436, but affecting the LTS branch. The [do-while mitigation](https://github.com/varnishcache/varnish-cache/blob/b10f51e5ce09004cbf3b859c4dcd90fa8bf61d62/lib/libvarnishapi/vut.c#L423) for #2788 looks like this:

```
do
    i = VSLQ_Dispatch(vut->vslq, vut_dispatch, vut);
while (i == vsl_more && !vut->sighup && !vut->sigusr1);
```
The sighup callback is called [at the beginning of the while loop](https://github.com/varnishcache/varnish-cache/blob/b10f51e5ce09004cbf3b859c4dcd90fa8bf61d62/lib/libvarnishapi/vut.c#L367), and `vut->sighup` is set back to 0:

```
if (vut->sighup && vut->sighup_f) {
    /* sighup callback */
    vut->sighup = 0;
    i = vut->sighup_f(vut);
```

If the client using VUT does not define `vut->sighup_f`, the branch is never taken, `vut->sighup` is never set back to 0, and the same behavior described in #3436 can be observed whenever a HUP signal is received.

**Comment by mbgrydeland** [comment]
Merged into the 6.0-LTS branch, fix in next release.
