### ISSUE TITLE
RFC: should probes be stopped when the admin health state is not "auto"?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3446]
I came across this question in a specific client station where the varnish probe was preventing an application from starting up:
Should we actually run probes if the admin health (as set with `varnishadm backend $name set_health`) is different from `auto`?

**Comment by nigoroll** [comment]
good feedback on irc:
(18:00:57) simon: slink: i vote very much no, its awesome to be able to see backend probes state in these cases. We've mostly used healthy to avoid removing backend when for example storage is performing horrible and then its nice to see what varnish thinks about them during that period
(18:01:55) xavierg: slink: I can imagine a sysadmin setting the health state precisely to disable health probes for some reason (e.g. too many probes for a puny backend?); and at the same time, I believe it is better to keep probing and evaluating the health state based on the window/threshold parameters for a smoother return to "auto"

**Comment by gquintard** [comment]
I probably won't be at intwash, so casting my vote here: I think it's better to keep the probes running to get a more accurate report. `.initial` is nice and all, but that's an imprecise shortcut.

**Comment by bsdphk** [comment]
Maybe we need a new admin state ("off" ?) that stops probes ?

**Comment by nigoroll** [comment]
ticket has served its purpose, the `off` admin state would be the proper solution, the question is, if it's worth the effort.
