### ISSUE TITLE
Cannot read X-Forwarded-For before modified by Varnish

### ISSUE THREAD

**Issue by Bilge** [varnishcache/varnish-cache#3453]
## Current Behavior
It should be possible to read unmodified request headers. Generally, this is possible in sub `vcl_recv`, but not in the case of the `X-Forwarded-For` header, which is modified before any sub can process it. 

```
*   << Request  >> 32853
-   Begin          req 32852 rxreq
-   Timestamp      Start: 1604526879.441043 0.000000 0.000000
-   Timestamp      Req: 1604526879.441043 0.000000 0.000000
-   VCL_use        boot
-   ReqStart       5.6.7.8 27238 a0
-   ReqMethod      GET
-   ReqURL         /
-   ReqProtocol    HTTP/1.1
-   ReqHeader      host: example.com
-   ReqHeader      connection: Keep-Alive
-   ReqHeader      accept-encoding: gzip
-   ReqHeader      x-forwarded-for: 1.2.3.4
-   ReqHeader      accept: */*
-   ReqUnset       x-forwarded-for: 1.2.3.4
-   ReqHeader      X-Forwarded-For: 1.2.3.4, 5.6.7.8
-   VCL_call       RECV
```

As shown in the log above, `ReqUnset` followed by `ReqHeader` rewrites the `X-Forwarded-For` internally before `vcl_recv` is called, but we haven't had a chance to process it yet.

## Expected Behavior

If we know that there will only be one proxy before us, we could just run `std.ip()` on the `X-Forwarded-For` header and be done with it. Since Varnish is going to modify it before we see it for the first time, we have to do additional processing to *undo* what it just did and access the first IP in the stack again. This is incredibly inefficient and wasteful: Varnish pushes an IP onto the header and then we immediately pop it off again, using expensive string manipulation functions like `regsub()`.

## Possible Solution
Two possible solutions come to mind:

1. Expose an additional object such as `rawreq` that has the original, unmolested request headers before Varnish made any changes internally.
2. Add a new sub, such as `vcl_pre_recv` or `vcl_init_recv` or something, that allows access to the request before changes are made to it and is called immediately before `vcl_recv`.

## Your Environment

* Version used: 6.1.1
* Operating System and version: Linux 4.15.0

**Comment by nigoroll** [comment]
First of all, I agree with your analysis, except for _This is incredibly inefficient and wasteful_: Yes, a `regsub()` does come at a cost, but for most users it will still be insignificant in relation to other code of their VCL. So I would agree to that statement except for _incredibly_. 

As far as I remember, the question if core code should modify `X-F-F` had been questioned and discussed at some point before. IIUC, at the time the proposed alternative to the current behavior was to move handling `X-F-F` from core code to `builtin.vcl`. Yet that would only get to run after a user-provided `vcl_recv`, so all users wishing to keep the current `X-F-F` behavior would need to change their VCL.

A new built-in sub would solve this issue in a compatible way, but extending the state engine is something we have been careful about: Calls into VCL subs come at a cost. Understanding Varnish-Cache can already be challenging and new subs add to that load. So we need very good reasons before we add a sub. One such reason would be problems which can not be solved in VCL, which is not the case here. That said, besides handling `X-F-F`, we also collect `Cache-Control` in `cnt_recv_prep`, which is also something we would potentially want to expose in VCL too.

Making the original request headers available is indeed an option which would avoid that cost and also be compatible with exiting VCL. As an alternative to `rawreq` I would propose `req0` which might be more in line with existing (internal) naming. (in code code, the original headers are saved in `(struct req).http0`.

**Comment by nigoroll** [comment]
BTW: If the use case is to get hold of the client IP as seen by one proxy in front of varnish, we commend to use the `PROXY` protocol (see [`varnishd -a` `PROXY` option](https://varnish-cache.org/docs/trunk/reference/varnishd.html#basic-options) and [`client.ip` documentation](https://varnish-cache.org/docs/trunk/reference/vcl.html#local-server-remote-and-client)). This avoids having to process `X-F-F`.

**Comment by Dridi** [comment]
> As far as I remember, the question if core code should modify `X-F-F` had been questioned and discussed at some point before. IIUC, at the time the proposed alternative to the current behavior was to move handling `X-F-F` from core code to `builtin.vcl`. Yet that would only get to run after a user-provided `vcl_recv`, so all users wishing to keep the current `X-F-F` behavior would need to change their VCL.

It used to be handled by the built-in VCL.

> So we need very good reasons before we add a sub. One such reason would be problems which can not be solved in VCL, which is not the case here. That said, besides handling `X-F-F`, we also collect `Cache-Control` in `cnt_recv_prep`, which is also something we would potentially want to expose in VCL too.

We also collect cookies for h2 requests, something that is potentially heavy on workspace usage.

> Making the original request headers available is indeed an option which would avoid that cost and also be compatible with exiting VCL. As an alternative to `rawreq` I would propose `req0` which might be more in line with existing (internal) naming. (in core code, the original headers are saved in `(struct req).http0`).

If we add a sub, then I'd rather have access to `req` from the get go.

Overall I'm really on the fence here, but I'm really skeptical regarding a new sub (and I know I have one in my backlog for #3259). It used to be part of the built-in, but it was also often duplicated in users' VCL especially when they'd intentionally return from `vcl_recv` and skip the built-in. The X-F-F header is a de-facto standard, but it's supposed to be superseded by the `Forwarded` header. At one point there was a discussion about having a boolean parameter to control whether core code would update-or-create either header fields.

If we go the parameter route, we could have a new bits `http` parameter:

- `gzip`
- `range`
- `xff`
- `forwarded`

(see https://github.com/varnishcache/varnish-cache/issues/3269#issuecomment-708925152 where I suggested something somewhat similar)

**Comment by Bilge** [comment]
`req0` sounds good to me.

**Comment by nigoroll** [comment]
> (`X-F-F`) used to be handled by the built-in VCL.

Thank you for refreshing my memory. It helped me find ae548683b8f91d0a92799f6c746b80773a4c9f05 and #1454

**Comment by nigoroll** [comment]
This has been discussed during bugwash.
Participants were generally in favor of a feature flag to disable `X-F-F` processing in c-code.
There could also be a feature flag to prefer `Forwarded`.
The feature flags could live in the `feature` parameter or all http related flags could be moved to a new `http` bitfield parameter.

**Comment by Dridi** [comment]
Meanwhile VIP30 (#3471) flipped the problem space around with an outcome similar to the `vcl_pre_recv` suggestion, moving xff handling back in VCL and it should become possible (see #3484) to both access the header before it's updated or even prevent the update directly from VCL.

There will eventually be a solution to this, and it is already registered in a VIP and another issue. Until then, there is nothing actionable with this ticket so I'm closing it.
