### ISSUE TITLE
website: 404 on http://varnish-cache.org/_downloads/varnish-$VERSION.tgz

### ISSUE THREAD

**Issue by delthas** [varnishcache/varnish-cache#3455]
## Expected Behavior

`http://varnish-cache.org/_downloads/varnish-$VERSION.tgz` used to point to the latest version of Varnish tarballs.

eg  http://varnish-cache.org/_downloads/varnish-5.1.3.tgz

## Current Behavior

All `http://varnish-cache.org/_downloads/varnish-$VERSION.tgz` URLs 404. They have been replaced with:
`http://varnish-cache.org/_downloads/$HASH/varnish-$VERSION.tgz` where `HASH` is not easily guessable.

## Possible Solution

Add redirects for all `http://varnish-cache.org/_downloads/varnish-$VERSION.tgz` URLs redirecting to their latest tarball version (ie their `http://varnish-cache.org/_downloads/$HASH/varnish-$VERSION.tgz`).

## Context

This makes it difficult to download a specific Varnish tarball automatically (for example as part of a CI pipeline). I'd have to scrape the HTML or make a table of all hashes locally which is not great.

**Comment by csandanov** [comment]
I have the same issue, we automatically update our varnish docker image https://github.com/wodby/varnish

**Comment by bsdphk** [comment]
This was introduced by a recent "improvement" in the `sphinx` tool we use to produce the website.

A Workaround is in progress.

**Comment by bsdphk** [comment]
The links should be OK now, I've hacked the installed sphinx on the web-server.

I'm leaving this ticket open until we have a permanent solution.

**Comment by bsdphk** [comment]
For future reference:

In `/usr/local/lib/python3.7/site-packages/sphinx/util/__init__.py`:

    def add_file(self, docname: str, filename: str) -> str:
        if filename not in self:
            #digest = md5(filename.encode()).hexdigest()
            #dest = '%s/%s' % (digest, os.path.basename(filename))
            dest = os.path.basename(filename)
            self[filename] = (set(), dest)

**Comment by mlechner** [comment]
the "improvement" seems to be activated again:

https://varnish-cache.org/lists/pipermail/varnish-misc/2021-February/026980.html

can this be fixed permanently?

**Comment by mlechner** [comment]
thnx, who ever fixed it (temporarily?).

**Comment by xcir** [comment]
It seem to have the same problem after the release of 7.0.0.

**Comment by mlechner** [comment]
happened again today:
http://varnish-cache.org/_downloads/b87bd1e151054fa83a4c5b4fbb85d038/varnish-6.0.10.tgz insdtead of http://varnish-cache.org/_downloads/varnish-6.0.10.tgz 
please fix (permanently)?

**Comment by bsdphk** [comment]
I have implemented a brute-force solution to this problem, which takes the URL's out of sphinx's control.

From now on all of these will work:

    http[s]://varnish-cache.org/[_]downloads/varnish-X.Y.Z.tgz
