### ISSUE TITLE
Ability to reset MAIN.n_lru_nuked counter

### ISSUE THREAD

**Issue by popey456963** [varnishcache/varnish-cache#3458]
## Expected Behavior

After changing the cache store the valueof `MAIN.n_lru_nuked` is reset.

## Current Behavior

There is no way to reset `MAIN.n_lru_nuked`

## Possible Solution

Reset `MAIN.n_lru_nuked` after cache change.

## Steps to Reproduce (for bugs)

1. Check `MAIN.n_lru_nuked`.
2. Change cache size
3. Check `MAIN.n_lru_nuked`.

## Context

I've been working on optimising our Varnish cache size.  It seems impossible to tell how many items have been nuked with the _current_ configuration, other than keeping a track of the scores manually.  I started off with the default cache of 256Mb, meaning that I have millions of nuked objects.  Now that I've increased the size I should see less over a period of time, but it's harder to work out because it never resets.

## Your Environment

* Operating System and version: Ubuntu
* Source of binary packages used (if any): Aptitude

**Comment by Dridi** [comment]
That's the point though. This is a counter, not a gauge, so what you get is the number of discrete events. If your monitoring infrastructure can generate graphs, you may prefer to graph counters as a (non negative) derivative of the value over time.

A change in the cache size requires a restart of `varnishd` which implies a reset of this counter.

**Comment by popey456963** [comment]
Curious.  I was restarting `varnishd` and the counter did not appear to reset?

**Comment by popey456963** [comment]
I'm pretty sure my service was doing something super funky and not restarting varnishd.  Fixing this fixed the counter, works as I expected! :+1:

**Comment by Dridi** [comment]
Next time, please send an email to the misc@varnish-cacche.org for a general question instead of opening an issue. If you aren't certain this is a bug, please use the mailing list or the #varnish channel on IRC.

https://varnish-cache.org/support/
