### ISSUE TITLE
vsl query numerals pitfall

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3463]
```
# varnishlog -r vxid.vsl -b -q 'TimeStamp:Beresp[2] > 119.86' -I 'TimeStamp:Beresp:'
*   << BeReq    >> 697119952 
-   Timestamp      Beresp: 1605489745.781986 119.861152 119.860892
```

but:

```
# varnishlog -r vxid.vsl -b -q 'TimeStamp:Beresp[2] > 119' -I 'TimeStamp:Beresp:'
```

(no output)

**Comment by Dridi** [comment]
I thought I had fixed that in the past, I was at the very least aware, so I will have a look at it since I happen to tread in VSL space these days.

**Comment by Dridi** [comment]
It's actually a documented behavior, I will nevertheless have a look and see whether we can fall back efficiently.
