### ISSUE TITLE
[feature] Add std.duration2integer(duration, fallback)

### ISSUE THREAD

**Issue by nyurik** [varnishcache/varnish-cache#3465]
When creating a `max-age` response header, I sometimes need to convert Varnish duration type to an integer. It seems there is no easy way to do it, forcing a fairly cumbersome (slow?) workaround (assume the `VCL_TTL` environment variable gets injected into VCL on build using `envsubst`)

```
// $VCL_TTL could be set to a proper duration like  1h
set resp.http.cache-control = 
    "public, max-age=" + 
    std.time2integer(std.time(0, now) + ${VCL_TTL}, 3600);
```

I would like to propose a `std.duration2integer(DURATION, INT)` function that would convert a proper duration value to an integer:

```
set resp.http.cache-control =
    "public, max-age=" +
    std.duration2integer(${VCL_TTL}, 3600);
```

Note that concatenating duration with a string `"max-age=" + 1h` results in `max-age=3600.000` -- not sure why string casting uses a float. Syntax like `"max-age=" + ((int)1h)` does not work.

## Your Environment

* Version used: 6.0
* Operating System and version: linux (docker image published by Varnish)

**Comment by Dridi** [comment]
As stated in our issue template, we use github issues for bug reports and have other channels for feature requests, or in your case a bit of guidance.

With 6.5 we changed `std.integer()` to allow it to take a `DURATION` among other inputs. If you need that for 6.0 you need to reach out to the misc mailing list and ask the back-port team to consider your case. But you can also get away with it on the condition of being evil:

```
varnishtest "3465"

server s1 {
        rxreq
        txresp
} -start

varnish v1 -vcl+backend {
        sub vcl_deliver {
                set resp.http.cache-control = "max-age=" + regsub(1h, "\..*", "") + ", public";
        }
} -start

client c1 {
        txreq
        rxresp
        expect resp.http.cache-control == "max-age=3600, public"
} -run
```

If you want to continue this discussion, please hit the misc list: https://varnish-cache.org/support/

**Comment by nyurik** [comment]
@Dridi my apologies, i should have read the issue comment more carefully. Thank you for your feedback and for the great project!
