### ISSUE TITLE
Missing signal to reload configs in varnishncsa

### ISSUE THREAD

**Issue by Bilge** [varnishcache/varnish-cache#3466]
It might be useful to have a signal to reload the output format (`-F`) and query files (`-Q`) in a live running instance, since restarting the program (`varnishncsa`) might drop data.

**Comment by nigoroll** [comment]
bugwash: we see a use case, but, as VSL clients may still drop data for a log overrun, we cannot quite follow the argument of avoiding data drops.
My personal work around so far was to have some overlap between an old and new log client when changing the configuration.
As we do not use tickets for feature requests, this would best be added as a [VIP](https://github.com/varnishcache/varnish-cache/wiki/Varnish-Improvement-Proposals). Also it seems this would need either an implementer or a sponsor, no-one was immediately volunteering to attempt the implementation.

@Bilge would you want to write up a VIP?

I will close this issue but will continue to assist you in case you need any help.

**Comment by Bilge** [comment]
>@Bilge would you want to write up a VIP?

@nigoroll No, I don't think so, I'm not interested in writing it up twice. From my brief assessment, VIP appears to be where ideas go to die. I'm not sure why you believe it's a good idea to misappropriate the wiki as a crude issue tracker when GitHub already has a fully functioning issue tracker system, but I disagree.

**Comment by nigoroll** [comment]
@Bilge please do not kill the messenger (I was merely reporting from bugwash) and please accept the rules the project has given itself.
It is true that some long-standing VIPs exist which have not been implemented, but also you fill find those who have.
At any rate, this is likely to get accepted once anyone writes the code.
