### ISSUE TITLE
Improving .path / UNIX socket handling

### ISSUE THREAD

**Issue by idl0r** [varnishcache/varnish-cache#3477]
Hey,

I just wanted to use a UNIX socket for backend connections since enabling .proxy_header [1|2] warns about a connection being used only once per request and may lead into EADDRNOTAVAIL according to:
https://varnish-cache.org/docs/6.1/reference/vcl.html#backend-definition
And for .path it says:

> The absolute path of a Unix domain socket at which a backend is listening. The file at that path must exist and must be accessible to Varnish at VCL load time, and it must be a socket. One of .path or .host must be declared (but not both). .path may only be used in VCL since version 4.1.

Wouldn't it make sense to treat it kind of like a TCP socket / connection and just try it again?
So it should fail the same way as a non open / reachable TCP listener and being tried again upon the next request IMHO.

**Comment by nigoroll** [comment]
since #2884 / 18e255742334720be7e7a02cc4c088d78be1fb67 a missing socket or a lack of permission does not fail vcl loading any more, but rather issues only a warning. The documentation was updated with f878f30444ca6cc19175e54c87c84fca69f9f697

When opening a UDS fails, it should be retried for any subsequent request. Can you please explain the actual problem you are seeing here?

**Comment by nigoroll** [comment]
please reopen if there is an actual issue

**Comment by idl0r** [comment]
Ah, that looks good.
One question though:

> But the socket file must exist and have necessary
￼    permissions before the first connection is attempted, otherwise
￼    fetches will fail.

Does that mean that it just fails as long as it is not available or even when it became available, after the first connection is attempted?

**Comment by nigoroll** [comment]
We do not use github issues for support questions. See here https://varnish-cache.org/support/index.html
