### ISSUE TITLE
revisit backend None

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3478]
With #3067 / ecef48518f3b3f4bbf28256e090bdbb5cd2b163c we added
```
backend <name> None;
```
to VCL, with `None` being translated to the `NULL` pointer.

Now with
```
backend a None;
backend b None;
```

`a` and `b` are indistinguishable, which is fine if you understand the C code, but might not exactly be POLA.

We might want to revisit how we implement the `None` backend.

**Comment by Dridi** [comment]
We should probably have a none director and actually generate individual instances, to at least carry be able to find the backend name of `bere(q|sp).backend`. I do not expect such a director to expose VSCs.

**Comment by nigoroll** [comment]
bugwash: docfix
