### ISSUE TITLE
Ignore or use alternate beresp.grace on beresp.status 200?

### ISSUE THREAD

**Issue by stateisbad** [varnishcache/varnish-cache#3494]
Hello all,

Apologies if there is a well-known way to achieve this, but I thus far haven't been able to find one. We're looking to add some resiliency to our Varnish layer when it comes to sporadic 503s from backends (we're also investigating that, but that's a separate issue). We have a high-throughput, low TTL/grace setup. Both the beresp ttl and grace are set to `1s`. The issue we're seeing is that, on occasion, for a few minutes, we receive 503s from our backend cluster. During this time, we'd like to cover this issue by serving stale cache when a 503 is received from the backend. Setting the beresp.grace to `5m` "works," although for certain paths that aren't hit constantly that results in serving stale cache for up to 5 minutes (due to how grace works by sending the cached object to the client while also retrieving a newer copy from the backend for the next request). The comment at the bottom of this blog post describes what we're seeing perfectly: https://blog.markvincze.com/how-to-gracefully-fall-back-to-cache-on-5xx-responses-with-varnish/

I haven't been able to find a way to use a low grace of say `1s` for 200 backend responses while using the higher `5m` grace for 503s. Here's my current backend config:

```
sub vcl_backend_response {
  set beresp.ttl = 1s;
  set beresp.grace = 5m;
  if (beresp.status == 500) {
    saintmode.blacklist(20s);
    return(retry);
  }
  if (beresp.status == 503) {
    if (bereq.is_bgfetch) {
      return (abandon);
    }
    set beresp.uncacheable = true;
  }
}
```

As you can see I've approached this by setting the default grace to `5m`. What I'm struggling with is finding some way to either _ignore_ or _use_ a lower value (like `1s`) if the beresp.status is `200`. If I create a `if (beresp.status == 200)` statement and inside set the grace to `1s`, it obviously changes it for the cached object entirely, replacing the `5m` value.

Does Varnish have the concept of `use` or `ignore` or anything similar? I've tested this on Varnish 5.2 as well as 6.5, with the same results. I see in 6.5 `req.grace` was reintroduced, and maybe that would provide some way, but so far I haven't been able to figure out how. Any advice or input would be appreciated. Thanks!

**Comment by nigoroll** [comment]
I think you have given the right answer yourself. But we [do not use issues for questions](https://varnish-cache.org/support/index.html) and you would know had you read the issue template.
