### ISSUE TITLE
varnishadm: Connection failed (<remote-ip>:6082): (null)

### ISSUE THREAD

**Issue by asadsa92** [varnishcache/varnish-cache#3510]
## Expected Behavior

`varnishadm` should always try to give a useful error message when a connection fails to open such that the user is able to investigate what the cause of the problem is.

## Current Behavior
`varnishadm` will sometime print:
`Connection failed (<remote-ip>:<port>): (null)`

This message is not very useful for the user as it lack a proper error message.

`varnishadm` uses `VTCP_open` to open a TCP connection. `VTCP_open`, and its sub routines, is supposed to fill in an error code if the connection fails, but after taking a quick glance I see some code paths leaving `error == NULL` during an abnormal return. This means that the user is left with a somewhat useless message about why the connection failed. 

## Steps to Reproduce
Run: `varnishadm -T <remote-ip>:<port>`
E.g., remote-ip: 127.0.0.1, port: 6082

Since `varnishd` is not running, we expect the connection to fail with a useful error message:
Output: `Connection failed (127.0.0.1:6082): (null)`

The error message gives no hint of what the problem could be.

### Background
I tried to use two computers, one running `varnishd`, while the other machine trying to connect to it through `varnishadm`.
I was not paying attention and ran this (on the first computer):

```
sudo ./varnishd -j unix,user=vcache -F -a :80 -T 127.0.0.1:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,256m
```

Obviously, `-T 127.0.0.1:6082` is an error as I want to accept connection over LAN. For completeness, this should have been at the very least `-T :6082`, i.e,, accept connections from all IP instead of only accepting from the same computer running `varnishd`.

However, I did not catch my error, and went to run this (on the second computer):

```
sudo varnishadm -T <remote-ip>:6082 -S /etc/varnish/secret
```

varnishadm was not being very helpful:

```
Connection failed (<remote-ip>:6082): (null)
```

Now, to investigate, I tried to see if changing the remote IP had any effect,  but to no avail (no local `varnishd` running):

```
sudo varnishadm -T 127.0.0.1:6082 -S /etc/varnish/secret
```

```
Connection failed (127.0.0.1:6082): (null)
```

The very same error. I then ran `tcpdump` and saw that the TCP handshake was being reset.

It was after I caught up with my mistake that I realized the first host was only listening to local clients and sure enough the mistake was located.  

## Environment
* Version used: commit da2409c3863d1da8f2dac0ace9ae05fa0e743d81 (master branch)
* Operating System and version: Debian GNU/Linux bullseye/sid (5.10.0-1-amd64)

**Comment by nigoroll** [comment]
bugwash: @asadsa92 to suggest a PR once #3509 is fixed

**Comment by asadsa92** [comment]
No longer reproducible after https://github.com/varnishcache/varnish-cache/commit/0d746632253d038c58110c9f2eeeef19b604556f
