### ISSUE TITLE
Trying to compile Varnish on Solaris 11.4, flock,  error: ‘LOCK_EX’ undeclared

### ISSUE THREAD

**Issue by corvinus-sysadmin** [varnishcache/varnish-cache#3513]
Hello,

I'm trying to compile Varnish, I tried to use version 5.2.1, 6.0.7 and 6.5.1, but any of them seems to have the same problem.

It seems that it has been coded to use flock(), but I guess Solaris does not support that. I'm using Oracle Solaris 11.4.28 and GCC 7.3.0. 

The installation guide does not say anything about this problem. Is there any workaround in Solaris to be able to compile Varnish? Should I try to compile it with Solaris Studio?

root@moodleplp:/app/moodlep/src/varnish/varnish-cache# /usr/bin/env LANG=en_US.UTF-8 CONFIG_SHELL="/bin/bash" PKG_CONFIG_PATH=/usr/lib/64/pkgconfig PKG_CONFIG_PATH=/usr/lib/64/pkgconfig CC="/usr/gcc/7/bin/gcc -m64 " CXX="/usr/gcc/7/bin/g++" PATH="/usr/gnu/bin:/usr/bin/64:/usr/bin" CC_FOR_BUILD="/usr/gcc/7/bin/gcc -m64" CXX_FOR_BUILD="/usr/gcc/7/bin/g++ -m64" CPPFLAGS="-m64" "ac_cv_func_realloc_0_nonnull=yes" "NM=/usr/gnu/bin/nm" INTLTOOL_PERL="/usr/perl5/5.22/bin/perl" CFLAGS="-m64 -O3" CXXFLAGS="-m64 -O3" LDFLAGS="" MAKE="gmake" make

vfl.c: In function ‘vflopenat’:
vfl.c:69:14: error: ‘LOCK_EX’ undeclared (first use in this function); did you mean ‘LOCK_HELD’?
  operation = LOCK_EX;
              ^~~~~~~
              LOCK_HELD
vfl.c:69:14: note: each undeclared identifier is reported only once for each function it appears in
vfl.c:71:16: error: ‘LOCK_NB’ undeclared (first use in this function); did you mean ‘LOCK_EX’?
   operation |= LOCK_NB;
                ^~~~~~~
                LOCK_EX
vfl.c:80:7: error: implicit declaration of function ‘flock’; did you mean ‘clock’? [-Werror=implicit-function-declaration]
   if (flock(fd, operation) == -1) {
       ^~~~~
       clock
cc1: all warnings being treated as errors
gmake[3]: *** [Makefile:911: libvarnish_la-vfl.lo] Error 1
gmake[3]: Leaving directory '/app/moodlep/src/varnish/varnish-cache/lib/libvarnish'
gmake[2]: *** [Makefile:417: all-recursive] Error 1
gmake[2]: Leaving directory '/app/moodlep/src/varnish/varnish-cache/lib'
gmake[1]: *** [Makefile:570: all-recursive] Error 1
gmake[1]: Leaving directory '/app/moodlep/src/varnish/varnish-cache'
make: *** [Makefile:455: all] Error 2

Kind regards,

 Benedek Rakovics

**Comment by corvinus-sysadmin** [comment]
Here is the output from the configuration:

root@moodleplp:/app/moodlep/src/varnish/varnish-cache# /usr/bin/env LANG=en_US.UTF-8 CONFIG_SHELL="/bin/bash" PKG_CONFIG_PATH=/usr/lib/64/pkgconfig PKG_CONFIG_PATH=/usr/lib/64/pkgconfig CC="/usr/gcc/7/bin/gcc -m64 " CXX="/usr/gcc/7/bin/g++" PATH="/usr/gnu/bin:/usr/bin/64:/usr/bin" CC_FOR_BUILD="/usr/gcc/7/bin/gcc -m64" CXX_FOR_BUILD="/usr/gcc/7/bin/g++ -m64" CPPFLAGS="-m64" "ac_cv_func_realloc_0_nonnull=yes" "NM=/usr/gnu/bin/nm" INTLTOOL_PERL="/usr/perl5/5.22/bin/perl" CFLAGS="-m64 -O3" CXXFLAGS="-m64 -O3" LDFLAGS=""  sh configure
checking for gcc... /usr/gcc/7/bin/gcc -m64
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/gcc/7/bin/gcc -m64  accepts -g... yes
checking for /usr/gcc/7/bin/gcc -m64  option to accept ISO C89... none needed
checking whether /usr/gcc/7/bin/gcc -m64  understands -c and -o together... yes
checking how to run the C preprocessor... /usr/gcc/7/bin/gcc -m64  -E
checking for grep that handles long lines and -e... /usr/gnu/bin/grep
checking for egrep... /usr/gnu/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking build system type... sparc-sun-solaris2.11
checking host system type... sparc-sun-solaris2.11
checking target system type... sparc-sun-solaris2.11
checking whether to enable maintainer-specific portions of Makefiles... no
checking for a BSD-compatible install... /usr/gnu/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/gnu/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of /usr/gcc/7/bin/gcc -m64 ... gcc3
checking whether make supports nested variables... (cached) yes
checking how to print strings... print -r
checking for a sed that does not truncate output... /usr/gnu/bin/sed
checking for fgrep... /usr/gnu/bin/grep -F
checking for ld used by /usr/gcc/7/bin/gcc -m64 ... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/gnu/bin/nm
checking the name lister (/usr/gnu/bin/nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572480
checking how to convert sparc-sun-solaris2.11 file names to sparc-sun-solaris2.11 format... func_convert_file_noop
checking how to convert sparc-sun-solaris2.11 file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... print -r --
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/gnu/bin/nm output from /usr/gcc/7/bin/gcc -m64  object... ok
checking for sysroot... no
checking for a working dd... /usr/gnu/bin/dd
checking how to truncate binary pipes... /usr/gnu/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if /usr/gcc/7/bin/gcc -m64  supports -fno-rtti -fno-exceptions... no
checking for /usr/gcc/7/bin/gcc -m64  option to produce PIC... -fPIC -DPIC
checking if /usr/gcc/7/bin/gcc -m64  PIC flag -fPIC -DPIC works... yes
checking if /usr/gcc/7/bin/gcc -m64  static flag -static works... no
checking if /usr/gcc/7/bin/gcc -m64  supports -c -o file.o... yes
checking if /usr/gcc/7/bin/gcc -m64  supports -c -o file.o... (cached) yes
checking whether the /usr/gcc/7/bin/gcc -m64  linker (/usr/bin/ld -64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... solaris2.11 ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... no
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for gcc... (cached) /usr/gcc/7/bin/gcc -m64
checking whether we are using the GNU C compiler... (cached) yes
checking whether /usr/gcc/7/bin/gcc -m64  accepts -g... (cached) yes
checking for /usr/gcc/7/bin/gcc -m64  option to accept ISO C89... (cached) none needed
checking whether /usr/gcc/7/bin/gcc -m64  understands -c and -o together... (cached) yes
checking for /usr/gcc/7/bin/gcc -m64  option to accept ISO C99... none needed
checking for /usr/gcc/7/bin/gcc -m64  option to accept ISO Standard C... (cached) none needed
checking whether /usr/gcc/7/bin/gcc -m64  is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... -D_POSIX_PTHREAD_SEMANTICS
checking for PTHREAD_PRIO_INHERIT... yes
checking for rst2man-3.6... no
checking for rst2man-3... no
checking for rst2man... no
checking for rst2man.py... rst2man.py
checking for sphinx-build-3.6... no
checking for sphinx-build-3... no
checking for sphinx-build... sphinx-build
checking for rst2html-3.6... no
checking for rst2html-3... no
checking for rst2html... no
checking for rst2html.py... rst2html.py
checking for dot... dot
checking for a Python interpreter with version >= 3.4... python3.7
checking for python3.7... /usr/bin/python3.7
checking for python3.7 version... 3.7
checking for python3.7 platform... sunos5
checking for python3.7 script directory... ${prefix}/lib/python3.7/site-packages
checking for python3.7 extension module directory... ${exec_prefix}/lib/python3.7/site-packages
checking for library containing pthread_create... none required
checking for clock_gettime in -lrt... yes
checking for dlopen in -ldl... yes
checking for socket in -lsocket... yes
checking for getaddrinfo in -lnsl... yes
checking umem.h usability... yes
checking umem.h presence... yes
checking for umem.h... yes
checking stdatomic.h usability... yes
checking stdatomic.h presence... yes
checking for stdatomic.h... yes
checking for cos in -lm... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for PCRE... yes
checking for PCRE JIT usability... yes
checking edit/readline/readline.h usability... no
checking edit/readline/readline.h presence... no
checking for edit/readline/readline.h... no
checking for LIBEDIT... yes
checking editline/readline.h usability... yes
checking editline/readline.h presence... yes
checking for editline/readline.h... yes
checking for CURSES... no
checking for CURSES... no
checking for CURSES... no
checking for NcursesW wide-character library... yes
checking for working ncursesw/curses.h... no
checking for working ncursesw.h... no
checking for working ncurses.h... no
configure: WARNING: could not find a working ncursesw/curses.h, ncursesw.h or ncurses.h
checking ncursesw/curses.h usability... no
checking ncursesw/curses.h presence... no
checking for ncursesw/curses.h... no
checking ncursesw.h usability... no
checking ncursesw.h presence... no
checking for ncursesw.h... no
checking ncurses/curses.h usability... yes
checking ncurses/curses.h presence... yes
checking for ncurses/curses.h... yes
checking ncurses.h usability... no
checking ncurses.h presence... no
checking for ncurses.h... no
checking curses.h usability... yes
checking curses.h presence... yes
checking for curses.h... yes
checking for ANSI C header files... (cached) yes
checking sys/endian.h usability... no
checking sys/endian.h presence... no
checking for sys/endian.h... no
checking sys/filio.h usability... yes
checking sys/filio.h presence... yes
checking for sys/filio.h... yes
checking for sys/mount.h... yes
checking sys/personality.h usability... no
checking sys/personality.h presence... no
checking for sys/personality.h... no
checking sys/statvfs.h usability... yes
checking sys/statvfs.h presence... yes
checking for sys/statvfs.h... yes
checking sys/vfs.h usability... yes
checking sys/vfs.h presence... yes
checking for sys/vfs.h... yes
checking endian.h usability... no
checking endian.h presence... no
checking for endian.h... no
checking for pthread_np.h... no
checking priv.h usability... yes
checking priv.h presence... yes
checking for priv.h... yes
checking fnmatch.h usability... yes
checking fnmatch.h presence... yes
checking for fnmatch.h... yes
checking for nanosleep... yes
checking for setppriv... yes
checking for fallocate... no
checking for closefrom... yes
checking for sigaltstack... yes
checking for getpeereid... no
checking for getpeerucred... yes
checking for fnmatch... yes
checking for pthread_set_name_np... no
checking for pthread_setname_np... yes
checking for pthread_mutex_isowned_np... no
checking for pthread_getattr_np... yes
checking whether __SUNPRO_C is declared... no
checking whether we have support for visibility attributes... yes
checking for setproctitle... no
checking for library containing backtrace... none required
checking whether daemon() works... checking for daemon... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for clock_gettime... yes
checking for gethrtime... yes
checking if clock_gettime is faster than gethrtime... no
checking for kqueue... no
checking for epoll_ctl... no
checking for port_create... yes
checking for struct sockaddr.sa_len... no
checking whether SO_ACCEPTFILTER is declared... no
checking whether SO_RCVTIMEO works... yes
checking whether SO_SNDTIMEO works... yes
checking for TCP_KEEP(CNT|IDLE|INTVL) socket options... no
checking for TCP_FASTOPEN socket option... no
checking if LD -Wl,--version-script works... no
checking whether C compiler accepts -Wall... yes
checking whether C compiler accepts -Werror... yes
checking whether C compiler accepts -Werror=unused-result... yes
checking whether C compiler accepts -fstack-protector... yes
checking whether the linker accepts -fstack-protector... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating bin/Makefile
config.status: creating bin/varnishadm/Makefile
config.status: creating bin/varnishd/Makefile
config.status: creating bin/varnishlog/Makefile
config.status: creating bin/varnishstat/Makefile
config.status: creating bin/varnishtop/Makefile
config.status: creating bin/varnishhist/Makefile
config.status: creating bin/varnishtest/Makefile
config.status: creating bin/varnishncsa/Makefile
config.status: creating doc/Makefile
config.status: creating doc/graphviz/Makefile
config.status: creating doc/sphinx/Makefile
config.status: creating doc/sphinx/conf.py
config.status: creating etc/Makefile
config.status: creating include/Makefile
config.status: creating lib/Makefile
config.status: creating lib/libvarnish/Makefile
config.status: creating lib/libvarnishapi/Makefile
config.status: creating lib/libvcc/Makefile
config.status: creating lib/libvgz/Makefile
config.status: creating man/Makefile
config.status: creating varnishapi.pc
config.status: creating varnishapi-uninstalled.pc
config.status: creating vmod/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing mkdir commands

**Comment by corvinus-sysadmin** [comment]
I did the following modifications, it might need some additional refinements:

./lib/libvarnish/vfl.c

#ifdef __sun
        operation = F_SETLK;
#else
        operation = LOCK_EX;
#endif

        if (flags & O_NONBLOCK)
#ifdef __sun
                operation |= F_RDLCK;
#else
                operation |= LOCK_NB;
#endif


*** I dont know if there should be a while cycle below

#ifdef __sun
                if (fcntl(fd, operation) == -1) {
                        /* unsupported or interrupted */
                        serrno = errno;
                        (void)close(fd);
                        errno = serrno;
                        return (-1);
                }
#else
                if (flock(fd, operation) == -1) {
                        /* unsupported or interrupted */
                        serrno = errno;
                        (void)close(fd);
                        errno = serrno;
                        return (-1);
                }
#endif

**Comment by corvinus-sysadmin** [comment]
Somethings still not perfect (a* test went fine, but b* fails):
bin/varnishtest/tests/b00001.log 

**** dT    0.000
*    top   TEST ./tests/b00001.vtc starting
**** top   extmacro def pwd=/app/moodlep/src/varnish/varnish-cache/bin/varnishtest
**** top   extmacro def localhost=127.0.0.1
**** top   extmacro def bad_backend=127.0.0.1:51901
**** top   extmacro def listen_addr=127.0.0.1:0
**** top   extmacro def bad_ip=192.0.2.255
**** top   extmacro def topbuild=/app/moodlep/src/varnish/varnish-cache
**** top   macro def testdir=/app/moodlep/src/varnish/varnish-cache/bin/varnishtest/./tests
**** top   macro def tmpdir=/tmp/vtc.23242.6cf0d100
**   top   === varnishtest "Check that a pipe transaction works"
*    top   VTEST Check that a pipe transaction works
**   top   === server s1 -repeat 1 {
**   s1    Starting server
**** s1    macro def s1_addr=127.0.0.1
**** s1    macro def s1_port=55928
**** s1    macro def s1_sock=127.0.0.1:55928
*    s1    Listen on 127.0.0.1:55928
**** dT    0.001
**   top   === varnish v1 -vcl+backend {
**   s1    Started on 127.0.0.1:55928 (1 iterations)
**** dT    0.009
**   v1    Launch
***  v1    CMD: cd ${pwd} && exec varnishd  -d -n /tmp/vtc.23242.6cf0d100/v1 -l 2m -p auto_restart=off -p syslog_cli_traffic=off -p thread_pool_min=10 -p debug=+vtc_mode -p vsl_mask=+Debug -p h2_initial_window_size=1m -p h2_rx_window_low_water=64k -a '127.0.0.1:0' -M '127.0.0.1 46511' -P /tmp/vtc.23242.6cf0d100/v1/varnishd.pid -p vmod_path=/app/moodlep/src/varnish/varnish-cache/vmod/.libs
***  v1    CMD: cd /app/moodlep/src/varnish/varnish-cache/bin/varnishtest && exec varnishd  -d -n /tmp/vtc.23242.6cf0d100/v1 -l 2m -p auto_restart=off -p syslog_cli_traffic=off -p thread_pool_min=10 -p debug=+vtc_mode -p vsl_mask=+Debug -p h2_initial_window_size=1m -p h2_rx_window_low_water=64k -a '127.0.0.1:0' -M '127.0.0.1 46511' -P /tmp/vtc.23242.6cf0d100/v1/varnishd.pid -p vmod_path=/app/moodlep/src/varnish/varnish-cache/vmod/.libs
***  v1    PID: 23259
**** v1    macro def v1_pid=23259
**** v1    macro def v1_name=/tmp/vtc.23242.6cf0d100/v1
**** dT    0.019
***  v1    debug|Error: Could not open pid-file (/tmp/vtc.23242.6cf0d100/v1//_.pid):
***  v1    debug|Bad address
***  v1    debug|(-? gives usage)
**** v1    CLIPOLL 1 0x0 0x10
---- v1    FAIL debug pipe closed
**** v1    STDOUT EOF
*    top   RESETTING after ./tests/b00001.vtc
**   s1    Waiting for server (3/-1)
**   v1    Wait
**** v1    CLI TX|panic.clear
#    top  TEST ./tests/b00001.vtc TIMED OUT (kill -9)
#    top  TEST ./tests/b00001.vtc FAILED (60.002) signal=9
FAIL tests/b00001.vtc (exit status: 2)

**Comment by nigoroll** [comment]
FYI, I will try to look at this, but can not offer an immediate detailed response due to important customer requests having priority at the moment.
We build on SmartOS as part of our continuous testing (see http://varnish-cache.org/vtest/ ), so my instinctive reaction is that you might have a botched build environment or that Oracle has made some odd changes since the Opensolaris fork.
To begin with, I wonder if this could be related to your overrides of the various build-related variables.
For our vtest server, we use far less. As an example, take the default gcc build for 64bit:

```
LC_ALL=C
export LC_ALL
# ...
export PATH=/opt/local/gcc47/bin:/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin
export MESSAGE="gcc4.7.3 -m64 IPv6 uffix"
export CC=gcc
unset CPPFLAGS
unset CFLAGS
unset LDFLAGS
runtest &
```

**Comment by bsdphk** [comment]
I'm going to time this ticket out.

If the issue still exists, feel free to reopen the ticket.

**Comment by wtarreau** [comment]
Just feeding this a little bit in case anyone else stumbles on this issue.

I faced a similar problem trying to build Vtest on Solaris 10, plus other issues. In short, LOCK_EX, LOCK_NB, O_CLOEXEC do not exist there. strndup() doesn't exist either (though that's easily addressed by doing a local implementation), struct statfs is not found but is present in sys/statfs.h, and FIONBIO requires inclusion of sys/ioctl.h. I have not tried to fix them given the lack of the former. I'm not sure if there's a way around them (O_CLOEXEC could probably be dropped if not existing, but for the LOCK_* stuff I don't know).
