### ISSUE TITLE
Shaman-mode

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#3517]
Fundamental Assumption:
-----------------------

We can never find a grace-candidate, which would not also be the IMS-candidate.

Proposal:
---------

In `vcl_miss{}` we give access to the IMS-object (if any) and the option of delivering it.

Everything else, including `builtin.vcl` stays the same, so nothing will happen unless explicitly coded in VCL.

Discussion:
-----------

Saint-mode worked by extending `grace` when the backend is sick, before the cache lookup happens.

For technical reasons, it was often implementing with a high default `grace` which was then lowered if the backend is healthy for the specific hash.

This required acccess to the hash-key, which is not available until after `vcl_hash{}` which then lead to the proposal for a new `vcl_lookup{}` to run after `vcl_hash{}` had run.

This is a counter-proposal.

Shaman-mode can do more than the proposed `vcl_lookup{}`, by runing with the lower `grace` by default, explicitly overriding it in `vcl_miss{}` when the backend is sick.

The precise VCL to do this, risks being clunky because negative numbers are involved, but something like:

```
        sub vcl_miss {
                if ([[backend is not healty]] &&
                    ${bikeshedobj} &&
                    ${bikeshedobj}.ttl > -${extragrace}) {
                        return (deliver);
                }
        }
```

A marked improvement over Saint-mode is that instead of "any object not older than" we can now examine everything about the concrete object in question before we decide to deliver it:

```
        sub vcl_miss {
                if ([[backend is not healty]] &&
                    ${bikeshedobj} &&
                    ${bikeshedobj}.ttl > -${extragrace} &&
                    ! ${bikeshedobj}.http.rushjob) {
                        return (deliver);
                }
        }
```

Why didnt we think of this before:
----------------------------------

We did not have IMS back then, so `vcl_miss{}` had no imscand-object that could be used this way.

Bikesheds:
----------

We need to decide if we expose the IMS-candidate as `obj.*` or as something else in `vcl_miss{}` (`oldobj.*`, `staleobj.*` etc.)

It is not clear what precisely users would use for `${extragrace}` in the above example.

It can obviously be a constant, but it seems likely that people will want to decide this value at `vcl_recv{}` time, but the value cannot be stashed in any of `req.{ttl,grace,keep}` without affecting the cache lookup.

A `req.${bikeshed}` may be desired, to communicate ${extragrace}  from `vcl_recv{}` to `vcl_miss{}`.

That would be a credible argument for per-task VCL variables.

Compatibility Issues:
---------------------

None.  It will take explicit, currently illegal VCL code in `vcl_miss{}` to enable this mode.

Implementation:
---------------

Seems uncomplicated, has not yet been attempted.

**Comment by nigoroll** [comment]
FTR, current context is #3259 / #3514 . Previous context is the (in?)famous #1799

General note upfront: I see this as orthogonal to _saintmode_: This PR does not touch on the idea of blacklisting a backend for a specific hash. For the "extend grace by blacklisted backend" use case something like _saintmode_ might still be needed (a similar result can be achieved with the _shard_ director `alt` parameter).

A basic concern is changing the miss vs. hit semantics. Do I understand correctly that the proposal is to continue to go to `vcl_hit` if `req.grace` is satisfied?

A major concern from #1799 was backend coalescing. It is not yet clear to me how we would deal with it in the context of this proposal. Currently, if there is a busy object and no qualified grace object (as per `req.grace`), we go straight to the waitinglist after `HSH_Lookup()`. Yet for this proposal to be useful to extend grace, we would need to go to `vcl_miss` even with a busyobject present.

**Comment by bsdphk** [comment]
"A basic concern is changing the miss vs. hit semantics. Do I understand correctly that the proposal is to continue to go to vcl_hit if req.grace is satisfied?"

Yes, unless you change your VCL to do this, nothing changes.

**Comment by bsdphk** [comment]
Overtaken by evens (and waiting list)
