### ISSUE TITLE
Move to travis-ci.com

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3519]
IIUC, we need to migrate?

https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/

**Comment by fgsch** [comment]
Just send a request to have access to this org in travis-ci.com.

**Comment by bsdphk** [comment]
Can somebody please write a summary of:

A: What is the current situation ?

B: What is the change ?

C: What are our alternatives, if any ?

**Comment by martin-g** [comment]
Hi,

On Thu, Feb 11, 2021 at 2:03 PM Poul-Henning Kamp <notifications@github.com>
wrote:

> Can somebody please write a summary of:
>
> A: What is the current situation ?
>
Varnish Cache uses Travis CI:
https://travis-ci.org/github/varnishcache/varnish-cache

> B: What is the change ?
>

travis-ci.*org *is deprecated in favour of travis-ci.*com*
Their documentation says that all projects which have not migrated by 31
Dec 2020 should have been migrated automatically but it didn't happen for
some reason.

> C: What are our alternatives, if any ?
>
1) Any GitHub admin of https://github.com/varnishcache/ should be able to
login to Travis-ci.org with his/her GitHub account (OAuth) and click a
button "Migrate".
2) Do nothing. Just wait and TravisCI will migrate you at some point

Regards,
Martin

**Comment by nigoroll** [comment]
bugwash appreciates @fgsch looking after this. We want to keep travis-ci for now, but general concerns have been raised with respect to CCI and travis making their data collection more invasive.

**Comment by fgsch** [comment]
Yeah, I agree. I didn't want to mention other options in this issue as they could be investigated and decided in parallel to migrating to travis-ci.com so there is no disruption to the CI pipeline.

**Comment by nigoroll** [comment]
@fgsch are you still working on this ticket? Do you need it open?

**Comment by fgsch** [comment]
@fgsch I am. I think I need someone with perms to do some stuff in GH. I will reach out on irc.

**Comment by martin-g** [comment]
FYI: by moving from .org to .com you may face an issue - TravisCI has put a limit of 10000 free credits. I.e. sooner or later they will ask you to pay for more credits to be able to run CI jobs.
TravisCI people say that for OSS projects there will be unlimited credits but some projects were not able to convince Travis that they are OSS...

**Comment by bsdphk** [comment]
I'm timing this ticket out, it seems to have served its purpose.

Feel free to reopen if new events warrant that.

**Comment by Dridi** [comment]
We are passed the .org deadline and there are no travis builds showing up in commits and pull request checks.

**Comment by fgsch** [comment]
Someone with org ownership perms needs to go to https://github.com/apps/travis-ci/installations/new, and set it up.

**Comment by Dridi** [comment]
Migration presumably complete with the old .org history: https://travis-ci.com/github/varnishcache/varnish-cache

Let's close when we see an actual build trigger, I force-pushed #3638 just changing the commit date and don't see any ongoing travisci build so far (even though circleci triggered a rebuild).

**Comment by fgsch** [comment]
I tried triggering a build and got "Could not authorize build request for varnishcache/varnish-cache.".
It might be me lacking some perms but doesn't look like it is working.

**Comment by Dridi** [comment]
That was because we needed to explicitly select a plan, which I just did. I hope it was the last missing bit of the setup, thanks for the help!
