### ISSUE TITLE
beresp.status and beresp.reason not reset on a retry

### ISSUE THREAD

**Issue by stevendore** [varnishcache/varnish-cache#3525]
When using `return error($STATUS, $REASON)` the status and response are not reset on future retries.

A PR with a fix and reproducible VTC coming shortly.

**Comment by nigoroll** [comment]
Can you please explain in which situation this is a problem? Why would we care about the values until they are set again?

**Comment by stevendore** [comment]
This leads to an incorrect reason and response. Looking at the VTC: https://github.com/varnishcache/varnish-cache/pull/3526/files#diff-13a21228d28972c9833d7b956a6c5abf478d1c60f07a69b9b5f192c9f778f911R5

Our status and response is `500` and `my response`.

We then retry, fail to connect to the backend. This usually a `503` but doesn't get set because we already have status and reason. Now we have an incorrect status / reason being  reported. The fields were supposed to be updated to 503/Backend failed but never was.

Additionally this is something already done in the client side that didn't make it to the backend side: https://github.com/varnishcache/varnish-cache/blob/b559b6b2daabc67901dfae07571b1300869ef690/bin/varnishd/cache/cache_req_fsm.c#L818-L841

**Comment by rezan** [comment]
Also, if you use `return error()` to transition into a new state and then happen to get a real backend error on your next retry, then those transition values are now returned.

**Comment by nigoroll** [comment]
thank you for the clarification, this should be a no-brainer then
