### ISSUE TITLE
threads_limited increases without reaching thread_pool_max

### ISSUE THREAD

**Issue by johanneswuerbach** [varnishcache/varnish-cache#3531]
## Current Behavior

`MAIN.threads_limited` sporadically increases while `thread_pool_max` has not been reached

## Expected Behavior

`MAIN.threads_limited` only increases limit if it reached the thread pool limit as described here https://varnish-cache.org/docs/6.5/reference/varnish-counters.html

## Possible Solution

If this is a known condition, I'm happy to work on a documentation update.

## Steps to Reproduce (for bugs)

The issue is reproducible when simulating fairly spiky traffic e.g. going from 200 to 5000 concurrent requests.

1. Checkout https://github.com/johanneswuerbach/varnish-threads-limit
2. With docker & docker compose installed locally `make build start stats` in one terminal
3. `make test` in another terminal
4. After a few seconds you should see `MAIN.threads_limited` increase without hitting the thread_pool_max, which is configured as 10000

## Context

Hitting the max threads pool is a situation we would like to monitor to ensure varnish is scaled appropriately, therefor we observe threads_limit using https://github.com/jonnenauha/prometheus_varnish_exporter and wondered whether there is another limitation we are hitting by seeing that occasionally threads being limited.  

## Your Environment

* Version used: varnishd (varnish-6.1.1 revision efc2f6c1536cf2272e471f5cff5f145239b19460)
* Operating System and version: Inside docker based on debian:buster-20210111-slim using the official debian packages. Reproducible with flatcar as host OS (kernel 5.4.92) and inside Docker for Mac (kernel 4.19.121)  
* Source of binary packages used (if any): The official debian buster package https://packagecloud.io/app/varnishcache/varnish65/search?dist=debian%2Fbuster

**Comment by nigoroll** [comment]
some notes upfront:
* you are using an outdated version. We have seen some relevant changes in this area since 6.1.1, #2942 / bdcdaf936ca13e07b8a71584e93669a0d0fcaf41 in particular
* If `MAIN.threads_failed` is non-zero, threads could not be created, most likely for a resource limit like `RLIMIT_NPROC` or systemd `TasksMax` (setting cgroup `pids.max`)
* also keep in mind that pools are largely decoupled. A session accepted by one pool will only use that pool's threads.

So I suspect this issue is invalid, and I would only want to have a closer look if it could be shown to exist with current code and the abovementioned aspects considered.

**Comment by johanneswuerbach** [comment]
Sorry I tricked myself trying to reproduce the issue locally on an arm macbook, which can't use the official deb packages, I will update the reproduction with building varnish from source and report back.

In production we use `varnish-6.5.1 revision 1dae23376bb5ea7a6b8e9e4b9ed95cdc9469fb64` and see the same issue. Our `MAIN.threads_failed` is usually zero.

Our current thread count is usually way below the configured 10000 thread_pool_max so even a complete imbalance shouldn't be above the overall limit.

Below is a chart of threads/threads_limited/threads_failed from two varnish pods serving traffic roughly 50/50. Due to a spike in traffic we increased from 200 to ~320 threads and one of the varnishes is incrementing the threads_limited. threads_failed stays constantly at zero during the event.

![image](https://user-images.githubusercontent.com/864578/108623137-99608a00-743d-11eb-8011-8f7c341afb3d.png)

**Comment by nigoroll** [comment]
The graphs are in line with what I would expect from before #2942 / bdcdaf9 

With current code, I am aware that we might occasionally _over_ breed (create more threads then absolutely necessary), which I find acceptable. But I am not aware of any _under_ breeding, so I we would really need to see this happening with current code before this ticket is actionable.
Please reopen if so

**Comment by nigoroll** [comment]
oops I overlookde that the production version is 6.5.1

**Comment by nigoroll** [comment]
There is a race in current code which can lead to the counter being increased even if everything is ok.
Fix on the way.

**Comment by johanneswuerbach** [comment]
Wow, thanks for the fast response and fix 🤩. Really amazing 👏
