### ISSUE TITLE
for long-running cc_command, vcl.load fails intermittendly with error 400

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3542]
This is a placeholder to be filled with more detailed information
When `cc_command` takes ~12 seconds (which is considerably shorter than the 60 second `cli_timeout`), `vcl.load` occasionally fails with an error 400, despite succeeding
```
+ varnishadm vcl.load quickdeploy32256 /tmp/varnish-live.vcl
VCL compiled.
CLI communication error
Command failed with error code 400
command terminated with exit code 1
```

**Comment by nigoroll** [comment]
see also here: https://serverfault.com/questions/940716/large-varnish-vcl-does-not-load

**Comment by bsdphk** [comment]
GCC has a known problem, as in O(lines^n), with compiling large functions.

I have deeply sunken TODO item about decomposing large ACLs to multiple functions called serially.

**Comment by nigoroll** [comment]
As discussed on IRC: For my particular case, I am already using inline-C to attribute `v_dont_optimize` to the `vcl_init` subs in use. Using `gcc -O0` or switching to `clang` does not reduce the compilation time significantly and this bug is concerned with the 400 error, not with compiler runtime.

**Comment by nigoroll** [comment]
I added a backtrace to the 400 error to check where it originates, and it is varnishadm
```
$ while : ; do /tmp/bin/varnishadm vcl.load n$RANDOM /tmp/t.vcl ; done
Rejected 400
/tmp/bin/varnishadm(VCLI_ReadResult+0x1db) [0x403ebb]
/tmp/bin/varnishadm() [0x402584]
/tmp/bin/varnishadm() [0x402cda]
/tmp/bin/varnishadm() [0x402425]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f7fc0de52e1]
/tmp/bin/varnishadm() [0x40214a]

Rejected 400
/tmp/bin/varnishadm(VCLI_ReadResult+0x1db) [0x403ebb]
/tmp/bin/varnishadm() [0x402584]
/tmp/bin/varnishadm() [0x402cda]
/tmp/bin/varnishadm() [0x402425]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1) [0x7f4f7ef4f2e1]
/tmp/bin/varnishadm() [0x40214a]
...
```
