### ISSUE TITLE
[rfc] make builtin subroutines easier to reuse

### ISSUE THREAD

**Issue by gquintard** [varnishcache/varnish-cache#3543]
Following #3541, I'm way late to the party, but I just realized: would it make sense to have a single encapsulating `vcl_builtin_$METH` method, in essence going from:
```
sub vcl_recv
	call vcl_req_host;
	call vcl_req_method;
	call vcl_req_authorization;
	call vcl_req_cookie;
	return (hash);
}
```
to:
```
sub vcl_recv
	call vcl_builtin_req;
	return (hash);
}

sub vcl_builtin_req {
	call vcl_req_host;
	call vcl_req_method;
	call vcl_req_authorization;
	call vcl_req_cookie;
}
```
that would allow users to easily call the builtin VCL without knowing exactly which subroutines to call?

**Comment by Dridi** [comment]
FWIW it's not a breaking change, it something we can safely do before or after the March release.

**Comment by nigoroll** [comment]
bugwash was in favor by a single +1 vote.
@gquintard would you please implement `vcl_foo => vcl_builtin_foo` for all built-in subs but `init/fini`?

**Comment by gquintard** [comment]
@nigoroll , with pleasure. For planning consideration, does this have a chance of getting in the release next week, or is that cutting it too short?

**Comment by nigoroll** [comment]
FTR see 3f3d67d9da491155bda9f1f1d4986b5228db5fd6 #3548
