### ISSUE TITLE
ACL rework

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#3544]
I have revisited the VCC/ACL production and the landscape has shifted significantly since we decided the current "compile to code" strategy, and in particular compilers have gotten even slower at compiling huge functions.

If diving in here anyway, a couple of UX related questions:

Should it be possible to control, per-ACL or even per ACL-entry if a VSL record should be logged on match ?

Do we want statistics counters (possibly optional per-ACL or even per ACL-entry?) for ACL hits ?

Does anybody have representative huge ACL's they can share with me for study ?

**Comment by nigoroll** [comment]
I have never seen demand for changing the logging or statistics counters.
The largest ACL I use is generated from the list of networks in `AS32934` and `AS54115`, as returned by `whois -h whois.radb.net -- "-i origin ${AS_NUMER}"`.
The other topic I have on my wish list is the _acl merge_ patch, which I am maintaining and using in production, but for which I have not opened a PR because I had been asked to improve VTC coverage for ACLs first: https://github.com/nigoroll/varnish-cache/tree/acl_merge

**Comment by bsdphk** [comment]
Preliminary benchmark:
-------------------

The test-acl has 12554 non-overlapping entries{1}.

The test matches 62914560 different IP#'s against this ACL{2}.

The test is not realistic of real world use{3}.

The table code has not been profiled/optimized yet.

Measurements:
-------------

            Compile         Test/All         Test/IP
    --------------------------------------------------------
    CODE     23.6 s      6.65 +/- 0.13s   105.8 +/- 1.9ns
    TABLE     1.2 s     22.18 +/- 0.55s   352.6 +/- 8.6ns
    --------------------------------------------------------

Implementation details:
-----------------------

VCC emits a uint8[], and bsearch(3) is used to find a matching entry, taking partial byte compares due to masks into account.

bsearch(3) can only find a single exact match, so overlapping entries are not allowed in the table.  They are instead emitted as code (as usual), and the table is only consulted if the code finds no hits.
 
Observations:
-------------

a) Our current ACL's are blindingly fast.

b) C-compilers are much better at huge-data than huge-functions.

c) It's not even close.

Conclusions
-----------

Even though I suspect nobody would notice if we switched to the table-driven approach, a 3:1 performance difference makes me uneasy.

The table driven approach is hard to speed up, without adding a *lot* of complexity{4}.

Right now I'm most inclined to add "acl-table" as a VCL keyword, to let people pick which mode they want, on a per-ACL basis.

{1} 'non-overlapping' is important: Only entries not overlapped by another entry will be put in the table.  Not sure how real-world ACLs look in this respect.  At the cost of adding more complexity, this requirement can be loosened by having multiple tables.

{2} Every 64th IP# between 0.0.0.0 and 239.255.255.255.

{3} These are near-optimal conditions, because a vmod_debug function simply pounds all IP#s through the ACL.

{4} The only thing I can think of is a VCC-contructed per-ACL weighed-binary search function. Not going there.

**Comment by bsdphk** [comment]
I have committed the table code as disabled by default in cc885760c1b2fbd6467084a3437a2c5327f6407d
