### ISSUE TITLE
SUB arguments use-before-define

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3555]
SUB arguments currently can only be used after being defined. E.g. this works:

```
sub foo { }
sub caller {
  some.vmod(foo);
}
```

but this does not:

```
sub caller {
  some.vmod(foo);
}
sub foo { }
```

**Comment by Dridi** [comment]
Isn't this the case with other symbols too? (backend, acl, anything named)

**Comment by nigoroll** [comment]
exactly. But `call sub` instantiates `sub`, so I wonder if use as an argument should do the same

**Comment by Dridi** [comment]
It's actually not true that anything named can be defined after use. It's only true for a subset of the VCL parsing like the `call` action or the IP `~` operator.

With this test case snippet:

```
varnish v1 -vcl {
        sub vcl_recv {
                set req.backend_hint = b;
        }
        backend b { .host = "${localhost}"; }
}
```

I get this:

```
**** v1    CLI RX|Message from VCC-compiler:
**** v1    CLI RX|Symbol not found: 'b'
**** v1    CLI RX|At: ('<vcl.inline>' Line 4 Pos 40) -- (Pos 40)
**** v1    CLI RX|                set req.backend_hint = b;
**** v1    CLI RX|---------------------------------------#-
**** v1    CLI RX|
**** v1    CLI RX|Running VCC-compiler failed, exited with 2
**** v1    CLI RX|VCL compilation failed
---- v1    VCL compilation failed expected success
```

I think we could generalize "defined after use" for all types that need to be referenced when used via a symbol:

- ACL
- BACKEND
- PROBE
- SUB

If we agree on doing that, I would implement this special case with a new field in `struct type`.

**Comment by Dridi** [comment]
https://github.com/varnishcache/varnish-cache/pull/3613
