### ISSUE TITLE
Move to pcre2

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#3559]
Check that it's OK for all the platforms we care about.

**Comment by ingvarha** [comment]
Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1938985

**Comment by Dridi** [comment]
https://github.com/varnishcache/varnish-cache/pull/3616

**Comment by Dridi** [comment]
Feedback from testing on Fedora is welcome.
