### ISSUE TITLE
Configurable MAX_HDR for Varnishtest

### ISSUE THREAD

**Issue by aondio** [varnishcache/varnish-cache#3574]
Default value for MAX_HDR is 50 lines and it is hardcoded.
More and more often users, when writing very verbose tests, hit that limit.

Either a higher value, or even better a configurable one, would be nice to have.

**Comment by Dridi** [comment]
FWIW, the default value for `http_max_hdr` is 64, but maybe we could have something like:

```
server s1 -max_hdr 64 {
        ...
} -start
```

**Comment by bsdphk** [comment]
I'm fine with this, but personally I would probably just bump the default up and not add complexity.
