### ISSUE TITLE
Should default probe start out healthy ?

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#3596]
`d00007.vtc` contains:

        probe pr {}

        sub vcl_init {
                new s1 = debug.dyn("0.0.0.0", "0");
        }

        sub vcl_recv {
                s1.refresh("${s1_addr}", "${s1_port}", pr);
                set req.backend_hint = s1.backend();
        }

While playing around with directors, I spotted a fundamental problem here.

The default director is sick when created, and becomes healthy if the first response it receives is good.

So how has `d00007.vtc` ever worked, when the dynamic backend is created `sick` in `vcl_recv{}` ?

It transpires that we never actually did set that initial `sick` status from the probe.

Setting health status is supressed in `VBP_Update_Backend()` if `backend->director == NULL`.

`backend-director` is NULL, until after `VRT_AddDirector()` returns, so the `VBP_Control()` call which should have set the probes initial `sick` status, does not.

This bug is fixable, but I suspect it would more POLA to let the default probe start out healthy, and fall sick if the first probe fails ?

**Comment by Dridi** [comment]
The probe´s `initial` value defaults to `threshold - 1`, it´s in the manual. I don´t see a need to change that, even POLA: arguably you want to see your probe succeed at least once before using a backend you decided to guard with that probe.

FWIW it´s the main reason why an optional delay was added to the `varnishreload` script between `vcl.load` and `vcl.use`.

If that disturbs a test case, then it should be configured accordingly.

**Comment by bsdphk** [comment]
Bugwash:  Keep documented behaviour, fix code, fix d7 to have `probe { .initial = .threshold }`

(Release-note fodder!)
