### ISSUE TITLE
libvarnishapi: suppress or fix VUT_Init "memory leak"

### ISSUE THREAD

**Issue by asadsa92** [varnishcache/varnish-cache#3597]
## Current Behavior
We allocate `vut`, but soon realize that we need to `exit`. This result in an ASAN panic.
```
../../bin/varnishncsa/varnishncsa --options > include/varnishncsa_options.rst_
=================================================================
==85091==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x7fcae7bc4037 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:154
    #1 0x7fcae793ae99 in VUT_Init .../varnish-cache/lib/libvarnishapi/vut.c:249
    #2 0x561c29361655 in main .../varnish-cache/bin/varnishncsa/varnishncsa.c:1087
    #3 0x7fcae6b4fd09 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 144 byte(s) leaked in 1 allocation(s).

```

## Possible Solution
We really do not need the `vut` object before terminating as it goes unused, so move the allocation below the `exit` calls.
Another solution might be to just suppress this.

## Steps to Reproduce (for bugs)
1. sh autogen.sh && sh configure --enable-ubsan --enable-asan
2. make clean all

## Your Environment
* Version used: f2b9846d212dfd5bfc8b94637feff84741b4f282
* OS: Debian GNU/Linux bullseye/sid
* Kernel: 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09)

**Comment by nigoroll** [comment]
I have not run ASAN, please reopen if still present.
