### ISSUE TITLE
Varnish as no root container 

### ISSUE THREAD

**Issue by jbrunetext** [varnishcache/varnish-cache#3605]
Hello Team varnish i faced an issue when i start varnish in docker mode .
I have a Dockerfile that run into kubernetes cluster. So far so good . it's work fine but i want to use a no root container i have this error . 

Error: Could not get socket :80: Permission denied
(-? gives usage)

You can find my Dockerfile below
ARG VARNISH_VERSION=6.0
FROM varnish:${VARNISH_VERSION} AS client_varnish

RUN apt-get update && apt-get install -y procps && \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $fetchDeps && \
    rm -rf /var/lib/apt/lists/*

COPY client/docker/varnish/conf /etc/varnish

# Use non Root User into Container ,User varnish already exist...
RUN chown -R varnish:varnish /var/lib/varnish
USER varnish

CMD ["bash", "-c", "varnishd -F -f /etc/varnish/default.vcl -p http_req_hdr_len=65536 -p http_req_size=98304 -p workspace_backend=256k -p workspace_client=256k -p shm_reclen=1024 -p max_retries=1 & varnishncsa -b -c -t off"]

**Comment by bsdphk** [comment]
The `varnish` user does not have permissions to claim socket 80.

This is normal UNIX behaviour: You have to be root to open a socket less than 1000 (in some cases <1024)

**Comment by jbrunetext** [comment]
Works for me ....
RUN apt-get update && apt-get install -y libpcap-dev libcap2-bin
COPY docker/varnish/conf/default.vcl /etc/varnish/default.vcl

# allow varnish bin to listen 80
RUN setcap 'cap_net_bind_service=+ep' /usr/sbin/varnishd
# Use non Root User into Container ,User varnish already exist...
RUN chown -R varnish:varnish /var/lib/varnish
USER varnish
