### ISSUE TITLE
Varnish is running but throws ‘Could not get hold of varnishd’ when I run varnishlog

### ISSUE THREAD

**Issue by jbrunetext** [varnishcache/varnish-cache#3607]
### Possible Solution
Possible create files with different permissions.

### Steps to Reproduce (for bugs)
Pull image for K8s from varnish docker registry
FROM varnish:6.0

Use the user varnish,  and add his following param :
-a /tmp/listen.sock,HTTP,user=varnish,group=varnish,mode=660

varnishhist ,

Start it with the docker -compose.
Your Environment: 
Version used: Varnish 6.0
Operating System and version: Ubuntu or Mac Os
Source of binary packages used (if any)
Built from varnish image 6.0

I faced an issue when i use varnishlog.

USER varnish

CMD ["bash", "-c", "varnishd -F  -P /tmp/varnish.pid -n /tmp/varnish -a /tmp/listen.sock,HTTP,user=varnish,group=varnish,mode=660 -p http_req_hdr_len=65536 -p http_req_size=98304 -p workspace_backend=256k -p workspace_client=256k -p shm_reclen=1024 -p max_retries=1 & varnishncsa -b -c -t off"]

my varnish works and it is responsive but i can not  do an varnishlog.same thing with varnishncsa

Did i make something wrong in my config ?

**Comment by gquintard** [comment]
Hi,

note: that's really a question for the varnish-misc mailing list (https://varnish-cache.org/lists/mailman/listinfo/varnish-misc),** or the docker repository (https://github.com/varnish/docker-varnish) (or IRC https://varnish-cache.org/support/).

because you wanted to start `varnishd` as a regular user, you had to use `-n /tmp/varnish` to avoid permission issues (I think that was the idea, right), but you didn't to that for `varnishncsa` which will still be looking for data in `/var/lib/varnish$HOSTNAME`. In short, add `-n /tmp/varnish` to `varnishncsa` too.

please reopen if I went wrong somewhere here

**Comment by jbrunetext** [comment]
Hello @gquintard  i made the change in my dockerFile like you say 
`
#Varnish stage
FROM varnish:6.0

RUN apt-get update && apt-get install -y libpcap-dev libcap2-bin

COPY docker/varnish/conf/default.vcl /etc/varnish/default.vcl

RUN setcap 'cap_net_bind_service=+ep' /usr/sbin/varnishd
RUN usermod -a -G varnish varnishlog
RUN chown -R varnish:varnish /var/lib/varnish
USER varnish

CMD ["bash", "-c", "varnishd -F -f /etc/varnish/default.vcl -n /tmp/varnish -a /tmp/listen.sock,HTTP,user=varnish,group=varnish,mode=660 -p http_req_hdr_len=65536 -p http_req_size=98304 -p workspace_backend=256k -p workspace_client=256k -p shm_reclen=1024 -p max_retries=1 & varnishncsa -n /tmp/varnish -b -c -t off"]
`
i'm still suck with my issue VSM: Could not get hold of varnishd, is it running?

It looks like varnishlog is not pointing to the correct directory, or has not access to it.

Any helps would be nice

**Comment by Dridi** [comment]
We only use github issues for bug reports (modulus a few exceptions) as stated in the issue template.

Could you please move it to the misc mailing list as suggested by both @gquintard and the aforementioned issue template?

Also, it's not quite clear how you are running varnishlog and varnishncsa. Are they running in the same container? If they are running in different containers, do they share a volume for `/tmp/varnish`?

Please do not answer here and move the discussion to the mailing list.

https://varnish-cache.org/support/
