### ISSUE TITLE
Change ACL logging default?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3611]
Since varnishd commit 1e45d97c32b80232d84f6b2dec9c5e275a94c3f8, ACL use is not logged any more by default. Do we want to restore the previous default behavior?

**Comment by bsdphk** [comment]
I thought we already agreed to change the default for 7 ?

**Comment by nigoroll** [comment]
Closed as per bugwash consensus, the decision must have slipped through on my end.
