### ISSUE TITLE
Documentation: is std.file_exists cached?

### ISSUE THREAD

**Issue by glensc** [varnishcache/varnish-cache#3632]
For `std.fileread` there's a description of it being cached:
> The entire file is cached on the first call, and subsequent calls will return this cached contents, even if the file has changed in the meantime.

- https://varnish-cache.org/docs/6.6/reference/vmod_std.html#string-fileread-string

but nothing documented by `std.file_exists`:
- https://varnish-cache.org/docs/6.6/reference/vmod_std.html#std-file-exists

altho `strace` shows that no file access is made during vcl run. so its result seems to be cached as well.

The next question is how long are these cached? excellent would be if they cached for the lifetime of vcl, for example if new vcl is loaded with `varnishreload`, then file cache is all reset.

**Comment by gquintard** [comment]
Hi,

it's not cached (by the vmod), it's just a `stat()` call: https://github.com/varnishcache/varnish-cache/blob/master/vmod/vmod_std.c#L176

**Comment by glensc** [comment]
@gquintard 

🚧 Never link to branches, share a permalink 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
  and https://docs.gitlab.com/ee/user/shortcuts.html#project-files
- hit `y`
- and perhaps for https://github.com/josephfrazier/octopermalinker (GitHub)

**Comment by gquintard** [comment]
yeah, I'm going to close that issue

**Comment by glensc** [comment]
@gquintard and not improve documentation for the community?

**Comment by gquintard** [comment]
I don't think that is necessary? The function that caches is advertised as caching, the one that doesn't isn't. If you feel strongly about it, please open a PR with the wording you'd like to see, it's truly the fastest way to change it.

**Comment by Dridi** [comment]
FWIW, the issue template states that we don't use github issues for general questions and that is something that should have been discussed on a mailing list in the first place.

**Comment by glensc** [comment]
yes, I'd really want a feature request, and likely for the next milestone because of breaking change:

> excellent would be if they cached for the lifetime of vcl, for example if new vcl is loaded with varnishreload, then file cache is all reset.

I'm sorry, I will not go into 90s and subscribe to a mailing list to post a feature request.

**Comment by Dridi** [comment]
That is unfortunate.
