### ISSUE TITLE
Add a quiet flag to varnishd

### ISSUE THREAD

**Issue by markslater** [varnishcache/varnish-cache#3649]
By default, Varnish outputs seven lines to stdout on successful start up.  It should be possible to make `varnishd` respect 
[the rule of silence](http://www.linfo.org/rule_of_silence.html).  This makes it easier to identify problems because it means that if the process produces *any* output, it needs to be investigated.

## Expected Behavior
Add a `-q` flag to `varnishd` to suppress all 'unsurprising' output.  Warnings likely *should* be output in the presence of this flag, but note that the current output seems to be treating `VCL compiled` as a warning.

## Current Behavior
`varnishd` outputs:
```
Warnings:
VCL compiled.

Debug: Version: varnish-6.6.0 revision ef54768fc10f5b19556c7cf9866efc88cfbda8ff
Debug: Platform: Linux,5.4.0-77-generic,x86_64,-junix,-smalloc,-sdefault,-hcritbit
Debug: Child (23) Started
Info: Child (23) said Child starts
```

## Steps to Reproduce (for bugs)
1. Write the following configuration to e.g. `/tmp/default.vcl`
    ```
    vcl 4.0;

    backend default {
      .host = "www.example.com:80";
    }
    ```
1. execute `docker run --rm -it -v /tmp:/etc/varnish:ro --tmpfs /var/lib/varnish:exec varnish:6.6.0-1`
1. observe output

## Context
I'm running the [official Docker image](https://hub.docker.com/_/varnish) in Kubernetes.  This environment tends towards relatively large numbers of relatively short lived processes, which makes it important to be able to identify output that requires attention at a glance.

## Your Environment
I'm using the official Docker image with tag `6.6.0-1`

**Comment by Dridi** [comment]
Simple reproducer:

```
$ varnishd -F -a :0 -b :0 -n /tmp
Warnings:
VCL compiled.

Debug: Version: varnish-6.5.2 revision e7233b0ad2639043341819d19a8d2e418e94ce1b
Debug: Platform: Linux,5.13.5-200.fc34.x86_64,x86_64,-jnone,-sdefault,-sdefault,-hcritbit
Debug: Child (1383744) Started
Info: Child (1383744) said Child starts
```

I'll look at the spurious "warning".

**Comment by Dridi** [comment]
That warning may or may not be spurious, it's hard to tell from `cli_check()`:

```
$ cat test.vcl 
vcl 4.1;

backend b4 { .host = "127.0.0.1"; }
backend b6 { .host = "::1"; }

$ varnishd -F -a :0 -n /tmp -p vcc_err_unref=off -f $PWD/test.vcl
Warnings:
Message from VCC-compiler:
Unused backend b6, defined:
('test.vcl' Line 4 Pos 9)
backend b6 { .host = "::1"; }
--------##-------------------

(That was just a warning)
VCL compiled.

Debug: Version: varnish-6.5.2 revision e7233b0ad2639043341819d19a8d2e418e94ce1b
Debug: Platform: Linux,5.13.5-200.fc34.x86_64,x86_64,-jnone,-sdefault,-sdefault,-hcritbit
Debug: Child (1387696) Started
Info: Child (1387696) said Child starts
```

What could maybe be done would be to turn all `fprintf(strerr)` occurrences in the mgt process into proper `MGT_Complain()` calls. They would be `syslog`'d with a proper log level that might make things easier from a log centralization standpoint, and with that we could silence the `stderr` output with a simple `2>/dev/null`.

For me, whether we add a `-q` option or not, the first step should be the avoidance of direct `stderr` access, with `MGT_Complain()` as suggested.

Thoughts?

**Comment by bsdphk** [comment]
I have looked at this and rearranged things slightly, and I think that goes as far as we can in this respect.

Now `stderr` is only used for diagnostics if either a `-d` or `-F` flag is given.
