### ISSUE TITLE
localstatedir -> /var/something

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#3672]
Currently, and mostly due to autocrap defaults, our `localstatedir` ends up being `${PREFIX}/varnish`

That generally puts our run-time state under `/usr/local` or `/opt` which seems wrong: That stuff belongs under `/var`

@Dridi pointed out that having VSM files survive reboots is a debugging benefit.

To @bsdphk    `/var/tmp` seems like the right place to be, but Linux manpages describe this as:

        /var/tmp
               Like /tmp, this directory holds temporary files  stored  for  an
               unspecified duration.

This worries @Dridi , he suspects the files may disappaer under our feet without warning, with reference to the ISO-C "unspecified" madness.

@bsdphk think nothing much would work for long if that was the case, and notes that `/var/tmp` works for other daemons.

@Dridi points to `/var/cache` as a possible alternative.

Whatever default we set, `configure` arguments can override them.

**Comment by Dridi** [comment]
> That generally puts our run-time state under `/usr/local` or `/opt` which seems wrong: That stuff belongs under `/var`

Precision needed here to avoid confusion.

`/usr/local` is the default prefix in autoconf, and it is usually changed by packaging tools. For example RPM usually comes with a `%configure` macro that runs the configure script with some platform specific flags.

On my machine:

```
rpm --eval %configure
[... skipping exports of default CFLAGS and friends ...]
  ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu \
        --program-prefix= \
        --disable-dependency-tracking \
        --prefix=/usr \
        --exec-prefix=/usr \
        --bindir=/usr/bin \
        --sbindir=/usr/sbin \
        --sysconfdir=/etc \
        --datadir=/usr/share \
        --includedir=/usr/include \
        --libdir=/usr/lib64 \
        --libexecdir=/usr/libexec \
        --localstatedir=/var \
        --sharedstatedir=/var/lib \
        --mandir=/usr/share/man \
        --infodir=/usr/share/info
```

Some systems package things in `/opt`, I have seen it with at least one SunOS derivative, but our own `autogen.des` uses a `/opt/varnish` prefix for development so we shouldn't be surprised to see it show up in CI.

**Comment by nigoroll** [comment]
FTR: This has been discussed during bugwash.
One answer could be to refer to [site defaults](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.70/html_node/Site-Defaults.html)

**Comment by nigoroll** [comment]
FTR, I am unhappy about this change.
To begin with, how does one override `VARNISH_STATE_DIR` to the old behaviour?
