### ISSUE TITLE
varnishncsa -j can produce invalid JSON with Varnish:time_firstbyte

### ISSUE THREAD

**Issue by volter** [varnishcache/varnish-cache#3682]
Running varnishncsa from a weekly build (20210707) for Debian Buster with varnishd 6.6.1 from Debian Buster packages

I've actually seen this type of request logged before I started using the -j option and I don't really know what it is. Might be a corner case! Varnish:time_firstbyte is causing trouble, as it is simply an empty string here.
`FORMAT='{"vxid": "%{VCL_Log:vxid}x", "backend": "%{GH-BE}o", "vhost": "%{Host}i", "clientip": "%h", "userid": "%u", "timestamp": %{msec}t, "method": "%m", "request": "%U%q", "response": %s, "bytes": %b, "referrer": "%{Referer}i", "agent": "%{User-agent}i", "httpd_time": %D, "varnish_time_first_byte": %{Varnish:time_firstbyte}x, "varnish_handling": "%{Varnish:handling}x", ...`

`/usr/local/bin/varnishncsa -F "${FORMAT}"`

`{"vxid": "", "backend": "-", "vhost": "-", "clientip": "-", "userid": "-", "timestamp": 1630484907756, "method": "-", "request": "-", "response": 400, "bytes": 0, "referrer": "-", "agent": "-", "httpd_time": 0, "varnish_time_first_byte": , "varnish_handling": "-", ...`

Perhaps this could take a CTX.missing_int or something.

**Comment by Dridi** [comment]
On spot, thanks!

I had a look at the remaining "missing" bits but only noticed this one standing out.
