### ISSUE TITLE
RFC: Requiring socket timeouts to work?

### ISSUE THREAD

**Issue by Dridi** [varnishcache/varnish-cache#3692]
After I accidentally spotted e4a04d593 it occurred to me that we have `PLATFORM_DEPENDENT` flags for timeout parameters but that's incomplete.

At least `between_bytes_timeout` is set up with both `poll(2)` and `SO_RCVTIMEO` (the latter for HTTP/1 when we pull the beresp body from the VFP chain).  Ideally it should be documented that it could be partially implemented.

Should we instead pull the plug on a non-working socket timeouts? 

The reason why we have this is:

> Older Solaris versions define SO_{RCV,SND}TIMEO, but do not implement them.

I think OpenSolaris has been dead long enough for us not to care anymore, and I'd be surprised if OpenSolaris descendants didn't have socket timeouts support today.

**Comment by nigoroll** [comment]
👍🏽 for requiring `*TIMEO`

**Comment by Dridi** [comment]
Bugwash: we take `SO_???TIMEO` at face value and don't try to determine whether it actually works.
