### ISSUE TITLE
vnum_c_test fails on alpine x_86

### ISSUE THREAD

**Issue by gquintard** [varnishcache/varnish-cache#3697]
while trying to build packages for `7.0.0` I hit this:
```
==================================================
   Varnish 7.0.0: lib/libvarnish/test-suite.log
==================================================
# TOTAL: 6
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
.. contents:: :depth: 2
FAIL: vnum_c_test
=================
./vnum_c_test: VNUM_Duration() wrong, 31556908.800 delta = 8.658390e-10
FAIL vnum_c_test (exit status: 1)
```

This is on `alpine`, so using `muslc`, and the arch is `x86`, full log here: https://gitlab.alpinelinux.org/gquintard/aports/-/jobs/487996

**Comment by gquintard** [comment]
ok, looks like this is a combination of `-m32` and any non-zero `-O` optimization. You can easily reproduce on your regular `x86_64` (as long as you can use `m32`):

```
root@efadecff2eeb:/varnish-cache/lib/libvarnish# gcc  -o foo -DNUM_C_TEST -DTEST_VERBOSE -I../.. -I../../include vnum.c vas.c vct.c -lm -O1 -m32
root@efadecff2eeb:/varnish-cache/lib/libvarnish# ./foo
./foo: VNUM_Duration() wrong, 31556908.800 delta = 8.658390e-10
```

It's not just `gcc`, `clang` behaves the same too.
and just `printf`ing the value of `d1` before the test is enough to make the test pass...

**Comment by andypost** [comment]
Great news, thank you

**Comment by Dridi** [comment]
```
$ gcc -o foo -DNUM_C_TEST -DTEST_VERBOSE -I. -Iinclude lib/libvarnish/{vnum.c,vas.c,vct.c} -lm -Ofast -m32
$ ./foo
VNUM(12.34e-3) not NAN (nan)
VNUM(12.34e3) not NAN (nan)
VNUM(12.34e+3) not NAN (nan)
VNUM(+12.34e-3) not NAN (nan)
VNUM(-12.34e3) not NAN (nan)
VNUM(.) not NAN (nan)
VNUM(.12.) not NAN (nan)
VNUM(12..) not NAN (nan)
VNUM(12.,) not NAN (nan)
VNUM(12e,) not NAN (nan)
VNUM(12e+,) not NAN (nan)
VNUM(12ee,) not NAN (nan)
VNUM(1..2) not NAN (nan)
VNUM(A) not NAN (nan)
VNUM(1A) not NAN (nan)
VNUM(e-3) not NAN (nan)
./foo: VNUM_Duration(NULL) fail
./foo: VNUM_Duration() wrong, 31556908.800 delta = 0.000000e+00
```

**Comment by gquintard** [comment]
> `./foo: VNUM_Duration() wrong, 31556908.800 delta = 0.000000e+00`

wrong, with a 0 delta, lovely.

the value I see, `8.658390e-10` is way above my `DBL_EPSILON` (`2.220446e-16`), but still super low. As a result, I don't know how to qualify that bug: is it in the actual code, or just a weakness from the test? If it's the latter, we can go ahead with the `alpine` release, but if it's the former, I'd rather wait until we have a fix that we can use downstream

**Comment by bsdphk** [comment]
This is your regular run of the mill floating-point madness.

The test should be written to deal with that.

**Comment by gquintard** [comment]
So, just allow a custom epsilon? 1e-9 maybe, as we don't really care about
anything under a nanosecond?

**Comment by Dridi** [comment]
> So, just allow a custom epsilon? 1e-9 maybe, as we don't really care about anything under a nanosecond?

This is what @nigoroll and myself suggested. I'll let you submit a pull request and offer a review instead of fixing it myself (I volunteered during bugwash) since you told me on a different channel that you wanted to deal with this.

**Comment by Dridi** [comment]
FYI, the problem when building with `-Ofast` is `-ffast-math`:

```
