### ISSUE TITLE
REQ_STEPs named "Fetch Step"?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3708]
@bsdphk is the naming `Fetch Step` intentional for req fsm steps?

https://github.com/varnishcache/varnish-cache/blob/2f02345a4868e309f36d9c4a38c44ba50a1374ae/bin/varnishd/cache/cache_req_fsm.c#L75

**Comment by Dridi** [comment]
Clearly not:

https://github.com/varnishcache/varnish-cache/blob/2f02345a4868e309f36d9c4a38c44ba50a1374ae/bin/varnishd/cache/cache_fetch.c#L61-L65
