### ISSUE TITLE
Multipart range request not working

### ISSUE THREAD

**Issue by knirmalk** [varnishcache/varnish-cache#3715]
## Expected Behavior
Our origin server supports multipart range requests. We have introduced Varnish cache between origin server and client.
If the client request multipart range requests, Varnish cache is failing with "416 Requested Range Not Satisfiable"

If the request is with single byterange interval Varnish responds successfully with 206 Partial Content. But Multipart byterange interval is  throwing the error

Need support for multipart range requests in Varnish

## Current Behavior

curl -v -X GET -X GET -H "range: bytes=1-200" http://10.28.10.31:30718/lu10/hls/lu10/profile_1_video/Seg_442176/profile_1_video_88435346.ts
Note: Unnecessary use of -X or --request, GET is already inferred.
* Trying 10.28.10.31:30718...
* TCP_NODELAY set
* Connected to 10.28.10.31 (10.28.10.31) port 30718 (#0)
> GET /lu10/hls/lu10/profile_1_video/Seg_442176/profile_1_video_88435346.ts HTTP/1.1
> Host: 10.28.10.31:30718
> User-Agent: curl/7.65.0
> Accept: */*
> range: bytes=1-200
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 206 Partial Content
< Accept-Ranges: bytes
< Access-Control-Allow-Origin: *
< Cache-Control: public, max-age=7200
< Content-Type: video/mp2t
< Date: Thu, 21 Oct 2021 13:41:39 GMT
< Etag: "2021-10-21T13:41:03.994"
< Last-Modified: Thu, 21 Oct 2021 13:41:03 GMT
< Last-Modified-Milliseconds: Thu, 21 Oct 2021 13:41:03.994 GMT
< Origin-Instance: so-service-01
< X-Varnish: 32778
< Age: 0
< Via: 1.1 varnish (Varnish/7.0)
< Content-Range: bytes 1-200/107912
< Content-Length: 200
< Connection: keep-alive
<
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 200)
* Closing connection 0

----------------

curl -v -X GET -X GET -H "range: bytes=1-200, 400-500" http://10.28.10.31:30718/lu10/hls/lu10/profile_1_video/Seg_442176/profile_1_video_88435346.ts
Note: Unnecessary use of -X or --request, GET is already inferred.
* Trying 10.28.10.31:30718...
* TCP_NODELAY set
* Connected to 10.28.10.31 (10.28.10.31) port 30718 (#0)
> GET /lu10/hls/lu10/profile_1_video/Seg_442176/profile_1_video_88435346.ts HTTP/1.1
> Host: 10.28.10.31:30718
> User-Agent: curl/7.65.0
> Accept: */*
> range: bytes=1-200, 400-500
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 416 Requested Range Not Satisfiable
< Accept-Ranges: bytes
< Access-Control-Allow-Origin: *
< Cache-Control: public, max-age=7200
< Content-Type: video/mp2t
< Date: Thu, 21 Oct 2021 13:41:53 GMT
< Etag: "2021-10-21T13:41:03.994"
< Last-Modified: Thu, 21 Oct 2021 13:41:03 GMT
< Last-Modified-Milliseconds: Thu, 21 Oct 2021 13:41:03.994 GMT
< Origin-Instance: so-service-01
< X-Varnish: 32781
< Age: 0
< Via: 1.1 varnish (Varnish/7.0)
< Content-Range: bytes */107912
< Content-Length: 0
< Connection: keep-alive
<

## Possible Solution
Need support for multipart range requests in Varnish

## Context
Our origin server supports multipart range requests & our client does multipart range request. 
The requests are failing after we introduced Varnish between origin & client

## Your Environment

* Version used: Varnish 7.0.0
* Operating System and version: Linux

**Comment by nigoroll** [comment]
If anyone thinks this feature should be prioritized, please provide details on a practical use case any reopen
