### ISSUE TITLE
7.0.1 planning

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3721]
collection of suggestions of tickets for inclusion in 7.0.1

Candidates to merge in the 7.0 branch:

* [x] #3706 46bbfe2584380dec4c9036cfdc4a28d6c3d1ab9c 1996366df42bf5c89e7f2e74a8871f247e4693a3
* [x] #3719 f5798fd1f9362e2a56933c457ead9b85e9d97c79
* [x] #3720 2fd71469f60e56683723b9fddb6ae34ed9b79997
* [x] #3726 
  * prep: 464dad5ebfb787d4723a20b6cbf51c0a5a7ce12b 5e1589bf469be312e9af6ee98053936d55cfb7ce
  * fix: 8a4a7cc612253267b5ff97d3d52130953618c3c2
* [x] #3738
* [x] #3737
* [x] #3732

left out because ENOTREADY

* #3725
  * #3724 maybe also to complement pcre2 support?

**Comment by bsdphk** [comment]
We should consider adding #3737 to the list.

**Comment by nigoroll** [comment]
Note on #3732 :
it seems there was some misunderstanding yesterday about that merge, both @bsdphk and @mbgrydeland just said they want it in.

**Comment by nigoroll** [comment]
@mbgrydeland will look after remaining steps to release, thank you
