### ISSUE TITLE
Remote varnish service reload - Random failure on: Rejected 400 CLI communication error (hdr)

### ISSUE THREAD

**Issue by mf-fmbah** [varnishcache/varnish-cache#3741]
I am currently seeing intermittent behaviour when running a `service varnish reload` remotely from a ci env(Jenkins|github action). Basically sometimes the reload happens successfully, but in most cases it fails with below error message 

```ruby 
Rejected 400
CLI communication error (hdr)
Loading vcl from ../default.vcl
Current running config name is 
Using new config name reload_2021-11-22T12:24:40
Rejected 400
CLI communication error (hdr)
varnishadm -S ../secret -T 127.0.0.1:6082 vcl.load failed
``` 

Current versions of OS and varnish version 
```ruby 
varnishd (varnish-4.1.4 revision 4529ff7)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
```

```ruby
CentOS release 6.8 (Final)
```

Any suggestions and help will be appreciated

**Comment by Dridi** [comment]
You are running the 4.1 branch (not even the latest 4.1 release) that is no longer supported on an operating system that is also no longer supported. You should first upgrade to at least CentOS 7 and Varnish 6.0 LTS.
