### ISSUE TITLE
Why does Varnish remove If-None-Match from the bereq

### ISSUE THREAD

**Issue by ha-douken** [varnishcache/varnish-cache#3750]
I want to use conditional requests with my backend. But when putting Varnish between client and my backend I can see that the If-None-Match header does not exist on the bereq. It does exist on the req.

I guess I can easily add it using VCL but I wonder what the reason could be to deliberately remove it, maybe it will convince me to not use conditional requests with varnish.

* Version used: varnish-6.4.0
* Operating System and version: current varnish docker image

**Comment by Dridi** [comment]
As stated by the issue template, we don't use github for general questions. This is probably a cache miss, so Varnish has nothing to revalidate, and the revalidation is between Varnish and the client anyway if `If-None-Match` was supplied by the client.

**Comment by gquintard** [comment]
Grace will also do the trick. But the fundamental reason is: if you asked
varnish to cache and it doesn't know anything about the object, it can't
send a conditional response as that could lead to an empty response body

**Comment by ha-douken** [comment]
Oh, right. The async request in the "grace phase" also includes the revalidation headers.

If Varnish does not know about the object (does not have it in cache) I guess it cannot send conditional requests because it does not have them.

It cannot pass it from the client req to the bereq for multiple reasons, I'd say. Starting with the fact that there is no global definition of how to interpret the E-Tags value. "abc124" might match different things on different servers. I think the values can always only be a contract between a client with exact one server.

**Comment by gquintard** [comment]
Usually, the `e-tag` header is a hash of some sort, so it can be used with multiple servers, your own setup maybe different. However, if it is, does it really matter? Most of those conditional requests won't find a match, i.e. it will work as if the requests weren't conditional.

Maybe you can send an email to the [varnish-misc](https://varnish-cache.org/lists/mailman/listinfo/varnish-misc) mailing-list? It would be a more appropriate forum, and I'm sure the larger community will be happy to chime in
