### ISSUE TITLE
varnish crash when using disk storage with a lot of objects compared to available memory

### ISSUE THREAD

**Issue by ajoffre** [varnishcache/varnish-cache#3760]
## Expected Behavior

no crash varnish child when max number objects in cache (use file storage)
## Current Behavior

crash varnish child when max number objects in cache (use file storage)
When using file type storage Varnish uses memory to store the map key with its object. There is no control over memory usage by these keys!

With Docker when the memory limit is reached Docker you are the process that consumes too much memory, in our case the Varnish child process with the associated loss of cache.

## Possible Solution
There should be a system of cleaning objects when the memory limit is reached in order to avoid restarting.

## Steps to Reproduce (for bugs)

upload file attach varnishCrash.tgz
[varnishCrash.zip](https://github.com/varnishcache/varnish-cache/files/7728503/varnishCrash.zip)
```
unzip varnishCrash.zip
docker-compose up -d
ab -n500000 -r http://localhost:6081/
http://127.0.0.1:3000/d/9m4B3JrGk/varnish?orgId=1&from=now-15m&to=now&refresh=5s
login : admin/varnish
crash approximately every 2 minutes	
```
## Your Environment

* Version used: V6.0.8
* Operating System and version: linux ubuntu/Docker
* Source of binary packages used (if any)

**Comment by nigoroll** [comment]
quoting the [documentation](https://varnish-cache.org/docs/trunk/users-guide/storage-backends.html#file)

> The file backend stores objects in memory backed by an unlinked file on disk with _mmap_.

The _mmap_ implies here that varnish needs sufficient _virtual_ memory to accommodate the size of the storage file in addition to any memory. At this point, all the bundled storage engines use virtual memory, but other options might become available for open source varnish-cache soon.

That said, I can only speculate if this really is related to the crash, because you did not provide any crash related information. There should be some output in the container log, ideally a panic. Can you please share that?

Also, the documentation could be improved.

**Comment by ajoffre** [comment]
There is not a varnish crash. It is docker who kills the child process of varnish because it exceeds the authorized memory. and there is no way to limit this memory allowed on the varnish process.

**Comment by nigoroll** [comment]
Yes, this is what I am saying.

**Comment by ajoffre** [comment]
ok, but there could be a mechanism to clean up the 'mmap' on a memory threshold to prevent the process from getting killed?

**Comment by nigoroll** [comment]
This is not how mmap works.

**Comment by ajoffre** [comment]
Thank you for response.
Alexandre

**Comment by Dridi** [comment]
The only limit you can set in Varnish is for the contents of storage backends, so the rest of the memory footprint (data structures, cache metadata, loaded VCLs, socket buffers, shared memory etc) comes in addition to the limit when storage is full.

There is such a feature with Varnish Enterprise but having a global limit is currently not possible with Varnish Cache.

**Comment by nigoroll** [comment]
FTR, on the doc change: I deliberately did not want to get into the details of `setrlimit()` and whether or not `ulimit -v` applies to child processes or not, just wanted to give a pointer for interested readers. I will not feel offended if anyone rewrites that that section again.
