### ISSUE TITLE
'sp' undeclared

### ISSUE THREAD

**Issue by kuznetcoff777** [varnishcache/varnish-cache#3778]
I have an old config from centos5 - varnish-3
I converted config via this https://github.com/fgsch/varnish3to4
Now, when i start varnish-docker   latest such error appears:

```
Error:
Message from C-compiler:
vgc.c: In function 'VGC_function_vcl_backend_response':
vgc.c:2037:41: error: 'sp' undeclared (first use in this function)
 2037 |             l_lm = TIM_parse(VRT_GetHdr(sp, HDR_BERESP, "\016Last-Modified:"));
      |                                         ^~
vgc.c:2037:41: note: each undeclared identifier is reported only once for each function it appears in
vgc.c:2037:45: error: passing argument 2 of 'VRT_GetHdr' makes pointer from integer without a cast [-Werror=int-conversion]
 2037 |             l_lm = TIM_parse(VRT_GetHdr(sp, HDR_BERESP, "\016Last-Modified:"));
      |                                             ^~~~~~~~~~
      |                                             |
      |                                             int
[238 lines truncated]
Running C-compiler failed, exited with 1
VCL compilation failed

```

I need to put Expires header since some time form LastModified (for example, file appeared at x time, and i need expires +300s from that time and no more)

**Comment by Dridi** [comment]
Do you have inline C in your VCL? You should get a proper conversion instead of trying an automated process.

You can try to get some help from professionals if you have no Varnish experience.

https://varnish-cache.org/business/index.html
