### ISSUE TITLE
Feat: Skip compilation of VCL/SO when provided file is already a .so

### ISSUE THREAD

**Issue by leehambley** [varnishcache/varnish-cache#3781]
We maintain a fork of Varnish at ~6.6.1 and one of our custom patches is to bypass the attempted compilation of a provided file when provided with `varnishadm vcl.load <file>` because we have already compiled our VCLs into shared objecs ahead of time as part of a build pipeline.

Would such a patch be welcome upstream? Our current implementation begins with an extra boolean argument to `mgt_new_vcl` and new entrypoint for the varnishadm CLI. I would propose cleaning our patch so that the `vcl.load` remains the entrypoint, however an early detection for a symbol on the file is done, checking if it's a well-formed SO using the existing routines that are used when loading SOs via other paths.

Our motivation here with this early PR to ask permission/approach is in order that we can upstream what we think are valuable changes, and give-back to the project that which is deemed mutually beneficial, and also develop some experience with how to be good citizens and contribute back.

----

Questions:

 - Would such a contribution be welcome?
 - Are the broad strokes of the approach outlined (detect well-formed SOs and bypass the compiler phase) a good approach?

**Comment by nigoroll** [comment]
Can you please explain which of your needs could not be fulfilled by simply setting `cc_command` to some tool/script which just puts in place your pre-compiled `.so`?
Regarding safety, `varnishd` already attempts a test load in a separate process before actually loading the shared object.

**Comment by leehambley** [comment]
Hi @nigoroll thanks for the lightening fast answer ⚡ 

> Can you please explain which of your needs could not be fulfilled by simply setting cc_command to some tool/script which just puts in place your pre-compiled .so?

Good question, I'm new to the team who already had this patch in place, so I'm not familiar with the history. Setting that flag seems like it might alleviate the need for this patch at all.

> Regarding safety, varnishd already attempts a test load in a separate process before actually loading the shared object.

Indeed, I meant that those same routines (checking for the presense of the specific SO data symbol, for e.g) might be used to _conditionally_ compile.

---

So, this seems like an unwise contribution to make in the first instance, as it's redundantl; but in general are "Issues" framed as questions about the welcomeness of potential patches the right way to do it, or is it preferred to attend the weekly IRC office-hours bug wash?

LG aus HH nord,

**Comment by nigoroll** [comment]
So I suggest you see how far you can get with using `cc_command` instead of your patch. It should also be possible to conditionally compile, you are free to do whatever you want in `cc_command`,  `varnishd` just expects a working VCL `.so` when the command returns without error.

In general, we prefer to use github issues only for actual issues, but I think we are not too dogmatic about it. What we really do not want to see are general user questions. In general, the [dev mailing list](https://varnish-cache.org/lists/mailman/listinfo/varnish-dev) and `#varnish-hacking` on irc.redpill-linpro.com are preferred for general discussion.

Greetings from Hohenfelde
