### ISSUE TITLE
Wrong Error Message and wrong Range Test

### ISSUE THREAD

**Issue by araneolus** [varnishcache/varnish-cache#3786]
In the file bin/varnishd/cache/cache_range.c in line 296 there is an error message 'Unexpected content-range header'. Shouldn't it 'Unexpected range header' at this point?
In addition, the error always leads to an error if no range header is contained in the response, since the function 'http_GetRange' returns zero (there is no error) but the variables 'rlo' and 'rhi' are then always returned with -1, which leads to this error message.
This happens if I start varnishd with the option 'http_range_support=on'

**Comment by Dridi** [comment]
> Shouldn't it 'Unexpected range header' at this point?

The if statement before leaves the function when there is no content-range header in beresp. So when this error message is emitted we have a content-range header, but not a valid range header (or an invalid one) in bereq.

> In addition, the error always leads to an error if no range header is contained in the response

The range header is supposed to be in the request. If there is none and yet the response advertises a content-range, that's an error.

> This happens if I start varnishd with the option 'http_range_support=on'

Yes, this check is only enforced when range support is enabled.

Could you please a concrete example of a failing backend fetch that you think should have succeeded?

**Comment by araneolus** [comment]
You are right. I have read the rfc again EXACTLY and yes a range header must be sent so that a content-range may be contained in the response.
The application is probably not reacting correctly.
But now I have to ask another stupid question, because I didn't find this in the rfc: Shouldn't a status code 206 be returned for a reply with content-range and shouldn't this header be ignored for a reply with the status code 200?

**Comment by Dridi** [comment]
> Shouldn't a status code 206 be returned for a reply with content-range and shouldn't this header be ignored for a reply with the status code 200?

I don't have time right now to spend brain cycles on deciphering the RFC for this scenario, but you can work around this problem directly in VCL:

```vcl
sub vcl_backend_response {
        if (beresp.status != 206) {
                unset beresp.http.content-range;
        }
}
```

It's documented in the release notes: https://varnish-cache.org/docs/7.0/whats-new/upgrading-7.0.html#range-requests

**Comment by araneolus** [comment]
Perfect !!
I will do this.
