### ISSUE TITLE
Configure/disable default Via header

### ISSUE THREAD

**Issue by Tristan971** [varnishcache/varnish-cache#3794]
Hi, I'd like the default `Via` header added by Varnish to be either disabled or configurable. (see context section for the long story of why).

However, Varnish's use of a hardcoded value is getting in the way and will require me to iterate over all Via headers to find the right one to replace, which is rather suboptimal.

## Expected Behavior

`varnishd` supports a parameter/feature/? to disable automatic adding of `Via` header by Varnish

## Current Behavior

The following line adds a hardcoded `Via` header which isn't trivial to just unset+set in case the upstream response also has `Via` headers.

https://github.com/varnishcache/varnish-cache/blob/5424da941529503c724911d8141e6824db756f88/bin/varnishd/cache/cache_req_fsm.c#L170

## Possible Solution

I see 2 possible approaches:

1. as listed above: allow disabling the automatic adding of the header

2. Allow parameterizing automagically, something like `Via: 1.1 ${gethostname} (Varnish/7.1)` maybe

imo 2. sounds like a can of worms and an invitation to a pointless debate on whether the host name is a valid choice, and if not how to specify where to get it from instead. The approach in 1. seems way less opinionated and lets the user pick whatever makes them happy.

## Steps to Reproduce (for bugs)

N/A

## Context

Our setup has Varnish instances in multiple places, notably both at the edge and within our internal network.

In this case we want to cache 2 types of data:
- ESI sub-responses
- Assembled responses

Given our ESI target service is not deployed at the edge, assembling all from the edge involves paying the high latency cost twice (once for the base request, and once for the ESI request).

A simplified view of our approach (and why we use 2 Varnish tiers) is:

```
                                             /-> base req upstream (short TTL + has a Via header of its own)           
Edge Varnish --- high lat ---> LB -> Varnish
                                             \-> ESI req upstream (short TTL)
```

This allows us to pay the high latency cost only once.

However, in the current situation what we'll end up with is duplicated `Via: 1.1 varnish (Varnish/7.1)` which doesn't help a ton for tracking things as opposed to for example:
- `Via: 1.1 varnish edge (Varnish/7.1)`
- `Via: 1.1 varnish $servicename (Varnish/7.1)`

Additionally, the edge's Varnish sees a Via header added by the internal load-balancer (and potentially some other intermediates), so it can get rather tricky to find out which one was just added and should be replaced vs. which ones were preexisting from upstream and should be preserved.

It's possible to do something with an approach around saving them in something like `beresp.http.X-Original-Via` perhaps but it sounds just overall unnecessarily convoluted.

Finally, a nitpicky argument is to be able to remove the Varnish version as per general best practices when it comes to what headers should disclose or not to end-users for security purposes.

## Your Environment

Mostly irrelevant but a mix for direct install (ie APT) and k8s/docker.

---

Also, apologies if this would have belonged more somewhere else (like the mailing list)

**Comment by nigoroll** [comment]
It should be possible to do all you are asking for in vcl.

As a starting point:
```
sub vcl_deliver {
  set resp.http.Via = "...";
}
```

But please be advised that we do not use github issues for user support, as explained in the template.

> Also, apologies if this would have belonged more somewhere else (like the mailing list)

Yes. see [Getting Help](https://varnish-cache.org/support/index.html

If you believe that VCL does not offer full control, please explain that problem and reopen this issue.

**Comment by Dridi** [comment]
Reopening, see #3829 for a configurable Via header.

**Comment by Tristan971** [comment]
Oh, didn't expect this, and forgot to follow-up at the time. Thanks, that sums up (in a much clearer and RFC-based way) what I wanted.

I'm not sure what the policy is for closing issues on the repository, but 👍 as far as I'm concerned

**Comment by Dridi** [comment]
It should be closed automatically if the pull request is merged.

If you can, please build and run the branch from #3829 to give it a try and share some feedback there.
