### ISSUE TITLE
Read only file system

### ISSUE THREAD

**Issue by vashian** [varnishcache/varnish-cache#3800]
Hi.
I've tried to use **Varnish** image and start my container with a read-only filesystem.
Here's the error log:

```
Assert error in vju_make_workdir(), mgt/mgt_jail_unix.c line 283:
  Condition((chown(dname, -1, vju_gid)) == 0) not true.
  errno = 30 (Read-only file system)
```

CMD ["-f", "/tmp/user.vcl"]

If I run my container with a writable filesystem everything seems ok.
I don't know where **Varnish** wants to change...

**Comment by bsdphk** [comment]
Varnish cannot run without access to a writable filesystem for the workdir.

For one thing C-compilers wants to read their source (the compiled VCL) from files.

Suggest you consider a RAM disk or TMPFS filesystem as workdir.
