### ISSUE TITLE
[RFC] caching 206 response could be easier, maybe?

### ISSUE THREAD

**Issue by gquintard** [varnishcache/varnish-cache#3823]
This ticket applies to all current versions of Varnish.

I have a use-case where we want to cache 206 response, adding the `range` header to the hash (that sort of tomfoolery is actually ok as we trust our users in this context), and while VCL allows me to make things work, maybe I could save a few lines if Varnish was a bit more accommodating?

First, on the way in, I need to save `req.http.range` because it won't survive the copy into `bereq`. That's fair, we usually want the full object in cache. But maybe, in VCL, we could "protect" some headers from being scrubbed when creating `bereq`?

Second I also need to move `beresp.http.content-range` out of the way, otherwise Varnish considers it an error to have a `CR` header without an incoming `range` header. The frustrating point is that I DO have an incoming `range` header, but it's stored in `bereq` and not `bereq0` which is the object being checked.

I guess the issue on this one is that we only have a choice between `bereq0` and `bereq` and neither is an accurate depiction of what was sent to the backend.

mandatory vtc, even though it's missing most safeguards for the sake of readability:

``` vtc
varnishtest "content-range header"

server s1 {
        rxreq
        expect req.http.range == "bytes=5-7"
        txresp -status 206 -hdr "Content-Range: bytes 5-7/10" -body "567"
} -start

varnish v1 -vcl+backend {
        sub vcl_recv {
                set req.http.x-range = req.http.range;
        }

        sub vcl_hash {
                hash_data(req.http.x-range);
        }

        sub vcl_backend_fetch {
                set bereq.http.range = bereq.http.x-range;
        }

        sub vcl_backend_response {
                if (beresp.status == 206) {
                        set beresp.http.x-content-range = beresp.http.content-range;
                        unset beresp.http.content-range;
                }
        }

        sub vcl_deliver {
                if (resp.status == 206) {
                        set resp.http.content-range = resp.http.x-content-range;
                }
        }
} -start

varnish v1 -cliok "param.set debug +syncvsl"

client c1 {
        txreq -hdr "range: bytes=5-7"
        rxresp
        expect resp.http.content-range == "bytes 5-7/10"
} -run
```

Not sure this will be recognized as a bug, but I thought I'd raise that one up, just in case there was a nicer solution.

**Comment by Dridi** [comment]
Could you make another test case that turns it off?

**Comment by Dridi** [comment]
> varnish v1 -cliok "param.set http_range_support true"

That's the opposite of disabling it :-/

**Comment by gquintard** [comment]
...well, yes, ok, you win this round, but I'll be back!

it does work, so I'm confused about what's happening in prod then... Anyway, looks like I can close that again. Thanks @Dridi
