### ISSUE TITLE
[doc] Minor INSTALL inaccuracy for trunk builds

### ISSUE THREAD

**Issue by Tristan971** [varnishcache/varnish-cache#3831]
## Expected Behavior
INSTALL is accurate for trunk too

## Current Behavior
INSTALL suggests running `configure` but it's not present in trunk and requires running autoreconf -i first in that case (or rather autogen.sh but it seems like it's about to be removed).

## Possible Solution
A note about that difference "when building from trunk" in the INSTALL file, maybe?

## Context
I'm not too familiar with the C world's build systems, besides running cmake or configure-make-makeinstall so it wasn't automatically obvious to me.

Ended up figuring it out by looking at the CI jobs in this case.

I'd happily MR something for it, but it's so minor (as in barely more than a typo) that it seems more reasonable to have it bundled by a core maintainer in whatever the next doc-related commit is instead.

## Your Environment
N/A

**Comment by nigoroll** [comment]
A distribution tarball as created

**Comment by nigoroll** [comment]
Oh and INSTALL actually contains

> If you obtained the sources directly from the Git repository, you will need to run autogen.sh first to create the configure script.

But anyway, I will make it more concise

**Comment by Tristan971** [comment]
Well I meant to refer to trunk as in "upon a git clone" but indeed it is there... I'm not sure how I managed to miss it even while writing this issue... Sorry. 🤦

**Comment by Dridi** [comment]
Thank you @nigoroll for taking care of this, and thank you @Tristan971 for going through the trouble to try #3829!
