### ISSUE TITLE
Support for abstract sockets on Linux?

### ISSUE THREAD

**Issue by jlecour** [varnishcache/varnish-cache#3863]
Hi, I've just heard about abstract UNIX sockets on Linux.

I've found a few pieces of software that support them (HAProxy, curl…) so I wondered if I could use one of them for communication between HAProxy and Varnish instead of the typical UNIX sockets that I've been using.

I've tried to simply add an `@` before the `/` at the beginning of tha socket path, but Varnish refuses to start.

Thanks.

**Comment by bsdphk** [comment]
I'm not sure I see much point, but if somebody writes a patch...

**Comment by nigoroll** [comment]
> I've tried to simply add an @ before the / at the beginning of (the) socket path, but Varnish refuses to start.

With the patch linked above you can now do that

**Comment by jlecour** [comment]
Hi,

> I'm not sure I see much point

@bsdphk If I understand correctly, abstract sockets do not involve any filesystem interaction. That's why it can be a good thing to support. I've also heard about some performance gains (probably related to the previous point).

> With the patch linked above you can now do that

I wasn't asking for it, just wondering if this was possible or not.
But thanks a lot @nigoroll for the work !

I am not able to try this patch until it is releases and packaged, so I'll trust you.

If you think it's done, you can close the issue.
