### ISSUE TITLE
Could not rmdir 'vext_cache': No such file or directory 

### ISSUE THREAD

**Issue by iammeken** [varnishcache/varnish-cache#3874]
varnishd -C -f /etc/varnish/default.vcl always ends with this error as the last line, but vcl is ok and varnish runs ok.

varnish 7.2.1
ubuntu 22.04

**Comment by Dridi** [comment]
After a fresh build of the master branch:

```
$ bin/varnishd/varnishd -C -f $PWD/bin/varnishd/builtin.vcl 
Could not delete 'vcl_boot.1669879551.982733/vgc.sym': No such file or directory
Message from VCC-compiler:
No backends or directors found in VCL program, at least one is necessary.
Running VCC-compiler failed, exited with 2
VCL compilation failed
Could not rmdir 'vext_cache': No such file or directory
```

**Comment by nigoroll** [comment]
I can confirm that these issues exist, and I admit to have ignored them for irrelevance.
but, true, we should adress them.

**Comment by Dridi** [comment]
I already put @walid-git on it.

**Comment by DavidRadan** [comment]
Hello ,
I hope you are well !
We have the sam issue with the latest version of varnish **varnish-7.2.1-1.el8.** RPM version .
 **Could not rmdir 'vext_cache': No such file or directory**
I wonder if there is a new RPM that fixes this problem ?
Going back to older versions expose us to security issues .

Versions Installed :

varnish-7.2.1-1.el8.x86_64.rpm
varnish-devel-7.2.1-1.el8.x86_64.rpm

Thanks 
Dave

**Comment by Dridi** [comment]
The vext_cache error bug fix was merged but is not present in a release.

You can safely ignore it.

The reason why this ticket is still open is the second error message from https://github.com/varnishcache/varnish-cache/issues/3874#issuecomment-1333322965 and I think there was an open question regarding how inconsistently jail-remove things.

We should revisit this error message:
> Could not delete 'vcl_boot.1669879551.982733/vgc.sym': No such file or directory

**Comment by DavidRadan** [comment]
Dear Dridi ,
Many thanks for your reply !
The thing is that we are unable to start/run  the varnish , varnish fails to start simply maybe there is a workaround ?
Regards,
Dave

**Comment by gquintard** [comment]
Hi @DavidRadan,

There's probably a bit more to the error than just this message. We can help figure things out, however we try to keep the github issues for confirmed bugs rather than user help. May I ask you to join us on one of the support channels so we can discuss this? (https://varnish-cache.org/support/)

**Comment by DavidRadan** [comment]
Hi @gquintard 
Thanks for the offer we will consider that ofcourse .
we have decided not to upgrade it seems that version ( 7.2.1 ) is a buggy version , We have tested this on 3 machines with diffirent Linux versions , the older versions work ok but they suffer from security issues .
Regadlress maybe we will go with latest LTS version of varnish which if i'm not mistaken is 6.0.11 ( up to date ) .
Again thanks to you all for your time  .

Warm Regards,
Dave

**Comment by DavidRadan** [comment]
Hi to all ,
We have managed to find the root of the problem , I just wanted to to update this ticket .
In all our tests it seems that SELINUX was enabled , When selinux is enabled varnish 7.2.1 won't start at all , After disbaling the SELINUX varnish started , We are running tests on this version at moment .
I hope this will help  others that might come accross this error : 

**Error : Could not rmdir 'vext_cache': No such file or directory**

Solution / workaround ( at least in our case )  :
Disabling selinux .

Thanks for your help 
Dave

**Comment by Dridi** [comment]
Please open a separate github issue, I will look at the SELinux problem with you.
