### ISSUE TITLE
make check failed about varnish-cache@7.2.1 on openEuler_aarch64

### ISSUE THREAD

**Issue by Tom-python0121** [varnishcache/varnish-cache#3877]
Hello，I meet a problem:make check failed about varnish-cache@7.2.1 on openEuler_aarch64.
### Steps to reproduce the issue

```console
[root@localhost varnishtest]#make -j126 check
……
PASS: tests/v00045.vtc
PASS: tests/u00003.vtc
PASS: tests/u00010.vtc
PASS: tests/t02016.vtc
PASS: tests/u00006.vtc
PASS: tests/c00080.vtc
PASS: tests/u00009.vtc
PASS: tests/r02270.vtc
PASS: tests/v00006.vtc
PASS: tests/r01490.vtc
PASS: tests/v00003.vtc
FAIL: tests/u00011.vtc
============================================================================
Testsuite summary for Varnish 7.2.1
============================================================================
# TOTAL: 820
# PASS:  790
# SKIP:  29
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See bin/varnishtest/test-suite.log
Please report to varnish-dev@varnish-cache.org
============================================================================
```
test-suite.log as:
[test-suite.log](https://github.com/varnishcache/varnish-cache/files/10163497/test-suite.log)
## Your Environment

* Version used:7.2.1
* Operating System and version: `Linux localhost.localdomain 4.19.90-2003.4.0.0036.oe1.aarch64 #1 SMP Mon Mar 23 19:06:43 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`
* Source of binary packages used (if any)

**Comment by Dridi** [comment]
It might simply be a flaky test under load, and you run the test suite with quite the parallelism.

Unless the test case consistently fails a `make recheck` we can probably close this one. The test log shows hints of timing issues.

**Comment by Tom-python0121** [comment]
@Dridi When I run the make check single thread test, the same error is reported.Is there any way to solve this problem?

**Comment by Dridi** [comment]
Can you please run the test again and share the test log after making this change?

```diff
diff --git i/bin/varnishtest/tests/u00011.vtc w/bin/varnishtest/tests/u00011.vtc
index 1561ad1e4..a41509576 100644
--- i/bin/varnishtest/tests/u00011.vtc
+++ w/bin/varnishtest/tests/u00011.vtc
@@ -20,6 +20,7 @@ process p1 -expect-text 0 1 "Type 'quit' to close CLI session."
 
 # expect a status in interactive mode (after a banner)
 process p1 -write "pin\t\r"
+process p1 -screen_dump -write "quit\r" -wait
 process p1 -expect-text 12 1 "200         "
 process p1 -expect-text 13 1 PONG
```

It appears that the output is off by one line on your system.

**Comment by Dridi** [comment]
I edited the diff above, there was a tiny mistake.

**Comment by Tom-python0121** [comment]
@Dridi ok,I will try it.

**Comment by Tom-python0121** [comment]
@Dridi The same error is still reported after making this change.
### Steps to reproduce the issue

```console
……
PASS: tests/v00003.vtc
FAIL: tests/u00011.vtc
============================================================================
Testsuite summary for Varnish 7.2.1
============================================================================
# TOTAL: 820
# PASS:  790
# SKIP:  29
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See bin/varnishtest/test-suite.log
Please report to varnish-dev@varnish-cache.org
============================================================================
```
test-suite.log:
[test-suite.log](https://github.com/varnishcache/varnish-cache/files/10174147/test-suite.log)

**Comment by Tom-python0121** [comment]
@Dridi It's useful,
[root@localhost src]#make -j126 check
……
PASS: tests/std_c00001.vtc
PASS: tests/blob_b00008.vtc
PASS: tests/directors_c00015.vtc
PASS: tests/directors_s00000.vtc
============================================================================
Testsuite summary for Varnish 7.2.1
============================================================================
# TOTAL: 78
# PASS:  78
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[3]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/vmod'
make[2]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/vmod'
make[1]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/vmod'
Making check in etc
make[1]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/etc'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/etc'
Making check in doc
make[1]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/doc'
Making check in graphviz
make[2]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/doc/graphviz'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/doc/graphviz'
Making check in sphinx
make[2]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/doc/sphinx'
make  check-am
make[3]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/doc/sphinx'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/doc/sphinx'
make[2]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/doc/sphinx'
make[2]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/doc'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/doc'
make[1]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/doc'
Making check in man
make[1]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/man'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/man'
Making check in contrib
make[1]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/contrib'
make  check-TESTS
make[2]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/contrib'
make[3]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/contrib'
============================================================================
Testsuite summary for Varnish 7.2.1
============================================================================
# TOTAL: 0
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[3]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/contrib'
make[2]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/contrib'
make[1]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src/contrib'
make[1]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src'
make  check-TESTS
make[2]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src'
make[3]: Entering directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src'
SKIP: tools/magic_check.sh
============================================================================
Testsuite summary for Varnish 7.2.1
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  1
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[3]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src'
make[2]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src'
make[1]: Leaving directory '/home/stage/root/spack-stage-varnish-cache-7.2.1-efb3rbj5zdsasznuq63iegksfluotxct/spack-src'
