### ISSUE TITLE
Temporarily blacklisting a backend for a "backend session"

### ISSUE THREAD

**Issue by delthas** [varnishcache/varnish-cache#3880]
Is there a way to tell Varnish to try using backends only once per backend request "session"?

The use case is I have multiple static backends and directors (including dyanmic backends, using libvmod-directors), and I'd like to try fetching from a backend, then try again on *another one* if I get a 404, etc.

Once I get a 404 for a particular file I'm sure the backend is not going to be able to serve that file in the near-future, so Varnish should ignore that backend for the remainder of the backend session.

This is different from probes because even though my instances can be healthy, for some reason they could be unable to serve a particular file for a short while.

---

Currently i'm wrapping my backends with saintmode and (ab)using saintmode.blacklist(1s) to emulate this behavior, but it's kinda hacky
because it operates with a duration rather than per-"backend session".

ie I'm basically doing (ignore the syntax errors, this is pseudocode from memory):
```
sub vcl_init:
  new sb1 = saintmode.backend(b1, 10000);
  new sb2 = saintmode.backend(b2, 10000);
  // ...

sub vcl_backend_response:
  if beresp.status == 404:
    saintmode.blacklist(1s);
    retry;
  // ...
```

Also for dyanmic backends created with libvmod-dynamic, i cannot just wrap the dynamci backends created by libvmod-dynamic with
saintmode. i can only saintmode.blacklist the whole backend, which is not what i want if there are multiple dyanmic backends created by
the director.

```
sub vcl_init:
  new b1 = directors.director(/* ... */);
  // ...

sub vcl_backend_request:
  set bereq.backend_hint = b1.backend("host-resolving-to-multiple-ips.example.com");

sub vcl_backend_response:
  if beresp.status == 404:
    saintmode.blacklist(1s); // -> Won't work because the backend elected by directors is not a saintmode backend.
    retry;
  // ...
```

---

So I was about to hack libvmod-dynamic to wrap its backends created with VRT_new_backend with saintmode, but i'm not sure if it's doable to link libvmod-directors against libvmod-saintmode.

And this all feels very hacky overall for something that looks simple. Any way to do this?

**Comment by Dridi** [comment]
The answer is no.

For general questions, please use the misc mailing list as indicated in the issue template.
