### ISSUE TITLE
Header names case

### ISSUE THREAD

**Issue by jlecour** [varnishcache/varnish-cache#3883]
This is not a bug, but a question to prevent bugs in client/servers ;)

As fas as I am concerned, the HTTP spec says that header names must be treated as case-insensitive.
HTTP/2 is even normalizing header names in lowercase.

The ` varnishd -x builtin` command shows (verified with various verisons of Varnish up to 7.1) that Varnish is getting/setting headers based on lowercase or uppercase keywords.

A few examples :

```
sub vcl_req_host {
	if (req.http.host ~ "[[:upper:]]") {
		set req.http.host = req.http.host.lower();
	}
        […]
}
sub vcl_beresp_cookie {
	if (beresp.http.Set-Cookie) {
		call vcl_beresp_hitmiss;
	}
}
sub vcl_builtin_synth {
	set resp.http.Content-Type = "text/html; charset=utf-8";
	set resp.http.Retry-After = "5";
	set resp.body = {"[…]"};
}
```

I am wondering if there is a technical reason for this disparity, or if it's just something that has not been completely changed in the code/docs ?

Also, can I use "setters" like `set resp.http.content-type` in place of `set resp.http.Content-Type` and "getters" like `req.http.cookie` in place of `req.http.Cookie` ?

Thanks.

**Comment by Dridi** [comment]
For general questions, please use the misc mailing list as indicated in the github issue template. It is also mentioned that we only want issues for actual bugs.

The answer is that VCL was historically designed when HTTP/1 was the only player in town and case sensitivity of the header names is enforced at the h2 protocol level.

**Comment by Dridi** [comment]
Unrelated, I couldn't attend le Capitole du Libre this year, I hope your talk was recorded.

**Comment by jlecour** [comment]
I'm sorry I didn't read the instructions properly and added some noise here.
I'll use the mailing list to continue the discussion. Thanks for the polite reminder.

> Unrelated, I couldn't attend le Capitole du Libre this year, I hope your talk was recorded.

It was recorded, but it's not available yet.
I've also given a different talk including Varnish, at HAProxyConf. The video should also be released soon.
