### ISSUE TITLE
Make An API request to fetch data and embedd it into response header to client

### ISSUE THREAD

**Issue by Aadarsh-Verma** [varnishcache/varnish-cache#3893]
I want to send a cached page back to the user But the problem is that I need to generate a VISITOR_ID for every user and 
send it back to the user through headers , so I need to send an API call from varnish to fetch VISITOR_ID and then append it to the response

We were earlier using Akamai and we were able to implement this using edge workers present there,
I want to know if such a thing is possible to do in varnish or not.

Thanks in Advance

**Comment by gquintard** [comment]
we try to keep the github issue for bugs, so I'm closing this one, encouraging you to join us on one of the help channels described here: https://varnish-cache.org/support/

most probably, you'll want to use this vmod https://github.com/gquintard/vmod_reqwest , but let's continue that discussion on mail, discord or IRC
