### ISSUE TITLE
Make dependency missing in vmod/

### ISSUE THREAD

**Issue by bsdphk** [varnishcache/varnish-cache#3928]
### Current Behavior

    critter phk> cd vmod
    critter phk> make clean >& /dev/null
    critter phk> make |& tail -10
    touch vcc_debug_if.c
      CC       libvmod_debug_la-vmod_debug.lo
    vmod_debug.c:45:10: fatal error: 'VSC_debug.h' file not found
    #include "VSC_debug.h"
             ^~~~~~~~~~~~~
    1 error generated.
    *** Error code 1
 
    Stop.
    make: stopped in /critter/Varnish/trunk/varnish-cache/vmod
    critter phk> make -k >& /dev/null
    critter phk> make |& tail -10
      CC       libvmod_debug_la-vmod_debug.lo
      CCLD     libvmod_debug.la

There seems to be neither a dependency on ``VSC_debug.h`` nor any make-rule to produce it, should such a dependency have existed.

### Varnish Cache version

Trunk

### Operating system

FreeBSD-Current.

**Comment by Dridi** [comment]
Please give https://github.com/varnishcache/varnish-cache/pull/3929 a try.

**Comment by fgsch** [comment]
Seeing the same under macos and ubuntu.

**Comment by Dridi** [comment]
Did you try #3929?

**Comment by fgsch** [comment]
No, I haven't as increasing the number of (make) jobs seems to workaround it and it initially was difficult for me to test the PR. I might try it in a different box when I find some time.
