### ISSUE TITLE
Deb package for debian bookworm release

### ISSUE THREAD

**Issue by Juanchimienti** [varnishcache/varnish-cache#3951]
### Expected Behavior

Install varnish on debian stable using the packagecloud varnish repository

### Current Behavior

No package it's available for the current debian stable version. 

Looking at https://packagecloud.io/app/varnishcache/varnish73/ I don't see a package for the current debian stable release 12 named bookworm. 

### Context

I understand that debian 12 was released after the last varnish release. My concern is if there is a timeline for a varnish pkg release that supports debian 12. 

I tried to ask this on the IRC but the channel appears to be invite only.

### Operating system

debian12

**Comment by gquintard** [comment]
I'll put a note either here on on the website, but in the meantime: https://varnish-cache.org/lists/pipermail/varnish-misc/2020-August/026926.html
