### ISSUE TITLE
VCC assert on VCL with invalid HTTP header

### ISSUE THREAD

**Issue by delthas** [varnishcache/varnish-cache#3960]
### Expected Behavior

VCC fails with a friendly error message.

### Current Behavior

VCC fails with:
```
Message from VCC-compiler:
Assert error in vcc_Eval_Var(), vcc_expr.c line 373:
  Condition(sym->kind == SYM_VAR) not true.
Running VCC-compiler failed, signal 6, core dumped
VCL compilation failed
```

### Steps to Reproduce (for bugs)

Compile the following VCL:
```
vcl 4.1;
backend default none;
sub vcl_recv {
    if (req.http.0) {}
}
```

### Context

I had old test cases laying around and found them failing when upgrading Varnish. I understand Varnish is now stricter wrt HTTP headers since a recent upgrade. I'll update the test case, but it might be clearer for users to have an error message rather than an assert.

### Varnish Cache version

7.3.0

**Comment by Dridi** [comment]
> I understand Varnish is now stricter wrt HTTP headers since a recent upgrade.

Yes and no.

There is stricter validation but "0" is a valid header name, but an invalid VCL symbol name. You can quote such header names, so we actually have better support for the HTTP grammar for header fields.

The following VCL should compile just fine:

```vcl
vcl 4.1;
backend default none;
sub vcl_recv {
        if (req.http."0") {}
}
```

Thank you for your bug report!
