### ISSUE TITLE
varnish: Depends: libc6-dev but it is not installable

### ISSUE THREAD

**Issue by mboy1011** [varnishcache/varnish-cache#3970]
### Expected Behavior

I want to install varnish/jammy 7.3.0-1~jammy amd64 on my Ubuntu 22.04.2 LTS Server Unfortunately I couldn't install it due to: 
**The following packages have unmet dependencies:
 varnish : Depends: libc6-dev but it is not installable or
                    libc6.1-dev but it is not installable or
                    libc-dev
E: Unable to correct problems, you have held broken packages.**
![image](https://github.com/varnishcache/varnish-cache/assets/24217468/dd190089-a3f7-4b53-a7eb-f350fce1aa80)

I've already followed the step-by-step installation [here](https://packagecloud.io/varnishcache/varnish73/install#manual-deb) via the official manual instruction from Varnishcache.

### Current Behavior

The following packages have unmet dependencies:
 varnish : Depends: libc6-dev but it is not installable or
                    libc6.1-dev but it is not installable or
                    libc-dev
E: Unable to correct problems, you have held broken packages

### Steps to Reproduce (for bugs)

1.  sudo apt-get update
2.  sudo apt-get install debian-archive-keyring
3.  sudo apt-get install curl gnupg apt-transport-https
4.  mkdir -p /etc/apt/keyrings/
5.  curl -fsSL https://packagecloud.io/varnishcache/varnish73/gpgkey | gpg --dearmor > /etc/apt/keyrings/varnishcache_varnish73-archive-keyring.gpg
6. Create a file named: /etc/apt/sources.list.d/varnishcache_varnish73.list
7.  echo "deb [signed-by=/etc/apt/keyrings/varnishcache_varnish73-archive-keyring.gpg] https://packagecloud.io/varnishcache/varnish73/ubuntu jammy main \ndeb-src [signed-by=/etc/apt/keyrings/varnishcache_varnish73-archive-keyring.gpg] https://packagecloud.io/varnishcache/varnish73/ubuntu jammy main"
8.  sudo apt-get update
9. apt install varnish -y

### Context

To configure my Magento 2.4.6-p2 Instance to have a successful Full Page Cache using Varnish, which is advised for production servers, I just want to install it using the most recent version of libc6-dev where there's a recent security patch and depends on it.

### Operating system

Ubuntu 22.04.2 LTS

**Comment by nigoroll** [comment]
Because this is a packaging issue, I have moved it to https://github.com/varnishcache/pkg-varnish-cache/issues/166
