### ISSUE TITLE
VCC Panic with floating point number

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#3971]
### Expected Behavior

Parse the number 42.42e42 or emit a helpful error message

### Current Behavior

VCC Panic:
```
Assert error in vcc_lex_number(), vcc_token.c line 507:
  Condition(s == tl->t->e) not true.
```

### Context

VTC:
```
varnishtest "A number"

varnish v1 -vcl {
	backend proforma none;
	sub vcl_recv {
		set resp.http.foo = 42.42e42;
	}
} -start
```

**Comment by Dridi** [comment]
> Parse the number 42.42e42 or emit a helpful error message

Error message it is, exponent notation was dropped a while ago.
