### ISSUE TITLE
memory leak in function 'Sess_Start_Thread'

### ISSUE THREAD

**Issue by JoraGevorgyan** [varnishcache/varnish-cache#3986]
### Expected Behavior

when trying to [create a thread](https://github.com/varnishcache/varnish-cache/blob/75babde974509daaaed3ce81b4e2a568d0e1f37e/bin/varnishtest/vtc_sess.c#L182) there must be a double check and in case of failure it must free the allocated memory

### Current Behavior

the [allocated memory](https://github.com/varnishcache/varnish-cache/blob/75babde974509daaaed3ce81b4e2a568d0e1f37e/bin/varnishtest/vtc_sess.c#L172) may left w/o free in case of failure of 'pthread_create'

### Possible Solution

The solution is to check return value and free if a thread is not created

### Context

The memory leak is reported by a static analyzer tool developed at [CAST](https://www.linkedin.com/company/cast-center)

**Comment by daghf** [comment]
The OS is capable of reclaiming this memory just fine - doing a free here would be akin to sweeping the floors of a building that's about to be demolished.

Closing.
