### ISSUE TITLE
varnishd -C -f /usr/local/etc/varnish/default.vcl does not take in account custom storage settings

### ISSUE THREAD

**Issue by Johanhen** [varnishcache/varnish-cache#3987]
### Expected Behavior

varnishd -C -f /usr/local/etc/varnish/default.vcl

to complete succesfully

### Current Behavior

varnishd -C -f /usr/local/etc/varnish/default.vcl
 
Message from VCC-compiler:
Symbol not found: 'storage.disk'
At: ('/usr/local/etc/varnish/default.vcl' Line 24 Pos 30) -- (Pos 41)
        set beresp.storage = storage.disk;
-----------------------------############-

Running VCC-compiler failed, exited with 2
VCL compilation failed 

### Possible Solution

Make sure varnishd -C sees the custom config

### Steps to Reproduce (for bugs)

Create a name storage
-s mem=malloc,256M -s disk=file,/usr/local/var/varnish/varnish_storage.bin,10G"

Create config in vcl under sub vcl_backend_response
if (bereq.url ~ "^[^?].(xml|xz|zip)(?.)?$") {
        set beresp.storage = storage.disk;
    } else {
        set beresp.storage = storage.mem;
    }

run varnishd -C -f /usr/local/etc/varnish/default.vcl

It will error out. 

### Context

We can not check the syntax of the config file anymore.

### Varnish Cache version

varnishd (varnish-6.6.1 revision e6a8c860944c4f6a7e1af9f40674ea78bbdcdc66)

### Operating system

FreeBSD an ubuntu 22.04, i suspect all

**Comment by walid-git** [comment]
Can you try with : 
```
varnishd -C -f /usr/local/etc/varnish/default.vcl -s mem=malloc,256M -s disk=file,/usr/local/var/varnish/varnish_storage.bin,10G 
```

**Comment by Johanhen** [comment]
Sorry for the late reply, but yes that does work indeed.
