### ISSUE TITLE
vtc: We need to split test cases

### ISSUE THREAD

**Issue by dridi** [varnishcache/varnish-cache#4002]
It looks like circleci has lowered the CPU budget we get, and jobs running with ASAN are taking 1.5 the time they used to, and some tests are just plainly timing out on a regular basis:

- [ ] m00043.vtc
- [ ] r00962.vtc
- [ ] u00008.vtc (also it seems to leak to varnishtest's stdout)
- [ ] v00018.vtc
- [ ] v00020.vtc
- [ ] v00051.vtc
- [ ] blob_b00008.vtc
- [ ] r02262.vtc (this one looks different, the nested varnishtest times out)

**Comment by nigoroll** [comment]
SAAS 🤯

**Comment by dridi** [comment]
The problem occurs much less often, this may have been a transient problem on cci's infrastructure. Regarding slow sanitizer jobs, we have #4118 now.
