### ISSUE TITLE
Date header not updated in cached response?

### ISSUE THREAD

**Issue by zdenekdrahos** [varnishcache/varnish-cache#4014]
### Expected Behavior

It is clear, if date header is or is not updated in cached response.

### Current Behavior

Response `Date` header == `Date` header returned from backend. It might be ok, but I could not find any related change. [Old versions in changes.rst](https://github.com/varnishcache/varnish-cache/blob/111e4f3d2fdd151306a90b4ac050697f9a7c4d5d/doc/changes.rst#changes-from-111-to-112) describe different behavior

> Changes from 3.0.2 to 3.0.3 (2012-08-20)
> Fix a case where varnish didn't remove the old Date header and served it alongside the varnish-generated Date header. [Bug #1104](https://www.varnish-cache.org/trac/ticket/1104).

> Changes from 1.1.1 to 1.1.2
> Varnish will now correctly generate a Date: header for every response instead of copying the one it got from the backend (see [ticket #157](https://www.varnish-cache.org/trac/ticket/157)).

### Possible Solution

* If it is a bug, then varnish should return fresh `Date` header
* If it is a feature, then `Date` header needs better documentation

### Steps to Reproduce (for bugs)

```
varnishtest "Frontend HTTP cache - response date"

server s1 {
    rxreq
    expect req.url == "/url"
    txresp -status 200 -hdr "Date: Wed, 01 Nov 2023 07:48:48 GMT"
} -start

varnish v1 -vcl+backend {
    import std;

    sub vcl_deliver {
        if (req.http.X-reset-date) {
            set resp.http.Date = std.strftime(now, "%a, %d %b %Y %H:%M:%S GMT");
        }
    }
} -start

client cFetch {
    txreq -req "GET" -url "/url"

    rxresp
    expect resp.status == 200
    expect resp.http.Age == "0"
    expect resp.http.Date == "Wed, 01 Nov 2023 07:48:48 GMT"
} -run

varnish v1 -expect client_req == 1
varnish v1 -expect cache_hit == 0
varnish v1 -expect s_fetch == 1

delay 2

client cHitOldDate {
    txreq -req "GET" -url "/url"

    rxresp
    expect resp.status == 200
    expect resp.http.Age != "0"
    expect resp.http.Date == "Wed, 01 Nov 2023 07:48:48 GMT"
} -run

varnish v1 -expect client_req == 2
varnish v1 -expect cache_hit == 1
varnish v1 -expect s_fetch == 1

client cHitNewDate {
    txreq -req "GET" -url "/url" -hdr "X-reset-date: 1"

    rxresp
    expect resp.status == 200
    expect resp.http.Age != "0"
    expect resp.http.Date != "Wed, 01 Nov 2023 07:48:48 GMT"
} -run

varnish v1 -expect client_req == 3
varnish v1 -expect cache_hit == 2
varnish v1 -expect s_fetch == 1

```

### Context

Migration to v7.4 caused some bugs because of unexpected (outdated) `Date` header.

### Varnish Cache version

varnishd (varnish-7.4.1 revision d5a5aa9cc879320840ca467ddbb7df0f99c9ba0f)

### Operating system

debianbookworm

### Source of binary packages used (if any)

https://hub.docker.com/layers/library/varnish/7.4.1/images/sha256-e03566ef6752192c478b1aa7bba603dc26f1ee563934c03f28e9c6a7a5396d59?context=explore

**Comment by linushstge** [comment]
Totally agree with your explanation. I guess this behaviour is a feature and should receive more documentation.
A simple workaround for 7.4 would be setting the date explicit in the `vcl_deliver` subroutine to get applied on uncached and cached responses as well.

```vcl
sub vcl_deliver {
     # RFC-1123 Date, https://datatracker.ietf.org/doc/html/rfc1123
     set resp.http.Date = now;
}
```

**Comment by Dridi** [comment]
I don't think this should specifically be explained in the Varnish documentation, since the semantics of well-known header fields such as `date` are specified by RFCs:

https://www.rfc-editor.org/rfc/rfc9110#name-date

After a quick look at rfc9110, rfc9111 and rfc5322, I must admit I don't know what the correct behavior is.

**Comment by nigoroll** [comment]
This has been discussed during bugwash and at this point we believe that the current behavior of Varnish-Cache is according to the HTTP RFCs. Some references:

[RFC 9110 6.6.1 Date](https://www.rfc-editor.org/rfc/rfc9110#section-6.6.1)

> The "Date" header field represents the date and time at which the message was originated

it goes on to say that servers with a clock MUST generate a `Date` header for most responses, clockless servers MUST NOT and caches must add it if not present. [We do that](https://github.com/varnishcache/varnish-cache/blob/34c87dd2ce90b7b12e49551834d9c6fa00b4c59a/bin/varnishd/cache/cache_fetch.c#L453-L466).

[RFC 9111 4. Constructing Responses from Caches](https://www.rfc-editor.org/rfc/rfc9111#name-constructing-responses-from)

>  When more than one suitable response is stored, a cache MUST use the most recent one (as determined by the Date header field).

This does not directly say that the cache must not create an own Date header, but the requirement only makes sense if the header is the one from the Origin. There is a second sentence with a similar meaning.

[RFC 9111 4.2.3. Calculating Age](https://www.rfc-editor.org/rfc/rfc9111#name-calculating-age)

> The term "date_value" denotes the value of the Date header field [...]

Again, the age calculations only make sense if the header field is that from the origin.
