### ISSUE TITLE
Getting AB mismatch error for reqwest vmod with varnish 7.3.0

### ISSUE THREAD

**Issue by piyush-98** [varnishcache/varnish-cache#4023]
### Expected Behavior

I'm compling varnish from varnish 7.3, steps also include installation of reqwest vmod in a docker container. After runnign the docker container I'm getting an error on the import reqwest line in vcl file.
Incompatible VMOD reqwest
	File name: /usr/lib/varnish/vmods/libvmod_reqwest.so
	ABI mismatch, expected <Varnish 7.3.1 f529d82f892cd4537b8272a18bac6c970be9deb6>, got <Varnish 7.3.0 84d79120b6d17b11819a663a93160743f293e63f>
I have an image which was built few weeks ago and it works pefectly fine with it.

### Current Behavior

import reqwst line is throwing following error
Incompatible VMOD reqwest
	File name: /usr/lib/varnish/vmods/libvmod_reqwest.so
	ABI mismatch, expected <Varnish 7.3.1 f529d82f892cd4537b8272a18bac6c970be9deb6>, got <Varnish 7.3.0 84d79120b6d17b11819a663a93160743f293e63f>

### Steps to Reproduce (for bugs)

[varnish-docker.tar.gz](https://github.com/varnishcache/varnish-cache/files/13414428/varnish-docker.tar.gz)
run follwing commands
sudo docker build -t <image_name> .
sudo docker run --privileged -d --restart always -v /data/etc/varnish:/etc/varnish -v /data/etc/logs:/logs -v /data/etc/storage:/data --network host  --name <container_name> <image_name>
sudo docker logs <container_id>
same error will be reproduced.

### Context

I'm not able to run any container from a new docker image which is a major issue for me.

### Varnish Cache version

varnishd (varnish-7.3.0 revision 84d79120b6d17b11819a663a93160743f293e63f)

### Operating system

Ubuntu 22.04.1 LTS

**Comment by Dridi** [comment]
You need to rebuild it.

Next time, please raise an issue to the vmod_reqwest project first.
