### ISSUE TITLE
vsl-query: floats do not behave as expected

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#4088]
### Expected Behavior

[Comparisons](https://varnish-cache.org/docs/trunk/reference/vsl-query.html#operators) involving [floats](https://varnish-cache.org/docs/trunk/reference/vsl-query.html#operand) should behave as documented:

> * == != < <= > >=
> 
> Numerical comparison. The record contents will be converted to either an integer or a float before comparison, depending on the type of the operand

### Current Behavior

Comparisons fail in unexpected ways

OK:

```
$ varnishlog -r varnishlog.err-20240314 -q 'Timestamp:Process[2] > 84.5 and Timestamp:Process[2] < 85.' -I Timestamp:Process|head -2                                            
*   << Request  >> 337084421 
-   Timestamp      Process: 1710329152.663188 84.677353 0.000041
$ varnishlog -r varnishlog.err-20240314 -q 'Timestamp:Process[2] > 84.6 and Timestamp:Process[2] < 85.' -I Timestamp:Process|head -2    
*   << Request  >> 337084421 
-   Timestamp      Process: 1710329152.663188 84.677353 0.000041
$ varnishlog -r varnishlog.err-20240314 -q 'Timestamp:Process[2] > 84.67 and Timestamp:Process[2] < 85.' -I Timestamp:Process|head -2
*   << Request  >> 337084421 
-   Timestamp      Process: 1710329152.663188 84.677353 0.000041
```

not OK:

```
$ varnishlog -r varnishlog.err-20240314 -q 'Timestamp:Process[2] > 84.677 and Timestamp:Process[2] < 85.' -I Timestamp:Process|head -2
*   << Request  >> 337346562 
-   Timestamp      Process: 1710329152.663282 84.678016 0.000011
```

### Context

```
(gdb) p (double)84.678016
$1 = 84.678016
(gdb) p (float)84.678016
$2 = 84.6780167
(gdb) p (float)84.677
$3 = 84.677002
```

**Comment by nigoroll** [comment]
It looks to me that this is related to use of [SF_Parse_Decimal()](https://github.com/varnishcache/varnish-cache/blob/13fe897fa582661fe075af21aff0e53b3770fcfe/lib/libvarnishapi/vsl_query.c#L215) since 05e10eee3076e4c416ebd460cfa70f4fa8fcdb67.

Questions:

* Are structured field semantics a good fit for vsl queries?
* Even if they were, is the behavior correct? Do I understand correctly that according to [RFC8941](https://www.rfc-editor.org/rfc/rfc8941.html#name-decimals), three digits of the fractional component should be significant without any rounding involved? It looks to me like, in the example, 84.677 got rounded to 84.678 ?

**Comment by bsdphk** [comment]
In retrospect, SF_Parse_Decimal() is too brutal for delta-T values in VSL records.

**Comment by nigoroll** [comment]
from 1:1 conversation with phk: we should probably just use `strtod()` in vsl
