### ISSUE TITLE
varnishtest fails to recognise -D as an option on alpine

### ISSUE THREAD

**Issue by gquintard** [varnishcache/varnish-cache#4090]
### Expected Behavior

`/ # varnishtest foo.vtc  -D x=1` should start the test, setting the `x` macro to 1

### Current Behavior

```
/ # varnishtest foo.vtc  -D x=1
Cannot stat file "-D": No such file or directory
```

### Steps to Reproduce (for bugs)

```docker run -it alpine sh -c "apk add varnish; echo varnishtest > foo.vtc; varnishtest foo.vtc  -D x=1"```

### Context

I was packaging so vmods and stumble onto that one.

### Varnish Cache version

varnishd (varnish-7.5.0 revision eef25264e5ca5f96a77129308edb83ccf84cb1b1)

### Operating system

alpine:3

**Comment by gquintard** [comment]
I toyed a bit with it, and it looks like that `alpine`'s `getopt` wants all the switched before the filenames. So this works:
```
varnishtest -D x= foo.vtc
```

I'll leave that around just in case somebody wants to look at it, but feel free to close.

**Comment by Dridi** [comment]
That's how `getopt()` normally works, have you tried an older build on the same alpine version? It probably got stricter on the alpine side.

**Comment by bsdphk** [comment]
FreeBSD also wants flags before filenames.

**Comment by bsdphk** [comment]
WontFix
