### ISSUE TITLE
Remaining number of seconds to midnight

### ISSUE THREAD

**Issue by Zabrane** [varnishcache/varnish-cache#4107]
### Expected Behavior

I'm trying to calculate the remaining number of seconds till midnight and use it in the `Cache-Control` HTTP header:

```vcl
sub vcl_backend_response {
set resp.http.X-Seconds-To-Midnight = std.integer(duration=std.time(regsub(now, "^(.+?)\d{2}:\d{2}:\d{2}(.+?)$", "\100:00:00\2")) + 1d - now);
 set beresp.http.Cache-Control = "public, max-age=" + resp.http.X-Seconds-To-Midnight + ", must-revalidate";
}
```

### Current Behavior

An error in the VCL when calling `duration`.

### Context

I'm unable to use the function `std.integer(duration=...`

### Varnish Cache version

varnishd (varnish-6.0.13 revision a395739fa63cddec305142eabefec0a4fd5339e7)

### Operating system

Debian GNU/Linux 10 (buster)

**Comment by gquintard** [comment]
Help us here :-) what's the error?

**Comment by Zabrane** [comment]
Hi @gquintard 

My bad, forgot the error message. Here you are:

```bash
-- The job identifier is 4090832.
May 18 16:33:27 XXXX varnishd[29974]: Error:
May 18 16:33:27 XXXX varnishd[29974]: Message from VCC-compiler:
May 18 16:33:27 XXXX varnishd[29974]: Unknown argument 'duration'
May 18 16:33:27 XXXX varnishd[29974]: ('/opt/intershop/eserver1/share/default.vcl' Line 187 Pos 55)
May 18 16:33:27 XXXX varnishd[29974]:     set resp.http.X-Seconds-To-Midnight = std.integer(duration=std.time(regsub(now, "^(.+?)\d{2}:\d{2}:\d{2}(.+?)$", "\100:00:00\2")) + 1d
May 18 16:33:27 XXXX varnishd[29974]: ------------------------------------------------------########-----------------------------------------------------------------------------
May 18 16:33:27 XXXX varnishd[29974]: While compiling function call:
May 18 16:33:27 XXXX varnishd[29974]: ('/opt/intershop/eserver1/share/default.vcl' Line 187 Pos 43) -- (Pos 54)
May 18 16:33:27 XXXX varnishd[29974]:     set resp.http.X-Seconds-To-Midnight = std.integer(duration=std.time(regsub(now, "^(.+?)\d{2}:\d{2}:\d{2}(.+?)$", "\100:00:00\2")) + 1d
May 18 16:33:27 XXXX varnishd[29974]: ------------------------------------------############-------------------------------------------------------------------------------------
May 18 16:33:27 XXXX varnishd[29974]: Running VCC-compiler failed, exited with 2
May 18 16:33:27 XXXX varnishd[29974]: VCL compilation failed
May 18 16:33:27 XXXX systemd[1]: varnish.service: Control process exited, code=exited, status=255/EXCEPTION
-- Subject: Unit process exited
```

**Comment by gquintard** [comment]
Thanks for that. It's just that on 6.0, that option doesn't exist: https://varnish-cache.org/docs/6.0/reference/vmod_generated.html

You will need to either upgrade to something more recent, like [7.5](https://packagecloud.io/varnishcache/varnish75), or use [std.time2integer()](https://varnish-cache.org/docs/6.0/reference/vmod_generated.html#func-time2integer)

**Comment by Zabrane** [comment]
Thanks @gquintard. I gonna try the `std.time2integer()`.

Any reason why `std` vmod wasn't backported to `6.x`?

We were scared a bit to use `7.5` because of the [VSV00014 vulnerability](https://varnish-cache.org/security/VSV00014.html#vsv00014).

**Comment by gquintard** [comment]
7.5 isn't affected, so that's actually a great reason to use it :-)
