### ISSUE TITLE
Should we add Josh's spell-checking?

### ISSUE THREAD

**Issue by nigoroll** [varnishcache/varnish-cache#4165]
> If you would like to pull in check-spelling, you'll want to review the [word list](https://github.com/jsoref/varnish-cache/blob/spell-check/.github/actions/spelling/expect.txt) to see if there are any other items that are also typos (I had missed at least `implicit` and `catastrophe`).

Do we want that? My personal preference would be for tooling which is not github actions, but this is not to be misunderstood as dismissal of the good work please, and also having a github action might be better than nothing at all.

_Originally posted by @jsoref in https://github.com/varnishcache/varnish-cache/issues/4153#issuecomment-2297088357_

**Comment by gquintard** [comment]
Are you again github actions in general, or as the only implementation?

how about making it a `git` hook? This would allow everyone to run it locally while also be usable inside CI

**Comment by nigoroll** [comment]
I am against github in general, and in particular against locking in functionality with it.
Josh's work specifically _is_ a github action. He has documented that [it can be run locally through a github action emulator](https://github.com/check-spelling/check-spelling/?tab=readme-ov-file#running-locally), but not how to run the collection of perl scripts that is the spell checker directly. Which is to say that this sure would be possible, but if not fully supported, I am a bit reluctant of this option...

**Comment by gquintard** [comment]
ah, thanks. Then yes, I'm with you, it should be local first, and runnable in CI second

**Comment by bsdphk** [comment]
For what it's worth, I'm against all (near-)monopolies, including github.
