### ISSUE TITLE
Return fail from vcl_init can only use static string

### ISSUE THREAD

**Issue by stevendore** [varnishcache/varnish-cache#4170]
### Expected Behavior

Be able to return string from a VMOD from `return(fail(...))` from vcl_init.

### Current Behavior

Below is a minimum reproducible VTC. 

```
varnishtest "Return string from VMOD from fail in vcl_init "

varnish v1 -vcl {
	import debug;
	backend default none;
	sub vcl_init {
		return(fail(debug.author()));
	}
} -start
```

The VCC turns the fail line into the below resulting in a compilation error since `VRT_fail` requires either a static string or a fmt and VA ARGS
```
VRT_fail(ctx,
        Vmod_xyzzy_debug_Func.f_author(ctx,
          *Vmod_xyzzy_debug_Func.enum_phk,
          *Vmod_xyzzy_debug_Func.enum_phk
        )
      );
```

### Possible Solution

N/A

### Steps to Reproduce (for bugs)

Run VTC

```
varnishtest "Return string from VMOD from fail in vcl_init "

varnish v1 -vcl {
	import debug;
	backend default none;
	sub vcl_init {
		return(fail(debug.author()));
	}
} -start
```

### Context

Reporting an error from vcl_init in more context.

### Varnish Cache version

varnishd (varnish-trunk revision 08d4e8045502c5c32796c62c6bb2574853a87e12)

### Operating system

Ubuntu 22.04

### Source of binary packages used (if any)

git clone

**Comment by walid-git** [comment]
Thanks for the detailed report. #4171 should fix it.
