### ISSUE TITLE
执行make check 失败

### ISSUE THREAD

**Issue by dabao1990** [varnishcache/varnish-cache#4191]
### Expected Behavior

pass

### Current Behavior

执行make check 失败

### Steps to Reproduce (for bugs)

spack install varnish-cache@7.6.0
cd varnish-cache@7.6.0
make check

### Context

FAIL: tests/v00042
==================

**** dT    0.000
*    top   TEST ./tests/v00042.vtc starting
**** top   extmacro def pkg_version=7.6.0
**** top   extmacro def pkg_branch=7.6
**** top   extmacro def pwd=/home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src/bin/varnishtest
**** top   extmacro def date(...)
**** top   extmacro def string(...)
**** top   extmacro def localhost=127.0.0.1
**** top   extmacro def bad_backend=127.0.0.1:39601
**** top   extmacro def listen_addr=127.0.0.1:0
**** top   extmacro def bad_ip=192.0.2.255
**** top   extmacro def topbuild=/home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src
**** top   extmacro def topsrc=/home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src
**** top   macro def testdir=/home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src/bin/varnishtest/./tests
**** top   macro def tmpdir=/tmp/vtc.351711.2fa35d90
**** top   macro def vtcid=vtc.351711.2fa35d90
**   top   === varnishtest "Make sure we also get separate PRIV_TASK contex...
*    top   VTEST Make sure we also get separate PRIV_TASK contexts in ESI subrequests.
**   top   === server s1 {
**   s1    Starting server
**** s1    macro def s1_addr=127.0.0.1
**** s1    macro def s1_port=37931
**** s1    macro def s1_sock=127.0.0.1:37931
*    s1    Listen on 127.0.0.1:37931
**   top   === varnish v1 -cliok "param.set thread_pool_stack 80k"
**   s1    Started on 127.0.0.1:37931 (1 iterations)
**** dT    0.009
**   v1    Launch
***  v1    CMD: cd ${pwd} && exec varnishd  -d -n /tmp/vtc.351711.2fa35d90/v1 -i v1 -l 2m -p auto_restart=off -p syslog_cli_traffic=off -p thread_pool_min=10 -p debug=+vtc_mode -p vsl_mask=+Debug,+H2RxHdr,+H2RxBody -p h2_initial_window_size=1m -p h2_rx_window_low_water=64k -a '127.0.0.1:0' -M '127.0.0.1 43601' -P /tmp/vtc.351711.2fa35d90/v1/varnishd.pid -p vmod_path=/home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src/vmod/.libs
***  v1    CMD: cd /home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src/bin/varnishtest && exec varnishd  -d -n /tmp/vtc.351711.2fa35d90/v1 -i v1 -l 2m -p auto_restart=off -p syslog_cli_traffic=off -p thread_pool_min=10 -p debug=+vtc_mode -p vsl_mask=+Debug,+H2RxHdr,+H2RxBody -p h2_initial_window_size=1m -p h2_rx_window_low_water=64k -a '127.0.0.1:0' -M '127.0.0.1 43601' -P /tmp/vtc.351711.2fa35d90/v1/varnishd.pid -p vmod_path=/home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src/vmod/.libs
***  v1    PID: 351730
**** v1    macro def v1_pid=351730
**** v1    macro def v1_name=/tmp/vtc.351711.2fa35d90/v1
**** dT    0.033
***  v1    debug|Debug: Version: varnish-7.6.0 revision NOGIT
***  v1    debug|Debug: Platform: Linux,4.18.0-193.el8.aarch64,aarch64,-jnone,-sdefault,-sdefault,-hcritbit
***  v1    debug|200 289
***  v1    debug|-----------------------------
***  v1    debug|Varnish Cache CLI 1.0
***  v1    debug|-----------------------------
***  v1    debug|Linux,4.18.0-193.el8.aarch64,aarch64,-jnone,-sdefault,-sdefault,-hcritbit
***  v1    debug|varnish-7.6.0 revision NOGIT
***  v1    debug|
***  v1    debug|Type 'help' for command list.
***  v1    debug|Type 'quit' to close CLI session.
***  v1    debug|Type 'start' to launch worker process.
***  v1    debug|
**** dT    0.133
**** v1    CLIPOLL 1 0x1 0x0 0x0
***  v1    CLI connection fd = 7
***  v1    CLI RX  107
**** v1    CLI RX|evtlkaxroqaflqjcqtyggmxeppjkqbzo
**** v1    CLI RX|
**** v1    CLI RX|Authentication required.
**** v1    CLI TX|auth 8007874f889c62e23dca43989e439a0f6071e7c4caa82e7dd40bb6f9a0678d9e
***  v1    CLI RX  200
**** v1    CLI RX|-----------------------------
**** v1    CLI RX|Varnish Cache CLI 1.0
**** v1    CLI RX|-----------------------------
**** v1    CLI RX|Linux,4.18.0-193.el8.aarch64,aarch64,-jnone,-sdefault,-sdefault,-hcritbit
**** v1    CLI RX|varnish-7.6.0 revision NOGIT
**** v1    CLI RX|
**** v1    CLI RX|Type 'help' for command list.
**** v1    CLI RX|Type 'quit' to close CLI session.
**** v1    CLI RX|Type 'start' to launch worker process.
**** v1    CLI TX|param.set thread_pool_stack 80k
**** dT    0.178
***  v1    CLI RX  106
**** v1    CLI RX|Must be at least 128k
**** v1    CLI RX|
**** v1    CLI RX|(attempting to set param 'thread_pool_stack' to '80k')
**   v1    CLI 106 <param.set thread_pool_stack 80k>
**** dT    0.188
---- v1    FAIL CLI response 106 expected 200
*    top   RESETTING after ./tests/v00042.vtc
**   s1    Waiting for server (4/-1)
**   v1    Wait
**** v1    CLI TX|panic.show
**** dT    0.234
***  v1    vsl|No VSL chunk found (child not started ?)
**** dT    0.238
***  v1    CLI RX  300
**** v1    CLI RX|Child has not panicked or panic has been cleared
***  v1    debug|Info: manager stopping child
***  v1    debug|Info: manager dies
**** v1    STDOUT EOF
**   v1    WAIT4 pid=351730 status=0x0000 (user 0.005704 sys 0.018605)
*    top   TEST ./tests/v00042.vtc FAILED
#    top  TEST ./tests/v00042.vtc FAILED (0.239) exit=2
FAIL tests/v00042.vtc (exit status: 2)

FAIL: tests/v00043
==================

**** dT    0.000
*    top   TEST ./tests/v00043.vtc starting
**** top   extmacro def pkg_version=7.6.0
**** top   extmacro def pkg_branch=7.6
**** top   extmacro def pwd=/home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src/bin/varnishtest
**** top   extmacro def date(...)
**** top   extmacro def string(...)
**** top   extmacro def localhost=127.0.0.1
**** top   extmacro def bad_backend=127.0.0.1:35263
**** top   extmacro def listen_addr=127.0.0.1:0
**** top   extmacro def bad_ip=192.0.2.255
**** top   extmacro def topbuild=/home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src
**** top   extmacro def topsrc=/home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src
**** top   macro def testdir=/home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src/bin/varnishtest/./tests
**** top   macro def tmpdir=/tmp/vtc.351744.42cae447
**** top   macro def vtcid=vtc.351744.42cae447
**   top   === varnishtest "Test PRIV_TOP"
*    top   VTEST Test PRIV_TOP
**   top   === server s1 {
**   s1    Starting server
**** s1    macro def s1_addr=127.0.0.1
**** s1    macro def s1_port=32769
**** s1    macro def s1_sock=127.0.0.1:32769
*    s1    Listen on 127.0.0.1:32769
**   top   === varnish v1 -errvcl "Not available in subroutine 'vcl_backend...
**   s1    Started on 127.0.0.1:32769 (1 iterations)
**** dT    0.009
**   v1    Launch
***  v1    CMD: cd ${pwd} && exec varnishd  -d -n /tmp/vtc.351744.42cae447/v1 -i v1 -l 2m -p auto_restart=off -p syslog_cli_traffic=off -p thread_pool_min=10 -p debug=+vtc_mode -p vsl_mask=+Debug,+H2RxHdr,+H2RxBody -p h2_initial_window_size=1m -p h2_rx_window_low_water=64k -a '127.0.0.1:0' -M '127.0.0.1 38911' -P /tmp/vtc.351744.42cae447/v1/varnishd.pid -p vmod_path=/home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src/vmod/.libs
***  v1    CMD: cd /home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src/bin/varnishtest && exec varnishd  -d -n /tmp/vtc.351744.42cae447/v1 -i v1 -l 2m -p auto_restart=off -p syslog_cli_traffic=off -p thread_pool_min=10 -p debug=+vtc_mode -p vsl_mask=+Debug,+H2RxHdr,+H2RxBody -p h2_initial_window_size=1m -p h2_rx_window_low_water=64k -a '127.0.0.1:0' -M '127.0.0.1 38911' -P /tmp/vtc.351744.42cae447/v1/varnishd.pid -p vmod_path=/home/stage/root/spack-stage-varnish-cache-7.6.0-6gaz6mjbo6v5s7vpjwjdjd2mjg2a4xdu/spack-src/vmod/.libs
***  v1    PID: 351763
**** v1    macro def v1_pid=351763
**** v1    macro def v1_name=/tmp/vtc.351744.42cae447/v1
**** dT    0.033
***  v1    debug|Debug: Version: varnish-7.6.0 revision NOGIT
***  v1    debug|Debug: Platform: Linux,4.18.0-193.el8.aarch64,aarch64,-jnone,-sdefault,-sdefault,-hcritbit
***  v1    debug|200 289
***  v1    debug|-----------------------------
***  v1    debug|Varnish Cache CLI 1.0
***  v1    debug|-----------------------------
***  v1    debug|Linux,4.18.0-193.el8.aarch64,aarch64,-jnone,-sdefault,-sdefault,-hcritbit
***  v1    debug|varnish-7.6.0 revision NOGIT
***  v1    debug|
***  v1    debug|Type 'help' for command list.
***  v1    debug|Type 'quit' to close CLI session.
***  v1    debug|Type 'start' to launch worker process.
***  v1    debug|
**** dT    0.133
**** v1    CLIPOLL 1 0x1 0x0 0x0
***  v1    CLI connection fd = 7
***  v1    CLI RX  107
**** v1    CLI RX|okljjmcbyejgfhmwrzclntbuuincwafy
**** v1    CLI RX|
**** v1    CLI RX|Authentication required.
**** v1    CLI TX|auth a9ee3fe631604450df9ab8c835ffbdbeb046516f2f426940795f62fe37605034
***  v1    CLI RX  200
**** v1    CLI RX|-----------------------------
**** v1    CLI RX|Varnish Cache CLI 1.0
**** v1    CLI RX|-----------------------------
**** v1    CLI RX|Linux,4.18.0-193.el8.aarch64,aarch64,-jnone,-sdefault,-sdefault,-hcritbit
**** v1    CLI RX|varnish-7.6.0 revision NOGIT
**** v1    CLI RX|
**** v1    CLI RX|Type 'help' for command list.
**** v1    CLI RX|Type 'quit' to close CLI session.
**** v1    CLI RX|Type 'start' to launch worker process.
**** v1    CLI TX|vcl.inline vcl1 << %XJEIFLH|)Xspa8P
**** v1    CLI TX|vcl 4.1;
**** v1    CLI TX|
**** v1    CLI TX|\timport debug;
**** v1    CLI TX|\tbackend be none;
**** v1    CLI TX|\tsub vcl_backend_fetch {
**** v1    CLI TX|\t\tdebug.test_priv_top("only works on client side");
**** v1    CLI TX|\t}
**** v1    CLI TX|
**** v1    CLI TX|%XJEIFLH|)Xspa8P
**** dT    0.138
***  v1    CLI RX  106
**** v1    CLI RX|Message from VCC-compiler:
**** v1    CLI RX|('<vcl.inline>' Line 6 Pos 23) -- (Pos 35)
**** v1    CLI RX|                debug.test_priv_top("only works on client side");
**** v1    CLI RX|----------------------#############------------------------------
**** v1    CLI RX|
**** v1    CLI RX|Not available in subroutine 'vcl_backend_fetch'.
**** v1    CLI RX|Running VCC-compiler failed, exited with 2
**** v1    CLI RX|VCL compilation failed
**   v1    VCL compilation failed (as expected)
***  v1    Found expected string: ("Not available in subroutine 'vcl_backend_fetch'")
**   top   === varnish v1 -errvcl "Not available in subroutine 'vcl_init'" ...
**** v1    CLI TX|vcl.inline vcl2 << %XJEIFLH|)Xspa8P
**** v1    CLI TX|vcl 4.1;
**** v1    CLI TX|
**** v1    CLI TX|\timport debug;
**** v1    CLI TX|\tbackend be none;
**** v1    CLI TX|\tsub vcl_init {
**** v1    CLI TX|\t\tdebug.test_priv_top("only works on client side");
**** v1    CLI TX|\t}
**** v1    CLI TX|
**** v1    CLI TX|%XJEIFLH|)Xspa8P
**** dT    0.190
***  v1    CLI RX  106
**** v1    CLI RX|Message from VCC-compiler:
**** v1    CLI RX|('<vcl.inline>' Line 6 Pos 23) -- (Pos 35)
**** v1    CLI RX|                debug.test_priv_top("only works on client side");
**** v1    CLI RX|----------------------#############------------------------------
**** v1    CLI RX|
**** v1    CLI RX|Not available in subroutine 'vcl_init'.
**** v1    CLI RX|Running VCC-compiler failed, exited with 2
**** v1    CLI RX|VCL compilation failed
**   v1    VCL compilation failed (as expected)
***  v1    Found expected string: ("Not available in subroutine 'vcl_init'")
**   top   === varnish v1 -cliok "param.set thread_pool_stack 80k"
**** v1    CLI TX|param.set thread_pool_stack 80k
**** dT    0.234
***  v1    vsl|No VSL chunk found (child not started ?)
**** dT    0.236
***  v1    CLI RX  106
**** v1    CLI RX|Must be at least 128k
**** v1    CLI RX|
**** v1    CLI RX|(attempting to set param 'thread_pool_stack' to '80k')
**   v1    CLI 106 <param.set thread_pool_stack 80k>
**** dT    0.246
---- v1    FAIL CLI response 106 expected 200
*    top   RESETTING after ./tests/v00043.vtc
**   s1    Waiting for server (4/-1)
**   v1    Wait
**** v1    CLI TX|panic.show
**** dT    0.305
***  v1    CLI RX  300
**** v1    CLI RX|Child has not panicked or panic has been cleared
**** dT    0.306
***  v1    debug|Info: manager stopping child
***  v1    debug|Info: manager dies
**** v1    STDOUT EOF
**** dT    0.334
***  v1    vsl|No VSL chunk found (child not started ?)
**   v1    WAIT4 pid=351763 status=0x0000 (user 0.012784 sys 0.020556)
*    top   TEST ./tests/v00043.vtc FAILED
#    top  TEST ./tests/v00043.vtc FAILED (0.334) exit=2
FAIL tests/v00043.vtc (exit status: 2)

### Varnish Cache version

7.6.0

### Operating system

centos8

**Comment by dridi** [comment]
This looks like the same problem as #4188, let's move the discussion there.
