### ISSUE TITLE
`mlock() of VSM failed: Out of memory (12)` in Kubernetes/container environment

### ISSUE THREAD

**Issue by kaiburjack** [varnishcache/varnish-cache#4193]
### Expected Behavior

We are operating Varnish in a GKE/Kubernetes 1.30 environment.

After upgrading from Varnish 7.5.0 to Varnish 7.6.0, we are seeing the warning [that is pointed out by the upgrade guide](https://varnish-cache.org/docs/7.6/whats-new/upgrading-7.6.html#warning-about-failed-memory-locking).
However, in our setup, the memory used by Varnish is definitely backed by physical/RAM memory and never swapped out, since the Kubernetes nodes don't have a SWAP file system.
Concretely, we are starting Varnish with `-n /somedir` where `/somedir` is a volumeMount for an emptyDir volume with medium="Memory", so it is a tmpfs volume. `df` also says that this particular volume/mount is only using 1% of its available space, so there is also no space problem.
Also, as a security best practices measure, we are instruction Kubernetes to drop all Linux capabilities of the Varnish container and don't run Varnish as root/privileged user and disallow privilege escalation.

I think, in such an environment, this warning is not actionable and should therefore probably not be issued.

### Current Behavior

Currently, when Varnish starts up, it issues the warning:
```
Info: Child (25) said Warning: mlock() of VSM failed: Out of memory (12)
```

### Steps to Reproduce (for bugs)

1. Run Varnish 7.6.0 in a container environment like Kubernetes (in our case GKE 1.30)
2. Observe the above mentioned warning message

With Docker, the simplest reproduction would be:
```
docker run --rm --tmpfs /tmp:exec --name varnish varnish:7.6.0-alpine -n /tmp/workdir
```
It is not 100% equivalent to what containerd would do in our Kubernetes, but it also exhibits the problem. To come closer to the Kubernetes environment (at least for the Linux caps drops part), the docker command would probably be:
```
docker run --cap-drop=all --rm --tmpfs /tmp:exec --name varnish varnish:7.6.0-alpine -n /tmp/workdir
```

### Context

The issue does not seem to affect the working Varnish instances in any way.
Our Varnish instances perform admirably at absolute peak performance handling many thousands of requests per second and we don't see any performance degradation at all.
It's just that the warning message issued is confusing and likely not actionable in a container/Kubernetes environment.

### Varnish Cache version

varnish-7.6.0 revision ed1243ca162a7b1d975bc0332f0d66d33f0bc78e

### Operating system

Linux Alpine 3.19 (Kernel Version 6.1.90)

### Source of binary packages used (if any)

https://hub.docker.com/_/varnish

**Comment by kaiburjack** [comment]
Tagging @gquintard , as per request in our Discord discussion. :)

**Comment by nigoroll** [comment]
bugwash: do something sensible with this ticket

**Comment by kaiburjack** [comment]
@nigoroll thanks for your answer and the reference to the Kubernetes GitHub issue.
I don't think we could do anything about the environment, actually, without resorting to some hacks that were proposed elsewhere like having a privileged DaemonSet pod that sets ulimit on the host and then probably also run Varnish as a privileged user to the ulimit also for this cgroup? Not sure what ulimit actually is, whether that is "namespaced" in Linux.

Would it not also be possible to introduce a Varnish property like "dont-complain-about-mlock-and-ulimit=true" that we could _explicitly_ set in such environments?

**Comment by nigoroll** [comment]
> In my opinion, any behavioural change should always be revertable/guarded by a flag.

Yes, I would think that we do follow this principle. Yet this is absolutely no behavioral change, this is a warning which you could simply ignore.
If really knowledge about resource controls got lost in the k8s world, that is unfortunately, but really nothing we as a project should be concerned with. As a user, you should not need to revert to hacks like a privileged pod just to use `mlock()`, and by the way, virtual memory exists for a reason and <rant>just because some people in the linux world think the oom killer was the greatest thing since the invention of sliced bread does not make it any better</rant>.
Anyway, this is nothing personal, I will try to come up with something.

**Comment by kaiburjack** [comment]
> Yet this is absolutely no behavioral change, this is a warning which you could simply ignore.

Sorry, by "behavioural" change I meant, that this changes how Varnish "behaves", if we also include "which log messages Varnish emits" as part of the definition of "behaviour" - in which case it _is_ a behavioural change, because the _observable behaviour_ of Varnish does change: It emits a log message which it did not do before.

I would really like for some parameter (whose default is `false` of course) to either:
- disable that Varnish tries to do mlock() in the first place; or
- disable that Varnish emits even a warning about this failing (as was the "baviour" in 7.5.0)

**Comment by nigoroll** [comment]
I hope to have added/proposed relevant changes to varnishd and packaging (see references above) to avoid this warning for everyone but container users. For container and Kubernetes users, I have added documentation with commit 82ab4ec6b08e085f912d238d84555fc2a633611a, available online at https://varnish-cache.org/docs/trunk/reference/vsm.html#warning-mlock-of-vsm-failed

I strongly believe that suppressing the warning, even optionally, is not the best idea, because environments differ, such suppression usually makes the rounds and sometimes even finds its way into "best practice" configurations. So we _really_ should tackle this at the root.

**Comment by kaiburjack** [comment]
Many thanks for your quick and elaborate answers and your work on this!

**Comment by theozaurus** [comment]
We managed to get this working on our Kubernetes environment with help from this thread, further info here: https://medium.com/@thejasongerard/resource-limits-mlock-and-containers-oh-my-cca1e5d1f259 and making a new docker image:

```
FROM varnish:7-alpine
USER root
RUN apk add libcap
RUN setcap cap_ipc_lock=+ep /usr/sbin/varnishd
USER varnish
```

While also setting this on the containers configuration.

```
securityContext:
  capabilities:
    add:
      - IPC_LOCK
```

**Comment by theozaurus** [comment]
@dridi I think so.

From the [mlock(2) man page](https://linux.die.net/man/2/mlock):

> **Limits and permissions**
>
> In Linux 2.6.8 and earlier, a process must be privileged (CAP_IPC_LOCK) in order to lock memory and the RLIMIT_MEMLOCK soft resource limit defines a limit on how much memory the process may lock.
>
> Since Linux 2.6.9, no limits are placed on the amount of memory that a privileged process can lock and the RLIMIT_MEMLOCK soft resource limit instead defines a limit on how much memory an unprivileged process may lock. 

So adding the capability on the executable means that if the right security context is passed as well any limit set by RLIMIT_MEMLOCK is ignored, allowing varnish to get what it needs. This was important for us when running on our Kubernete's cluster as setting RLIMIT_MEMLOCK isn't well supported: https://github.com/kubernetes/kubernetes/issues/3595
