### ISSUE TITLE
Assert error in vwe_thread(), waiter/cache_waiter_epoll.c line 108:

### ISSUE THREAD

**Issue by Mr-Bunyip** [varnishcache/varnish-cache#4227]
### Expected Behavior

Varnish does not panic.

### Current Behavior

Hello,
Under production loads we saw a similar error to [4204](https://github.com/varnishcache/varnish-cache/issues/4204) but referencing line 108.
The [patch](https://github.com/varnishcache/varnish-cache/commit/f9672b3b4612354a805e6426643b0c1724fb0cf1) released for 4204 does not appear to have addressed this case.

```
Assert error in vwe_thread(), waiter/cache_waiter_epoll.c line 108:
  Condition((vwe->nwaited) != 0) not true.
version = varnish-7.6.0 revision ed1243ca162a7b1d975bc0332f0d66d33f0bc78e, vrt api = 20.0
ident = Linux,6.8.0-47-generic,x86_64,-jlinux,-smalloc,-sdefault,-hcritbit,epoll
now = 9269.140145 (mono), 1730299631.113412 (real)
Backtrace:
  0x5db85ab6dfb4: /usr/sbin/varnishd(VBT_format+0x74) [0x5db85ab6dfb4]
  0x5db85aae962d: /usr/sbin/varnishd(+0x6062d) [0x5db85aae962d]
  0x5db85ab6d54c: /usr/sbin/varnishd(VAS_Fail+0x4c) [0x5db85ab6d54c]
  0x5db85ab4a69c: /usr/sbin/varnishd(+0xc169c) [0x5db85ab4a69c]
  0x75323929ca94: /lib/x86_64-linux-gnu/libc.so.6(+0x9ca94) [0x75323929ca94]
  0x753239329c3c: /lib/x86_64-linux-gnu/libc.so.6(+0x129c3c) [0x753239329c3c]
errno = 104 (Connection reset by peer)
```

### Context

Varnish panics under production load

### Varnish Cache version

Varnish 7.6

### Operating system

Unbuntu 2404

### Source of binary packages used (if any)

packagecloud.io/varnishcache

**Comment by nigoroll** [comment]
The root cause should be the same also for this assertion failure. Please reopen if you see this with [7.6.1](https://varnish-cache.org/releases/rel7.6.1.html#rel7-6-1) or more recent code.
